export const LocationPrefixRegEx: RegExp[] = [
  new RegExp(/\b(?<![,\\\/])(?:[1-9]\d{0,3}\-)?[1-9]\d{0,3}[a-h]?(?=\s[a-z]{2,})/, "gmi")
];

export const LocationMidfixRegEx: RegExp[] = [
  new RegExp(/\band\b/, "gmi"),
  new RegExp(/\bfor\b/, "gmi"),
  new RegExp(/\bof\b/, "gmi"),
  new RegExp(/\bof\sthe\b/, "gmi"),
  new RegExp(/\bon\b/, "gmi"),
  new RegExp(/\b[io]n\sthe\b/, "gmi"),
  new RegExp(/\bthe\b/, "gmi"),
  new RegExp(/\-y\-/, "gmi")
];

const a: RegExp[] = [
  /\bP\.?O\.?\sBox\s\d+\b/gmi,
  /\b(?:apartment|block|suite|unit)\s(?:\d\w?|\d\d?|\w\d?)\b|\b\d+(st|nd|rd|th)\sFloor\b/gmi,
  /\-on\-sea\b/gmi,
  /\-on\-the\-wall\b/gmi,

  /\babdication\swood\b/gmi,
  /\babundant\sgrace\b/gmi,
  /\baccommodation\s(?:lane|road)\b/gmi,
  /\bacquaintance\shill\b/gmi,
  /\badjuncts\scovert\b/gmi,
  /\badjustment\s(?:bottom|ground)\b/gmi,
  /\badmin\s(?:building|road)\b/gmi,
  /\badventure\s(?:lane|place)\b/gmi,
  /\badventurers?\s(?:drove|fen|land|quay|way)\b/gmi,
  /\baggravation\swood\b/gmi,
  /\baggregate\swalk\b/gmi,
  /\bagony\spoint\b/gmi,
  /\ball\ssaints\b/gmi,
  /\baircraft\s(?:esplanade|way)\b/gmi,
  /\b(?:Hairy|Little|The)\sArm\b/gm,
  /\b(?:barge|boshboil|east|holcot|loch|nan|peel|sandwell|walgrave|west)\sarm\b/gmi,
  /\barm\s(?:north|lane|road)\b/gmi,
  /\b(?:east|glyne|west)\sascent\b/gmi,
  /\bassociation\s(?:road|street|way)\b/gmi,
  /\bback\so['f]?\sthe\sworld\b/gmi,
  /\bbleaching\s(?:hill|rocks)\b/gmi,
  /\bbrother\s(?:hills|isle|loch)\b/gmi,
  /\bbusiness\s(?:centre|court|park)\b/gmi,
  /\bcabinet\s(?:close|way|wood)\b/gmi,
  /\bcoesau[\s\-]whips\b/gmi,
  /\bcommonwealth\s(?:avenue|close|drive|road|view|way)\b/gmi,
  /\bdefence\s(?:academy|close|street)\b/gmi,
  /\bholy\sfamily\b/gmi,
  /\bFamily\s(?:hub|pond|school)\b/gm,
  /\bSixth\sForm\b/gm,
  /\bframe\s(?:green|heath|lane|wood)\b/gmi,
  /\b(?:devil'?s?)frying\span\b/gmi,
  /\bfrying\span\spond\b/gmi,
  /\bfunny[\s\-]shaped\swood\b/gmi,
  /\bgovernors?\s(?:drive|close|marsh|mews|road|wood|yard)\b/gmi,
  /\bheight\sof\sthe\sworld\b/gmi,
  /\b(?:cove\ship|hip\s(?:crescent|lane|walk))\b/gmi,
  /\bhockey\s(?:close|fields|hill)\b/gmi,
  /\bheol\shurricane\b/gmi,
  /\bhurricane\s(?:avenue|close|court|drive|gate|grove|place|road|way|wood)\b/gmi,
  /\bknees?\shill\b/gmi,
  /\bknee\sof\b/gmi,
  /\b(?:The|Muckle|Snickert)\sKnees?\b/gm,
  /\bice\s(?:cleugh|drove|hill|house|pond|street)\b/gmi,
  /\bloading\s(?:bay|hope)\b/gmi,
  /\bmetal\s(?:box\sway|bridge|street)\b/gmi,
  /\bnormal\s(?:avenue|terrace)\b/gmi,
  /\bnutshell\slane\b/gmi,
  /\bplatform\s(?:\d+|drive|road|street)\b/gmi,
  /\bpolice\s(?:convalescent|drive|lane|pit|road|row|square|station|street)\b/gmi,
  /\bporpoise\shill\b/gmi,
  /\bporridge\s(?:bottom|cairn|green|pot\salley)\b/gmi,
  /\bpublic\s(?:hall|garden|park|wood)\b/gmi,
  /\bobserver\s(?:close|court|drive|point|way)\b/gmi,
  /\boccupation\s(?:close|gardens|lane|road|street|wood)\b/gmi,
  /\bonward\s(?:street|way)\b/gmi,
  /\bpresident\s(?:drive|place|plantation|road|street|way)\b/gmi,
  /\breform\s(?:beach|place|road|row|street|strip)\b/gmi,
  /\breformatory\scollege\b/gmi,
  /\brocking\s(?:moor|stone)\b/gmi,
  /\bskating\spond\b/gmi,
  /\bswinging\sbasin\b/gmi,
  /\btaxi\sway\b/gmi,
  /\bteapot\s(?:bank|corner|hill|lane|street)\b/gmi,
  /\btearing\sledge\b/gmi,
  /\btechnical\s(?:college|street)\b/gmi,
  /\btechnology\s(?:avenue|building|close|college|drive|road)\b/gmi,
  /\btime\s(?:park|square)\b/gmi,
  /\btradesman\swalk\b/gmi,
  /\btrainers\sbrae\b/gmi,
  /\btransforming\sstation\b/gmi,
  /\btransport\s(?:avenue|lane|plantation|road)\b/gmi,
  /\btripping\sgreen\b/gmi,
  /\bThe\s(?:Waterwheel)\b/gm,
  /\bunnamed\s(?:rd|road)\b/gmi,
  /\buniversity\s(?:academy|avenue|barns|boulevard|campus|center|centre|close|college|court|crescent|drive|farm|garden|hospital|house|parks?|parkway|place|quays|road|street|terrace|walk|way|wood)\b/gmi,
  /\bwaterwheel\s(?:close|court|lane|rise|way)\b/gmi,
  /\bwatery\s(?:bottom|brake|close|combe|dyke|gate|geo|grove|haven|hill|knowe|lane|marsh|orchard|pots|road|street|way|wood)\b/gmi,
  /\bwealth\s(?:hole|of\swaters)\b/gmi,
  /\bweeping\s(?:cross|elm)\b/gmi,
  /\bwelfare\s(?:avenue|close|crescent|park|road|view)\b/gmi,
  /\b(?:four|the)\swindings\b/gmi,
  /\bwhisky\spot\b/gmi,
  /\bwildlife\s(?:walk|way)\b/gmi,
  /\bwindfall\s(?:court|way|wood)\b/gmi,
  /\bwildflowers?\s(?:close|crescent|drive|grove|meadow|way)\b/gmi,
  /\bwindings\sroad\b/gmi,
  /\bwooded\sclose\b/gmi,
  /\bworld\s(?:end|way|wood)\b/gmi,
  /\byouth\s(?:close|wood)\b/gmi,
  /\bzone\spoint\b/gmi
];
const LocationRegEx: Set<RegExp> = new Set();
a.forEach(term => LocationRegEx.add(term));
export {
  LocationRegEx
};