export const NameSetJoinOnly: Set<string> = new Set([
  "academy",       // placenames (1k+)
  "avenue",        // placenames (1k+)
  "bank",          // placenames (1k+)
  "bay",           // placenames (1k+)
  "bottom",        // placenames (1k+)
  "bridge",        // placenames (1k+)
  "castle",        // placenames (885)
  "catholic",      // placenames (1k+)
  "church",        // placenames (1k+)
  "cl",
  "common",        // placenames (1k+)
  "copse",         // placenames (1k+)
  "courtyard",     // placenames (60)
  "crescent",      // placenames (1k+)
  "cross",         // placenames (1k+)
  "dr",
  "drive",         // placenames (1k+)
  "farm",          // placenames (1k+)
  "field",         // placenames (1k+)
  "garden",        // placenames (433)
  "gardens",       // placenames (1k+)
  "gate",          // placenames (1k+)
  "geo",           // placenames (1k+)
  "grange",        // placenames (1k+)
  "grove",         // placenames (1k+)
  "jr",            // first name
  "lane",          // placenames (1k+)
  "little",        // placenames (1k+)
  "lodge",         // placenames (946)
  "long",          // placenames (1k+)
  "manor",         // placenames (803)
  "mill",          // placenames (1k+)
  "moor",          // placenames (1k+)
  "mr",
  "mrs",
  "ms",
  "old",           // placenames (1k+)
  "park",          // placenames (1k+)
  "plantation",    // placenames (1k+)
  "pond",          // placenames (1k+)
  "port",          // placenames (1k+)
  "rd",
  "sea",           // placenames (189)
  "sir",           // placenames (214)
  "spinney",       // placenames (1k+)
  "spinneys",      // placenames (37)
  "street",        // placenames (1k+)
  "sub",           // placenames (32)
  "wall",          // placenames (188)
  "wood"           // placenames (1k+)
]);