export const NameSetJoinOnly: Set<string> = new Set([
  "academy",       // placenames (1k+)
  "avenue",        // placenames (1k+)
  "back",          // placenames (1k+)
  "bank",          // standalone & placenames (1k+)
  "bay",           // placenames (1k+)
  "bottom",        // placenames (1k+)
  "bridge",        // placenames (1k+)
  "catholic",      // placenames (1k+)
  "close",         // placenames (1k+)
  "college",       // placenames (1k+)
  "common",        // placenames (1k+)
  "community",     // placenames (1k+)
  "copse",         // placenames (1k+)
  "court",         // placenames (1k+)
  "crescent",      // placenames (1k+)
  "cross",         // placenames (1k+)
  "down",          // placenames (1k+)
  "drive",         // placenames (1k+)
  "east",          // placenames (1k+)
  "end",           // placenames (1k+)
  "farm",          // placenames (1k+)
  "field",         // surname & placenames (1k+)
  "garden",        // placenames (433)
  "gardens",       // placenames (1k+)
  "gate",          // placenames (1k+)
  "geo",           // placenames (1k+)
  "high",          // placenames (1k+)
  "new",           // placenames (1k+)
  "old",           // placenames (1k+)
  "plantation",    // placenames (1k+)
  "sea",           // placenames (189)
  "wall",          // placenames (188)
  "wood"           // placenames (1k+)
]);