/**
 * @link https://en.wikipedia.org/wiki/list_of_contemporary_ethnic_groups
 */
export const ethnicity: string[] = [
"a-hmao", "azorean", "andalusian", "asturian", "aragonese", "arain", "assiniboine", "argentine", "awan", "angolan", "aranese", "auvergnat", "arsi", "angami", "alibamu", "amoltepec", "awakatek", "akatek", "achi", "ambalavasi", "antaifasy", "antemoro", "antaisaka", "antambahoaka", "antankarana", "antanosy", "arusha", "aukstaitian", "abayudaya", "ababda", "abazin", "abbé", "abbe", "abidji", "abkhazian", "acehnese", "acholi", "adjarian", "adjoukrou", "adygean", "afar", "afemai", "african", "afrikaner", "afshar", "agaw", "aguri", "ahafo", "ahanta", "ahom", "aimaq", "aimol", "aizi", "aja", "akan", "akha", "akhdam", "akuapem", "akwamu", "akyem", "al balushi", "alawite", "albanian", "albayanon", "algerian", "alur", "alsatian", "amarar", "ambonese", "ambundu", "american", "amhara", "amis", "amish", "anaang", "anatri", "andorran", "aneuk jamee", "angolar", "angkola", "antiguan", "anyi", "anuak", "aowin", "apache", "arab", "arbëreshë", "arbereshe", "argobba", "armeno-tat", "armenian", "aromanian", "arpitan", "aruban", "arvanite", "ashanti", "asho", "askani", "assin", "assyrian", "atoni", "atikamekw", "attie", "atyap", "austrian", "australian", "avar", "avatime", "avikam", "awadhi", "awi", "awjila", "aymara", "ayrum", "azerbaijani", "aro", "anioma", "apulian", "abruzzan", "ashkenazim", "athpare",
"bagdi", "banjara", "bolivian", "brazilian", "boran", "barentoo", "bedaria", "bulungan", "bhoi", "bruneian", "berau", "betsileo", "betsimisaraka", "bezanozano", "bara", "bakhtiari", "boyanese", "bukusu", "bajalan", "bété", "baggara", "bahamian", "bahnar", "bahraini", "bai", "baidya", "baishya", "bakossi", "bali aga", "balangao", "bontoc", "bille", "basilicatan", "boyanese", "banyumasan", "bukharan", "berber", "bahun", "badi", "bantawa", "bahing", "barthélemoise", "batsbi", "baltic", "baria", "balinese", "balanta", "balti", "bajkani", "bakati", "balkar", "baloch", "bamar", "bambara", "bamileke", "bamum", "banda", "bangulzai", "banjarese", "baoulé", "baoule", "barazani", "barbadian", "barbudan", "barda", "barhai", "bari", "bariba", "barujibi", "bashkir", "basque", "bassa", "baster", "batak", "bauri", "bawm", "bayat", "bedouin", "beja", "balearic", "belarusian", "belizean", "bemba", "bembe", "beni-amer", "bengali", "berber", "berom", "berta", "betawi", "beti", "bhadralok", "bhagalia", "bhil", "bhilala", "bharwad", "bhambi", "bhoi", "bhojpuri", "bhumij", "bhurgari", "biatah", "biate", "bicolano", "bidayuh", "bilala", "bilen", "bimoba", "bishari", "bishnupriya", "bissa", "blaan", "boa", "bodo", "boer", "bohemian", "bohra", "bolivian", "bonairian", "bosniak", "bosnian", "botswanan", "bouyei", "bozo", "braber", "brahmin", "brahui", "brazilian", "breton", "brong", "bru", "budu", "buduma", "buginese", "bugti", "bukar sadong", "buledi", "bulgarian", "burgundian", "burmese", "bunjevci", "burusho", "butonese", "bwa",
"caldoche", "comorian", "cuban", "chilean", "castilian", "cantabrian", "carinthian", "cossack", "cape verdean", "coushatta", "cuicatecs", "chonyi", "ch'ol", "chontal", "chilean", "chuj", "ch'orti", "cook islander", "cantonese", "cappadocian", "carib", "catandunganon", "catalan", "cayman", "chakma", "charan", "chakosi", "chaldean", "cham", "chamorro", "chandio", "chaoui", "chaudhri", "chechen", "chenoua", "cherepon", "cherkes", "cherkesogai", "cherokee", "chewa", "chiricahua", "chiriguano", "choctaw", "chokwe", "cayuga", "calabrian", "campanian", "cirebonese", "cochin", "chhetri", "chunaru", "chutiya", "chuanqing", "chuukese", "chuvash", "circassian", "colognian", "comorian", "copt", "cornish", "corsican", "cree", "creole", "croat", "csango", "curaçaoan", "curacaoan", "cuyunon", "cypriot", "czech", 
"dagaaba", "dominican", "dakota", "debri", "donyi-polo", "digo", "dhangar", "dheevara", "dusun", "dumpas", "damai", "dagomba", "damara", "damor", "dane", "danish", "danu", "dargin", "darzada", "dayak", "dehwar", "deori", "dhofari", "dholi", "dinka", "dodai", "dogon", "dogra", "dombki", "dominiquai", "dominican", "doms", "dongxiang", "druze", "dubla", "dungri", "dutch", "dyula", 
"ebira", "ecuadorian", "eleme", "eket", "ezhava", "edda", "ekpeye", "etche", "ezaa", "engenni", "edo", "efik", "efutu", "egun", "egyptian", "ekoi", "emai", "emberá", "emirati", "english", "esan", "estonian", "evalue",
"fang", "feyli", "fante", "fijian", "finn", "finnish", "firozkohi", "flemish", "fon", "franconian", "french", "frisian", "friulian", "fujianese", "fula", "fulakunda", "fulfulde", "fuzhounese",
"ga-adangbe", "gurjar", "gascon", "ghulfan", "giriama", "gozitan", "grebo", "gandarbha", "gabol", "gagauz", "galician", "gametia", "ganda", "gandhabanik", "gaoshan", "garasia", "garifuna", "garo", "gayonese", "gbagyi", "gbaya", "gedeo", "gelao", "georgian", "german", "gha-mu", "ghanaian", "ghanchi", "ghazini", "gheg", "ghomara", "ghoti", "giáy", "goffal", "gola", "gondi", "gonja", "gorontaloan", "greek", "griko", "griqua", "groning", "guan", "guaraní", "guianese", "gurage", "gujarat", "gurunsi", "gujarati", "gurma", "gumuz", 
"hadendoa", "hitchiti", "huastecan", "huilliche", "hemba", "hainan", "hadhrami", "hadiya", "hainanese", "haitian", "hakka", "han", "hani", "harari", "haratin", "hari", "hausa", "hawaiian", "hayhurum", "hazara", "hebei", "hedareb", "hemshin", "hejazi", "herero", "hessian", "hmar", "hmong", "hoa", "hoklo", "hongkonger", "houara", "hui'an", "hui", "hutu", "hungarian", "huli", "hunanese", "hunsrik", "hutterite",
"ijaw", "ixil", "itza", "idakho", "isukha", "izhma komi", "italian", "itawes", "israeli", "ida'an", "ibani", "ilocano", "ingush", "inuit", "inuvialuit", "inuktitut", "inughuit", "iranun", "irish", "irish traveller", "iroquoi", "isan", "iban", "ibibio", "icelander", "idoma", "igbo", "ika", "ikwerre", "ikwo", "isu", "izzi", "igede", "igorot", "ibaloi", "ifugao", "isnag", "iñupiat", "isoko", "ibanag", "indian", "indonesian", "ika", "innu", "intha", "iranian", "iraqi", 
"ja'alin", "jagoi", "jakaltek", "japanese", "jeju islander", "jarai", "javanese", "jew", "jewish", "juhurim", "jingpo", "jola", "jukun", "jalon", "jalia", "jamaican", "jamali", "jamshidi", "janjevci", "jangkang", "japanese", "jasz", "jatoi", "javakheti", "jerbi", "jhalawan", "jicarilla", "jianghuai", "jordanian",  
"kabye", "kichepo", "kachhi", "khatri", "kristang", "kadaru", "karko", "kheng", "kaqchikel", "k'iche", "kunbi", "kelantanese", "knanaya", "kedahan", "kwavi", "kabras", "khayo", "kisa", "kursenieki", "kisan", "kurmanji", "kuwaa", "krahn", "kunama", "korean", "kuteb", "kyrgyz", "kurukh", "kurd", "kposo", "kru", "kpelle", "korean", "kumyk", "konso", "konjo", "kongo", "konkani", "kofyar", "komi", "kalanguya", "kalinga", "kankanaey", "kalabari", "kula", "kalaallit", "krymchak", "kadazan-dusun", "kadazan", "kwijau", "kalanga", "kalenjin", "keiyo", "kipsigi", "kalinago", "kamba", "kanak", "kannadiga", "kanuri", "kanembu", "kapampangan", "kapsiki", "karachay", "karakalpak", "karbi", "kashmiri", "kashubian", "kazakh", "kami", "khmer", "khonds", "khorasani", "kikuyu", "kilba", "kirati", "kulung", "kirat mundhum", "kissi", "kabyle", "kabardian", "kaibarta", "kakwa", "kalmati", "kansabanik", "kapali", "karabakhi", "karadaghi", "karmakar", "karo", "kassena", "katanga", "kataria", "kayastha", "kembayan", "kendayan", "kenyan", "kharva", "khalpa", "khetran", "khoja", "kimbundu", "kipchak", "kist", "koireng", "koli", "kom", "kosovar", "koya", "krashovani", "küresünni", "kuku", "kluet", "kunara", "kuresunni", "kuwaiti", "kven", "kyode",
"lamba", "leonese", "lakota", "lipovan", "languedocien", "lotha", "lomwe", "lacandon", "luxembourger", "lurs", "luo", "luhya", "lulua", "luba", "lietuvninkai", "lithuanian", "lisu", "limba", "lezgins", "lega", "laz", "latgalian", "latvian", "lamaholot", "lao", "lak", "lari", "luso-indian", "lazian", "lombard", "lotud", "limbu", "lampung", "lamkang", "langhani", "lango", "laotian", "lara", "lashkrani", "lebanese", "liberian", "libyan", "liechtensteiner", "lipan", "lohana", "loharani", "lorrainer", "luapula", "lund", "lushai",
"m'bato", "mursi", "moldovan", "marma", "mahyavanshi", "marwari", "meena", "madeiran", "mozambican", "macanese", "macha", "midob", "mtwara", "mwera", "musgum", "mossi", "miccosukee", "muscogee", "murut", "mahali", "munda", "munanese", "mumuye", "mordvin", "moksha", "mongo", "montenegrin", "mongondow", "mongol", "mixtec", "mixe", "mising", "miskito", "minangkabau", "minahasan", "mijikenda", "miꞌkmaq", "mien", "mende", "meitei", "melanau", "mehri", "mbaka", "mazatec", "mazahua", "motozintlecos", "mopan", "maya", "masalit", "masa", "mari", "mahar", "maratha", "marathi", "maranao", "mestizo", "māori", "mapuche", "manggarai", "manjak", "mandinka", "mandarese", "manchu", "mambila", "maltese", "mahl", "maldivian", "mappila", "malayali", "musi", "malay", "mahafaly", "makoa", "mikea", "merina", "malagasy", "makua", "machinga", "makonde", "makassarese", "maithil", "magar", "maguindanao", "magahi", "mafa", "madurese", "madi", "mijak", "macedonian", "maasai", "marama", "marachi", "maragoli", "mayombe", "mbaise", "mgbo", "mohawk", "marchigiano", "monégasque", "molisan", "malaysian", "mizrahim", "moroccan", "mangka'ak", "maragang", "minokok", "marakwet", "maasina", "macanese", "macedonian", "madhya pradesh", "maghreb", "maharastra", "mahishya", "makrani", "mal", "malay", "malagasy", "mandaean", "mandja", "mandari", "mandailing", "manipuri", "maore", "maronite", "marri", "matmata", "mauritian", "mauritanian", "mavchi", "mazari", "meena", "mengal", "mengal", "mescalero", "mennonite", "meskhetian", "mestizo", "métis", "mewasi", "mestizo", "mingrelian", "mirali", "mizo", "molise", "momna", "moroccan", "moravian", "mozabite", "mru", "mrucha", "mualang", "mugheri", "mullazai", "muria",
"nafusi", "nakota", "nakoda", "nyishi", "nuristani", "nùng", "nuer", "nubian", "norwegian", "nogais", "nias", "ngbandi", "ngalop", "ngaju", "newar", "navajo", "nama", "nahua", "nagpuri", "naga", "natchez", "nair", "nandi", "nepalese", "ngwa", "nri-igbo", "nkoro", "nkoroo", "nunavik", "nunatukavut", "neapolitan", "nambya", "nyole", "nguni", "northern ndebele", "ngái", "najdi", "namasudra", "namibian", "naskapi", "ningbonese", "nirdhi", "norman", "nothazai", "nuna", "nyadu", "nyangwara", "nzema",
"omani", "orcadians", "ovimbundu", "ovambo", "otomi", "ossetian", "oromo", "ojibwe", "ogoni", "odia", "occitan", "oorlam", "ovahimba", "ovambanderu", "ogba", "ohafia", "ohuhu", "onitsha-ado", "obolo", "oneida", "onondaga", "osing", "orang sungai", "okiek",
"paite", "puerto rican", "pomor", "peruvian", "paraguayan", "purépecha", "pole", "punjabi", "polish", "portuguese", "persian", "pende", "pashtun", "pashayi", "pangasinese", "pamiri", "provençal", "poqomam", "paravar", "perakian", "palembangese", "pontianak", "pattani", "pahang", "pakistani", "pakpak", "palestinian", "piedmontese", "pökoot", "palóc", "paraguayan", "paswan", "patidar", "peranakan", "peruvian", "picard", "pitafi", "poitevin", "pojulu", "pomak", "pomeranian", "pontic", "putianese",
"qaisrani", "quechua", "qiang", "qashqai", "qaratay", "q'anjob'al", "qajar", "qarapapaq", "qatari", "qemant", "q'eqchi",
"raisani", "rusyn", "ryukyuan", "russian", "roma", "romanian", "rohingya", "rejangese", "rakhine", "rajbongshi", "rajput", "rajasthani", "rade", "ruvuma", "romaniote", "rumanau", "rungu", "rai", "rajasthan", "rashaida", "rawal", "réunionese", "rhinelander", "ribun", "rifian", "rinconada", "rind", "rûm",
"saint-martinois", "sylheti", "swede", "swedish", "susu", "swazi", "shirazi", "swahili", "surma", "sukuma", "sumbawa", "sundanese", "sumba", "sui", "spaniard", "spanish", "sotho", "somali", "soninke", "songhai", "soga", "slovene", "slovak", "sioux", "sinhalese", "sindhi", "silt'e", "silesian", "sidama", "sika", "siddi", "sibe", "shona", "shilluk", "sherbro", "serer", "serbian", "serb", "senufo", "shetlander", "scottish", "scots", "savu", "sasak", "sardinian", "santal", "sangirese", "samoan", "sámi", "sambal", "sama-bajau", "salar", "saho", "sikh", "salale", "shaigiya", "sangtam", "seminole", "shawnee", "sabar", "sarnaism", "segeju", "soqotri", "sakapultek", "sipakapense", "sakalava", "sihanaka", "samburu", "samia", "samogitian", "selonian", "soran", "shabak", "seneca", "sicilian", "suundi", "sanmarinese", "samin", "surinamese", "syrian", "sephardim", "sabaot", "sarki", "sunuwar", "saban", "sadozai", "sadgop", "saha", "sahrawi", "saint helenian", "saint lucian", "saintongeais", "salinero", "san'ani", "sanggau", "sangley", "sanhaja de srair", "sara bakati", "sarakatsani", "sarawan", "sasoli", "saudi", "saxon", "sefwi", "selako", "semandang", "sethwi", "setos", "seychellois", "shahsevan", "shaikhzadah", "shapsug", "shandong", "shanghainese", "shenva", "shilha", "shirazi", "shunri", "sichuanese", "silesian", "simalungun", "simte", "singaporean", "singkil", "siwi", "sokci", "sorsoganon", "south tyrolean", "st eustatian", "st maartener", "sudanese", "sunni", "subei", "surinamese", "suvarna banik", "svan", "swabian", "syrian", "székely",
"ta'izzis-adenis", "tutsi", "tupuri", "tuvan", "turk", "turkish", "turkmen", "turkana", "tsonga", "tujia", "tswana", "toucouleur", "tripuri", "thai", "toraja", "tlapanec", "toubou", "tigre", "tiwa", "tibetan", "tigrayan", "tausūg", "temne", "tboli", "tamil", "tatar", "tarok", "talysh", "tama", "tajik", "tahitian", "tagalog", "tabasaran", "tibetan", "trique", "tidong", "tz'utujil", "tzotzil", "tojolab'al", "tzeltal", "terengganuarian", "tektitek", "tanala", "tsimihety", "tandroy", "torbesh", "tachoni", "tiriki", "tsotso", "tadvi", "taishanese", "tunumiit", "tuscarora", "ticino", "tuscan", "trentini", "tenggerese", "teimanim", "toshavim", "tunisian", "tambanuo", "tugen", "terik", "thakuri", "theravada", "turk", "taiwanese", "talpur", "tanka", "tauki", "taungyo", "taymani", "tchaman", "tem", "teochew", "terekeme", "thadou", "thai", "tihami", "timuri", "toba", "tobagonian", "tornedalian", "tosk", "transylvanian", "trinidadian", "tringgu", "tuareg", "tunisian", "tushetian", "twi", "tyari",
"umrani", "uruguayan", "umbundu", "urum", "ukwuani", "umbrian", "uspantek", "udmurt", "urhobo", "ukrainian", "uyghur", "uzbek",
"valencian", "vezo", "vagri", "vasava", "virjal", "võros", "venetian", "vili", "venda", "vietnamese", "visayan",
"wassa", "wenzhou", "white", "wodaabe", "wolof", "wu", "waawa", "waldensian", "wanga", "wollo", "wakhi", "walloon", "waxiang", "welayta", "welsh",
"xamtanga", "ximre", "xinca", "xhosa",
"yarahmadzai", "yakö", "yörük", "yakan", "yuchi", "yoruba", "yakut", "yao", "yimchunger", "yakoma", "yaw", "yazidi", "yemeni", "yeraz", "yogi nath", "yemenite", "yerwa", "yakkha",
"zagar", "zapotec", "zande", "zamboangueño", "zaghawa", "zafimaniry", "zaza", "zakria zae", "zambian", "zanzibari", "zarabes", "zardari", "zay", "zoreilles", "zou", "zhuang"
];