export const Religion: string[] = [
"anglican", "animism", "animist", "anito", "anitist", "armenian apostolic", "african zionism",
"batak", "bathouism", "buddhism", "bulgarian orthodox",
"calvinism", "calvinist", "catholic", "creek mythology", "catholicism", "chinese folk religion", "christian", "christianity", "church of scotland", "coptic orthodox",
"eastern orthodox", "eritrean orthodox", "ethiopian orthodox",
"georgian orthodox", "greek orthodox",
"hanafi", "hindu", "hinduism", "hmong folk religion",
"islam", "isma",
"lisu", "longhouse religion", "lutheran",
"methodist", "moism", "macedonian orthodox", "moravian church",
"native american", "nahdlatul ulama", "nuo folk religion",
"ohrid archbishopric",
"p'ent'ay", "protestant",
"qiang folk religion",
"russian orthodox", "ryukyuan",
"sarnaism", "serbian orthodox", "shamanism", "shia", "shinto", "sunni",
"taoism", "tewahedo", "theravada", "tibetan buddhism", "traditional african",
"vaishnavism",
"west african vodun",
"yao folk religion",
"zionist"
];