/**
 * @link https://en.wikipedia.org/wiki/list_of_sovereign_states
 */
export const territory: string[] = [
"abazinia", "alabama", "assam", "aceh", "accra", "aosta valley", "alberta", "alabama", "akwa", "alaska", "antilles", "abkhazia", "aceh", "afar", "afaria", "afghanistan", "akwa ibom state", "albania", "algeria", "amarasi", "ambon island", "america", "amhara", "amharia", "andorra", "angola", "anuakia", "antigua", "argentina", "armenia", "artsakh", "assam", "assyria", "australia", "austria", "avaristan", "awadh", "azerbaijan",
"bahamas", "bengal", "boyer-ahmad", "bushehr", "bakhtiari", "bombali", "buton", "burundi", "bandiagara", "brong-ahafo", "benishangul-gumuz", "budjak", "buganda", "bener", "benue", "bayelsa", "basilicata", "bahrain", "bakossi mountains", "bali", "balochistan", "balkans", "kabardino-balkaria", "bangladesh", "barbados", "barbuda", "bas-uele", "bashkortostan", "basilan", "basque country", "northwest sumatra–barrier islands", "belarus", "belgium", "belize", "bengal", "benin", "benue state", "benishangul-gumuz", "bhojpur", "bhutan", "bicolandia", "bolivia", "boma", "borgu", "bosnia", "botswana", "brasil", "brazil", "britain", "brittany", "brunei", "bulgaria", "burkina faso", "burma", "burundi", 
"cabo verde", "comoros", "chari-baguirmi", "comoros", "chaharmahal", "cagayan", "chuuk lagoon", "cornwall", "corsica", "cuyo archipelago", "circassia", "chittagong", "chuvashia", "champa", "chechnya", "cordillera", "calabria", "campania", "cagayan valley", "caledonia", "cambodia", "cameroon", "canary islands", "caribbean", "cayman", "central african republic", "central asia", "chad", "chile", "china", "colombia", "comoros", "congo", "costa rica", "côte divoire", "croatia", "cuba", "cymru", "cyprus", "czech republic", 
"dabou", "dholuo", "darién", "dagestan", "dahomey", "dagbon", "dagestan", "dali bai", "delta state", "democratic republic of the congo", "denmark", "djibouti", "dominica", "dominican republic",
"east timor", "echigo", "edo state", "ecuador", "egypt", "el salvador", "equatorial guinea", "england", "eritrea", "estonia", "eswatini", "ethiopia",
"fiji", "free state", "finland", "france", "felvidék", "frisia", "friuli", "fiji", "flanders", "florida",
"gabon", "georgia", "grand kru", "goa", "gilgit-baltistan", "gujarat", "guizhou", "gondwana", "gorontalo", "guragia", "galicia", "garo hills", "gedeo zone", "gayo lues", "gagauzia", "gambia", "georgia", "germany", "ghana", "gibraltar", "gilgit-baltistan", "gold coast", "great britain", "greece", "greenland", "guangxi", "guatemala", "guerrero", "guinea", "guinea bissau", "guizhou", "guyana", 
"haiti", "hidalgo", "harari", "hunan", "hezhou", "hadiya", "hararia", "hawaii", "hazarajat", "hokuriku", "herzegovina", "honduras", "horn of africa", "hualien", "hunan", "hungary", 
"iceland", "ibom", "ilocos", "ingushetia", "isoko", "india", "indonesia", "iran", "iraq", "ireland", "italy", "ituri", "ivory coast",
"jakarta", "jamaica", "japan", "java", "jharkhand", "jordan", "jammu", "java",
"kazakhstan", "kapisa", "kathmandu", "kerala", "khuzestan", "kohgiluyeh", "koinadugu", "kurdistan", "kandhamal", "khorasan", "kogi", "kivu", "kachin", "kamba", "kanakia", "karnataka", "karachay-cherkessia", "karakalpakstan", "karbi anglong", "kashmir", "kashubia", "kaduna state", "kosovo", "kuwait", "kwazulu-natal", "kyrgyzstan", "kenya",
"lake fitri", "limpopo", "laghman", "lanao", "lorestan", "lezgistan", "lazistan", "lakia", "labrador", "louisiana", "lombardy", "lampung", "laos", "latvia", "lebanon", "lesotho", "liberia", "libya", "liechtenstein", "lithuania", "luxembourg", 
"macedonia", "mpumalanga", "mayo-kebbi est", "murutia", "mosquito coast", "mordovia", "minahassa", "manipur", "mahra", "maharashtra", "manchuria", "malta", "mambilla", "maldives", "mayotte", "mauritius", "mueda", "mithila", "magadha", "madura", "maryland", "misiones", "manitoba", "mariana islands", "mississippi", "meriah", "mindanao", "mandara", "madagascar", "malaysia", "maldives", "mali", "malta", "manipur", "marshall islands", "mauritania", "mauritius", "meghalaya", "mexico", "micronesia", "middle east", "moldova", "mongolia", "montenegro", "morocco", "mozambique", "mpumalanga", "mtwara", "myanmar", 
"namibia", "nangarhar", "nuristan", "nubia", "newfoundland", "north carolina", "nunavut", "nunatsiavut", "niigata", "nauru", "nepal", "netherlands", "new zealand", "nicaragua", "niger", "nigeria", "north korea", "north macedonia", "north sumatra", "northern cape", "northern ireland", "norway", 
"oaxaca", "ossetia", "occitania", "odisha", "oecusse", "oman", "oromia", "ontario",
"pakistan", "puebla", "permyakia", "palau", "panama", "piedmont", "pampanga", "punjab", "papua new guinea", "paraguay", "peru", "philippines", "poland", "portugal", "puerto rico", 
"qatar", "quảng bình", "quảng trị", "quebec",
"romania", "rajasthan", "ryukyu islands", "réunion", "russia", "ruvuma", "rwanda", "río muni", "romandy", "rwenzori mountains",
"saint kitts and nevis", "silesia", "sardinia", "sangihe islands", "samoa", "stavropol", "sarawak", "sulawesi", "schleswig", "székely", "sarawak", "saint vincent and the grenadines", "saskatchewan", "shin'etsu", "shinshuu", "suriname", "sabah", "saint lucia", "saint vincent and the grenadines", "samoa", "san marino", "sandžak", "sao tome and principe", "sarawak", "saudi arabia", "savannakhet", "scotland", "senegal", "serbia", "seychelles", "sichuan", "sierra leone", "singapore", "slovakia", "slovenia", "soccsksargen", "solomon islands", "somalia", "south africa", "south cotabato", "south kalimantan", "south korea", "spain", "sri lanka", "sudan", "south sudan", "sulu", "sumbawa", "suriname", "sweden", "switzerland", "sylhet", "syria", 
"tabasaranstan", "tahiti", "tibet", "tennessee", "taraba", "tennessee", "tōkai", "tahiti", "taitung", "taiwan", "tajikistan", "tanzania", "tatarstan", "tasmania", "telangana", "tibet", "timor leste", "thailand", "tobago", "togo", "tonga", "tooro", "trinidad", "tripura", "tunisia", "turkey", "turkmenistan", "tuva",
"udmurtia", "ukambani", "uttarakhand", "uganda", "ukraine", "united arab emirates", "united kingdom", "united states", "uruguay", "uyghuristan", "uzbekistan", 
"vatican", "veracruz", "venezuela", "vietnam", "visayas", "volta", "veneto", "vokkaliga",
"wa state", "wukari", "wales", "wallonia", "wamba", "west indies", "west nile", "west timor", "western cape", "wolayitia", "wuling", "wallonia",
"yakurr", "yakutia", "yemen", "yugoslavia", "yunnan",
"zambia", "zhuangia", "zimbabwe"
];