-- Up
INSERT INTO Placename (keyword)
VALUES
('Iachino'),
('Iain'),
('Ian'),
('Ian Charles Community'),
('Ian Hay'),
('Ian Mikardo'),
('Ian Rankin'),
('Ian Rose'),
('Ian Smith'),
('Ian Urquhart'),
('Ians'),
('Ianson'),
('Ianstown'),
('Iar choire Sneachdach'),
('Iard Yr Orsaf'),
('Iarsiadar'),
('Iasg Loch'),
('Iaşi'),
('Ibadan'),
('Ibagué'),
('Ibaraki'),
('Ibarra'),
('Ibber Clough'),
('Ibberson'),
('Ibbersons Drove'),
('Ibberton'),
('Ibberton Long Down'),
('Ibbertson'),
('Ibbetson'),
('Ibbetson Oval'),
('Ibbett'),
('Ibbidge'),
('Ibbot Royd Clough'),
('Ibbotroyd'),
('Ibbotson'),
('Ibbotsons'),
('Ibbott'),
('Ibbottson'),
('Iber'),
('Iberian'),
('Iberis'),
('Iberry'),
('Ibert'),
('Ibex'),
('Ibirité'),
('Ibis'),
('Ible'),
('Ibri'),
('Ibris'),
('Ibrook'),
('Ibrox'),
('Ibroxholm'),
('Ibroxholm Oval'),
('Ibscott'),
('Ibsen'),
('Ibsley'),
('Ibsley Drove'),
('Ibsley Water'),
('Ibstock'),
('Ibstone'),
('Ibthorpe'),
('Iburndale'),
('Ibworth'),
('Ica'),
('Icarus'),
('Icconhurst'),
('Ice'),
('Ice Cleugh'),
('Ice Drove'),
('Ice House'),
('Ice House Belt'),
('Ice Well'),
('Icedale'),
('Icedell'),
('Icehouse'),
('Icehouse Clump'),
('Icehouse Combe'),
('Icehouse Covert'),
('Icehouse Hanger'),
('Icehouse Pool'),
('Icehouse Ride'),
('Icehouse Strip'),
('Icehousehill Covert'),
('Iceland'),
('Iceland Skerry'),
('Icelander'),
('Icelton'),
('Icen'),
('Iceni'),
('Icepits'),
('Icewell'),
('Ichalakaranji'),
('Ichihara'),
('Ichikawa'),
('Ichinomiya'),
('Ichinoseki'),
('Icicle'),
('ICIT'),
('Ickburgh'),
('Ickburgh Carr'),
('Ickburgh Long Covert'),
('Ickenham'),
('Ickenham Marsh'),
('Ickford'),
('Ickham'),
('Ickham'),
('Well'),
('Ickleford'),
('Ickles'),
('Icklesham'),
('Ickleton'),
('Ickley'),
('Icklingham'),
('Icklingham Belt'),
('Icklingham Furze'),
('Icklingham Plains'),
('Icknield'),
('Icknield Port'),
('Ickornshaw'),
('Ickwell'),
('Ickworth'),
('Icold'),
('Icomb'),
('Icomb Cow'),
('Icombe'),
('Icy'),
('Icy Geo'),
('Ida'),
('Ida Darwin'),
('Ida Quadrant'),
('Idaho'),
('Idas'),
('Idbury'),
('Iddesleigh'),
('Iddinshall Hall'),
('Iddinshall Rough'),
('Iddison'),
('Iddlecott'),
('Ide'),
('Ide Brake'),
('Ideal Bungalows'),
('Ideford'),
('Idehurst'),
('Iden'),
('Iden Hurst'),
('Idencroft'),
('Idens'),
('Idenwood'),
('Ides'),
('Idewell'),
('Idle'),
('Idle'),
('Thackley'),
('Idle Stop'),
('Idle Valley'),
('Idlecombe'),
('Idlecombe Down'),
('Idlecroft'),
('Idleigh'),
('Idless'),
('Idlethorp'),
('Idleton'),
('Idlewood'),
('Idlib'),
('Idlicote'),
('Idmiston'),
('Idmiston Down'),
('Idoch'),
('Idol'),
('Idole'),
('Idolsfold'),
('Idonia'),
('Idover'),
('Idovers'),
('Idridgehay'),
('Idridgehay'),
('Alton'),
('Idrigill'),
('Idris'),
('Idris Villas'),
('Idsall'),
('Idston'),
('Idstone'),
('Idstone Down'),
('Idsworth'),
('Idsworth Down'),
('Idvies'),
('Idvies Strip'),
('Idwal'),
('Idzholm'),
('Iestyn'),
('Iestynian'),
('Iet y Bontbren'),
('Iet y bwlch'),
('Ife'),
('Iffcomb'),
('Iffin'),
('Iffley'),
('Iffley Fields'),
('Iffley Fields'),
('St. Marys'),
('Iffley Turn'),
('Ifield'),
('Ifieldwood'),
('Ifold'),
('Ifoldhurst'),
('Ifor'),
('Ifor Hael'),
('Iford'),
('Iford Fields'),
('Ifould'),
('Ifton'),
('Ifton Fields'),
('Ifton Great'),
('Ifton Heath'),
('Igarassu'),
('Ighten'),
('Ightenhill'),
('Ightfield'),
('Ightfield Heath'),
('Ightham'),
('Ightham'),
('Stansted Wrotham'),
('Ightham By Pass'),
('Ignet Castle'),
('Ignet Craig'),
('Iguala'),
('Ihlee'),
('ihub'),
('Iida'),
('Iizuka'),
('Ikea'),
('Ikeda'),
('Iken'),
('Iken Cliff'),
('Iken Marshes'),
('Ikere Ekiti'),
('Ikey'),
('Ikin'),
('Ikins'),
('Ikoma'),
('Ikon'),
('Iksan'),
('Il Holm'),
('Ilagan'),
('Ilam'),
('Ilan'),
('Ilay'),
('Ilbert'),
('Ilberts'),
('Ilbury'),
('Ilchester'),
('Ilchester Mead Drove'),
('Ildersly'),
('Ilderton'),
('Ile'),
('Ile Coire'),
('Ileach Bhàn'),
('Ileden'),
('Iles'),
('Ilesa'),
('Ilex'),
('Ilex Clump'),
('Iley'),
('Ilford'),
('Ilford Bridges'),
('Ilford Side'),
('Ilford Town'),
('Ilfracombe'),
('Ilfracombe Central'),
('Ilfracombe Tyrrell'),
('Ilgars'),
('Ilges'),
('Ilhéus'),
('Iliad'),
('Iliffe'),
('Iliffes'),
('Iligan'),
('Ilion'),
('Ilk'),
('Ilkerton'),
('Ilkeston'),
('Ilkeston Community'),
('Ilketshall St Andrew'),
('Ilketshall St Lawrence'),
('Ilketshall St Margaret'),
('Ilketshall St. Andrew'),
('Ilketshall St. John'),
('Ilketshall St. Lawrence'),
('Ilketshall St. Margaret'),
('Ilkley'),
('Ilkley Hall'),
('Ill Bell'),
('Ill Carr'),
('Ill Crag'),
('Ill Craig'),
('Ill Geo'),
('Illand'),
('Illawalla'),
('Illcott'),
('Illett'),
('Illey'),
('Illeybrook'),
('Illgill Head'),
('Illidge'),
('Illiffe'),
('Illings'),
('Illington'),
('Illington Belt'),
('Illingworth'),
('Illingworth'),
('Mixenden'),
('Illingworths'),
('Illinois'),
('Illiswilgig'),
('Illogan'),
('Illogan Downs'),
('Illogan Highway'),
('Illona'),
('Illshaw'),
('Illshaw Heath'),
('Illsley'),
('Illston'),
('Illston on the'),
('Illtud'),
('Illtyd'),
('Illustrious'),
('Illwills Border'),
('Ilmer'),
('Ilmington'),
('Ilminster'),
('Iloilo City'),
('Ilonas'),
('Ilopango'),
('Ilorin'),
('Ilse Pool'),
('Ilsham'),
('Ilsham Marine'),
('Ilsham Valley'),
('Ilsington'),
('Ilsington Heath'),
('Ilsley'),
('Ilsom House Residential'),
('Ilston'),
('Ilsyn'),
('Ilsyngrove'),
('Ilthorpe'),
('Ilton'),
('Ilton cum Pott'),
('Ilton Garth'),
('Ilway'),
('Ilynton'),
('Imabari'),
('Imachar'),
('Imadene'),
('Image'),
('Image Pool'),
('Imair'),
('Imandra'),
('iMap Centre'),
('Imbaba'),
('Imber'),
('Imber Cross'),
('Imber Firs'),
('Imberdown'),
('Imberfield'),
('Imberhorne'),
('Imbert'),
('Imberwood'),
('Imble'),
('Imbook'),
('Imbrecourt'),
('Imby'),
('Imeary'),
('Imelda'),
('Imeraval'),
('Imeson'),
('Imesons'),
('Imison'),
('Imjin'),
('Imlach'),
('Immaculate Heart Of Mary'),
('Immanuel'),
('Immanuel'),
('St Andrew'),
('Immenstadt'),
('Immingham'),
('Immingham Dock'),
('Imogen'),
('Imp'),
('Impala'),
('Imperatriz'),
('Imperial'),
('Imperial Circus'),
('Imperial Dock'),
('Imperial House'),
('Imperial Wharf'),
('Impetts'),
('Impey'),
('Imphal'),
('Impington'),
('Impington International'),
('Implacable'),
('Implement'),
('Impney'),
('Import Dock'),
('Impsley'),
('Impson'),
('Impstone'),
('Impstones'),
('Impton'),
('Imran'),
('Imray'),
('Imre'),
('Imriche'),
('Imrie'),
('Imus'),
('In'),
('In Fields'),
('In Gully'),
('In The Ray'),
('Ina'),
('Ina Down'),
('Inaccessible Pinnacle'),
('Inaclete'),
('Inazawa'),
('Inbhair Chircaig'),
('Inbhir a Chlair'),
('Inbhir a Ghàrraidh'),
('Inbhir Allt na Luachair'),
('Inbhir Amlabhaig'),
('Inbhir an Dubh Uillt'),
('Inbhir Beag'),
('Inbhir Buidhe'),
('Inbhir Ghil'),
('Inbhir Nis'),
('Inbhir Nèill'),
('Inbhir Shligeach'),
('Inbhirean'),
('Inby'),
('Inca'),
('Incan Slade'),
('Ince'),
('Ince Airfield'),
('Ince'),
('Elton'),
('Ince Banks'),
('Ince Blundell'),
('Ince Blundell Hall'),
('Ince Brake'),
('Ince Castle'),
('Ince Hall'),
('Ince in Makerfield'),
('Ince Marshes'),
('Ince Moss'),
('Ince Piece'),
('Incemore'),
('Inch'),
('Inch Biggie'),
('Inch Cleuch'),
('Inch Colm'),
('Inch Ford'),
('Inch Garvie'),
('Inch Geck'),
('Inch Head'),
('Inch Keith'),
('Inch Kenneth'),
('Inch Marnock'),
('Inch More'),
('Inch Murrin'),
('Inch of Arnhall'),
('Inch Peel'),
('Inch Pool'),
('Inch Rocks'),
('Inchaffray'),
('Incham'),
('Inchard'),
('Inchbae'),
('Inchbare'),
('Inchberry'),
('Inchbonnie'),
('Inchbrae'),
('Inchbrakie'),
('Inchbraoch'),
('Inchbrayock'),
('Inchbread'),
('Inchbrook'),
('Inchbroom'),
('Inchburn'),
('Inchcailloch'),
('Inchcape'),
('Inchcape Rock'),
('Inchcliffe'),
('Inchcolm'),
('Inchconnachan'),
('Inchcorse'),
('Inchcorsie'),
('Inchcross'),
('Inchcross Steadings'),
('Inchcruin'),
('Inchcumine'),
('Inchdarnie'),
('Inchdonald'),
('Inchdrewer'),
('Incheon'),
('Incher'),
('Incheril'),
('Inches'),
('Inchewan'),
('Inchfad'),
('Inchfield'),
('Inchford'),
('Inchgall'),
('Inchgarth'),
('Inchgarth'),
('Inchgarve'),
('Inchgarvie'),
('Inchgarvie Loan'),
('Inchgotrick'),
('Inchgower'),
('Inchgreen'),
('Inchholm'),
('Inchie'),
('Inchie Strip'),
('Inchina'),
('Inchinnan'),
('Inchkeil'),
('Inchkeith'),
('Inchkeith Wynd'),
('Inchlaggan'),
('Inchlaw'),
('Inchlee'),
('Inchley'),
('Inchline'),
('Inchlonaig'),
('Inchlumpie'),
('Inchmarlo'),
('Inchmarnock'),
('Inchmead'),
('Inchmery'),
('Inchmery Clump'),
('Inchmickery'),
('Inchmoan'),
('Inchmore'),
('Inchmuir'),
('Inchmulloch'),
('Inchmurrin'),
('Inchna'),
('Inchnacardoch'),
('Inchnadamph'),
('Inchnagour'),
('Inchneuk'),
('Inchnock'),
('Inchoch'),
('Inchomnie'),
('Inchree'),
('Inchrory'),
('Inchshannoch'),
('Inchslithery'),
('Inchtavannach'),
('Inchture'),
('Inchview'),
('Inchvuilt'),
('Inchwood'),
('Inchyettle'),
('Inchyra'),
('Incinerator'),
('Incle'),
('Incleborough'),
('Incledon'),
('Incline'),
('Incline Top'),
('Inclosures'),
('Incombe'),
('Income Stream'),
('Indaiatuba'),
('Indale'),
('Indells'),
('Independence'),
('Independent'),
('Independents'),
('Inderwick'),
('Index'),
('Indhouse'),
('India'),
('Indian'),
('Indian Queen'),
('Indian Queens'),
('Indiana'),
('Indianapolis'),
('Indians'),
('Indiansdorp'),
('Indicknowle'),
('Indicombe'),
('Indigo'),
('Indilake'),
('Indio'),
('Indio Lake'),
('Indiwell'),
('Indmere'),
('Indore'),
('Indstry'),
('Indulf House'),
('Indus'),
('Industry'),
('Inegöl'),
('Inett'),
('Inezgane'),
('Infant'),
('Infantry'),
('Infell'),
('Infield'),
('Infield Holt'),
('Infields'),
('Infiniti'),
('Infinity'),
('Infirmary'),
('Infrastructure'),
('Ing'),
('Ing Barn'),
('Ing Dale'),
('Ing Dene'),
('Ing Drove'),
('Ing Ends'),
('Ing Head'),
('Ing Holt'),
('Ing Lands'),
('Ing Marsh'),
('Ing Nook'),
('Inga'),
('Inga Ness'),
('Ingal'),
('Ingale Skerry'),
('Ingale Sound'),
('Ingalis'),
('Ingamells'),
('Inganess'),
('Inganoust'),
('Ingardine'),
('Ingarfield'),
('Ingarsby'),
('Ingas Holm'),
('Ingate'),
('Ingatestone'),
('Ingatestone'),
('Fryerning'),
('Ingatestone By Pass'),
('Ingathorpe'),
('Ingaville'),
('Ingavoe'),
('Ingaway'),
('Ingbarrow'),
('Ingber'),
('Ingbirchworth'),
('Ingbirchworth'),
('Ingdale'),
('Ingdale Howl'),
('Inge'),
('Ingelheim'),
('Ingelow'),
('Ingelrica'),
('Ingels'),
('Ingerbeck'),
('Ingerholmes'),
('Ingersley'),
('Ingersley Clough'),
('Ingersley Vale'),
('Ingersol'),
('Ingersoll'),
('Ingerthorpe'),
('Inges'),
('Inges Shaw'),
('Ingester'),
('Ingestre'),
('Ingeva'),
('Ingfield'),
('Ingham'),
('Ingham Cliff'),
('Ingham Clough'),
('Ingham Corner'),
('Ingham Garth'),
('Ingham Hall'),
('Ingham Old Hall'),
('Ingham Pastures'),
('Inghams'),
('Inghamwood'),
('Inghead'),
('Ingie Geo'),
('Ingland'),
('Inglands'),
('Inglass Geo'),
('Inglby'),
('Ingle'),
('Ingle Dell'),
('Ingle Head'),
('Ingle Nook'),
('Ingle Pingle'),
('Ingle Pool'),
('Ingleberry'),
('Inglebert'),
('Ingleboro'),
('Ingleborough'),
('Inglebrook'),
('Ingleby'),
('Ingleby Arncliffe'),
('Ingleby Barwick'),
('Ingleby Cross'),
('Ingleby Greenhow'),
('Ingleby House'),
('Ingleby Paddocks'),
('Inglecote'),
('Ingleden'),
('Ingledene'),
('Ingledew'),
('Inglefield'),
('Ingleglen'),
('Inglegreen'),
('Inglehead'),
('Ingleholme'),
('Inglehurst'),
('Ingleigh'),
('Inglemere'),
('Inglemire'),
('Inglemoss'),
('Ingleneuk'),
('Inglenook'),
('Inglenook Court Leigh'),
('Ingles'),
('Ingles Belt'),
('Ingles Edge'),
('Ingles Fold'),
('Inglesbatch'),
('Inglesby Corner'),
('Inglescombe'),
('Inglesgarth'),
('Inglesham'),
('Ingleside'),
('Ingleston'),
('Inglestone'),
('Inglethorpe'),
('Ingleton'),
('Ingleton'),
('Clapham'),
('Ingleway'),
('Inglewhite'),
('Inglewhite Fold'),
('Inglewood'),
('Inglewood Dell'),
('Inglewood Hollow'),
('Ingli Geo'),
('Inglis'),
('Inglis Banks'),
('Inglis Green Gait'),
('Inglis Green Rigg'),
('Ingliston'),
('Inglistonhill'),
('Ingloss'),
('Ingman Lodge'),
('Ingman Lodge Rough'),
('Ingman Lodge Shaw'),
('Ingmanthorpe'),
('Ingmire'),
('Ingmire Back'),
('Ingmires'),
('Ingmoor Moss'),
('Ingmote'),
('Ingoe'),
('Ingoe Covert'),
('Ingol'),
('Ingol'),
('Tanterton'),
('Ingold'),
('Ingoldale'),
('Ingoldfield'),
('Ingoldisthorpe'),
('Ingoldmells'),
('Ingoldmells Rural'),
('Ingoldsby'),
('Ingolside'),
('Ingolstadt'),
('Ingon'),
('Ingot'),
('Ingra'),
('Ingra Tor'),
('Ingram'),
('Ingram Pit'),
('Ingram Pool'),
('Ingram Shaw'),
('Ingramgate'),
('Ingrams'),
('Ingrams Furze'),
('Ingrams Opening'),
('Ingrams Piece'),
('Ingrams Well'),
('Ingraston'),
('Ingraston Moss'),
('Ingrave'),
('Ingrave'),
('West Horndon Herongate'),
('Ingrave Johnstone'),
('Ingrebourne'),
('Ingress'),
('Ingreway'),
('Ingrie'),
('Ingrish'),
('Ingrove'),
('Ingrow'),
('Ings'),
('Ings Balk'),
('Ings Causeway'),
('Ings Drove'),
('Ings Holt'),
('Ings Mere'),
('Ings New'),
('Ings Rood'),
('Ings Villa'),
('Ingsdon'),
('Ingsdons'),
('Ingsfield'),
('Ingsgarth'),
('Ingshead'),
('Ingst'),
('Ingswell'),
('Ingthorne'),
('Ingthorpe'),
('Ingwell'),
('Ingwood'),
('Ingworth'),
('Inham'),
('Inham Circus'),
('Inham Down'),
('Inham Fields'),
('Inhams'),
('Inhams Fold'),
('Inhedge'),
('Inholmes'),
('Inholms'),
('Inhurst'),
('Inigo'),
('Inigo Jones'),
('Inishail'),
('Ink Moss'),
('Inkberrow'),
('Inkbottle'),
('Inkerman'),
('Inkerman Belt'),
('Inkerpole'),
('Inkersall'),
('Inkersley'),
('Inkerson Fen'),
('Inkford'),
('Inkle Moors'),
('Inkpen'),
('Inkpen Furze'),
('Inkpen Great'),
('Inkpins'),
('Inks'),
('Inkstack'),
('Inkwell'),
('Inkwood'),
('Inkydown'),
('Inland'),
('Inland Pool'),
('Inland Sea'),
('Inlands'),
('Inlays'),
('Inleborough'),
('Inley'),
('Inley Drove'),
('Inleys'),
('Inlie'),
('Inman'),
('Inmans'),
('Inmarsh'),
('Inmead'),
('Inmoor'),
('Inmosthay'),
('Inn'),
('Inn Down'),
('Inn Holm'),
('Inn Island'),
('Inna Ness'),
('Inna Yea'),
('Innacamas'),
('Innage'),
('Innan Neb'),
('Innbanks'),
('Innean'),
('Innean a Chromain'),
('Innellan'),
('Inner'),
('Inner Alscott Combe'),
('Inner Anchorage'),
('Inner Appledore Rocks'),
('Inner Basin'),
('Inner Black'),
('Inner Blue Carn'),
('Inner Booth'),
('Inner Brackets'),
('Inner Breakwater'),
('Inner Brigurd'),
('Inner Broady Cove'),
('Inner Bucks'),
('Inner Butt'),
('Inner Byre Cleuch'),
('Inner Camber'),
('Inner Castle'),
('Inner Circle'),
('Inner Cleuch'),
('Inner Cleugh'),
('Inner Colvel Rock'),
('Inner Combe Rocks'),
('Inner Croagle'),
('Inner Dale'),
('Inner Dock'),
('Inner Dodd'),
('Inner Down'),
('Inner Farne'),
('Inner Fladdack'),
('Inner Flaess'),
('Inner Forum'),
('Inner Froward'),
('Inner Ganges'),
('Inner Gat'),
('Inner Geo'),
('Inner Geo of Heog'),
('Inner Gosling'),
('Inner Green Cleugh'),
('Inner Grey'),
('Inner Gullands'),
('Inner Hamar'),
('Inner Hangie'),

('Inner Hare Cleuch'),
('Inner Haven'),
('Inner Head'),
('Inner Hebrides'),
('Inner Height'),
('Inner Hey'),
('Inner Holm'),
('Inner Holm of Skaw'),
('Inner Hope'),
('Inner Kimlers'),
('Inner Knock'),
('Inner Lake'),
('Inner Lead'),
('Inner Ling'),
('Inner London'),
('Inner Loop'),
('Inner Luff'),
('Inner Maynards'),
('Inner Mid'),
('Inner Nebbock'),
('Inner Neck of Gerwick'),
('Inner Owers'),
('Inner Passage'),
('Inner Pendower Cove'),
('Inner Penlee'),
('Inner Penny Ledge'),
('Inner Promenade'),
('Inner Quickening Cleugh'),
('Inner Rags'),
('Inner Ranneys'),
('Inner Redding'),
('Inner Ring'),
('Inner Rock of Carn Wethers'),
('Inner Ruskock'),
('Inner Score'),
('Inner Scouter Cleuch'),
('Inner Scud'),
('Inner Shag Rocks'),
('Inner Silder Skerry'),
('Inner Sinni Geo'),
('Inner Skerry'),
('Inner Snow Craig'),
('Inner Sound'),
('Inner Stone'),
('Inner Taing'),
('Inner Tarri Geos'),
('Inner Temple'),
('Inner Tidal'),
('Inner Ting Tong'),
('Inner Tod'),
('Inner Troola'),
('Inner Tumble Wick'),
('Inner Virdik'),
('Inner Voder'),
('Inner Westland'),
('Innerbridge'),
('Innerbrook'),
('Innercleavy Clump'),
('Innerdouny'),
('Innerdownie'),
('Innergellie Haven'),
('Innerhaugh'),
('Innerkip'),
('Innerleith'),
('Innerleithen'),
('Innerleven'),
('Innermanse Quadrant'),
('Innermarkie Wynd'),
('Innermessan'),
('Innerpark'),
('Innerpeffray'),
('Innerstone'),
('Innertown'),
('Innerwell'),
('Innerwell Port'),
('Innerwick'),
('Innerwick Hydroelectric'),
('Innerwood'),
('Innerwyke'),
('Innes'),
('Innescourt'),
('Innesfield'),
('Innesmoor'),
('Inness Cast'),
('Innewan'),
('Inney'),
('Innham'),
('Innhams'),
('Innholder'),
('Innicks'),
('Inniens'),
('Innings'),
('Inninmore'),
('Innins'),
('Innis'),
('Innis Bhuidhe'),
('Innis Chonain'),
('Innis Chonnell'),
('Innis Downs'),
('Innis Dubh'),
('Innis Loch'),
('Innis Mhòr'),
('Innis na Birlinn'),
('Innis nam Feorag'),
('Innis nan Gobhar'),
('Innis nan Nathraichean'),
('Innis Sèa Ràmhach'),
('Innis àrd'),
('Inniscarra'),
('Inniscord Lochs'),
('Innisfail'),
('Innisfree'),
('Innisidgen'),
('Innisidgen Carn'),
('Inniskilling'),
('Innisvouls Brow'),
('Innisvouls Neck'),
('Innkeepers'),
('Innocence'),
('Innocents'),
('Innominate Tarn'),
('Innova'),
('Innovation'),
('Innovation Centre'),
('Innox'),
('Innri Geo'),
('Inns'),
('Inns Holm'),
('Innsbruck'),
('Innserais'),
('Innsker'),
('Innskerry'),
('Innsmead'),
('Innsworth'),
('Innsworth Garth'),
('Innsworth with Down Hatherley'),
('Inny Foot'),
('Inny Ham Mere'),
('Inott Furze'),
('Inrea'),
('Insall'),
('Inscar'),
('Insch'),
('Insch War Memorial'),
('Inschannochie'),
('Inset'),
('Insetton'),
('Insh'),
('Insh Island'),
('Inshanks'),
('Inshaw'),
('Inshegra'),
('Insherrit Island'),
('Inshes'),
('Inshewan'),
('Inshoch'),
('Inshoch Moss'),
('Inside'),
('Insignia'),
('Inskift'),
('Inskift of Skewnesstoft'),
('Inskip'),
('Inskip Moss Side'),
('Inskip St Peters'),
('Inskip with Sowerby'),
('Insley'),
('Insleys'),
('Insole'),
('Inspiration'),
('Inspirations'),
('Instant'),
('Institute'),
('Institute Beach'),
('Institution'),
('Instone'),
('Instoneville'),
('Instow'),
('Instow Barton Marsh'),
('Instow Sands'),
('Instow Town'),
('Insull'),
('Inswell'),
('Inswork'),
('Insworke'),
('Intac'),
('Intack'),
('Intaglio'),
('Intake'),
('Intake Dale'),
('Intake Force'),
('Intake Head'),
('Intake Pot'),
('Intakefield'),
('Intakes'),
('Intalbury'),
('Intelligence'),
('Intended'),
('Inter Valley'),
('Intercity'),
('Intercommon Heath'),
('Interfield'),
('Interlink'),
('Intermediate'),
('Intermediate Lake'),
('Intermezzo'),
('International'),
('Intown'),
('Intrepid'),
('intu Metrocentre Transport Interchange'),
('Intwood'),
('Intwood Carr'),
('Invaders'),
('Inval'),
('Invar'),
('Invargarry'),
('Invention'),
('Inver'),
('Inver Bar'),
('Inver Channel'),
('Inver Dalavil'),
('Inver Kerry'),
('Inver Pot'),
('Inver Tote'),
('Inverailort'),
('Inveraldie'),
('Inverallan'),
('Inverallan'),
('Advie Cromdale'),
('Inveralligin'),
('Inverallochy'),
('Inveralmond'),
('Inveran'),
('Inveraray'),
('Inverarish'),
('Inverarity'),
('Inverarnan'),
('Inverarnie'),
('Inverary'),
('Inverasdale'),
('Inveravon'),
('Inverawe'),
('Inverbeg'),
('Inverbervie'),
('Inverbreakie'),
('Inverbroom Bridge Pool'),
('Invercanny'),
('Invercargill'),
('Invercarron'),
('Invercauld'),
('Inverchaolain'),
('Invercharron'),
('Invercloy'),
('Inverclyde'),
('Inverclyde Royal'),
('Invercraig'),
('Inverdene'),
('Inverdruie'),
('Invererne'),
('Inveresk'),
('Inveresk Quadrant'),
('Inveresragan'),
('Inverewe'),
('Inverey'),
('Inverfarigaig'),
('Inverforth'),
('Invergarry'),
('Invergarry Quad'),
('Invergeldie'),
('Inverghiusachan'),
('Inverglas'),
('Invergoil'),
('Invergordon'),
('Invergowrie'),
('Invergyle'),
('Inverhouse'),
('Inverie'),
('Inverinan'),
('Inverinate'),
('Inverine'),
('Inveriscandye'),
('Inverkar'),
('Inverkeillor'),
('Inverkeilor'),
('Inverkeithing'),
('Inverkeithing'),
('Dalgety'),
('Inverkeithing Burn'),
('Inverkeithny'),
('Inverkip'),
('Inverkirkaig'),
('Inverlael'),
('Inverlaidnan'),
('Inverlair'),
('Inverlair Falls'),
('Inverlauren'),
('Inverlauren Muir'),
('Inverlaw'),
('Inverlea'),
('Inverleigh'),
('Inverleith'),
('Inverleven'),
('Inverliever'),
('Inverliver'),
('Inverlochlarig'),
('Inverlochy'),
('Invermark'),
('Invermashie Pool'),
('Invermead'),
('Invermore'),
('Invermoriston'),
('Invermoriston Falls'),
('Invernaver'),
('Inverneil Island'),
('Inverneill'),
('Invernenty'),
('Inverness'),
('Inverness'),
('Bona'),
('Inverness Central'),
('Inverness Millburn'),
('Inverness Ness side'),
('Inverness shire'),
('Invernettie'),
('Invernoe'),
('Inveroran'),
('Inveroykel'),
('Inverpolly'),
('Inverquhomery'),
('Inverroy'),
('Inversanda'),
('Inverscaddle'),
('Invershiel'),
('Invershin'),
('Inversnaid'),
('Inverteign'),
('Invertiel'),
('Invertilt'),
('Inverton'),
('Invertrees'),
('Inverugie'),
('Inverugie Wynd'),
('Inveruglas'),
('Inveruglas Isle'),
('Inverurie'),
('Inverurie'),
('District'),
('Inverury'),
('Invervale'),
('Invervar'),
('Invervegain'),
('Inverview'),
('Inverwick'),
('Inverythan'),
('Investiture'),
('Investment'),
('Invicta'),
('Invicta Plaza'),
('Inville'),
('Invincible'),
('Inward'),
('Inward Car Lanes'),
('Inwardleigh'),
('Inwood'),
('Inworth'),
('Inyama Hellia'),
('Inyeth Geo'),
('Inzie Head'),
('Inzievar'),
('Iochdar'),
('Iola'),
('Iola a Chàirn Deirg'),
('Iola Bhàn'),
('Iola Chruaidh'),
('Iola Creag Mhòr Sgoraig'),
('Iola Mhòr'),
('Iola Sgeir'),
('Iola Sgorr'),
('Iolainn Bhèag'),
('Iolainn Mhòr'),
('Iolann an Eilein'),
('Iolanthe'),
('Iolla Bheag'),
('Iolla Mhòr'),
('Iolo'),
('Iolyn'),
('Iomairean Dubha'),
('Iomallach'),
('Ion'),
('Iona'),
('Iona Na Liseagaraidh'),
('Iona Quadrant'),
('Iona Wynd'),
('Ionad Achadh Na Mara'),
('Ionad An Duin'),
('Ionad An Fhleisteir'),
('Ionad An Stor'),
('Ionad Asgrib'),
('Ionad Bhoraraig'),
('Ionad Carn Dearg'),
('Ionad Chruachain'),
('Ionad Columba'),
('Ionad Fhinn'),
('Ionad Fleming'),
('Ionad Ghlamaig'),
('Ionad Lister'),
('Ionad Macaonghais'),
('Ionad Mharsco'),
('Ionad Mhicceallaig'),
('Ionad Mhicille Mhoire'),
('Ionad Mhicmhathain'),
('Ionad Mhurchaidh'),
('Ionad Na Buaile'),
('Ionad Na Corra Grithich'),
('Ionad Phoil'),
('Ionad Ronaidh'),
('Ionad Scalpaidh'),
('Ionad Soaidh'),
('Ionad Stiubhairt'),
('Ionad Thiannabhaig'),
('Ionia'),
('Ionian'),
('Ionic'),
('Iorcail'),
('Iorguill'),
('Iorwerth'),
('Iosaigh'),
('Iowa'),
('Ipatinga'),
('Ipiales'),
('Iping'),
('Iping Marsh'),
('Ipley'),
('Ipley Inclosure'),
('Ipoh'),
('Iport'),
('Ipplepen'),
('Ipsden'),
('Ipsden Heath'),
('Ipsley'),
('Ipsley Church'),
('Ipstones'),
('Ipstones Edge'),
('Ipswich'),
('Ipswich Circus'),
('Ipswich Wet Dock'),
('Iqbal'),
('Iquique'),
('Iquitos'),
('Iram Drove'),
('Irapuato'),
('Irbid'),
('Irby'),
('Irby Dales'),
('Irby Heath'),
('Irby Holmes'),
('Irby in the Marsh'),
('Irby Upon Humber'),
('Irbyside'),
('Irchester'),
('Ire Geo'),
('Ireby'),
('Ireby'),
('Uldale'),
('Iredale'),
('Iredine'),
('Ireland'),
('Ireland Moss'),
('Ireland Sands'),
('Ireland Wick'),
('Irelands'),
('Irelands Clough'),
('Irelands Cross'),
('Irelandton'),
('Ireleth'),
('Ireleth Brow'),
('Ireleth Reservoirs'),
('Iremonger'),
('Irena'),
('Irene'),
('Irene Hughes'),
('Ires Geo'),
('Ires Hope'),
('Ires Taing'),
('Ireshope'),
('Ireshope Plains'),
('Ireshopeburn'),
('Ireson'),
('Irestone'),
('Ireton'),
('Ireton Rough'),
('Iretons'),
('Irex'),
('Irfon'),
('Iridium'),
('Iriga'),
('Iris'),
('Irish'),
('Irish Hole'),
('Irish Lady'),
('Irish Law'),
('Irish Sea'),
('Irish Town'),
('Irishcombe'),
('Irishmans Ledge'),
('Irishmans Rock'),
('Irk'),
('Irk Vale'),
('Irkdale'),
('Irkutsk'),
('Irlam'),
('Irlam Moss'),
('Irlam o th Height'),
('Irlam Wharf'),
('Irlams Beach'),
('Irlams o th Height'),
('Irma'),
('Irmingland'),
('Irnham'),
('Iron'),
('Iron Acton'),
('Iron Band'),
('Iron Bar'),
('Iron Bar Drove'),
('Iron Bar Sands'),
('Iron Car'),
('Iron Carr'),
('Iron Cliff'),
('Iron Cove'),
('Iron Covert'),
('Iron Crag'),
('Iron Craig'),
('Iron Cross'),
('Iron Dish'),
('Iron Down'),
('Iron Duke'),
('Iron Foundry'),
('Iron Geo'),
('Iron Groves'),
('Iron Hellia'),
('Iron Hogg'),
('Iron Hole'),
('Iron Howe'),
('Iron Latch'),
('Iron Man'),
('Iron Mine'),
('Iron Ness'),
('Iron Pikes'),
('Iron Plat'),
('Iron Railway'),
('Iron Scar'),
('Iron Scars'),
('Iron Shovel'),
('Iron Slunk'),
('Iron Well Island'),
('Ironbower Moss'),
('Ironbridge'),
('Ironbridge Carr'),
('Ironbridge Gorge'),
('Ironchurch'),
('Irondale'),
('Irondish'),
('Irondown'),
('Ironestone'),
('Ironfield'),
('Ironfork Cleugh'),
('Irongate'),
('Irongate Bridge'),
('Irongray'),
('Ironhash'),
('Ironhirst Moss'),
('Ironi Geo'),
('Ironing Box Clump'),
('Ironlatch'),
('Ironmarket'),
('Ironmasters'),
('Ironmill'),
('Ironmills'),
('Ironmonger'),
('Ironmongers'),
('Ironmould'),
('Ironotter'),
('Ironpaddock'),
('Ironpits'),
('Ironrieves'),
('Ironrock Pool'),
('Irons'),
('Ironsbottom'),
('Ironshill Inclosure'),
('Ironside'),
('Ironstone'),
('Ironstone Cove'),
('Ironstones'),
('Ironswell'),
('Irontongue'),
('Ironville'),
('Ironville'),
('Riddings'),
('Ironwalls'),
('Ironwell'),
('Ironwells'),
('Ironwells New Covert'),
('Ironwood'),
('Ironworks'),
('Irony Geo'),
('Irrigation'),
('Irsha'),
('Irstead'),
('Irston'),
('Irt'),
('Irthing'),
('Irthington'),
('Irthlingborough'),
('Irthlingborough John Pyel'),
('Irthlingborough Waterloo'),
('Irton'),
('Irton Pike'),
('Irton with Santon'),
('Iruma'),
('Irvan'),
('Irvin'),
('Irvine'),
('Irvine Bar'),

('Irvine Mains'),
('Irvine Moss'),
('Irvine Valley'),
('Irvinebank'),
('Irvineburn'),
('Irvinemuir'),
('Irvines'),
('Irvines Geo'),
('Irvines Strip'),
('Irving'),
('Irving Burgess'),
('Irving Dale'),
('Irving Quadrant'),
('Irvings'),
('Irvington'),
('Irvon'),
('Irwell'),
('Irwell Riverside'),
('Irwell Vale'),
('Irwin'),
('Is afon'),
('Is coed'),
('Is Fryn'),
('Is Terfyn'),
('Is Y Bryn'),
('Is Y Bryniau'),
('Is Y Coed'),
('Is Y Llan'),
('Isa'),
('Isaac'),
('Isaac Newton'),
('Isaac Walton'),
('Isaacs'),
('Isaacs Cleugh'),
('Isaacs Holt'),
('Isaacson'),
('Isabel'),
('Isabel Hospice'),
('Isabela'),
('Isabella'),
('Isabella Banks'),
('Isabella Pit'),
('Isabelle'),
('Isacombe Oaks'),
('Isadora Lea'),
('Isaf'),
('Isahaya'),
('Isaiah'),
('Isallt'),
('Isambard'),
('Isambard Brunel'),
('Isandula'),
('Isauld'),
('Isauld Port'),
('Isbel'),
('Isbell'),
('Isbells'),
('Isbets Dale'),
('Isbister'),
('Isbister Holm'),
('Isbourne'),
('Isbury'),
('Isca'),
('Iscennen'),
('Iscoed'),
('Iscoyd'),
('Ise'),
('Ise Lodge'),
('Ise Vale'),
('Iseanach Beag'),
('Iseanach Mòr'),
('Iseberry Head'),
('Isebrook'),
('Isehara'),
('Isel'),
('Isel Old'),
('Isemans Dub'),
('Isemill'),
('Isemonger'),
('Isenburg'),
('Isenhurst'),
('Iser'),
('Isesaki'),
('Isewoods'),
('Isfield'),
('Isfryn'),
('Isgean'),
('Isgeir'),
('Isglan'),
('Isgoed'),
('Isgraig'),
('Ishag'),
('Isham'),
('Ishams Chase'),
('Isherwood'),
('Isherwood Fold'),
('Isherwoods'),
('Ishinomaki'),
('Ishneich'),
('Isiah'),
('Isidore'),
('Isigny'),
('Isinglass'),
('Isington'),
('Isinvrank'),
('Isis'),
('Isis Lake'),
('Iskandariya'),
('Isla'),
('Isla Pot'),
('Islachattan'),
('Islahead'),
('Islam Shahr'),
('Islamabad'),
('Island'),
('Island Barn'),
('Island Carr'),
('Island Centre'),
('Island Clump'),
('Island Copsie'),
('Island Covert'),
('Island Davaar'),
('Island Dub'),
('Island Gardens DLR'),
('Island I Vow'),
('Island Lanes'),
('Island Loop'),
('Island Macaskin'),
('Island Mere'),
('Island Muller'),
('Island of Clunie'),
('Island of Danna'),
('Island Of Dee'),
('Island of Dundurcas'),
('Island of Mull'),
('Island of Rocks'),
('Island of Stroma'),
('Island Planting'),
('Island Pool'),
('Island Roary'),
('Island Rock'),
('Island Rocks'),
('Island Run'),
('Island Sand'),
('Island Stream'),
('Island Stream Pool'),
('Island Wall'),
('Islandpool'),
('Islands'),
('Islands Brow'),
('Islands Hearn'),
('Islands of Fleet'),
('Islands Thorns Inclosure'),
('Islandsmead'),
('Islandstone'),
('Islawen'),
('Islay'),
('Islay Quadrant'),
('Islayfitz'),
('Isle'),
('Isle Abbotts'),
('Isle Abbotts Drove'),
('Isle Brewers'),
('Isle Head'),
('Isle Maree'),
('Isle Martin'),
('Isle Mouth'),
('Isle na Gower'),
('Isle of Anglesey'),
('Isle of Arran'),
('Isle of Axholme'),
('Isle of Bute'),
('Isle of Dogs'),
('Isle of Ely'),
('Isle of Ewe'),
('Isle of Fethaland'),
('Isle of Gigha'),
('Isle of Grain'),
('Isle of Grain Storage Installation'),
('Isle of Gunnister'),
('Isle of Lanna'),
('Isle of Lewis'),
('Isle of Lochnaw'),
('Isle of Man'),
('Isle Of May'),
('Isle of Moy'),
('Isle of Nibon'),
('Isle of Niddister'),
('Isle of Noss'),
('Isle of Oxney'),
('Isle of Partan'),
('Isle Of Pin'),
('Isle Of Pins'),
('Isle of Portland'),
('Isle of Purbeck'),
('Isle of Raasay'),
('Isle of Rhea'),
('Isle of Sheppey'),
('Isle of Skye'),
('Isle of Spar'),
('Isle of Stenness'),
('Isle of Thanet'),
('Isle of the Biawn'),
('Isle Of Thorns'),
('Isle of Walney'),
('Isle of West Burrafirth'),
('Isle of Westerhouse'),
('Isle of Whithorn'),
('Isle of Wight'),
('Isle Ornsay'),
('Isle Pool'),
('Isle Port'),
('Isle Ristol'),
('Isle Rough'),
('Isle Shaw'),
('Islebeck'),
('Isledane'),
('Isledon'),
('Isleham'),
('Islehurst'),
('Islemoor'),
('Islemoor Drove'),
('Isleornsay'),
('Isleport'),
('Isles'),
('Isles Geo'),
('Isles of Burrow'),
('Isles of Killaser'),
('Isles of Scilly'),
('Isles of Trool'),
('Isles Quarry'),
('Islesteps'),
('Islestone'),
('Islet'),
('Isleworth'),
('Isleworth Ait'),
('Isley'),
('Isley cum Langley'),
('Isley Marsh'),
('Isley Walton'),
('Isleys'),
('Isleys Geo'),
('Islibhig'),
('Islingham'),
('Islington'),
('Islington High'),
('Islington Row Middleway'),
('Islington South'),
('Finsbury'),
('Islingword'),
('Islip'),
('Islip Manor'),
('Isllan'),
('Islwyn'),
('Islwyn Scout Parc'),
('Ismailia'),
('Ismay'),
('Ismay Wharf'),
('Ismays'),
('Ismaïlia'),
('Ismere'),
('Ismore'),
('Ismyrddin'),
('Isobel'),
('Isobella'),
('Isom'),
('Isombridge'),
('Ison'),
('Isons'),
('Ispahan'),
('Isparta'),
('Israel Gill'),
('Issa'),
('Issott'),
('Issue Clough'),
('Issues'),
('Istead'),
('Isthmus'),
('Istoneville'),
('Isvrivm Roman Town'),
('Isycoed'),
('Itabira'),
('Itaboraí'),
('Itabuna'),
('Itaguaí'),
('Itagüí'),
('Itajaí'),
('Italy'),
('Itami'),
('Itapecerica da Serra'),
('Itapetininga'),
('Itapevi'),
('Itapipoca'),
('Itaquaquecetuba'),
('Itatiba'),
('Itch'),
('Itchel'),
('Itchel Mill Springs'),
('Itchell'),
('Itchen'),
('Itchen Abbas'),
('Itchen Southampton'),
('Itchen Stoke'),
('Itchen Stoke'),
('Ovington'),
('Itchen Stoke Down'),
('Itchen Valley'),
('Itchenor'),
('Itchenside'),
('Itchin'),
('Itchingfield'),
('Itchington'),
('Itchington Holt'),
('Itchingwood'),
('Iter'),
('Itford'),
('Ithens'),
('Itherie Geo'),
('Ithica'),
('Ithlan goch'),
('Ithon'),
('Itlay'),
('Itlings'),
('Ito'),
('Itter'),
('Itterby'),
('Itteringham'),
('Ittingstone Pool'),
('Itton'),
('Itu'),
('Ituiutaba'),
('Itumbiara'),
('Iurramaich'),
('Ivah'),
('Ivah Great'),
('Ivamy'),
('Ivan'),
('Ivan Blatny'),
('Ivan Clarks Corner'),
('Ivanhoe'),
('Ivano Frankivsk'),
('Ivanovo'),
('Ivans'),
('Ivar'),
('Ivaro'),
('Ivas'),
('Ivatt'),
('Ive'),
('Ive House'),
('Ive Stones Clough'),
('Iveagh'),
('Ivedon'),
('Ivegate'),
('Ivegill'),
('Ivel'),
('Ivel Bury'),
('Ivelbury'),
('Ivelchester'),
('Iveldale'),
('Ivelet'),
('Ivelet Force'),
('Iveley'),
('Ivelway'),
('Ively'),
('Ivens'),
('Ivenscar'),
('Iver'),
('Iver Heath'),
('Iver Lodge'),
('Iver Stye'),
('Iverdale'),
('Ivere'),
('Iverhurst'),
('Iverley'),
('Iverley Heath'),
('Iverna'),
('Ivernia'),
('Ivers'),
('Iversgate'),
('Iverson'),
('Ivery'),
('Ives'),
('Ives Drove'),
('Ives Head'),
('Ivescar End Moss'),
('Ivesdike'),
('Ivesdyke'),
('Iveshead'),
('Ivesley'),
('Iveson'),
('Iveson Garth'),
('Ivesons Stripe'),
('Ivest'),
('Iveston'),
('Ivetsey'),
('Ivetts'),
('Ivey'),
('Ivies'),
('Ivimey'),
('Iving Cleugh'),
('Iving Pool'),
('Ivinghoe'),
('Ivinghoe Aston'),
('Ivinghoe Business Centre'),
('Ivinghoe Hills'),
('Ivington'),
('Ivins'),
('Ivinson'),
('Ivo'),
('Ivo Peters'),
('Ivonbrook'),
('Ivonbrook Nursing'),
('Residential Home'),
('Ivor'),
('Ivor Thomas'),
('Ivors'),
('Ivory'),
('Ivorydown'),
('Ivry'),
('Ivy'),
('Ivy Arch'),
('Ivy Barns'),
('Ivy Bower'),
('Ivy Chase'),
('Ivy Chimney'),
('Ivy Chimneys'),
('Ivy Church'),
('Ivy Cottage Shaw'),
('Ivy Cove'),
('Ivy Crag'),
('Ivy Cross'),
('Ivy Dene'),
('Ivy Down'),
('Ivy Garth'),
('Ivy Graham'),
('Ivy Ground'),
('Ivy Hall'),
('Ivy Hall Rocks'),
('Ivy Hatch'),
('Ivy House'),
('Ivy House Paddocks'),
('Ivy Island'),
('Ivy Lake'),
('Ivy Lea'),
('Ivy Leaf'),
('Ivy Leigh'),
('Ivy Linn'),
('Ivy Lodge'),
('Ivy May'),
('Ivy Meade'),
('Ivy Pool'),
('Ivy Robyn'),
('Ivy Rose'),
('Ivy Side'),
('Ivy Spring'),
('Ivy Stone'),
('Ivy Tarn'),
('Ivy Thorn'),
('Ivy Todd'),
('Ivy Tree'),
('Ivybank'),
('Ivybank House'),
('Ivybridge'),
('Ivychurch'),
('Ivycombe'),
('Ivycourt'),
('Ivycroft'),
('Ivydale'),
('Ivyday'),
('Ivydene'),
('Ivydore'),
('Ivyfield'),
('Ivygate'),
('Ivygreen'),
('Ivygrove'),
('Ivyhole'),
('Ivyhouse'),
('Ivyhouse Gully'),
('Ivyhurst'),
('Ivylands'),
('Ivylea'),
('Ivyleaf'),
('Ivymoor Head'),
('Ivymount'),
('Ivys'),
('Ivyside'),
('Ivyspring'),
('Ivythorn'),
('Ivytree'),
('Ivyway'),
('Ivywell'),
('Ivywood'),
('Iwade'),
('Iwade'),
('Lower Halstow Bobbing'),
('Iwaki'),
('Iwakuni'),
('Iwata'),
('Iwatsuki'),
('Iwerddon'),
('Iwerne'),
('Iwerne Courtney'),
('Iwerne Courtney or Shroton'),
('Iwerne Minster'),
('Iwerne Stepleton'),
('Iwo'),
('Iwood'),
('Ixer'),
('Ixhill'),
('Ixtapaluca'),
('Ixworth'),
('Ixworth Thorpe'),
('Izaac Walton'),
('Izaak Walton'),
('Izane'),
('Izas'),
('Izatt'),
('Izeh'),
('Izhevsk'),
('Izlebridge'),
('Izod'),
('Izods'),
('Izons'),
('Izumi'),
('Izumisano'),
('Izumo'),
('Izzard');
-- Down
DELETE FROM "Placename" WHERE "keyword" LIKE 'i%';