-- Up
INSERT INTO Placename (keyword)
VALUES
('Qalat Sukkar'),
('Qalyub'),
('Qamishli'),
('Qarchak'),
('Qarshi'),
('Qatif'),
('Qazvin'),
('Qena'),
('Qianjiang'),
('Qidong'),
('Qingdao'),
('Qingtongxia'),
('Qingyang'),
('Qingyuan'),
('Qingzhou'),
('Qinhuangdao'),
('Qinyang'),
('Qinzhou'),
('Qiqihar'),
('Qitaihe'),
('Qods'),
('Qom'),
('Quaas'),
('Quaas Loaning'),
('Quab'),
('Quabbs'),
('Quack'),
('Quadling'),
('Quadrans'),
('Quadrant'),
('Quadrant Hall'),
('Quadrilateral Covert'),
('Quadrille'),
('Quadring'),
('Gosberton Donington'),
('Quadring Eaudike'),
('Quadring High Fen'),
('Quadring Low Fen'),
('Quaggs'),
('Quaggy'),
('Quagmire'),
('Quagmirebank'),
('Quagrigg Moss'),
('Quags Corner'),
('Quail'),
('Quail Corner'),
('Quail Holme'),
('Quaile'),
('Quainton'),
('Quaintways'),
('Quair Throat'),
('Quaish'),
('Quakefield'),
('Quaker'),
('Quaker Fold'),
('Quakerfield'),
('Quakerfields'),
('Quakers'),
('Quakers Course'),
('Quakers Drove'),
('Quakers Hall'),
('Quakers Mede'),
('Quakers Plat'),
('Quakerscorner'),
('Quakesick'),
('Quaking Ash Wiel'),
('Quaking Houses'),
('Quakinghouse'),
('Qualcast'),
('Quale'),
('Qualitas'),
('Quality'),
('Quality Corner'),
('Qualla Dale'),
('Quanea'),
('Quanea Drove'),
('Quaney'),
('Quanley'),
('Quant'),
('Quantans'),
('Quanter Ness'),
('Quanterness Skerry'),
('Quantico'),
('Quantock'),
('Quantock Combe'),
('Quantock Hills'),
('Quantock Vale'),
('Quantocks'),
('Quantocks Head'),
('Quantrelle'),
('Quantrill'),
('Quantry'),
('Quantum'),
('Quanzhou'),
('Quaperlake'),
('Quar'),
('Quar Hill Cuttings'),
('Quarante Ans'),
('Quarella'),
('Quarely'),
('Quarhill'),
('Quarhouse'),
('Quarle'),
('Quarles'),
('Quarleston'),
('Quarleston Down'),
('Quarley'),
('Quarls'),
('Quarlton'),
('Quarlton Fold'),
('Quarmby'),
('Quarmby Fold'),
('Quarme'),
('Quarn'),
('Quarndon'),
('Quarnford'),
('Quarr'),
('Quarr Barton'),
('Quarr clydach'),
('Quarrel'),
('Quarrel Burn'),
('Quarrel Cleugh'),
('Quarrel Dean'),
('Quarrel Geo'),
('Quarrel Geos'),
('Quarrel Knowe'),
('Quarrel Sand'),
('Quarrels'),
('Quarrelton'),
('Quarrelwood'),
('Quarrenden'),
('Quarrendon'),
('Quarriedene'),
('Quarrier'),
('Quarriers'),
('Quarries'),
('Quarrington'),
('Quarrington Fen'),
('Quarrolhall'),
('Quarry'),
('Quarry'),
('Coton'),
('Quarry'),
('Risinghurst'),
('Quarry Bank'),
('Dudley'),
('Quarry Banks'),
('Quarry Barton'),
('Quarry Batch'),
('Quarry Beach'),
('Quarry Berry'),
('Quarry Brake'),
('Quarry Brow'),
('Quarry Burn'),
('Quarry Clough'),
('Quarry Clump'),
('Quarry Cotts'),
('Quarry Covert'),
('Quarry Dale'),
('Quarry Dene'),
('Quarry Ebb'),
('Quarry Edge'),
('Quarry Ffinant'),
('Quarry Fields'),
('Quarry Gill'),
('Quarry Haven'),
('Quarry Hay'),
('Quarry Head'),
('Quarry Heath'),
('Quarry Hey'),
('Quarry High'),
('Quarry Hills'),
('Quarry Hole'),
('Quarry Hole Covert'),
('Quarry Hollow'),
('Quarry House'),
('Quarry Howe'),
('Quarry Knowe'),
('Quarry Lake'),
('Quarry Leasow'),
('Quarry Line'),
('Quarry Moor Brake'),
('Quarry Oldsworth'),
('Quarry Oval'),
('Quarry Park Clump'),
('Quarry Parks'),
('Quarry Piece'),
('Quarry Pool'),
('Quarry Rigg'),
('Quarry Rock Cove'),
('Quarry Shaw'),
('Quarry Side'),
('Quarry Siding Halt'),
('Quarry Spring'),
('Quarry Steps'),
('Quarry Stream'),
('Quarry Vale'),
('Quarry Well'),
('Quarrybank'),
('Quarrybanks Covert'),
('Quarrybeck'),
('Quarrybrae'),
('Quarrybrook'),
('Quarryclose'),
('Quarrydale'),
('Quarrydam'),
('Quarrydene'),
('Quarryfield'),
('Quarryfields'),
('Quarryflatts'),
('Quarryfoot'),
('Quarryhead'),
('Quarryheads'),
('Quarryhill'),
('Quarryholes'),
('Quarryhouse'),
('Quarryknowe'),
('Quarryknowes'),
('Quarrylands'),
('Quarrymans'),
('Quarrymill Woodland'),
('Quarrypark'),
('Quarryside'),
('Quarrystone'),
('Quarryview'),
('Quarrywood'),
('Quart'),
('Quartains Moss'),
('Quarter'),
('Quarter Bach'),
('Quarter Land'),
('Quarter Mile'),
('Quarter Strip'),
('Quarter Wall'),
('Quarterbank'),
('Quarterbrass'),
('Quarterhouse'),
('Quartermain'),
('Quartermaine'),
('Quartermass'),
('Quartermaster'),
('Quartermile'),
('Quarters'),
('Quarters Spit'),
('Quarterstone'),
('Quarterway'),
('Quarthill'),
('Quartley'),
('Quartleys'),
('Quartly'),
('Quartremaine'),
('Quarts'),
('Quartz'),
('Quashetts'),
('Quassawall Loch'),
('Quat Goose'),
('Quater Deck'),
('Quatford'),
('Quatquoy'),
('Quatrain'),
('Quatre Bras'),
('Quatt'),
('Quatt Malvern'),
('Quave'),
('Quaver'),
('Quaves'),
('Quavey'),
('Quaveys'),
('Quay'),
('Quay Corner'),
('Quay Fold'),
('Quay Geo'),
('Quay Haven'),
('Quay Hole'),
('Quay Pend'),
('Quay Reach'),
('Quay Side'),
('Quay Walls'),
('Quayfield'),
('Quayhead'),
('Quayle'),
('Quayles'),
('Quaynan'),
('Quays'),
('Quaysgate'),
('Quayside'),
('Quba'),
('Quchan'),
('Queach'),
('Quear of Eastafea'),
('Queastybirch'),
('Quebbs'),
('Quebec'),
('Quebec City'),
('Quebec Wynd'),
('Quedgeley'),
('Quedgeley Fieldcourt'),
('Quedgeley Severn Vale'),
('Quee'),
('Quee Ness'),
('Queech'),
('Queel'),
('Queels Knowe'),
('Queen'),
('Queen Adelaide'),
('Queen Adelaides'),
('Queen Adelaides Ride'),
('Queen Alexandra'),
('Queen Alexandra Dock'),
('Queen Alexandra Hospital Home'),
('Queen Alexandras'),
('Queen Ann'),
('Queen Anne'),
('Queen Anne Royal Free'),
('Queen Annes'),
('Queen Anns'),
('Queen Bee'),
('Queen Bertha'),
('Queen Berthas'),
('Queen Bess Rock'),
('Queen Camel'),
('Queen Caroline'),
('Queen Catherine'),
('Queen Charlotte'),
('Queen Charlton'),
('Queen Dart'),
('Queen Down Warren'),
('Queen Edith'),
('Queen Ediths'),
('Queen Eleanor'),
('Queen Eleanor'),
('Buccleuch'),
('Queen Eleanors'),
('Queen Elizabeth'),
('Queen Elizabeth Chase'),
('Queen Elizabeth Diamond Jubilee'),
('Queen Elizabeth Dock'),
('Queen Elizabeth House'),
('Queen Elizabeth II'),
('Queen Elizabeth II Coronation'),
('Queen Elizabeth II Dock'),
('Queen Elizabeth II Jetty'),
('Queen Elizabeth II Storage'),
('Queen Elizabeth II Terminal'),
('Queen Elizabeth ll'),
('Queen Elizabeth The Queen Mother'),
('Queen Elizabeth University'),
('Queen Elizabeths'),
('Queen Elizabeths Island'),
('Queen Emma'),
('Queen Emmas Dyke'),
('Queen Esthers'),
('Queen Ethelburgas'),
('Queen Geos'),
('Queen Headland'),
('Queen Henrietta'),
('Queen Hoo'),
('Queen Isabella'),
('Queen Isabels'),
('Queen Johanna'),
('Queen Katherine'),
('Queen Katherines'),
('Queen Manor'),
('Queen Manor Belt'),
('Queen Margaret'),
('Queen Margaret Fauld'),
('Queen Margaret University'),
('Queen Margarets'),
('Queen Margarets Cove'),
('Queen Margarets Gait'),
('Queen Mary'),
('Queen Mary'),
('Queen Marys'),
('Queen Marys Covert'),
('Queen Marys Dubb'),
('Queen Marys Hospital For Children'),
('Queen Marys House'),
('Queen Marys Pool'),
('Queen Marys Royal Free'),
('Queen Mother'),
('Queen Mother Hall'),
('Queen Mother'),
('Queen Mothers'),
('Queen Oak'),
('Queen of Ho'),
('Queen Philippa'),
('Queen Pool'),
('Queen Rock'),
('Queen Rocks'),
('Queen s Arms'),
('Queen Sonja Kloss'),
('Queen Street Back'),
('Queen Thorne'),
('Queen Vera'),
('Queen Victoria'),
('Queen Victoria Centre'),
('Queen Victoria Memorial'),
('Queen Victorias'),
('Queen Victorias Review Oak'),
('Queenborough'),
('Queenborough'),
('Halfway'),
('Queenborough Spit'),
('Queendale'),
('Queendown'),
('Queener'),
('Queeness'),
('Queenhill'),
('Queenhill Rough'),
('Queenhill Shaw'),
('Queenhills'),
('Queenhithe'),
('Queenholme'),
('Queenhythe'),
('Queenie'),
('Queenie Cliff'),
('Queeniths'),
('Queenmeadow'),
('Queens'),
('Queens Acre'),
('Queens Bower'),
('Queens Cairn'),
('Queens Chase'),
('Queens Circus'),
('Queens Club'),
('Queens Corner'),
('Queens Cottage Grounds'),
('Queens Counsellor Shelter Belt'),
('Queens Court Ride'),
('Queens Crags'),
('Queens Cross'),
('Queens Den'),
('Queens Ditch'),
('Queens Dock'),
('Queens Down'),
('Queens Drive Mossley'),
('Queens Drive Stoneycroft'),
('Queens Drive Walton'),
('Queens Drive West Derby'),
('Queens Elm'),
('Queens Eyot'),
('Queens Fen'),
('Queens Ferry'),
('Queens Fields'),
('Queens Garth'),
('Queens Gate Villas'),
('Queens Grounds'),
('Queens Haugh'),
('Queens Head'),
('Queens Head Wynd'),
('Queens Highway'),
('Queens Hills'),
('Queens Hospital'),
('Queens House'),
('Queens Inclosure'),
('Queens Lancashire'),
('Queens Lea'),
('Queens Ledge'),
('Queens Mere'),
('Queens Mire'),
('Queens Nympton'),
('Queens Own'),
('Queens Passage'),
('Queens Pine'),
('Queens Pool'),
('Queens Promenade'),
('Queens Purse'),
('Queens Quadrant'),
('Queens Reach'),
('Queens Retreat'),
('Queens Ride'),
('Queens Road Peckham'),
('Queens Rock'),
('Queens Sedge'),
('Queens Specialist Building'),
('Queens Staith'),
('Queens Steps'),
('Queens Strip'),
('Queens Vale'),
('Queens Well'),
('Queens Wharf'),
('Queensbank'),
('Queensberry'),
('Queensberry Beeches'),
('Queensberrys'),
('Queensborough'),
('Queensborough Passage'),
('Queensbridge'),
('Queensbridge Dingle'),
('Queensbrook'),
('Queensbury'),
('Queensbury Chase'),
('Queensbury Circle'),
('Queensbury Station'),
('Queensby'),
('Queenscairn'),
('Queenscliffe'),
('Queenscote'),
('Queenscourt'),
('Queenscourt Hospice'),
('Queenscroft'),
('Queensdale'),
('Queensdown'),
('Queenseat'),
('Queensferry'),
('Queensfield'),
('Queensgate'),
('Queenshaugh'),
('Queenshill'),
('Queenshill Garth'),
('Queenshill Lodge'),
('Queensholm'),
('Queenside'),
('Queenside Loch'),
('Queenside Muir'),
('Queensland'),
('Queenslie'),
('Queensmead'),
('Queensmead Lake'),
('Queensmere'),
('Queensmill'),
('Queensmount'),
('Queensport'),
('Queenss'),
('Queensthorpe'),
('Queenstock'),
('Queenston'),
('Queenstown'),
('Queensview'),
('Queensville'),
('Queensway'),
('Queensway Entrance'),
('Queensway House'),
('Queensway Mersey Tunnel'),
('Queensway Tunnel'),
('Queenswell'),
('Queenswood'),
('Queentree'),
('Queenwell'),
('Queenwood'),
('Queenzieburn'),
('Queer'),
('Queestmoor'),
('Queich'),
('Queimados'),
('Queina Waters'),
('Queintin'),
('Quelch'),
('Quelimane'),
('Quell'),
('Quellwood'),
('Quelmans Head Ride'),
('Quemby'),
('Quemerford'),
('Quenby'),
('Quenby Corner'),
('Quench'),
('Quenchwell'),
('Quendale'),
('Quendell'),
('Quendon'),
('Quendon'),
('Rickling'),
('Queniborough'),
('Quenington'),
('Quennell'),
('Quennells'),
('Quennels'),
('Quenneys'),
('Quentin'),
('Quentins'),
('Quercetum'),
('Quercus'),
('Querida'),
('Queripel'),
('Quern'),
('Quern Dyke Holt'),
('Quern Geos'),
('Quern of Grithen'),
('Quern of Whisber'),
('Querneby'),
('Querni Geo'),
('Quernmore'),
('Quernmore Brow'),
('Querns'),
('Querns of the Mull'),
('Quernstone'),
('Querrin'),
('Querétaro'),
('Queslade'),
('Queslett'),
('Quesse'),
('Quest'),
('Quest Hills'),
('Quest Slade'),
('Questant'),
('Quested'),
('Quethiock'),
('Quetlaw'),
('Quetta'),
('Quetzaltenango'),
('Quevedo'),
('Quex'),
('Quey'),
('Quey Firth'),
('Quey Geo'),
('Quey Skerries'),
('Queyin Ness'),
('Queys Houll'),
('Quezon'),
('Quezon City'),
('Qufu'),
('Quhaap Knowe'),
('Quheyinstany Geo'),
('Quhina roo'),
('Quholm'),
('Quhytewoollen'),
('Qui Ayre'),
('Qui Ness'),
('Qui Nhơn'),
('Quibdó'),
('Quibell'),
('Quibells'),
('Quibo'),
('Quibury'),
('Quick'),
('Quick Cleugh'),
('Quick Edge'),
('Quick Moss'),
('Quickbeam'),
('Quickbeams'),
('Quickbourne'),
('Quickbury'),
('Quickcleugh Moss'),
('Quickedge'),
('Quicken'),
('Quicken Tree'),
('Quickening Cleuch'),
('Quickley'),
('Quickly Brow'),
('Quickmoor'),
('Quickningair'),
('Quickrells'),
('Quicks'),
('Quicksand'),
('Quickset'),
('Quicksets'),
('Quicksilver'),
('Quicksrt Drove'),
('Quickstep'),
('Quickswood'),
('Quickthorn'),
('Quickthorns'),
('Quickwell'),
('Quickwood'),
('Quickwoods'),
('Quida'),
('Quida Dale'),
('Quida Ness'),
('Quida Stack'),
('Quidadale'),
('Quidan Ness'),
('Quidditch'),
('Quidenham'),
('Quidenham Mere Water'),
('Quidham'),
('Quidhampton'),
('Quidhampton Southley'),
('Quidi'),
('Quidin'),
('Quien'),
('Quier Houll'),
('Quies'),
('Quiet'),
('Quiet Nook'),
('Quietways'),
('Quigley'),
('Quilberry'),
('Quilco'),
('Quill'),
('Quill Hall'),
('Quillcourt'),
('Quiller Couch'),
('Quillet'),
('Quillets'),
('Quilletts'),
('Quilling'),
('Quillings'),
('Quillot'),
('Quills'),
('Quilmes'),
('Quilow'),
('Quilp'),
('Quilpué'),
('Quilquox'),
('Quilsa Geo'),
('Quilsa Shun'),
('Quilsa Taing'),
('Quilse'),
('Quilse of Hoganeap'),
('Quilston'),
('Quilstyle'),
('Quilt'),
('Quilt Ness'),
('Quilter'),
('Quilters'),
('Quilters Rill'),
('Quilters Straight'),
('Quilts'),
('Quilva Taing'),
('Quilver'),
('Quimperle'),
('Quin'),
('Quina'),
('Quina Stack'),
('Quinag'),
('Quinary'),
('Quinbrookes'),
('Quinbury'),
('Quince'),
('Quince Tree'),
('Quinces'),
('Quinces Corner'),
('Quincewood'),
('Quincey'),
('Quincy'),
('Quindell'),
('Quindry'),
('Quines'),
('Quinesway'),
('Quiney'),
('Quineys'),
('Quineys Leys'),
('Quinion'),
('Quinish'),
('Quinloch'),
('Quinloch Muir'),
('Quinn'),
('Quinnel'),
('Quinnell'),
('Quinney'),
('Quinneys'),
('Quinni Clett'),
('Quinni Geo'),
('Quinni Loch'),
('Quinns'),
('Quins'),
('Quinta'),
('Quinta Fields'),
('Quintain'),
('Quintan'),
('Quintbridge'),
('Quintec'),
('Quinten'),
('Quintet'),
('Quintilis'),
('Quintin'),
('Quintinespie'),
('Quintins Man'),
('Quintinshill'),
('Quinton'),
('Quinton Expressway'),
('Quinton Fields'),
('Quinton House'),
('Quinton Pool'),
('Quintons'),
('Quintonside'),
('Quintrell'),
('Quintrell Downs'),
('Quintus'),
('Quiraing'),
('Quirills Dale'),
('Quirke'),
('Quirnish'),
('Quisters'),
('Quithel'),
('Quither'),
('Quito'),
('Quivals'),
('Quivals Loch'),
('Quivilsda Moss'),
('Quix'),
('Quixhill'),
('Quixley'),
('Quixote'),
('Quixwood'),
('Qujing'),
('Quob'),
('Quobleigh'),
('Quobwell'),
('Quoditch'),
('Quoditchmoor'),
('Quoich Pool'),
('Quoig'),
('Quoiggs'),
('Quoisley Big Mere'),
('Quoisley Little Mere'),
('Quoit'),
('Quoiter'),
('Quoiters'),
('Quoiting'),
('Quoitings'),
('Quoits'),
('Quoits Water Pill'),
('Quomp'),
('Quonister Cleugh'),
('Quorn'),
('Quorn House'),
('Quornden'),
('Quorndon'),
('Quorndon Waters'),
('Quorum'),
('Quothquan'),
('Quothquan Law'),
('Quoy'),
('Quoy Ayre'),
('Quoy Banks'),
('Quoy Geo'),
('Quoy Ness'),
('Quoy Noust'),
('Quoy Ribs'),
('Quoybanks'),
('Quoybrae'),
('Quoyelsh'),
('Quoynalonga Ness'),
('Quoyness'),
('Quoys'),
('Qurayyat'),
('Qureshi'),
('Quwwatul'),
('Quy'),
('Quy Waters'),
('Quys Green or Gainsford'),
('Quzhou'),
('Qwysson'),
('Qā’em Shahr');
-- Down
DELETE FROM Placename WHERE keyword LIKE 'q%';