-- Up

INSERT INTO "Placename"
("keyword")
VALUES
('Quaas Crescent'),
('Quaas Loaning'),
('Quab'),
('Quab Hill'),
('Quab Lane'),
('Quab Lane Close'),
('Quabbs'),
('Quabbs Lane'),
('Quabbs Plantation'),
('Quabbs Road'),
('Quack Copse'),
('Quadling Street'),
('Quadrans Close'),
('Quadrant'),
('Quadrant Close'),
('Quadrant Court'),
('Quadrant East'),
('Quadrant Grove'),
('Quadrant Hall'),
('Quadrant Lane'),
('Quadrant Plantation'),
('Quadrant Plantation South'),
('Quadrant Road'),
('Quadrant Way'),
('Quadrant West'),
('Quadrilateral Covert'),
('Quadrille Avenue'),
('Quadrille Lawns'),
('Quadring'),
('Quadring and Gosberton Donington'),
('Quadring Bank'),
('Quadring Eaudike'),
('Quadring High Fen'),
('Quadring Low Fen'),
('Quadring Road'),
('Quaggs Road'),
('Quaggy Walk'),
('Quagmire Copse'),
('Quagmire Lane'),
('Quagmirebank Wood'),
('Quagrigg Moss'),
('Quags Corner'),
('Quaikin Plantation'),
('Quail Avenue'),
('Quail Close'),
('Quail Corner'),
('Quail Court'),
('Quail Drive'),
('Quail Gardens'),
('Quail Gate'),
('Quail Green'),
('Quail Grove'),
('Quail Holme Road'),
('Quail Meadows'),
('Quail Park Drive'),
('Quail Ridge'),
('Quail Rise'),
('Quail Road'),
('Quail Street'),
('Quail Walk'),
('Quail Way'),
('Quaile Park'),
('Quainton'),
('Quainton Church Of England Combined School'),
('Quainton Close'),
('Quainton Hall School'),
('Quainton Hill'),
('Quainton Road'),
('Quainton Street'),
('Quaintways'),
('Quair Throat'),
('Quaish Lane'),
('Quakefield Road'),
('Quaker Bottom'),
('Quaker Brook Lane'),
('Quaker Close'),
('Quaker Court'),
('Quaker Drive'),
('Quaker Fold'),
('Quaker Green'),
('Quaker Hill'),
('Quaker Lane'),
('Quaker Rise'),
('Quaker Road'),
('Quaker Street'),
('Quaker Terrace'),
('Quaker Way'),
('Quaker Wood'),
('Quaker Yard'),
('Quakerfield'),
('Quakerfields'),
('Quakers Close'),
('Quakers Coppice'),
('Quakers Course'),
('Quakers Court'),
('Quakers Drove'),
('Quakers Field'),
('Quakers Hall Lane'),
('Quakers Hill'),
('Quakers Lane'),
('Quakers Mead'),
('Quakers Meadow'),
('Quakers Mede'),
('Quakers Place'),
('Quakers Plantation'),
('Quakers Plat'),
('Quakers Road'),
('Quakers Row'),
('Quakers Spinney'),
('Quakers Terrace'),
('Quakers View'),
('Quakers Walk'),
('Quakers Way'),
('Quakers Wood'),
('Quakers Yard'),
('Quakerscorner Copse'),
('Quakesick Spinney'),
('Quaking Ash Wiel'),
('Quaking Houses'),
('Quakinghouse Copse'),
('Quakinghouse Lane'),
('Qualcast Road'),
('Quale Road'),
('Qualitas'),
('Quality Corner'),
('Quality Plantation'),
('Quality Row'),
('Quality Row Road'),
('Quality Street'),
('Quality Street Lane'),
('Qualla Dale'),
('Quanea Drove'),
('Quanea Hill'),
('Quaney Field'),
('Quanley Grove'),
('Quant Mews'),
('Quant Park'),
('Quantans Hill'),
('Quanter Ness'),
('Quanterness Skerry'),
('Quantico Close'),
('Quantock Avenue'),
('Quantock Campus'),
('Quantock Close'),
('Quantock Combe'),
('Quantock Common'),
('Quantock Court'),
('Quantock Crescent'),
('Quantock Drive'),
('Quantock Gardens'),
('Quantock Green'),
('Quantock Grove'),
('Quantock Hills'),
('Quantock Meadow'),
('Quantock Mews'),
('Quantock Place'),
('Quantock Rise'),
('Quantock Road'),
('Quantock Street'),
('Quantock Terrace'),
('Quantock Vale'),
('Quantock View'),
('Quantock Way'),
('Quantock Wood'),
('Quantocks'),
('Quantocks Head'),
('Quantocks Road'),
('Quantrelle Court'),
('Quantrill Terrace'),
('Quantry Lane'),
('Quantum Court'),
('Quaperlake Street'),
('Quar Close'),
('Quar Hill Cuttings'),
('Quar Hill Plantation'),
('Quar Road'),
('Quarante-Ans'),
('Quarella'),
('Quarella Crescent'),
('Quarella Road'),
('Quarella Street'),
('Quarely Road'),
('Quarhill Close'),
('Quarhouse'),
('Quarhouse Lane'),
('Quarle Wood'),
('Quarles Close'),
('Quarles Park Road'),
('Quarleston'),
('Quarleston Down'),
('Quarley'),
('Quarley Hill'),
('Quarley Wood'),
('Quarls'),
('Quarlton Drive'),
('Quarlton Fold'),
('Quarmby'),
('Quarmby Croft'),
('Quarmby Fold'),
('Quarmby Road'),
('Quarme Combe Plantation'),
('Quarme Hill'),
('Quarme Lane'),
('Quarme Wood'),
('Quarn Drive'),
('Quarn Street'),
('Quarn Way'),
('Quarndon'),
('Quarndon Common'),
('Quarndon Heights'),
('Quarndon View'),
('Quarnford'),
('Quarr'),
('Quarr Barton'),
('Quarr Close'),
('Quarr Drive'),
('Quarr Hill'),
('Quarr Lane'),
('Quarr Place'),
('Quarr Plantation'),
('Quarr Road'),
('Quarr Wood'),
('Quarr-clydach'),
('Quarrel Burn Reservoir'),
('Quarrel Cleugh'),
('Quarrel Dean'),
('Quarrel Geo'),
('Quarrel Geos'),
('Quarrel Hill'),
('Quarrel Knowe'),
('Quarrel Sand'),
('Quarrel Wood'),
('Quarrelhill Plantation'),
('Quarrels Copse'),
('Quarrelton'),
('Quarrelton Grove'),
('Quarrelton Road'),
('Quarrelwood'),
('Quarrenden'),
('Quarrendon'),
('Quarrendon Avenue'),
('Quarrendon Road'),
('Quarrendon Street'),
('Quarriedene Court'),
('Quarrier Street'),
('Quarriers Village'),
('Quarries Lane'),
('Quarries Plantation'),
('Quarries Way'),
('Quarrington'),
('Quarrington Close'),
('Quarrington Fen'),
('Quarrington Grove'),
('Quarrington Hill'),
('Quarrington Lane'),
('Quarrington Place'),
('Quarrington Road'),
('Quarrington Wood'),
('Quarrolhall Crescent'),
('Quarry and Coton Hill'),
('Quarry and Risinghurst'),
('Quarry Avenue'),
('Quarry Bank'),
('Quarry Bank and Dudley Wood'),
('Quarry Bank Close'),
('Quarry Bank Court'),
('Quarry Bank Lane'),
('Quarry Bank Mews'),
('Quarry Bank Primary School'),
('Quarry Bank Rise'),
('Quarry Bank Road'),
('Quarry Bank Street'),
('Quarry Bank Wood'),
('Quarry Banks'),
('Quarry Banks Plantations'),
('Quarry Barton'),
('Quarry Batch'),
('Quarry Bay'),
('Quarry Beach'),
('Quarry Berry Lane'),
('Quarry Bottom'),
('Quarry Brae'),
('Quarry Brae Primary School'),
('Quarry Brake'),
('Quarry Brow'),
('Quarry Burn'),
('Quarry Burn Lane'),
('Quarry Close'),
('Quarry Close Copse'),
('Quarry Close Plantation'),
('Quarry Close Wood'),
('Quarry Clough'),
('Quarry Clump'),
('Quarry Coppice'),
('Quarry Copse'),
('Quarry Cotts'),
('Quarry Court'),
('Quarry Covert'),
('Quarry Crescent'),
('Quarry Dale'),
('Quarry Dale View'),
('Quarry Dene'),
('Quarry Dene Park'),
('Quarry Drive'),
('Quarry Ebb'),
('Quarry Edge'),
('Quarry End'),
('Quarry Farm Close'),
('Quarry Farm Court'),
('Quarry Farm Road'),
('Quarry Field'),
('Quarry Field Lane'),
('Quarry Field Plantation'),
('Quarry Fields'),
('Quarry Garden Plantation'),
('Quarry Gardens'),
('Quarry Gate'),
('Quarry Gill Wood'),
('Quarry Green'),
('Quarry Green Close'),
('Quarry Ground Plantation'),
('Quarry Grove'),
('Quarry Guards Plantation'),
('Quarry Haven'),
('Quarry Hay'),
('Quarry Head'),
('Quarry Heath'),
('Quarry Heights'),
('Quarry Hey'),
('Quarry High Street'),
('Quarry Hill'),
('Quarry Hill Academy'),
('Quarry Hill Care Home'),
('Quarry Hill Common'),
('Quarry Hill Copse'),
('Quarry Hill Court'),
('Quarry Hill Lane'),
('Quarry Hill Nursing Home'),
('Quarry Hill Park'),
('Quarry Hill Plantation'),
('Quarry Hill Road'),
('Quarry Hill Wood'),
('Quarry Hills'),
('Quarry Hills Close'),
('Quarry Hills Lane'),
('Quarry Hole'),
('Quarry Hole Covert'),
('Quarry Holes Plantation'),
('Quarry Hollow'),
('Quarry House'),
('Quarry House Close'),
('Quarry House Gardens'),
('Quarry House Lane'),
('Quarry Howe'),
('Quarry Knowe'),
('Quarry Knowe Place'),
('Quarry Lake'),
('Quarry Lake Copse'),
('Quarry Lane'),
('Quarry Leasow Wood'),
('Quarry Line Path'),
('Quarry Mead'),
('Quarry Meadows'),
('Quarry Mews'),
('Quarry Moor'),
('Quarry Moor Brake'),
('Quarry Moor Lane'),
('Quarry Moor Park'),
('Quarry Mount'),
('Quarry Mount Mews'),
('Quarry Mount Place'),
('Quarry Mount Primary School'),
('Quarry Mount Street'),
('Quarry Mount Terrace'),
('Quarry Oldsworth Copse'),
('Quarry Oval'),
('Quarry Park'),
('Quarry Park Avenue'),
('Quarry Park Bottom'),
('Quarry Park Close'),
('Quarry Park Clump'),
('Quarry Park Copse'),
('Quarry Park Plantation'),
('Quarry Park Road'),
('Quarry Park Wood'),
('Quarry Parks'),
('Quarry Piece Drive'),
('Quarry Pits Plantation'),
('Quarry Place'),
('Quarry Plantation'),
('Quarry Point'),
('Quarry Pond'),
('Quarry Pond Road'),
('Quarry Pool'),
('Quarry Rigg'),
('Quarry Rise'),
('Quarry Road'),
('Quarry Road East'),
('Quarry Road West'),
('Quarry Rock Cove'),
('Quarry Row'),
('Quarry School Place'),
('Quarry Shaw'),
('Quarry Side'),
('Quarry Siding Halt'),
('Quarry Spring'),
('Quarry Square'),
('Quarry Steps'),
('Quarry Stream'),
('Quarry Street'),
('Quarry Street South'),
('Quarry Terrace'),
('Quarry Vale Grove'),
('Quarry Vale Road'),
('Quarry View'),
('Quarry View Close'),
('Quarry Walk'),
('Quarry Way'),
('Quarry Well Wood'),
('Quarry Wood'),
('Quarry Wood Close'),
('Quarry Wood Court'),
('Quarry Wood Road'),
('Quarry Woods'),
('Quarry Yard'),
('Quarry-Ffinant'),
('Quarrybank'),
('Quarrybank Close'),
('Quarrybank Court'),
('Quarrybank End'),
('Quarrybank Street'),
('Quarrybanks Covert'),
('Quarrybeck Wood'),
('Quarrybrae Avenue'),
('Quarrybrae Court'),
('Quarrybrae Gardens'),
('Quarrybrae Street'),
('Quarrybrook Close'),
('Quarryclose Copse'),
('Quarryclose Plantation'),
('Quarryclose Wood'),
('Quarrydale Academy'),
('Quarrydale Avenue'),
('Quarrydale Close'),
('Quarrydale Drive'),
('Quarrydale Road'),
('Quarrydam Wood'),
('Quarrydene'),
('Quarrydene Drive'),
('Quarryfield Lane'),
('Quarryfield Plantation'),
('Quarryfield Road'),
('Quarryfield Wood'),
('Quarryfields'),
('Quarryflatts Wood'),
('Quarryfoot Gardens'),
('Quarryfoot Green'),
('Quarryfoot Place'),
('Quarryhead'),
('Quarryhead Wood'),
('Quarryheads Lane'),
('Quarryhill'),
('Quarryhill Copse'),
('Quarryhill Court'),
('Quarryhill Plantation'),
('Quarryhill Primary School'),
('Quarryhill Wood'),
('Quarryholes Wood'),
('Quarryhouse Moor'),
('Quarryhouse Wood'),
('Quarryknowe'),
('Quarryknowe Crescent'),
('Quarryknowe Gardens'),
('Quarryknowe Street'),
('Quarrylands Lane'),
('Quarrymans Court'),
('Quarrymans View'),
('Quarrymill Woodland Park'),
('Quarrymoor Plantation'),
('Quarrypark Copse'),
('Quarrypark Drive'),
('Quarrypark Lane'),
('Quarrypark Plantation'),
('Quarrypark Wood'),
('Quarrypit Plantation'),
('Quarryside'),
('Quarryside Court'),
('Quarryside Drive'),
('Quarryside Road'),
('Quarryside Street'),
('Quarrystone Bank'),
('Quarryview'),
('Quarrywood'),
('Quarrywood Avenue'),
('Quarrywood Court'),
('Quarrywood Grove'),
('Quarrywood Hill'),
('Quarrywood Road'),
('Quart Lane'),
('Quartains Moss'),
('Quarter Bach'),
('Quarter Fell'),
('Quarter Gate'),
('Quarter Gate Lane'),
('Quarter Hill'),
('Quarter Land'),
('Quarter Lane'),
('Quarter Mile Lane'),
('Quarter Primary School'),
('Quarter Strip'),
('Quarter Wall Bay'),
('Quarter Wood'),
('Quarter Wood Hill'),
('Quarter Woods'),
('Quarterbank'),
('Quarterbrass Farm Road'),
('Quarterhouse Wood'),
('Quarterknowe Plantation'),
('Quartermain Close'),
('Quartermain Road'),
('Quartermaine Avenue'),
('Quartermass Close'),
('Quartermass Road'),
('Quartermaster Lane'),
('Quartermaster Road'),
('Quartermile Road'),
('Quartermilefield Plantation'),
('Quarters Copse'),
('Quarters Spit'),
('Quarters Wood'),
('Quarterstone'),
('Quarterway Lane'),
('Quarthill Lane'),
('Quartley Hill'),
('Quartleys Wood'),
('Quartly Drive'),
('Quartremaine Road'),
('Quarts'),
('Quarts Moor'),
('Quartz Avenue'),
('Quartz Close'),
('Quartz Court'),
('Quartz Way'),
('Quassawall Loch'),
('Quat Goose Lane'),
('Quater Deck Avenue'),
('Quatford'),
('Quatford Close'),
('Quatford Coppice'),
('Quatford Gardens'),
('Quatquoy'),
('Quatrain Close'),
('Quatre Bras'),
('Quatre Bras Wood'),
('Quatt'),
('Quatt Malvern'),
('Quave Brae'),
('Quaver Lane'),
('Quaves Lane'),
('Quaves Road'),
('Quavey Road'),
('Quaveys Copse'),
('Quaw Plantation'),
('Quay Academy'),
('Quay Brae'),
('Quay Close'),
('Quay Copse'),
('Quay Corner Avenue'),
('Quay Field'),
('Quay Fold'),
('Quay Geo'),
('Quay Haven'),
('Quay Hill'),
('Quay Hole'),
('Quay Lane'),
('Quay Mill Walk'),
('Quay Parade'),
('Quay Pend'),
('Quay Place'),
('Quay Reach'),
('Quay Road'),
('Quay Road North'),
('Quay Side'),
('Quay Street'),
('Quay Terrace'),
('Quay View'),
('Quay View Business Park'),
('Quay View School'),
('Quay Walls'),
('Quay West'),
('Quay Wood'),
('Quayfield Coppice'),
('Quayfield Road'),
('Quayfield Square'),
('Quayfield Wood'),
('Quayhead'),
('Quayle Avenue'),
('Quayle Close'),
('Quayle Court'),
('Quayle Crescent'),
('Quayle Drive'),
('Quayle Grove'),
('Quayles Mews'),
('Quaynan'),
('Quays Avenue'),
('Quays Road'),
('Quaysgate'),
('Quayside'),
('Quayside Close'),
('Quayside Court'),
('Quayside Drive'),
('Quayside East'),
('Quayside Lane'),
('Quayside Mews'),
('Quayside Nursing Home'),
('Quayside Parade'),
('Quayside Road'),
('Quayside Street'),
('Quayside Walk'),
('Quayside Way'),
('Quayside West'),
('Quba Court'),
('Queach Grove'),
('Quear of Eastafea'),
('Queastybirch Lane'),
('Quebbs Coppice'),
('Quebec'),
('Quebec Avenue'),
('Quebec Close'),
('Quebec Drive'),
('Quebec Gardens'),
('Quebec Grove'),
('Quebec Mews'),
('Quebec Place'),
('Quebec Plantation'),
('Quebec Road'),
('Quebec Square'),
('Quebec Street'),
('Quebec Way'),
('Quebec Wood'),
('Quebec Wynd'),
('Quedgeley'),
('Quedgeley Fieldcourt'),
('Quedgeley Severn Vale'),
('Quee Lane'),
('Quee Ness'),
('Queech Lane'),
('Queech Plantation'),
('Queech Wood'),
('Queel'),
('Queels Knowe'),
('Queen Adelaide'),
('Queen Adelaide Mews'),
('Queen Adelaide Road'),
('Queen Adelaide Way'),
('Queen Adelaides Hill'),
('Queen Adelaides Ride'),
('Queen Alexandra Avenue'),
('Queen Alexandra College'),
('Queen Alexandra Dock'),
('Queen Alexandra Hospital'),
('Queen Alexandra Hospital Home'),
('Queen Alexandra Road'),
('Queen Alexandra Road West'),
('Queen Alexandras Way'),
('Queen Ann Drive'),
('Queen Ann Road'),
('Queen Anne Avenue'),
('Queen Anne Close'),
('Queen Anne Court'),
('Queen Anne Drive'),
('Queen Anne Gardens'),
('Queen Anne Gate'),
('Queen Anne High School'),
('Queen Anne Mews'),
('Queen Anne Plantation'),
('Queen Anne Road'),
('Queen Anne Square'),
('Queen Anne Street'),
('Queen Anne Terrace'),
('Queen Annes Avenue'),
('Queen Annes Close'),
('Queen Annes Court'),
('Queen Annes Drive'),
('Queen Annes Gardens'),
('Queen Annes Gate'),
('Queen Annes Grove'),
('Queen Annes Mews'),
('Queen Annes Place'),
('Queen Annes Road'),
('Queen Annes School'),
('Queen Annes Square'),
('Queen Annes Terrace'),
('Queen Annes Way'),
('Queen Anns Grove'),
('Queen Avenue'),
('Queen Bee Court'),
('Queen Bertha Road'),
('Queen Berthas Avenue'),
('Queen Bess Rock'),
('Queen Boudica Primary School'),
('Queen Camel'),
('Queen Caroline Close'),
('Queen Caroline Street'),
('Queen Catherine Road'),
('Queen Charlotte Drive'),
('Queen Charlotte Lane'),
('Queen Charlotte Mews'),
('Queen Charlotte Street'),
('Queen Charlton'),
('Queen Charlton Lane'),
('Queen Close'),
('Queen Copse'),
('Queen Dart Hill'),
('Queen Down Warren'),
('Queen Edith Community Primary School'),
('Queen Edith Drive'),
('Queen Ediths'),
('Queen Ediths Way'),
('Queen Eleanor and Buccleuch'),
('Queen Eleanor Close'),
('Queen Eleanor Drive'),
('Queen Eleanor Primary School'),
('Queen Eleanor Road'),
('Queen Eleanor Street'),
('Queen Eleanor Technology College'),
('Queen Eleanor Terrace'),
('Queen Eleanors Church Of England Junior School'),
('Queen Eleanors Drive'),
('Queen Eleanors Road'),
('Queen Elizabeth Avenue'),
('Queen Elizabeth Chase'),
('Queen Elizabeth Close'),
('Queen Elizabeth Court'),
('Queen Elizabeth Crescent'),
('Queen Elizabeth Dock'),
('Queen Elizabeth Drive'),
('Queen Elizabeth Forest Park'),
('Queen Elizabeth Gardens'),
('Queen Elizabeth Grammar School'),
('Queen Elizabeth Grammer School'),
('Queen Elizabeth Grove'),
('Queen Elizabeth High School'),
('Queen Elizabeth Hospital'),
('Queen Elizabeth House'),
('Queen Elizabeth II Bridge'),
('Queen Elizabeth II Coronation Grove'),
('Queen Elizabeth II Dock'),
('Queen Elizabeth II Jetty'),
('Queen Elizabeth II Jubilee School'),
('Queen Elizabeth II Storage Reservoir'),
('Queen Elizabeth II Terminal'),
('Queen Elizabeth ll Hospital'),
('Queen Elizabeth Place'),
('Queen Elizabeth Plantation'),
('Queen Elizabeth Road'),
('Queen Elizabeth School'),
('Queen Elizabeth Square'),
('Queen Elizabeth Street'),
('Queen Elizabeth The Queen Mother Hospital'),
('Queen Elizabeth University Hospital'),
('Queen Elizabeth Walk'),
('Queen Elizabeth Way'),
('Queen Elizabeths Academy'),
('Queen Elizabeths Avenue'),
('Queen Elizabeths Close'),
('Queen Elizabeths Community College'),
('Queen Elizabeths Drive'),
('Queen Elizabeths Gardens'),
('Queen Elizabeths Girls School'),
('Queen Elizabeths Grammar School'),
('Queen Elizabeths Hospital School'),
('Queen Elizabeths Island'),
('Queen Elizabeths Plantation'),
('Queen Elizabeths School'),
('Queen Elizabeths School Upper'),
('Queen Elizabeths Spinney'),
('Queen Elizabeths Walk'),
('Queen Elizabeths Wood'),
('Queen Emma Place'),
('Queen Emma Primary School'),
('Queen Emma Walk'),
('Queen Emmas Dyke'),
('Queen Emmas Primary School'),
('Queen Esthers Grove'),
('Queen Ethelburgas College'),
('Queen Ethelburgas Gardens'),
('Queen Ethelburgas Park'),
('Queen Gardens'),
('Queen Geos'),
('Queen Headland Lane'),
('Queen Henrietta Place'),
('Queen Hill Wood'),
('Queen Hoo Lane'),
('Queen Isabella Way'),
('Queen Isabels Avenue'),
('Queen Johanna Drive'),
('Queen Johanna Place'),
('Queen Johanna Road'),
('Queen Katherine Road'),
('Queen Katherine Street'),
('Queen Katherines Avenue'),
('Queen Lane'),
('Queen Manor Belt'),
('Queen Manor Road'),
('Queen Margaret Academy'),
('Queen Margaret Close'),
('Queen Margaret Drive'),
('Queen Margaret Fauld'),
('Queen Margaret Gardens'),
('Queen Margaret Hospital'),
('Queen Margaret Park'),
('Queen Margaret Primary School And Childrens Centre'),
('Queen Margaret Road'),
('Queen Margaret Street'),
('Queen Margaret University'),
('Queen Margaret University Way'),
('Queen Margarets Avenue'),
('Queen Margarets Close'),
('Queen Margarets Cove'),
('Queen Margarets Drive'),
('Queen Margarets Gait'),
('Queen Margarets Grove'),
('Queen Margarets Place'),
('Queen Margarets Road'),
('Queen Margarets Road Industrial Estate'),
('Queen Margarets School'),
('Queen Mary Avenue'),
('Queen Mary Avenue Infant & Nursery School'),
('Queen Mary Close'),
('Queen Mary Court'),
('Queen Mary Crescent'),
('Queen Mary Drive'),
('Queen Mary Gardens'),
('Queen Mary Grove'),
('Queen Mary Mews'),
('Queen Mary Reservoir'),
('Queen Mary Rise'),
('Queen Mary Road'),
('Queen Mary Street'),
('Queen Mary University Of London'),
('Queen Mary Way'),
('Queen Marys Avenue'),
('Queen Marys Close'),
('Queen Marys College'),
('Queen Marys Covert'),
('Queen Marys Drive'),
('Queen Marys Dubb'),
('Queen Marys Grammar School'),
('Queen Marys High School'),
('Queen Marys Hospital'),
('Queen Marys Hospital For Children'),
('Queen Marys House'),
('Queen Marys Lane'),
('Queen Marys Plantation'),
('Queen Marys Pool'),
('Queen Marys Road'),
('Queen Marys Royal Free Hospital'),
('Queen Marys School'),
('Queen Marys Walk'),
('Queen Mother Hall'),
('Queen Mother Square'),
('Queen Mothers Drive'),
('Queen North Wood'),
('Queen Oak'),
('Queen Oak Plantation'),
('Queen of Ho'),
('Queen Parade'),
('Queen Philippa Street'),
('Queen Pool'),
('Queen Road'),
('Queen Rock'),
('Queen Rocks'),
('Queen s Arms Yard'),
('Queen Sonja Kloss'),
('Queen Square'),
('Queen Square Avenue'),
('Queen Square Bus Station'),
('Queen Square Court'),
('Queen Square Place'),
('Queen Street'),
('Queen Street Back Road'),
('Queen Street Close'),
('Queen Street East'),
('Queen Street Gardens East'),
('Queen Street Gardens West'),
('Queen Street Mews'),
('Queen Street North'),
('Queen Street Place'),
('Queen Street South'),
('Queen Street West'),
('Queen Terrace'),
('Queen Thorne'),
('Queen Vera Road'),
('Queen Victoria Avenue'),
('Queen Victoria Court'),
('Queen Victoria Crescent'),
('Queen Victoria Drive'),
('Queen Victoria Gate'),
('Queen Victoria Memorial Hospital'),
('Queen Victoria Primary School'),
('Queen Victoria Road'),
('Queen Victoria School'),
('Queen Victoria Street'),
('Queen Victoria Way'),
('Queen Victorias Plantation'),
('Queen Victorias Review Oak'),
('Queen Victorias Walk'),
('Queen Wood'),
('Queen Wood Close'),
('Queenborough'),
('Queenborough and Halfway'),
('Queenborough Drive'),
('Queenborough Gardens'),
('Queenborough Lane'),
('Queenborough Road'),
('Queenborough School & Nursery'),
('Queenborough Spit'),
('Queendale Court'),
('Queendown Avenue'),
('Queener Point'),
('Queeness Road'),
('Queenhill'),
('Queenhill Drive'),
('Queenhill Road'),
('Queenhill Rough'),
('Queenhill Shaw'),
('Queenhills Copse'),
('Queenhithe'),
('Queenholme Way'),
('Queenhythe Crescent'),
('Queenhythe Road'),
('Queenie Cliff'),
('Queenie Wood'),
('Queeniths'),
('Queenmeadow Copse'),
('Queens Acre'),
('Queens Approach'),
('Queens Avenue'),
('Queens Avenue South'),
('Queens Bank'),
('Queens Bay Crescent'),
('Queens Bower'),
('Queens Bower Road'),
('Queens Bridge Road'),
('Queens Cairn'),
('Queens Campus'),
('Queens Campus Durham University'),
('Queens Chase'),
('Queens Church Of England Academy'),
('Queens Circus'),
('Queens Close'),
('Queens Club Gardens'),
('Queens College'),
('Queens College Junior School'),
('Queens Coppice'),
('Queens Copse'),
('Queens Copse Lane'),
('Queens Corner'),
('Queens Cottage Grounds'),
('Queens Cottages'),
('Queens Counsellor Shelter Belt'),
('Queens Court'),
('Queens Court Ride'),
('Queens Crags'),
('Queens Crescent'),
('Queens Crescent Primary School'),
('Queens Croft'),
('Queens Croft Community School'),
('Queens Cross'),
('Queens Den'),
('Queens Diamond Jubilee Plantation 1897'),
('Queens Ditch'),
('Queens Dock'),
('Queens Dock Avenue'),
('Queens Down'),
('Queens Drive'),
('Queens Drive (Wavertree)'),
('Queens Drive Close'),
('Queens Drive Infants School'),
('Queens Drive Lane'),
('Queens Drive Mossley Hill'),
('Queens Drive Primary School'),
('Queens Drive Stoneycroft'),
('Queens Drive Walton'),
('Queens Drive West'),
('Queens Drive West Derby'),
('Queens Elm Square'),
('Queens Eyot'),
('Queens Farm Gardens'),
('Queens Farm Road'),
('Queens Fen'),
('Queens Ferry'),
('Queens Field'),
('Queens Fields East'),
('Queens Fields West'),
('Queens Gardens'),
('Queens Garth'),
('Queens Gate'),
('Queens Gate Gardens'),
('Queens Gate Lane'),
('Queens Gate Mews'),
('Queens Gate Place'),
('Queens Gate Place Mews'),
('Queens Gate Road'),
('Queens Gate School'),
('Queens Gate Street'),
('Queens Gate Terrace'),
('Queens Gate Villas Road'),
('Queens Green'),
('Queens Grounds'),
('Queens Grove'),
('Queens Grove Road'),
('Queens Haugh'),
('Queens Head'),
('Queens Head Close'),
('Queens Head Lane'),
('Queens Head Road'),
('Queens Head Street'),
('Queens Head Wynd'),
('Queens Highway'),
('Queens Hill'),
('Queens Hill Crescent'),
('Queens Hill Drive'),
('Queens Hill Education Unit'),
('Queens Hill Gardens'),
('Queens Hill Primary and Nursery School'),
('Queens Hill Rise'),
('Queens Hills'),
('Queens Hospital'),
('Queens Hospital Close'),
('Queens House'),
('Queens Inclosure Primary School'),
('Queens Lancashire Avenue'),
('Queens Lancashire Way'),
('Queens Lane'),
('Queens Lane North'),
('Queens Lane South'),
('Queens Lea'),
('Queens Ledge'),
('Queens Lodge Nursing Home'),
('Queens Manor School And Special Needs Unit'),
('Queens Mead'),
('Queens Mead Road'),
('Queens Meadow'),
('Queens Mere'),
('Queens Mews'),
('Queens Mill Road'),
('Queens Mire'),
('Queens Nursing Home'),
('Queens Nympton'),
('Queens Own Place'),
('Queens Parade'),
('Queens Parade Close'),
('Queens Parade Place'),
('Queens Park'),
('Queens Park Academy'),
('Queens Park Academy Community Nursery'),
('Queens Park Avenue'),
('Queens Park Church Of England And United Reformed'),
('Queens Park Church Of England And United Reformed (Controlled) Primary School'),
('Queens Park Close'),
('Queens Park Community School'),
('Queens Park Drive'),
('Queens Park Gardens'),
('Queens Park High School'),
('Queens Park Infant Academy'),
('Queens Park Mews'),
('Queens Park Place'),
('Queens Park Primary School'),
('Queens Park Rise'),
('Queens Park Road'),
('Queens Park South Drive'),
('Queens Park Street'),
('Queens Park Terrace'),
('Queens Park View'),
('Queens Park Way'),
('Queens Park West Drive'),
('Queens Passage'),
('Queens Pine'),
('Queens Place'),
('Queens Plantation'),
('Queens Point'),
('Queens Pool'),
('Queens Promenade'),
('Queens Purse Wood'),
('Queens Quadrant'),
('Queens Reach'),
('Queens Retreat'),
('Queens Ride'),
('Queens Rise'),
('Queens Road'),
('Queens Road Academy'),
('Queens Road East'),
('Queens Road North'),
('Queens Road Peckham'),
('Queens Road South'),
('Queens Road West'),
('Queens Rock'),
('Queens Row'),
('Queens School'),
('Queens Sedge Moor'),
('Queens Specialist Building'),
('Queens Square'),
('Queens Staith Road'),
('Queens Steps'),
('Queens Street'),
('Queens Strip'),
('Queens Terrace'),
('Queens Terrace Lane'),
('Queens Vale'),
('Queens View'),
('Queens View Crescent'),
('Queens Walk'),
('Queens Way'),
('Queens Way Forest Drive'),
('Queens Well Avenue'),
('Queens Well Wood'),
('Queens Wharf'),
('Queens Wood'),
('Queens Wood Road'),
('Queens Yard'),
('Queensbank Avenue'),
('Queensberry'),
('Queensberry Avenue'),
('Queensberry Beeches'),
('Queensberry Brae'),
('Queensberry Court'),
('Queensberry Gardens'),
('Queensberry Mews West'),
('Queensberry Nursing Home'),
('Queensberry Place'),
('Queensberry Road'),
('Queensberry Square'),
('Queensberry Street'),
('Queensberry View'),
('Queensberry Way'),
('Queensberrys'),
('Queensborough Drive'),
('Queensborough Gardens'),
('Queensborough Mews'),
('Queensborough Passage'),
('Queensborough Road'),
('Queensborough Square'),
('Queensborough Terrace'),
('Queensbridge'),
('Queensbridge Dingle'),
('Queensbridge Drive'),
('Queensbridge Park'),
('Queensbridge Primary School'),
('Queensbridge Road'),
('Queensbridge School'),
('Queensbrook'),
('Queensbury'),
('Queensbury Academy'),
('Queensbury Avenue'),
('Queensbury Chase'),
('Queensbury Circle Parade'),
('Queensbury Close'),
('Queensbury Court'),
('Queensbury Drive'),
('Queensbury Gardens'),
('Queensbury Gate'),
('Queensbury Grove'),
('Queensbury Lane'),
('Queensbury Mews'),
('Queensbury Park Drive'),
('Queensbury Place'),
('Queensbury Road'),
('Queensbury School'),
('Queensbury Square'),
('Queensbury Station'),
('Queensbury Station Parade'),
('Queensbury Street'),
('Queensbury Way'),
('Queensby Avenue'),
('Queensby Place'),
('Queensby Road'),
('Queenscairn Hill'),
('Queenscairn Wood'),
('Queenscliffe Road'),
('Queenscote'),
('Queenscourt'),
('Queenscourt Avenue'),
('Queenscourt Hospice'),
('Queenscourt Road'),
('Queenscroft Road'),
('Queensdale Avenue'),
('Queensdale Close'),
('Queensdale Crescent'),
('Queensdale Place'),
('Queensdale Road'),
('Queensdale Walk'),
('Queensdown'),
('Queensdown Gardens'),
('Queensdown Road'),
('Queensdown School Road'),
('Queenseat Hill'),
('Queensferry'),
('Queensferry Campus'),
('Queensferry Close'),
('Queensferry Gardens'),
('Queensferry High School'),
('Queensferry Parade'),
('Queensferry Primary School'),
('Queensferry Road'),
('Queensferry Street'),
('Queensferry Street Lane'),
('Queensferry Terrace'),
('Queensfield'),
('Queensfield Drive'),
('Queensgate'),
('Queensgate Drive'),
('Queensgate Foundation Primary School'),
('Queensgate Gardens'),
('Queensgate Mews'),
('Queensgate Nursing Home'),
('Queensgate Primary School'),
('Queensgate Square'),
('Queensgate Wood'),
('Queenshaugh Drive'),
('Queenshill Approach'),
('Queenshill Avenue'),
('Queenshill Crescent'),
('Queenshill Drive'),
('Queenshill Gardens'),
('Queenshill Garth'),
('Queenshill Lodge'),
('Queenshill Road'),
('Queenshill View'),
('Queenshill Walk'),
('Queenshill Wood'),
('Queensholm Avenue'),
('Queensholm Close'),
('Queensholm Crescent'),
('Queensholm Drive'),
('Queenside Crescent'),
('Queenside Hill'),
('Queenside Loch'),
('Queenside Muir'),
('Queensland'),
('Queensland Avenue'),
('Queensland Close'),
('Queensland Court'),
('Queensland Crescent'),
('Queensland Drive'),
('Queensland Gardens'),
('Queensland Grove'),
('Queensland Lane East'),
('Queensland Lane West'),
('Queensland Place'),
('Queensland Road'),
('Queensland Street'),
('Queenslie'),
('Queenslie Street'),
('Queensmead'),
('Queensmead Avenue'),
('Queensmead Close'),
('Queensmead Court'),
('Queensmead Lake'),
('Queensmead Primary Academy'),
('Queensmead Road'),
('Queensmead School'),
('Queensmere'),
('Queensmere Close'),
('Queensmere Drive'),
('Queensmere Road'),
('Queensmill Road'),
('Queensmill School'),
('Queensmount'),
('Queensport Close'),
('Queenss Court'),
('Queensthorpe Avenue'),
('Queensthorpe Close'),
('Queensthorpe Rise'),
('Queensthorpe Road'),
('Queenstock Lane'),
('Queenston Road'),
('Queenstown'),
('Queenstown Gardens'),
('Queenstown Road'),
('Queensview Drive'),
('Queensville'),
('Queensville Avenue'),
('Queensville Bridge'),
('Queensville Road'),
('Queensway'),
('Queensway (Mersey Tunnel)'),
('Queensway (Tunnel)'),
('Queensway Avenue South'),
('Queensway Close'),
('Queensway Community Junior School'),
('Queensway Court'),
('Queensway Crescent'),
('Queensway Drive'),
('Queensway Entrance (Mersey Tunnel)'),
('Queensway House'),
('Queensway Infant School And Nursery'),
('Queensway Meadows'),
('Queensway North'),
('Queensway Place'),
('Queensway Primary School & Nursery'),
('Queensway Roman Catholic Primary School'),
('Queensway School'),
('Queensway South'),
('Queenswell Infant & Nursery School'),
('Queenswell Junior School'),
('Queenswell Road'),
('Queenswood'),
('Queenswood Avenue'),
('Queenswood Close'),
('Queenswood Court'),
('Queenswood Crescent'),
('Queenswood Drive'),
('Queenswood Gardens'),
('Queenswood Gate'),
('Queenswood Green'),
('Queenswood Grove'),
('Queenswood Mount'),
('Queenswood Park'),
('Queenswood Primary School And Nursery'),
('Queenswood Rise'),
('Queenswood Road'),
('Queenswood School'),
('Queentree Coppice'),
('Queenwell'),
('Queenwood'),
('Queenwood Avenue'),
('Queenwood Grove'),
('Queenwood Plantation'),
('Queenwood Rise'),
('Queenwood Road'),
('Queenzieburn'),
('Queer Wood'),
('Queesmill Secondary School'),
('Queestmoor Wood'),
('Queich Court'),
('Queich Place'),
('Queina Waters'),
('Queintin Road'),
('Quelch Close'),
('Quell Copse'),
('Quell Lane'),
('Quell Wood'),
('Quellwood Common'),
('Quelmans Head Ride'),
('Quemby Close'),
('Quemerford'),
('Quemerford Common'),
('Quemerford Gate'),
('Quemerford Lodge Plantation'),
('Quemerford Road'),
('Quenby Corner'),
('Quenby Crescent'),
('Quenby Drive'),
('Quenby Lane'),
('Quenby Park'),
('Quenby Road'),
('Quenby Street'),
('Quenby Way'),
('Quench Road'),
('Quenchwell'),
('Quenchwell Road'),
('Quendale'),
('Quendale Drive'),
('Quendell Walk'),
('Quendon'),
('Quendon and Rickling'),
('Quendon Avenue'),
('Quendon Drive'),
('Quendon Road'),
('Quendon Way'),
('Quendon Wood'),
('Queniborough'),
('Queniborough Church Of England Primary School'),
('Queniborough Road'),
('Quenington'),
('Quenington Close'),
('Quennell Close'),
('Quennell Mews'),
('Quennell Way'),
('Quennells Hill'),
('Quennels Pond Copse'),
('Quenneys Close'),
('Quentin Avenue'),
('Quentin Close'),
('Quentin Drive'),
('Quentin Gardens'),
('Quentin Place'),
('Quentin Rise'),
('Quentin Road'),
('Quentin Street'),
('Quentin Way'),
('Quentins Copse'),
('Quercetum Close'),
('Quercus Road'),
('Querida Close'),
('Queripel Close'),
('Queripel Mews'),
('Quern Dyke Holt'),
('Quern Geos'),
('Quern of Grithen'),
('Quern of Whisber'),
('Quern Road'),
('Quern Way'),
('Querneby Avenue'),
('Querneby Close'),
('Querneby Road'),
('Querni Geo'),
('Quernmore'),
('Quernmore Avenue'),
('Quernmore Brow'),
('Quernmore CE (Controlled) Primary School'),
('Quernmore Close'),
('Quernmore Drive'),
('Quernmore Park'),
('Quernmore Road'),
('Quernmore Walk'),
('Querns Lane'),
('Querns of the Mull'),
('Querns Place'),
('Querns Road'),
('Quernstone Court'),
('Quernstone Lane'),
('Querrin Street'),
('Queslade Close'),
('Queslett'),
('Queslett Road'),
('Queslett Road East'),
('Queslett Way'),
('Quesse Wood'),
('Quest Avenue'),
('Quest Close'),
('Quest End'),
('Quest Hills'),
('Quest Hills Road'),
('Quest Place'),
('Quest Slade'),
('Questant Lane'),
('Quested Road'),
('Quested Way'),
('Quethiock'),
('Quethiock Church Of England (Voluntary Aided) Scho'),
('Quethiock Church Of England (Voluntary Aided) School'),
('Quetlaw Road'),
('Quetta Road'),
('Quex Mews'),
('Quex Park'),
('Quex Road'),
('Quex View Road'),
('Quey Firth'),
('Quey Geo'),
('Quey Skerries'),
('Queyin Ness'),
('Queys Houll'),
('Quhaap Knowe'),
('Quheyinstany Geo'),
('Quhina-roo'),
('Quholm'),
('Quhytewoollen Hill'),
('Quhytewoollen Plantation'),
('Qui Ayre'),
('Qui Ness'),
('Quibell Road'),
('Quibells Lane'),
('Quibo Lane'),
('Quibury Close'),
('Quick Cleugh'),
('Quick Close'),
('Quick Edge'),
('Quick Hill Road'),
('Quick Lane'),
('Quick Moor'),
('Quick Moss'),
('Quick Road'),
('Quick Row'),
('Quick Street'),
('Quick View'),
('Quick Wood'),
('Quickbeam Hill'),
('Quickbeams'),
('Quickbourne Lane'),
('Quickburn Plantation'),
('Quickbury'),
('Quickcleugh Moss'),
('Quickedge Lane'),
('Quickedge Road'),
('Quicken Tree Wood'),
('Quicken Wood'),
('Quickening Cleuch'),
('Quickley Lane'),
('Quickley Rise'),
('Quickly Brow'),
('Quickmoor Lane'),
('Quickningair Hill'),
('Quickrells Avenue'),
('Quicks Green'),
('Quicks Plantation'),
('Quicks Road'),
('Quicksand Lane'),
('Quicksaw Plantation'),
('Quickset Close'),
('Quickset Road'),
('Quicksets'),
('Quicksilver Crescent'),
('Quicksilver Street'),
('Quicksilver Way'),
('Quicksrt Drove'),
('Quickstep Close'),
('Quickswood'),
('Quickswood Close'),
('Quickswood Drive'),
('Quickswood Green'),
('Quickthorn Close'),
('Quickthorn Crescent'),
('Quickthorns'),
('Quickwell Hill'),
('Quickwood'),
('Quickwood Close'),
('Quickwoods'),
('Quida'),
('Quida Dale'),
('Quida Ness'),
('Quida Stack'),
('Quidadale'),
('Quidan Ness'),
('Quidditch Lane'),
('Quidenham'),
('Quidenham Court'),
('Quidenham Mere Water'),
('Quidenham Park'),
('Quidenham Road'),
('Quidham Street'),
('Quidhampton'),
('Quidhampton Pond'),
('Quidhampton Southley Copse'),
('Quidhampton Wood'),
('Quidi Moor'),
('Quien Hill'),
('Quien Plantation'),
('Quier Houll'),
('Quies'),
('Quiet Close'),
('Quiet Lane'),
('Quiet Nook'),
('Quiet Street'),
('Quietways'),
('Quigley Avenue'),
('Quigley Street'),
('Quilberry Drive'),
('Quilco'),
('Quill'),
('Quill Copse'),
('Quill Court'),
('Quill Hall Lane'),
('Quill Street'),
('Quillcourt'),
('Quiller Couch Way'),
('Quillet Road'),
('Quillets Road'),
('Quilletts Close'),
('Quilling Close'),
('Quillings Way'),
('Quills'),
('Quilow Lane'),
('Quilp Drive'),
('Quilp Street'),
('Quilquox'),
('Quilsa Geo'),
('Quilsa Shun'),
('Quilsa Taing'),
('Quilse of Hoganeap'),
('Quilston Wood'),
('Quilstyle Road'),
('Quilt Hill'),
('Quilt Ness'),
('Quilter Avenue'),
('Quilter Close'),
('Quilter Drive'),
('Quilter Grove'),
('Quilter Meadow'),
('Quilter Road'),
('Quilter Street'),
('Quilter Way'),
('Quilters Close'),
('Quilters Drive'),
('Quilters Infant School'),
('Quilters Junior School'),
('Quilters Place'),
('Quilters Rill'),
('Quilters Straight'),
('Quilters Way'),
('Quilters Wood'),
('Quilters Yard'),
('Quilva Taing'),
('Quilver Close'),
('Quimperle Way'),
('Quin Court'),
('Quin Crescent'),
('Quin Square'),
('Quin Street'),
('Quina Brook'),
('Quina Stack'),
('Quinag'),
('Quinbrookes'),
('Quinbury End'),
('Quince'),
('Quince Close'),
('Quince Court'),
('Quince Drive'),
('Quince Hill'),
('Quince Hill Wood'),
('Quince Lane'),
('Quince Mews'),
('Quince Orchard'),
('Quince Plantations'),
('Quince Road'),
('Quince Tree Close'),
('Quince Tree Way'),
('Quince Way'),
('Quinceborough Plantation'),
('Quinces Corner'),
('Quinces Croft'),
('Quincewood Gardens'),
('Quincey Drive'),
('Quincey Road'),
('Quincey Row'),
('Quincy Close'),
('Quincy Meadows'),
('Quincy Rise'),
('Quincy Road'),
('Quincy Way'),
('Quindell Place'),
('Quindry'),
('Quines Close'),
('Quines Hill Road'),
('Quinesway'),
('Quiney Way'),
('Quineys Leys'),
('Quineys Road'),
('Quinion Close'),
('Quinish Point'),
('Quinloch Muir'),
('Quinloch Wood'),
('Quinn Close'),
('Quinn Court'),
('Quinn Meadows'),
('Quinn Street'),
('Quinn Way'),
('Quinnel Close'),
('Quinnell Drive'),
('Quinnell Street'),
('Quinnell Way'),
('Quinney Crescent'),
('Quinneys Court'),
('Quinneys Lane'),
('Quinneys Place'),
('Quinni Clett'),
('Quinni Geo'),
('Quinni Loch'),
('Quinns Croft'),
('Quins Croft'),
('Quinta Close'),
('Quinta Drive'),
('Quinta Fields'),
('Quinta Mews'),
('Quinta Park'),
('Quinta Road'),
('Quinta Terrace'),
('Quintain Mews'),
('Quintan Avenue'),
('Quintans Plantation'),
('Quintbridge Close'),
('Quintec Court'),
('Quinten Wood'),
('Quintet Close'),
('Quintilis'),
('Quintin Avenue'),
('Quintin Bottom'),
('Quintin Close'),
('Quintin Place'),
('Quintin Road'),
('Quintinespie Hill'),
('Quintinespie Plantation'),
('Quintins Man'),
('Quintinshill Drive'),
('Quintinshill Place'),
('Quinton'),
('Quinton Avenue'),
('Quinton Church Primary School'),
('Quinton Close'),
('Quinton Drive'),
('Quinton Expressway'),
('Quinton Fields'),
('Quinton Gardens'),
('Quinton Green'),
('Quinton Grove'),
('Quinton House'),
('Quinton House School'),
('Quinton Lane'),
('Quinton Parade'),
('Quinton Park'),
('Quinton Place'),
('Quinton Pool'),
('Quinton Primary School'),
('Quinton Rise'),
('Quinton Road'),
('Quinton Road West'),
('Quinton Street'),
('Quinton Walk'),
('Quinton Way'),
('Quintons Lane'),
('Quintons Road'),
('Quintonside'),
('Quintrell Avenue'),
('Quintrell Close'),
('Quintrell Downs'),
('Quintrell Gardens'),
('Quintrell Road'),
('Quintus Close'),
('Quintus Place'),
('Quiraing View'),
('Quirills Dale'),
('Quirke Street'),
('Quirnish'),
('Quisters'),
('Quithel Wood'),
('Quither'),
('Quither Common'),
('Quivals'),
('Quivals Loch'),
('Quivilsda Moss'),
('Quix Hill'),
('Quixhill Bank'),
('Quixhill Close'),
('Quixhill Drive'),
('Quixhill Lane'),
('Quixley Street'),
('Quixote Crescent'),
('Quixwood Moor'),
('Quob Copse'),
('Quob Farm Close'),
('Quob Lane'),
('Quobleigh Pond'),
('Quobwell Copse'),
('Quobwell Plantations'),
('Quoditch'),
('Quoditchmoor Plantations'),
('Quoich Pool'),
('Quoig'),
('Quoiggs Wood'),
('Quoisley Big Mere'),
('Quoisley Little Mere'),
('Quoit'),
('Quoit Green'),
('Quoiter Way'),
('Quoiters Court'),
('Quoiting Green Road'),
('Quoitings Drive'),
('Quoits Close'),
('Quoits Copse'),
('Quoits Field'),
('Quoits Meadow'),
('Quoits Water Pill'),
('Quoits Wood'),
('Quomp'),
('Quomp Copse'),
('Quonister Cleugh'),
('Quorn'),
('Quorn & Barrow'),
('Quorn and Mountsorrel Castle'),
('Quorn and Woodhouse'),
('Quorn Avenue'),
('Quorn Close'),
('Quorn Crescent'),
('Quorn Drive'),
('Quorn Gardens'),
('Quorn Grove'),
('Quorn House Park'),
('Quorn Mews'),
('Quorn Park'),
('Quorn Rise'),
('Quorn Road'),
('Quorn Street'),
('Quorn Way'),
('Quornden Wood'),
('Quorndon'),
('Quorndon Crescent'),
('Quorndon Rise'),
('Quorndon Terrace'),
('Quorndon Waters Court'),
('Quothquan'),
('Quothquan Law'),
('Quoy Ayre'),
('Quoy Banks'),
('Quoy Geo'),
('Quoy Hill'),
('Quoy Ness'),
('Quoy Noust'),
('Quoy Ribs'),
('Quoybanks'),
('Quoybanks Crescent'),
('Quoybanks Drive'),
('Quoybanks Place'),
('Quoybrae'),
('Quoyelsh'),
('Quoynalonga Ness'),
('Quoyness'),
('Quoys'),
('Quoys Road'),
('Qureshi View'),
('Quwwat Ul Islam Girls School'),
('Quwwatul Education Centre'),
('Quy Court'),
('Quy Road'),
('Quy Waters'),
('Quys Green or Gainsford End'),
('Qwysson Avenue');

-- Down

DELETE FROM "Placename" WHERE "keyword" LIKE 'q%';
