-- Up
INSERT INTO Placename (keyword)
VALUES
('Qalat Sukkar'),
('Qalyub'),
('Qamishli'),
('Qarchak'),
('Qazvin'),
('Qena'),
('Qianjiang'),
('Qingdao'),
('Qingtongxia'),
('Qinhuangdao'),
('Qinyang'),
('Qitaihe'),
('Qods'),
('Qom'),
('Quaas Loaning'),
('Quab Hill'),
('Quab Lane'),
('Quabbs Lane'),
('Quabbs Road'),
('Quack Copse'),
('Quadling Street'),
('Quadrans Close'),
('Quadrant'),
('Quadrant Close'),
('Quadrant Court'),
('Quadrant East'),
('Quadrant Grove'),
('Quadrant Hall'),
('Quadrant Lane'),
('Quadrant Road'),
('Quadrant Way'),
('Quadrant West'),
('Quadrilateral Covert'),
('Quadrille Avenue'),
('Quadrille Lawns'),
('Quadring'),
('Quadring Bank'),
('Quadring Eaudike'),
('Quadring High Fen'),
('Quadring Low Fen'),
('Quadring Road'),
('Quaggs Road'),
('Quaggy Walk'),
('Quagmire Copse'),
('Quagmire Lane'),
('Quagmirebank Wood'),
('Quagrigg Moss'),
('Quags Corner'),
('Quail Avenue'),
('Quail Close'),
('Quail Corner'),
('Quail Court'),
('Quail Drive'),
('Quail Gardens'),
('Quail Gate'),
('Quail Green'),
('Quail Grove'),
('Quail Holme'),
('Quail Meadows'),
('Quail Park'),
('Quail Ridge'),
('Quail Rise'),
('Quail Road'),
('Quail Street'),
('Quail Walk'),
('Quail Way'),
('Quaile Park'),
('Quainton Close'),
('Quainton Hill'),
('Quainton Road'),
('Quainton Street'),
('Quaintways'),
('Quair Throat'),
('Quaish Lane'),
('Quakefield Road'),
('Quaker Bottom'),
('Quaker Brook'),
('Quaker Close'),
('Quaker Court'),
('Quaker Drive'),
('Quaker Fold'),
('Quaker Green'),
('Quaker Hill'),
('Quaker Lane'),
('Quaker Rise'),
('Quaker Road'),
('Quaker Street'),
('Quaker Terrace'),
('Quaker Way'),
('Quaker Wood'),
('Quaker Yard'),
('Quakerfield'),
('Quakerfields'),
('Quakers Close'),
('Quakers Coppice'),
('Quakers Course'),
('Quakers Court'),
('Quakers Drove'),
('Quakers Field'),
('Quakers Hall'),
('Quakers Hill'),
('Quakers Lane'),
('Quakers Mead'),
('Quakers Meadow'),
('Quakers Mede'),
('Quakers Place'),
('Quakers Plat'),
('Quakers Road'),
('Quakers Row'),
('Quakers Spinney'),
('Quakers Terrace'),
('Quakers View'),
('Quakers Walk'),
('Quakers Way'),
('Quakers Wood'),
('Quakers Yard'),
('Quakerscorner Copse'),
('Quakesick Spinney'),
('Quaking Ash Wiel'),
('Quaking Houses'),
('Quakinghouse Copse'),
('Quakinghouse Lane'),
('Qualcast Road'),
('Quale Road'),
('Qualitas'),
('Quality Corner'),
('Quality Row'),
('Quality Street'),
('Qualla Dale'),
('Quanea Drove'),
('Quanea Hill'),
('Quaney Field'),
('Quanley Grove'),
('Quant Mews'),
('Quant Park'),
('Quantans Hill'),
('Quanter Ness'),
('Quanterness Skerry'),
('Quantico Close'),
('Quantock Avenue'),
('Quantock Close'),
('Quantock Combe'),
('Quantock Common'),
('Quantock Court'),
('Quantock Drive'),
('Quantock Gardens'),
('Quantock Green'),
('Quantock Grove'),
('Quantock Hills'),
('Quantock Meadow'),
('Quantock Mews'),
('Quantock Place'),
('Quantock Rise'),
('Quantock Road'),
('Quantock Street'),
('Quantock Terrace'),
('Quantock Vale'),
('Quantock View'),
('Quantock Way'),
('Quantock Wood'),
('Quantocks'),
('Quantocks Head'),
('Quantocks Road'),
('Quantrelle Court'),
('Quantrill Terrace'),
('Quantry Lane'),
('Quantum Court'),
('Quaperlake Street'),
('Quar Close'),
('Quar Hill Cuttings'),
('Quar Road'),
('Quarante Ans'),
('Quarella'),
('Quarella Road'),
('Quarella Street'),
('Quarely Road'),
('Quarhill Close'),
('Quarhouse'),
('Quarhouse Lane'),
('Quarle Wood'),
('Quarles Close'),
('Quarles Park'),
('Quarleston'),
('Quarleston Down'),
('Quarley'),
('Quarley Hill'),
('Quarley Wood'),
('Quarls'),
('Quarlton Drive'),
('Quarlton Fold'),
('Quarmby Croft'),
('Quarmby Fold'),
('Quarmby Road'),
('Quarme Hill'),
('Quarme Lane'),
('Quarme Wood'),
('Quarn Drive'),
('Quarn Street'),
('Quarn Way'),
('Quarndon'),
('Quarndon Common'),
('Quarndon Heights'),
('Quarndon View'),
('Quarnford'),
('Quarr'),
('Quarr Barton'),
('Quarr Close'),
('Quarr clydach'),
('Quarr Drive'),
('Quarr Hill'),
('Quarr Lane'),
('Quarr Place'),
('Quarr Road'),
('Quarr Wood'),
('Quarrel Burn'),
('Quarrel Cleugh'),
('Quarrel Dean'),
('Quarrel Geo'),
('Quarrel Geos'),
('Quarrel Hill'),
('Quarrel Knowe'),
('Quarrel Sand'),
('Quarrel Wood'),
('Quarrels Copse'),
('Quarrelton'),
('Quarrelton Grove'),
('Quarrelton Road'),
('Quarrelwood'),
('Quarrenden'),
('Quarrendon'),
('Quarrendon Avenue'),
('Quarrendon Road'),
('Quarrendon Street'),
('Quarriedene Court'),
('Quarrier Street'),
('Quarriers Village'),
('Quarries Lane'),
('Quarries Way'),
('Quarrington Close'),
('Quarrington Fen'),
('Quarrington Grove'),
('Quarrington Hill'),
('Quarrington Lane'),
('Quarrington Place'),
('Quarrington Road'),
('Quarrington Wood'),
('Quarrolhall'),
('Quarry'),
('Quarry and Coton'),
('Quarry and Risinghurst'),
('Quarry Avenue'),
('Quarry Bank'),
('Quarry Bank Court'),
('Quarry Banks'),
('Quarry Barton'),
('Quarry Batch'),
('Quarry Bay'),
('Quarry Beach'),
('Quarry Berry'),
('Quarry Bottom'),
('Quarry Brae'),
('Quarry Brake'),
('Quarry Brow'),
('Quarry Burn'),
('Quarry Close'),
('Quarry Clough'),
('Quarry Clump'),
('Quarry Coppice'),
('Quarry Copse'),
('Quarry Cotts'),
('Quarry Court'),
('Quarry Covert'),
('Quarry Dale'),
('Quarry Dene'),
('Quarry Drive'),
('Quarry Ebb'),
('Quarry Edge'),
('Quarry End'),
('Quarry Farm'),
('Quarry Farm Court'),
('Quarry Ffinant'),
('Quarry Field'),
('Quarry Fields'),
('Quarry Gardens'),
('Quarry Gate'),
('Quarry Gill'),
('Quarry Green'),
('Quarry Grove'),
('Quarry Haven'),
('Quarry Hay'),
('Quarry Head'),
('Quarry Heath'),
('Quarry Heights'),
('Quarry Hey'),
('Quarry High'),
('Quarry Hill'),
('Quarry Hill Court'),
('Quarry Hills'),
('Quarry Hole'),
('Quarry Hole Covert'),
('Quarry Hollow'),
('Quarry House'),
('Quarry Howe'),
('Quarry Knowe'),
('Quarry Lake'),
('Quarry Lane'),
('Quarry Leasow'),
('Quarry Line'),
('Quarry Mead'),
('Quarry Meadows'),
('Quarry Mews'),
('Quarry Moor'),
('Quarry Moor Brake'),
('Quarry Mount'),
('Quarry Oldsworth'),
('Quarry Oval'),
('Quarry Park'),
('Quarry Park Clump'),
('Quarry Parks'),
('Quarry Piece'),
('Quarry Place'),
('Quarry Point'),
('Quarry Pond'),
('Quarry Pool'),
('Quarry Rigg'),
('Quarry Rise'),
('Quarry Road'),
('Quarry Rock Cove'),
('Quarry Row'),
('Quarry Shaw'),
('Quarry Side'),
('Quarry Siding Halt'),
('Quarry Spring'),
('Quarry Square'),
('Quarry Steps'),
('Quarry Stream'),
('Quarry Street'),
('Quarry Strip'),
('Quarry Terrace'),
('Quarry Vale'),
('Quarry View'),
('Quarry Walk'),
('Quarry Way'),
('Quarry Well'),
('Quarry Wood'),
('Quarry Wood Court'),
('Quarry Woods'),
('Quarry Yard'),
('Quarrybank'),
('Quarrybank Close'),
('Quarrybank Court'),
('Quarrybank End'),
('Quarrybank Street'),
('Quarrybanks Covert'),
('Quarrybeck Wood'),
('Quarrybrae Avenue'),
('Quarrybrae Court'),
('Quarrybrae Gardens'),
('Quarrybrae Street'),
('Quarrybrook Close'),
('Quarryclose Copse'),
('Quarryclose Wood'),
('Quarrydale Avenue'),
('Quarrydale Close'),
('Quarrydale Drive'),
('Quarrydale Road'),
('Quarrydam Wood'),
('Quarrydene'),
('Quarrydene Drive'),
('Quarryfield Lane'),
('Quarryfield Road'),
('Quarryfield Wood'),
('Quarryfields'),
('Quarryflatts Wood'),
('Quarryfoot Gardens'),
('Quarryfoot Green'),
('Quarryfoot Place'),
('Quarryhead'),
('Quarryhead Wood'),
('Quarryheads Lane'),
('Quarryhill'),
('Quarryhill Copse'),
('Quarryhill Court'),
('Quarryhill Wood'),
('Quarryholes Wood'),
('Quarryhouse Moor'),
('Quarryhouse Wood'),
('Quarryknowe'),
('Quarryknowe Gardens'),
('Quarryknowe Street'),
('Quarryknowes'),
('Quarrylands Lane'),
('Quarrymans Court'),
('Quarrymans View'),
('Quarrymill Woodland'),
('Quarrypark Copse'),
('Quarrypark Drive'),
('Quarrypark Lane'),
('Quarrypark Wood'),
('Quarryside'),
('Quarryside Court'),
('Quarryside Drive'),
('Quarryside Road'),
('Quarryside Street'),
('Quarrystone Bank'),
('Quarryview'),
('Quarrywood'),
('Quarrywood Avenue'),
('Quarrywood Court'),
('Quarrywood Grove'),
('Quarrywood Hill'),
('Quarrywood Road'),
('Quart Lane'),
('Quartains Moss'),
('Quarter Bach'),
('Quarter Fell'),
('Quarter Gate'),
('Quarter Hill'),
('Quarter Land'),
('Quarter Lane'),
('Quarter Mile'),
('Quarter Strip'),
('Quarter Wall'),
('Quarter Wood'),
('Quarter Woods'),
('Quarterbank'),
('Quarterbrass Farm'),
('Quarterhouse Wood'),
('Quartermain Close'),
('Quartermain Road'),
('Quartermaine Avenue'),
('Quartermass Close'),
('Quartermass Road'),
('Quartermaster Lane'),
('Quartermaster Road'),
('Quartermile Road'),
('Quarters Copse'),
('Quarters Spit'),
('Quarters Wood'),
('Quarterstone'),
('Quarterway Lane'),
('Quarthill Lane'),
('Quartley Hill'),
('Quartleys Wood'),
('Quartly Drive'),
('Quartremaine Road'),
('Quarts'),
('Quarts Moor'),
('Quartz Avenue'),
('Quartz Close'),
('Quartz Court'),
('Quartz Way'),
('Quashetts'),
('Quassawall Loch'),
('Quat Goose'),
('Quater Deck'),
('Quatford'),
('Quatford Close'),
('Quatford Coppice'),
('Quatford Gardens'),
('Quatquoy'),
('Quatrain Close'),
('Quatre Bras'),
('Quatt'),
('Quatt Malvern'),
('Quaver Lane'),
('Quaves Lane'),
('Quaves Road'),
('Quavey Road'),
('Quaveys Copse'),
('Quay Brae'),
('Quay Close'),
('Quay Copse'),
('Quay Corner'),
('Quay Field'),
('Quay Fold'),
('Quay Geo'),
('Quay Haven'),
('Quay Hill'),
('Quay Hole'),
('Quay Lane'),
('Quay Mill'),
('Quay Parade'),
('Quay Pend'),
('Quay Place'),
('Quay Reach'),
('Quay Road'),
('Quay Side'),
('Quay Street'),
('Quay Terrace'),
('Quay View'),
('Quay Walls'),
('Quay West'),
('Quay Wood'),
('Quayfield Coppice'),
('Quayfield Road'),
('Quayfield Square'),
('Quayfield Wood'),
('Quayhead'),
('Quayle Avenue'),
('Quayle Close'),
('Quayle Court'),
('Quayle Drive'),
('Quayle Grove'),
('Quayles Mews'),
('Quays Avenue'),
('Quays Road'),
('Quaysgate'),
('Quayside'),
('Quayside Close'),
('Quayside Court'),
('Quayside Drive'),
('Quayside East'),
('Quayside Lane'),
('Quayside Mews'),
('Quayside Parade'),
('Quayside Road'),
('Quayside Street'),
('Quayside Walk'),
('Quayside Way'),
('Quayside West'),
('Quba Court'),
('Queach Grove'),
('Quear of Eastafea'),
('Queastybirch Lane'),
('Quebbs Coppice'),
('Quebec Avenue'),
('Quebec City'),
('Quebec Close'),
('Quebec Drive'),
('Quebec Gardens'),
('Quebec Grove'),
('Quebec Mews'),
('Quebec Place'),
('Quebec Road'),
('Quebec Square'),
('Quebec Street'),
('Quebec Way'),
('Quebec Wood'),
('Quebec Wynd'),
('Quedgeley'),
('Quedgeley Fieldcourt'),
('Quedgeley Severn Vale'),
('Quee Lane'),
('Quee Ness'),
('Queech'),
('Queech Lane'),
('Queech Wood'),
('Queel'),
('Queels Knowe'),
('Queen Adelaide'),
('Queen Adelaides'),
('Queen Adelaides Ride'),
('Queen Alexandra'),
('Queen Alexandra Dock'),
('Queen Alexandras'),
('Queen Ann'),
('Queen Anne'),
('Queen Anne Court'),
('Queen Anne Royal Free'),
('Queen Annes'),
('Queen Annes Court'),
('Queen Anns'),
('Queen Avenue'),
('Queen Bee Court'),
('Queen Bertha'),
('Queen Berthas'),
('Queen Bess'),
('Queen Camel'),
('Queen Caroline'),
('Queen Catherine'),
('Queen Charlotte'),
('Queen Charlton'),
('Queen Close'),
('Queen Copse'),
('Queen Dart'),
('Queen Down Warren'),
('Queen Edith'),
('Queen Ediths'),
('Queen Eleanor'),
('Queen Eleanors'),
('Queen Elizabeth'),
('Queen Elizabeth Chase'),
('Queen Elizabeth Court'),
('Queen Elizabeth Dock'),
('Queen Elizabeth House'),
('Queen Elizabeth II'),
('Queen Elizabeth II Dock'),
('Queen Elizabeth II Jetty'),
('Queen Elizabeth II Terminal'),
('Queen Elizabeth ll'),
('Queen Elizabeths'),
('Queen Elizabeths Island'),
('Queen Emma'),
('Queen Emmas Dyke'),
('Queen Esthers'),
('Queen Ethelburgas'),
('Queen Gardens'),
('Queen Geos'),
('Queen Headland'),
('Queen Henrietta'),
('Queen Hill'),
('Queen Hoo'),
('Queen Isabella'),
('Queen Isabels'),
('Queen Johanna'),
('Queen Katherine'),
('Queen Katherines'),
('Queen Lane'),
('Queen Manor'),
('Queen Manor Belt'),
('Queen Margaret'),
('Queen Margaret Fauld'),
('Queen Margaret University'),
('Queen Margarets'),
('Queen Margarets Cove'),
('Queen Margarets Gait'),
('Queen Mary'),
('Queen Mary Court'),
('Queen Marys'),
('Queen Marys Covert'),
('Queen Marys Dubb'),
('Queen Marys House'),
('Queen Marys Pool'),
('Queen Marys Royal Free'),
('Queen Mother'),
('Queen Mother Court'),
('Queen Mother Hall'),
('Queen Mothers'),
('Queen North'),
('Queen Oak'),
('Queen of Ho'),
('Queen Parade'),
('Queen Philippa'),
('Queen Pool'),
('Queen Road'),
('Queen Rock'),
('Queen Rocks'),
('Queen s Arms'),
('Queen Sonja Kloss'),
('Queen Square'),
('Queen Square Court'),
('Queen Street'),
('Queen Street Back'),
('Queen Terrace'),
('Queen Thorne'),
('Queen Vera'),
('Queen Victoria'),
('Queen Victoria Centre'),
('Queen Victoria Court'),
('Queen Victoria Memorial'),
('Queen Victorias'),
('Queen Victorias Review Oak'),
('Queen Wood'),
('Queenborough'),
('Queenborough and Halfway'),
('Queenborough Drive'),
('Queenborough Gardens'),
('Queenborough Lane'),
('Queenborough Road'),
('Queenborough Spit'),
('Queendale Court'),
('Queendown Avenue'),
('Queener Point'),
('Queeness Road'),
('Queenhill'),
('Queenhill Drive'),
('Queenhill Road'),
('Queenhill Rough'),
('Queenhill Shaw'),
('Queenhills Copse'),
('Queenhithe'),
('Queenholme Way'),
('Queenhythe'),
('Queenhythe Road'),
('Queenie Cliff'),
('Queenie Wood'),
('Queeniths'),
('Queenmeadow Copse'),
('Queens'),
('Queens Acre'),
('Queens Approach'),
('Queens Avenue'),
('Queens Bank'),
('Queens Bay'),
('Queens Bower'),
('Queens Bridge'),
('Queens Cairn'),
('Queens Chase'),
('Queens Circus'),
('Queens Close'),
('Queens Club'),
('Queens Coppice'),
('Queens Copse'),
('Queens Corner'),
('Queens Cottage Grounds'),
('Queens Cottages'),
('Queens Counsellor Shelter Belt'),
('Queens Court'),
('Queens Court Ride'),
('Queens Crags'),
('Queens Croft'),
('Queens Cross'),
('Queens Den'),
('Queens Ditch'),
('Queens Dock'),
('Queens Down'),
('Queens Drive'),
('Queens Drive Mossley'),
('Queens Drive Stoneycroft'),
('Queens Drive Walton'),
('Queens Drive West Derby'),
('Queens Elm'),
('Queens Eyot'),
('Queens Farm'),
('Queens Fen'),
('Queens Ferry'),
('Queens Field'),
('Queens Fields'),
('Queens Forest'),
('Queens Gardens'),
('Queens Garth'),
('Queens Gate'),
('Queens Gate Villas'),
('Queens Green'),
('Queens Grounds'),
('Queens Grove'),
('Queens Haugh'),
('Queens Head'),
('Queens Head Wynd'),
('Queens Highway'),
('Queens Hill'),
('Queens Hills'),
('Queens Hospital'),
('Queens House'),
('Queens Inclosure'),
('Queens Lancashire'),
('Queens Lane'),
('Queens Lea'),
('Queens Ledge'),
('Queens Mead'),
('Queens Meadow'),
('Queens Mere'),
('Queens Mews'),
('Queens Mill'),
('Queens Mire'),
('Queens Nympton'),
('Queens Own'),
('Queens Parade'),
('Queens Park'),
('Queens Passage'),
('Queens Pine'),
('Queens Place'),
('Queens Point'),
('Queens Pool'),
('Queens Promenade'),
('Queens Purse'),
('Queens Quadrant'),
('Queens Reach'),
('Queens Retreat'),
('Queens Ride'),
('Queens Rise'),
('Queens Road'),
('Queens Road Peckham'),
('Queens Rock'),
('Queens Row'),
('Queens Sedge'),
('Queens Specialist Building'),
('Queens Square'),
('Queens Staith'),
('Queens Steps'),
('Queens Street'),
('Queens Strip'),
('Queens Terrace'),
('Queens Vale'),
('Queens View'),
('Queens Walk'),
('Queens Way'),
('Queens Well'),
('Queens Wharf'),
('Queens Wood'),
('Queens Yard'),
('Queensbank Avenue'),
('Queensberry Avenue'),
('Queensberry Beeches'),
('Queensberry Court'),
('Queensberry Gardens'),
('Queensberry Mews'),
('Queensberry Place'),
('Queensberry Road'),
('Queensberry Square'),
('Queensberry Street'),
('Queensberry View'),
('Queensberry Way'),
('Queensberrys'),
('Queensborough Drive'),
('Queensborough Gardens'),
('Queensborough Mews'),
('Queensborough Passage'),
('Queensborough Road'),
('Queensborough Square'),
('Queensborough Terrace'),
('Queensbridge'),
('Queensbridge Dingle'),
('Queensbridge Drive'),
('Queensbridge Park'),
('Queensbridge Road'),
('Queensbrook'),
('Queensbury'),
('Queensbury Avenue'),
('Queensbury Chase'),
('Queensbury Circle'),
('Queensbury Close'),
('Queensbury Court'),
('Queensbury Drive'),
('Queensbury Gardens'),
('Queensbury Gate'),
('Queensbury Grove'),
('Queensbury Lane'),
('Queensbury Mews'),
('Queensbury Park'),
('Queensbury Place'),
('Queensbury Road'),
('Queensbury Square'),
('Queensbury Station'),
('Queensbury Street'),
('Queensbury Way'),
('Queensby Avenue'),
('Queensby Place'),
('Queensby Road'),
('Queenscairn Hill'),
('Queenscairn Wood'),
('Queenscliffe Road'),
('Queenscote'),
('Queenscourt'),
('Queenscourt Avenue'),
('Queenscourt Hospice'),
('Queenscourt Road'),
('Queenscroft Road'),
('Queensdale'),
('Queensdale Avenue'),
('Queensdale Close'),
('Queensdale Place'),
('Queensdale Road'),
('Queensdale Walk'),
('Queensdown'),
('Queensdown Gardens'),
('Queensdown Road'),
('Queenseat Hill'),
('Queensferry'),
('Queensferry Close'),
('Queensferry Gardens'),
('Queensferry Parade'),
('Queensferry Road'),
('Queensferry Street'),
('Queensferry Terrace'),
('Queensfield'),
('Queensfield Drive'),
('Queensgate'),
('Queensgate Drive'),
('Queensgate Gardens'),
('Queensgate Mews'),
('Queensgate Square'),
('Queensgate Wood'),
('Queenshaugh Drive'),
('Queenshill'),
('Queenshill Approach'),
('Queenshill Avenue'),
('Queenshill Drive'),
('Queenshill Gardens'),
('Queenshill Garth'),
('Queenshill Lodge'),
('Queenshill Road'),
('Queenshill View'),
('Queenshill Walk'),
('Queenshill Wood'),
('Queensholm'),
('Queensholm Avenue'),
('Queensholm Close'),
('Queensholm Drive'),
('Queenside'),
('Queenside Hill'),
('Queenside Loch'),
('Queenside Muir'),
('Queensland'),
('Queensland Avenue'),
('Queensland Close'),
('Queensland Court'),
('Queensland Drive'),
('Queensland Gardens'),
('Queensland Grove'),
('Queensland Lane'),
('Queensland Place'),
('Queensland Road'),
('Queensland Street'),
('Queenslie'),
('Queenslie Street'),
('Queensmead'),
('Queensmead Avenue'),
('Queensmead Close'),
('Queensmead Court'),
('Queensmead Lake'),
('Queensmead Road'),
('Queensmere'),
('Queensmere Close'),
('Queensmere Drive'),
('Queensmere Road'),
('Queensmill Road'),
('Queensmount'),
('Queensport Close'),
('Queenss Court'),
('Queensthorpe Avenue'),
('Queensthorpe Close'),
('Queensthorpe Rise'),
('Queensthorpe Road'),
('Queenstock Lane'),
('Queenston Road'),
('Queenstown'),
('Queenstown Gardens'),
('Queenstown Road'),
('Queensview Drive'),
('Queensville'),
('Queensville Avenue'),
('Queensville Bridge'),
('Queensville Road'),
('Queensway'),
('Queensway Avenue'),
('Queensway Close'),
('Queensway Court'),
('Queensway Drive'),
('Queensway Entrance'),
('Queensway House'),
('Queensway Meadows'),
('Queensway Mersey Tunnel'),
('Queensway Place'),
('Queensway Tunnel'),
('Queenswell Road'),
('Queenswood'),
('Queenswood Avenue'),
('Queenswood Close'),
('Queenswood Court'),
('Queenswood Drive'),
('Queenswood Gardens'),
('Queenswood Gate'),
('Queenswood Green'),
('Queenswood Grove'),
('Queenswood Mount'),
('Queenswood Park'),
('Queenswood Rise'),
('Queenswood Road'),
('Queentree Coppice'),
('Queenwell'),
('Queenwood'),
('Queenwood Avenue'),
('Queenwood Grove'),
('Queenwood Rise'),
('Queenwood Road'),
('Queenzieburn'),
('Queer Wood'),
('Queestmoor Wood'),
('Queich Court'),
('Queich Place'),
('Queimados'),
('Queina Waters'),
('Queintin Road'),
('Quelch Close'),
('Quelimane'),
('Quell Copse'),
('Quell Lane'),
('Quell Wood'),
('Quellwood Common'),
('Quelmans Head Ride'),
('Quemby Close'),
('Quemerford'),
('Quemerford Common'),
('Quemerford Gate'),
('Quemerford Road'),
('Quenby Corner'),
('Quenby Drive'),
('Quenby Lane'),
('Quenby Park'),
('Quenby Road'),
('Quenby Street'),
('Quenby Way'),
('Quench Road'),
('Quenchwell'),
('Quenchwell Road'),
('Quendale'),
('Quendale Drive'),
('Quendell Walk'),
('Quendon'),
('Quendon Avenue'),
('Quendon Drive'),
('Quendon Road'),
('Quendon Way'),
('Quendon Wood'),
('Queniborough'),
('Queniborough Road'),
('Quenington'),
('Quenington Close'),
('Quennell Close'),
('Quennell Mews'),
('Quennell Way'),
('Quennells Hill'),
('Quennels Pond'),
('Quenneys Close'),
('Quentin Avenue'),
('Quentin Close'),
('Quentin Drive'),
('Quentin Gardens'),
('Quentin Gate'),
('Quentin Mount'),
('Quentin Place'),
('Quentin Rise'),
('Quentin Road'),
('Quentin Street'),
('Quentin Strip'),
('Quentin View'),
('Quentin Walk'),
('Quentin Way'),
('Quentins Close'),
('Quentins Copse'),
('Quentins Hill'),
('Quercetum Close'),
('Quercus Road'),
('Querida Close'),
('Queripel Close'),
('Queripel Mews'),
('Quern'),
('Quern Dyke Holt'),
('Quern Geos'),
('Quern of Grithen'),
('Quern of Whisber'),
('Quern Road'),
('Quern Way'),
('Querneby Avenue'),
('Querneby Close'),
('Querneby Road'),
('Querni Geo'),
('Quernmore'),
('Quernmore Avenue'),
('Quernmore Brow'),
('Quernmore Close'),
('Quernmore Drive'),
('Quernmore Park'),
('Quernmore Road'),
('Quernmore Walk'),
('Querns Lane'),
('Querns of the Mull'),
('Querns Place'),
('Querns Road'),
('Quernstone Court'),
('Quernstone Lane'),
('Querrin Street'),
('Queslade Close'),
('Queslett Road'),
('Queslett Way'),
('Quesse Wood'),
('Quest Avenue'),
('Quest Close'),
('Quest End'),
('Quest Hills'),
('Quest Place'),
('Quest Slade'),
('Questant Lane'),
('Quested Road'),
('Quested Way'),
('Quethiock'),
('Quetlaw Road'),
('Quetta'),
('Quetta Road'),
('Quetzaltenango'),
('Quex Mews'),
('Quex Park'),
('Quex Road'),
('Quex View'),
('Quey Firth'),
('Quey Geo'),
('Quey Skerries'),
('Queyin Ness'),
('Queys Houll'),
('Quezon City'),
('Qufu'),
('Quhaap Knowe'),
('Quheyinstany Geo'),
('Quhina roo'),
('Quholm'),
('Quhytewoollen Hill'),
('Qui Ayre'),
('Qui Ness'),
('Qui Nhơn'),
('Quibdó'),
('Quibell Road'),
('Quibells Lane'),
('Quibo Lane'),
('Quibury Close'),
('Quick Cleugh'),
('Quick Close'),
('Quick Edge'),
('Quick Hill'),
('Quick Lane'),
('Quick Moor'),
('Quick Moss'),
('Quick Road'),
('Quick Row'),
('Quick Street'),
('Quick View'),
('Quick Wood'),
('Quickbeam Hill'),
('Quickbeams'),
('Quickbourne Lane'),
('Quickbury'),
('Quickcleugh Moss'),
('Quickedge Lane'),
('Quickedge Road'),
('Quicken Tree'),
('Quicken Wood'),
('Quickening Cleuch'),
('Quickley Lane'),
('Quickley Rise'),
('Quickly Brow'),
('Quickmoor Lane'),
('Quickningair Hill'),
('Quickrells Avenue'),
('Quicks Green'),
('Quicks Road'),
('Quicksand Lane'),
('Quickset Close'),
('Quickset Road'),
('Quicksets'),
('Quicksilver'),
('Quicksilver Street'),
('Quicksilver Way'),
('Quicksrt Drove'),
('Quickstep Close'),
('Quickswood'),
('Quickswood Close'),
('Quickswood Drive'),
('Quickswood Green'),
('Quickthorn'),
('Quickthorn Close'),
('Quickthorns'),
('Quickwell Hill'),
('Quickwood'),
('Quickwood Close'),
('Quickwoods'),
('Quida'),
('Quida Dale'),
('Quida Ness'),
('Quida Stack'),
('Quidadale'),
('Quidan Ness'),
('Quidditch Lane'),
('Quidenham Court'),
('Quidenham Mere Water'),
('Quidenham Park'),
('Quidenham Road'),
('Quidham Street'),
('Quidhampton'),
('Quidhampton Pond'),
('Quidhampton Southley'),
('Quidhampton Wood'),
('Quidi Moor'),
('Quidin'),
('Quie'),
('Quien'),
('Quien Hill'),
('Quier Houll'),
('Quies'),
('Quiet Close'),
('Quiet Lane'),
('Quiet Nook'),
('Quiet Street'),
('Quietways'),
('Quigley Avenue'),
('Quigley Street'),
('Quilberry Drive'),
('Quill Copse'),
('Quill Court'),
('Quill Hall'),
('Quill Street'),
('Quillcourt'),
('Quiller Couch'),
('Quillet Road'),
('Quillets'),
('Quillets Road'),
('Quilletts'),
('Quilletts Close'),
('Quilling Close'),
('Quillings Way'),
('Quillot'),
('Quills'),
('Quilmes'),
('Quilow Lane'),
('Quilp Drive'),
('Quilp Street'),
('Quilpué'),
('Quilquox'),
('Quilsa Geo'),
('Quilsa Shun'),
('Quilsa Taing'),
('Quilse'),
('Quilse of Hoganeap'),
('Quilston Wood'),
('Quilstyle Road'),
('Quilt Hill'),
('Quilt Ness'),
('Quilter Avenue'),
('Quilter Close'),
('Quilter Drive'),
('Quilter Grove'),
('Quilter Meadow'),
('Quilter Road'),
('Quilter Street'),
('Quilter Way'),
('Quilters Close'),
('Quilters Drive'),
('Quilters Place'),
('Quilters Rill'),
('Quilters Straight'),
('Quilters Way'),
('Quilters Wood'),
('Quilters Yard'),
('Quilts'),
('Quilva Taing'),
('Quilver Close'),
('Quimperle Way'),
('Quin Court'),
('Quin Square'),
('Quin Street'),
('Quina Brook'),
('Quina Stack'),
('Quinag'),
('Quinary'),
('Quinbrookes'),
('Quinbury End'),
('Quince Close'),
('Quince Court'),
('Quince Drive'),
('Quince Hill'),
('Quince Lane'),
('Quince Mews'),
('Quince Orchard'),
('Quince Road'),
('Quince Tree'),
('Quince Way'),
('Quinces Corner'),
('Quinces Croft'),
('Quincewood Gardens'),
('Quincey Drive'),
('Quincey Road'),
('Quincey Row'),
('Quincy Close'),
('Quincy Meadows'),
('Quincy Rise'),
('Quincy Road'),
('Quincy Way'),
('Quindell Place'),
('Quindry'),
('Quines Close'),
('Quines Hill'),
('Quinesway'),
('Quiney Way'),
('Quineys Leys'),
('Quineys Road'),
('Quinion Close'),
('Quinish Point'),
('Quinloch Muir'),
('Quinloch Wood'),
('Quinn Close'),
('Quinn Court'),
('Quinn Meadows'),
('Quinn Street'),
('Quinn Way'),
('Quinnel Close'),
('Quinnell Drive'),
('Quinnell Street'),
('Quinnell Way'),
('Quinneys Court'),
('Quinneys Lane'),
('Quinneys Place'),
('Quinni Clett'),
('Quinni Geo'),
('Quinni Loch'),
('Quinns Croft'),
('Quins Croft'),
('Quinta Close'),
('Quinta Drive'),
('Quinta Fields'),
('Quinta Mews'),
('Quinta Park'),
('Quinta Road'),
('Quinta Terrace'),
('Quintain Mews'),
('Quintan Avenue'),
('Quintbridge Close'),
('Quintec Court'),
('Quinten Wood'),
('Quintet Close'),
('Quintilis'),
('Quintin Avenue'),
('Quintin Bottom'),
('Quintin Close'),
('Quintin Field'),
('Quintin Gardens'),
('Quintin Park'),
('Quintin Place'),
('Quintin Road'),
('Quintinespie Hill'),
('Quintins Close'),
('Quintins Man'),
('Quintinshill Drive'),
('Quintinshill Place'),
('Quinton Avenue'),
('Quinton Close'),
('Quinton Drive'),
('Quinton Expressway'),
('Quinton Fields'),
('Quinton Gardens'),
('Quinton Green'),
('Quinton Grove'),
('Quinton House'),
('Quinton Lane'),
('Quinton Parade'),
('Quinton Park'),
('Quinton Place'),
('Quinton Pool'),
('Quinton Rise'),
('Quinton Road'),
('Quinton Street'),
('Quinton Walk'),
('Quinton Way'),
('Quintons Court'),
('Quintons Lane'),
('Quintons Road'),
('Quintonside'),
('Quintrell Avenue'),
('Quintrell Close'),
('Quintrell Downs'),
('Quintrell Gardens'),
('Quintrell Road'),
('Quintus Close'),
('Quintus Place'),
('Quiraing View'),
('Quirills Dale'),
('Quirke Street'),
('Quirnish'),
('Quisters'),
('Quithel Wood'),
('Quither'),
('Quither Common'),
('Quivals'),
('Quivals Loch'),
('Quivilsda Moss'),
('Quivox'),
('Quivox Road'),
('Quix Hill'),
('Quixhill Bank'),
('Quixhill Close'),
('Quixhill Drive'),
('Quixhill Lane'),
('Quixley Street'),
('Quixote'),
('Quixwood Moor'),
('Qujing'),
('Quob Copse'),
('Quob Farm'),
('Quob Lane'),
('Quobleigh Pond'),
('Quobwell'),
('Quobwell Copse'),
('Quoditch'),
('Quoditchmoor'),
('Quoich'),
('Quoich Hills'),
('Quoich Pool'),
('Quoig'),
('Quoiggs Wood'),
('Quoisley Big Mere'),
('Quoisley Little Mere'),
('Quoit'),
('Quoit Green'),
('Quoiter Way'),
('Quoiters Court'),
('Quoiting Green'),
('Quoitings Drive'),
('Quoits Close'),
('Quoits Copse'),
('Quoits Field'),
('Quoits Meadow'),
('Quoits Water Pill'),
('Quoits Wood'),
('Quomp'),
('Quomp Copse'),
('Quonister Cleugh'),
('Quorn Avenue'),
('Quorn Close'),
('Quorn Drive'),
('Quorn Gardens'),
('Quorn Grove'),
('Quorn House'),
('Quorn Mews'),
('Quorn Park'),
('Quorn Rise'),
('Quorn Road'),
('Quorn Street'),
('Quorn Way'),
('Quornden Wood'),
('Quorndon'),
('Quorndon Rise'),
('Quorndon Terrace'),
('Quorndon Waters Court'),
('Quorum'),
('Quothquan Law'),
('Quoy Ayre'),
('Quoy Banks'),
('Quoy Geo'),
('Quoy Hill'),
('Quoy Ness'),
('Quoy Noust'),
('Quoy Ribs'),
('Quoybanks'),
('Quoybanks Drive'),
('Quoybanks Place'),
('Quoybrae'),
('Quoyelsh'),
('Quoynalonga Ness'),
('Quoyness'),
('Quoys'),
('Quoys Road'),
('Qurayyat'),
('Qureshi View'),
('Quwwatul'),
('Quy Court'),
('Quy Road'),
('Quy Waters'),
('Quys Green'),
('Qwysson Avenue'),
('Qā’em Shahr');
-- Down
DELETE FROM Placename WHERE keyword LIKE 'q%';