-- Up
INSERT INTO Placename (keyword)
VALUES
("U Wybr Ty Coch"),
("Uabhal Mòr"),
("Uachdar"),
("Uamascleit"),
("Uamh"),
("Uamh an Druideig"),
("Uamh Bheag"),
("Uamh Capuill"),
("Uamh Dhonn"),
("Uamh Ghamhainn"),
("Uamh Latha"),
("Uamh Lice Ruaidhe"),
("Uamh na h Acrach"),
("Uamh na h Oidhche"),
("Uamh nan Clach"),
("Uamh nan Daoine"),
("Uamh nan Ròn"),
("Uamh nan Soithichean"),
("Uamh Oir"),
("Uamh Phadaich"),
("Uamh Ruaidhridh"),
("Uamha na Creadha"),
("Uamha na Seann Daoine"),
("Uamha Sloc Bhearnasgaig"),
("Uamhag Labhruinn"),
("Uamhag na Creige streap"),
("Uamhag nan Gobhar"),
("Uamish"),
("Uamvar"),
("Uath Lochan"),
("Ubberley"),
("Ubbeston"),
("Ube"),
("Uberaba"),
("Uberash"),
("Uberash Roughs"),
("Uberlândia"),
("Ubique"),
("Ubley"),
("Ubley Drove"),
("Ubley Sideling"),
("Ubon Ratchathani"),
("Ubsdell"),
("Ubá"),
("Uchaf Corris"),
("Uchd a Bhuic"),
("Uchd a Chlàrsair"),
("Uchd a Phollain Shàmhaich"),
("Uchd an Ãird"),
("Uchd Mòr"),
("Uchdach Bhrisdidh Cridhe"),
("Uchel Dre"),
("Ucheldre"),
("Uckerby"),
("Uckerby Fox Covert"),
("Uckfield"),
("Uckfield Central"),
("Uckfield Community"),
("Uckfield New Town"),
("Uckfield Ridgewood"),
("Uckfield South With Framfield"),
("Uckham"),
("Uckinghall"),
("Uckington"),
("Uckington Heath"),
("Udaipur"),
("Udairn"),
("Udale"),
("Udall"),
("Uddens"),
("Uddern"),
("Uddingston"),
("Uddington"),
("Uden"),
("Udford"),
("Udgir"),
("Udi Geo"),
("Udiam"),
("Udimore"),
("Udine"),
("Udley"),
("Udney"),
("Udny"),
("Udon Thani"),
("Udracleit"),
("Udston"),
("Udstonhead"),
("Udupi"),
("Ueda"),
("Ufa"),
("Uffa"),
("Uffa Magna"),
("Uffcott"),
("Uffcott Down"),
("Uffculme"),
("Uffculme Down"),
("Uffen"),
("Uffington"),
("Uffington Down"),
("Uffington Gorse"),
("Uffington New"),
("Uffmoor"),
("Ufford"),
("Ufford Oaks"),
("Ufford Thicks"),
("Ufton"),
("Ufton Fields"),
("Ufton Nervet"),
("Ugadale"),
("Ugag"),
("Uganda"),
("Ugasta"),
("Ugborough"),
("Ugborough Beacon"),
("Ugbrooke"),
("Ugford"),
("Ugford Clump"),
("Ugg Mere"),
("Uggeshall"),
("Uggeshall Spring"),
("Uggle"),
("Ugglebarnby"),
("Uggoe"),
("Ughill"),
("Ughill Moors"),
("Ugie"),
("Ugiebank"),
("Ugley"),
("Uglow"),
("Ugly"),
("Ugly Dale"),
("Ugthorpe"),
("Ugworthy"),
("UHI Millennium Institute"),
("Uibhist a Deas"),
("Uibhist a Tuath"),
("Uidh"),
("Uidh Alasdair Ghuinnich"),
("Uidh an Tigh Sheilg"),
("Uidh Gharbh"),
("Uidh nam Fiadh"),
("Uidhe Gharbh"),
("Uidhseal"),
("Uig"),
("Uig Ferry"),
("Uige Sgeir"),
("Uigean"),
("Uigen"),
("Uiginis"),
("Uiginish"),
("Uiginish Bonnet"),
("Uigshader"),
("Uilbhinnis"),
("Uilystrand"),
("Uilystrand Heugh"),
("Uineabhal"),
("Uineasan"),
("Uirigh Bheithe"),
("Uirigh na Salach"),
("Uiseabhal"),
("Uisge Fear fiamh"),
("Uisge Ruadh"),
("Uisgneabhal Beag"),
("Uisgneabhal Mòr"),
("Uisinis"),
("Uist"),
("Uji"),
("Ujjain"),
("Ukna Skerry"),
("Ukraine"),
("Ul Dale"),
("Ulaanbaatar"),
("Ulabhal"),
("Ulalia"),
("Ulan Hot"),
("Ulan Ude"),
("Ulanqab"),
("Ulbster"),
("Ulcat"),
("Ulceby"),
("Ulceby Carr"),
("Ulceby Cross"),
("Ulceby Skitter"),
("Ulceby with Fordington"),
("Ulcombe"),
("Uldale"),
("Uldale Fells"),
("Uldale Force"),
("Uldale Head"),
("Uley"),
("Ulfgar"),
("Ulfhart"),
("Ulfkell"),
("Ulfred"),
("Ulgham"),
("Ulgraves"),
("Ulhasnagar"),
("Ulla"),
("Ulladale"),
("Ullapool"),
("Ullapool Hills"),
("Ullapow"),
("Ullard Hall"),
("Ullathorne"),
("Ullathorns"),
("Ullcombe"),
("Ulldale"),
("Ullen"),
("Ullenhall"),
("Ullenwood"),
("Ullenwood Reservoir"),
("Ullerdale"),
("Ulleries"),
("Ullermire"),
("Ullesby"),
("Ulleskelf"),
("Ullesthorpe"),
("Ulleswater"),
("Ullet"),
("Ulley"),
("Ulley Holt"),
("Ulley Reservoir"),
("Ullie Geo"),
("Ullin"),
("Ullingswick"),
("Ullington"),
("Ullinish"),
("Ullins Geo"),
("Ullins Water"),
("Ullioch"),
("Ullister"),
("Ullock"),
("Ullock Moss"),
("Ullock Pike"),
("Ullrik"),
("Ullscarf"),
("Ullswater"),
("Ullswheel"),
("Ulluva"),
("Ullyatts Drove"),
("Ulm"),
("Ulnaby"),
("Ulnes Walton"),
("Ulph"),
("Ulpha"),
("Ulrica"),
("Ulrick"),
("Ulrome"),
("Ulrome Sands"),
("Ulsan"),
("Ulshaw"),
("Ulsta"),
("Ulstan"),
("Ulster"),
("Ulston"),
("Ulswater"),
("Ulthwaite Rigg"),
("Ulting"),
("Ulting Hall"),
("Ultra"),
("Uluberia"),
("Ulundi"),
("Ulva"),
("Ulva Islands"),
("Ulverley"),
("Ulvers"),
("Ulverscroft"),
("Ulverston"),
("Ulverston Channel"),
("Ulverston Sands"),
("Ulverstone"),
("Ulviet"),
("Ulwell"),
("Ulwin"),
("Ulyanovsk"),
("Ulyett"),
("Ulysses"),
("Umachan"),
("Umber"),
("Umberleigh"),
("Umberley Sick"),
("Umberly"),
("Umbers"),
("Umberslade"),
("Umberston"),
("Umberstone"),
("Umberstone Covert"),
("Umberton"),
("Umberville"),
("Umbrella"),
("Umbria"),
("Umfraville Dene"),
("Umfreville"),
("Umlazi"),
("Umpire"),
("Umpleby"),
("Umuarama"),
("Una"),
("Unaizah"),
("Unapool"),
("Unasaraidh Islands"),
("Uncle Bens"),
("Uncle Toms"),
("Uncleby"),
("Uncleby Wold"),
("Uncles"),
("Uncles Hillock"),
("Uncombe"),
("Uncouth"),
("Under"),
("Under Billinge"),
("Under Cardiff"),
("Under Chapel"),
("Under Clough"),
("Under Covert"),
("Under Ffrydd"),
("Under Greave"),
("Under Hill Flat"),
("Under Hill Head"),
("Under Knoll"),
("Under Lee"),
("Under Loan"),
("Under Minnow"),
("Under Nine Rocks"),
("Under Parks"),
("Under Rainow"),
("Under Ripton"),
("Under Saddle Yoke"),
("Under Scar"),
("Under Sheriffs Clump"),
("Under th"),
("Under the"),
("Under The Hills"),
("Under the Low"),
("Under Tofts"),
("Under Town"),
("Under Win"),
("Underacre"),
("Underacres"),
("Underbank"),
("Underbank Hoe"),
("Underbank Old"),
("Underbank Reservoir"),
("Underbanks"),
("Underbarrow"),
("Underbarrow'),
('Bradleyfield"),
("Underbarrow Moss"),
("Underbarrow Pool"),
("Underbridge"),
("Underbrow"),
("Undercleave"),
("Undercliff"),
("Undercliffe"),
("Undercliffe Old"),
("Undercraigs"),
("Undercroft"),
("Underdale"),
("Underdown"),
("Underdown Covert"),
("Underdown Hollow"),
("Underfell"),
("Underfleet"),
("Undergate"),
("Undergreens"),
("Underhay"),
("Underhayes"),
("Underhedge"),
("Underhelm"),
("Underhill"),
("Underhill Circus"),
("Underhill Lake"),
("Underhills"),
("Underhoull"),
("Underhowe"),
("Underidge"),
("Underlaid"),
("Underland"),
("Underland Girt"),
("Underlands"),
("Underlane"),
("Underleaf"),
("Underleat"),
("Underley"),
("Underley Cop"),
("Underleys"),
("Underling"),
("Underlyn"),
("Undermill"),
("Undermillbeck"),
("Undermoss Strip"),
("Underne"),
("Underplot"),
("Underriver"),
("Underriver House"),
("Underscar"),
("Undershaft"),
("Undershaw"),
("Undershore"),
("Underskiddaw"),
("Undersley"),
("Underton"),
("Undertown"),
("Undertrees"),
("Underway"),
("Underways"),
("Underwit"),
("Underwood"),
("Underwoods"),
("Underwoods Grounds"),
("Underwoods Hard"),
("Undine"),
("Undirhoul"),
("Undley"),
("Undraynian"),
("Undsworth"),
("Undy"),
("Uned Ty Aalton"),
("Uneeda"),
("Unett"),
("Unetts"),
("Ungain Deep"),
("Ungam"),
("Ungla Skerry"),
("Unglabreid"),
("Unhill"),
("Uni Firth"),
("Unicorn"),
("Unicorn Gateway"),
("Unicumes"),
("Unifirth"),
("Unilever"),
("Union"),
("Union Alley"),
("Union Arcade"),
("Union Belt"),
("Union Buildings"),
("Union Castle"),
("Union Cross"),
("Union Dock"),
("Union Drift"),
("Union Drove"),
("Union Gorse"),
("Union Gorse Covert"),
("Union Hall"),
("Union House"),
("Union Mine"),
("Union Passage"),
("Union Quay"),
("Union Wynd"),
("Unique"),
("Unit"),
("Unitas"),
("United"),
("United Downs"),
("United Downs industrial"),
("Unitt"),
("Unity"),
("Unity Hall"),
("Universal"),
("University"),
("University Centre"),
("University Centre Rotherham"),
("University Centre Shrewsbury"),
("University Hospital Ayr"),
("University Hospital Crosshouse"),
("University Hospital Hairmyres"),
("University Hospital Llandough"),
("University Hospital of Hartlepool"),
("University Hospital Of North Durham"),
("University Hospital Of North Tees"),
("University Hospital of Wales"),
("University Hospital Wishaw"),
("University House"),
("University Parks"),
("University Parkway"),
("Unketts"),
("Unla Water"),
("Unlawater"),
("Unna"),
("Unnao"),
("Unodourised"),
("Unodourised Gas Installation Honeybourne"),
("Unsliven"),
("Unst"),
("Unstead"),
("Unsted"),
("Unstone"),
("Unstone Dronfield By Pass"),
("Unsworth"),
("Unthank"),
("Untons"),
("Unwin"),
("Unwin Pool"),
("Unwins"),
("Uny Lelant"),
("Up"),
("Up Brooks"),
("Up Cerne"),
("Up Corner"),
("Up Exe"),
("Up Hatherley"),
("Up Holland"),
("Up Marden"),
("Up Mudford"),
("Up Nately"),
("Up Somborne"),
("Up Somborne Down"),
("Up Sydling"),
("Upavon"),
("Upavon Airfield"),
("Upavon Army Camp"),
("Upavon Down"),
("Upavon Garth"),
("Upbank"),
("Upbrook"),
("Upbury"),
("Upcast"),
("Upcerne"),
("Upchat"),
("Upcher"),
("Upchurch"),
("Upchurch Hartlip"),
("Upcot"),
("Upcott"),
("Upcott Barton"),
("Upcott Brake"),
("Upcott Cleave"),
("Upcott Moors"),
("Upcott Valley"),
("Upcroft"),
("Upcross"),
("Updale"),
("Updown"),
("Upend"),
("Upende"),
("Upex"),
("Upexe"),
("Upfallow"),
("Upfield"),
("Upfold"),
("Upfolds"),
("Upfra Loch"),
("Upgang"),
("Upgang Beach"),
("Upgarth"),
("Upgate"),
("Uphall"),
("Uphall'),
('Winchburgh Broxburn"),
("Uphall Station"),
("Uphalle"),
("Upham"),
("Uphampton"),
("Uphay"),
("Upherds"),
("Uphill"),
("Uphill Pill"),
("Uphills"),
("Upholland"),
("Uphouse"),
("Upjohn"),
("Upland"),
("Upland Chase"),
("Upland Shaw"),
("Upland Wynd"),
("Uplands"),
("Uplands Chase"),
("Uplands Farm Barns"),
("Uplands Vean"),
("Uplawmoor"),
("Upleadon"),
("Upleatham"),
("Uplees"),
("Uplees Marshes"),
("Uplin"),
("Uploders"),
("Uplowman"),
("Uplyme"),
("Upmeadows"),
("Upmill"),
("Upminster"),
("Upney"),
("Upnor"),
("Upnor Reach"),
("Upottery"),
("Uppacott"),
("Uppacott Down"),
("Uppark"),
("Uppat"),
("Uppaton"),
("Uppend"),
("Upper Abbey"),
("Upper Abbotstone"),
("Upper Abbotts"),
("Upper Abercanaid"),
("Upper Accommodation"),
("Upper Acharn Pool"),
("Upper Acres"),
("Upper Ada"),
("Upper Adare"),
("Upper Addison"),
("Upper Adelaide"),
("Upper Adgestone"),
("Upper Affcot"),
("Upper Albert"),
("Upper Albion"),
("Upper Alders"),
("Upper Allan"),
("Upper Allen"),
("Upper Allerton"),
("Upper Alma"),
("Upper Amport"),
("Upper'),
('Lower Fence"),
("Upper'),
('Lower Shuckburgh"),
("Upper Andover"),
("Upper Anstey"),
("Upper Arail"),
("Upper Arbeadie"),
("Upper Arcan"),
("Upper Archer"),
("Upper Ardchronie"),
("Upper Arles"),
("Upper Arley"),
("Upper Armley"),
("Upper Arncott"),
("Upper Arthur"),
("Upper Arundel"),
("Upper Ash"),
("Upper Ashley"),
("Upper Ashlyns"),
("Upper Astley"),
("Upper Aston"),
("Upper Aston Hall"),
("Upper Astrop"),
("Upper Attington"),
("Upper Auchintore"),
("Upper Aughton"),
("Upper Aultderg"),
("Upper Austin Lodge"),
("Upper Backway"),
("Upper Badcall"),
("Upper Badley"),
("Upper Baggeridge"),
("Upper Baila"),
("Upper Bainbrigge"),
("Upper Bairds Covert"),
("Upper Baker"),
("Upper Balcom"),
("Upper Balsall Heath"),
("Upper Bangor"),
("Upper Banister"),
("Upper Banks"),
("Upper Bannisters"),
("Upper Baptist"),
("Upper Bar"),
("Upper Barclay"),
("Upper Barcott"),
("Upper Barden Reservoir"),
("Upper Barker"),
("Upper Barn"),
("Upper Barn Hanger"),
("Upper Barresdale"),
("Upper Barton"),
("Upper Basildon"),
("Upper Basinghall"),
("Upper Bath"),
("Upper Bathville"),
("Upper Batley"),
("Upper Batley Low"),
("Upper Battlefield"),
("Upper Battye"),
("Upper Bayble"),
("Upper Beanham"),
("Upper Beau"),
("Upper Beckwith"),
("Upper Bedford"),
("Upper Beechen"),
("Upper Beeding"),
("Upper Beeding'),
('Woodmancote Bramber"),
("Upper Belgrave"),
("Upper Bell"),
("Upper Bell Hall"),
("Upper Belmont"),
("Upper Belt"),
("Upper Belvedere"),
("Upper Bench"),
("Upper Benefield"),
("Upper Benter"),
("Upper Bentley"),
("Upper Bere"),
("Upper Berkeley"),
("Upper Berrington"),
("Upper Berry"),
("Upper Berwick"),
("Upper Beulah"),
("Upper Bevendean"),
("Upper Biggin"),
("Upper Bilson"),
("Upper Birchin"),
("Upper Birchwood"),
("Upper Birtley"),
("Upper Bittell Reservoir"),
("Upper Bitterns"),
("Upper Black Bushes"),
("Upper Black Moss Reservoir"),
("Upper Blackbuck"),
("Upper Blackbush"),
("Upper Blackhead"),
("Upper Blackrock Covert"),
("Upper Blairs"),
("Upper Blakeridge"),
("Upper Blind"),
("Upper Blindlow"),
("Upper Bloomfield"),
("Upper Blunts"),
("Upper Boat"),
("Upper Boddington"),
("Upper Bog"),
("Upper Bognor"),
("Upper Boishall"),
("Upper Bolstone"),
("Upper Bolton Brow"),
("Upper Bolton Strips"),
("Upper Bonchurch"),
("Upper Bond"),
("Upper Bonegate"),
("Upper Bongate"),
("Upper Bonstone"),
("Upper Booth"),
("Upper Borough Walls"),
("Upper Borth"),
("Upper Botten"),
("Upper Boundary"),
("Upper Boundstone"),
("Upper Bourne"),
("Upper Bourne Vale"),
("Upper Bourtree"),
("Upper Bow"),
("Upper Bowley"),
("Upper Braddons"),
("Upper Bradway"),
("Upper Braes"),
("Upper Brailes"),
("Upper Brake"),
("Upper Branch"),
("Upper Branston"),
("Upper Brassey"),
("Upper Bray"),
("Upper Breach"),
("Upper Breckland"),
("Upper Breeze"),
("Upper Breinton"),
("Upper Brents"),
("Upper Brentwood"),
("Upper Brig Royd"),
("Upper Brighton"),
("Upper Bristol"),
("Upper Bristow"),
("Upper Britton"),
("Upper Broad"),
("Upper Broadheath"),
("Upper Broadmoor"),
("Upper Broadridge"),
("Upper Brockholes"),
("Upper Brockley"),
("Upper Brook Covert"),
("Upper Brooks"),
("Upper Broom"),
("Upper Broomgrove"),
("Upper Broomieknowe"),
("Upper Brooms"),
("Upper Broughton"),
("Upper Brow"),
("Upper Brown"),
("Upper Brownhill"),
("Upper Bruntingthorpe"),
("Upper Bryans"),
("Upper Bryn"),
("Upper Bryn Coch"),
("Upper Brynamman"),
("Upper Brynhyfryd"),
("Upper Bryntirion"),
("Upper Buckenhill"),
("Upper Buckhurst Shaw"),
("Upper Bucklebury"),
("Upper Bugle"),
("Upper Bullington"),
("Upper Burgate"),
("Upper Burgess"),
("Upper Burn"),
("Upper Burnside"),
("Upper Burnthouse"),
("Upper Bush"),
("Upper Bushes"),
("Upper Bute"),
("Upper Butts"),
("Upper Byron"),
("Upper Cakesbridge"),
("Upper Caldecote"),
("Upper Calton"),
("Upper Cam"),
("Upper Cambourne"),
("Upper Cambrian"),
("Upper Camden"),
("Upper Camp"),
("Upper Campbrae"),
("Upper Campsfield"),
("Upper Camroyd"),
("Upper Canaan"),
("Upper Canada"),
("Upper Canfold"),
("Upper Canning"),
("Upper Canterton"),
("Upper Capel"),
("Upper Car Cleuch"),
("Upper Carlisle"),
("Upper Carloway"),
("Upper Carman"),
("Upper Carr"),
("Upper Carters Leys"),
("Upper Cartsburn"),
("Upper Castle"),
("Upper Castle Cleugh"),
("Upper Castle Combe"),
("Upper Castlehill"),
("Upper Catesby"),
("Upper Catshill"),
("Upper Cavendish"),
("Upper Caxton"),
("Upper Chalkey"),
("Upper Chalkley"),
("Upper Chalvington"),
("Upper Chantry"),
("Upper Chapel"),
("Upper Charles"),
("Upper Charnwood"),
("Upper Chase"),
("Upper Cheddon"),
("Upper Chelsea"),
("Upper Cheltenham"),
("Upper Chestnut"),
("Upper Cheyne"),
("Upper Chicksgrove"),
("Upper Chilmans Downs"),
("Upper Chilstone"),
("Upper Chimes"),
("Upper Chobham"),
("Upper Chorlton"),
("Upper Church"),
("Upper Church Fields"),
("Upper Churnside"),
("Upper Churston"),
("Upper Chute"),
("Upper Chyngton"),
("Upper Clabdens"),
("Upper Clapton"),
("Upper Clara"),
("Upper Clarence"),
("Upper Clatford"),
("Upper Claypark"),
("Upper Cleminson"),
("Upper Cleuch"),
("Upper Cliff"),
("Upper Cliffe"),
("Upper Clifton"),
("Upper Clough"),
("Upper Clwyd"),
("Upper Coal"),
("Upper Coberley"),
("Upper Cockington"),
("Upper Coedcae"),
("Upper Coire Faoin Stack"),
("Upper Cokeham"),
("Upper Colbren"),
("Upper Coldwell Reservoir"),
("Upper Coll"),
("Upper Colliers"),
("Upper Collins"),
("Upper Colquhoun"),
("Upper Coltbridge"),
("Upper Colwall"),
("Upper Commercial"),
("Upper Commissary Pool"),
("Upper Conham Vale"),
("Upper Conran"),
("Upper Constitution"),
("Upper Conybere"),
("Upper Coombe"),
("Upper Copperas Creek"),
("Upper Coquetdale"),
("Upper Cornaway"),
("Upper Corniche"),
("Upper Cornsland"),
("Upper Cosmeston"),
("Upper Coston"),
("Upper Cotton"),
("Upper Cound"),
("Upper Covert"),
("Upper Cowdens"),
("Upper Cowslow Covert"),
("Upper Coxley"),
("Upper Crabbick"),
("Upper Crabtree"),
("Upper Crackney"),
("Upper Craighill"),
("Upper Craigie"),
("Upper Craigo"),
("Upper Craigour"),
("Upper Craigs"),
("Upper Crale"),
("Upper Cramond"),
("Upper Cranbrook"),
("Upper Crannel Drove"),
("Upper Crantit"),
("Upper Crockford"),
("Upper Croft Shaw"),
("Upper Crofts"),
("Upper Crooked"),
("Upper Cross"),
("Upper Crossgate"),
("Upper Crown"),
("Upper Cudworth"),
("Upper Culham"),
("Upper Cullernie"),
("Upper Culm"),
("Upper Culver"),
("Upper Cumberland"),
("Upper Cumberworth"),
("Upper Cumbrae Reservoir"),
("Upper Cut"),
("Upper Cwm Twrch"),
("Upper Cwmbran"),
("Upper Cwmgwyn"),
("Upper Cwminon"),
("Upper Cyrus"),
("Upper Dagnall"),
("Upper Dagwells"),
("Upper Daisy"),
("Upper Dalby"),
("Upper Dale"),
("Upper Dales"),
("Upper Dalgairn"),
("Upper Dallachy"),
("Upper Damhead"),
("Upper Damside"),
("Upper Dane"),
("Upper Deacon"),
("Upper Deal"),
("Upper Deal Belt"),
("Upper Dean"),
("Upper Dean Head Reservoir"),
("Upper Deeside'),
('Donside Aboyne"),
("Upper Delph Drove"),
("Upper Den"),
("Upper Denbigh"),
("Upper Denburn"),
("Upper Denby"),
("Upper Denmark"),
("Upper Denton"),
("Upper Derwent Valley"),
("Upper Dicconson"),
("Upper Dicker"),
("Upper Din"),
("Upper Dinchope"),
("Upper Dingle"),
("Upper Dobbin"),
("Upper Dock"),
("Upper Dod"),
("Upper Doe Carr"),
("Upper Dolfor"),
("Upper Dormington"),
("Upper Dorrells"),
("Upper Dovercourt"),
("Upper Dowdeswell"),
("Upper Down"),
("Upper Downing"),
("Upper Downing Hall"),
("Upper Downs"),
("Upper Downside"),
("Upper Drakeloe"),
("Upper Drove"),
("Upper Drummond"),
("Upper Duke"),
("Upper Dukes"),
("Upper Dullarg"),
("Upper Dumpton"),
("Upper Dunbar"),
("Upper Dunnymans"),
("Upper Dunsforth"),
("Upper Dunsley"),
("Upper Dunstan"),
("Upper Dunstead"),
("Upper Durrants"),
("Upper Dutmoss"),
("Upper Dwarf Brake"),
("Upper Eashing"),
("Upper East Hayes"),
("Upper Eastcliffe"),
("Upper Eastern"),
("Upper Eastlands"),
("Upper Easton"),
("Upper Eastville"),
("Upper Eastwick"),
("Upper Eastwood"),
("Upper Eddington"),
("Upper Edge"),
("Upper Edgebold"),
("Upper Edgeborough"),
("Upper Edinbane"),
("Upper Edmonton"),
("Upper Edward"),
("Upper Egleton"),
("Upper Eldon"),
("Upper Elizabeth"),
("Upper Elkstone"),
("Upper Ell"),
("Upper Ellastone"),
("Upper Ellistones"),
("Upper Elmers"),
("Upper Elms"),
("Upper Elsdon"),
("Upper Engamoor"),
("Upper Enham"),
("Upper Ensign"),
("Upper Enton Lake"),
("Upper Esgair"),
("Upper Essex"),
("Upper Etloe"),
("Upper Ettingshall"),
("Upper Eythorne"),
("Upper Fagley"),
("Upper Fairfield"),
("Upper Fall of Foyers"),
("Upper Fans"),
("Upper Fant"),
("Upper Farburn"),
("Upper Farm Down"),
("Upper Farm Pool"),
("Upper Farmcote"),
("Upper Farringdon"),
("Upper Fawth"),
("Upper Fedw"),
("Upper Fenn"),
("Upper Fenwick"),
("Upper Feorlig"),
("Upper Ferndown"),
("Upper Ferry"),
("Upper Fforest"),
("Upper Field House"),
("Upper Fifth"),
("Upper Fillington"),
("Upper Fir Covert"),
("Upper Fish"),
("Upper Fisher"),
("Upper Flaybrick"),
("Upper Foel"),
("Upper Fold"),
("Upper Folderings"),
("Upper Folly"),
("Upper Forecourt"),
("Upper Forest Level"),
("Upper Forge"),
("Upper Forster"),
("Upper Forty Acres"),
("Upper Fountain"),
("Upper Four Acres"),
("Upper Fourth"),
("Upper Fox Valley"),
("Upper Foxmoor"),
("Upper Framilode"),
("Upper Francis"),
("Upper Frederick"),
("Upper Free Down"),
("Upper Frenchmoor"),
("Upper Frog"),
("Upper Froyle"),
("Upper Fullingpits"),
("Upper Furlong"),
("Upper Furze"),
("Upper Fyfe"),
("Upper Galdeford"),
("Upper Gambolds"),
("Upper Gardner"),
("Upper Garrington"),
("Upper Garston"),
("Upper Garth"),
("Upper Gate Clough"),
("Upper Gatton"),
("Upper Geise"),
("Upper Gendros"),
("Upper Geo Kirk"),
("Upper George"),
("Upper Gertrude"),
("Upper Gills"),
("Upper Gilmore"),
("Upper Gipping"),
("Upper Gipsys"),
("Upper Gladstone"),
("Upper Glasshouse"),
("Upper Glebe"),
("Upper Gledfield"),
("Upper Glen Dam"),
("Upper Glen Ely"),
("Upper Glenburn"),
("Upper Glenburnie"),
("Upper Glendevon Reservoir"),
("Upper Glenfinlas"),
("Upper Glenfyne"),
("Upper Glenjaan"),
("Upper Gloucester"),
("Upper Glyn Gwyn"),
("Upper Goat"),
("Upper Godney"),
("Upper Goldstone"),
("Upper Golf Links"),
("Upper Gordon"),
("Upper Gore"),
("Upper Gornal"),
("Upper Gornal'),
('Woodsetton"),
("Upper Gorry Pool"),
("Upper Gough"),
("Upper Graham"),
("Upper Granco"),
("Upper Grassy Pool"),
("Upper Grateley"),
("Upper Gravenhurst"),
("Upper Gray"),
("Upper Great"),
("Upper Greenhill"),
("Upper Greens"),
("Upper Greenwoods"),
("Upper Greetland"),
("Upper Grenoven"),
("Upper Grenville"),
("Upper Gresham"),
("Upper Griffin"),
("Upper Grip"),
("Upper Grosvenor"),
("Upper Grotto"),
("Upper Ground"),
("Upper Guildown"),
("Upper Guist"),
("Upper Gungate"),
("Upper Gunnas"),
("Upper Gwastad"),
("Upper Gwestydd"),
("Upper Gwyddon"),
("Upper Gwydir"),
("Upper Gynor"),
("Upper Hackney"),
("Upper Hael"),
("Upper Hagg"),
("Upper Haggi Geo"),
("Upper Haigh"),
("Upper Hailey"),
("Upper Hale"),
("Upper Haliford"),
("Upper Hall"),
("Upper Hall Fold"),
("Upper Hall Lake"),
("Upper Hallidayhill"),
("Upper Halliford"),
("Upper Halling"),
("Upper Ham"),
("Upper Hambleton"),
("Upper Hamilton"),
("Upper Hammer"),
("Upper Hamnish"),
("Upper Hampton"),
("Upper Hanger"),
("Upper Hanover"),
("Upper Harbledown"),
("Upper Harbour"),
("Upper Hardres"),
("Upper Hardwick"),
("Upper Harestone"),
("Upper Harley"),
("Upper Harmans"),
("Upper Harrington"),
("Upper Hartfield"),
("Upper Hartshay"),
("Upper Hartwell"),
("Upper Harvel"),
("Upper Hass Loch"),
("Upper Hatfield"),
("Upper Hathershelf"),
("Upper Hatton"),
("Upper Haugh"),
("Upper Haugh Shaw"),
("Upper Havelock"),
("Upper Haydon"),
("Upper Hayes"),
("Upper Hayesden"),
("Upper Haysden"),
("Upper Hayton"),
("Upper Hazel"),
("Upper Head Moss"),
("Upper Headland"),
("Upper Heamies"),
("Upper Heath"),
("Upper Heathfield"),
("Upper Heaton"),
("Upper Hedgemead"),
("Upper Helena"),
("Upper Hellesdon"),
("Upper Helmsley"),
("Upper Hengoed"),
("Upper Hergeist"),
("Upper Hergest"),
("Upper Hermitage"),
("Upper Hermosa"),
("Upper Heworth"),
("Upper Hey"),
("Upper Heyden"),
("Upper Heyford"),
("Upper Heys"),
("Upper Heyshott"),
("Upper Heywood"),
("Upper Hibbert"),
("Upper Hiendley"),
("Upper High"),
("Upper High Fields"),
("Upper High Royds"),
("Upper Higham"),
("Upper Highbridge"),
("Upper Highfield"),
("Upper Highfields"),
("Upper Highgate"),
("Upper Highland"),
("Upper Highway"),
("Upper Highwood"),
("Upper Hillchurch"),
("Upper Hillcrest"),
("Upper Hillfoot"),
("Upper Hinton"),
("Upper Hird"),
("Upper Hirst"),
("Upper Hitch"),
("Upper Hoden"),
("Upper Holland"),
("Upper Hollesley"),
("Upper Hollingdean"),
("Upper Hollis"),
("Upper Hollow"),
("Upper Holloway"),
("Upper Holly"),
("Upper Holme"),
("Upper Holt"),
("Upper Holton"),
("Upper Holway"),
("Upper Home"),
("Upper Hook"),
("Upper Hope"),
("Upper Hopgarden"),
("Upper Hopton"),
("Upper Horse"),
("Upper Horse Pool"),
("Upper Horse Rough"),
("Upper Horsebridge"),
("Upper Houndlaw"),
("Upper House"),
("Upper House Fold"),
("Upper Houses"),
("Upper Howick"),
("Upper Howsell"),
("Upper Hoyland"),
("Upper Hoyle Ing"),
("Upper Hucksteep"),
("Upper Huddles"),
("Upper Hulme"),
("Upper Humblescough"),
("Upper Hundreds"),
("Upper Huntbach"),
("Upper Huntlywood"),
("Upper Hunton"),
("Upper Hurst"),
("Upper Huskisson"),
("Upper Hyde"),
("Upper Icknield"),
("Upper Ifield"),
("Upper Ifold"),
("Upper Inglesham"),
("Upper Inhams"),
("Upper Inkerman"),
("Upper Isbury"),
("Upper James"),
("Upper John"),
("Upper Keith"),
("Upper Kempley"),
("Upper Kent"),
("Upper Kenyon"),
("Upper Kessock"),
("Upper Kilchattan"),
("Upper Kilcott"),
("Upper Killay"),
("Upper Kiln"),
("Upper Kincraig"),
("Upper King"),
("Upper Kings"),
("Upper Kings Head"),
("Upper Kingston"),
("Upper Kinneddar"),
("Upper Kinsham"),
("Upper Kipping"),
("Upper Kirby"),
("Upper Kirkgate"),
("Upper Kitching Spring"),
("Upper Kites"),
("Upper Kitesnest"),
("Upper Knapp"),
("Upper Knarr Fen"),
("Upper Knockando"),
("Upper Knockbain"),
("Upper Knole"),
("Upper Knollys"),
("Upper Knowe"),
("Upper Knowle"),
("Upper Ladyes Hills"),
("Upper Ladypark"),
("Upper Lairochs"),
("Upper Lake"),
("Upper Lamborough"),
("Upper Lambourn"),
("Upper Lambricks"),
("Upper Lambridge"),
("Upper Lamphey"),
("Upper Landslip"),
("Upper Landywood"),
("Upper Langford"),
("Upper Langridge"),
("Upper Langsky Belt"),
("Upper Langwith"),
("Upper Lanham"),
("Upper Lansdown"),
("Upper Largo"),
("Upper Lattimore"),
("Upper Laundimer"),
("Upper Layham"),
("Upper Lays"),
("Upper Lazy Bushes"),
("Upper Leazes"),
("Upper Lee"),
("Upper Lees"),
("Upper Leigh"),
("Upper Lewes"),
("Upper Ley"),
("Upper Ley Dell"),
("Upper Lichfield"),
("Upper Lightwood"),
("Upper Linacre Reservoir"),
("Upper Lindum"),
("Upper Linhay"),
("Upper Linney"),
("Upper Littlegill"),
("Upper Littleton"),
("Upper Llancayo"),
("Upper Llandwrog"),
("Upper Llanelwedd"),
("Upper Lliedi Reservoir"),
("Upper Lliw Reservoir"),
("Upper Lloyd"),
("Upper Loads"),
("Upper Loan"),
("Upper Loaning"),
("Upper Loch"),
("Upper Loch of Brouster"),
("Upper Loch of Setter"),
("Upper Loch Torridon"),
("Upper Lochan Sligeanach"),
("Upper Lochton"),
("Upper Lodge"),
("Upper Lombard"),
("Upper Long Leys"),
("Upper Longdon"),
("Upper Longlands"),
("Upper Longwood"),
("Upper Lord"),
("Upper Loughor"),
("Upper Ludstone"),
("Upper Ludwell Shaw"),
("Upper Lum"),
("Upper Lumb"),
("Upper Lune"),
("Upper Lune Valley"),
("Upper Lunns"),
("Upper Luton"),
("Upper Lybster"),
("Upper Lydbrook"),
("Upper Lydbrooke"),
("Upper Lyde"),
("Upper Lye"),
("Upper Lynch"),
("Upper Lynmore"),
("Upper Maenen"),
("Upper Maes Coed"),
("Upper Maescoed"),
("Upper Mains"),
("Upper Maisondieu"),
("Upper Mall"),
("Upper Malthouse"),
("Upper Mann"),
("Upper Manor"),
("Upper Mansbrook"),
("Upper Manse Pool"),
("Upper Mantle"),
("Upper Marehay"),
("Upper Market"),
("Upper Marlborough"),
("Upper Marlbrook"),
("Upper Marsh"),
("Upper Marsh Covert"),
("Upper Marshall"),
("Upper Marston"),
("Upper Martin"),
("Upper Martridge"),
("Upper Mary"),
("Upper Mastrick"),
("Upper Maudlin"),
("Upper Maund"),
("Upper Mayfield"),
("Upper Maylins"),
("Upper Mayne"),
("Upper Maythorn"),
("Upper Maze"),
("Upper Meadow Spring"),
("Upper Mealines"),
("Upper Melton"),
("Upper Meon Valley"),
("Upper Mersey"),
("Upper Mexborough"),
("Upper Midhope"),
("Upper Midway"),
("Upper Milcote"),
("Upper Miless Rough"),
("Upper Millergate"),
("Upper Millfield"),
("Upper Millgate"),
("Upper Millhill"),
("Upper Millichope"),
("Upper Milton"),
("Upper Minety"),
("Upper Misden Clough"),
("Upper Mitton"),
("Upper Mod"),
("Upper Monsall"),
("Upper Montagu"),
("Upper Monynut"),
("Upper Moor Side"),
("Upper Moorfield"),
("Upper Moorgreen"),
("Upper Moors"),
("Upper Moors Gully"),
("Upper Morax"),
("Upper Morgay"),
("Upper Morin"),
("Upper Morton"),
("Upper Moss"),
("Upper Moss Cleuch"),
("Upper Moss of Leonach"),
("Upper Mosscar"),
("Upper Mossley"),
("Upper Mounts"),
("Upper Mulgrave"),
("Upper Mullins"),
("Upper Mwldan"),
("Upper Myrtle"),
("Upper Napier"),
("Upper Nash"),
("Upper Navigation"),
("Upper Neapaback"),
("Upper Neatham"),
("Upper Neck Shaw"),
("Upper Nellington"),
("Upper Nelson"),
("Upper Netchwood"),
("Upper Neuadd Reservoir"),
("Upper New"),
("Upper New Pool"),
("Upper Newbold"),
("Upper Newborough"),
("Upper Newdown"),
("Upper Newington"),
("Upper Newmarket"),
("Upper Newton"),
("Upper Nidd"),
("Upper Nisbet"),
("Upper Noads"),
("Upper Nobut"),
("Upper Norfolk"),
("Upper Normacot"),
("Upper North Dean"),
("Upper Northam"),
("Upper Northgate"),
("Upper Norwich"),
("Upper Norwood"),
("Upper Nursery"),
("Upper Nut Hurst"),
("Upper Oak"),
("Upper Oakcuts"),
("Upper Oakley"),
("Upper Oaks"),
("Upper Ochrwyth"),
("Upper Oddington"),
("Upper Oddington Ashes"),
("Upper Ogden Reservoir"),
("Upper Old"),
("Upper Old Bargains"),
("Upper Oldfield"),
("Upper Oliver Dod"),
("Upper Olland"),
("Upper Orwell"),
("Upper Owlers"),
("Upper Ox"),
("Upper Oxford"),
("Upper Packington"),
("Upper Paddock"),
("Upper Padley"),
("Upper Parish Ghyll"),
("Upper Park Clump"),
("Upper Parkers Hole"),
("Upper Parkstone"),
("Upper Parliament"),
("Upper Parrotts"),
("Upper Parting"),
("Upper Passmonds"),
("Upper Pattiesbank"),
("Upper Paul"),
("Upper Pavenhill"),
("Upper Pearson"),
("Upper Peel"),
("Upper Pemberton"),
("Upper Penman"),
("Upper Pennington"),
("Upper Penns"),
("Upper Penshill"),
("Upper Pentre Bach"),
("Upper Perlieu"),
("Upper Perry"),
("Upper Pertwood Bushes"),
("Upper Phillimore"),
("Upper Piccadilly"),
("Upper Piece"),
("Upper Pillory Down"),
("Upper Pilsley"),
("Upper Pines"),
("Upper Pinewood"),
("Upper Pitching"),
("Upper Pitt"),
("Upper Pleasley"),
("Upper Polecats"),
("Upper Pollicott"),
("Upper Polmear Parc"),
("Upper Pool"),
("Upper Poole"),
("Upper Popes"),
("Upper Poppleton"),
("Upper Port"),
("Upper Portland"),
("Upper Potley"),
("Upper Power"),
("Upper Pownall"),
("Upper Price"),
("Upper Princes"),
("Upper Princess"),
("Upper Priory"),
("Upper Profit"),
("Upper Promenade"),
("Upper Pulley"),
("Upper Quarry"),
("Upper Quay"),
("Upper Queen"),
("Upper Queens"),
("Upper Quell"),
("Upper Quinton"),
("Upper Quoy"),
("Upper Raby"),
("Upper Race"),
("Upper Radford"),
("Upper Radnor"),
("Upper Raglan"),
("Upper Rainham"),
("Upper Rake"),
("Upper Randell"),
("Upper Rapeland"),
("Upper Rashy Cleuch"),
("Upper Ratley"),
("Upper Ratton"),
("Upper Ravens"),
("Upper Rawcliffe with Tarnacre"),
("Upper Red"),
("Upper Red Cross"),
("Upper Redbrook"),
("Upper Reddale Clough"),
("Upper Redlands"),
("Upper Regent"),
("Upper Regents"),
("Upper Reservoir"),
("Upper Reynolds"),
("Upper Rhynd"),
("Upper Rice"),
("Upper Richardson"),
("Upper Richmond"),
("Upper Ride"),
("Upper Riding"),
("Upper Ridings"),
("Upper Riochan"),
("Upper Rissington"),
("Upper Rithe"),
("Upper River"),
("Upper Rivington Reservoir"),
("Upper Road Pool"),
("Upper Roadstead"),
("Upper Robinson"),
("Upper Rochford"),
("Upper Rock"),
("Upper Rodge"),
("Upper Rodley"),
("Upper Rodmersham"),
("Upper Roedale"),
("Upper Roman"),
("Upper Rose"),
("Upper Rosemary"),
("Upper Rough"),
("Upper Roughs"),
("Upper Rouse"),
("Upper Rowe"),
("Upper Royal"),
("Upper Rudimoor"),
("Upper Rushall"),
("Upper Rushton"),
("Upper Rusko"),
("Upper Russell"),
("Upper Ruxley"),
("Upper Rye"),
("Upper Ryle"),
("Upper Sackville"),
("Upper Sales"),
("Upper Saline"),
("Upper Salisbury"),
("Upper Salters"),
("Upper Samshill"),
("Upper Sanday"),
("Upper Sandhurst"),
("Upper Sapey"),
("Upper Sawleywood"),
("Upper Saxon"),
("Upper Saxondale"),
("Upper Scar"),
("Upper Sea"),
("Upper Seagry"),
("Upper Seal Clough"),
("Upper Sean"),
("Upper Second"),
("Upper Selsdon"),
("Upper Selves"),
("Upper Settle"),
("Upper Seven Acres"),
("Upper Seymour"),
("Upper Shaftesbury"),
("Upper Shaw"),
("Upper Sheepwash"),
("Upper Sheffield"),
("Upper Shelley"),
("Upper Shelton"),
("Upper Shenmore"),
("Upper Sherborne"),
("Upper Sheridan"),
("Upper Sheringham"),
("Upper Sherwood"),
("Upper Shirley"),
("Upper Shirley High"),
("Upper Shooters"),
("Upper Shoreham"),
("Upper Short"),
("Upper Shot"),
("Upper Shott"),
("Upper Shrubbery"),
("Upper Shuckburgh"),
("Upper Siddington"),
("Upper Skelmorlie"),
("Upper Slackbuie"),
("Upper Slackstead"),
("Upper Slades"),
("Upper Slatepits"),
("Upper Slaughter"),
("Upper Sluice"),
("Upper Small Clough"),
("Upper Smearing Cleuch"),
("Upper Smithers"),
("Upper Smollett"),
("Upper Snailsden Moss"),
("Upper Sneyd"),
("Upper Soldridge"),
("Upper Soles"),
("Upper Solva"),
("Upper Soudley"),
("Upper Sound"),
("Upper Soundwell"),
("Upper Sourfold"),
("Upper South Rill"),
("Upper Speighthill"),
("Upper Spon"),
("Upper Spond"),
("Upper Spring"),
("Upper Springfield"),
("Upper St Albans"),
("Upper St Anns"),
("Upper St Giles"),
("Upper St Helens"),
("Upper St Jamess"),
("Upper St John"),
("Upper St Johns"),
("Upper St Martins"),
("Upper St Marys"),
("Upper St Michaels"),
("Upper St Pauls"),
("Upper St Stephen"),
("Upper Stafford"),
("Upper Staithe"),
("Upper Stanford"),
("Upper Stanhope"),
("Upper Stanton"),
("Upper Stanton Drew"),
("Upper Stapens"),
("Upper Staple Hills"),
("Upper Staploe"),
("Upper Star Post Ride"),
("Upper Station"),
("Upper Steeping"),
("Upper Stephens"),
("Upper Stockriding"),
("Upper Stoke"),
("Upper Stondon"),
("Upper Stone"),
("Upper Stoneborough"),
("Upper Stoneham"),
("Upper Stonehayes"),
("Upper Stoneymollan"),
("Upper Stony Cleuch"),
("Upper Stonyfield"),
("Upper Stonyhills"),
("Upper Stowe"),
("Upper Stowfield"),
("Upper Stratton"),
("Upper Streat"),
("Upper Strensham"),
("Upper Strinesdale Reservoir"),
("Upper Strode"),
("Upper Stroquhan"),
("Upper Stroud"),
("Upper Studdings Shaw"),
("Upper Studley"),
("Upper Stumble"),
("Upper Sude"),
("Upper Sudeley"),
("Upper Sugworth"),
("Upper Sunbury"),
("Upper Sundon"),
("Upper Sunny"),
("Upper Sunt"),
("Upper Sutherland"),
("Upper Sutton"),
("Upper Swaines"),
("Upper Swainswick"),
("Upper Swallow"),
("Upper Swanmore"),
("Upper Swell"),
("Upper Swineshaw Reservoir"),
("Upper Swinhoe Lake"),
("Upper Swinton"),
("Upper Sydenham"),
("Upper Sydney"),
("Upper Tachbrook"),
("Upper Tachore Pot"),
("Upper Tadmarton"),
("Upper Taff"),
("Upper Tail"),
("Upper Tal y coed"),
("Upper Talley Lake"),
("Upper Tamar Lake"),
("Upper Tankersley"),
("Upper Tarnberry"),
("Upper Taylors"),
("Upper Tean"),
("Upper Teddington"),
("Upper Tennyson"),
("Upper Thames"),
("Upper Thicket"),
("Upper Third"),
("Upper Thirstin"),
("Upper Thomas"),
("Upper Thornton"),
("Upper Thrift"),
("Upper Throat Pool"),
("Upper Thurnham"),
("Upper Tichborne"),
("Upper Tilehouse"),
("Upper Tockington"),
("Upper Tokes"),
("Upper Tollington"),
("Upper Tomvaich"),
("Upper Tone"),
("Upper Toothill"),
("Upper Tooting"),
("Upper Tor"),
("Upper Tormsdale Pool"),
("Upper Torrs"),
("Upper Torwoodhill"),
("Upper Tote"),
("Upper Tott Shaw"),
("Upper Town"),
("Upper Trawscoed"),
("Upper Tredrea"),
("Upper Trelyn"),
("Upper Tribute"),
("Upper Tring"),
("Upper Trinity"),
("Upper Trosnant"),
("Upper Troublesome Reach"),
("Upper Tullich"),
("Upper Tulse"),
("Upper Tumbril"),
("Upper Tyndrum"),
("Upper Tynings"),
("Upper Tysoe"),
("Upper Tything"),
("Upper Under"),
("Upper Union"),
("Upper Uphall"),
("Upper Upham"),
("Upper Upnor"),
("Upper Valley"),
("Upper Vann"),
("Upper Vaughan"),
("Upper Vauxhall"),
("Upper Vernon"),
("Upper Verran"),
("Upper Vert"),
("Upper Viaduct"),
("Upper Vicarage"),
("Upper Villiers"),
("Upper Vobster"),
("Upper Wallemoore Covert"),
("Upper Walmer"),
("Upper Walthamstow"),
("Upper Wanborough"),
("Upper Wardington"),
("Upper Wardown"),
("Upper Warehams"),
("Upper Wargrave"),
("Upper Warlingham"),
("Upper Warren"),
("Upper Warrengate"),
("Upper Warwick"),
("Upper Washer"),
("Upper Washwell"),
("Upper Waston"),
("Upper Watchingwell"),
("Upper Water"),
("Upper Waterhay"),
("Upper Waun"),
("Upper Waxhall"),
("Upper Weald"),
("Upper Weedon"),
("Upper Well"),
("Upper Welland"),
("Upper Wellheads"),
("Upper Wellhouse"),
("Upper Wellingham"),
("Upper Wellington"),
("Upper Wells"),
("Upper Welson"),
("Upper Wensum"),
("Upper Wepham"),
("Upper Westby"),
("Upper Westhill"),
("Upper Westholme"),
("Upper Westley"),
("Upper Westlock"),
("Upper Weston"),
("Upper Westwood"),
("Upper Wetmoor"),
("Upper Weybourne"),
("Upper Weybread"),
("Upper Wharf"),
("Upper Wharfedale"),
("Upper Whatcombe"),
("Upper Whiphill"),
("Upper Whiston"),
("Upper Whitelea"),
("Upper Whiteside"),
("Upper Whitley Edge"),
("Upper Wick"),
("Upper Wickham"),
("Upper Widhill"),
("Upper Wield"),
("Upper Wilcove"),
("Upper Wilderness"),
("Upper William"),
("Upper Willington"),
("Upper Willow Beds"),
("Upper Willow Hall"),
("Upper Wilton"),
("Upper Wimpole"),
("Upper Winchendon"),
("Upper Windleden Reservoir"),
("Upper Windsor"),
("Upper Winfield"),
("Upper Wish"),
("Upper Witton"),
("Upper Woburn"),
("Upper Wolvercote"),
("Upper Wolverton"),
("Upper Wolves"),
("Upper Womans"),
("Upper Woodcote"),
("Upper Woodcott Down"),
("Upper Woodford"),
("Upper Woodhouse"),
("Upper Woodland"),
("Upper Woodlands"),
("Upper Woodside"),
("Upper Woodview"),
("Upper Woolgrove"),
("Upper Woolhampton"),
("Upper Woollaston Covert"),
("Upper Wootton"),
("Upper Wortley"),
("Upper Wraxall"),
("Upper Wriggle"),
("Upper Wrigglebrook"),
("Upper Writhlington"),
("Upper Wyche"),
("Upper Wyke"),
("Upper Yarborough"),
("Upper Yeld"),
("Upper Yeo"),
("Upper York"),
("Upper Youlbury Heath"),
("Upper Zoar"),
("Upperbarn"),
("Upperboat"),
("Upperbreach Belt"),
("Upperbrook"),
("Upperby"),
("Uppercliff"),
("Uppercommon"),
("Uppercraft Fleet"),
("Uppercroft"),
("Upperdale"),
("Upperfield"),
("Upperfields"),
("Upperford"),
("Uppergate"),
("Upperhead"),
("Upperhouse"),
("Upperkirk"),
("Upperkirkgate"),
("Upperlands"),
("Uppermill"),
("Uppermoor"),
("Uppermoss"),
("Uppermost Clough"),
("Upperstaff"),
("Upperstone"),
("Upperthong"),
("Upperthorpe"),
("Upperthorpe Villas"),
("Upperton"),
("Uppertown"),
("Upperup"),
("Upperway Furlong"),
("Upperwood"),
("Upphall"),
("Uppincott"),
("Upping"),
("Uppingham"),
("Uppington"),
("Uppleby"),
("Uppsala"),
("Upright Cliff"),
("Upron"),
("Ups'),
('Downs"),
("Upsall"),
("Upsdell"),
("Upsettlington"),
("Upsher"),
("Upsheres"),
("Upshire"),
("Upshot"),
("Upsland"),
("Upsons"),
("Upstall"),
("Upstreet"),
("Upthorpe"),
("Upton"),
("Upton Barn"),
("Upton Beacon"),
("Upton Bishop"),
("Upton Bridle"),
("Upton Broad"),
("Upton Brooks"),
("Upton by Chester"),
("Upton By Pass"),
("Upton Carr"),
("Upton Cheyney"),
("Upton Coombe"),
("Upton Cow Down"),
("Upton Cressett"),
("Upton Crews"),
("Upton Cross"),
("Upton Day"),
("Upton Dene"),
("Upton Down"),
("Upton Dyke"),
("Upton Grey"),
("Upton Hall"),
("Upton Heath"),
("Upton Hellions"),
("Upton Lake"),
("Upton Lane Site"),
("Upton Lea"),
("Upton Lodge"),
("Upton Lovell"),
("Upton Magna"),
("Upton Manor"),
("Upton Marshes"),
("Upton Noble"),
("Upton Pyne"),
("Upton Quarry"),
("Upton Rocks"),
("Upton Scudamore"),
("Upton Snodsbury"),
("Upton St Leonards"),
("Upton St. Leonards"),
("Upton Stones"),
("Upton Towans"),
("Upton upon Severn"),
("Upton Valley"),
("Upton Warren"),
("Upton with Fishley"),
("Uptons"),
("Upwaltham"),
("Upware"),
("Upway"),
("Upways"),
("Upwell"),
("Upwell'),
('Delph"),
("Upwell Fen"),
("Upwey"),
("Upwey'),
('Broadwey"),
("Upwick"),
("Upwood"),
("Upwood Airfield"),
("Upwood'),
('the Raveleys"),
("Upwoods"),
("Ura"),
("Ura Firth"),
("Ura Geo"),
("Ura Stack"),
("Urabug"),
("Uradale"),
("Urafirth"),
("Uragaig"),
("Uraghag"),
("Uralite Halt"),
("Uranus"),
("Urasoe"),
("Urawa"),
("Urayasu"),
("Urban"),
("Urban Hive"),
("Urch"),
("Urchair Fhada"),
("Urchany'),
('Farley"),
("Urchar"),
("Urchfont"),
("Urchfont'),
('The Cannings"),
("Urchfont Down"),
("Urchfont Gorse"),
("Urchin"),
("Urchin Clough"),
("Urchinwood"),
("Urd"),
("Urda Stack"),
("Urdaneta"),
("Urdimarsh"),
("Ure"),
("Ure Bank Maltings"),
("Ure Bank Top"),
("Ure Force"),
("Ure Water"),
("Uredale"),
("Urford"),
("Urfords"),
("Urgashay"),
("Urgench"),
("Urgha"),
("Uribia"),
("Uridge"),
("Urie"),
("Urie Head"),
("Urie Lingey"),
("Urie Loch"),
("Urie Ness"),
("Urievale"),
("Urinbeg"),
("Urishay"),
("Urishay Villa"),
("Urit"),
("Urlar"),
("Urlay"),
("Urlay Nook"),
("Urlwin"),
("Urmia"),
("Urmond"),
("Urmson"),
("Urmston"),
("Urmston House"),
("Urnachean"),
("Urnfield"),
("Urpeth"),
("Urquart"),
("Urquhart"),
("Urquhart'),
('Glenmoriston"),
("Urquhart'),
('Logie Wester"),
("Urquhart Cut"),
("Urquhart Wynd"),
("Urquharts"),
("Urr"),
("Urr Water"),
("Urra"),
("Urra Taing"),
("Urrall"),
("Urrall Loch"),
("Urray"),
("Urrdale"),
("Ursa"),
("Ursa Major"),
("Ursula"),
("Ursula Gould"),
("Ursula Taylor"),
("Ursuline"),
("Ursuline Convent"),
("Urswick"),
("Urswick Tarn"),
("Uruapan"),
("Uruguaiana"),
("Uruma"),
("Urvaig"),
("Urwick"),
("Urwin"),
("Ury"),
("Ury Dale"),
("Uryside"),
("Usan"),
("Usan Ness"),
("Usborne"),
("Usbourne"),
("Ushat Geo"),
("Ushat Head"),
("Ushaw"),
("Usher"),
("Ushercombe"),
("Ushercoombe"),
("Ushers"),
("Ushers Wynd"),
("Usherwood"),
("Usk"),
("Usk Patch"),
("Usk Reservoir"),
("Usk Vale"),
("Usker"),
("Uskers"),
("Uskie Geo"),
("Uskley"),
("Uskmouth"),
("Usmere"),
("Usmore"),
("Usprig"),
("Usprig Meadhoin"),
("Usselby"),
("Ussie"),
("Ussleby"),
("Ussuriysk"),
("Usta Ness"),
("Usterdale"),
("Ustick Moss"),
("Usticke"),
("Usulwall"),
("Usway"),
("Usworth"),
("Usworth Station"),
("Utah"),
("UTC Building"),
("UTC Central Bedfordshire"),
("UTC Norfolk"),
("UTC Plymouth"),
("UTC Portsmouth"),
("UTC Reading"),
("UTC Sheffield"),
("UTC Warrington"),
("UTC@harbourside"),
("UTC@MediaCityUK"),
("Utgard"),
("Utica"),
("Utile"),
("Utkinton"),
("Utkinton'),
('Cotebrook"),
("Utla Taing"),
("Utleys"),
("Uton"),
("Utopia"),
("Utrecht"),
("Utrillo"),
("Utstabi"),
("Utsunomiya"),
("Uttarpara"),
("Utterby"),
("Utterby Side"),
("Utters"),
("Utting"),
("Uttlesford"),
("Uttley"),
("Uttons"),
("Uttons Drove"),
("Uttoxeter"),
("Uttoxeter New"),
("Uttoxeter Old"),
("Uttoxeter Rural"),
("Uttoxeter Town"),
("Uvedale"),
("Uverdale"),
("Uwch Conwy"),
("Uwch Gwendraeth"),
("Uwch Menai"),
("Uwch Mynydd"),
("Uwch Y Don"),
("Uwch Y Dre"),
("Uwch y llan"),
("Uwch Y Maes"),
("Uwch Y Mor"),
("Uwch Y Nant"),
("Uwchafon"),
("Uwchaled"),
("Uwchlawr Coed"),
("Uwchmynydd"),
("Uwchydre"),
("Uwchygarreg"),
("Uwe Hillside"),
("Ux Ness"),
("Uxavig"),
("Uxbridge"),
("Uxbridge'),
('South Ruislip"),
("Uxbridge Road High"),
("Uxbridge Road The Broadway"),
("Uxendon"),
("Uxilla"),
("Uxmore"),
("Uxna Geo"),
("Uyea"),
("Uyea Sound"),
("Uyeasound"),
("Uynarey"),
("Uzella"),
("Uzhhorod"),
("Uzmaston"),
("Uzzles"),
("Uşak");
-- Down
DELETE FROM Placename WHERE keyword LIKE 'u%';