-- Up
INSERT INTO "Placename"
("keyword")
VALUES
('U Wybr Ty Coch'),
('U.P. Lane'),
('U.P. Road'),
('Uabhal Mòr'),
('Uachdar'),
('Uamascleit'),
('Uamh'),
('Uamh an Druideig'),
('Uamh Bheag'),
('Uamh Capuill'),
('Uamh Dhonn'),
('Uamh Ghamhainn'),
('Uamh Latha'),
('Uamh Lice Ruaidhe'),
('Uamh na h-Acrach'),
('Uamh na h-Oidhche'),
('Uamh nan Clach'),
('Uamh nan Daoine'),
('Uamh nan Ròn'),
('Uamh nan Soithichean'),
('Uamh Oir'),
('Uamh Phadaich'),
('Uamh Ruaidhridh'),
('Uamha na Creadha'),
('Uamha na Seann Daoine'),
('Uamha Sloc Bhearnasgaig'),
('Uamhag Labhruinn'),
('Uamhag na Creige-streap'),
('Uamhag nan Gobhar'),
('Uamish'),
('Uamvar Street'),
('Uath Lochan'),
('Ubberley'),
('Ubberley Road'),
('Ubbeston'),
('Ubbeston Green'),
('Ubbeston Way'),
('Ubbeston Wood'),
('Uberash Plain'),
('Uberash Roughs'),
('Ubique Avenue'),
('Ubley'),
('Ubley Drove'),
('Ubley Sideling'),
('Ubley Wood'),
('Ubsdell Close'),
('Uchaf Corris'),
('Uchd a Bhuic'),
('Uchd a Chlàrsair'),
('Uchd a Phollain Shàmhaich'),
('Uchd an Ã™ird Wood'),
('Uchd Mòr'),
('Uchdach Bhrisdidh Cridhe'),
('Uchel Dre'),
('Ucheldre'),
('Ucheldre Avenue'),
('Ucheldre Wood'),
('Uckerby'),
('Uckerby Fox Covert'),
('Uckfield'),
('Uckfield Central'),
('Uckfield Close'),
('Uckfield Community'),
('Uckfield Grove'),
('Uckfield Lane'),
('Uckfield New Town'),
('Uckfield North'),
('Uckfield Ridgewood'),
('Uckfield Road'),
('Uckfield South With Framfield'),
('Uckham Lane'),
('Uckinghall'),
('Uckinghall Meadow'),
('Uckington'),
('Uckington Heath'),
('Udairn'),
('Udale Bay'),
('Udale Court'),
('Udale Place'),
('Udale Street'),
('Udall Gardens'),
('Udall Road'),
('Udall Street'),
('Uddens'),
('Uddens Coppice'),
('Uddens Drive'),
('Uddens Park'),
('Uddens Road'),
('Uddern Copse'),
('Uddingston'),
('Uddingston Road'),
('Uddington'),
('Uden Road'),
('Udford Wood'),
('Udi Geo'),
('Udiam Lane'),
('Udimore'),
('Udimore Road'),
('Udley'),
('Udney Park Road'),
('Udny'),
('Udny Green'),
('Udny Place'),
('Udracleit'),
('Udston'),
('Udston Avenue'),
('Udston'),
('Udston Mill Road'),
('Udston Road'),
('Udston Terrace'),
('Udstonhead'),
('Uffa Hill'),
('Uffa Magna'),
('Uffcott'),
('Uffcott Close'),
('Uffcott Down'),
('Uffculme'),
('Uffculme Down'),
('Uffculme Road'),
('Uffen Way'),
('Uffington'),
('Uffington Avenue'),
('Uffington Close'),
('Uffington Court'),
('Uffington Down'),
('Uffington Drive'),
('Uffington Gorse'),
('Uffington New Wood'),
('Uffington Parade'),
('Uffington Park'),
('Uffington Place'),
('Uffington Road'),
('Uffington Wood'),
('Uffmoor'),
('Uffmoor Estate'),
('Uffmoor Green'),
('Uffmoor Lane'),
('Uffmoor Wood'),
('Ufford'),
('Ufford Close'),
('Ufford Oaks'),
('Ufford Place'),
('Ufford Road'),
('Ufford Spinney'),
('Ufford Street'),
('Ufford Thicks'),
('Ufton'),
('Ufton Close'),
('Ufton Common'),
('Ufton Crescent'),
('Ufton Croft'),
('Ufton Fields'),
('Ufton Green'),
('Ufton Grove'),
('Ufton Hill'),
('Ufton Lane'),
('Ufton Nervet'),
('Ufton Park'),
('Ufton Road'),
('Ufton Wood'),
('Ugadale Point'),
('Ugag'),
('Uganda Street'),
('Ugasta'),
('Ugborough'),
('Ugborough Beacon'),
('Ugborough Moor'),
('Ugborough Road'),
('Ugbrooke Park'),
('Ugford'),
('Ugford Clump'),
('Ugg Mere'),
('Ugg Mere Court Road'),
('Uggeshall'),
('Uggeshall Close'),
('Uggeshall Hill'),
('Uggeshall Spring'),
('Uggle Lane'),
('Ugglebarnby'),
('Ugglebarnby Moor'),
('Uggoe Hill'),
('Ughill'),
('Ughill Moors'),
('Ughill Road'),
('Ughill Wood'),
('Ugie Drive'),
('Ugie'),
('Ugie Place'),
('Ugie Road'),
('Ugie Street'),
('Ugie View'),
('Ugiebank Place'),
('Ugley'),
('Ugley Green'),
('Uglow Close'),
('Ugly Dale'),
('Ugly Lane'),
('Ugthorpe'),
('Ugthorpe Moor'),
('Ugworthy Moor'),
('UHI Millennium Institute'),
('Uibhist a Deas'),
('Uibhist a Tuath'),
('Uidh'),
('Uidh Alasdair Ghuinnich'),
('Uidh an Tigh Sheilg'),
('Uidh nam Fiadh'),
('Uidh-Gharbh'),
('Uidhe Gharbh'),
('Uidhseal'),
('Uig'),
('Uig Bay'),
('Uig Ferry'),
('Uig Place'),
('Uige Sgeir'),
('Uigean'),
('Uigen'),
('Uiginis'),
('Uiginish'),
('Uiginish Bonnet'),
('Uiginish Point'),
('Uigshader'),
('Uilbhinnis'),
('Uilystrand Brae'),
('Uilystrand Heugh'),
('Uineabhal'),
('Uineasan'),
('Uirigh Bheithe'),
('Uirigh na Salach'),
('Uiseabhal'),
('Uisge Fear-fiamh'),
('Uisge Ruadh'),
('Uisgneabhal Beag'),
('Uisgneabhal Mòr'),
('Uisinis'),
('Uist Avenue'),
('Uist Crescent'),
('Uist Drive'),
('Uist Lane'),
('Uist Place'),
('Uist Road'),
('Uist Street'),
('Uist Terrace'),
('Uist Way'),
('Ukna Skerry'),
('Ukraine Road'),
('Ul Dale'),
('Ulabhal'),
('Ulalia Road'),
('Ulbster'),
('Ulcat Row'),
('Ulceby'),
('Ulceby Carr'),
('Ulceby Cross'),
('Ulceby Road'),
('Ulceby Skitter'),
('Ulceby with Fordington'),
('Ulcombe'),
('Ulcombe Gardens'),
('Ulcombe Hill'),
('Ulcombe Road'),
('Uldale'),
('Uldale Close'),
('Uldale Court'),
('Uldale Drive'),
('Uldale Fells'),
('Uldale Force'),
('Uldale Grove'),
('Uldale Head'),
('Uldale Road'),
('Uldale View'),
('Uldale Way'),
('Uley'),
('Uley Road'),
('Ulfgar Road'),
('Ulfhart Point'),
('Ulfkell Road'),
('Ulfred Point'),
('Ulgham'),
('Ulgham Close'),
('Ulgham Lane'),
('Ulgraves'),
('Ulla Green'),
('Ulla Street'),
('Ulladale Crescent'),
('Ullapool'),
('Ullapool Close'),
('Ullapool Crescent'),
('Ullapool Hills'),
('Ullapool Point'),
('Ullapow'),
('Ullard Hall Lane'),
('Ullathorne Rise'),
('Ullathorne Road'),
('Ullathorns Wood'),
('Ullcombe Lane'),
('Ulldale Court'),
('Ullen Wood'),
('Ullenhall'),
('Ullenhall Lane'),
('Ullenhall Road'),
('Ullenhall Street'),
('Ullenwood'),
('Ullenwood Reservoir'),
('Ullenwood Road'),
('Ullerdale Close'),
('Ulleries Road'),
('Ullermire'),
('Ullesby Gardens'),
('Ulleskelf'),
('Ullesthorpe'),
('Ullesthorpe Road'),
('Ulleswater Close'),
('Ulleswater Crescent'),
('Ulleswater Road'),
('Ulleswater Street'),
('Ullet Road'),
('Ulley'),
('Ulley Crescent'),
('Ulley Holt'),
('Ulley Lane'),
('Ulley Reservoir'),
('Ulley Road'),
('Ulley View'),
('Ullie Geo'),
('Ullin Street'),
('Ullingswick'),
('Ullington'),
('Ullinish'),
('Ullins Geo'),
('Ullins Water'),
('Ullioch Hill'),
('Ullister Hill'),
('Ullock'),
('Ullock Coppice'),
('Ullock Moss'),
('Ullock Pike'),
('Ullrik Green'),
('Ullscarf'),
('Ullscarf Close'),
('Ullswater'),
('Ullswater Avenue'),
('Ullswater Close'),
('Ullswater Court'),
('Ullswater Crescent'),
('Ullswater Drive'),
('Ullswater Gardens'),
('Ullswater Grove'),
('Ullswater Park'),
('Ullswater Place'),
('Ullswater Rise'),
('Ullswater Road'),
('Ullswater Street'),
('Ullswater Terrace'),
('Ullswater Way'),
('Ullswheel'),
('Ulluva'),
('Ullyatts Drove'),
('Ulnaby Lane'),
('Ulnes Walton'),
('Ulnes Walton Lane'),
('Ulph'),
('Ulph Place'),
('Ulpha'),
('Ulpha Close'),
('Ulpha Fell'),
('Ulpha Park'),
('Ulpha Wood'),
('Ulrica Drive'),
('Ulrick Avenue'),
('Ulrome'),
('Ulrome Court'),
('Ulrome Sands'),
('Ulshaw'),
('Ulsta'),
('Ulstan Close'),
('Ulster Avenue'),
('Ulster Close'),
('Ulster Crescent'),
('Ulster Drive'),
('Ulster Gardens'),
('Ulster Grove'),
('Ulster Place'),
('Ulster Road'),
('Ulster Street'),
('Ulster Terrace'),
('Ulston Moor'),
('Ulswater Avenue'),
('Ulthwaite Rigg'),
('Ulting'),
('Ulting Grove'),
('Ulting Hall Road'),
('Ulting Lane'),
('Ulting Road'),
('Ulting Way'),
('Ultra Avenue'),
('Ultra Close'),
('Ulundi Road'),
('Ulundi Street'),
('Ulva'),
('Ulva Islands'),
('Ulva Road'),
('Ulva Street'),
('Ulverley Crescent'),
('Ulverley Green'),
('Ulverley Green Road'),
('Ulvers Croft Way'),
('Ulverscroft'),
('Ulverscroft Drive'),
('Ulverscroft Lane'),
('Ulverscroft Pond'),
('Ulverscroft Road'),
('Ulverscroft Wood'),
('Ulverston'),
('Ulverston Avenue'),
('Ulverston Channel'),
('Ulverston Close'),
('Ulverston Crescent'),
('Ulverston Drive'),
('Ulverston East'),
('Ulverston Gardens'),
('Ulverston Green'),
('Ulverston Lawn'),
('Ulverston Road'),
('Ulverston Sands'),
('Ulverston Terrace'),
('Ulverston West'),
('Ulverstone Road'),
('Ulverstone Terrace'),
('Ulviet Gate'),
('Ulwell'),
('Ulwell Road'),
('Ulwin Avenue'),
('Ulyett Lane'),
('Ulyett Place'),
('Ulysses Road'),
('Umachan'),
('Umber Close'),
('Umberleigh'),
('Umberleigh Road'),
('Umberley Sick'),
('Umberly Road'),
('Umbers Hill'),
('Umberslade Park'),
('Umberslade Road'),
('Umberston Street'),
('Umberstone'),
('Umberstone Covert'),
('Umberton Road'),
('Umberville Way'),
('Umbrella Wood'),
('Umbria Street'),
('Umfraville Dene'),
('Umfreville Road'),
('Umpire Close'),
('Umpire View'),
('Umpleby Wood'),
('Una Avenue'),
('Una Place'),
('Una Road'),
('Unapool'),
('Unasaraidh Islands'),
('Uncle Bens Close'),
('Uncle Toms Point'),
('Uncleby'),
('Uncleby Hill'),
('Uncleby Wold'),
('Uncles Hillock'),
('Uncles Lane'),
('Uncombe Close'),
('Uncouth Road'),
('Under Bank'),
('Under Billinge Lane'),
('Under Cardiff Road'),
('Under Chapel Yard'),
('Under Clough'),
('Under Covert'),
('Under Ffrydd Wood'),
('Under Greave Wood'),
('Under Hill'),
('Under Hill Close'),
('Under Hill Flat'),
('Under Hill Head'),
('Under Knoll'),
('Under Lane'),
('Under Lee'),
('Under Loan Park'),
('Under Minnow Road'),
('Under Nine Rocks'),
('Under Parade Road'),
('Under Parks'),
('Under Rainow Road'),
('Under Ripton Wood'),
('Under Road'),
('Under Saddle Yoke'),
('Under Scar'),
('Under Sheriffs Clump'),
('Under the Hill'),
('Under The Hills'),
('Under the Low'),
('Under The Wood'),
('Under Tofts'),
('Under Town'),
('Under Way'),
('Under Win Green'),
('Under Wood'),
('Under Woods'),
('Under-th-bank'),
('Underacre Close'),
('Underacres Close'),
('Underbank'),
('Underbank Avenue'),
('Underbank Close'),
('Underbank End Road'),
('Underbank Hoe'),
('Underbank Lane'),
('Underbank Old Road'),
('Underbank Reservoir'),
('Underbank Road'),
('Underbank Way'),
('Underbank Wood'),
('Underbanks'),
('Underbarrow'),
('Underbarrow and Bradleyfield'),
('Underbarrow Moss'),
('Underbarrow Pool'),
('Underbarrow Road'),
('Underbridge Lane'),
('Underbrow Wood'),
('Undercleave Copse'),
('Undercleave Wood'),
('Undercliff'),
('Undercliff Avenue'),
('Undercliff Drive'),
('Undercliff Gardens'),
('Undercliff Road'),
('Undercliff Road East'),
('Undercliff Road West'),
('Undercliff Terrace'),
('Undercliffe'),
('Undercliffe Drive'),
('Undercliffe Lane'),
('Undercliffe Old Road'),
('Undercliffe Rise'),
('Undercliffe Road'),
('Undercliffe Street'),
('Undercraigs Court'),
('Undercraigs Drive'),
('Undercraigs Place'),
('Undercraigs Road'),
('Undercroft'),
('Underdale'),
('Underdale Avenue'),
('Underdale Road'),
('Underdown'),
('Underdown Avenue'),
('Underdown Bottom'),
('Underdown Close'),
('Underdown Covert'),
('Underdown Hollow'),
('Underdown Lane'),
('Underdown Moor'),
('Underdown Road'),
('Underdown Wood'),
('Underfell'),
('Underfleet'),
('Undergate Field'),
('Undergate Road'),
('Undergreens Road'),
('Underhay'),
('Underhay Close'),
('Underhayes Court'),
('Underhayes Lane'),
('Underhedge Gardens'),
('Underhelm Wood'),
('Underhill'),
('Underhill Avenue'),
('Underhill Circus'),
('Underhill Close'),
('Underhill Coppice'),
('Underhill Copse'),
('Underhill Crescent'),
('Underhill Drive'),
('Underhill Lake'),
('Underhill Lane'),
('Underhill Park'),
('Underhill Park Road'),
('Underhill Road'),
('Underhill Spinney'),
('Underhill Street'),
('Underhill Terrace'),
('Underhill Way'),
('Underhill Wood'),
('Underhills Wood'),
('Underhoull'),
('Underhowe Coppice'),
('Underidge Close'),
('Underidge Drive'),
('Underidge Road'),
('Underlaid Wood'),
('Underland Girt'),
('Underland Wood'),
('Underlands Lane'),
('Underlands Wood'),
('Underlane'),
('Underleaf Close'),
('Underleaf Way'),
('Underleat Close'),
('Underley'),
('Underley Avenue'),
('Underley Close'),
('Underley Cop'),
('Underley Copse'),
('Underley Hill'),
('Underley Road'),
('Underley Street'),
('Underleys'),
('Underling Green'),
('Underlyn Lane'),
('Undermill Road'),
('Undermillbeck Common'),
('Undermoss Strip'),
('Underne Avenue'),
('Underplot Copse'),
('Underriver'),
('Underriver House Road'),
('Underscar'),
('Undershaft'),
('Undershaw'),
('Undershaw Road'),
('Undershore'),
('Undershore Road'),
('Underskiddaw'),
('Undersley Wood'),
('Underton'),
('Undertown'),
('Undertown Lane'),
('Undertown Wood'),
('Undertrees Close'),
('Underway Lane'),
('Underways'),
('Underwit Road'),
('Underwit Wood'),
('Underwood'),
('Underwood Avenue'),
('Underwood Close'),
('Underwood Cottages'),
('Underwood Court'),
('Underwood Crescent'),
('Underwood Drive'),
('Underwood End'),
('Underwood Gardens'),
('Underwood Glen'),
('Underwood Grove'),
('Underwood Hill'),
('Underwood Lane'),
('Underwood Mews'),
('Underwood Place'),
('Underwood Rise'),
('Underwood Road'),
('Underwood Row'),
('Underwood Square'),
('Underwood Street'),
('Underwood Terrace'),
('Underwood Way'),
('Underwoods Grounds'),
('Underwoods Grove'),
('Underwoods Hard'),
('Underwoods Hill Spinney'),
('Underwoods Lane'),
('Underwoods Wood'),
('Undine Road'),
('Undine Street'),
('Undirhoul'),
('Undley'),
('Undley Common'),
('Undley Road'),
('Undraynian Point'),
('Undsworth Court'),
('Undy'),
('Undy Common'),
('Uned Ty Aalton'),
('Uneeda Drive'),
('Unett Street'),
('Unett Street North'),
('Unetts Wood'),
('Ungain Deep'),
('Ungam'),
('Ungla Skerry'),
('Unglabreid'),
('Unhill Bottom'),
('Unhill Wood'),
('Uni Firth'),
('Unicorn Avenue'),
('Unicorn Close'),
('Unicorn Court'),
('Unicorn Gateway'),
('Unicorn Hill'),
('Unicorn Lane'),
('Unicorn Place'),
('Unicorn Road'),
('Unicorn Row'),
('Unicorn Street'),
('Unicorn View'),
('Unicorn Walk'),
('Unicorn Way'),
('Unicorn Yard'),
('Unicumes Lane'),
('Unifirth'),
('Unilever'),
('Union Alley'),
('Union Arcade'),
('Union Avenue'),
('Union Bank Lane'),
('Union Bay'),
('Union Belt'),
('Union Brae'),
('Union Buildings'),
('Union Castle Row'),
('Union Close'),
('Union Court'),
('Union Crescent'),
('Union Cross Yard'),
('Union Dock'),
('Union Drift'),
('Union Drive'),
('Union Drove'),
('Union Gardens'),
('Union Gate'),
('Union Glen'),
('Union Gorse'),
('Union Gorse Covert'),
('Union Green'),
('Union Grove'),
('Union Grove Lane'),
('Union Hall Road'),
('Union Hill'),
('Union House Lane'),
('Union Lane'),
('Union Mill Close'),
('Union Mill Street'),
('Union Mine Road'),
('Union Park'),
('Union Park Road'),
('Union Passage'),
('Union Place'),
('Union Quay'),
('Union Rise'),
('Union Road'),
('Union Road East'),
('Union Road West'),
('Union Row'),
('Union Spinney'),
('Union Square'),
('Union Street'),
('Union Street Lane'),
('Union Terrace'),
('Union Walk'),
('Union Way'),
('Union Wood'),
('Union Wynd'),
('Union Yard'),
('Unique Way'),
('Unit Road'),
('Unitas Crescent'),
('Unitas Road'),
('United Downs'),
('United Downs industrial Park'),
('United Road'),
('United Way'),
('Unitt Drive'),
('Unitt Road'),
('Unity Avenue'),
('Unity Close'),
('Unity Court'),
('Unity Crescent'),
('Unity Drive'),
('Unity Gardens'),
('Unity Grove'),
('Unity Hall Court'),
('Unity Lane'),
('Unity Mews'),
('Unity Park'),
('Unity Place'),
('Unity Road'),
('Unity Square'),
('Unity Street'),
('Unity Terrace'),
('Unity Way'),
('Unity Wood'),
('Universal Close'),
('Universal Road'),
('Universal Street'),
('University Avenue'),
('University Boulevard'),
('University Centre'),
('University Centre Rotherham'),
('University Centre Shrewsbury'),
('University Close'),
('University Court'),
('University Crescent'),
('University Drive'),
('University Farm'),
('University Gardens'),
('University'),
('University Hospital Ayr'),
('University Hospital Crosshouse'),
('University Hospital Hairmyres'),
('University Hospital Llandough'),
('University Hospital of Hartlepool'),
('University Hospital Of North Durham'),
('University Hospital Of North Tees'),
('University Hospital of Wales'),
('University Hospital Wishaw'),
('University House'),
('University Park'),
('University Park'),
('University Park Drive'),
('University Parks'),
('University Parkway'),
('University Place'),
('University Road'),
('University Road West'),
('University Street'),
('University Terrace'),
('University Walk'),
('University Way'),
('University Wood'),
('Unketts Road'),
('Unla Water'),
('Unlawater Lane'),
('Unna Way'),
('Unodourised'),
('Unodourised Gas Installation Honeybourne'),
('Unsliven Road'),
('Unst'),
('Unst Lane'),
('Unstead Lane'),
('Unstead Wood'),
('Unsted Place'),
('Unsted Wood'),
('Unstone'),
('Unstone Green'),
('Unstone Hill'),
('Unstone Road'),
('Unstone Street'),
('Unstone-Dronfield By-Pass'),
('Unsworth'),
('Unsworth Avenue'),
('Unsworth Court'),
('Unsworth Gardens'),
('Unsworth Street'),
('Unsworth Way'),
('Unthank'),
('Unthank End'),
('Unthank Hill'),
('Unthank Lane'),
('Unthank Moor'),
('Unthank Road'),
('Unthank Wood'),
('Untons Place'),
('Unwin Avenue'),
('Unwin Close'),
('Unwin Crescent'),
('Unwin Park'),
('Unwin Place'),
('Unwin Pool'),
('Unwin Road'),
('Unwin Square'),
('Unwin Street'),
('Unwin Way'),
('Unwins Lane'),
('Uny Lelant'),
('Up Brooks'),
('Up Cerne'),
('Up Cerne Wood'),
('Up Corner'),
('Up Corner Close'),
('Up Croft'),
('Up End'),
('Up Exe'),
('Up Green'),
('Up Hatherley'),
('Up Hatherley Way'),
('Up Holland'),
('Up Marden'),
('Up Mudford'),
('Up Nately'),
('Up Park'),
('Up Somborne'),
('Up Somborne Down'),
('Up Street'),
('Up Sydling'),
('Up Wood'),
('Up-Brooks'),
('Up-Mudford'),
('Upavon'),
('Upavon Airfield'),
('Upavon Army Camp'),
('Upavon Avenue'),
('Upavon Close'),
('Upavon Down'),
('Upavon Drive'),
('Upavon Gardens'),
('Upavon Garth'),
('Upavon Hill'),
('Upavon Road'),
('Upavon Way'),
('Upbank Wood'),
('Upbrook Mews'),
('Upbury Way'),
('Upcast Lane'),
('Upcerne Road'),
('Upchat Road'),
('Upcher Close'),
('Upchurch'),
('Upchurch Close'),
('Upchurch Walk'),
('Upcot Crescent'),
('Upcott'),
('Upcott Avenue'),
('Upcott Barton'),
('Upcott Barton Wood'),
('Upcott Brake'),
('Upcott Cleave Wood'),
('Upcott Hill'),
('Upcott Lane'),
('Upcott Mead Road'),
('Upcott Moor'),
('Upcott Moors'),
('Upcott Plantations'),
('Upcott Road'),
('Upcott Valley'),
('Upcott Wood'),
('Upcroft'),
('Upcroft Avenue'),
('Upcross Gardens'),
('Updale Close'),
('Updale Road'),
('Updown Hill'),
('Updown Way'),
('Updown Wood'),
('Upend'),
('Upend Wood'),
('Upende'),
('Upex Close'),
('Upexe Lane'),
('Upfallow'),
('Upfield'),
('Upfield Close'),
('Upfield Road'),
('Upfield Way'),
('Upfold Close'),
('Upfold Lane'),
('Upfolds Green'),
('Upfra Loch'),
('Upgang Beach'),
('Upgang Lane'),
('Upgarth Close'),
('Upgate'),
('Upgate Common'),
('Upgate Road'),
('Upgate Street'),
('Uphall'),
('Uphall and Winchburgh Broxburn'),
('Uphall Place'),
('Uphall Road'),
('Uphall Station Road'),
('Uphalle'),
('Upham'),
('Upham Copse'),
('Upham Lane'),
('Upham Park Road'),
('Upham Road'),
('Upham Street'),
('Uphampton'),
('Uphay Lane'),
('Upherds Lane'),
('Uphill'),
('Uphill Close'),
('Uphill Drive'),
('Uphill Grove'),
('Uphill Lane'),
('Uphill Pill'),
('Uphill Road'),
('Uphill Way'),
('Uphills'),
('Upholland'),
('Upholland Close'),
('Upholland Road'),
('Uphouse Road'),
('Upjohn Crescent'),
('Upland Avenue'),
('Upland Chase'),
('Upland Close'),
('Upland Court Road'),
('Upland Crescent'),
('Upland Drive'),
('Upland Gardens'),
('Upland Grove'),
('Upland Lane'),
('Upland Park Road'),
('Upland Rise'),
('Upland Road'),
('Upland Shaw'),
('Upland Way'),
('Upland Wynd'),
('Uplands'),
('Uplands Avenue'),
('Uplands Chase'),
('Uplands Close'),
('Uplands Coppice'),
('Uplands Crescent'),
('Uplands Croft'),
('Uplands Drive'),
('Uplands Farm Barns'),
('Uplands Gardens'),
('Uplands Green'),
('Uplands Grove'),
('Uplands Lane'),
('Uplands Park'),
('Uplands Park Road'),
('Uplands Rise'),
('Uplands Road'),
('Uplands Square'),
('Uplands Terrace'),
('Uplands Vean'),
('Uplands Way'),
('Uplands Wood'),
('Uplawmoor'),
('Uplawmoor Road'),
('Uplawmoor Wood'),
('Upleadon'),
('Upleadon Close'),
('Upleatham'),
('Upleatham Grove'),
('Upleatham Street'),
('Uplees'),
('Uplees Marshes'),
('Uplees Road'),
('Uplin Crescent'),
('Uploders'),
('Uplowman'),
('Uplowman Road'),
('Uplyme'),
('Uplyme Close'),
('Uplyme Road'),
('Upmeadows Drive'),
('Upmill Close'),
('Upminster'),
('Upminster Bridge'),
('Upminster Close'),
('Upminster Common'),
('Upminster Drive'),
('Upminster Road'),
('Upney'),
('Upney Close'),
('Upney Lane'),
('Upney Wood'),
('Upnor Close'),
('Upnor Reach'),
('Upnor Road'),
('Upnor Way'),
('Upottery'),
('Uppacott'),
('Uppacott Down'),
('Uppark Drive'),
('Uppark Gardens'),
('Uppark Way'),
('Uppat Place'),
('Uppat Wood'),
('Uppaton'),
('Uppaton Lane'),
('Uppend'),
('Upper Abbey Road'),
('Upper Abbey Street'),
('Upper Abbotstone Wood'),
('Upper Abbotts Hill'),
('Upper Abercanaid'),
('Upper Accommodation Road'),
('Upper Acharn Pool'),
('Upper Acres'),
('Upper Ada Street'),
('Upper Adare Street'),
('Upper Addison Gardens'),
('Upper Addison Street'),
('Upper Adelaide Street'),
('Upper Adgestone Road'),
('Upper Affcot'),
('Upper Albert Road'),
('Upper Albion Street'),
('Upper Alders'),
('Upper Allan Street'),
('Upper Allen Street'),
('Upper Allerton Lane'),
('Upper Alma Place'),
('Upper Amport Wood'),
('Upper and Lower Fence Wood'),
('Upper and Lower Shuckburgh'),
('Upper Andover Hill'),
('Upper Anstey Lane'),
('Upper Approach Road'),
('Upper Arail Street'),
('Upper Arbeadie Place'),
('Upper Arbeadie Road'),
('Upper Arcan Road'),
('Upper Archer Street'),
('Upper Ardchronie'),
('Upper Arles Wood'),
('Upper Arley'),
('Upper Armley'),
('Upper Arncott'),
('Upper Arthur Street'),
('Upper Arundel Street'),
('Upper Ash Drive'),
('Upper Ash Grove'),
('Upper Ash Road'),
('Upper Ashley Lane'),
('Upper Ashley Street'),
('Upper Ashlyns Road'),
('Upper Astley'),
('Upper Astley Wood'),
('Upper Aston'),
('Upper Aston Hall Lane'),
('Upper Astrop'),
('Upper Astrop Road'),
('Upper Attington Wood'),
('Upper Auchintore'),
('Upper Aughton Road'),
('Upper Aultderg'),
('Upper Austin Lodge Road'),
('Upper Avenue'),
('Upper Backway'),
('Upper Badcall'),
('Upper Badley Wood'),
('Upper Baggeridge'),
('Upper Baila'),
('Upper Bainbrigge Street'),
('Upper Bairds Covert'),
('Upper Baker Street'),
('Upper Balcom Mews'),
('Upper Balsall Heath Road'),
('Upper Bangor'),
('Upper Banister Street'),
('Upper Bank End Road'),
('Upper Bank Street'),
('Upper Banks'),
('Upper Bannisters Way'),
('Upper Baptist Street'),
('Upper Bar'),
('Upper Barclay Street'),
('Upper Barcott Copse'),
('Upper Barden Reservoir'),
('Upper Barker Street'),
('Upper Barn'),
('Upper Barn Close'),
('Upper Barn Copse'),
('Upper Barn Field'),
('Upper Barn Hanger'),
('Upper Barn Hill'),
('Upper Barn Wood'),
('Upper Barresdale'),
('Upper Barton'),
('Upper Basildon'),
('Upper Basinghall Street'),
('Upper Bath Road'),
('Upper Bath Street'),
('Upper Bathville'),
('Upper Batley'),
('Upper Batley Lane'),
('Upper Batley Low Lane'),
('Upper Battlefield'),
('Upper Battye Street'),
('Upper Bayble'),
('Upper Beanham Wood'),
('Upper Beau Street'),
('Upper Beckwith Street'),
('Upper Bedford Street'),
('Upper Beechen Wood'),
('Upper Beeding'),
('Upper Beeding and Woodmancote Bramber'),
('Upper Belgrave Road'),
('Upper Belgrave Street'),
('Upper Bell Croft'),
('Upper Bell Hall'),
('Upper Belmont Road'),
('Upper Belt'),
('Upper Belvedere'),
('Upper Bench'),
('Upper Benefield'),
('Upper Benter'),
('Upper Bentley'),
('Upper Bere Wood'),
('Upper Berkeley Place'),
('Upper Berkeley Street'),
('Upper Berrington'),
('Upper Berry Wood'),
('Upper Berwick'),
('Upper Beulah Hill'),
('Upper Bevendean Avenue'),
('Upper Biggin'),
('Upper Bilson Road'),
('Upper Birchin Grove'),
('Upper Birchwood'),
('Upper Birtley'),
('Upper Bittell Reservoir'),
('Upper Bitterns Wood'),
('Upper Black Bushes'),
('Upper Black Moss Reservoir'),
('Upper Blackbuck Wood'),
('Upper Blackbush Copse'),
('Upper Blackhead'),
('Upper Blackrock Covert'),
('Upper Blairs Copse'),
('Upper Blakeridge Lane'),
('Upper Blind Lane'),
('Upper Blindlow Lane'),
('Upper Bloomfield Road'),
('Upper Blunts Copse'),
('Upper Boat'),
('Upper Boddington'),
('Upper Bog'),
('Upper Bognor'),
('Upper Bognor Road'),
('Upper Boishall Wood'),
('Upper Bolstone Wood'),
('Upper Bolton Brow'),
('Upper Bolton Strips'),
('Upper Bonchurch'),
('Upper Bond Street'),
('Upper Bonegate'),
('Upper Bongate Gardens'),
('Upper Bonstone Wood'),
('Upper Booth'),
('Upper Borough Walls'),
('Upper Borth'),
('Upper Botten'),
('Upper Boundary Road'),
('Upper Boundstone Lane'),
('Upper Bourne'),
('Upper Bourne End Lane'),
('Upper Bourne Lane'),
('Upper Bourne Vale'),
('Upper Bourtree Court'),
('Upper Bourtree Drive'),
('Upper Bourtree Gardens'),
('Upper Bow'),
('Upper Bowley Copse'),
('Upper Braddons Hill Road'),
('Upper Bradway'),
('Upper Braes'),
('Upper Brailes'),
('Upper Brake'),
('Upper Branch Street'),
('Upper Branston Road'),
('Upper Brassey Street'),
('Upper Bray Road'),
('Upper Breach'),
('Upper Breckland Road'),
('Upper Breeze Hill'),
('Upper Breinton'),
('Upper Brents'),
('Upper Brentwood Road'),
('Upper Bridge Road'),
('Upper Bridge Street'),
('Upper Brig Royd'),
('Upper Brighton Road'),
('Upper Bristol Road'),
('Upper Bristow Copse'),
('Upper Britton Place'),
('Upper Broad Street'),
('Upper Broadheath'),
('Upper Broadmoor Road'),
('Upper Broadridge Coppice'),
('Upper Brockholes'),
('Upper Brockley Road'),
('Upper Brook Covert'),
('Upper Brook Drive'),
('Upper Brook Hill'),
('Upper Brook Lane'),
('Upper Brook Street'),
('Upper Brook Wood'),
('Upper Brooks'),
('Upper Broom Way'),
('Upper Broomgrove Road'),
('Upper Broomieknowe'),
('Upper Brooms Wood'),
('Upper Broughton'),
('Upper Brow Road'),
('Upper Brown Street'),
('Upper Brownhill Road'),
('Upper Bruntingthorpe'),
('Upper Bryans Wood'),
('Upper Bryn Coch'),
('Upper Bryn Road'),
('Upper Brynamman'),
('Upper Brynhyfryd Terrace'),
('Upper Bryntirion Drive'),
('Upper Buckenhill'),
('Upper Buckhurst Shaw'),
('Upper Bucklebury'),
('Upper Bugle Street'),
('Upper Bullington'),
('Upper Burgate'),
('Upper Burgess Street'),
('Upper Burn Moor'),
('Upper Burnside Avenue'),
('Upper Burnside Court'),
('Upper Burnside Drive'),
('Upper Burnthouse Lane'),
('Upper Bush'),
('Upper Bush Road'),
('Upper Bushes'),
('Upper Bute Street'),
('Upper Butts'),
('Upper Byron Place'),
('Upper Cakesbridge Copse'),
('Upper Caldecote'),
('Upper Calton Street'),
('Upper Cam'),
('Upper Cambourne'),
('Upper Cambrian Road'),
('Upper Camden Street'),
('Upper Camp Street'),
('Upper Campbrae Wood'),
('Upper Campsfield Road'),
('Upper Camroyd Street'),
('Upper Canaan'),
('Upper Canada'),
('Upper Canfold Wood'),
('Upper Canning Street'),
('Upper Canterton'),
('Upper Canterton Green'),
('Upper Capel Street'),
('Upper Car Cleuch'),
('Upper Carlisle Road'),
('Upper Carloway'),
('Upper Carman Road'),
('Upper Carr'),
('Upper Carr Lane'),
('Upper Carr Street'),
('Upper Carr Wood'),
('Upper Carters Leys Coppice'),
('Upper Cartsburn Street'),
('Upper Castle Cleugh'),
('Upper Castle Combe'),
('Upper Castle Road'),
('Upper Castle Street'),
('Upper Castle View'),
('Upper Castlehill'),
('Upper Catesby'),
('Upper Catshill'),
('Upper Cavendish Avenue'),
('Upper Cavendish Street'),
('Upper Caxton Wood'),
('Upper Chalkey'),
('Upper Chalkley'),
('Upper Chalvington Place'),
('Upper Chantry Lane'),
('Upper Chapel'),
('Upper Chapel Lane'),
('Upper Chapel Street'),
('Upper Charles Street'),
('Upper Charnwood Street'),
('Upper Chase'),
('Upper Chase Road'),
('Upper Cheddon'),
('Upper Chelsea Street'),
('Upper Cheltenham Place'),
('Upper Chestnut Drive'),
('Upper Cheyne Row'),
('Upper Chicksgrove'),
('Upper Chilmans Downs'),
('Upper Chilstone'),
('Upper Chimes'),
('Upper Chobham Road'),
('Upper Chorlton Road'),
('Upper Church Fields'),
('Upper Church Lane'),
('Upper Church Park'),
('Upper Church Road'),
('Upper Church Street'),
('Upper Church Village'),
('Upper Churnside'),
('Upper Churston Rise'),
('Upper Chute'),
('Upper Chyngton Gardens'),
('Upper Clabdens'),
('Upper Clapton'),
('Upper Clapton Road'),
('Upper Clara Street'),
('Upper Clarence Road'),
('Upper Clatford'),
('Upper Claypark'),
('Upper Cleminson Street'),
('Upper Cleuch'),
('Upper Cliff Road'),
('Upper Cliffe'),
('Upper Cliffe Road'),
('Upper Clifton Road'),
('Upper Close'),
('Upper Close Way'),
('Upper Clough Road'),
('Upper Clwyd Street'),
('Upper Coal Spinney'),
('Upper Coberley'),
('Upper Cockington Lane'),
('Upper Coedcae'),
('Upper Coedcae Road'),
('Upper Coire Faoin Stack'),
('Upper Cokeham'),
('Upper Colbren Road'),
('Upper Coldwell Reservoir'),
('Upper Coll'),
('Upper Colliers Row'),
('Upper Collins'),
('Upper Colquhoun Street'),
('Upper Coltbridge Terrace'),
('Upper Colwall'),
('Upper Commercial Street'),
('Upper Commissary Pool'),
('Upper Common'),
('Upper Common Lane'),
('Upper Common Road'),
('Upper Conham Vale'),
('Upper Conran Street'),
('Upper Constitution Street'),
('Upper Conybere Street'),
('Upper Coombe'),
('Upper Copperas Creek'),
('Upper Coppice'),
('Upper Copse'),
('Upper Coquetdale'),
('Upper Cornaway Lane'),
('Upper Corniche'),
('Upper Cornsland'),
('Upper Cosmeston Farm'),
('Upper Coston'),
('Upper Cotton'),
('Upper Cound'),
('Upper Court'),
('Upper Court Road'),
('Upper Court Terrace'),
('Upper Court Yard'),
('Upper Covert'),
('Upper Cowdens Wood'),
('Upper Cowslow Covert'),
('Upper Coxley'),
('Upper Crabbick Lane'),
('Upper Crabtree'),
('Upper Crackney Lane'),
('Upper Craighill'),
('Upper Craigie'),
('Upper Craigo Street'),
('Upper Craigour'),
('Upper Craigour Way'),
('Upper Craigs'),
('Upper Crale'),
('Upper Cramond Court'),
('Upper Cranbrook Road'),
('Upper Crannel Drove'),
('Upper Crantit Road'),
('Upper Crescent'),
('Upper Crescent Road'),
('Upper Crockford Bottom'),
('Upper Croft'),
('Upper Croft Close'),
('Upper Croft Road'),
('Upper Croft Shaw'),
('Upper Crofts'),
('Upper Crooked Meadow'),
('Upper Cross Lane'),
('Upper Cross Road'),
('Upper Cross Street'),
('Upper Crossgate Road'),
('Upper Crown Street'),
('Upper Cudworth'),
('Upper Culham'),
('Upper Culham Farm'),
('Upper Cullernie Court'),
('Upper Cullernie Place'),
('Upper Culm'),
('Upper Culver Road'),
('Upper Cumberland Walk'),
('Upper Cumberworth'),
('Upper Cumbrae Reservoir'),
('Upper Cut'),
('Upper Cwm-Twrch'),
('Upper Cwmbran'),
('Upper Cwmbran Road'),
('Upper Cwmgwyn'),
('Upper Cwminon'),
('Upper Cyrus Street'),
('Upper Dagnall Street'),
('Upper Dagwells Copse'),
('Upper Daisy Hill'),
('Upper Dalby Wood'),
('Upper Dale Road'),
('Upper Dales'),
('Upper Dalgairn'),
('Upper Dallachy'),
('Upper Damhead Wood'),
('Upper Damside'),
('Upper Dane'),
('Upper Dane Road'),
('Upper Dane Wood'),
('Upper Deacon Road'),
('Upper Deal'),
('Upper Deal Belt'),
('Upper Dean'),
('Upper Dean Head Reservoir'),
('Upper Dean Street'),
('Upper Dean Terrace'),
('Upper Deeside and Donside Aboyne'),
('Upper Delph Drove'),
('Upper Den'),
('Upper Denbigh Road'),
('Upper Denburn'),
('Upper Denby'),
('Upper Denmark Road'),
('Upper Denton'),
('Upper Derwent Valley'),
('Upper Dicconson Street'),
('Upper Dicker'),
('Upper Din Wood'),
('Upper Dinchope'),
('Upper Dingle'),
('Upper Dobbin Close'),
('Upper Dobbin Lane'),
('Upper Dock Street'),
('Upper Dock Walk'),
('Upper Dod'),
('Upper Doe Carr Wood'),
('Upper Dolfor Road'),
('Upper Dormington'),
('Upper Dorrells Wood'),
('Upper Dovercourt'),
('Upper Dowdeswell'),
('Upper Down Copse'),
('Upper Downing Hall'),
('Upper Downing Road'),
('Upper Downs'),
('Upper Downside'),
('Upper Drakeloe Pond'),
('Upper Drive'),
('Upper Drove'),
('Upper Drummond'),
('Upper Duke Street'),
('Upper Dukes Drive'),
('Upper Dullarg Hill'),
('Upper Dumpton Park Road'),
('Upper Dunbar Street'),
('Upper Dunnymans'),
('Upper Dunsforth'),
('Upper Dunsley'),
('Upper Dunstan Road'),
('Upper Dunstead Road'),
('Upper Durrants Copse'),
('Upper Dutmoss Wood'),
('Upper Dwarf Brake'),
('Upper Eashing'),
('Upper East End'),
('Upper East Hayes'),
('Upper East Road'),
('Upper East Street'),
('Upper Eastcliffe Road'),
('Upper Eastern Green'),
('Upper Eastern Green Lane'),
('Upper Eastlands Wood'),
('Upper Easton'),
('Upper Eastville'),
('Upper Eastwick Copse'),
('Upper Eastwood'),
('Upper Eddington'),
('Upper Edge'),
('Upper Edgebold'),
('Upper Edgeborough Road'),
('Upper Edinbane'),
('Upper Edmonton'),
('Upper Edward Street'),
('Upper Egleton'),
('Upper Eldon Street'),
('Upper Elizabeth Street'),
('Upper Elkstone'),
('Upper Ell Gate'),
('Upper Ellastone'),
('Upper Ellistones Court'),
('Upper Elmers End'),
('Upper Elmers End Road'),
('Upper Elms Road'),
('Upper Elsdon Street'),
('Upper End'),
('Upper End Court'),
('Upper End Road'),
('Upper Engamoor'),
('Upper Enham'),
('Upper Ensign'),
('Upper Enton Lake'),
('Upper Esgair Hill'),
('Upper Essex Street'),
('Upper Etloe'),
('Upper Ettingshall'),
('Upper Ettingshall Road'),
('Upper Eythorne'),
('Upper Fagley'),
('Upper Fairfield Road'),
('Upper Fall of Foyers'),
('Upper Fans Lane'),
('Upper Fant'),
('Upper Fant Road'),
('Upper Farburn Road'),
('Upper Farm Close'),
('Upper Farm Down'),
('Upper Farm Meadow'),
('Upper Farm Pool'),
('Upper Farm Road'),
('Upper Farmcote'),
('Upper Farringdon'),
('Upper Fawth Close'),
('Upper Fedw'),
('Upper Fenn Road'),
('Upper Fenwick Grove'),
('Upper Feorlig'),
('Upper Ferndown Green'),
('Upper Ferry Lane'),
('Upper Fforest Way'),
('Upper Field Close'),
('Upper Field House Lane'),
('Upper Field Lane'),
('Upper Field Road'),
('Upper Fifth Street'),
('Upper Fillington Wood'),
('Upper Fir Covert'),
('Upper Fish Pond'),
('Upper Fisher Row'),
('Upper Flaybrick Road'),
('Upper Foel Road'),
('Upper Fold'),
('Upper Folderings'),
('Upper Folly'),
('Upper Forecourt'),
('Upper Forest'),
('Upper Forest Level'),
('Upper Forest Road'),
('Upper Forge'),
('Upper Forster Street'),
('Upper Forty Acres'),
('Upper Fountain Street'),
('Upper Fountain Wood'),
('Upper Four Acres'),
('Upper Fourth Avenue'),
('Upper Fourth Street'),
('Upper Fox Valley'),
('Upper Foxmoor Wood'),
('Upper Framilode'),
('Upper Francis Street'),
('Upper Frederick Street'),
('Upper Free Down'),
('Upper Frenchmoor Copse'),
('Upper Frog Street'),
('Upper Froyle'),
('Upper Froyle Drive'),
('Upper Fullingpits Wood'),
('Upper Furlong'),
('Upper Furlong Street'),
('Upper Furze'),
('Upper Furze Park'),
('Upper Furze Wood'),
('Upper Fyfe Lane'),
('Upper Galdeford'),
('Upper Gambolds Lane'),
('Upper Gardner Street'),
('Upper Garrington'),
('Upper Garston Lane'),
('Upper Garth Gardens'),
('Upper Garth Road'),
('Upper Garth Wood'),
('Upper Gate'),
('Upper Gate Clough'),
('Upper Gate Road'),
('Upper Gate Street'),
('Upper Gatton Wood'),
('Upper Geise Place'),
('Upper Gendros Crescent'),
('Upper Geo Kirk'),
('Upper George Street'),
('Upper George Yard'),
('Upper Gertrude Street'),
('Upper Gills'),
('Upper Gilmore Place'),
('Upper Gilmore Terrace'),
('Upper Gipping'),
('Upper Gipsys Copse'),
('Upper Gladstone Road'),
('Upper Glasshouse Field'),
('Upper Glebe'),
('Upper Gledfield'),
('Upper Glen'),
('Upper Glen Avenue'),
('Upper Glen Dam'),
('Upper Glen Ely Wood'),
('Upper Glen Road'),
('Upper Glenburn Road'),
('Upper Glenburnie Wood'),
('Upper Glendevon Reservoir'),
('Upper Glenfinlas Street'),
('Upper Glenfyne Park'),
('Upper Glenjaan Hill'),
('Upper Gloucester Road'),
('Upper Gloucester Street'),
('Upper Glyn Gwyn Street'),
('Upper Goat Lane'),
('Upper Godney'),
('Upper Goldstone'),
('Upper Golf Links Road'),
('Upper Gordon Road'),
('Upper Gore'),
('Upper Gornal'),
('Upper Gornal and Woodsetton'),
('Upper Gorry Pool'),
('Upper Gough Street'),
('Upper Graham Street'),
('Upper Granco Street'),
('Upper Grange'),
('Upper Grange Avenue'),
('Upper Grange Copse'),
('Upper Grange Crescent'),
('Upper Grange Road'),
('Upper Grassy Pool'),
('Upper Grateley Wood'),
('Upper Gravenhurst'),
('Upper Gray Street'),
('Upper Great Grove'),
('Upper Green'),
('Upper Green Avenue'),
('Upper Green Close'),
('Upper Green Drive'),
('Upper Green East'),
('Upper Green Lane'),
('Upper Green Place'),
('Upper Green Road'),
('Upper Green Street'),
('Upper Green Way'),
('Upper Green West'),
('Upper Greenhill Gardens'),
('Upper Greens'),
('Upper Greenwoods Lane'),
('Upper Greetland'),
('Upper Grenoven Wood'),
('Upper Grenville Copse'),
('Upper Gresham'),
('Upper Griffin Street'),
('Upper Grip Hill'),
('Upper Grosvenor Road'),
('Upper Grosvenor Street'),
('Upper Grotto Road'),
('Upper Ground'),
('Upper Grove'),
('Upper Grove Common'),
('Upper Grove Place'),
('Upper Grove Road'),
('Upper Grove Street'),
('Upper Grove Wood'),
('Upper Guildown Road'),
('Upper Guist'),
('Upper Gungate'),
('Upper Gunnas Close'),
('Upper Gwastad Terrace'),
('Upper Gwestydd Lane'),
('Upper Gwyddon Road'),
('Upper Gwydir Street'),
('Upper Gynor Place'),
('Upper Hackney'),
('Upper Hael Wood'),
('Upper Hagg Road'),
('Upper Haggi Geo'),
('Upper Haigh Street'),
('Upper Hailey Wood'),
('Upper Hale'),
('Upper Hale Road'),
('Upper Hale Wood'),
('Upper Haliford'),
('Upper Hall Close'),
('Upper Hall Fold'),
('Upper Hall Green'),
('Upper Hall Lake'),
('Upper Hall Lane'),
('Upper Hall Park'),
('Upper Hall Road'),
('Upper Hall Street'),
('Upper Hall View'),
('Upper Hallidayhill'),
('Upper Halliford'),
('Upper Halliford Road'),
('Upper Halling'),
('Upper Ham Copse'),
('Upper Ham Green'),
('Upper Ham Road'),
('Upper Hambleton'),
('Upper Hamilton Road'),
('Upper Hammer Lane'),
('Upper Hamnish'),
('Upper Hampton Street'),
('Upper Hanger'),
('Upper Hanover Street'),
('Upper Harbledown'),
('Upper Harbour'),
('Upper Hardres'),
('Upper Hardres Wood'),
('Upper Hardwick'),
('Upper Hardwick Lane'),
('Upper Harestone'),
('Upper Harley Street'),
('Upper Harmans Lane'),
('Upper Harrington Street'),
('Upper Hartfield'),
('Upper Hartshay'),
('Upper Hartwell'),
('Upper Harvel'),
('Upper Hass Loch'),
('Upper Hatfield Place'),
('Upper Hathershelf Wood'),
('Upper Hatton'),
('Upper Haugh'),
('Upper Haugh Shaw'),
('Upper Havelock Street'),
('Upper Haydon Hill'),
('Upper Hayes Close'),
('Upper Hayes Road'),
('Upper Hayesden'),
('Upper Haysden'),
('Upper Haysden Lane'),
('Upper Hayton'),
('Upper Hazel'),
('Upper Head Moss'),
('Upper Headland Park Road'),
('Upper Heamies'),
('Upper Heath Road'),
('Upper Heath Wood'),
('Upper Heathfield Road'),
('Upper Heaton'),
('Upper Heaton Lane'),
('Upper Hedgemead Road'),
('Upper Heights Road'),
('Upper Helena Street'),
('Upper Hellesdon'),
('Upper Helmsley'),
('Upper Helmsley Common'),
('Upper Hengoed'),
('Upper Hergeist'),
('Upper Hergest'),
('Upper Hermitage'),
('Upper Hermosa Road'),
('Upper Heworth'),
('Upper Hey'),
('Upper Heyden'),
('Upper Heyford'),
('Upper Heys Wood'),
('Upper Heyshott'),
('Upper Heywood'),
('Upper Hibbert Lane'),
('Upper Hiendley'),
('Upper High Fields'),
('Upper High Royds'),
('Upper High Street'),
('Upper Higham Lane'),
('Upper Highbridge Coppice'),
('Upper Highfield'),
('Upper Highfields'),
('Upper Highgate Street'),
('Upper Highland Road'),
('Upper Highway'),
('Upper Highwood Copse'),
('Upper Hill'),
('Upper Hill Park'),
('Upper Hill Rise'),
('Upper Hill Street'),
('Upper Hill Way'),
('Upper Hillchurch Street'),
('Upper Hillcrest'),
('Upper Hillfoot Road'),
('Upper Hinton Road'),
('Upper Hird Street'),
('Upper Hirst'),
('Upper Hitch'),
('Upper Hoden Farm'),
('Upper Holland Road'),
('Upper Hollesley Common'),
('Upper Hollingdean Road'),
('Upper Hollis'),
('Upper Hollow'),
('Upper Holloway'),
('Upper Holly Hill Road'),
('Upper Holly Walk'),
('Upper Holme'),
('Upper Holt'),
('Upper Holt Street'),
('Upper Holton'),
('Upper Holway Road'),
('Upper Home Copse'),
('Upper Hook'),
('Upper Hook Road'),
('Upper Hope'),
('Upper Hope Place'),
('Upper Hopgarden Pond'),
('Upper Hopton'),
('Upper Horse'),
('Upper Horse Pool'),
('Upper Horse Rough'),
('Upper Horsebridge'),
('Upper Horsebridge Road'),
('Upper Houndlaw'),
('Upper House'),
('Upper House Copse'),
('Upper House Court'),
('Upper House Fold'),
('Upper House Lane'),
('Upper House Road'),
('Upper House Street'),
('Upper House Wood'),
('Upper Houses'),
('Upper Howick Street'),
('Upper Howsell'),
('Upper Howsell Road'),
('Upper Hoyland'),
('Upper Hoyland Road'),
('Upper Hoyle Ing'),
('Upper Hucksteep Wood'),
('Upper Hulme'),
('Upper Humblescough Wood'),
('Upper Hundreds Way'),
('Upper Huntbach Street'),
('Upper Huntlywood'),
('Upper Hunton Hill'),
('Upper Hurst Coppice'),
('Upper Huskisson Street'),
('Upper Hyde'),
('Upper Hyde Farm Lane'),
('Upper Hyde Lane'),
('Upper Icknield Way'),
('Upper Ifield'),
('Upper Ifold'),
('Upper Ifold Wood'),
('Upper Inglesham'),
('Upper Inhams Copse'),
('Upper Inkerman Street'),
('Upper Isbury'),
('Upper James Street'),
('Upper John Street'),
('Upper Keith'),
('Upper Kempley Wood'),
('Upper Kent'),
('Upper Kent Road'),
('Upper Kenyon Street'),
('Upper Kessock Street'),
('Upper Kilchattan'),
('Upper Kilcott'),
('Upper Killay'),
('Upper Kiln Lane'),
('Upper Kincraig Street'),
('Upper King Street'),
('Upper Kings Avenue'),
('Upper Kings Drive'),
('Upper Kings Head Road'),
('Upper Kingston'),
('Upper Kingston Lane'),
('Upper Kinneddar'),
('Upper Kinneddar Gardens'),
('Upper Kinsham'),
('Upper Kipping Close'),
('Upper Kirby Street'),
('Upper Kirkgate'),
('Upper Kitching Spring'),
('Upper Kites Wood'),
('Upper Kitesnest Lane'),
('Upper Knapp Wood'),
('Upper Knarr Fen'),
('Upper Knockando'),
('Upper Knockbain Road'),
('Upper Knockbain Wood'),
('Upper Knole'),
('Upper Knollys Terrace Lane'),
('Upper Knowe'),
('Upper Knowle'),
('Upper Ladyes Hills'),
('Upper Ladypark Wood'),
('Upper Lairochs Wood'),
('Upper Lake'),
('Upper Lamborough Lane'),
('Upper Lambourn'),
('Upper Lambourn Road'),
('Upper Lambricks'),
('Upper Lambridge Street'),
('Upper Lamphey Road'),
('Upper Landslip'),
('Upper Landywood'),
('Upper Landywood Lane'),
('Upper Lane'),
('Upper Langford'),
('Upper Langridge'),
('Upper Langsky Belt'),
('Upper Langwith'),
('Upper Lanham Copse'),
('Upper Lanham Lane'),
('Upper Lansdown Mews'),
('Upper Largo'),
('Upper Lattimore Road'),
('Upper Laundimer Wood'),
('Upper Lawn'),
('Upper Lawns'),
('Upper Layham'),
('Upper Lays Wood'),
('Upper Lazy Bushes'),
('Upper Leazes'),
('Upper Lee Wood'),
('Upper Lees Drive'),
('Upper Lees Road'),
('Upper Leigh'),
('Upper Lewes Road'),
('Upper Ley'),
('Upper Ley Court'),
('Upper Ley Dell'),
('Upper Lichfield Street'),
('Upper Lightwood'),
('Upper Linacre Reservoir'),
('Upper Lindum Street'),
('Upper Linhay'),
('Upper Linney'),
('Upper Littlegill Wood'),
('Upper Littleton'),
('Upper Llancayo Wood'),
('Upper Llandwrog'),
('Upper Llanelwedd Wood'),
('Upper Lliedi Reservoir'),
('Upper Lliw Reservoir'),
('Upper Lloyd Street'),
('Upper Loads'),
('Upper Loan Park'),
('Upper Loaning'),
('Upper Loch'),
('Upper Loch of Brouster'),
('Upper Loch of Setter'),
('Upper Loch Torridon'),
('Upper Lochan Sligeanach'),
('Upper Lochton'),
('Upper Lochton East'),
('Upper Lochton Wood'),
('Upper Lodge Lane'),
('Upper Lodge Road'),
('Upper Lodge Way'),
('Upper Lodge Wood'),
('Upper Lombard Street'),
('Upper Long Leys Road'),
('Upper Longdon'),
('Upper Longlands'),
('Upper Longwood'),
('Upper Lord Street'),
('Upper Loughor'),
('Upper Ludstone'),
('Upper Ludwell Shaw'),
('Upper Lum Close'),
('Upper Lumb Lane'),
('Upper Lune Street'),
('Upper Lune Valley'),
('Upper Lunns Close'),
('Upper Luton Road'),
('Upper Lybster'),
('Upper Lydbrook'),
('Upper Lydbrooke'),
('Upper Lyde'),
('Upper Lye'),
('Upper Lynch Road'),
('Upper Lynmore Wood'),
('Upper Maenen'),
('Upper Maes Coed'),
('Upper Maes-coed'),
('Upper Maescoed'),
('Upper Mains Wood'),
('Upper Maisondieu'),
('Upper Mall'),
('Upper Malthouse Hill'),
('Upper Mann Street'),
('Upper Manor Road'),
('Upper Mansbrook Wood'),
('Upper Manse Pool'),
('Upper Mantle Close'),
('Upper Marehay Road'),
('Upper Market Road'),
('Upper Market Square'),
('Upper Market Street'),
('Upper Marlborough Road'),
('Upper Marlbrook'),
('Upper Marsh'),
('Upper Marsh Covert'),
('Upper Marsh Lane'),
('Upper Marsh Road'),
('Upper Marshall Street'),
('Upper Marston'),
('Upper Martin Green'),
('Upper Martridge Wood'),
('Upper Mary Street'),
('Upper Mastrick Way'),
('Upper Maudlin Street'),
('Upper Maund Common'),
('Upper Mayfield'),
('Upper Maylins'),
('Upper Mayne'),
('Upper Maythorn Lane'),
('Upper Maze Hill'),
('Upper Mead'),
('Upper Mead Close'),
('Upper Meadow'),
('Upper Meadow Copse'),
('Upper Meadow Road'),
('Upper Meadow Spring'),
('Upper Meadow Wood'),
('Upper Meadows'),
('Upper Mealines'),
('Upper Melton Terrace'),
('Upper Meon Valley'),
('Upper Mersey Road'),
('Upper Mersey Street'),
('Upper Mexborough Road'),
('Upper Midhope'),
('Upper Midway'),
('Upper Milcote'),
('Upper Miless Rough'),
('Upper Mill'),
('Upper Mill Field'),
('Upper Mill Green'),
('Upper Mill Lane'),
('Upper Mill Pond'),
('Upper Mill Road'),
('Upper Mill Street'),
('Upper Millergate'),
('Upper Millfield Wood'),
('Upper Millgate'),
('Upper Millhill Street'),
('Upper Millichope'),
('Upper Mills View'),
('Upper Milton'),
('Upper Minety'),
('Upper Misden Clough'),
('Upper Mitton'),
('Upper Mod'),
('Upper Monsall Street'),
('Upper Montagu Street'),
('Upper Monynut Forest'),
('Upper Moor'),
('Upper Moor Road'),
('Upper Moor Side'),
('Upper Moor Street'),
('Upper Moorfield Road'),
('Upper Moorgreen Road'),
('Upper Moors'),
('Upper Moors Gully'),
('Upper Moors Road'),
('Upper Morax Wood'),
('Upper Morgay Wood'),
('Upper Morin Road'),
('Upper Morton'),
('Upper Moss Cleuch'),
('Upper Moss Lane'),
('Upper Moss of Leonach'),
('Upper Mosscar Street'),
('Upper Mossley'),
('Upper Mount'),
('Upper Mount Street'),
('Upper Mounts'),
('Upper Mulgrave Road'),
('Upper Mullins Lane'),
('Upper Mwldan'),
('Upper Myrtle Hill'),
('Upper Napier Street'),
('Upper Nash'),
('Upper Navigation Street'),
('Upper Neapaback'),
('Upper Neatham Mill Lane'),
('Upper Neck Shaw'),
('Upper Nellington'),
('Upper Nelson Street'),
('Upper Netchwood'),
('Upper Neuadd Reservoir'),
('Upper New Copse'),
('Upper New Pool'),
('Upper New Road'),
('Upper New Street'),
('Upper New Walk'),
('Upper New Wood'),
('Upper Newbold'),
('Upper Newbold Close'),
('Upper Newborough Street'),
('Upper Newdown Copse'),
('Upper Newington'),
('Upper Newmarket Street'),
('Upper Newton Wood'),
('Upper Nidd Street'),
('Upper Nisbet Moor'),
('Upper Noads Copse'),
('Upper Nobut'),
('Upper Norfolk Street'),
('Upper Normacot Road'),
('Upper North Dean'),
('Upper North Field'),
('Upper North Pond'),
('Upper North Road'),
('Upper North Street'),
('Upper Northam Close'),
('Upper Northam Drive'),
('Upper Northam Road'),
('Upper Northgate Street'),
('Upper Norwich Road'),
('Upper Norwood'),
('Upper Norwood Street'),
('Upper Nursery'),
('Upper Nut Hurst'),
('Upper Oak Street'),
('Upper Oakcuts Copse'),
('Upper Oakley'),
('Upper Oaks Court'),
('Upper Ochrwyth'),
('Upper Oddington'),
('Upper Oddington Ashes'),
('Upper Ogden Reservoir'),
('Upper Old Bargains Wood'),
('Upper Old Park Lane'),
('Upper Old Park Wood'),
('Upper Old Street'),
('Upper Oldfield Copse'),
('Upper Oldfield Park'),
('Upper Oliver Dod'),
('Upper Olland Street'),
('Upper Orchard Street'),
('Upper Orwell Street'),
('Upper Owlers Wood'),
('Upper Ox Close Wood'),
('Upper Ox Hill'),
('Upper Oxford Street'),
('Upper Packington Road'),
('Upper Paddock Road'),
('Upper Padley'),
('Upper Parish Ghyll Lane'),
('Upper Park'),
('Upper Park Avenue'),
('Upper Park Clump'),
('Upper Park Gate'),
('Upper Park Place'),
('Upper Park Road'),
('Upper Park Street'),
('Upper Park Terrace'),
('Upper Park Wood'),
('Upper Parkers Hole'),
('Upper Parkstone'),
('Upper Parliament Street'),
('Upper Parrotts Copse'),
('Upper Parting'),
('Upper Passmonds Grove'),
('Upper Pasture'),
('Upper Pattiesbank Wood'),
('Upper Paul Street'),
('Upper Pavenhill'),
('Upper Pearson Street'),
('Upper Peel Street'),
('Upper Pemberton'),
('Upper Penman Street'),
('Upper Pennington'),
('Upper Pennington Common'),
('Upper Penns Road'),
('Upper Penshill Coppice'),
('Upper Pentre-Bach'),
('Upper Perlieu Wood'),
('Upper Perry Hill'),
('Upper Pertwood Bushes'),
('Upper Phillimore Gardens'),
('Upper Piccadilly'),
('Upper Piece'),
('Upper Pillory Down'),
('Upper Pilsley'),
('Upper Pines'),
('Upper Pinewood Road'),
('Upper Pitching'),
('Upper Pitt Street'),
('Upper Pleasley'),
('Upper Polecats'),
('Upper Polecats Copse'),
('Upper Pollicott'),
('Upper Polmear Parc'),
('Upper Pond'),
('Upper Pond Street'),
('Upper Ponds'),
('Upper Pool'),
('Upper Pool Coppice'),
('Upper Poole Road'),
('Upper Popes Wood'),
('Upper Poppleton'),
('Upper Port Wood'),
('Upper Portland Street'),
('Upper Potley'),
('Upper Power Street'),
('Upper Pownall Street'),
('Upper Price Street'),
('Upper Princes Road'),
('Upper Princess Street'),
('Upper Priory Street'),
('Upper Profit'),
('Upper Promenade'),
('Upper Pulley'),
('Upper Quarry Road'),
('Upper Quay Street'),
('Upper Queen Street'),
('Upper Queens Road'),
('Upper Quell Copse'),
('Upper Quinton'),
('Upper Quoy'),
('Upper Raby Road'),
('Upper Race'),
('Upper Radford'),
('Upper Radnor Wood'),
('Upper Raglan Street'),
('Upper Rainham Road'),
('Upper Rake'),
('Upper Randell Copse'),
('Upper Rapeland Wood'),
('Upper Rashy Cleuch'),
('Upper Ratley'),
('Upper Ratton Drive'),
('Upper Ravens Close Wood'),
('Upper Rawcliffe-with-Tarnacre'),
('Upper Red Cross Road'),
('Upper Red Hill'),
('Upper Redbrook'),
('Upper Reddale Clough'),
('Upper Redlands Road'),
('Upper Regent Street'),
('Upper Regents Park'),
('Upper Reservoir'),
('Upper Reynolds Wood'),
('Upper Rhynd'),
('Upper Rice Lane'),
('Upper Richardson'),
('Upper Richmond Road'),
('Upper Richmond Road West'),
('Upper Ride'),
('Upper Ridge Green'),
('Upper Riding'),
('Upper Ridings'),
('Upper Riochan'),
('Upper Rissington'),
('Upper Rithe'),
('Upper River Bank'),
('Upper River Row'),
('Upper Rivington Reservoir'),
('Upper Road'),
('Upper Road Pool'),
('Upper Roadstead'),
('Upper Robinson Street'),
('Upper Rochford'),
('Upper Rock Gardens'),
('Upper Rodge Wood'),
('Upper Rodley Road'),
('Upper Rodmersham'),
('Upper Roedale'),
('Upper Roman Road'),
('Upper Rose Hill'),
('Upper Rose Lane'),
('Upper Rosemary Hill'),
('Upper Rough'),
('Upper Rough Wood'),
('Upper Roughs'),
('Upper Rouse Copse'),
('Upper Row'),
('Upper Rowe Court'),
('Upper Royal Lane'),
('Upper Rudimoor Coppice'),
('Upper Rushall Street'),
('Upper Rushton Road'),
('Upper Rusko Wood'),
('Upper Russell Street'),
('Upper Ruxley'),
('Upper Rye Close'),
('Upper Ryle'),
('Upper Sackville Street'),
('Upper Sales'),
('Upper Saline Wood'),
('Upper Salisbury Street'),
('Upper Salters'),
('Upper Samshill'),
('Upper Sanday'),
('Upper Sandhurst Road'),
('Upper Sapey'),
('Upper Sawleywood'),
('Upper Saxon Street'),
('Upper Saxondale'),
('Upper Scar'),
('Upper Sea Road'),
('Upper Seagry'),
('Upper Seal Clough'),
('Upper Sean'),
('Upper Second Avenue'),
('Upper Second Street'),
('Upper Selsdon Road'),
('Upper Selves Wood'),
('Upper Settle'),
('Upper Seven Acres'),
('Upper Seymour Street'),
('Upper Shaftesbury Avenue'),
('Upper Shaw'),
('Upper Sheepwash Copse'),
('Upper Sheffield Road'),
('Upper Shelley Copse'),
('Upper Shelton'),
('Upper Shelton Road'),
('Upper Shenmore'),
('Upper Sherborne Road'),
('Upper Sheridan Road'),
('Upper Sheringham'),
('Upper Sheringham Common'),
('Upper Sherwood Road'),
('Upper Shirley'),
('Upper Shirley Avenue'),
('Upper Shirley High'),
('Upper Shirley Road'),
('Upper Shooters Wood'),
('Upper Shoreham Road'),
('Upper Short Street'),
('Upper Shot'),
('Upper Shott'),
('Upper Shrubbery'),
('Upper Shuckburgh'),
('Upper Siddington'),
('Upper Skelmorlie'),
('Upper Slackbuie'),
('Upper Slackstead'),
('Upper Slades'),
('Upper Slatepits'),
('Upper Slaughter'),
('Upper Sluice Wood'),
('Upper Small Clough'),
('Upper Smearing Cleuch'),
('Upper Smithers Copse'),
('Upper Smollett Street'),
('Upper Snailsden Moss'),
('Upper Sneyd Road'),
('Upper Solar Farm'),
('Upper Soldridge Road'),
('Upper Soles Wood'),
('Upper Solva'),
('Upper Soudley'),
('Upper Sound'),
('Upper Soundwell'),
('Upper Sourfold Glen'),
('Upper South Rill'),
('Upper South Road'),
('Upper South Street'),
('Upper South View'),
('Upper Speighthill Wood'),
('Upper Spinney'),
('Upper Spon Street'),
('Upper Spond'),
('Upper Spring'),
('Upper Spring Lane'),
('Upper Springfield'),
('Upper Springfield Road'),
('Upper Square'),
('Upper St Albans Road'),
('Upper St Anns Road'),
('Upper St Giles Street'),
('Upper St Helens Road'),
('Upper St Jamess Street'),
('Upper St John Street'),
('Upper St Johns Road'),
('Upper St Martins Lane'),
('Upper St Marys Road'),
('Upper St Marys Street'),
('Upper St Michaels Grove'),
('Upper St Michaels Road'),
('Upper St Pauls Terrace'),
('Upper St Stephen Street'),
('Upper Stafford Avenue'),
('Upper Staithe Road'),
('Upper Stanford Road'),
('Upper Stanhope Street'),
('Upper Stanton'),
('Upper Stanton Drew'),
('Upper Stapens Copse'),
('Upper Staple Hills Wood'),
('Upper Staploe'),
('Upper Star Post Ride'),
('Upper Station Road'),
('Upper Steeping'),
('Upper Stephens'),
('Upper Stockriding Wood'),
('Upper Stoke'),
('Upper Stondon'),
('Upper Stone Close'),
('Upper Stone Drive'),
('Upper Stone Street'),
('Upper Stone Wood'),
('Upper Stoneborough Lane'),
('Upper Stoneham'),
('Upper Stonehayes'),
('Upper Stoneymollan Road'),
('Upper Stony Cleuch'),
('Upper Stonyfield'),
('Upper Stonyhills Wood'),
('Upper Stowe'),
('Upper Stowfield Road'),
('Upper Strand'),
('Upper Strand Street'),
('Upper Stratton'),
('Upper Streat Green'),
('Upper Street'),
('Upper Street Lane'),
('Upper Strensham'),
('Upper Strinesdale Reservoir'),
('Upper Strode'),
('Upper Stroquhan Hill'),
('Upper Stroud Close'),
('Upper Studdings Shaw'),
('Upper Studley'),
('Upper Stumble Wood'),
('Upper Sude Hill Road'),
('Upper Sudeley Street'),
('Upper Sugworth Copse'),
('Upper Sunbury Road'),
('Upper Sundon'),
('Upper Sunny Bank Mews'),
('Upper Sunt Copse'),
('Upper Sutherland Crescent'),
('Upper Sutherland Road'),
('Upper Sutherland Street'),
('Upper Sutton Lane'),
('Upper Sutton Street'),
('Upper Swaines'),
('Upper Swainswick'),
('Upper Swallow Wood'),
('Upper Swanmore'),
('Upper Swell'),
('Upper Swineshaw Reservoir'),
('Upper Swinhoe Lake'),
('Upper Swinton Wood'),
('Upper Sydenham'),
('Upper Sydney Street'),
('Upper Tachbrook Street'),
('Upper Tachore Pot'),
('Upper Tadmarton'),
('Upper Taff Street'),
('Upper Tail'),
('Upper Tal-y-coed Wood'),
('Upper Talley Lake'),
('Upper Tamar Lake'),
('Upper Tankersley'),
('Upper Tarnberry'),
('Upper Taylors Wood'),
('Upper Tean'),
('Upper Teddington Road'),
('Upper Tennyson Road'),
('Upper Terrace'),
('Upper Terrace Road'),
('Upper Thames Street'),
('Upper Thames Way'),
('Upper Thicket Copse'),
('Upper Third Avenue'),
('Upper Third Street'),
('Upper Thirstin'),
('Upper Thomas Street'),
('Upper Thornton'),
('Upper Thrift Street'),
('Upper Throat Pool'),
('Upper Thurnham'),
('Upper Tichborne Street'),
('Upper Tilehouse Street'),
('Upper Tockington Road'),
('Upper Tokes Wood'),
('Upper Tollington Park'),
('Upper Tomvaich Wood'),
('Upper Tone'),
('Upper Toothill Road'),
('Upper Tooting'),
('Upper Tooting Park'),
('Upper Tooting Road'),
('Upper Tor'),
('Upper Tormsdale Pool'),
('Upper Torrs'),
('Upper Torwoodhill Road'),
('Upper Tote'),
('Upper Tott Shaw'),
('Upper Town'),
('Upper Town Lane'),
('Upper Town Road'),
('Upper Town Street'),
('Upper Trawscoed Wood'),
('Upper Tredrea'),
('Upper Trelyn'),
('Upper Tribute Avenue'),
('Upper Tring Park'),
('Upper Trinity Road'),
('Upper Trinity Street'),
('Upper Trosnant Street'),
('Upper Troublesome Reach'),
('Upper Tullich'),
('Upper Tulse Hill'),
('Upper Tumbril Lane'),
('Upper Tyndrum'),
('Upper Tynings'),
('Upper Tysoe'),
('Upper Tything'),
('Upper Under Hill'),
('Upper Union Street'),
('Upper Union Terrace'),
('Upper Uphall'),
('Upper Upham'),
('Upper Upnor'),
('Upper Valley Road'),
('Upper Vann Lane'),
('Upper Vaughan Street'),
('Upper Vauxhall'),
('Upper Vernon Road'),
('Upper Verran Road'),
('Upper Vert Wood'),
('Upper Viaduct Terrace'),
('Upper Vicarage Road'),
('Upper Village Road'),
('Upper Villiers Street'),
('Upper Vobster'),
('Upper Walk'),
('Upper Wallemoore Covert'),
('Upper Walmer'),
('Upper Walthamstow'),
('Upper Walthamstow Road'),
('Upper Wanborough'),
('Upper Wardington'),
('Upper Wardown'),
('Upper Warehams Wood'),
('Upper Wargrave'),
('Upper Warlingham'),
('Upper Warren Avenue'),
('Upper Warren Wood'),
('Upper Warrengate'),
('Upper Warwick Street'),
('Upper Washer Lane'),
('Upper Washwell'),
('Upper Waston Road'),
('Upper Watchingwell'),
('Upper Water Street'),
('Upper Waterhay'),
('Upper Waun Street'),
('Upper Waxhall Grove'),
('Upper Way'),
('Upper Weald'),
('Upper Weedon'),
('Upper Well Close'),
('Upper Well Street'),
('Upper Welland'),
('Upper Welland Road'),
('Upper Wellheads'),
('Upper Wellhouse'),
('Upper Wellhouse Road'),
('Upper Wellingham'),
('Upper Wellington'),
('Upper Wellington Road'),
('Upper Wellington Street'),
('Upper Wells Street'),
('Upper Welson'),
('Upper Wensum'),
('Upper Wepham Wood'),
('Upper West Drive'),
('Upper West Grove'),
('Upper West Lane'),
('Upper West Street'),
('Upper West Terrace'),
('Upper West Wood'),
('Upper Westby Street'),
('Upper Westhill Road'),
('Upper Westholme'),
('Upper Westley'),
('Upper Westlock Avenue'),
('Upper Weston'),
('Upper Weston Lane'),
('Upper Weston Wood'),
('Upper Westwood'),
('Upper Wetmoor'),
('Upper Weybourne Lane'),
('Upper Weybread'),
('Upper Wharf'),
('Upper Wharf Street'),
('Upper Wharfedale'),
('Upper Whatcombe'),
('Upper Whiphill Copse'),
('Upper Whiston'),
('Upper Whiston Close'),
('Upper Whiston Lane'),
('Upper Whitelea Green'),
('Upper Whiteside Moor'),
('Upper Whitley Edge'),
('Upper Wick'),
('Upper Wick Lane'),
('Upper Wickham Lane'),
('Upper Widhill Copse'),
('Upper Wield'),
('Upper Wield Drive'),
('Upper Wilcove'),
('Upper Wilderness'),
('Upper William Street'),
('Upper Willington'),
('Upper Willow Beds'),
('Upper Willow Hall'),
('Upper Wilton Street'),
('Upper Wimpole Street'),
('Upper Winchendon'),
('Upper Windleden Reservoir'),
('Upper Windsor Street'),
('Upper Winfield Avenue'),
('Upper Wish Hill'),
('Upper Witton'),
('Upper Woburn Place'),
('Upper Wolvercote'),
('Upper Wolverton'),
('Upper Wolves Copse'),
('Upper Womans Way Pond'),
('Upper Wood'),
('Upper Wood Lane'),
('Upper Wood Street'),
('Upper Woodcote Green'),
('Upper Woodcote Road'),
('Upper Woodcote Village'),
('Upper Woodcott Down'),
('Upper Woodford'),
('Upper Woodhouse'),
('Upper Woodland Street'),
('Upper Woodlands'),
('Upper Woodlands Road'),
('Upper Woodside Road'),
('Upper Woodview Place'),
('Upper Woolgrove Wood'),
('Upper Woolhampton'),
('Upper Woollaston Covert'),
('Upper Wootton'),
('Upper Wortley'),
('Upper Wortley Road'),
('Upper Wraxall'),
('Upper Wriggle Brook'),
('Upper Wrigglebrook Lane'),
('Upper Writhlington'),
('Upper Wyche'),
('Upper Wyke'),
('Upper Yarborough Road'),
('Upper Yeld Road'),
('Upper Yeo'),
('Upper York Street'),
('Upper Youlbury Heath'),
('Upper Zoar Street'),
('Upperbarn Copse'),
('Upperbarn Wood'),
('Upperboat Place'),
('Upperboat Road'),
('Upperbreach Belt'),
('Upperbrook Way'),
('Upperby'),
('Upperby Court'),
('Upperby Road'),
('Upperby Way'),
('Uppercliff Close'),
('Uppercliff Drive'),
('Uppercommon Lane'),
('Uppercraft Fleet'),
('Uppercroft'),
('Upperdale'),
('Upperdale Park'),
('Upperfield'),
('Upperfield Close'),
('Upperfield Drive'),
('Upperfield Grove'),
('Upperfield Road'),
('Upperfield Way'),
('Upperfields'),
('Upperford Copse'),
('Uppergate'),
('Uppergate Wood'),
('Upperhead Row'),
('Upperhouse Wood'),
('Upperkirk Gate'),
('Upperkirkgate'),
('Upperlands Copse'),
('Uppermill'),
('Uppermill Drive'),
('Uppermoor'),
('Uppermoor Close'),
('Uppermoss Wood'),
('Uppermost Clough'),
('Upperstaff Wood'),
('Upperstone Close'),
('Upperthong'),
('Upperthong Lane'),
('Upperthorpe'),
('Upperthorpe Glen'),
('Upperthorpe Hill'),
('Upperthorpe Road'),
('Upperthorpe Villas'),
('Upperton'),
('Upperton Common'),
('Upperton Gardens'),
('Upperton Grove'),
('Upperton Lane'),
('Upperton Rise'),
('Upperton Road'),
('Upperton Road East'),
('Upperton Road West'),
('Upperton Wood'),
('Uppertown'),
('Uppertown Lane'),
('Upperup'),
('Upperway Furlong'),
('Upperwood'),
('Upperwood Close'),
('Upperwood Farm'),
('Upperwood Road'),
('Upphall Lane'),
('Uppincott'),
('Uppincott Lane'),
('Upping Copse'),
('Uppingham'),
('Uppingham Avenue'),
('Uppingham Close'),
('Uppingham Crescent'),
('Uppingham Drive'),
('Uppingham Gardens'),
('Uppingham Road'),
('Uppingham Street'),
('Uppington'),
('Uppington Avenue'),
('Uppington Close'),
('Uppington Lane'),
('Uppleby'),
('Uppleby Road'),
('Upright Cliff'),
('Upron Field Close'),
('Ups and Downs'),
('Upsall'),
('Upsall Drive'),
('Upsall Grove'),
('Upsall Lane'),
('Upsall Moor'),
('Upsall Park'),
('Upsall Road'),
('Upsdell Avenue'),
('Upsettlington'),
('Upsher Green'),
('Upsheres'),
('Upshire'),
('Upshire Gardens'),
('Upshire Road'),
('Upshot Lane'),
('Upshot Wood'),
('Upsland'),
('Upsland Hill'),
('Upsons Way'),
('Upstall Street'),
('Upstreet'),
('Upthorpe'),
('Upthorpe Drive'),
('Upthorpe Lane'),
('Upthorpe Road'),
('Upton'),
('Upton and Coppingford'),
('Upton and Hanley'),
('Upton Avenue'),
('Upton Barn'),
('Upton Beacon'),
('Upton Bishop'),
('Upton Bridle Path'),
('Upton Broad'),
('Upton Brooks'),
('Upton By-Pass'),
('Upton Carr'),
('Upton Cheyney'),
('Upton Close'),
('Upton Common'),
('Upton Coombe'),
('Upton Court'),
('Upton Court Road'),
('Upton Cow Down'),
('Upton Crescent'),
('Upton Cressett'),
('Upton Crews'),
('Upton Cross'),
('Upton Day'),
('Upton Dene'),
('Upton Down'),
('Upton Drive'),
('Upton Dyke'),
('Upton End'),
('Upton End Road'),
('Upton Gardens'),
('Upton Glen'),
('Upton Grange'),
('Upton Green'),
('Upton Grey'),
('Upton Grey and The Candovers'),
('Upton Grey Close'),
('Upton Grey Road'),
('Upton Grove'),
('Upton Hall'),
('Upton Hall Lane'),
('Upton Heath'),
('Upton Heath Estate'),
('Upton Hellions'),
('Upton Hill'),
('Upton Hill Road'),
('Upton'),
('Upton Lake'),
('Upton Lane'),
('Upton Lane Site'),
('Upton Lea'),
('Upton Lodge Close'),
('Upton Lovell'),
('Upton Magna'),
('Upton Manor Park'),
('Upton Manor Road'),
('Upton Marshes'),
('Upton Meadow'),
('Upton Meadows'),
('Upton Mount'),
('Upton Noble'),
('Upton Park'),
('Upton Park Drive'),
('Upton Park Road'),
('Upton Place'),
('Upton Pyne'),
('Upton Pyne Hill'),
('Upton Quarry'),
('Upton Road'),
('Upton Rocks'),
('Upton Rocks Avenue'),
('Upton Rocks Mews'),
('Upton Scudamore'),
('Upton Snodsbury'),
('Upton Snodsbury Road'),
('Upton St Leonards'),
('Upton St. Leonards'),
('Upton Stones'),
('Upton Street'),
('Upton Terrace'),
('Upton Towans'),
('Upton upon Severn'),
('Upton Valley Way East'),
('Upton Valley Way North'),
('Upton Walk'),
('Upton Warren'),
('Upton Way'),
('Upton with Fishley'),
('Upton Wood'),
('Upton Wood Road'),
('Upton-by-Chester'),
('Upton-upon-Severn'),
('Uptons'),
('Uptons Garden'),
('Uptons Way'),
('Upwaltham'),
('Upwaltham Hill'),
('Upware'),
('Upware Road'),
('Upway'),
('Upway Road'),
('Upway Street'),
('Upways Close'),
('Upwell'),
('Upwell and Delph'),
('Upwell Fen'),
('Upwell Hill'),
('Upwell Lane'),
('Upwell Road'),
('Upwell Street'),
('Upwey'),
('Upwey and Broadwey'),
('Upwey Avenue'),
('Upwick Green'),
('Upwick Mews'),
('Upwick Road'),
('Upwick Wood'),
('Upwood'),
('Upwood Airfield'),
('Upwood and the Raveleys'),
('Upwood Close'),
('Upwood Drive'),
('Upwood Lane'),
('Upwood Road'),
('Upwoods Road'),
('Ura'),
('Ura Firth'),
('Ura Geo'),
('Ura Stack'),
('Urabug'),
('Uradale'),
('Urafirth'),
('Uragaig'),
('Uraghag'),
('Uralite Halt'),
('Uranus Road'),
('Urban Avenue'),
('Urban Drive'),
('Urban Gardens'),
('Urban Hive'),
('Urban Mews'),
('Urban Road'),
('Urban Street'),
('Urban Terrace'),
('Urban View'),
('Urban Way'),
('Urch Close'),
('Urchair Fhada'),
('Urchany and Farley Forest'),
('Urchar Wood'),
('Urchfont'),
('Urchfont and The Cannings'),
('Urchfont Down'),
('Urchfont Gorse'),
('Urchfont Hill'),
('Urchin Clough'),
('Urchin Hill'),
('Urchin Wood'),
('Urchinwood Lane'),
('Urd'),
('Urda Stack'),
('Urdimarsh'),
('Ure Bank'),
('Ure Bank Maltings'),
('Ure Bank Terrace'),
('Ure Bank Top'),
('Ure Court'),
('Ure Crescent'),
('Ure Force'),
('Ure Gardens'),
('Ure Grove'),
('Ure Place'),
('Ure Street'),
('Ure Water'),
('Uredale Place'),
('Urford Close'),
('Urfords Drive'),
('Urgashay'),
('Urgha'),
('Uridge Crescent'),
('Uridge Road'),
('Urie Crescent'),
('Urie Head'),
('Urie Lingey'),
('Urie Loch'),
('Urie Ness'),
('Urievale Road'),
('Urinbeg'),
('Urishay Common'),
('Urishay Court'),
('Urishay Villa'),
('Urit Hill'),
('Urlar Road'),
('Urlay Grove'),
('Urlay Nook'),
('Urlay Nook Road'),
('Urlwin Street'),
('Urlwin Walk'),
('Urmond Road'),
('Urmson Road'),
('Urmson Street'),
('Urmston'),
('Urmston Avenue'),
('Urmston Drive'),
('Urmston House'),
('Urmston Lane'),
('Urmston Park'),
('Urmston Place'),
('Urmston Street'),
('Urnachean'),
('Urnfield'),
('Urnfield Close'),
('Urpeth'),
('Urpeth Common'),
('Urpeth Wood'),
('Urquart Street'),
('Urquhart'),
('Urquhart and Glenmoriston'),
('Urquhart and Logie Wester'),
('Urquhart Bay'),
('Urquhart Close'),
('Urquhart Court'),
('Urquhart Crescent'),
('Urquhart Cut'),
('Urquhart Drive'),
('Urquhart Gardens'),
('Urquhart Green'),
('Urquhart Grove'),
('Urquhart Lane'),
('Urquhart Place'),
('Urquhart Road'),
('Urquhart Street'),
('Urquhart Terrace'),
('Urquhart Wynd'),
('Urquharts Brae'),
('Urr'),
('Urr Road'),
('Urr Terrace'),
('Urr Water'),
('Urra'),
('Urra Moor'),
('Urra Moor Close'),
('Urra Taing'),
('Urrall Fell'),
('Urrall Loch'),
('Urray'),
('Urrdale Road'),
('Ursa Major Road'),
('Ursa Way'),
('Ursula Avenue'),
('Ursula Avenue North'),
('Ursula Gould Way'),
('Ursula Mews'),
('Ursula Square'),
('Ursula Street'),
('Ursula Taylor Walk'),
('Ursuline Convent'),
('Ursuline Drive'),
('Ursuline Way'),
('Urswick'),
('Urswick Close'),
('Urswick Court'),
('Urswick Gardens'),
('Urswick Green'),
('Urswick Road'),
('Urswick Tarn'),
('Urvaig'),
('Urwick Road'),
('Urwin Gardens'),
('Urwin Lane'),
('Urwin Street'),
('Ury Dale'),
('Ury Meadows'),
('Uryside Drive'),
('Usan'),
('Usan Ness'),
('Usan Road'),
('Usborne Close'),
('Usborne Mews'),
('Usbourne Way'),
('Ushat Geo'),
('Ushat Head'),
('Ushaw Moor'),
('Ushaw Road'),
('Usher Avenue'),
('Usher Close'),
('Usher Drive'),
('Usher Gardens'),
('Usher Green'),
('Usher Lane'),
('Usher Park Road'),
('Usher Road'),
('Usher Street'),
('Usher Wood'),
('Ushercombe View'),
('Ushercoombe Copse'),
('Ushers Meadow'),
('Ushers Wynd'),
('Usherwood Close'),
('Usk'),
('Usk Avenue'),
('Usk'),
('Usk Close'),
('Usk Court'),
('Usk Drive'),
('Usk Patch'),
('Usk Place'),
('Usk Reservoir'),
('Usk Road'),
('Usk Street'),
('Usk Vale Close'),
('Usk Vale Court'),
('Usk Vale Drive'),
('Usk Way'),
('Usker Close'),
('Uskers Wood'),
('Uskie Geo'),
('Uskley Court'),
('Uskmouth'),
('Usmere Road'),
('Usmore Place'),
('Usprig'),
('Usprig Meadhoin'),
('Usselby'),
('Usselby Moor'),
('Ussie'),
('Ussie Wood'),
('Ussleby Close'),
('Usta Ness'),
('Usterdale Road'),
('Ustick Moss'),
('Usticke Lane'),
('Usulwall Close'),
('Usway Close'),
('Usway Court'),
('Usworth'),
('Usworth Close'),
('Usworth Road'),
('Usworth Station Road'),
('Utah Close'),
('Utah Drive'),
('Utah Lane'),
('Utah Rise'),
('Utah Road'),
('UTC Building'),
('UTC Central Bedfordshire'),
('UTC Norfolk'),
('UTC Plymouth'),
('UTC Portsmouth'),
('UTC Reading'),
('UTC Sheffield'),
('UTC Warrington'),
('UTC@harbourside'),
('UTC@MediaCityUK'),
('Utgard Way'),
('Utica'),
('Utile Gardens'),
('Utkinton'),
('Utkinton and Cotebrook'),
('Utkinton Close'),
('Utkinton Lane'),
('Utkinton Road'),
('Utla Taing'),
('Utleys Croft'),
('Uton'),
('Utopia Place'),
('Utopia Way'),
('Utrecht Court'),
('Utrillo Close'),
('Utstabi'),
('Utterby'),
('Utterby Drive'),
('Utterby Side'),
('Utters Hill'),
('Utting Avenue'),
('Utting Avenue East'),
('Utting Close'),
('Uttlesford'),
('Uttley Close'),
('Uttley Croft'),
('Uttley Drive'),
('Uttley Street'),
('Uttons Avenue'),
('Uttons Drove'),
('Uttoxeter'),
('Uttoxeter Avenue'),
('Uttoxeter Close'),
('Uttoxeter New Road'),
('Uttoxeter Old Road'),
('Uttoxeter Road'),
('Uttoxeter Rural'),
('Uttoxeter Town'),
('Uvedale Close'),
('Uvedale Crescent'),
('Uvedale Gardens'),
('Uvedale Road'),
('Uverdale Road'),
('Uwch Conwy'),
('Uwch Gwendraeth'),
('Uwch Menai'),
('Uwch Mynydd'),
('Uwch Y Maes'),
('Uwch-mynydd'),
('Uwch-Y-Don Avenue'),
('Uwch-Y-Dre'),
('Uwch-y-llan Wood'),
('Uwch-Y-Mor'),
('Uwch-Y-Nant'),
('Uwchafon'),
('Uwchaled'),
('Uwchlawr-Coed'),
('Uwchmynydd'),
('Uwchydre'),
('Uwchygarreg'),
('Uwe Hillside Gardens'),
('Ux Ness'),
('Uxavig'),
('Uxbridge'),
('Uxbridge and South Ruislip'),
('Uxbridge Avenue'),
('Uxbridge Close'),
('Uxbridge Crescent'),
('Uxbridge Drive'),
('Uxbridge Grove'),
('Uxbridge Lane'),
('Uxbridge Moor'),
('Uxbridge North'),
('Uxbridge Road'),
('Uxbridge Road High Street'),
('Uxbridge Road The Broadway'),
('Uxbridge Square'),
('Uxbridge Street'),
('Uxendon Crescent'),
('Uxendon Hill'),
('Uxilla Terrace'),
('Uxmore Road'),
('Uxna Geo'),
('Uyea'),
('Uyea Sound'),
('Uyeasound'),
('Uynarey'),
('Uzella Park'),
('Uzmaston'),
('Uzmaston Road'),
('Uzzles Hill'),
('Ubá'),
('Ube'),
('Uberaba'),
('Uberlândia'),
('Ubon Ratchathani'),
('Udaipur'),
('Udgir'),
('Udine'),
('Udon Thani'),
('Udupi'),
('Ueda'),
('Ufa'),
('Uji'),
('Ujjain'),
('Ulaanbaatar'),
('Ulan Hot'),
('Ulanqab'),
('Ulan-Ude'),
('Ulhasnagar'),
('Ulm'),
('Ulsan'),
('Uluberia'),
('Ulyanovsk'),
('Umlazi'),
('Umuarama'),
('Unaizah'),
('Unnao'),
('Uppsala'),
('Urasoe'),
('Urawa'),
('Urayasu'),
('Urdaneta'),
('Urgench'),
('Uribia'),
('Urmia'),
('Uruapan'),
('Uruguaiana'),
('Uruma'),
('Ürümqi'),
('Uşak'),
('Ussuriysk'),
('Utrecht'),
('Utsunomiya'),
('Uttarpara'),
('Uzhhorod'),
('Undercliff'),
('Underfleet'),
('Underway'),
('Underwood'),
('Uplands'),
('Upper Drive'),
('Upper Huddles'),
('Upper Tynings'),
('Upway'),
('Urie');

-- Down
DELETE FROM "Placename" WHERE "keyword" LIKE 'u%';
