-- Up
INSERT INTO "Placename"
("keyword")
VALUES
('Vaa Geo'),
('Vaagen Road'),
('Vaagso Close'),
('Vaakel Craigs'),
('Vaal Street'),
('Vaasetter'),
('Vache Lane'),
('Vachel Road'),
('Vachelich'),
('Vachell Court'),
('Vachell Road'),
('Vacherie Lane'),
('Vachery Lane'),
('Vachery Pond'),
('Vacye Wood'),
('Vadament Stack'),
('Vadill'),
('Vadill of Garth'),
('Vadis Close'),
('Vadna Geo'),
('Vadna Taing'),
('Vadne Gardens'),
('Vaendre Close'),
('Vaendre Lane'),
('Vaga Close'),
('Vaga Crescent'),
('Vaga Street'),
('Vagaland'),
('Vagar Hill'),
('Vagarth Close'),
('Vagg'),
('Vagg Copse'),
('Vagg Lane'),
('Vaggs Hill'),
('Vaggs Hill Bushes'),
('Vaggs Lane'),
('Vahler Terrace'),
('Vai Voe'),
('Vaila'),
('Vaila Lane'),
('Vaila Place'),
('Vaila Sound'),
('Vaila Street'),
('Vailan'),
('Vaile Mead'),
('Vaillant Road'),
('Vaindre Close'),
('Vaindre Drive'),
('Vainor Road'),
('Vair Geo'),
('Vaisey Field'),
('Vaisey Road'),
('Vaitam'),
('Vakel of Baagie'),
('Val Ayre'),
('Val Prinseps Road'),
('Val View'),
('Valaberg'),
('Valan Leas'),
('Valance Avenue'),
('Valance Close'),
('Valance Road'),
('Valanders Lane'),
('Valarian Close'),
('Valasay'),
('Valbourne Road'),
('Vald Skerries'),
('Valda Road'),
('Valda Vale'),
('Valdene Close'),
('Valdene Drive'),
('Valdetta Court'),
('Valdoe'),
('Vale'),
('Vale Acre Copse'),
('Vale Avenue'),
('Vale Bank'),
('Vale Close'),
('Vale Community'),
('Vale Coppice'),
('Vale Copse'),
('Vale Cottages'),
('Vale Court'),
('Vale Crescent'),
('Vale Croft'),
('Vale Down'),
('Vale Drive'),
('Vale Edge'),
('Vale End'),
('Vale Estate'),
('Vale Farm Road'),
('Vale Foundary Lane'),
('Vale Gardens'),
('Vale Grove'),
('Vale Head'),
('Vale Head Drive'),
('Vale Head Grove'),
('Vale Head Mount'),
('Vale House Close'),
('Vale House Drive'),
('Vale Lane'),
('Vale Leaze'),
('Vale Link'),
('Vale Mews'),
('Vale Mill Lane'),
('Vale Mill Way'),
('Vale of Aylesbury'),
('Vale of Belvoir'),
('Vale of Berkeley'),
('Vale Of Bonny View'),
('Vale of Catmose'),
('Vale of Clwyd'),
('Vale of Conwy'),
('Vale of Edale'),
('Vale of Evesham'),
('Vale of Ewyas'),
('Vale of Ffestiniog'),
('Vale of Glamorgan'),
('Vale of Gloucester'),
('Vale of Health'),
('Vale of Holmesdale'),
('Vale of Kent'),
('Vale of Lanherne'),
('Vale Of Leven District General'),
('Vale of Llangollen'),
('Vale of Mawgan'),
('Vale of Montgomery'),
('Vale of Mowbray'),
('Vale of Neath'),
('Vale Of Neath Road'),
('Vale of Nightshade'),
('Vale of Pewsey'),
('Vale of Pickering'),
('Vale of Taunton Deane'),
('Vale of Wardour'),
('Vale of White Horse'),
('Vale of York'),
('Vale Orchard'),
('Vale Owen Road'),
('Vale Park'),
('Vale Park Drive'),
('Vale Park Way'),
('Vale Place'),
('Vale Pleasant'),
('Vale Reach'),
('Vale Rise'),
('Vale Road'),
('Vale Road Bridge'),
('Vale Row'),
('Vale Royal'),
('Vale Royal Close'),
('Vale Royal Drive'),
('Vale Royal Wood'),
('Vale Side'),
('Vale Square'),
('Vale Street'),
('Vale Street East'),
('Vale Terrace'),
('Vale Top Avenue'),
('Vale View'),
('Vale View Close'),
('Vale View Crescent'),
('Vale View Drive'),
('Vale View Gardens'),
('Vale View Road'),
('Vale View Terrace'),
('Vale Walk'),
('Vale Way'),
('Vale Wood'),
('Vale Wood Drive'),
('Vale Wood Lane'),
('Valebridge Close'),
('Valebridge Drive'),
('Valebridge Pond'),
('Valebridge Road'),
('Valebrook'),
('Valebrook Close'),
('Valebrook Drive'),
('Valebrook Road'),
('Valebrooke Avenue'),
('Valebrooke Gardens'),
('Valehead'),
('Valehouse Close'),
('Valehouse Court'),
('Valehouse Farm'),
('Valehouse Reservoir'),
('Valehouse View'),
('Valehouse Wood'),
('Valemount'),
('Valence'),
('Valence Avenue'),
('Valence Circus'),
('Valence Crescent'),
('Valence Drive'),
('Valence End'),
('Valence Road'),
('Valence Walk'),
('Valence Way'),
('Valence Wood'),
('Valence Wood Road'),
('Valencia Close'),
('Valencia Croft'),
('Valencia Grove'),
('Valencia Road'),
('Valencia Way'),
('Valenciennes Road'),
('Valency Close'),
('Valency Drive'),
('Valency Row'),
('Valens Close'),
('Valens Terrace'),
('Valenta Close'),
('Valentia Avenue'),
('Valentia Close'),
('Valentia Court'),
('Valentia Place'),
('Valentia Road'),
('Valentina Avenue'),
('Valentina Court'),
('Valentine Avenue'),
('Valentine Close'),
('Valentine Court'),
('Valentine Crescent'),
('Valentine Drive'),
('Valentine Grove'),
('Valentine Mews'),
('Valentine Place'),
('Valentine Rise'),
('Valentine Road'),
('Valentine Row'),
('Valentine Spring'),
('Valentine Street'),
('Valentine Walk'),
('Valentine Way'),
('Valentine Wood'),
('Valentines'),
('Valentines Close'),
('Valentines Clump'),
('Valentines Drive'),
('Valentines Gardens'),
('Valentines Grove'),
('Valentines Lane'),
('Valentines Lea'),
('Valentines Meadow'),
('Valentines Park'),
('Valentines Road'),
('Valentines Way'),
('Valentines Wood'),
('Valentines Woods'),
('Valentinus Crescent'),
('Valentyne Close'),
('Valepits Road'),
('Valeria Close'),
('Valerian Avenue'),
('Valerian Close'),
('Valerian Court'),
('Valerian Drive'),
('Valerian Gardens'),
('Valerian Grove'),
('Valerian Place'),
('Valerian Rise'),
('Valerian Road'),
('Valerian Street'),
('Valerian Walk'),
('Valerian Way'),
('Valeridge Copse'),
('Valerie Close'),
('Valerie Grove'),
('Valerie Road'),
('Valerio Court'),
('Valeroyal Cut'),
('Valeroyal Park'),
('Valery Place'),
('Valery Road'),
('Vales Close'),
('Vales Moor'),
('Vales Road'),
('Vales Wood'),
('Valescourt Road'),
('Valeside'),
('Valeside Gardens'),
('Valestone Avenue'),
('Valestone Close'),
('Valeswood Lane'),
('Valeswood Road'),
('Valetta Close'),
('Valetta Drive'),
('Valetta Gardens'),
('Valetta Grove'),
('Valetta Park'),
('Valetta Place'),
('Valetta Road'),
('Valetta Way'),
('Valette Road'),
('Valette Street'),
('Valeview'),
('Valeview Terrace'),
('Valeway Avenue'),
('Valewood Avenue'),
('Valewood Close'),
('Valewood Lane'),
('Valewood Road'),
('Valfreda Way'),
('Valgreen Court'),
('Valiant Avenue'),
('Valiant Close'),
('Valiant Drive'),
('Valiant Gardens'),
('Valiant Place'),
('Valiant Road'),
('Valiant Square'),
('Valiant Street'),
('Valiant Way'),
('Valiers Bottom'),
('Valingers Place'),
('Valingers Road'),
('Valjean Crescent'),
('Valkyrie Avenue'),
('Valkyrie Close'),
('Valkyrie Road'),
('Vall Ayre'),
('Valla Dale'),
('Valla Field'),
('Valla Kames'),
('Valla Ness'),
('Valladale'),
('Vallance Close'),
('Vallance Drive'),
('Vallance Gardens'),
('Vallance Place'),
('Vallance Road'),
('Vallance Street'),
('Vallans Close'),
('Vallansgate'),
('Vallantine Crescent'),
('Vallaquie Strand'),
('Vallastrome'),
('Vallay'),
('Vallay Strand'),
('Vallay Street'),
('Vallenders Road'),
('Vallentin Road'),
('Vallentin Way'),
('Vallet Avenue'),
('Vallet Covert'),
('Valletort'),
('Valletort Lane'),
('Valletort Park'),
('Valletort Place'),
('Valletort Road'),
('Vallets Coppice'),
('Vallets Wood'),
('Valletta Close'),
('Valletta Street'),
('Valletta Way'),
('Valletts Lane'),
('Valley Airfield'),
('Valley Approach'),
('Valley Avenue'),
('Valley Belt'),
('Valley Bridge'),
('Valley Bridge Parade'),
('Valley Bridge Road'),
('Valley Close'),
('Valley Clump'),
('Valley Corner'),
('Valley Cottages'),
('Valley Court'),
('Valley Covers'),
('Valley Creek'),
('Valley Crescent'),
('Valley Dam'),
('Valley Dane Shaw'),
('Valley Dene'),
('Valley Drive'),
('Valley End'),
('Valley End House'),
('Valley End Road'),
('Valley Farm Drive'),
('Valley Farm Lane'),
('Valley Farm Road'),
('Valley Farm Spinney'),
('Valley Farm Way'),
('Valley Field'),
('Valley Field Covert'),
('Valley Field View'),
('Valley Fields Crescent'),
('Valley Fold'),
('Valley Forge'),
('Valley Forge Close'),
('Valley Gardens'),
('Valley Garth'),
('Valley Green'),
('Valley Grove'),
('Valley Head'),
('Valley Heights'),
('Valley Hill'),
('Valley Lane'),
('Valley Lodge'),
('Valley Manor'),
('Valley Mead'),
('Valley Meadow'),
('Valley Meadow Close'),
('Valley Meadow Wood'),
('Valley Mews'),
('Valley Mill Court'),
('Valley Mill Lane'),
('Valley Mount'),
('Valley Mushroom Farm'),
('Valley New Road'),
('Valley of Coustry'),
('Valley of Desolation'),
('Valley of Houlland'),
('Valley of Keelhamar'),
('Valley of Koam'),
('Valley of Rocks'),
('Valley of Stones'),
('Valley of the Rocks'),
('Valley of Uraday'),
('Valley Parade'),
('Valley Park'),
('Valley Park Close'),
('Valley Park Drive'),
('Valley Park Lane'),
('Valley Park Road'),
('Valley Park Way'),
('Valley Prospect'),
('Valley Ridge'),
('Valley Rise'),
('Valley Road'),
('Valley Side'),
('Valley Side Road'),
('Valley Square'),
('Valley Street'),
('Valley Street North'),
('Valley Terrace'),
('Valley Truckle'),
('Valley View'),
('Valley View Close'),
('Valley View Court'),
('Valley View Crescent'),
('Valley View Drive'),
('Valley View Estate'),
('Valley View Gardens'),
('Valley View Grove'),
('Valley View Park'),
('Valley View Rise'),
('Valley View Road'),
('Valley View Street'),
('Valley Walk'),
('Valley Wash'),
('Valley Way'),
('Valley Way Road'),
('Valley Wood'),
('Valleybank'),
('Valleybridge Road'),
('Valleybrook Grove'),
('Valleydene'),
('Valleyfield'),
('Valleyfield Avenue'),
('Valleyfield Brae'),
('Valleyfield Crescent'),
('Valleyfield Drive'),
('Valleyfield Glen'),
('Valleyfield Meadow'),
('Valleyfield Park'),
('Valleyfield Place'),
('Valleyfield Road'),
('Valleyfield Street'),
('Valleyfield Top'),
('Valleyfield Woods'),
('Valleys Shaw'),
('Valleyside'),
('Valleyview Drive'),
('Valleyview Place'),
('Vallian Croft'),
('Valliant Street'),
('Vallibus Close'),
('Valliere Road'),
('Valliers Ness'),
('Valliers Wood Road'),
('Valligates'),
('Vallin Ness'),
('Vallings Place'),
('Vallis Close'),
('Vallis Road'),
('Vallis Vale'),
('Vallis Way'),
('Vallum Close'),
('Vallum Gardens'),
('Vallum Place'),
('Vallum Road'),
('Vallum Way'),
('Valma Rocks'),
('Valmar Avenue'),
('Valmar Road'),
('Valmeade Close'),
('Valmont Avenue'),
('Valmont Road'),
('Valnay Street'),
('Valognes Avenue'),
('Valon Road'),
('Valonia Drive'),
('Valonia Gardens'),
('Valor Drive'),
('Valpy Avenue'),
('Valpy Street'),
('Valroy Close'),
('Vals Ness'),
('Valsheba Drive'),
('Valti Stack'),
('Valtos'),
('Valtos Rocks'),
('Valuation Lane'),
('Valvedare Wood'),
('Valway'),
('Vambery Road'),
('Vamh'),
('Vampire Road'),
('Vampire Way'),
('Van Alen Mews'),
('Van Common'),
('Van Der Bilt Court'),
('Van Der Breen Street'),
('Van Diemans'),
('Van Diemans Gardens'),
('Van Diemans Land'),
('Van Diemans Lane'),
('Van Diemans Road'),
('Van Diemans Way'),
('Van Diemens Close'),
('Van Diemens Gardens'),
('Van Diemens Land'),
('Van Diemens Lane'),
('Van Diemens Pass'),
('Van Dyck Avenue'),
('Van Dyck Close'),
('Van Dyck Place'),
('Van Dyck Road'),
('Van Dyke Close'),
('Van Dyke Place'),
('Van Gogh Close'),
('Van Gogh Drive'),
('Van Gogh Place'),
('Van Mildert Close'),
('Van Mildert Road'),
('Van Mildert Way'),
('Van Pool'),
('Van Road'),
('Van Street'),
('Van-Diemans Lane'),
('Vanborough Court'),
('Vanborough Walk'),
('Vanbrough Crescent'),
('Vanbrugh Close'),
('Vanbrugh Court'),
('Vanbrugh Crescent'),
('Vanbrugh Drive'),
('Vanbrugh Fields'),
('Vanbrugh Gardens'),
('Vanbrugh Gate'),
('Vanbrugh Grove'),
('Vanbrugh Hill'),
('Vanbrugh Lane'),
('Vanbrugh Park'),
('Vanbrugh Park Road'),
('Vanbrugh Park Road West'),
('Vanbrugh Road'),
('Vanbrugh Terrace'),
('Vanbrugh Way'),
('Vanburgh Close'),
('Vanburgh Gardens'),
('Vanburgh Place Lane'),
('Vanburgh Way'),
('Vance Road'),
('Vances Glen'),
('Vancouver Avenue'),
('Vancouver Close'),
('Vancouver Court'),
('Vancouver Crescent'),
('Vancouver Drive'),
('Vancouver Gardens'),
('Vancouver House'),
('Vancouver Lane'),
('Vancouver Place'),
('Vancouver Quay'),
('Vancouver Road'),
('Vancouver Street'),
('Vancouver Way'),
('Vanda Crescent'),
('Vandeleur Avenue'),
('Vandeleur Grove'),
('Vandeleur Place'),
('Vandenbury Circle'),
('Vanderbilt Avenue'),
('Vanderbilt Road'),
('Vanderbyl Avenue'),
('Vanderhoot Way'),
('Vanderlin Court'),
('Vanderplanks Covert'),
('Vanderville Gardens'),
('Vanderwalt Avenue'),
('Vandome Close'),
('Vandon Street'),
('Vandra Close'),
('Vandries Street'),
('Vandyck Avenue'),
('Vandyck Road'),
('Vandyke'),
('Vandyke Avenue'),
('Vandyke Close'),
('Vandyke Cross'),
('Vandyke Road'),
('Vandyke Street'),
('Vane Close'),
('Vane Clump'),
('Vane Coppice'),
('Vane Court'),
('Vane Hall Place'),
('Vane Hill'),
('Vane Lane'),
('Vane Road'),
('Vane Street'),
('Vane Terrace'),
('Vanehill Road'),
('Vanes Copse'),
('Vanessa Avenue'),
('Vanessa Close'),
('Vanessa Drive'),
('Vanessa Road'),
('Vanessa Walk'),
('Vanessa Way'),
('Vanfield Close'),
('Vangarde Way'),
('Vange'),
('Vange Corner Drive'),
('Vange Cottage Mews'),
('Vange Hill Drive'),
('Vange Marshes'),
('Vange Park Road'),
('Vanguard'),
('Vanguard Avenue'),
('Vanguard Chase'),
('Vanguard Circle'),
('Vanguard Close'),
('Vanguard Court'),
('Vanguard Hill'),
('Vanguard Road'),
('Vanguard Street'),
('Vanguard Way'),
('Vanguard Wharf'),
('Vanhurst Copse'),
('Vanilla Close'),
('Vanilla Mews'),
('Vanity Close'),
('Vanity Lane'),
('Vanity Road'),
('Vanlore Way'),
('Vann Bridge Close'),
('Vann Close'),
('Vann Copse'),
('Vann Farm Road'),
('Vann Hill'),
('Vann Lake'),
('Vann Lake Road'),
('Vann Lane'),
('Vann Road'),
('Vanna-gya'),
('Vanneck Close'),
('Vanneck Square'),
('Vanner Road'),
('Vanners'),
('Vanners Copse'),
('Vanners Lane'),
('Vanners Road'),
('Vanoc Gardens'),
('Vanoli Close'),
('Vanpost Hill'),
('Vanquish Close'),
('Vanquisher Walk'),
('Vanrigg Wood'),
('Vans Gill'),
('Vans Wood'),
('Vansittart Drive'),
('Vansittart Estate'),
('Vansittart Road'),
('Vansittart Street'),
('Vanston Place'),
('Vanstone Road'),
('Vant Road'),
('Vant Street'),
('Vantage Copse'),
('Vantage Court'),
('Vantage Drive'),
('Vantage Meadow'),
('Vantage Mews'),
('Vantage Road'),
('Vantage Street'),
('Vantage Way'),
('Vantomme Street'),
('Vantorts Close'),
('Vantorts Road'),
('Vanwall Drive'),
('Vanwall Road'),
('Vanzell Road'),
('Vapery Lane'),
('Vapron Road'),
('Var Cottage Wood'),
('Vara Close'),
('Varah Close'),
('Varaquoy'),
('Varchoel'),
('Varchoel Lane'),
('Varco Square'),
('Varcoe Gardens'),
('Varcoe Road'),
('Vardar Avenue'),
('Varden Avenue'),
('Varden Close'),
('Varden Croft'),
('Varden Grove'),
('Varden Road'),
('Varden Street'),
('Vardens Road'),
('Vardentown'),
('Vardon Close'),
('Vardon Drive'),
('Vardon Green'),
('Vardon Lea'),
('Vardon Place'),
('Vardon Road'),
('Vardon Way'),
('Vardre'),
('Vardre Avenue'),
('Vardre Close'),
('Vardre Lane'),
('Vardre Road'),
('Vardroe Way'),
('Vardy Close'),
('Vardy Terrace'),
('Varey Road'),
('Varey Street'),
('Varfell Lane'),
('Varian Court'),
('Varich Place'),
('Varis Road'),
('Varle Hill'),
('Varley'),
('Varley Avenue'),
('Varley Close'),
('Varley Court'),
('Varley Drive'),
('Varley Gardens'),
('Varley Halls Of Residence'),
('Varley Head'),
('Varley Lane'),
('Varley Parade'),
('Varley Road'),
('Varley Sand'),
('Varley Street'),
('Varley Vale'),
('Varley Way'),
('Varleys Copse'),
('Varlian Close'),
('Varlins Way'),
('Varlow Road'),
('Varmady'),
('Varme Dale'),
('Varna Close'),
('Varna Lane'),
('Varna Road'),
('Varna Street'),
('Varncombe Hill'),
('Varndean Close'),
('Varndean Drive'),
('Varndean Gardens'),
('Varndean Holt'),
('Varndean Road'),
('Varndell Road'),
('Varndell Street'),
('Varndells Copse'),
('Varne Place'),
('Varne Road'),
('Varnes Street'),
('Varney Avenue'),
('Varney Close'),
('Varney Road'),
('Varneys Wood'),
('Varnister Lane'),
('Varnister Road'),
('Varnsdorf Way'),
('Varo Terrace'),
('Varos Close'),
('Varrick Way'),
('Varrier Jones Drive'),
('Varrier Jones Place'),
('Varriers Wood'),
('Vars Road'),
('Varses'),
('Varsity'),
('Varsity Close'),
('Varsity Drive'),
('Varsity Rise'),
('Varsity Road'),
('Varsity Row'),
('Varsity Way'),
('Vart Road'),
('Varteg'),
('Varteg Hill'),
('Varteg Road'),
('Varteg Row'),
('Vartenham Hill'),
('Varthen Street'),
('Vartry Road'),
('Varvel Avenue'),
('Varvel Close'),
('Vary Clump'),
('Vary Coppice'),
('Vasa Loch'),
('Vasa Point'),
('Vasart Court'),
('Vasart Place'),
('Vaseford Copse'),
('Vasey Close'),
('Vasey Crescent'),
('Vashon Close'),
('Vashon Drive'),
('Vassa'),
('Vassa Voe'),
('Vassall'),
('Vassall Court'),
('Vassall Road'),
('Vassancro'),
('Vassar Court'),
('Vasser Road'),
('Vastern'),
('Vastern Road'),
('Vastern Wharf'),
('Vastern Wood'),
('Vasterne Close'),
('Vastre View'),
('Vat of Kirbuster'),
('Vatch Lane'),
('Vatch View'),
('Vatem'),
('Vatersay'),
('Vatersay Place'),
('Vati Geo'),
('Vatisker'),
('Vatisker Park'),
('Vatna Gaet'),
('Vats Meadow'),
('Vats Wick'),
('Vats-houll'),
('Vats-houll Voe'),
('Vatten'),
('Vatten Island'),
('Vattingstone Brake'),
('Vattingstone Lane'),
('Vauban Drive'),
('Vauban Place'),
('Vauban Street'),
('Vauce Wood'),
('Vaucluse Place'),
('Vaudeville Close'),
('Vaudrey Close'),
('Vaudrey Crescent'),
('Vaudrey Drive'),
('Vaudrey Lane'),
('Vaudrey Road'),
('Vaudrey Street'),
('Vaughan Avenue'),
('Vaughan Close'),
('Vaughan Court'),
('Vaughan Crescent'),
('Vaughan Drive'),
('Vaughan Gardens'),
('Vaughan Grove'),
('Vaughan Lane'),
('Vaughan Mead'),
('Vaughan Parade'),
('Vaughan Place'),
('Vaughan Rise'),
('Vaughan Road'),
('Vaughan Street'),
('Vaughan Terrace'),
('Vaughan Thomas Lane'),
('Vaughan Way'),
('Vaughan Williams Close'),
('Vaughan Williams Drive'),
('Vaughan Williams Road'),
('Vaughan Williams Way'),
('Vaughans'),
('Vaughans Lane'),
('Vaughn Street'),
('Vaughton Drive'),
('Vaughton Hill'),
('Vaughton Street'),
('Vaul'),
('Vaul Bay'),
('Vault Beach'),
('Vault Glen'),
('Vault Hill'),
('Vault Hill Wood'),
('Vault Square'),
('Vaults Lane'),
('Vaults Wood'),
('Vaulx Road'),
('Vaunces Lane'),
('Vauterhill Moor'),
('Vaux Avenue'),
('Vaux Crescent'),
('Vaux Place'),
('Vaux Road'),
('Vauxhall'),
('Vauxhall Avenue'),
('Vauxhall Bridge Road'),
('Vauxhall Centre'),
('Vauxhall Close'),
('Vauxhall Copse'),
('Vauxhall Covert'),
('Vauxhall Crescent'),
('Vauxhall Drive'),
('Vauxhall Gardens'),
('Vauxhall Grove'),
('Vauxhall Lane'),
('Vauxhall Place'),
('Vauxhall Quay'),
('Vauxhall Road'),
('Vauxhall Street'),
('Vauxhall Terrace'),
('Vauxhall Walk'),
('Vauxhall Way'),
('Vauze Avenue'),
('Vauze House Close'),
('Vavasour Court'),
('Vavasours Slip'),
('Vawdrey Close'),
('Vawdrey Drive'),
('Vawdrey Road'),
('Vawers Close'),
('Vawser Crescent'),
('Vawser Way'),
('Vayne Moor Wood'),
('Vaynol Close'),
('Vaynol Covert'),
('Vaynol Hall'),
('Vaynol Street'),
('Vaynol Way'),
('Vaynol Wood'),
('Vaynor'),
('Vaynor Drive'),
('Vaynor Lane'),
('Vaynor Road'),
('Vaynor Street'),
('Vaynor-fâch Wood'),
('Vayre Close'),
('Vayro Close'),
('Ve Ness'),
('Ve Skerries'),
('Veal Lane'),
('Veal Street'),
('Veale Close'),
('Veale Drive'),
('Vealenia Terrace'),
('Veales Road'),
('Veals Copse'),
('Veals Lane'),
('Veals Mead'),
('Veals Row'),
('Veals Wood'),
('Vean Hole'),
('Vean Road'),
('Vean Terrace'),
('Veantrow Bay'),
('Vears Lane'),
('Vearse Close'),
('Veasey Close'),
('Veasey Road'),
('Veasey Way'),
('Veasypark'),
('Veathery Quoy'),
('Vecqueray Street'),
('Vecta Close'),
('Vecta House'),
('Vectis Close'),
('Vectis Drive'),
('Vectis Gardens'),
('Vectis Road'),
('Vectis Way'),
('Vector Walk'),
('Veda Road'),
('Vedal Drove'),
('Vedders Geo'),
('Veddoes Coppice'),
('Vedonis Park'),
('Vedonis Road'),
('Vedra Close'),
('Vedra Street'),
('Vedrato'),
('Vedri Geo'),
('Vedrick'),
('Vedwllwyd Wood'),
('Vee Lane'),
('Vee Taing'),
('Veeda Stack'),
('Veedie'),
('Veensgarth'),
('Veenston Glen'),
('Veere Park'),
('Veester Hill'),
('Veevers Street'),
('Vega Close'),
('Vega Crescent'),
('Vega Road'),
('Vega Street'),
('Vegal Crescent'),
('Vegas'),
('Veille Lane'),
('Veiny Cheese Pond'),
('Veir Terrace'),
('Veitch Close'),
('Veitch Gardens'),
('Veitch Place'),
('Veitches Court'),
('Veitchs Square'),
('Vela Close'),
('Vela Row'),
('Vela Walk'),
('Velator'),
('Velator Close'),
('Velator Drive'),
('Velator Lane Avenue'),
('Velator Road'),
('Velda Close'),
('Velden Way'),
('Veldene Way'),
('Velder Avenue'),
('Veldo'),
('Veldo Lane'),
('Veles Road'),
('Velfrey Road'),
('Velhurst Copse'),
('Velhurst Drive'),
('Velindre'),
('Velindre Cancer Centre'),
('Velindre Place'),
('Velindre Road'),
('Velindre Street'),
('Velindre Wood'),
('Velizy Avenue'),
('Vellacott Close'),
('Vellacott Lane'),
('Vellacott Wood'),
('Vellacotts'),
('Vellan Avenue'),
('Vellan Close'),
('Vellan Court'),
('Vellan Drang'),
('Vellan Head'),
('Vellan Parc Avenue'),
('Vellan Vrane'),
('Velland Avenue'),
('Vellandrucia'),
('Vellanoweth'),
('Vellator Way'),
('Velley Hill'),
('Vellin-gluz Rocks'),
('Vellore Lane'),
('Vellore Road'),
('Vellow'),
('Vellow Moor Lane'),
('Vellow Road'),
('Vellow Wood'),
('Vellow Wood Lane'),
('Vellum Drive'),
('Vellus Court'),
('Velly Wood'),
('Velmead Close'),
('Velmead Road'),
('Velmere Avenue'),
('Velmore Road'),
('Velocette Way'),
('Velocity Way'),
('Velour Close'),
('Velsheda Close'),
('Velsheda Court'),
('Velsheda Road'),
('Velsheda View'),
('Velt Hevda'),
('Velthouse Lane'),
('Veltie'),
('Veltie Skerry'),
('Veltieskerry Loch'),
('Veltshaw Close'),
('Velver Wood'),
('Velvet Beds Island'),
('Velvet Bottom'),
('Velvet Hall Strip'),
('Velvet Lawn'),
('Velvet Lawn Road'),
('Velvet Rock'),
('Velvet Street'),
('Velvet Wood Close'),
('Velvetere Wood'),
('Velville Court'),
('Velwell Road'),
('Velyn Avenue'),
('Vementry'),
('Ven Combe'),
('Ven Law'),
('Venables Avenue'),
('Venables Close'),
('Venables Coppice'),
('Venables Court'),
('Venables Drive'),
('Venables Lane'),
('Venables Road'),
('Venables Street'),
('Venables Way'),
('Venachar Avenue'),
('Venachar Place'),
('Venachar Road'),
('Venalie'),
('Venator Place'),
('Venborough Close'),
('Venbridge Hill'),
('Vence Close'),
('Venchen Hill'),
('Venches Rock'),
('Vencourt Place'),
('Vendace Crescent'),
('Vendace Drive'),
('Vendace Mews'),
('Vendace Place'),
('Vendace Wynd'),
('Vendale Avenue'),
('Vendeen'),
('Vendeen Crescent'),
('Vendra Stacks'),
('Venerable Road'),
('Venericks Cove'),
('Veness'),
('Veness Hill'),
('Venesta Avenue'),
('Venetia Close'),
('Venetia Park'),
('Venetia Road'),
('Venetia Street'),
('Venetian Court'),
('Venetian Crescent'),
('Venetian Road'),
('Venette Close'),
('Venford Close'),
('Venford Hill'),
('Venford Moor'),
('Venford Reservoir'),
('Venford Wood'),
('Vengeance Road'),
('Vengeance Street'),
('Venges Brake'),
('Venhay Down'),
('Venibar'),
('Venice'),
('Venice Avenue'),
('Venice Close'),
('Venice Court'),
('Venice Street'),
('Venics Way'),
('Venison Wood'),
('Veniss Copse'),
('Venlake'),
('Venlake Close'),
('Venlake End'),
('Venland Close'),
('Venlaw High Road'),
('Venlaw Quarry Road'),
('Venlaw Road'),
('Venley Copse'),
('Venley Lane'),
('Venlo Road'),
('Venlock Close'),
('Venlow Gardens'),
('Venmans Hill Wood'),
('Venmore Drive'),
('Venmore Street'),
('Venn'),
('Venn Channing Copse'),
('Venn Close'),
('Venn Close Coppice'),
('Venn Copse'),
('Venn Court'),
('Venn Crescent'),
('Venn Cross'),
('Venn Dingle'),
('Venn Down'),
('Venn Drive'),
('Venn Gardens'),
('Venn Grove'),
('Venn Hill'),
('Venn Lane'),
('Venn Moor'),
('Venn Orchard'),
('Venn Ottery'),
('Venn Ottery Common'),
('Venn Ottery Hill'),
('Venn Ottery Road'),
('Venn Park'),
('Venn Place'),
('Venn Road'),
('Venn Street'),
('Venn Way'),
('Venn Wood'),
('Vennacher Road'),
('Vennacher Street'),
('Vennal Hill'),
('Vennals Copse'),
('Vennard Gardens'),
('Vennaway Lane'),
('Venneit Close'),
('Vennel Lane'),
('Vennel Street'),
('Venner Avenue'),
('Venner Close'),
('Venner Road'),
('Venners Close'),
('Venners Water'),
('Venngreen'),
('Venning Avenue'),
('Venning Grove'),
('Venning Road'),
('Vennings Copse'),
('Vennington'),
('Vennington Walk'),
('Vennland Way'),
('Vennpark Moor'),
('Venns Acre'),
('Venns Close'),
('Venns Gate'),
('Venns Green'),
('Venns Lane'),
('Venns Road'),
('Venns Wood'),
('Vennwood Close'),
('Venny Bridge'),
('Venny Tedburn'),
('Venom Road'),
('Venomous Clough'),
('Vensfield Road'),
('Vensilly Hill'),
('Vensland'),
('Venslooe Hill'),
('Venslooe Wood'),
('Venta Drive'),
('Venta Way'),
('Venterdon'),
('Ventfield Close'),
('Vention'),
('Vention Lane'),
('Vention Road'),
('Ventnor'),
('Ventnor Avenue'),
('Ventnor Bay'),
('Ventnor Close'),
('Ventnor Court'),
('Ventnor Crescent'),
('Ventnor Drive'),
('Ventnor East'),
('Ventnor Gardens'),
('Ventnor Grove'),
('Ventnor Haven'),
('Ventnor Lane'),
('Ventnor Place'),
('Ventnor Rise'),
('Ventnor Road'),
('Ventnor Street'),
('Ventnor Terrace'),
('Ventnor Villas'),
('Ventnor Way'),
('Ventnor West'),
('Vento Close'),
('Venton'),
('Venton Close'),
('Venton Cove'),
('Venton Drive'),
('Venton East Square'),
('Venton Hill Point'),
('Venton Lace Road'),
('Venton Moor'),
('Venton Road'),
('Venton Vaden'),
('Venton Vision Rise'),
('Venton Wood'),
('Ventongimps'),
('Ventongoose Road'),
('Ventonhills Copse'),
('Ventonleague'),
('Ventonleague Hill'),
('Ventonleague Row'),
('Ventonraze'),
('Ventonwyn Wood'),
('Ventor Street'),
('Ventress Close'),
('Ventress Hall'),
('Ventris Close'),
('Ventry Close'),
('Ventura Avenue'),
('Ventura Close'),
('Ventura Court'),
('Ventura Drive'),
('Ventura Park'),
('Ventura Park Road'),
('Ventura Place'),
('Venture Avenue'),
('Venture Avenue Venture Avenue'),
('Venture Chase'),
('Venture Close'),
('Venture Court'),
('Venture Crescent'),
('Venture Drive'),
('Venture Hill'),
('Venture Road'),
('Venture Scout Way'),
('Venture Street'),
('Venture Way'),
('Venturefair Avenue'),
('Venturefair Drive'),
('Venturefield Wood'),
('Venue Street'),
('Venus Avenue'),
('Venus Bank'),
('Venus Close'),
('Venus Court'),
('Venus Hill'),
('Venus Lane'),
('Venus Mews'),
('Venus Place'),
('Venus Road'),
('Venus Street'),
('Venus Way'),
('Venus Wood'),
('Venusbank Coppice'),
('Venusbank Wood'),
('Venvell Close'),
('Venwood'),
('Venwood Road'),
('Veny Crescent'),
('Veor Cove'),
('Veor Road'),
('Ver Brook Avenue'),
('Ver Geo'),
('Ver Road'),
('Vera Avenue'),
('Vera Close'),
('Vera Court'),
('Vera Crescent'),
('Vera Lane'),
('Vera Lynn Close'),
('Vera Road'),
('Vera Roberts Way'),
('Vera Street'),
('Vera Wood Close'),
('Veralam Way'),
('Verallo Drive'),
('Verandah Street'),
('Veras Walk'),
('Verax Street'),
('Verbania Way'),
('Verbena Avenue'),
('Verbena Close'),
('Verbena Court'),
('Verbena Crescent'),
('Verbena Drive'),
('Verbena Gardens'),
('Verbena Road'),
('Verbena Terrace'),
('Verbena Walk'),
('Verbena Way'),
('Vercor Close'),
('Vercourt'),
('Verda Place'),
('Verda Street'),
('Verdala Park'),
('Verdale Avenue'),
('Verdant Close'),
('Verdant Drive'),
('Verdant Lane'),
('Verdant Vale'),
('Verdant Way'),
('Verdayne Avenue'),
('Verdayne Gardens'),
('Verde Close'),
('Verden Avenue'),
('Verden Close'),
('Verden Way'),
('Verder Grove'),
('Verderers Road'),
('Verdi Avenue'),
('Verdi Close'),
('Verdi Court'),
('Verdi Crescent'),
('Verdi Road'),
('Verdi Street'),
('Verdi Terrace'),
('Verdin Avenue'),
('Verdin Close'),
('Verdin Court'),
('Verdin Street'),
('Verdins Cut'),
('Verdley Place'),
('Verdley Wood'),
('Verdon Avenue'),
('Verdon Close'),
('Verdon Crescent'),
('Verdon Drive'),
('Verdon Place'),
('Verdon Street'),
('Verdons Lane'),
('Verdun Avenue'),
('Verdun Close'),
('Verdun Crescent'),
('Verdun Road'),
('Verdun Square'),
('Verdun Terrace'),
('Verdure Avenue'),
('Verdure Close'),
('Verdure Gardens'),
('Vere Avenue'),
('Vere Close'),
('Vere Court'),
('Vere Gardens'),
('Vere Place'),
('Vere Point'),
('Vere Road'),
('Vere Square'),
('Vere Street'),
('Vere Terrace'),
('Vereker Drive'),
('Vereker Road'),
('Vereland Road'),
('Vereley'),
('Vereley Wood'),
('Verelst Avenue'),
('Verely Hill'),
('Verena Terrace'),
('Vereth Road'),
('Verey Close'),
('Verey Road'),
('Vergam Terrace'),
('Verge Wood'),
('Verger Close'),
('Vergette Court'),
('Vergette Road'),
('Vergette Street'),
('Vergyland Combe'),
('Verica Gardens'),
('Veridion Way'),
('Verig Street'),
('Verini Close'),
('Verinia Court'),
('Veritas Grove'),
('Verity Close'),
('Verity Crescent'),
('Verity Gardens'),
('Verity Place'),
('Verity Rise'),
('Verity Spur'),
('Verity Street'),
('Verity View'),
('Verity Walk'),
('Verity Way'),
('Veritys'),
('Verlam Grove'),
('Verland Close'),
('Verland Way'),
('Verlands'),
('Verlands Close'),
('Verlands Road'),
('Verlands Wood'),
('Verley Close'),
('Verlon Close'),
('Vermeer Close'),
('Vermeer Crescent'),
('Vermeer Ride'),
('Vermiel Grove'),
('Vermin Lane'),
('Vermin Valley'),
('Vermont'),
('Vermont Avenue'),
('Vermont Close'),
('Vermont Crescent'),
('Vermont Drive'),
('Vermont Gardens'),
('Vermont Green'),
('Vermont Grove'),
('Vermont Place'),
('Vermont Road'),
('Vermont Standing'),
('Vermont Street'),
('Vermont Way'),
('Vermont Woods'),
('Vermuyden'),
('Vermuyden Gardens'),
('Vermuyden Road'),
('Vermuyden Terrace'),
('Vermuyden Villas'),
('Vermuyden Way'),
('Vern Place'),
('Verna Place'),
('Verna Road'),
('Vernal Close'),
('Vernal Lane'),
('Vernalls Close'),
('Vernalls Court'),
('Vernalls Gardens'),
('Vernalls Road'),
('Vernatts Green'),
('Vernditch Chase'),
('Verne Avenue'),
('Verne Close'),
('Verne Common Road'),
('Verne Drive'),
('Verne Hill Road'),
('Verne Road'),
('Verne Walk'),
('Verne Way'),
('Verner Close'),
('Verner Common'),
('Verner Road'),
('Verner Street'),
('Verneuil Avenue'),
('Verney Avenue'),
('Verney Close'),
('Verney Copse'),
('Verney Crescent'),
('Verney Drive'),
('Verney Farm Close'),
('Verney Gardens'),
('Verney Junction'),
('Verney Mews'),
('Verney Park'),
('Verney Park'),
('Verney Road'),
('Verney Spinney'),
('Verney Street'),
('Verney Walk'),
('Verney Way'),
('Vernham Bank'),
('Vernham Dean'),
('Vernham Dean Gillums'),
('Vernham Grove'),
('Vernham Road'),
('Vernham Row'),
('Vernham Street'),
('Vernham Walk'),
('Vernham Wood'),
('Vernhams Dean'),
('Vernhamwood Close'),
('Vernier Avenue'),
('Vernier Close'),
('Vernier Crescent'),
('Verno Lane'),
('Vernolds Common'),
('Vernolds Coppice'),
('Vernolds Croft'),
('Vernon Avenue'),
('Vernon Bank'),
('Vernon Close'),
('Vernon Corner'),
('Vernon Court'),
('Vernon Crescent'),
('Vernon Delph'),
('Vernon Drive'),
('Vernon Gardens'),
('Vernon Green'),
('Vernon Grove'),
('Vernon Hill'),
('Vernon Lane'),
('Vernon Park'),
('Vernon Park Drive'),
('Vernon Park Road'),
('Vernon Place'),
('Vernon Rise'),
('Vernon Road'),
('Vernon Square'),
('Vernon Street'),
('Vernon Street North'),
('Vernon Terrace'),
('Vernon Villas'),
('Vernon Walk'),
('Vernon Way'),
('Vernon Williams Close'),
('Vernon Wood'),
('Vernon Yard'),
('Vernongate'),
('Vernonholme'),
('Vernons Close'),
('Vernons Copse'),
('Vernons Lane'),
('Vernons Place'),
('Vernons Road'),
('Vernslade'),
('Veroan Road'),
('Veron Point'),
('Verona'),
('Verona Avenue'),
('Verona Close'),
('Verona Court'),
('Verona Drive'),
('Verona Gardens'),
('Verona Grove'),
('Verona Lane'),
('Verona Place'),
('Verona Rise'),
('Verona Road'),
('Verona Street'),
('Verona Way'),
('Veronica Avenue'),
('Veronica Close'),
('Veronica Crescent'),
('Veronica Drive'),
('Veronica Gardens'),
('Veronica House'),
('Veronica Road'),
('Veronica Street'),
('Veronica Walk'),
('Veronica Way'),
('Veronique Gardens'),
('Veronne Drive'),
('Veros Lane'),
('Verrall Close'),
('Verralls'),
('Verralls Wood'),
('Verran Road'),
('Verridge Wood'),
('Verrier Road'),
('Verriers'),
('Verrill Avenue'),
('Verrington'),
('Verrington'),
('Verrington Lane'),
('Verrington Park Road'),
('Verriotts Lane'),
('Verry Geo'),
('Versa Geo'),
('Versailles Gardens'),
('Versailles Road'),
('Versatile Square'),
('Verschoyle Gardens'),
('Versil Terrace'),
('Verstone Croft'),
('Verstone Road'),
('Vert Lane'),
('Vertican Road'),
('Vertish Hill'),
('Verulam'),
('Verulam Avenue'),
('Verulam Close'),
('Verulam Gardens'),
('Verulam Passage'),
('Verulam Place'),
('Verulam Road'),
('Verulam Street'),
('Verulam Way'),
('Vervain Close'),
('Vervan Rocks'),
('Verwey Road'),
('Verwill Lane'),
('Verwood'),
('Verwood Close'),
('Verwood Crescent'),
('Verwood Drive'),
('Verwood East'),
('Verwood Road'),
('Verwood West'),
('Veryan'),
('Veryan Bay'),
('Veryan Churchtown'),
('Veryan Close'),
('Veryan Gardens'),
('Veryan Green'),
('Veryan Place'),
('Veryan Road'),
('Vesalius Street'),
('Vescock Street'),
('Vesey Close'),
('Vesey Court'),
('Vesey Road'),
('Vesey Street'),
('Vesey Trees'),
('Veseys Holehill'),
('Vesker'),
('Vespan Road'),
('Vespasian Close'),
('Vespasian Gardens'),
('Vespasian Road'),
('Vespasian Street'),
('Vespasian Way'),
('Vesper Close'),
('Vesper Court'),
('Vesper Court Drive'),
('Vesper Drive'),
('Vesper Gardens'),
('Vesper Gate Crescent'),
('Vesper Gate Drive'),
('Vesper Gate Mount'),
('Vesper Grove'),
('Vesper Lane'),
('Vesper Mount'),
('Vesper Place'),
('Vesper Rise'),
('Vesper Road'),
('Vesper Street'),
('Vesper Terrace'),
('Vesper Walk'),
('Vesper Way'),
('Vespers Close'),
('Vessacks'),
('Vessey Close'),
('Vessey Hill'),
('Vessey Pasture Belt'),
('Vessey Pasture Dale'),
('Vessey Road'),
('Vessey Terrace'),
('Vest Ness'),
('Vesta Avenue'),
('Vesta Close'),
('Vesta Grove'),
('Vesta Mews'),
('Vesta Quarry'),
('Vesta Road'),
('Vesta Skerry'),
('Vesta Street'),
('Vesta Way'),
('Vestaber'),
('Vestaneum'),
('Vestavirdin Loch'),
('Vester Geos'),
('Vesters Hill Drove'),
('Vestey Court'),
('Vestey Wood'),
('Vestra Fiold'),
('Vestris Drive'),
('Vestris Road'),
('Vestry Close'),
('Vestry Court'),
('Vestry Drive'),
('Vestry Gardens'),
('Vestry Lane'),
('Vestry Mews'),
('Vestry Place'),
('Vestry Road'),
('Vestry Street'),
('Vesty Road'),
('Vesuvian Drive'),
('Vesuvius Drive'),
('Vesuvius Street'),
('Vetch Close'),
('Vetch Field Avenue'),
('Vetch Fields'),
('Vetch Hole Wood'),
('Vetch Park'),
('Vetch Place'),
('Vetch Way'),
('Vetches Downs Plantations'),
('Vetchfield'),
('Vetchfield Close'),
('Vetchwood Gardens'),
('Veteran Close'),
('Veterinary Close'),
('Vetquoy Road'),
('Vettriano Vale'),
('Vevers Bushes'),
('Vevers Road'),
('Vevey Street'),
('Vexation Lane'),
('Vexhim Park'),
('Vexil Close'),
('Veyses End'),
('Veysey Close'),
('Veyseys Wood'),
('Vezey Street'),
('VI Form'),
('Via Gellia'),
('Via Gellia Road'),
('Via Ravenna'),
('Via Romana'),
('Via Urbis Romanae'),
('Viables'),
('Viables Lane'),
('Viadevana'),
('Viador'),
('Viaduct'),
('Viaduct Circle'),
('Viaduct Close'),
('Viaduct Covert'),
('Viaduct Drive'),
('Viaduct Estate Road'),
('Viaduct Hill'),
('Viaduct Lane'),
('Viaduct Place'),
('Viaduct Road'),
('Viaduct Street'),
('Viaduct View'),
('Viaduct Way'),
('Viaduct Wood'),
('Vian Avenue'),
('Vian Close'),
('Vian End'),
('Vian Place'),
('Vian Road'),
('Vian Street'),
('Vian Way'),
('Vianesa Grove'),
('Vias Moss'),
('Vibart Gardens'),
('Vibart Road'),
('Vibernum Rise'),
('Vibia Close'),
('Viborg Gardens'),
('Viburnum Chase'),
('Viburnum Close'),
('Viburnum Court'),
('Viburnum Gate'),
('Viburnum Road'),
('Viburnum View'),
('Viburnum Way'),
('Vicar Crescent'),
('Vicar Hill'),
('Vicar Hill Lane'),
('Vicar Lane'),
('Vicar Park Drive'),
('Vicar Park Road'),
('Vicar Pond'),
('Vicar Road'),
('Vicar Street'),
('Vicar Water Close'),
('Vicar Way'),
('Vicar Wood'),
('Vicarage'),
('Vicarage Avenue'),
('Vicarage Ball'),
('Vicarage Bank'),
('Vicarage Carr'),
('Vicarage Causeway'),
('Vicarage Cliff'),
('Vicarage Close'),
('Vicarage Closes'),
('Vicarage Coppice'),
('Vicarage Copse'),
('Vicarage Court'),
('Vicarage Crescent'),
('Vicarage Croft'),
('Vicarage Drive'),
('Vicarage Drove'),
('Vicarage Farm Close'),
('Vicarage Farm Court'),
('Vicarage Farm Road'),
('Vicarage Farm Yard'),
('Vicarage Field'),
('Vicarage Fields'),
('Vicarage Flats'),
('Vicarage Fold'),
('Vicarage Garden'),
('Vicarage Gardens'),
('Vicarage Gate'),
('Vicarage Gorse'),
('Vicarage Gorse Covert'),
('Vicarage Green'),
('Vicarage Grove'),
('Vicarage Heights'),
('Vicarage Hill'),
('Vicarage Hill Head'),
('Vicarage House'),
('Vicarage Lane'),
('Vicarage Lawn'),
('Vicarage Lawns'),
('Vicarage Meadow'),
('Vicarage Meadows'),
('Vicarage Mews'),
('Vicarage Paddock'),
('Vicarage Park'),
('Vicarage Place'),
('Vicarage Prospect'),
('Vicarage Rise'),
('Vicarage Road'),
('Vicarage Row'),
('Vicarage Shaw'),
('Vicarage Spinney'),
('Vicarage Square'),
('Vicarage Street'),
('Vicarage Terrace'),
('Vicarage View'),
('Vicarage Walk'),
('Vicarage Way'),
('Vicarage Wood'),
('Vicarage Wood Way'),
('Vicarfield Place'),
('Vicarfield Street'),
('Vicarland'),
('Vicarland Place'),
('Vicarland Road'),
('Vicarman Clough'),
('Vicars Allotment'),
('Vicars Brake'),
('Vicars Bridge Close'),
('Vicars Bridge Road'),
('Vicars Close'),
('Vicars Coppice'),
('Vicars Copse'),
('Vicars Court'),
('Vicars Croft'),
('Vicars Cross Road'),
('Vicars Drive'),
('Vicars Fields'),
('Vicars Gardens'),
('Vicars Garth'),
('Vicars Gate'),
('Vicars Grove'),
('Vicars Hall Gardens'),
('Vicars Hall Lane'),
('Vicars Hill'),
('Vicars Lane'),
('Vicars Mews'),
('Vicars Moor Lane'),
('Vicars Moor Wood'),
('Vicars Oak Road'),
('Vicars Orchard'),
('Vicars Pond'),
('Vicars Road'),
('Vicars Rough'),
('Vicars Row'),
('Vicars Street'),
('Vicars Terrace'),
('Vicars Walk'),
('Vicars Wood'),
('Vicarscross'),
('Vicarsfields Road'),
('Vicarsholme Close'),
('Vicarton Street'),
('Vicarwood Avenue'),
('Vicary Close'),
('Vicary Crescent'),
('Vicary Lane'),
('Vicary Street'),
('Vicary Way'),
('Vice Lane'),
('Vicerons Place'),
('Viceroy Close'),
('Viceroy Drive'),
('Viceroy Gardens'),
('Viceroy Road'),
('Viceroy Street'),
('Vichy Close'),
('Vicker Close'),
('Vicker Grove'),
('Vickerman Crescent'),
('Vickerman Street'),
('Vickermans Lane'),
('Vickers Avenue'),
('Vickers Close'),
('Vickers Drive'),
('Vickers Ground'),
('Vickers Lane'),
('Vickers Point'),
('Vickers Road'),
('Vickers Row'),
('Vickers Street'),
('Vickers Way'),
('Vickersdale'),
('Vickerstown'),
('Vickery Close'),
('Vickery Court'),
('Vickery Street'),
('Vickery Way'),
('Vicks Meadow'),
('Victena Road'),
('Victeria terrace'),
('Victop Lay Place'),
('Victor Approach'),
('Victor Avenue'),
('Victor Beamish Avenue'),
('Victor Charles Close'),
('Victor Close'),
('Victor Crescent'),
('Victor Drive'),
('Victor Gardens'),
('Victor Grove'),
('Victor Jackson Avenue'),
('Victor Lane'),
('Victor Mann Street'),
('Victor Mew Close'),
('Victor Park Terrace'),
('Victor Place'),
('Victor Road'),
('Victor Street'),
('Victor Terrace'),
('Victor Walk'),
('Victor Way'),
('Victor Wilde Drive'),
('Victoria'),
('Victoria & Norcross'),
('Victoria Approach'),
('Victoria Avenue'),
('Victoria Avenue East'),
('Victoria Avenue West'),
('Victoria Bay'),
('Victoria Beach'),
('Victoria Belt'),
('Victoria Bridge Road'),
('Victoria Bridge Street'),
('Victoria Buildings'),
('Victoria Care Centre'),
('Victoria Chase'),
('Victoria Circus'),
('Victoria Close'),
('Victoria Clump'),
('Victoria Coach Station'),
('Victoria Common'),
('Victoria Copse'),
('Victoria Cottage'),
('Victoria Cottages'),
('Victoria Court'),
('Victoria Crescent'),
('Victoria Crescent Lane'),
('Victoria Crescent Place'),
('Victoria Crescent Road'),
('Victoria Crescent West'),
('Victoria Cross Road'),
('Victoria Deep Water Terminal'),
('Victoria Dock'),
('Victoria Dock Road'),
('Victoria Docks'),
('Victoria Drive'),
('Victoria Drive East'),
('Victoria Drive West'),
('Victoria East Road'),
('Victoria Education Centre'),
('Victoria Embankment'),
('Victoria Esplanade'),
('Victoria Estate'),
('Victoria Falls'),
('Victoria Falls Road'),
('Victoria Farm Close'),
('Victoria Fields'),
('Victoria Fold'),
('Victoria Gardens'),
('Victoria Garesfield'),
('Victoria Gate'),
('Victoria Gate Gardens'),
('Victoria Glade'),
('Victoria Grange Drive'),
('Victoria Grange Way'),
('Victoria Green'),
('Victoria Grove'),
('Victoria Grove Mews'),
('Victoria Hall Gardens'),
('Victoria Harbour'),
('Victoria Heights'),
('Victoria Hill'),
('Victoria Hill Road'),
('Victoria Hospice'),
('Victoria'),
('Victoria Hospital Annexe'),
('Victoria House'),
('Victoria Infirmary'),
('Victoria Integrated Care Centre'),
('Victoria Jubilee Covert'),
('Victoria Lake'),
('Victoria Lane'),
('Victoria Lawn'),
('Victoria Lodge'),
('Victoria Manor'),
('Victoria Mead'),
('Victoria Meadow'),
('Victoria Memorial'),
('Victoria Mews'),
('Victoria Mill Drive'),
('Victoria Mill Road'),
('Victoria Mills'),
('Victoria Mount'),
('Victoria Orchard'),
('Victoria Osiers'),
('Victoria Parade'),
('Victoria Park'),
('Victoria Park Avenue'),
('Victoria Park Corner'),
('Victoria Park Drive'),
('Victoria Park Gardens'),
('Victoria Park Grove'),
('Victoria Park Lane North'),
('Victoria Park Mount'),
('Victoria Park Neuk'),
('Victoria Park Road'),
('Victoria Park Road East'),
('Victoria Park Road West'),
('Victoria Park Square'),
('Victoria Park Street'),
('Victoria Park View'),
('Victoria Park Way'),
('Victoria Passage'),
('Victoria Place'),
('Victoria Point'),
('Victoria Promenade'),
('Victoria Quadrant'),
('Victoria Quay'),
('Victoria Reservoir'),
('Victoria Retreat'),
('Victoria Rise'),
('Victoria Road'),
('Victoria Rooms'),
('Victoria Row'),
('Victoria Spinney'),
('Victoria Springs'),
('Victoria Square'),
('Victoria Stables'),
('Victoria Station Approach'),
('Victoria Station Road'),
('Victoria Street'),
('Victoria Terrace'),
('Victoria Track'),
('Victoria Vale'),
('Victoria Viaduct'),
('Victoria Village'),
('Victoria Villas'),
('Victoria Walk'),
('Victoria Way'),
('Victoria Wood'),
('Victorian Crescent'),
('Victorian Grove'),
('Victorian Road'),
('Victoriana Way'),
('Victorias Spinney'),
('Victorias Way'),
('Victors Close'),
('Victors Crescent'),
('Victors Drive'),
('Victors Way'),
('Victory Avenue'),
('Victory Belt'),
('Victory Boulevard'),
('Victory Close'),
('Victory Clump'),
('Victory Court'),
('Victory Crescent'),
('Victory Drive'),
('Victory Gardens'),
('Victory Green'),
('Victory Grove'),
('Victory Lane'),
('Victory Park'),
('Victory Park Road'),
('Victory Park Way'),
('Victory Place'),
('Victory Planting'),
('Victory Rise'),
('Victory Road'),
('Victory Road Mews'),
('Victory Square'),
('Victory Street'),
('Victory Street East'),
('Victory Street West'),
('Victory Way'),
('Victory Wood'),
('Victrex Road'),
('Victuals Grove'),
('Vicus Way'),
('Vida Field Stour'),
('Vidgeon Avenue'),
('Vidler Square'),
('Vidlin'),
('Vidlin Loch'),
('Vidlin Ness'),
('Vidlin Voe'),
('Vielstone Wood'),
('Vienenburg Avenue'),
('Vienna Close'),
('Vienna Court'),
('Vienna Grove'),
('Vienna Place'),
('Vienna Road'),
('Vienna Road East'),
('Vienna Street'),
('Vienna Way'),
('Vienne Close'),
('Viennese Road'),
('Viersen Platz'),
('Vieux Close'),
('View Bank'),
('View Close'),
('View Crescent'),
('View Croft Road'),
('View Drive'),
('View Edge'),
('View Forth'),
('View France Close'),
('View Gardens'),
('View Hall Fields'),
('View Island'),
('View Lane'),
('View Mount'),
('View Park Road'),
('View Place'),
('View Point'),
('View Point Road'),
('View Ponds'),
('View Road'),
('View Rock'),
('View Spinney'),
('View Street'),
('View Strip'),
('View Terrace'),
('View Tops'),
('View Tree Close'),
('View Wood'),
('Viewbank'),
('Viewbank Avenue'),
('Viewbank Drive'),
('Viewbank Place'),
('Viewbank Road'),
('Viewbank Street'),
('Viewbank View'),
('Viewcraig Gardens'),
('Viewcraig Street'),
('Viewdales Close'),
('Viewfar Road'),
('Viewfield'),
('Viewfield Avenue'),
('Viewfield Close'),
('Viewfield Court'),
('Viewfield Crescent'),
('Viewfield Drive'),
('Viewfield Gardens'),
('Viewfield Lane'),
('Viewfield Park'),
('Viewfield Place'),
('Viewfield Road'),
('Viewfield Street'),
('Viewfield Terrace'),
('Viewfield Wood'),
('Viewfield Woods'),
('Viewfields'),
('Viewforth'),
('Viewforth Avenue'),
('Viewforth Drive'),
('Viewforth Gardens'),
('Viewforth Place'),
('Viewforth Road'),
('Viewforth Square'),
('Viewforth Street'),
('Viewforth Terrace'),
('Viewglen Court'),
('Viewhill'),
('Viewhill Crescent'),
('Viewhill Meadows'),
('Viewhills Road'),
('Viewie Knowe'),
('Viewing Hill'),
('Viewland Close'),
('Viewland Road'),
('Viewlands'),
('Viewlands Avenue'),
('Viewlands Close'),
('Viewlands Crescent'),
('Viewlands Drive'),
('Viewlands Mount'),
('Viewlands Place'),
('Viewlands Rise'),
('Viewlands Road'),
('Viewlands Road West'),
('Viewlands Terrace'),
('Viewlaw'),
('Viewlaw Lake'),
('Viewley Centre Road'),
('Viewley Hill Avenue'),
('Viewley Wood'),
('Viewly Hill'),
('Viewmount Brae'),
('Viewmount Crescent'),
('Viewmount Drive'),
('Viewmount Road'),
('Viewmount Wood'),
('Viewpark'),
('Viewpark Avenue'),
('Viewpark Close'),
('Viewpark Drive'),
('Viewpark Gardens'),
('Viewpark Glen'),
('Viewpark Place'),
('Viewpark Road'),
('Viewpoint Gate'),
('Viewpoint Place'),
('Viewpoint Road'),
('Views Wood'),
('Viewside Close'),
('Viewy Knowe'),
('Viga Geo'),
('Viga Road'),
('Viga Taing'),
('Vigadale'),
('Vigar Houll'),
('Vigar Stack'),
('Vigar Way'),
('Vigerons Way'),
('Vigers Geo'),
('Viggar Geo'),
('Viggars Place'),
('Viggen Way'),
('Viggory Lane'),
('Vigilance Avenue'),
('Vigilant Close'),
('Vigilant Way'),
('Vignola Terrace'),
('Vignoles Road'),
('Vigo'),
('Vigo Avenue'),
('Vigo Close'),
('Vigo Hill'),
('Vigo Lane'),
('Vigo Place'),
('Vigo Road'),
('Vigo Sprong'),
('Vigo Street'),
('Vigo Terrace'),
('Vigo Village'),
('Vigo Wood'),
('Vigobridge Road'),
('Vigor Close'),
('Vigor Road'),
('Vigornia Avenue'),
('Vigors Croft'),
('Vigrind'),
('Vigus Close'),
('Vihiers Close'),
('Vijay Patel Building'),
('Viking'),
('Viking Avenue'),
('Viking Bay'),
('Viking Close'),
('Viking Court'),
('Viking Crescent'),
('Viking Drive'),
('Viking Gardens'),
('Viking Gas Terminal'),
('Viking Grove'),
('Viking Heights'),
('Viking Meadow'),
('Viking Place'),
('Viking Rise'),
('Viking Road'),
('Viking Street'),
('Viking Terrace'),
('Viking Way'),
('Vikinglea Close'),
('Vikinglea Drive'),
('Vikinglea Glade'),
('Vikinglea Road'),
('Vikings Close'),
('Vikings Court'),
('Vikings Way'),
('Vilberie Close'),
('Vilberie Way'),
('Vildebeest Road'),
('Vile Skerry'),
('Vileneuve St. Georges Way'),
('Viles Park Wood'),
('Vilia Close'),
('Villa Avenue'),
('Villa Bank'),
('Villa Close'),
('Villa Court'),
('Villa Crescent'),
('Villa Dean'),
('Villa Dean Park'),
('Villa Farm'),
('Villa Farm Close'),
('Villa Fields'),
('Villa Gardens'),
('Villa Gloria Close'),
('Villa Grove'),
('Villa Hill'),
('Villa Lane'),
('Villa Mount'),
('Villa Park Road'),
('Villa Place'),
('Villa Pond'),
('Villa Real Estate'),
('Villa Real Road'),
('Villa Rise'),
('Villa Road'),
('Villa Scalabrini'),
('Villa Street'),
('Villa Terrace'),
('Villa View'),
('Villa Walk'),
('Villa Way'),
('Villa Wood'),
('Villacourt Road'),
('Villafield Avenue'),
('Villafield Drive'),
('Villafield Loan'),
('Village Acres'),
('Village Avenue'),
('Village Centre'),
('Village Close'),
('Village Court'),
('Village Courts'),
('Village Croft'),
('Village Cross Road'),
('Village Drive'),
('Village East'),
('Village Farm'),
('Village Farm Close'),
('Village Farm Court'),
('Village Farm Drive'),
('Village Farm Road'),
('Village Fold'),
('Village Garden'),
('Village Garden Mews'),
('Village Gardens'),
('Village Garth'),
('Village Gate'),
('Village Green'),
('Village Green Avenue'),
('Village Green Court'),
('Village Green Lane'),
('Village Green Road'),
('Village Green Way'),
('Village Hall Close'),
('Village Hall Yard'),
('Village Heights'),
('Village Jubilee Orchard'),
('Village Lake'),
('Village Lane'),
('Village Manor'),
('Village Meadow'),
('Village Mews'),
('Village Nook'),
('Village Paddock'),
('Village Park'),
('Village Park Close'),
('Village Place'),
('Village Road'),
('Village Row'),
('Village Spinney'),
('Village Street'),
('Village Terrace'),
('Village View'),
('Village Walks'),
('Village Way'),
('Village Way East'),
('Village Wood'),
('Villagelands Road'),
('Villagers Close'),
('Villarome'),
('Villars Street'),
('Villas Court'),
('Villas Road'),
('Villavon Way'),
('Villdale Avenue'),
('Ville De Paris Road'),
('Ville Road'),
('Villebois Road'),
('Villebon Way'),
('Villeboys Close'),
('Villedomer Wood'),
('Villers Court'),
('Villers View'),
('Villes Lane'),
('Villett Street'),
('Villette Brook Street'),
('Villette Close'),
('Villette Grove'),
('Villette Path'),
('Villette Road'),
('Villice Bay'),
('Villice Lane'),
('Villier Court'),
('Villier Drive'),
('Villier Street'),
('Villiers Avenue'),
('Villiers Close'),
('Villiers Court'),
('Villiers Crescent'),
('Villiers Drive'),
('Villiers Gardens'),
('Villiers Grove'),
('Villiers Lane'),
('Villiers Mead'),
('Villiers Place'),
('Villiers Road'),
('Villiers Russell Close'),
('Villiers Square'),
('Villiers Street'),
('Villiers Way'),
('Villiers-Sur-Marne Avenue'),
('Villigar'),
('Vilner Lane'),
('Viltham Copse'),
('Vilts Coppice'),
('Vilverie Mead'),
('Vimiera Close'),
('Vimoutiers Court'),
('Vimpany Close'),
('Vimpennys Lane'),
('Vimy Avenue'),
('Vimy Close'),
('Vimy Crescent'),
('Vimy Drive'),
('Vimy Ridge'),
('Vimy Road'),
('Vin Field'),
('Vinall Gardens'),
('Vinalls Copse'),
('Vinca Grove'),
('Vincam Close'),
('Vince Close'),
('Vince Dunn Mews'),
('Vince Moor Wood'),
('Vince Street'),
('Vincent'),
('Vincent Avenue'),
('Vincent Carey Road'),
('Vincent Close'),
('Vincent Court'),
('Vincent Crescent'),
('Vincent Drift'),
('Vincent Drive'),
('Vincent Farm Mews'),
('Vincent Gardens'),
('Vincent Grove'),
('Vincent Hills'),
('Vincent Lane'),
('Vincent Mews'),
('Vincent Parade'),
('Vincent Pits'),
('Vincent Place'),
('Vincent Rise'),
('Vincent Road'),
('Vincent Row'),
('Vincent Square'),
('Vincent Street'),
('Vincent Terrace'),
('Vincent View'),
('Vincent Way'),
('Vincent Wood'),
('Vincents Close'),
('Vincents Grove'),
('Vincents Lake'),
('Vincents Road'),
('Vincents Walk'),
('Vincents Way'),
('Vincents Wood'),
('Vincenzo Close'),
('Vincenzo Lunardi Place'),
('Vinces Court'),
('Vinces Road'),
('Vincients Road'),
('Vincit Street'),
('Vinculum Way'),
('Vindelis Way'),
('Vindex Close'),
('Vindomis Close'),
('Vindomora Road'),
('Vine Acre'),
('Vine Avenue'),
('Vine Bank'),
('Vine Bank Road'),
('Vine Close'),
('Vine Coppice'),
('Vine Court'),
('Vine Court Road'),
('Vine Crescent'),
('Vine Drive'),
('Vine End'),
('Vine Farm'),
('Vine Farm Close'),
('Vine Farm Road'),
('Vine Farm Yard'),
('Vine Fold'),
('Vine Gardens'),
('Vine Garth'),
('Vine Geo'),
('Vine Grove'),
('Vine Grove Court'),
('Vine Grove Gardens'),
('Vine Hill'),
('Vine Hill Close'),
('Vine Hill Drive'),
('Vine House Close'),
('Vine House Gardens'),
('Vine Lands'),
('Vine Lane'),
('Vine Mews'),
('Vine Moor'),
('Vine Orchard'),
('Vine Park Avenue'),
('Vine Park Drive'),
('Vine Passage'),
('Vine Place'),
('Vine Road'),
('Vine Row'),
('Vine Square'),
('Vine Street'),
('Vine Street Bridge'),
('Vine Terrace'),
('Vine Tree Avenue'),
('Vine Tree Close'),
('Vine Tree Court'),
('Vine Tree Terrace'),
('Vine Walk'),
('Vine Way'),
('Vine Wood'),
('Vine Yard'),
('Vinebank Street'),
('Vineburgh Avenue'),
('Vineburgh Court'),
('Vinecote Road'),
('Vinefield Court'),
('Vinefields'),
('Vinegar Cove'),
('Vinegar Hill'),
('Vinegar Lane'),
('Vinegar Spring'),
('Vinegar Street'),
('Vinegar Yard'),
('Vinegars Shaw'),
('Vinegarth'),
('Vinehall Close'),
('Vinehall Forest'),
('Vinehall Road'),
('Vinehall Street'),
('Vinehouse Close'),
('Viner Close'),
('Viner Way'),
('Vineries Bank'),
('Vineries Close'),
('Viners Close'),
('Viners Lane'),
('Viners Wood'),
('Vinery Avenue'),
('Vinery Close'),
('Vinery Court'),
('Vinery Gardens'),
('Vinery Grove'),
('Vinery Lane'),
('Vinery Meadow'),
('Vinery Mount'),
('Vinery Park'),
('Vinery Place'),
('Vinery Road'),
('Vinery Street'),
('Vinery Terrace'),
('Vinery View'),
('Vinery Way'),
('Vinery Wood'),
('Vines Avenue'),
('Vines Brake'),
('Vines Court'),
('Vines Cross'),
('Vines Cross Road'),
('Vines Gate Shaw'),
('Vines Lane'),
('Vines Place'),
('Vinescroft'),
('Vinesend Lane'),
('Vineside'),
('Vineside Road'),
('Vinesse Road'),
('Vineton Place'),
('Vinetrees'),
('Viney Avenue'),
('Viney Bank'),
('Viney Close'),
('Viney Hill'),
('Viney Lane'),
('Viney Road'),
('Viney Street'),
('Viney Wood'),
('Vineyard'),
('Vineyard Avenue'),
('Vineyard Bottom'),
('Vineyard Close'),
('Vineyard Clump'),
('Vineyard Coppice'),
('Vineyard Copse'),
('Vineyard Cottages'),
('Vineyard Court'),
('Vineyard Crescent'),
('Vineyard Drive'),
('Vineyard Gate'),
('Vineyard Grove'),
('Vineyard Hill'),
('Vineyard Hill Road'),
('Vineyard Lane'),
('Vineyard Path'),
('Vineyard Place'),
('Vineyard Road'),
('Vineyard Row'),
('Vineyard Shaw'),
('Vineyard Spring'),
('Vineyard Street'),
('Vineyard Vale'),
('Vineyard Walk'),
('Vineyard Way'),
('Vineyard Wood'),
('Vineyards Brake'),
('Vineyards Close'),
('Vineyards Lane'),
('Vineyards Road'),
('Vineyards Wood'),
('Vineycroft Lane'),
('Vineys Copse'),
('Vineys Gardens'),
('Vineys Wood'),
('Vineys Yard'),
('Vingoes Lane'),
('Vingsteen'),
('Vinicombe Lane'),
('Vinicombe Street'),
('Vining Common'),
('Vining Copse'),
('Vining Road'),
('Vining Street'),
('Vining Walk'),
('Vinings Gardens'),
('Vinings Hill'),
('Vinings Road'),
('Vink'),
('Vinlake Avenue'),
('Vinnall Grove'),
('Vinnells Lane'),
('Vinnells Wood'),
('Vinnetrow Lake'),
('Vinnetrow Road'),
('Vinney Copse'),
('Vinney Lane'),
('Vinney Ridge Inclosure'),
('Vinneys Close'),
('Vinnick Rock'),
('Vinnicombes Covert'),
('Vinnicombes Road'),
('Vinns Lane'),
('Vinny Avenue'),
('Vinny Combe'),
('Vinny Den'),
('Vinny Green'),
('Vinovia Place'),
('Vinquin Hill'),
('Vinquoy Hill'),
('Vins Geo'),
('Vins Taing'),
('Vinson Close'),
('Vinson Road'),
('Vinstone Way'),
('Vinstra Close'),
('Vinstrick Ness'),
('Vint Crescent'),
('Vint Rise'),
('Vintage Close'),
('Vintage Mews'),
('Vinten Close'),
('Vinter Terrace'),
('Vinters Avenue'),
('Vinters Park'),
('Vinters Road'),
('Vinters Way'),
('Vintery Leys'),
('Vinthill Withy Bed'),
('Vintin Lane'),
('Vintner Close'),
('Vintner Road'),
('Vintners Close'),
('Vintners Court'),
('Vintners Mews'),
('Vintners Way'),
('Vintry'),
('Vintry Mews'),
('Vinyard Close'),
('Vinyl Place'),
('Viol Moor'),
('Viola Avenue'),
('Viola Bank'),
('Viola Close'),
('Viola Crescent'),
('Viola Croft'),
('Viola Drive'),
('Viola Place'),
('Viola Road'),
('Viola Square'),
('Viola Street'),
('Viola Way'),
('Violet Avenue'),
('Violet Bank'),
('Violet Bank Road'),
('Violet Close'),
('Violet Court'),
('Violet Crescent'),
('Violet Croft'),
('Violet Drive'),
('Violet Farm Close'),
('Violet Gardens'),
('Violet Grove'),
('Violet Hill'),
('Violet Hill Clump'),
('Violet Hill Copse'),
('Violet Hill Road'),
('Violet Lane'),
('Violet Place'),
('Violet Road'),
('Violet Row'),
('Violet Spinney'),
('Violet Street'),
('Violet Street North'),
('Violet Strip'),
('Violet Walk'),
('Violet Way'),
('Violet Wood'),
('Violeta Crescent'),
('Violets Close'),
('Violets Lane'),
('Violets Spring'),
('Violets Wood'),
('Viper Hall Wood'),
('Viper Wood'),
('Vipersmoor Wood'),
('Vipoints Hill'),
('Vir Vaa'),
('Virda'),
('Virda Dale'),
('Virda Field'),
('Virda Geo'),
('Virda Loch'),
('Virda Pund'),
('Virda Vatn'),
('Virda Water'),
('Virdi Field'),
('Virdi Geos'),
('Virdi Point'),
('Virdi Taing'),
('Virdi Water'),
('Virdik'),
('Virdins'),
('Vire Island'),
('Virgate'),
('Virgil Court'),
('Virgil Drive'),
('Virgil Place'),
('Virgil Road'),
('Virgil Street'),
('Virgin Hill'),
('Virgin Hill Wood'),
('Virgin Moss'),
('Virgin Square'),
('Virgin Street'),
('Virginia'),
('Virginia Avenue'),
('Virginia Chase'),
('Virginia Close'),
('Virginia Court'),
('Virginia Crescent'),
('Virginia Drive'),
('Virginia Gardens'),
('Virginia Grove'),
('Virginia Orchard'),
('Virginia Park Road'),
('Virginia Place'),
('Virginia Road'),
('Virginia Street'),
('Virginia Water'),
('Virginia Water Plantations'),
('Virginia Way'),
('Virginia Wood'),
('Virgins Corner Wood'),
('Virgins Croft'),
('Virgins Lane'),
('Virgins Spring'),
('Virginsalley Lane'),
('Virginstow'),
('Virgintree Wood'),
('Viridian Mews'),
('Viridian Square'),
('Viridor Wood'),
('Virley'),
('Virley Channel'),
('Virley Close'),
('Virnells Copse'),
('Virtle Rock'),
('Virtue Close'),
('Virtue Well View'),
('Virtuewell Glen'),
('Virva'),
('Virworthy'),
('Visa View'),
('Viscar'),
('Viscount Avenue'),
('Viscount Close'),
('Viscount Court'),
('Viscount Drive'),
('Viscount Evan Drive'),
('Viscount Gardens'),
('Viscount Gate'),
('Viscount Grove'),
('Viscount Mews'),
('Viscount Road'),
('Viscount Square'),
('Viscount Street'),
('Viscount Terrace'),
('Viscount Walk'),
('Viscount Way'),
('Viscounts Pend'),
('Vishall Hill'),
('Vishwell Road'),
('Vision Hill Road'),
('Vision Terrace'),
('Vision West Nottinghamshire Collegre'),
('Visitors Hill'),
('Vislok Close'),
('Vissett Close'),
('Vissitt Lane'),
('Vista Avenue'),
('Vista Close'),
('Vista Court'),
('Vista Drive'),
('Vista Green'),
('Vista Rise'),
('Vista Road'),
('Vista Way'),
('Vista-Del-Mar'),
('Vistavird'),
('Vistula Crescent'),
('Vita Road'),
('Vitali Close'),
('Vitellius Gardens'),
('Vitesse Road'),
('Vitland Wood'),
('Vitllus Close'),
('Vitre Gardens'),
('Vitriol Square'),
('Vitruvius Court'),
('Vitruvius Way'),
('Vittery Close'),
('Vittle Drive'),
('Vittoria Close'),
('Vittoria Dock'),
('Vittoria Street'),
('Vittoria Walk'),
('Viva Way'),
('Vivaldi Close'),
('Vivaldi Court'),
('Vivaldi Drive'),
('Vivars Way'),
('Vivary Bridge'),
('Vivary Road'),
('Vivary Way'),
('Vivash Road'),
('Viveash Close'),
('Viveham'),
('Viveham Wood'),
('Viver'),
('Viver Green'),
('Viver Lane'),
('Viverdon Down'),
('Vivers Hill'),
('Vivers Place'),
('Vivian Avenue'),
('Vivian Close'),
('Vivian Comma Close'),
('Vivian Court'),
('Vivian Crescent'),
('Vivian Drive'),
('Vivian Gardens'),
('Vivian Park'),
('Vivian Park Drive'),
('Vivian Place'),
('Vivian Road'),
('Vivian Square'),
('Vivian Street'),
('Vivian Terrace'),
('Vivian Way'),
('Vivians Covert'),
('Vivians Wood'),
('Vivid Approach'),
('Vivien Avenue'),
('Vivien Close'),
('Vivien Road'),
('Vivienne Close'),
('Vivienne Cohen House'),
('Vivienne Smith Lane'),
('Vivilie Loch'),
('Vivis Lane'),
('Vivod Mountain'),
('Vixen Close'),
('Vixen Court'),
('Vixen Drive'),
('Vixen Grove'),
('Vixen Gully'),
('Vixen Tor'),
('Vixen Tor Close'),
('Vixen Track'),
('Vixen Walk'),
('Vixen Way'),
('Viyella Gardens'),
('Viyella Mews'),
('Vizard Close'),
('Vizard Road'),
('Vize Lane'),
('Vlissingen Drive'),
('Voake Close'),
('Voases Close'),
('Voases Lane'),
('Vobster'),
('Vobster Hill'),
('Voce Gardens'),
('Voce Road'),
('Voces Lane'),
('Vochums Cleuch'),
('Vockins Close'),
('Vocus Copse'),
('Voder'),
('Voder View'),
('Vodmore Copse'),
('Vodo Meadow'),
('Voe'),
('Voe Botn'),
('Voe Drus'),
('Voe of Browland'),
('Voe of Clousta'),
('Voe of Cullingsburgh'),
('Voe of Dale'),
('Voe of Footabrough'),
('Voe of Leiraness'),
('Voe of Littlure'),
('Voe of North House'),
('Voe of Rumble'),
('Voe of Scatsta'),
('Voe of Setter'),
('Voe of Snarraness'),
('Voe of Sound'),
('Voe of the Brig'),
('Voe of the Mels'),
('Voe of Vaila'),
('Voel Road'),
('Voel-y-crio'),
('Voelas Street'),
('Voes Bottom'),
('Voewood Close'),
('Vog Minn'),
('Vog Skerry'),
('Vogan Avenue'),
('Vogan Close'),
('Vogans Point'),
('Vogans Voe'),
('Vogrie Crescent'),
('Vogrie Place'),
('Vogrie Road'),
('Vogue'),
('Vogue Beloth'),
('Vogue Close'),
('Vogue Hill'),
('Vogus Lane'),
('Vogwell Down'),
('Voice Road'),
('Voil Drive'),
('Voil Road'),
('Voils Grove'),
('Voisey Close'),
('Vokes Close'),
('Vokes Street'),
('Vokes Way'),
('Volage Court'),
('Volans Drive'),
('Volans Lane'),
('Volante Close'),
('Volante Drive'),
('Volary Grove'),
('Volcanic Dyke'),
('Vole'),
('Vole Close'),
('Vole Court'),
('Vole Road'),
('Voley'),
('Voley Close'),
('Voley Lane'),
('Volis Hill'),
('Volla Wood'),
('Vollans Court'),
('Vollards Lane'),
('Vollature Wood'),
('Voller Drive'),
('Vollgastell'),
('Vollum Rise'),
('Vollum Street'),
('Volpe Close'),
('Volri Geo'),
('Volridge Copse'),
('Volt Avenue'),
('Volta Close'),
('Volta Rise'),
('Volta Road'),
('Volta Street'),
('Volta Way'),
('Voltaire Avenue'),
('Voltaire Road'),
('Voltigeur Drive'),
('Voluntary Place'),
('Volunteer Avenue'),
('Volunteer Close'),
('Volunteer Fields'),
('Volunteer Road'),
('Volunteer Street'),
('Volunteer Way'),
('Volunteers Green'),
('Volunteers Wood'),
('Volwycke Avenue'),
('Vomit Point'),
('Vong Lane'),
('Vongs'),
('Voorburg Road'),
('Vord Hill'),
('Vorda Road'),
('Vorfield Close'),
('Vorley Road'),
('Vorlich Avenue'),
('Vorlich Court'),
('Vorlich Crescent'),
('Vorlich Drive'),
('Vorlich Place'),
('Vorlich Road'),
('Vorlich Way'),
('Voronzoff Wood'),
('Vorrap'),
('Vorrap Zawn'),
('Vortex Road'),
('Voryn Avenue'),
('Vose Close'),
('Vosper Croft'),
('Vosper Road'),
('Vosporth Hill'),
('Voss Court'),
('Voss Park Close'),
('Voss Park Drive'),
('Voss Street'),
('Vosss Lane'),
('Vosss Moor'),
('Vostock Close'),
('Voter Run'),
('Votersay'),
('Voulsdon Copse'),
('Voulters Wood'),
('Vounder Close'),
('Vounder Glaze'),
('Voundervour Lane'),
('Vounog Hill'),
('Vow Randie'),
('Vowchurch'),
('Vowchurch Close'),
('Vowchurch Common'),
('Vowchurch Road'),
('Vowchurch Way'),
('Vowell Close'),
('Vowels Lane'),
('Vowes Gorse'),
('Vowler Road'),
('Vowles Bottom'),
('Vowles Close'),
('Vowles Road'),
('Vowley'),
('Vowley View'),
('Vownog'),
('Vownog Newydd'),
('Voxhills Copse'),
('Voxter'),
('Voxter Ness'),
('Voxter Voe'),
('Voxwell Lane'),
('Voxwill Copse'),
('Voy'),
('Voyage Road'),
('Voyager Close'),
('Voyager Drive'),
('Voyager Park North'),
('Voyagers Close'),
('Voyce Close'),
('Voyce Way'),
('Voylart Close'),
('Voylart Road'),
('Voysey Avenue'),
('Voysey Court'),
('Voysey Gardens'),
('Voysey Hill'),
('Voysey Place'),
('Voyseycombe Wood'),
('Vrackie Place'),
('Vriskaig Point'),
('Vroe'),
('Vron Close'),
('Vron Gate'),
('Vron Square'),
('Vron Vellin Wood'),
('Vron Wood'),
('Vroncysyllte'),
('Vronhill Close'),
('Vroning Coppice'),
('Vronladies Wood'),
('Vryburg Close'),
('Vryburg Crescent'),
('Vuefield Hill'),
('Vugga Cove'),
('Vulcan Close'),
('Vulcan Court'),
('Vulcan Crescent'),
('Vulcan Croft'),
('Vulcan Drive'),
('Vulcan Gardens'),
('Vulcan Gate'),
('Vulcan Mews'),
('Vulcan Park Way'),
('Vulcan Place'),
('Vulcan Road'),
('Vulcan Street'),
('Vulcan Terrace'),
('Vulcan View'),
('Vulcan Village'),
('Vulcan Way'),
('Vulcans Lane'),
('Vulscombe Lane'),
('Vulscombe Wood'),
('Vyces Road'),
('Vyne Close'),
('Vyne Crescent'),
('Vyne Meadow'),
('Vyne Road'),
('Vyne Walk'),
('Vyner Close'),
('Vyner Croft'),
('Vyner Grove'),
('Vyner Park'),
('Vyner Place'),
('Vyner Road'),
('Vyner Street'),
('Vyners Close'),
('Vyners Way'),
('Vynes Close'),
('Vynes Way'),
('Vyrnwy Close'),
('Vyrnwy Crescent'),
('Vyrnwy Grove'),
('Vyrnwy'),
('Vyrnwy Place'),
('Vyrnwy Road'),
('Vyrnwy Street'),
('Vyrnwy Way'),
('Vyse Close'),
('Vyse Drive'),
('Vyse Lane'),
('Vyse Road'),
('Vyse Street'),
('Vyse Wood'),
('Vyvyan Court'),
('Vyvyan Drive'),
('Vyvyan Place'),
('Vyvyan Road'),
('Vyvyan Spinney'),
('Vyvyan Street'),
('Vyvyan Terrace'),
('Vacoas-Phoenix'),
('Vadodara'),
('Valdivia'),
('Valencia'),
('Valenzuela'),
('Valera'),
('Valinhos'),
('Valladolid'),
('Valle de Chalco'),
('Valledupar'),
('Vallejo'),
('Valparaíso de Goiás'),
('Valparaíso'),
('Valsad'),
('Van'),
('Vancouver'),
('Vantaa'),
('Vapi'),
('Varamin'),
('Varanasi'),
('Varginha'),
('Varna'),
('Várzea Grande'),
('Várzea Paulista'),
('Vasai-Virar'),
('Västerås'),
('Vaughan'),
('Veliky Novgorod'),
('Vellore'),
('Venlo'),
('Veracruz'),
('Veraval'),
('Vespasiano'),
('Viamão'),
('Vicente López'),
('Vicenza'),
('Victorville'),
('Vidisha'),
('Vienna'),
('Vientiane'),
('Vihiga'),
('Vijayawada'),
('Vila Nova de Gaia'),
('Vila Velha'),
('Villa Alemana'),
('Villa Nueva'),
('Villahermosa'),
('Villanueva'),
('Villavicencio'),
('Villeurbanne'),
('Vilnius'),
('Viña del Mar'),
('Vinh'),
('Vinnytsia'),
('Viranşehir'),
('Virginia Beach'),
('Visakhapatnam'),
('Visalia'),
('Vitebsk'),
('Vitória da Conquista'),
('Vitória de Santo Antão'),
('Vitória'),
('Vitoria-Gasteiz'),
('Vizianagaram'),
('Vladikavkaz'),
('Vladimir'),
('Vladivostok'),
('Vlorë'),
('Volgodonsk'),
('Volgograd'),
('Vologda'),
('Volos'),
('Volta Redonda'),
('Volzhsky'),
('Voronezh'),
('Vosloorus'),
('Votorantim'),
('Vũng Tàu'),
('Vadill'),
('Vadills'),
('Valder'),
('Valdoe'),
('Vale'),
('Vale House'),
('Vale of Grwyney'),
('Vale Uxbridge Road'),
('Vallance'),
('Valley Green'),
('Valleys Nursing Home'),
('Valls'),
('Var'),
('Vatch'),
('Vauld'),
('Vauntie'),
('Vennel'),
('Vennings'),
('Ventry'),
('Vere'),
('Verlands'),
('Verne'),
('Verneys'),
('Veshels'),
('Vetches'),
('Vian'),
('Viels'),
('Vilage'),
('Villa'),
('Village Barn'),
('Village Belt'),
('Village Close'),
('Village Nursing Home'),
('Village Street'),
('Vinefields'),
('Vineries'),
('Vineway'),
('Vintners'),
('Vintry'),
('Violet'),
('Violets'),
('Vir'),
('Voes'),
('Voute'),
('Vro'),
('Vroe'),
('Vron'),
('Vyne');

-- Down
DELETE FROM "Placename" WHERE "keyword" LIKE 'v%';
