-- Up
INSERT INTO Placename (keyword)
VALUES
('Vaa Geo'),
('Vaagen'),
('Vaagso'),
('Vaakel Craigs'),
('Vaal'),
('Vaasetter'),
('Vache'),
('Vachel'),
('Vachelich'),
('Vachell'),
('Vacherie'),
('Vachery'),
('Vacoas Phoenix'),
('Vacye'),
('Vadament Stack'),
('Vadill'),
('Vadill of Garth'),
('Vadills'),
('Vadis'),
('Vadna Geo'),
('Vadna Taing'),
('Vadne'),
('Vadodara'),
('Vaendre'),
('Vaga'),
('Vagaland'),
('Vagar'),
('Vagarth'),
('Vagg'),
('Vaggs'),
('Vaggs Hill Bushes'),
('Vahler'),
('Vai Voe'),
('Vaila'),
('Vaila Sound'),
('Vailan'),
('Vaile'),
('Vaillant'),
('Vaindre'),
('Vainor'),
('Vair Geo'),
('Vaisey'),
('Vaitam'),
('Vakel of Baagie'),
('Val'),
('Val Ayre'),
('Val Prinseps'),
('Valaberg'),
('Valan Leas'),
('Valance'),
('Valanders'),
('Valarian'),
('Valasay'),
('Valbourne'),
('Vald Skerries'),
('Valda'),
('Valda Vale'),
('Valdene'),
('Valder'),
('Valdetta'),
('Valdivia'),
('Valdoe'),
('Vale'),
('Vale Acre'),
('Vale Community'),
('Vale Down'),
('Vale Edge'),
('Vale Foundary'),
('Vale Head'),
('Vale House'),
('Vale Leaze'),
('Vale Link'),
('Vale of Aylesbury'),
('Vale of Belvoir'),
('Vale of Berkeley'),
('Vale Of Bonny'),
('Vale of Catmose'),
('Vale of Clwyd'),
('Vale of Conwy'),
('Vale of Edale'),
('Vale of Evesham'),
('Vale of Ewyas'),
('Vale of Ffestiniog'),
('Vale of Glamorgan'),
('Vale of Gloucester'),
('Vale of Grwyney'),
('Vale of Health'),
('Vale of Holmesdale'),
('Vale of Kent'),
('Vale of Lanherne'),
('Vale Of Leven District General'),
('Vale of Llangollen'),
('Vale of Mawgan'),
('Vale of Montgomery'),
('Vale of Mowbray'),
('Vale of Neath'),
('Vale of Nightshade'),
('Vale of Pewsey'),
('Vale of Pickering'),
('Vale of Taunton Deane'),
('Vale of Wardour'),
('Vale of White Horse'),
('Vale of York'),
('Vale Owen'),
('Vale Pleasant'),
('Vale Reach'),
('Vale Royal'),
('Vale Side'),
('Vale Top'),
('Vale Uxbridge'),
('Valebridge'),
('Valebrook'),
('Valebrooke'),
('Valehead'),
('Valehouse'),
('Valehouse'),
('Valemount'),
('Valence'),
('Valence Circus'),
('Valencia'),
('Valenciennes'),
('Valency'),
('Valens'),
('Valenta'),
('Valentia'),
('Valentina'),
('Valentine'),
('Valentine Spring'),
('Valentines'),
('Valentines Clump'),
('Valentines Lea'),
('Valentinus'),
('Valentyne'),
('Valenzuela'),
('Valepits'),
('Valera'),
('Valeria'),
('Valerian'),
('Valeridge'),
('Valerie'),
('Valerio'),
('Valeroyal'),
('Valeroyal Cut'),
('Valery'),
('Vales'),
('Valescourt'),
('Valeside'),
('Valestone'),
('Valeswood'),
('Valetta'),
('Valette'),
('Valeview'),
('Valeway'),
('Valewood'),
('Valfreda'),
('Valgreen'),
('Valiant'),
('Valiers'),
('Valingers'),
('Valinhos'),
('Valjean'),
('Valkyrie'),
('Vall Ayre'),
('Valla'),
('Valla Dale'),
('Valla Kames'),
('Valla Ness'),
('Valladale'),
('Valladolid'),
('Vallance'),
('Vallans'),
('Vallansgate'),
('Vallantine'),
('Vallaquie'),
('Vallastrome'),
('Vallay'),
('Valle de Chalco'),
('Valledupar'),
('Vallejo'),
('Vallenders'),
('Vallentin'),
('Vallet'),
('Vallet Covert'),
('Valletort'),
('Vallets'),
('Valletta'),
('Valletts'),
('Valley'),
('Valley Airfield'),
('Valley Belt'),
('Valley Clump'),
('Valley Corner'),
('Valley Covers'),
('Valley Creek'),
('Valley Dam'),
('Valley Dane Shaw'),
('Valley Dene'),
('Valley End House'),
('Valley Field Covert'),
('Valley Fields'),
('Valley Fold'),
('Valley Forge'),
('Valley Garth'),
('Valley Head'),
('Valley Lodge'),
('Valley Manor'),
('Valley Mushroom'),
('Valley New'),
('Valley of Coustry'),
('Valley of Desolation'),
('Valley of Houlland'),
('Valley of Keelhamar'),
('Valley of Koam'),
('Valley of Rocks'),
('Valley of Stones'),
('Valley of the Rocks'),
('Valley of Uraday'),
('Valley Prospect'),
('Valley Side'),
('Valley Truckle'),
('Valley Wash'),
('Valleybank'),
('Valleybridge'),
('Valleybrook'),
('Valleydene'),
('Valleyfield'),
('Valleyfield Top'),
('Valleys'),
('Valleys Shaw'),
('Valleyside'),
('Valleyview'),
('Vallian'),
('Valliant'),
('Vallibus'),
('Valliere'),
('Valliers'),
('Valliers Ness'),
('Valligates'),
('Vallin Ness'),
('Vallings'),
('Vallis'),
('Vallis Vale'),
('Valls'),
('Vallum'),
('Valma Rocks'),
('Valmar'),
('Valmeade'),
('Valmont'),
('Valnay'),
('Valognes'),
('Valon'),
('Valonia'),
('Valor'),
('Valparaíso'),
('Valparaíso de Goiás'),
('Valpy'),
('Valroy'),
('Vals Ness'),
('Valsad'),
('Valsheba'),
('Valti Stack'),
('Valtos'),
('Valtos Rocks'),
('Valuation'),
('Valvedare'),
('Valway'),
('Vambery'),
('Vamh'),
('Vampire'),
('Van'),
('Van Alen'),
('Van Der Bilt'),
('Van Der Breen'),
('Van Diemans'),
('Van Diemans Land'),
('Van Diemens'),
('Van Diemens Land'),
('Van Diemens Pass'),
('Van Dyck'),
('Van Dyke'),
('Van Gogh'),
('Van Mildert'),
('Van Pool'),
('Vanborough'),
('Vanbrough'),
('Vanbrugh'),
('Vanbrugh Fields'),
('Vanburgh'),
('Vance'),
('Vances'),
('Vancouver'),
('Vancouver House'),
('Vancouver Quay'),
('Vanda'),
('Vandeleur'),
('Vandenbury Circle'),
('Vanderbilt'),
('Vanderbyl'),
('Vanderhoot'),
('Vanderlin'),
('Vanderplanks Covert'),
('Vanderville'),
('Vanderwalt'),
('Vandome'),
('Vandon'),
('Vandra'),
('Vandries'),
('Vandyck'),
('Vandyke'),
('Vandyke Cross'),
('Vane'),
('Vane Clump'),
('Vane Hall'),
('Vanehill'),
('Vanes'),
('Vanessa'),
('Vanfield'),
('Vangarde'),
('Vange'),
('Vange Corner'),
('Vange Marshes'),
('Vanguard'),
('Vanguard Chase'),
('Vanguard Circle'),
('Vanguard Wharf'),
('Vanhurst'),
('Vanilla'),
('Vanity'),
('Vanlore'),
('Vann'),
('Vann Lake'),
('Vanna gya'),
('Vanneck'),
('Vanner'),
('Vanners'),
('Vanoc'),
('Vanoli'),
('Vanpost'),
('Vanquish'),
('Vanquisher'),
('Vanrigg'),
('Vans'),
('Vans Gill'),
('Vansittart'),
('Vanston'),
('Vanstone'),
('Vant'),
('Vantaa'),
('Vantage'),
('Vantomme'),
('Vantorts'),
('Vanwall'),
('Vanzell'),
('Vapery'),
('Vapi'),
('Vapron'),
('Var'),
('Vara'),
('Varah'),
('Varamin'),
('Varanasi'),
('Varaquoy'),
('Varchoel'),
('Varco'),
('Varcoe'),
('Vardar'),
('Varden'),
('Vardens'),
('Vardentown'),
('Vardon'),
('Vardon Lea'),
('Vardre'),
('Vardroe'),
('Vardy'),
('Varey'),
('Varfell'),
('Varginha'),
('Varian'),
('Varich'),
('Varis'),
('Varle'),
('Varley'),
('Varley Halls Of Residence'),
('Varley Head'),
('Varley Sand'),
('Varley Vale'),
('Varleys'),
('Varlian'),
('Varlins'),
('Varlow'),
('Varmady'),
('Varme Dale'),
('Varna'),
('Varncombe'),
('Varndean'),
('Varndean Holt'),
('Varndell'),
('Varndells'),
('Varne'),
('Varnes'),
('Varney'),
('Varneys'),
('Varnister'),
('Varnsdorf'),
('Varo'),
('Varos'),
('Varrick'),
('Varrier Jones'),
('Varriers'),
('Vars'),
('Varses'),
('Varsity'),
('Vart'),
('Varteg'),
('Vartenham'),
('Varthen'),
('Vartry'),
('Varvel'),
('Vary'),
('Vary Clump'),
('Vasa'),
('Vasa Loch'),
('Vasai Virar'),
('Vasart'),
('Vaseford'),
('Vasey'),
('Vashon'),
('Vassa'),
('Vassa Voe'),
('Vassall'),
('Vassancro'),
('Vassar'),
('Vasser'),
('Vastern'),
('Vastern Wharf'),
('Vasterne'),
('Vastre'),
('Vat of Kirbuster'),
('Vatch'),
('Vatem'),
('Vatersay'),
('Vati Geo'),
('Vatisker'),
('Vatna Gaet'),
('Vats'),
('Vats houll'),
('Vats houll Voe'),
('Vats Wick'),
('Vatten'),
('Vatten Island'),
('Vattingstone'),
('Vattingstone Brake'),
('Vauban'),
('Vauce'),
('Vaucluse'),
('Vaudeville'),
('Vaudrey'),
('Vaughan'),
('Vaughan Thomas'),
('Vaughan Williams'),
('Vaughans'),
('Vaughn'),
('Vaughton'),
('Vaul'),
('Vauld'),
('Vault'),
('Vault Beach'),
('Vaults'),
('Vaulx'),
('Vaunces'),
('Vauntie'),
('Vauterhill'),
('Vaux'),
('Vauxhall'),
('Vauxhall Centre'),
('Vauxhall Covert'),
('Vauxhall Quay'),
('Vauze'),
('Vauze House'),
('Vavasour'),
('Vavasours Slip'),
('Vawdrey'),
('Vawers'),
('Vawser'),
('Vayne'),
('Vaynol'),
('Vaynol Covert'),
('Vaynol Hall'),
('Vaynor'),
('Vaynor fâch'),
('Vayre'),
('Vayro'),
('Ve Ness'),
('Ve Skerries'),
('Veal'),
('Veale'),
('Vealenia'),
('Veales'),
('Veals'),
('Vean'),
('Vean Hole'),
('Veantrow'),
('Vears'),
('Vearse'),
('Veasey'),
('Veasypark'),
('Veathery Quoy'),
('Vecqueray'),
('Vecta'),
('Vecta House'),
('Vectis'),
('Vector'),
('Veda'),
('Vedal Drove'),
('Vedders Geo'),
('Veddoes'),
('Vedonis'),
('Vedra'),
('Vedrato'),
('Vedri Geo'),
('Vedrick'),
('Vedwllwyd'),
('Vee'),
('Vee Taing'),
('Veeda Stack'),
('Veedie'),
('Veensgarth'),
('Veenston'),
('Veere'),
('Veester'),
('Veevers'),
('Vega'),
('Vegal'),
('Vegas'),
('Veille'),
('Veiny Cheese'),
('Veir'),
('Veitch'),
('Veitches'),
('Veitchs'),
('Vela'),
('Velator'),
('Velda'),
('Velden'),
('Veldene'),
('Velder'),
('Veldo'),
('Veles'),
('Velfrey'),
('Velhurst'),
('Veliky Novgorod'),
('Velindre'),
('Velindre Cancer Centre'),
('Velizy'),
('Vellacott'),
('Vellacotts'),
('Vellan'),
('Vellan Drang'),
('Vellan Head'),
('Vellan Parc'),
('Vellan Vrane'),
('Velland'),
('Vellandrucia'),
('Vellanoweth'),
('Vellator'),
('Velley'),
('Vellin gluz Rocks'),
('Vellore'),
('Vellow'),
('Vellum'),
('Vellus'),
('Velly'),
('Velmead'),
('Velmere'),
('Velmore'),
('Velocette'),
('Velocity'),
('Velour'),
('Velsheda'),
('Velt Hevda'),
('Velthouse'),
('Veltie'),
('Veltie Skerry'),
('Veltieskerry Loch'),
('Veltshaw'),
('Velver'),
('Velvet'),
('Velvet Beds Island'),
('Velvet Hall Strip'),
('Velvet Rock'),
('Velvetere'),
('Velville'),
('Velwell'),
('Velyn'),
('Vementry'),
('Ven Combe'),
('Ven Law'),
('Venables'),
('Venachar'),
('Venalie'),
('Venator'),
('Venborough'),
('Venbridge'),
('Vence'),
('Venchen'),
('Venches Rock'),
('Vencourt'),
('Vendace'),
('Vendace Wynd'),
('Vendale'),
('Vendeen'),
('Vendra Stacks'),
('Venerable'),
('Venericks Cove'),
('Veness'),
('Venesta'),
('Venetia'),
('Venetian'),
('Venette'),
('Venford'),
('Venford'),
('Vengeance'),
('Venges Brake'),
('Venhay Down'),
('Venibar'),
('Venice'),
('Venics'),
('Venison'),
('Veniss'),
('Venlake'),
('Venland'),
('Venlaw'),
('Venlaw High'),
('Venlaw Quarry'),
('Venley'),
('Venlo'),
('Venlock'),
('Venlow'),
('Venmans'),
('Venmore'),
('Venn'),
('Venn Channing'),
('Venn Cross'),
('Venn Dingle'),
('Venn Down'),
('Venn Ottery'),
('Vennacher'),
('Vennal'),
('Vennals'),
('Vennard'),
('Vennaway'),
('Venneit'),
('Vennel'),
('Venner'),
('Venners'),
('Venners Water'),
('Venngreen'),
('Venning'),
('Vennings'),
('Vennington'),
('Vennland'),
('Vennpark'),
('Venns'),
('Venns Acre'),
('Vennwood'),
('Venny'),
('Venny Tedburn'),
('Venom'),
('Venomous Clough'),
('Vensfield'),
('Vensilly'),
('Vensland'),
('Venslooe'),
('Venta'),
('Venterdon'),
('Ventfield'),
('Vention'),
('Ventnor'),
('Ventnor Haven'),
('Ventnor Villas'),
('Vento'),
('Venton'),
('Venton Cove'),
('Venton Lace'),
('Venton Vaden'),
('Venton Vision'),
('Ventongimps'),
('Ventongoose'),
('Ventonhills'),
('Ventonleague'),
('Ventonraze'),
('Ventonwyn'),
('Ventor'),
('Ventress'),
('Ventress Hall'),
('Ventris'),
('Ventry'),
('Ventura'),
('Venture'),
('Venture Avenue Venture'),
('Venture Chase'),
('Venture Scout'),
('Venturefair'),
('Venturefield'),
('Venue'),
('Venus'),
('Venusbank'),
('Venvell'),
('Venwood'),
('Veny'),
('Veor'),
('Veor Cove'),
('Ver'),
('Ver Geo'),
('Vera'),
('Vera Lynn'),
('Vera Roberts'),
('Veracruz'),
('Veralam'),
('Verallo'),
('Verandah'),
('Veras'),
('Veraval'),
('Verax'),
('Verbania'),
('Verbena'),
('Vercor'),
('Vercourt'),
('Verda'),
('Verdala'),
('Verdale'),
('Verdant'),
('Verdant Vale'),
('Verdayne'),
('Verde'),
('Verden'),
('Verder'),
('Verderers'),
('Verdi'),
('Verdin'),
('Verdins Cut'),
('Verdley'),
('Verdon'),
('Verdons'),
('Verdun'),
('Verdure'),
('Vere'),
('Vereker'),
('Vereland'),
('Vereley'),
('Verelst'),
('Verely'),
('Verena'),
('Vereth'),
('Verey'),
('Vergam'),
('Verge'),
('Verger'),
('Vergette'),
('Vergyland Combe'),
('Verica'),
('Veridion'),
('Verig'),
('Verini'),
('Verinia'),
('Veritas'),
('Verity'),
('Verity Spur'),
('Veritys'),
('Verlam'),
('Verland'),
('Verlands'),
('Verley'),
('Verlon'),
('Vermeer'),
('Vermeer Ride'),
('Vermiel'),
('Vermin'),
('Vermin Valley'),
('Vermont'),
('Vermont Standing'),
('Vermuyden'),
('Vermuyden Villas'),
('Vern'),
('Verna'),
('Vernal'),
('Vernalls'),
('Vernatts'),
('Vernditch Chase'),
('Verne'),
('Verner'),
('Verneuil'),
('Verney'),
('Verneys'),
('Vernham'),
('Vernham Dean'),
('Vernham Dean Gillums'),
('Vernhams Dean'),
('Vernhamwood'),
('Vernier'),
('Verno'),
('Vernolds'),
('Vernon'),
('Vernon Corner'),
('Vernon Delph'),
('Vernon Villas'),
('Vernon Williams'),
('Vernongate'),
('Vernonholme'),
('Vernons'),
('Vernslade'),
('Veroan'),
('Veron'),
('Verona'),
('Veronica'),
('Veronica House'),
('Veronique'),
('Veronne'),
('Veros'),
('Verrall'),
('Verralls'),
('Verran'),
('Verridge'),
('Verrier'),
('Verriers'),
('Verrill'),
('Verrington'),
('Verriotts'),
('Verry Geo'),
('Versa Geo'),
('Versailles'),
('Versatile'),
('Verschoyle'),
('Versil'),
('Verstone'),
('Vert'),
('Vertican'),
('Vertish'),
('Verulam'),
('Verulam Passage'),
('Vervain'),
('Vervan Rocks'),
('Verwey'),
('Verwill'),
('Verwood'),
('Veryan'),
('Veryan Churchtown'),
('Vesalius'),
('Vescock'),
('Vesey'),
('Vesey Trees'),
('Veseys Holehill'),
('Veshels'),
('Vesker'),
('Vespan'),
('Vespasian'),
('Vespasiano'),
('Vesper'),
('Vespers'),
('Vessacks'),
('Vessey'),
('Vessey Pasture Belt'),
('Vessey Pasture Dale'),
('Vest Ness'),
('Vesta'),
('Vesta Quarry'),
('Vesta Skerry'),
('Vestaber'),
('Vestaneum'),
('Vestavirdin Loch'),
('Vester Geos'),
('Vesters Hill Drove'),
('Vestey'),
('Vestra Fiold'),
('Vestris'),
('Vestry'),
('Vesty'),
('Vesuvian'),
('Vesuvius'),
('Vetch'),
('Vetch Fields'),
('Vetch Hole'),
('Vetches'),
('Vetches Downs'),
('Vetchfield'),
('Vetchwood'),
('Veteran'),
('Veterinary'),
('Vetquoy'),
('Vettriano Vale'),
('Vevers'),
('Vevers Bushes'),
('Vevey'),
('Vexation'),
('Vexhim'),
('Vexil'),
('Veyses'),
('Veysey'),
('Veyseys'),
('Vezey'),
('Via Gellia'),
('Via Ravenna'),
('Via Romana'),
('Via Urbis Romanae'),
('Viables'),
('Viadevana'),
('Viador'),
('Viaduct'),
('Viaduct Circle'),
('Viaduct Covert'),
('Viamão'),
('Vian'),
('Vianesa'),
('Vias Moss'),
('Vibart'),
('Vibernum'),
('Vibia'),
('Viborg'),
('Viburnum'),
('Viburnum Chase'),
('Vicar'),
('Vicar Water'),
('Vicarage'),
('Vicarage Ball'),
('Vicarage Carr'),
('Vicarage Causeway'),
('Vicarage Cliff'),
('Vicarage Closes'),
('Vicarage Drove'),
('Vicarage Fields'),
('Vicarage Fold'),
('Vicarage Gorse'),
('Vicarage Gorse Covert'),
('Vicarage Hill Head'),
('Vicarage House'),
('Vicarage Paddock'),
('Vicarage Prospect'),
('Vicarage Shaw'),
('Vicarfield'),
('Vicarland'),
('Vicarman Clough'),
('Vicars'),
('Vicars Allotment'),
('Vicars Brake'),
('Vicars Cross'),
('Vicars Fields'),
('Vicars Garth'),
('Vicars Hall'),
('Vicars Oak'),
('Vicars Rough'),
('Vicarscross'),
('Vicarsfields'),
('Vicarsholme'),
('Vicarton'),
('Vicarwood'),
('Vicary'),
('Vice'),
('Vicente López'),
('Vicenza'),
('Vicerons'),
('Viceroy'),
('Vichy'),
('Vicker'),
('Vickerman'),
('Vickermans'),
('Vickers'),
('Vickers Ground'),
('Vickersdale'),
('Vickerstown'),
('Vickery'),
('Vicks'),
('Victena'),
('Victeria'),
('Victop Lay'),
('Victor'),
('Victor Beamish'),
('Victor Charles'),
('Victor Jackson'),
('Victor Mann'),
('Victor Mew'),
('Victor Wilde'),
('Victoria'),
('Victoria Beach'),
('Victoria Belt'),
('Victoria Buildings'),
('Victoria Care Centre'),
('Victoria Chase'),
('Victoria Circus'),
('Victoria Clump'),
('Victoria Cross'),
('Victoria Deep Water'),
('Victoria Dock'),
('Victoria Docks'),
('Victoria Embankment'),
('Victoria Esplanade'),
('Victoria Falls'),
('Victoria Fields'),
('Victoria Fold'),
('Victoria Garesfield'),
('Victoria Glade'),
('Victoria Hall'),

('Victoria House'),
('Victoria Jubilee Covert'),
('Victoria Lake'),
('Victoria Lodge'),
('Victoria Manor'),
('Victoria Memorial'),
('Victoria Osiers'),
('Victoria Park Corner'),
('Victoria Park Neuk'),
('Victoria Passage'),
('Victoria Promenade'),
('Victoria Quadrant'),
('Victoria Quay'),
('Victoria'),
('Victoria Retreat'),
('Victoria Rooms'),
('Victoria Springs'),
('Victoria Stables'),
('Victoria Station'),
('Victoria Track'),
('Victoria Vale'),
('Victoria Viaduct'),
('Victoria Villas'),
('Victorian'),
('Victoriana'),
('Victorias'),
('Victors'),
('Victorville'),
('Victory'),
('Victory Belt'),
('Victory Clump'),
('Victory Planting'),
('Victrex'),
('Victuals'),
('Vicus'),
('Vida Field Stour'),
('Vidgeon'),
('Vidisha'),
('Vidler'),
('Vidlin'),
('Vidlin Loch'),
('Vidlin Ness'),
('Vidlin Voe'),
('Viels'),
('Vielstone'),
('Vienenburg'),
('Vienna'),
('Vienne'),
('Viennese'),
('Vientiane'),
('Viersen Platz'),
('Vieux'),
('View'),
('View Edge'),
('View Forth'),
('View France'),
('View Hall Fields'),
('View Island'),
('View Rock'),
('View Strip'),
('View Tops'),
('View Tree'),
('Viewbank'),
('Viewcraig'),
('Viewdales'),
('Viewfar'),
('Viewfield'),
('Viewfields'),
('Viewforth'),
('Viewglen'),
('Viewhill'),
('Viewhills'),
('Viewie Knowe'),
('Viewing'),
('Viewland'),
('Viewlands'),
('Viewlaw'),
('Viewlaw Lake'),
('Viewley'),
('Viewley Centre'),
('Viewly'),
('Viewmount'),
('Viewpark'),
('Viewpoint'),
('Views'),
('Viewside'),
('Viewy Knowe'),
('Viga'),
('Viga Geo'),
('Viga Taing'),
('Vigadale'),
('Vigar'),
('Vigar Houll'),
('Vigar Stack'),
('Vigerons'),
('Vigers Geo'),
('Viggar Geo'),
('Viggars'),
('Viggen'),
('Viggory'),
('Vigilance'),
('Vigilant'),
('Vignola'),
('Vignoles'),
('Vigo'),
('Vigo Sprong'),
('Vigobridge'),
('Vigor'),
('Vigornia'),
('Vigors'),
('Vigrind'),
('Vigus'),
('Vihiers'),
('Vihiga'),
('Vijay Patel Building'),
('Vijayawada'),
('Viking'),
('Viking Gas Terminal'),
('Vikinglea'),
('Vikinglea Glade'),
('Vikings'),
('Vila Nova de Gaia'),
('Vila Velha'),
('Vilage'),
('Vilberie'),
('Vildebeest'),
('Vile Skerry'),
('Vileneuve St. Georges'),
('Viles'),
('Vilia'),
('Villa'),
('Villa Alemana'),
('Villa Dean'),
('Villa Fields'),
('Villa Gloria'),
('Villa Nueva'),
('Villa Real'),
('Villa Scalabrini'),
('Villacourt'),
('Villafield'),
('Villafield Loan'),
('Village'),
('Village Acres'),
('Village Barn'),
('Village Belt'),
('Village Centre'),
('Village Courts'),
('Village Cross'),
('Village Fold'),
('Village Garth'),
('Village Hall'),
('Village Jubilee'),
('Village Lake'),
('Village Manor'),
('Village Nook'),
('Village Paddock'),
('Village Walks'),
('Villagelands'),
('Villagers'),
('Villahermosa'),
('Villanueva'),
('Villarome'),
('Villars'),
('Villas'),
('Villavicencio'),
('Villavon'),
('Villdale'),
('Ville'),
('Ville De Paris'),
('Villebois'),
('Villebon'),
('Villeboys'),
('Villedomer'),
('Villers'),
('Villes'),
('Villett'),
('Villette'),
('Villeurbanne'),
('Villice'),
('Villier'),
('Villiers'),
('Villiers Russell'),
('Villiers Sur Marne'),
('Villigar'),
('Vilner'),
('Vilnius'),
('Viltham'),
('Vilts'),
('Vilverie'),
('Vimiera'),
('Vimoutiers'),
('Vimpany'),
('Vimpennys'),
('Vimy'),
('Vin'),
('Vinall'),
('Vinalls'),
('Vinca'),
('Vincam'),
('Vince'),
('Vince Dunn'),
('Vincent'),
('Vincent Carey'),
('Vincent Drift'),
('Vincent Hills'),
('Vincent Pits'),
('Vincents'),
('Vincents Lake'),
('Vincenzo'),
('Vincenzo Lunardi'),
('Vinces'),
('Vincients'),
('Vincit'),
('Vinculum'),
('Vindelis'),
('Vindex'),
('Vindomis'),
('Vindomora'),
('Vine'),
('Vine Acre'),
('Vine Fold'),
('Vine Garth'),
('Vine Geo'),
('Vine House'),
('Vine Lands'),
('Vine Passage'),
('Vine Tree'),
('Vinebank'),
('Vineburgh'),
('Vinecote'),
('Vinefield'),
('Vinefields'),
('Vinegar'),
('Vinegar Cove'),
('Vinegar Spring'),
('Vinegars Shaw'),
('Vinegarth'),
('Vinehall'),
('Vinehouse'),
('Viner'),
('Vineries'),
('Viners'),
('Vinery'),
('Vines'),
('Vines Brake'),
('Vines Cross'),
('Vines Gate Shaw'),
('Vinescroft'),
('Vinesend'),
('Vineside'),
('Vinesse'),
('Vineton'),
('Vinetrees'),
('Vineway'),
('Viney'),
('Vineyard'),
('Vineyard Clump'),
('Vineyard Shaw'),
('Vineyard Spring'),
('Vineyard Vale'),
('Vineyards'),
('Vineyards Brake'),
('Vineycroft'),
('Vineys'),
('Vingoes'),
('Vingsteen'),
('Vinh'),
('Vinicombe'),
('Vining'),
('Vinings'),
('Vink'),
('Vinlake'),
('Vinnall'),
('Vinnells'),
('Vinnetrow'),
('Vinnetrow Lake'),
('Vinney'),
('Vinney Ridge Inclosure'),
('Vinneys'),
('Vinnick Rock'),
('Vinnicombes'),
('Vinnicombes Covert'),
('Vinns'),
('Vinny'),
('Vinny Combe'),
('Vinny Den'),
('Vinnytsia'),
('Vinovia'),
('Vinquin'),
('Vinquoy'),
('Vins Geo'),
('Vins Taing'),
('Vinson'),
('Vinstone'),
('Vinstra'),
('Vinstrick Ness'),
('Vint'),
('Vintage'),
('Vinten'),
('Vinter'),
('Vinters'),
('Vintery Leys'),
('Vinthill Withy Bed'),
('Vintin'),
('Vintner'),
('Vintners'),
('Vintry'),
('Vinyard'),
('Vinyl'),
('Viol'),
('Viola'),
('Violet'),
('Violet Hill Clump'),
('Violet Strip'),
('Violeta'),
('Violets'),
('Violets Spring'),
('Viper'),
('Viper Hall'),
('Vipersmoor'),
('Vipoints'),
('Vir'),
('Vir Vaa'),
('Viranşehir'),
('Virda'),
('Virda Dale'),
('Virda Geo'),
('Virda Loch'),
('Virda Pund'),
('Virda Vatn'),
('Virda Water'),
('Virdi'),
('Virdi Geos'),
('Virdi Taing'),
('Virdi Water'),
('Virdik'),
('Virdins'),
('Vire Island'),
('Virgate'),
('Virgil'),
('Virgin'),
('Virgin Moss'),
('Virginia'),
('Virginia Beach'),
('Virginia Chase'),
('Virginia Water'),
('Virgins'),
('Virgins Corner'),
('Virgins Spring'),
('Virginsalley'),
('Virginstow'),
('Virgintree'),
('Viridian'),
('Viridor'),
('Virley'),
('Virley Channel'),
('Virnells'),
('Virtle Rock'),
('Virtue'),
('Virtue Well'),
('Virtuewell'),
('Virva'),
('Virworthy'),
('Visa'),
('Visakhapatnam'),
('Visalia'),
('Viscar'),
('Viscount'),
('Viscount Evan'),
('Viscounts Pend'),
('Vishall'),
('Vishwell'),
('Vision'),
('Vision West Nottinghamshire Collegre'),
('Visitors'),
('Vislok'),
('Vissett'),
('Vissitt'),
('Vista'),
('Vista Del Mar'),
('Vistavird'),
('Vistula'),
('Vita'),
('Vitali'),
('Vitebsk'),
('Vitellius'),
('Vitesse'),
('Vitland'),
('Vitllus'),
('Vitoria Gasteiz'),
('Vitre'),
('Vitriol'),
('Vitruvius'),
('Vittery'),
('Vittle'),
('Vittoria'),
('Vittoria Dock'),
('Vitória'),
('Vitória da Conquista'),
('Vitória de Santo Antão'),
('Viva'),
('Vivaldi'),
('Vivars'),
('Vivary'),
('Vivash'),
('Viveash'),
('Viveham'),
('Viver'),
('Viverdon Down'),
('Vivers'),
('Vivian'),
('Vivian Comma'),
('Vivians'),
('Vivians Covert'),
('Vivid'),
('Vivien'),
('Vivienne'),
('Vivienne Cohen House'),
('Vivienne Smith'),
('Vivilie Loch'),
('Vivis'),
('Vivod Mountain'),
('Vixen'),
('Vixen Gully'),
('Vixen Tor'),
('Vixen Track'),
('Viyella'),
('Vizard'),
('Vize'),
('Vizianagaram'),
('Viña del Mar'),
('Vladikavkaz'),
('Vladimir'),
('Vladivostok'),
('Vlissingen'),
('Vlorë'),
('Voake'),
('Voases'),
('Vobster'),
('Voce'),
('Voces'),
('Vochums Cleuch'),
('Vockins'),
('Vocus'),
('Voder'),
('Vodmore'),
('Vodo'),
('Voe'),
('Voe Botn'),
('Voe Drus'),
('Voe of Browland'),
('Voe of Clousta'),
('Voe of Cullingsburgh'),
('Voe of Dale'),
('Voe of Footabrough'),
('Voe of Leiraness'),
('Voe of Littlure'),
('Voe of North House'),
('Voe of Rumble'),
('Voe of Scatsta'),
('Voe of Setter'),
('Voe of Snarraness'),
('Voe of Sound'),
('Voe of the Brig'),
('Voe of the Mels'),
('Voe of Vaila'),
('Voel'),
('Voel y crio'),
('Voelas'),
('Voes'),
('Voewood'),
('Vog Minn'),
('Vog Skerry'),
('Vogan'),
('Vogans'),
('Vogans Voe'),
('Vogrie'),
('Vogue'),
('Vogue Beloth'),
('Vogus'),
('Vogwell Down'),
('Voice'),
('Voil'),
('Voils'),
('Voisey'),
('Vokes'),
('Volage'),
('Volans'),
('Volante'),
('Volary'),
('Volcanic Dyke'),
('Vole'),
('Voley'),
('Volgodonsk'),
('Volgograd'),
('Volis'),
('Volla'),
('Vollans'),
('Vollards'),
('Vollature'),
('Voller'),
('Vollgastell'),
('Vollum'),
('Vologda'),
('Volos'),
('Volpe'),
('Volri Geo'),
('Volridge'),
('Volt'),
('Volta'),
('Volta Redonda'),
('Voltaire'),
('Voltigeur'),
('Voluntary'),
('Volunteer'),
('Volunteer Fields'),
('Volunteers'),
('Volwycke'),
('Volzhsky'),
('Vomit'),
('Vong'),
('Vongs'),
('Voorburg'),
('Vord'),
('Vorda'),
('Vorfield'),
('Vorley'),
('Vorlich'),
('Voronezh'),
('Voronzoff'),
('Vorrap'),
('Vorrap Zawn'),
('Vortex'),
('Voryn'),
('Vose'),
('Vosloorus'),
('Vosper'),
('Vosporth'),
('Voss'),
('Vosss'),
('Vostock'),
('Voter Run'),
('Votersay'),
('Votorantim'),
('Voulsdon'),
('Voulters'),
('Vounder'),
('Vounder Glaze'),
('Voundervour'),
('Vounog'),
('Voute'),
('Vow Randie'),
('Vowchurch'),
('Vowell'),
('Vowels'),
('Vowes Gorse'),
('Vowler'),
('Vowles'),
('Vowley'),
('Vownog'),
('Vownog Newydd'),
('Voxhills'),
('Voxter'),
('Voxter Ness'),
('Voxter Voe'),
('Voxwell'),
('Voxwill'),
('Voy'),
('Voyage'),
('Voyager'),
('Voyagers'),
('Voyce'),
('Voylart'),
('Voysey'),
('Voyseycombe'),
('Vrackie'),
('Vriskaig'),
('Vro'),
('Vroe'),
('Vron'),
('Vron Vellin'),
('Vroncysyllte'),
('Vronhill'),
('Vroning'),
('Vronladies'),
('Vryburg'),
('Vuefield'),
('Vugga Cove'),
('Vulcan'),
('Vulcans'),
('Vulscombe'),
('Vyces'),
('Vyne'),
('Vyner'),
('Vyners'),
('Vynes'),
('Vyrnwy'),
('Vyse'),
('Vyvyan'),
('Várzea Grande'),
('Várzea Paulista'),
('Västerås'),
('Vũng Tàu');
-- Down
DELETE FROM Placename WHERE keyword LIKE 'v%';