-- Up
INSERT INTO Skip (keyword)
VALUES
('A batch'),
('A bath'),
('A battle'),
('A bill'),
('A black belt'),
('A black hole'),
('A boulder'),
('A bow'),
('A buddy'),
('A cash'),
('A chance'),
('A childs'),
('A christian'),
('A christmas'),
('A clause'),
('A country lane'),
('A deal'),
('A deep pit'),
('A dot'),
('A fairer'),
('A flurry'),
('A gang'),
('A glass'),
('A gorge'),
('A greater'),
('A green'),
('A guy'),
('A heap'),
('A jan'),
('A june'),
('A king'),
('A knock'),
('A lamb'),
('A little less'),
('A little long'),
('A little rough'),
('A loner'),
('A long road'),
('A long walk'),
('A long way'),
('A lower exchange'),
('A mark'),
('A may'),
('A mini'),
('A new house'),
('A page'),
('A pat'),
('A peculiar'),
('A penny'),
('A plant'),
('A postal'),
('A pound'),
('A ridge'),
('A rod'),
('A savanna'),
('A scolding'),
('A shepherd'),
('A smaller'),
('A spike'),
('A steep'),
('A stellar'),
('A story'),
('A tee'),
('A tennis court'),
('A thorn'),
('A walker'),
('A way'),
('A windy'),
('A wise'),
('Accompany the exchange'),
('Achilles heel'),
('Ad hoc'),
('Affiliated boards'),
('After the court'),
('Against the wall'),
('Akin to'),
('Albeit smaller'),
('All roses'),
('All stripes'),
('All the pieces'),
('All the points'),
('All the wood'),
('All tier'),
('All westward'),
('Alls well'),
('Along the path'),
('Alpha male'),
('Also rose'),
('Also wear'),
('Always wear'),
('Am holding'),
('Am leary'),
('Amber warning'),
('Amber warnings'),
('Among young'),
('An april'),
('An over'),
('And bonds'),
('And dizzy'),
('And green'),
('And hedging'),
('And holding'),
('And mingle'),
('And snow'),
('And trucks'),
('Another chance'),
('Any deal'),
('Any page'),
('Any pressing'),
('Any reading'),
('Any winnings'),
('Appeal court'),
('Ardent in'),
('Are angels'),
('Are down'),
('Are greater'),
('Are holding'),
('Are loving'),
('Are low'),
('Are reading'),
('Are the key'),
('Are two ways'),
('Are under way'),
('Armor piercing'),
('Armour piercing'),
('Arts majors'),
('As a little'),
('As low as'),
('As well'),
('At a march'),
('At the ball'),
('At the borders'),
('At the course'),
('At the court'),
('At the front'),
('At the heart'),
('At the helm'),
('At the mercy'),
('At the spa'),
('Audio channels'),
('Autumn camp'),
('Autumn season'),
('Back corner'),
('Back down'),
('Back in'),
('Back to back'),
('Bad aims'),
('Bad bill'),
('Bad buy'),
('Bad captain'),
('Bad chancellor'),
('Bad charity'),
('Bad christmas'),
('Bad church'),
('Bad clues'),
('Bad college'),
('Bad cook'),
('Bad cooks'),
('Bad day'),
('Bad faith'),
('Bad farewell'),
('Bad grace'),
('Bad guest'),
('Bad guy'),
('Bad heart'),
('Bad june'),
('Bad lady'),
('Bad lord'),
('Bad love'),
('Bad minister'),
('Bad piece'),
('Bad president'),
('Bad price'),
('Bad prince'),
('Bad professor'),
('Bad school'),
('Bad story'),
('Bad summer'),
('Bad summers'),
('Bad university'),
('Bad will'),
('Bad winter'),
('Balk at'),
('Bank of england'),
('Banner reading'),
('Bark some'),
('Bashed pots'),
('Battle re-enactments'),
('Battle the'),
('Be fearing'),
('Be finely'),
('Be holding'),
('Be the key'),
('Beautiful flowers'),
('Been barefoot'),
('Been down'),
('Been loosely'),
('Before christmas'),
('Before holding'),
('Began tembling'),
('Beta test'),
('Beta testing'),
('Big deal'),
('Big guy'),
('Big kitty'),
('Bigger gap'),
('Bird seed'),
('Black beans'),
('Black box'),
('Black eye'),
('Black high'),
('Black labrador'),
('Black market'),
('Black monday'),
('Black olives'),
('Blue eyes'),
('Blunt instrument'),
('Blunt refusal'),
('Bodily harm'),
('Boils down'),
('Bona fide'),
('Bond villain'),
('Bonus miles'),
('Book villain'),
('Booth at'),
('Borders on'),
('Bottom line'),
('Bows out'),
('Box office'),
('Brace for'),
('Break down'),
('Breaks down'),
('Bridal showers'),
('Bride and groom'),
('Brings a'),
('Brings an'),
('Britain tidy'),
('British airways'),
('British ambassador'),
('British towns'),
('Broad gun'),
('Broad range'),
('Brown bag'),
('Burn bridges'),
('Bus fare'),
('But will'),
('Buy back'),
('By chance'),
('By compass'),
('By courier'),
('By smaller'),
('Cake tin'),
('Caller id'),
('Camp at'),
('Camp by'),
('Camp will'),
('Camps are'),
('Card holder'),
('Cartel heartland'),
('Cash back'),
('Cash trading'),
('Cavalier attitude'),
('Centers to'),
('Central bank'),
('Central banks'),
('Challenge harder'),
('Challenging pace'),
('Chambers of commerce'),
('Change the connection'),
('Change the statutes'),
('Chinese wall'),
('Christian Democratic'),
('Christmas day'),
('Church leader'),
('City centre'),
('Climate change'),
('Clinic access'),
('Close down'),
('Clothes hanger'),
('Co ed'),
('Cold winters'),
('Coming autumn'),
('Coming spring'),
('Coming weeks'),
('Commercial banks'),
('Common crimes'),
('Common practice'),
('Confer with'),
('Contrasted sharply'),
('Corporate bonds'),
('Cost center'),
('Cost centre'),
('Could mark the'),
('County level'),
('Court appearance'),
('Court case'),
('Court for'),
('Court heard'),
('Court judge'),
('Court upheld'),
('Cover story'),
('Cranberry sauce'),
('Crimes against'),
('Cross median'),
('Cross roads'),
('Crown jewel'),
('Crown jewels'),
('Crystal clear'),
('Current median'),
('Cut back'),
('Cutting a'),
('Cutting an'),
('Cutting back'),
('Cutting edge'),
('Cutting the'),
('Dairy farmer'),
('Dairy seller'),
('Data grabber'),
('Dawn of time'),
('Day fall'),
('De facto'),
('Deal by'),
('Deal is'),
('Deal making'),
('Deal negotiation'),
('Deal now'),
('Deal or'),
('Deal should'),
('Deal that'),
('Deal to'),
('Deal transfer'),
('Deal with'),
('Deal would'),
('Deems appropriate'),
('Deep snow'),
('Demand peaks'),
('Different story'),
('District judge'),
('Do the rest'),
('Docking station'),
('Dolby digital'),
('Domino effect'),
('Dont wanna'),
('Doorbell rang'),
('Double chevron'),
('Down before'),
('Down here'),
('Down memory lane'),
('Down the'),
('Down the drain'),
('Down the valley'),
('Draws for'),
('Drew large'),
('Drill down'),
('Drive down'),
('Drive east'),
('Drive north'),
('Drive south'),
('Drive toward'),
('Drive west'),
('E mails'),
('Each camp'),
('Each day'),
('Each lay'),
('Each purchase'),
('Each side'),
('Each view'),
('Each way'),
('Each westward'),
('Early april'),
('Early june'),
('Early may'),
('Early trading'),
('Earner for'),
('Edge over'),
('Electricity deal'),
('Emmy nomination'),
('End of April'),
('End of Jan'),
('End of June'),
('End of May'),
('End of the month'),
('End of the quarter'),
('End of the year'),
('Ended april'),
('Ended jan'),
('Ended june'),
('Ended may'),
('Enough booze'),
('Escape hatch'),
('Et al'),
('Even greater'),
('Even harder'),
('Evenly among'),
('Every angle'),
('Every autumn'),
('Every kitchen'),
('Ex parte'),
('Experience gross'),
('Fair deal'),
('Fairy tale'),
('Faith in'),
('Fall back'),
('Fall from grace'),
('Fall into line'),
('Fall over'),
('Fall well'),
('Fallen angels'),
('Family reading'),
('Farm entrance'),
('Fast pace'),
('Fell back'),
('Fell ill'),
('Fell over'),
('Fell to its'),
('Few weeks'),
('Field day'),
('Field specialist'),
('Fields from'),
('Fields in'),
('Fighting chance'),
('Final weeks'),
('Fine art'),
('Fine day'),
('Finished april'),
('Finished jan'),
('Finished june'),
('Finished may'),
('First blush'),
('First brushes'),
('First dibs'),
('Fixed deal'),
('Flat colander'),
('Flat pack'),
('Fleet manager'),
('Flying back'),
('Follow the steps'),
('For biz'),
('For christmas'),
('For greater'),
('For not'),
('For the front'),
('For the joint'),
('For the ride'),
('Foray into'),
('Frank take'),
('French doors'),
('French windows'),
('Front page'),
('FTSE 100'),
('Full and frank'),
('Full page'),
('Full story'),
('Fun deal'),
('Future deal'),
('Garden box'),
('Garners respect'),
('Gas deal'),
('Gas fields'),
('Gave way'),
('Gene edited'),
('Gene therapy'),
('General ledger'),
('Generating plant'),
('German shepherd'),
('Get under way'),
('Getting flack'),
('Giddy hope'),
('Given greater'),
('Goes back'),
('Goes sour'),
('Goes through'),
('Goes to the'),
('Goes way'),
('Goes well'),
('Goings on'),
('Good guy'),
('Good lord'),
('Got underway'),
('Grace period'),
('Grant agreement'),
('Grant agreements'),
('Grant request'),
('Grant requests'),
('Grant similar'),
('Graphic novel'),
('Graphic novels'),
('Great deal'),
('Great guy'),
('Great healer'),
('Greater detail'),
('Greater good'),
('Greater than'),
('Greater value'),
('Green earth'),
('Green energy'),
('Green light'),
('Green power'),
('Grew up reading'),
('Gross profit'),
('Gross profits'),
('Halfway point'),
('Halfway through'),
('Hanky panky'),
('Have heard'),
('Have snow'),
('Have the plain'),
('Have won'),
('He may'),
('He sang'),
('He will'),
('He won'),
('Head end'),
('Head lice'),
('Head of rugby'),
('Head office'),
('Heard back'),
('Heard how'),
('Heart goes'),
('Heavyweight boxer'),
('Hee hee'),
('High building'),
('High court'),
('High level'),
('High plateau'),
('High price'),
('High school'),
('High speed'),
('High standards'),
('High street banks'),
('Highest faith'),
('His view'),
('Hit the fan'),
('Ho ho ho'),
('Holding a'),
('Holding back'),
('Holding companies'),
('Holding company'),
('Holding fund'),
('Holding funds'),
('Holding off'),
('Holding period'),
('Holding the'),
('Holding up'),
('Holding us'),
('Holdings completely'),
('Hollering like'),
('Home loan'),
('Home page'),
('Home town'),
('Homing in'),
('Honest and frank'),
('Hope all'),
('Hope everything'),
('Hope everythings'),
('Hope for'),
('Hope that'),
('Hope to'),
('Hope we'),
('Hope you'),
('Hope your'),
('Hopping around'),
('Hot cross buns'),
('Hot ember'),
('Hover around'),
('Hover at'),
('How bad'),
('How close'),
('How could'),
('How far'),
('How long'),
('How peculiar'),
('How will'),
('Huddle with'),
('Huge deal'),
('Hung out'),
('Hunt down'),
('Hunts in the'),
('I bow'),
('I hope'),
('I lay'),
('I may'),
('I miss'),
('I wear'),
('I will'),
('Ideas forth'),
('In april'),
('In bars'),
('In bonds'),
('In building'),
('In earnest'),
('In flux'),
('In jan'),
('In june'),
('In may'),
('In ruins'),
('In summer'),
('In the'),
('In the autumn'),
('In the bush'),
('In the corner'),
('In the end'),
('In the forehead'),
('In the forest'),
('In the front'),
('In the greater'),
('In the heart'),
('In the joint'),
('In the light'),
('In the loop'),
('In the run'),
('In the rush'),
('In the rut'),
('In the spa'),
('In the spot'),
('In the spring'),
('In the still'),
('In the walk'),
('In the wood'),
('In the works'),
('Information booths'),
('International women'),
('Is geared to'),
('Is idle'),
('Is loving'),
('Is lower'),
('Is reading'),
('Is under way'),
('Issue bonds'),
('It may'),
('It will'),
('Its bonds'),
('Jabs at'),
('Joins with'),
('Joint boards'),
('Jot those'),
('Junk bonds'),
('Keen to'),
('Keep faith'),
('Key day'),
('Key target'),
('Kickoff meeting'),
('King and queen'),
('Kitchen counter'),
('Lane judges'),
('Last april'),
('Last autumn'),
('Last beam'),
('Last chance'),
('Last christmas'),
('Last easter'),
('Last jan'),
('Last june'),
('Last may'),
('Late april'),
('Late jan'),
('Late june'),
('Late may'),
('Law professor'),
('Lay eggs'),
('Lay off'),
('Lay out'),
('Lead over'),
('Leaks row'),
('Left the trees'),
('Left wing'),
('Left winger'),
('Less common'),
('Less rich'),
('Level playing field'),
('Light trucks'),
('Like to pass'),
('Local deal'),
('Locked down'),
('Locks are'),
('Locks have'),
('Long beard'),
('Long haul'),
('Long range'),
('Longer term'),
('Looks like under'),
('Losing faith'),
('Lovers on'),
('Loves reading'),
('Low cost'),
('Low daily'),
('Low ebb'),
('Low income'),
('Low levels'),
('Low price'),
('Low rank'),
('Low ranking'),
('Lower christmas'),
('Lower court'),
('Lower house'),
('Lower level'),
('Lowest rung'),
('Lows expected'),
('Lows in'),
('Made camp'),
('Main office'),
('Main page'),
('Major banks'),
('Many meetings'),
('March or april'),
('March through'),
('Marches mark'),
('Marches to'),
('Marches took'),
('Mark discrepancy'),
('Mark it'),
('Mark ups'),
('Mark your'),
('Market approach'),
('Market hedges'),
('Market price'),
('Market rate'),
('Market side'),
('Marks & spencer'),
('Marks and spencer'),
('Marks for'),
('Max number'),
('Max numbers'),
('Max rate'),
('Max rates'),
('Mayor of London'),
('Meager credit'),
('Meat packer'),
('Median age'),
('Merger deal'),
('Messing things'),
('Messing up'),
('Metre high'),
('Metre higher'),
('Metre lower'),
('Mid jan'),
('Mid june'),
('Mid march'),
('Mid may'),
('Middle school'),
('Monte carlo simulation'),
('Month of april'),
('Month of jan'),
('Month of june'),
('Month of may'),
('More miles'),
('More pressing'),
('More weeks'),
('Mortgage bill'),
('Mountain man'),
('Much smaller'),
('Much snow'),
('Muddle through'),
('Murky brown'),
('Muscle strands'),
('My calendar'),
('My heart'),
('My lips'),
('Nailing down'),
('Nearby camp'),
('New bill'),
('New bonds'),
('New deal'),
('New lows'),
('New snow'),
('New way to'),
('News story'),
('Next april'),
('Next autumn'),
('Next jan'),
('Next june'),
('Next may'),
('NHS england'),
('Nicer guy'),
('No biggie'),
('No faith'),
('Normal pace'),
('Northern city'),
('Northern town'),
('Northern village'),
('Not grant'),
('Notch above'),
('Notch below'),
('Nursery tunes'),
('Of bonds'),
('Of cheddar'),
('Of court'),
('Of fries'),
('Of greater'),
('Of hope'),
('Of jan'),
('Of june'),
('Of march'),
('Of may'),
('Of miles'),
('Of plant'),
('Of summers'),
('Of the ashes'),
('Of the ball'),
('Of the end'),
('Of the joint'),
('Of the osprey'),
('Of the rise'),
('Of weeks'),
('Off the front'),
('Off the hook'),
('Oh my'),
('Oh well'),
('Oil fields'),
('Old couple'),
('Old gal'),
('Old guy'),
('On black'),
('On boards'),
('On deal'),
('On page'),
('On the corner'),
('On the downside'),
('On the hill'),
('On the hook'),
('On the island'),
('On the lookout'),
('On the moon'),
('On the rise'),
('On the sly'),
('On the stack'),
('Once mighty'),
('One chance'),
('One more'),
('One of'),
('One page'),
('One way'),
('Only chance'),
('Onto the island'),
('Opening paragraph'),
('Option grant'),
('Original deal'),
('Oscar nominated'),
('Oscar winning'),
('Other postal'),
('Ouija board'),
('Ouija boards'),
('Our chances'),
('Outside the court'),
('Oval office'),
('Over a'),
('Over riding'),
('Over steep'),
('Over stepping'),
('Over the border'),
('Over the counter'),
('Over the course'),
('Over the last'),
('Over weeks'),
('Overnight lows'),
('Pace through'),
('Package deal'),
('Page at'),
('Page on'),
('Page to'),
('Page using'),
('Page version'),
('Pan racial faith'),
('Parks at'),
('Parks by'),
('Parks near'),
('Parks on'),
('Past weeks'),
('Pasta alfredo'),
('Pastures for'),
('Pay down the'),
('Pea shoots'),
('Peak weeks'),
('Pearl Harbor'),
('Per day'),
('Per page'),
('Per pound'),
('Percent bonds'),
('Permanently ground'),
('Personal story'),
('Phone bill'),
('Pinch on'),
('Pinch the'),
('Pinching yourself'),
('Place down here'),
('Place down there'),
('Plain vanilla'),
('Plant pots'),
('Plant volume'),
('Plant will'),
('Plateau that'),
('Play rugby'),
('Playing rugby'),
('Plays rugby'),
('Polling booth'),
('Port of call'),
('Portion of chips'),
('Ports docks'),
('Positive story'),
('Pound fell'),
('Pound sterling'),
('Powder snow'),
('Power plant'),
('Powers to'),
('President level'),
('Price fell'),
('Price in'),
('Price may'),
('Price ramping'),
('Price swap'),
('Prima facie'),
('Prior deal'),
('Pro rata'),
('Public Health England'),
('Pull the ball'),
('Quick halt'),
('Quick pace'),
('Rainy day'),
('Rapid halt'),
('Rapid pace'),
('Reached the dock'),
('Read the joint'),
('Reading about'),
('Reading books'),
('Reading excerpts'),
('Reading from'),
('Reading her'),
('Reading his'),
('Reading my'),
('Reading the'),
('Reading their'),
('Reading this'),
('Reading your'),
('Rebel song'),
('Recent weeks'),
('Reform bill'),
('Related fields'),
('Resolve disputes'),
('Revenue bonds'),
('Revenue rose'),
('Rich fields'),
('Rich premium'),
('Rich premiums'),
('Rips up'),
('Road closure'),
('Road closures'),
('Road down to'),
('Rock stars'),
('Rod for'),
('Rod to'),
('Rode that'),
('Roller coaster'),
('Roman catholic'),
('Romp through'),
('Rose almost'),
('Rose by'),
('Rose marginally'),
('Rose slightly'),
('Rose to'),
('Round trip'),
('Round trips'),
('Row over'),
('Royal Bank of Scotland'),
('Rugby club'),
('Rugby clubs'),
('Rugby football'),
('Rugby league'),
('Rugby player'),
('Rugby players'),
('Rugby sevens'),
('Rugby union'),
('Run down'),
('Rushed to'),
('Rushing into'),
('Rushing to'),
('Rushing water'),
('Russian roulette'),
('Sail from'),
('Sail out'),
('Sail to'),
('Sales price'),
('Salt cavern'),
('Same page'),
('Sang about'),
('Santa claus'),
('School day'),
('Sea wall'),
('Second quarter'),
('Second reading'),
('Secondary school'),
('Security holdings'),
('See that'),
('Sellers to'),
('Sellers who'),
('Selling bonds'),
('Send prices down'),
('Serve burgers'),
('Set forth'),
('Set to batter'),
('Settle there'),
('Settle these'),
('Several weeks'),
('Shares rose'),
('Sharp decline'),
('Sharp discount'),
('Sharp drop'),
('Sharp fall'),
('Sharp falls'),
('Sharp guy'),
('Sharp turn'),
('Sharper than'),
('She may'),
('She sang'),
('She will'),
('She won'),
('Shoo in'),
('Shoring up'),
('Short circuit'),
('Short term'),
('Sift through'),
('Silver stars'),
('Similar to how'),
('Since April'),
('Sit idle'),
('Slight chance'),
('Slimming pills'),
('Slow pace'),
('Sluggish pace'),
('Small cliff'),
('Smaller than'),
('Snow machine'),
('Snow mobile'),
('Some beers'),
('Some milder'),
('Southern city'),
('Southern town'),
('Southern village'),
('Spanning the'),
('Speed bumps'),
('Spelling mistake'),
('Spelling mistakes'),
('Spilling it'),
('Splash page'),
('Spurs opposition'),
('Stakes in'),
('Star quest'),
('Stars are'),
('Start of April'),
('Start of Jan'),
('Start of June'),
('Start of May'),
('Steel foundry'),
('Steep costs'),
('Stepping back'),
('Still under way'),
('Stock holdings'),
('Stocking stuffers'),
('Stocks close higher'),
('Stocks close lower'),
('Stocks fell'),
('Stocks rose'),
('Stone cold'),
('Story about'),
('Street marches'),
('Stripe down'),
('Stylish way'),
('Sue you'),
('Summary page'),
('Summed up'),
('Summer day'),
('Summer deal'),
('Summer styles'),
('Sunrise from'),
('Suspension bridges'),
('Taken the liberty'),
('Taming the'),
('Tax havens'),
('Team won'),
('Television channels'),
('Telly gold'),
('Term deal'),
('That clause'),
('That creates'),
('That deal'),
('That guy'),
('That joins'),
('That nodal'),
('That page'),
('That sees'),
('That song'),
('That the spot'),
('That the walk'),
('That van'),
('That were pressing'),
('The alter'),
('The april'),
('The autumn'),
('The ball is'),
('The bank'),
('The bank to'),
('The battle'),
('The beam'),
('The bees'),
('The bill'),
('The blithe'),
('The bloc'),
('The bonds'),
('The boulder'),
('The bow'),
('The buffalo'),
('The calendar'),
('The calls to'),
('The camp'),
('The cash'),
('The cashier'),
('The chance'),
('The childs'),
('The christmas'),
('The clouds'),
('The connection is'),
('The copier'),
('The couch'),
('The course'),
('The course that'),
('The court'),
('The court to'),
('The court will'),
('The crew'),
('The deal'),
('The dial in'),
('The easter'),
('The edge'),
('The eggs'),
('The elbow'),
('The ferry'),
('The fleet'),
('The folders specified'),
('The front'),
('The front office'),
('The front page'),
('The front room'),
('The gang'),
('The golf'),
('The gorge'),
('The grant'),
('The grass'),
('The greater'),
('The guy'),
('The hall to'),
('The heavenly'),
('The heck'),
('The hem'),
('The high'),
('The high crest'),
('The high end'),
('The higher end'),
('The hood'),
('The hope'),
('The jan'),
('The jedi'),
('The june'),
('The key element'),
('The key ingredient'),
('The key is'),
('The key issue'),
('The key to'),
('The king'),
('The kitchen'),
('The land is'),
('The light at'),
('The light load'),
('The loop on'),
('The low end'),
('The lower end'),
('The main front'),
('The march'),
('The mark'),
('The max'),
('The may'),
('The miles'),
('The moon'),
('The new house'),
('The new site'),
('The pace'),
('The page'),
('The peak hours'),
('The peculiar'),
('The piece between'),
('The plain truth'),
('The plant'),
('The plant would'),
('The point is'),
('The point that'),
('The points which'),
('The pool'),
('The prospect'),
('The prospect that'),
('The puncher'),
('The rally seemed'),
('The range'),
('The reins'),
('The rest'),
('The retreat was'),
('The rise in'),
('The roads'),
('The royal bank'),
('The run'),
('The seashore'),
('The sellers'),
('The short time'),
('The snow'),
('The song'),
('The sound'),
('The south side'),
('The spring'),
('The spur'),
('The stakes are'),
('The stock down'),
('The story'),
('The summers'),
('The sun'),
('The swallow'),
('The tally'),
('The tanking'),
('The tenor'),
('The ticker'),
('The upper hand'),
('The usher'),
('The van'),
('The verge'),
('The waiter'),
('The walk goes'),
('The walk to'),
('The way'),
('The weeks'),
('The west side'),
('The whack'),
('The winter'),
('The winters'),
('The works'),
('Their borders'),
('Then the forest'),
('There will'),
('They may'),
('They sang'),
('They will'),
('This april'),
('This autumn'),
('This childs'),
('This christmas'),
('This deal'),
('This easter'),
('This grant'),
('This guy'),
('This jan'),
('This june'),
('This may'),
('This page'),
('This rod'),
('This story'),
('This sun'),
('This traverse'),
('This will'),
('This won'),
('Through the model'),
('Ticket booth'),
('Tier that'),
('Tipper lorry'),
('To block the'),
('To camp'),
('To chance'),
('To clink'),
('To grant'),
('To hoard'),
('To lavish'),
('To lodge'),
('To march'),
('To mark the'),
('To pay down'),
('To plant'),
('To plow'),
('To prosper'),
('To quell'),
('To rebut'),
('To rout'),
('To stoke'),
('To tailor'),
('To the bar'),
('To the edge'),
('To the forest'),
('To the heart'),
('To the joint'),
('To the new common'),
('To the peak'),
('To the plant'),
('To the point in'),
('To the point when'),
('To the point where'),
('To the rest'),
('To the round'),
('To tilt'),
('To tote'),
('To uphold'),
('To vent'),
('To wear'),
('To withold'),
('Told callers'),
('Tonic for'),
('Too bad'),
('Too low'),
('Top court'),
('Top level'),
('Top line'),
('Top notch'),
('Top story'),
('Top will'),
('Tore her'),
('Tore his'),
('Tore my'),
('Tore out'),
('Towns battle'),
('Trade credit'),
('Trade credits'),
('Trade deal'),
('Trading deal'),
('Trading side'),
('Tree saplings'),
('Trial court'),
('Trickle out'),
('Trickle to'),
('Truly frank'),
('Trustworthy basis'),
('Tumble dryer'),
('Turned the corner'),
('Tut over'),
('Two way'),
('Uncommon gene'),
('Under house'),
('Under way on'),
('Under way to'),
('Under way with'),
('Until autumn'),
('Until spring'),
('Upper chamber'),
('Vantage point'),
('Vehicle fleet'),
('Via courier'),
('Vice versa'),
('Virgin atlantic'),
('Voting booth'),
('Walk back'),
('Walk down'),
('walk way'),
('Walked back'),
('Walked down'),
('Walls above'),
('Was down'),
('Was idle'),
('Was stolen'),
('Was very low'),
('Wash in'),
('Watch in dismay'),
('Water bottles'),
('Way round'),
('We drew'),
('We hope'),
('We hung'),
('We may'),
('We miss'),
('We will'),
('Wear help them'),
('Wear what'),
('Wear white'),
('Web page'),
('Week low'),
('Weeks ago'),
('Weeks to'),
('Well and'),
('Well over'),
('Well underway'),
('Were down'),
('Were low'),
('Were under way'),
('Wetter than'),
('When will'),
('Where grass'),
('Which borders'),
('Which wood'),
('While sellers'),
('Who love'),
('Who styles'),
('Who will'),
('Who won'),
('Wholesale sellers'),
('Wild card'),
('Wild goose'),
('Wind down'),
('Winding down'),
('Wings are'),
('Wings have'),
('Wins a'),
('Winter day'),
('Winter deal'),
('Wireless LAN'),
('With rich'),
('With smaller'),
('With the court'),
('With the high'),
('Within the bounds'),
('Without reading'),
('Women march'),
('Won her'),
('Won his'),
('Won the'),
('Wood chips'),
('Work crew'),
('Work will'),
('World fleet'),
('Worthy cause'),
('Worthy causes'),
('Would hurt'),
('Would settle'),
('Would sue'),
('Would wear'),
('Year lows'),
('Year old'),
('Years eve'),
('You may'),
('You must'),
('You will'),
('Your earthly'),
('Your grant'),
('Your heart'),
('Your knuckles'),
('Your sins');
-- Down
DELETE FROM Skip;