-- Up
INSERT INTO Placename (keyword)
VALUES
('Vaa Geo'),
('Vaagso Close'),
('Vaakel Craigs'),
('Vaasetter'),
('Vache Lane'),
('Vachelich'),
('Vachell Court'),
('Vacherie Lane'),
('Vachery Lane'),
('Vachery Pond'),
('Vadament Stack'),
('Vadill'),
('Vadill of Garth'),
('Vadis Close'),
('Vadna Geo'),
('Vadna Taing'),
('Vaendre Close'),
('Vaendre Lane'),
('Vaga Close'),
('Vagaland'),
('Vagar Hill'),
('Vagarth Close'),
('Vagg'),
('Vagg Copse'),
('Vagg Lane'),
('Vaggs Hill'),
('Vaggs Hill Bushes'),
('Vaggs Lane'),
('Vai Voe'),
('Vaila'),
('Vaila Lane'),
('Vaila Sound'),
('Vailan'),
('Vaile Mead'),
('Vaindre Close'),
('Vaindre Drive'),
('Vair Geo'),
('Vaisey Field'),
('Vaitam'),
('Vakel of Baagie'),
('Val Ayre'),
('Val Prinseps Road'),
('Val View'),
('Valaberg'),
('Valan Leas'),
('Valance Avenue'),
('Valance Close'),
('Valanders Lane'),
('Valarian Close'),
('Valasay'),
('Vald Skerries'),
('Valda Vale'),
('Valdene Close'),
('Valdene Drive'),
('Valdetta Court'),
('Valdoe'),
('Vale Acre Copse'),
('Vale Avenue'),
('Vale Bank'),
('Vale Close'),
('Vale Community'),
('Vale Coppice'),
('Vale Copse'),
('Vale Cottages'),
('Vale Court'),
('Vale Croft'),
('Vale Down'),
('Vale Drive'),
('Vale Edge'),
('Vale End'),
('Vale Estate'),
('Vale Farm Road'),
('Vale Foundary Lane'),
('Vale Grove'),
('Vale Head'),
('Vale Head Drive'),
('Vale Head Grove'),
('Vale Head Mount'),
('Vale House Close'),
('Vale House Drive'),
('Vale Lane'),
('Vale Leaze'),
('Vale Link'),
('Vale Mews'),
('Vale Mill Lane'),
('Vale Mill Way'),
('Vale of Aylesbury'),
('Vale of Belvoir'),
('Vale of Berkeley'),
('Vale Of Bonny View'),
('Vale of Catmose'),
('Vale of Clwyd'),
('Vale of Conwy'),
('Vale of Edale'),
('Vale of Evesham'),
('Vale of Ewyas'),
('Vale of Ffestiniog'),
('Vale of Glamorgan'),
('Vale of Gloucester'),
('Vale of Health'),
('Vale of Holmesdale'),
('Vale of Kent'),
('Vale of Lanherne'),
('Vale Of Leven District General'),
('Vale of Llangollen'),
('Vale of Mawgan'),
('Vale of Montgomery'),
('Vale of Mowbray'),
('Vale of Neath'),
('Vale Of Neath Road'),
('Vale of Nightshade'),
('Vale of Pewsey'),
('Vale of Pickering'),
('Vale of Taunton Deane'),
('Vale of Wardour'),
('Vale of White Horse'),
('Vale of York'),
('Vale Orchard'),
('Vale Owen Road'),
('Vale Park'),
('Vale Park Drive'),
('Vale Park Way'),
('Vale Pleasant'),
('Vale Reach'),
('Vale Rise'),
('Vale Road Bridge'),
('Vale Row'),
('Vale Royal'),
('Vale Royal Close'),
('Vale Royal Drive'),
('Vale Royal Wood'),
('Vale Side'),
('Vale Square'),
('Vale Street East'),
('Vale Top Avenue'),
('Vale View'),
('Vale View Close'),
('Vale View Crescent'),
('Vale View Drive'),
('Vale View Gardens'),
('Vale View Road'),
('Vale View Terrace'),
('Vale Walk'),
('Vale Way'),
('Vale Wood Drive'),
('Vale Wood Lane'),
('Valebridge Close'),
('Valebridge Drive'),
('Valebridge Pond'),
('Valebrook'),
('Valebrook Close'),
('Valebrook Drive'),
('Valebrooke Avenue'),
('Valehead'),
('Valehouse Close'),
('Valehouse Court'),
('Valehouse Farm'),
('Valehouse Reservoir'),
('Valehouse View'),
('Valemount'),
('Valence'),
('Valence Avenue'),
('Valence Circus'),
('Valence Drive'),
('Valence End'),
('Valence Walk'),
('Valence Way'),
('Valence Wood Road'),
('Valencia Close'),
('Valencia Croft'),
('Valencia Grove'),
('Valencia Way'),
('Valency Close'),
('Valency Drive'),
('Valency Row'),
('Valens Close'),
('Valenta Close'),
('Valentia Avenue'),
('Valentia Close'),
('Valentia Court'),
('Valentina Avenue'),
('Valentina Court'),
('Valentine Avenue'),
('Valentine Close'),
('Valentine Court'),
('Valentine Drive'),
('Valentine Grove'),
('Valentine Mews'),
('Valentine Rise'),
('Valentine Row'),
('Valentine Spring'),
('Valentine Walk'),
('Valentine Way'),
('Valentines'),
('Valentines Close'),
('Valentines Clump'),
('Valentines Drive'),
('Valentines Grove'),
('Valentines Lane'),
('Valentines Lea'),
('Valentines Meadow'),
('Valentines Park'),
('Valentines Way'),
('Valentines Woods'),
('Valentyne Close'),
('Valeria Close'),
('Valerian Avenue'),
('Valerian Close'),
('Valerian Court'),
('Valerian Drive'),
('Valerian Grove'),
('Valerian Rise'),
('Valerian Walk'),
('Valerian Way'),
('Valeridge Copse'),
('Valerie Close'),
('Valerie Grove'),
('Valerio Court'),
('Valeroyal Cut'),
('Valeroyal Park'),
('Vales Close'),
('Vales Moor'),
('Valeside'),
('Valestone Avenue'),
('Valestone Close'),
('Valeswood Lane'),
('Valetta Close'),
('Valetta Drive'),
('Valetta Grove'),
('Valetta Park'),
('Valetta Way'),
('Valeview'),
('Valeway Avenue'),
('Valewood Avenue'),
('Valewood Close'),
('Valewood Lane'),
('Valfreda Way'),
('Valgreen Court'),
('Valiant Avenue'),
('Valiant Close'),
('Valiant Drive'),
('Valiant Square'),
('Valiant Way'),
('Valiers Bottom'),
('Valkyrie Avenue'),
('Valkyrie Close'),
('Vall Ayre'),
('Valla Dale'),
('Valla Field'),
('Valla Kames'),
('Valla Ness'),
('Valladale'),
('Vallance Close'),
('Vallance Drive'),
('Vallans Close'),
('Vallansgate'),
('Vallaquie Strand'),
('Vallastrome'),
('Vallay'),
('Vallay Strand'),
('Vallentin Way'),
('Vallet Avenue'),
('Vallet Covert'),
('Valletort'),
('Valletort Lane'),
('Valletort Park'),
('Vallets Coppice'),
('Valletta Close'),
('Valletta Way'),
('Valletts Lane'),
('Valley Airfield'),
('Valley Approach'),
('Valley Avenue'),
('Valley Belt'),
('Valley Bridge'),
('Valley Bridge Parade'),
('Valley Bridge Road'),
('Valley Close'),
('Valley Clump'),
('Valley Corner'),
('Valley Cottages'),
('Valley Court'),
('Valley Covers'),
('Valley Creek'),
('Valley Dam'),
('Valley Dane Shaw'),
('Valley Dene'),
('Valley Drive'),
('Valley End'),
('Valley End House'),
('Valley End Road'),
('Valley Farm Drive'),
('Valley Farm Lane'),
('Valley Farm Road'),
('Valley Farm Spinney'),
('Valley Farm Way'),
('Valley Field'),
('Valley Field Covert'),
('Valley Field View'),
('Valley Fields Crescent'),
('Valley Fold'),
('Valley Forge'),
('Valley Forge Close'),
('Valley Garth'),
('Valley Green'),
('Valley Grove'),
('Valley Head'),
('Valley Heights'),
('Valley Hill'),
('Valley Lane'),
('Valley Lodge'),
('Valley Manor'),
('Valley Mead'),
('Valley Meadow'),
('Valley Meadow Close'),
('Valley Meadow Wood'),
('Valley Mews'),
('Valley Mill Court'),
('Valley Mill Lane'),
('Valley Mount'),
('Valley Mushroom Farm'),
('Valley New Road'),
('Valley of Coustry'),
('Valley of Desolation'),
('Valley of Houlland'),
('Valley of Keelhamar'),
('Valley of Koam'),
('Valley of Rocks'),
('Valley of Stones'),
('Valley of the Rocks'),
('Valley of Uraday'),
('Valley Parade'),
('Valley Park'),
('Valley Park Close'),
('Valley Park Drive'),
('Valley Park Lane'),
('Valley Park Road'),
('Valley Park Way'),
('Valley Prospect'),
('Valley Ridge'),
('Valley Rise'),
('Valley Side'),
('Valley Side Road'),
('Valley Square'),
('Valley Street North'),
('Valley Truckle'),
('Valley View'),
('Valley View Close'),
('Valley View Court'),
('Valley View Crescent'),
('Valley View Drive'),
('Valley View Estate'),
('Valley View Gardens'),
('Valley View Grove'),
('Valley View Park'),
('Valley View Rise'),
('Valley View Road'),
('Valley View Street'),
('Valley Walk'),
('Valley Wash'),
('Valley Way'),
('Valley Way Road'),
('Valleybank'),
('Valleybrook Grove'),
('Valleydene'),
('Valleyfield'),
('Valleyfield Avenue'),
('Valleyfield Brae'),
('Valleyfield Drive'),
('Valleyfield Glen'),
('Valleyfield Meadow'),
('Valleyfield Park'),
('Valleyfield Top'),
('Valleyfield Woods'),
('Valleys Shaw'),
('Valleyside'),
('Valleyview Drive'),
('Vallian Croft'),
('Vallibus Close'),
('Valliers Ness'),
('Valliers Wood Road'),
('Valligates'),
('Vallin Ness'),
('Vallis Close'),
('Vallis Vale'),
('Vallis Way'),
('Vallum Close'),
('Vallum Way'),
('Valma Rocks'),
('Valmar Avenue'),
('Valmeade Close'),
('Valmont Avenue'),
('Valognes Avenue'),
('Valonia Drive'),
('Valor Drive'),
('Valpy Avenue'),
('Valroy Close'),
('Vals Ness'),
('Valsheba Drive'),
('Valti Stack'),
('Valtos'),
('Valtos Rocks'),
('Valuation Lane'),
('Valway'),
('Vamh'),
('Vampire Way'),
('Van Alen Mews'),
('Van Common'),
('Van Der Bilt Court'),
('Van Der Breen Street'),
('Van Diemans'),
('Van Diemans Gardens'),
('Van Diemans Land'),
('Van Diemans Lane'),
('Van Diemans Road'),
('Van Diemans Way'),
('Van Diemens Close'),
('Van Diemens Gardens'),
('Van Diemens Land'),
('Van Diemens Lane'),
('Van Diemens Pass'),
('Van Dyck Avenue'),
('Van Dyck Close'),
('Van Dyck Place'),
('Van Dyck Road'),
('Van Dyke Close'),
('Van Dyke Place'),
('Van Gogh Close'),
('Van Gogh Drive'),
('Van Gogh Place'),
('Van Mildert Close'),
('Van Mildert Road'),
('Van Mildert Way'),
('Van Pool'),
('Van  Diemans Lane'),
('Vanborough Court'),
('Vanborough Walk'),
('Vanbrugh Close'),
('Vanbrugh Court'),
('Vanbrugh Drive'),
('Vanbrugh Fields'),
('Vanbrugh Gate'),
('Vanbrugh Grove'),
('Vanbrugh Hill'),
('Vanbrugh Lane'),
('Vanbrugh Park'),
('Vanbrugh Park Road'),
('Vanbrugh Park Road West'),
('Vanbrugh Way'),
('Vanburgh Close'),
('Vanburgh Place Lane'),
('Vanburgh Way'),
('Vances Glen'),
('Vancouver Avenue'),
('Vancouver Close'),
('Vancouver Court'),
('Vancouver Drive'),
('Vancouver House'),
('Vancouver Lane'),
('Vancouver Quay'),
('Vancouver Way'),
('Vandeleur Avenue'),
('Vandeleur Grove'),
('Vandenbury Circle'),
('Vanderbilt Avenue'),
('Vanderbyl Avenue'),
('Vanderhoot Way'),
('Vanderlin Court'),
('Vanderplanks Covert'),
('Vanderwalt Avenue'),
('Vandome Close'),
('Vandra Close'),
('Vandyck Avenue'),
('Vandyke'),
('Vandyke Avenue'),
('Vandyke Close'),
('Vandyke Cross'),
('Vane Close'),
('Vane Clump'),
('Vane Coppice'),
('Vane Court'),
('Vane Hall Place'),
('Vane Hill'),
('Vane Lane'),
('Vanes Copse'),
('Vanessa Avenue'),
('Vanessa Close'),
('Vanessa Drive'),
('Vanessa Walk'),
('Vanessa Way'),
('Vanfield Close'),
('Vangarde Way'),
('Vange'),
('Vange Corner Drive'),
('Vange Cottage Mews'),
('Vange Hill Drive'),
('Vange Marshes'),
('Vange Park Road'),
('Vanguard'),
('Vanguard Avenue'),
('Vanguard Chase'),
('Vanguard Circle'),
('Vanguard Close'),
('Vanguard Court'),
('Vanguard Hill'),
('Vanguard Way'),
('Vanguard Wharf'),
('Vanhurst Copse'),
('Vanilla Close'),
('Vanilla Mews'),
('Vanity Close'),
('Vanity Lane'),
('Vanlore Way'),
('Vann Bridge Close'),
('Vann Close'),
('Vann Copse'),
('Vann Farm Road'),
('Vann Hill'),
('Vann Lake'),
('Vann Lake Road'),
('Vann Lane'),
('Vanna  gya'),
('Vanneck Close'),
('Vanneck Square'),
('Vanners'),
('Vanners Copse'),
('Vanners Lane'),
('Vanoli Close'),
('Vanpost Hill'),
('Vanquish Close'),
('Vanquisher Walk'),
('Vans Gill'),
('Vansittart Drive'),
('Vansittart Estate'),
('Vantage Copse'),
('Vantage Court'),
('Vantage Drive'),
('Vantage Meadow'),
('Vantage Mews'),
('Vantage Way'),
('Vantorts Close'),
('Vanwall Drive'),
('Vapery Lane'),
('Var Cottage Wood'),
('Vara Close'),
('Varah Close'),
('Varaquoy'),
('Varchoel'),
('Varchoel Lane'),
('Varco Square'),
('Vardar Avenue'),
('Varden Avenue'),
('Varden Close'),
('Varden Croft'),
('Varden Grove'),
('Vardentown'),
('Vardon Close'),
('Vardon Drive'),
('Vardon Green'),
('Vardon Lea'),
('Vardon Way'),
('Vardre'),
('Vardre Avenue'),
('Vardre Close'),
('Vardre Lane'),
('Vardroe Way'),
('Vardy Close'),
('Varfell Lane'),
('Varian Court'),
('Varle Hill'),
('Varley'),
('Varley Avenue'),
('Varley Close'),
('Varley Court'),
('Varley Drive'),
('Varley Halls Of Residence'),
('Varley Head'),
('Varley Lane'),
('Varley Parade'),
('Varley Sand'),
('Varley Vale'),
('Varley Way'),
('Varleys Copse'),
('Varlian Close'),
('Varlins Way'),
('Varmady'),
('Varme Dale'),
('Varna Close'),
('Varna Lane'),
('Varncombe Hill'),
('Varndean Close'),
('Varndean Drive'),
('Varndean Holt'),
('Varndells Copse'),
('Varney Avenue'),
('Varney Close'),
('Varnister Lane'),
('Varnsdorf Way'),
('Varos Close'),
('Varrick Way'),
('Varrier Jones Drive'),
('Varrier Jones Place'),
('Varses'),
('Varsity'),
('Varsity Close'),
('Varsity Drive'),
('Varsity Rise'),
('Varsity Row'),
('Varsity Way'),
('Varteg'),
('Varteg Hill'),
('Varteg Row'),
('Vartenham Hill'),
('Varvel Avenue'),
('Varvel Close'),
('Vary Clump'),
('Vary Coppice'),
('Vasa Loch'),
('Vasa Point'),
('Vasart Court'),
('Vaseford Copse'),
('Vasey Close'),
('Vashon Close'),
('Vashon Drive'),
('Vassa'),
('Vassa Voe'),
('Vassall'),
('Vassall Court'),
('Vassancro'),
('Vassar Court'),
('Vastern'),
('Vastern Wharf'),
('Vasterne Close'),
('Vastre View'),
('Vat of Kirbuster'),
('Vatch Lane'),
('Vatch View'),
('Vatem'),
('Vatersay'),
('Vati Geo'),
('Vatisker'),
('Vatisker Park'),
('Vatna Gaet'),
('Vats Meadow'),
('Vats Wick'),
('Vats  houll'),
('Vats  houll Voe'),
('Vatten'),
('Vatten Island'),
('Vattingstone Brake'),
('Vattingstone Lane'),
('Vauban Drive'),
('Vaudeville Close'),
('Vaudrey Close'),
('Vaudrey Drive'),
('Vaudrey Lane'),
('Vaughan Avenue'),
('Vaughan Close'),
('Vaughan Court'),
('Vaughan Drive'),
('Vaughan Grove'),
('Vaughan Lane'),
('Vaughan Mead'),
('Vaughan Parade'),
('Vaughan Rise'),
('Vaughan Thomas Lane'),
('Vaughan Way'),
('Vaughan Williams Close'),
('Vaughan Williams Drive'),
('Vaughan Williams Road'),
('Vaughan Williams Way'),
('Vaughans'),
('Vaughans Lane'),
('Vaughton Drive'),
('Vaughton Hill'),
('Vaul'),
('Vaul Bay'),
('Vault Beach'),
('Vault Glen'),
('Vault Hill'),
('Vault Hill Wood'),
('Vault Square'),
('Vaults Lane'),
('Vaunces Lane'),
('Vauterhill Moor'),
('Vaux Avenue'),
('Vauxhall'),
('Vauxhall Avenue'),
('Vauxhall Bridge Road'),
('Vauxhall Centre'),
('Vauxhall Close'),
('Vauxhall Copse'),
('Vauxhall Covert'),
('Vauxhall Drive'),
('Vauxhall Grove'),
('Vauxhall Lane'),
('Vauxhall Quay'),
('Vauxhall Walk'),
('Vauxhall Way'),
('Vauze Avenue'),
('Vauze House Close'),
('Vavasour Court'),
('Vavasours Slip'),
('Vawdrey Close'),
('Vawdrey Drive'),
('Vawers Close'),
('Vawser Way'),
('Vayne Moor Wood'),
('Vaynol Close'),
('Vaynol Covert'),
('Vaynol Hall'),
('Vaynol Way'),
('Vaynor'),
('Vaynor Drive'),
('Vaynor Lane'),
('Vaynor  fâch Wood'),
('Vayre Close'),
('Vayro Close'),
('Ve Ness'),
('Ve Skerries'),
('Veal Lane'),
('Veale Close'),
('Veale Drive'),
('Veals Copse'),
('Veals Lane'),
('Veals Mead'),
('Veals Row'),
('Vean Hole'),
('Veantrow Bay'),
('Vears Lane'),
('Vearse Close'),
('Veasey Close'),
('Veasey Way'),
('Veasypark'),
('Veathery Quoy'),
('Vecta Close'),
('Vecta House'),
('Vectis Close'),
('Vectis Drive'),
('Vectis Way'),
('Vector Walk'),
('Vedal Drove'),
('Vedders Geo'),
('Veddoes Coppice'),
('Vedonis Park'),
('Vedra Close'),
('Vedrato'),
('Vedri Geo'),
('Vedrick'),
('Vee Lane'),
('Vee Taing'),
('Veeda Stack'),
('Veedie'),
('Veensgarth'),
('Veenston Glen'),
('Veere Park'),
('Veester Hill'),
('Vega Close'),
('Vegas'),
('Veille Lane'),
('Veiny Cheese Pond'),
('Veitch Close'),
('Veitches Court'),
('Veitchs Square'),
('Vela Close'),
('Vela Row'),
('Vela Walk'),
('Velator'),
('Velator Close'),
('Velator Drive'),
('Velator Lane Avenue'),
('Velda Close'),
('Velden Way'),
('Veldene Way'),
('Velder Avenue'),
('Veldo'),
('Veldo Lane'),
('Velhurst Copse'),
('Velhurst Drive'),
('Velindre'),
('Velindre Cancer Centre'),
('Velizy Avenue'),
('Vellacott Close'),
('Vellacott Lane'),
('Vellacotts'),
('Vellan Avenue'),
('Vellan Close'),
('Vellan Court'),
('Vellan Drang'),
('Vellan Head'),
('Vellan Parc Avenue'),
('Vellan Vrane'),
('Velland Avenue'),
('Vellandrucia'),
('Vellanoweth'),
('Vellator Way'),
('Velley Hill'),
('Vellin  gluz Rocks'),
('Vellore Lane'),
('Vellow'),
('Vellow Moor Lane'),
('Vellow Wood Lane'),
('Vellum Drive'),
('Vellus Court'),
('Velmead Close'),
('Velmere Avenue'),
('Velocette Way'),
('Velocity Way'),
('Velour Close'),
('Velsheda Close'),
('Velsheda Court'),
('Velsheda View'),
('Velt Hevda'),
('Velthouse Lane'),
('Veltie'),
('Veltie Skerry'),
('Veltieskerry Loch'),
('Veltshaw Close'),
('Velvet Beds Island'),
('Velvet Bottom'),
('Velvet Hall Strip'),
('Velvet Lawn'),
('Velvet Lawn Road'),
('Velvet Rock'),
('Velvet Wood Close'),
('Velville Court'),
('Velyn Avenue'),
('Vementry'),
('Ven Combe'),
('Ven Law'),
('Venables Avenue'),
('Venables Close'),
('Venables Coppice'),
('Venables Court'),
('Venables Drive'),
('Venables Lane'),
('Venables Way'),
('Venachar Avenue'),
('Venalie'),
('Venborough Close'),
('Venbridge Hill'),
('Vence Close'),
('Venchen Hill'),
('Venches Rock'),
('Vendace Drive'),
('Vendace Mews'),
('Vendace Wynd'),
('Vendale Avenue'),
('Vendeen'),
('Vendra Stacks'),
('Venericks Cove'),
('Veness'),
('Veness Hill'),
('Venesta Avenue'),
('Venetia Close'),
('Venetia Park'),
('Venetian Court'),
('Venette Close'),
('Venford Close'),
('Venford Hill'),
('Venford Moor'),
('Venford Reservoir'),
('Venges Brake'),
('Venhay Down'),
('Venibar'),
('Venice'),
('Venice Avenue'),
('Venice Close'),
('Venice Court'),
('Venics Way'),
('Veniss Copse'),
('Venlake'),
('Venlake Close'),
('Venlake End'),
('Venland Close'),
('Venlaw High Road'),
('Venlaw Quarry Road'),
('Venley Copse'),
('Venley Lane'),
('Venlock Close'),
('Venmans Hill Wood'),
('Venmore Drive'),
('Venn'),
('Venn Channing Copse'),
('Venn Close'),
('Venn Close Coppice'),
('Venn Copse'),
('Venn Court'),
('Venn Cross'),
('Venn Dingle'),
('Venn Down'),
('Venn Drive'),
('Venn Grove'),
('Venn Hill'),
('Venn Lane'),
('Venn Moor'),
('Venn Orchard'),
('Venn Ottery'),
('Venn Ottery Common'),
('Venn Ottery Hill'),
('Venn Ottery Road'),
('Venn Park'),
('Venn Way'),
('Vennal Hill'),
('Vennals Copse'),
('Vennaway Lane'),
('Venneit Close'),
('Vennel Lane'),
('Venner Avenue'),
('Venner Close'),
('Venners Close'),
('Venners Water'),
('Venngreen'),
('Venning Avenue'),
('Venning Grove'),
('Vennings Copse'),
('Vennington'),
('Vennington Walk'),
('Vennland Way'),
('Vennpark Moor'),
('Venns Acre'),
('Venns Close'),
('Venns Gate'),
('Venns Green'),
('Venns Lane'),
('Vennwood Close'),
('Venny Bridge'),
('Venny Tedburn'),
('Venomous Clough'),
('Vensilly Hill'),
('Vensland'),
('Venslooe Hill'),
('Venta Drive'),
('Venta Way'),
('Venterdon'),
('Ventfield Close'),
('Vention'),
('Vention Lane'),
('Ventnor'),
('Ventnor Avenue'),
('Ventnor Bay'),
('Ventnor Close'),
('Ventnor Court'),
('Ventnor Drive'),
('Ventnor East'),
('Ventnor Grove'),
('Ventnor Haven'),
('Ventnor Lane'),
('Ventnor Rise'),
('Ventnor Villas'),
('Ventnor Way'),
('Ventnor West'),
('Vento Close'),
('Venton'),
('Venton Close'),
('Venton Cove'),
('Venton Drive'),
('Venton East Square'),
('Venton Hill Point'),
('Venton Lace Road'),
('Venton Moor'),
('Venton Vaden'),
('Venton Vision Rise'),
('Ventongimps'),
('Ventonhills Copse'),
('Ventonleague'),
('Ventonleague Hill'),
('Ventonleague Row'),
('Ventonraze'),
('Ventress Close'),
('Ventress Hall'),
('Ventris Close'),
('Ventry Close'),
('Ventura Avenue'),
('Ventura Close'),
('Ventura Court'),
('Ventura Drive'),
('Ventura Park'),
('Ventura Park Road'),
('Venture Avenue'),
('Venture Avenue Venture Avenue'),
('Venture Chase'),
('Venture Close'),
('Venture Court'),
('Venture Drive'),
('Venture Hill'),
('Venture Scout Way'),
('Venture Way'),
('Venturefair Avenue'),
('Venturefair Drive'),
('Venus Avenue'),
('Venus Bank'),
('Venus Close'),
('Venus Court'),
('Venus Hill'),
('Venus Lane'),
('Venus Mews'),
('Venus Way'),
('Venusbank Coppice'),
('Venvell Close'),
('Venwood'),
('Veor Cove'),
('Ver Brook Avenue'),
('Ver Geo'),
('Vera Avenue'),
('Vera Close'),
('Vera Court'),
('Vera Lane'),
('Vera Lynn Close'),
('Vera Roberts Way'),
('Vera Wood Close'),
('Veralam Way'),
('Verallo Drive'),
('Veras Walk'),
('Verbania Way'),
('Verbena Avenue'),
('Verbena Close'),
('Verbena Court'),
('Verbena Drive'),
('Verbena Walk'),
('Verbena Way'),
('Vercor Close'),
('Vercourt'),
('Verdala Park'),
('Verdale Avenue'),
('Verdant Close'),
('Verdant Drive'),
('Verdant Lane'),
('Verdant Vale'),
('Verdant Way'),
('Verdayne Avenue'),
('Verde Close'),
('Verden Avenue'),
('Verden Close'),
('Verden Way'),
('Verder Grove'),
('Verdi Avenue'),
('Verdi Close'),
('Verdi Court'),
('Verdin Avenue'),
('Verdin Close'),
('Verdin Court'),
('Verdins Cut'),
('Verdon Avenue'),
('Verdon Close'),
('Verdon Drive'),
('Verdons Lane'),
('Verdun Avenue'),
('Verdun Close'),
('Verdun Square'),
('Verdure Avenue'),
('Verdure Close'),
('Vere Avenue'),
('Vere Close'),
('Vere Court'),
('Vere Point'),
('Vere Square'),
('Vereker Drive'),
('Vereley'),
('Verelst Avenue'),
('Verely Hill'),
('Verey Close'),
('Verger Close'),
('Vergette Court'),
('Vergyland Combe'),
('Veridion Way'),
('Verini Close'),
('Verinia Court'),
('Veritas Grove'),
('Verity Close'),
('Verity Rise'),
('Verity Spur'),
('Verity View'),
('Verity Walk'),
('Verity Way'),
('Veritys'),
('Verlam Grove'),
('Verland Close'),
('Verland Way'),
('Verlands'),
('Verlands Close'),
('Verley Close'),
('Verlon Close'),
('Vermeer Close'),
('Vermeer Ride'),
('Vermiel Grove'),
('Vermin Lane'),
('Vermin Valley'),
('Vermont'),
('Vermont Avenue'),
('Vermont Close'),
('Vermont Drive'),
('Vermont Green'),
('Vermont Grove'),
('Vermont Standing'),
('Vermont Way'),
('Vermont Woods'),
('Vermuyden'),
('Vermuyden Villas'),
('Vermuyden Way'),
('Vernal Close'),
('Vernal Lane'),
('Vernalls Close'),
('Vernalls Court'),
('Vernatts Green'),
('Vernditch Chase'),
('Verne Avenue'),
('Verne Close'),
('Verne Common Road'),
('Verne Drive'),
('Verne Hill Road'),
('Verne Walk'),
('Verne Way'),
('Verner Close'),
('Verner Common'),
('Verneuil Avenue'),
('Verney Avenue'),
('Verney Close'),
('Verney Copse'),
('Verney Drive'),
('Verney Farm Close'),
('Verney Junction'),
('Verney Mews'),
('Verney Park'),
('Verney Spinney'),
('Verney Walk'),
('Verney Way'),
('Vernham Bank'),
('Vernham Dean'),
('Vernham Dean Gillums'),
('Vernham Grove'),
('Vernham Row'),
('Vernham Walk'),
('Vernhams Dean'),
('Vernhamwood Close'),
('Vernier Avenue'),
('Vernier Close'),
('Verno Lane'),
('Vernolds Common'),
('Vernolds Coppice'),
('Vernolds Croft'),
('Vernon Avenue'),
('Vernon Bank'),
('Vernon Close'),
('Vernon Corner'),
('Vernon Court'),
('Vernon Delph'),
('Vernon Drive'),
('Vernon Green'),
('Vernon Grove'),
('Vernon Hill'),
('Vernon Lane'),
('Vernon Park'),
('Vernon Park Drive'),
('Vernon Park Road'),
('Vernon Rise'),
('Vernon Square'),
('Vernon Street North'),
('Vernon Villas'),
('Vernon Walk'),
('Vernon Way'),
('Vernon Williams Close'),
('Vernon Yard'),
('Vernongate'),
('Vernonholme'),
('Vernons Close'),
('Vernons Copse'),
('Vernons Lane'),
('Vernslade'),
('Veron Point'),
('Verona'),
('Verona Avenue'),
('Verona Close'),
('Verona Court'),
('Verona Drive'),
('Verona Grove'),
('Verona Lane'),
('Verona Rise'),
('Verona Way'),
('Veronica Avenue'),
('Veronica Close'),
('Veronica Drive'),
('Veronica House'),
('Veronica Walk'),
('Veronica Way'),
('Veronne Drive'),
('Veros Lane'),
('Verrall Close'),
('Verralls'),
('Verriers'),
('Verrill Avenue'),
('Verrington'),
('Verrington Lane'),
('Verrington Park Road'),
('Verriotts Lane'),
('Verry Geo'),
('Versa Geo'),
('Versatile Square'),
('Verstone Croft'),
('Vert Lane'),
('Vertish Hill'),
('Verulam'),
('Verulam Avenue'),
('Verulam Close'),
('Verulam Passage'),
('Verulam Way'),
('Vervain Close'),
('Vervan Rocks'),
('Verwill Lane'),
('Verwood'),
('Verwood Close'),
('Verwood Drive'),
('Verwood East'),
('Verwood West'),
('Veryan'),
('Veryan Bay'),
('Veryan Churchtown'),
('Veryan Close'),
('Veryan Green'),
('Vesey Close'),
('Vesey Court'),
('Vesey Trees'),
('Veseys Holehill'),
('Vesker'),
('Vespasian Close'),
('Vespasian Way'),
('Vesper Close'),
('Vesper Court'),
('Vesper Court Drive'),
('Vesper Drive'),
('Vesper Gate Crescent'),
('Vesper Gate Drive'),
('Vesper Gate Mount'),
('Vesper Grove'),
('Vesper Lane'),
('Vesper Mount'),
('Vesper Rise'),
('Vesper Walk'),
('Vesper Way'),
('Vespers Close'),
('Vessacks'),
('Vessey Close'),
('Vessey Hill'),
('Vessey Pasture Belt'),
('Vessey Pasture Dale'),
('Vest Ness'),
('Vesta Avenue'),
('Vesta Close'),
('Vesta Grove'),
('Vesta Mews'),
('Vesta Quarry'),
('Vesta Skerry'),
('Vesta Way'),
('Vestaber'),
('Vestaneum'),
('Vestavirdin Loch'),
('Vester Geos'),
('Vesters Hill Drove'),
('Vestey Court'),
('Vestra Fiold'),
('Vestris Drive'),
('Vestry Close'),
('Vestry Court'),
('Vestry Drive'),
('Vestry Lane'),
('Vestry Mews'),
('Vesuvian Drive'),
('Vesuvius Drive'),
('Vetch Close'),
('Vetch Field Avenue'),
('Vetch Fields'),
('Vetch Hole Wood'),
('Vetch Park'),
('Vetch Way'),
('Vetches Downs'),
('Vetchfield'),
('Vetchfield Close'),
('Veteran Close'),
('Veterinary Close'),
('Vettriano Vale'),
('Vevers Bushes'),
('Vexation Lane'),
('Vexhim Park'),
('Vexil Close'),
('Veyses End'),
('Veysey Close'),
('Via Gellia'),
('Via Gellia Road'),
('Via Ravenna'),
('Via Romana'),
('Via Urbis Romanae'),
('Viables'),
('Viables Lane'),
('Viadevana'),
('Viador'),
('Viaduct'),
('Viaduct Circle'),
('Viaduct Close'),
('Viaduct Covert'),
('Viaduct Drive'),
('Viaduct Estate Road'),
('Viaduct Hill'),
('Viaduct Lane'),
('Viaduct View'),
('Viaduct Way'),
('Vian Avenue'),
('Vian Close'),
('Vian End'),
('Vian Way'),
('Vianesa Grove'),
('Vias Moss'),
('Vibernum Rise'),
('Vibia Close'),
('Viburnum Chase'),
('Viburnum Close'),
('Viburnum Court'),
('Viburnum Gate'),
('Viburnum View'),
('Viburnum Way'),
('Vicar Hill'),
('Vicar Hill Lane'),
('Vicar Lane'),
('Vicar Park Drive'),
('Vicar Park Road'),
('Vicar Pond'),
('Vicar Water Close'),
('Vicar Way'),
('Vicarage'),
('Vicarage Avenue'),
('Vicarage Ball'),
('Vicarage Bank'),
('Vicarage Carr'),
('Vicarage Causeway'),
('Vicarage Cliff'),
('Vicarage Close'),
('Vicarage Closes'),
('Vicarage Coppice'),
('Vicarage Copse'),
('Vicarage Court'),
('Vicarage Croft'),
('Vicarage Drive'),
('Vicarage Drove'),
('Vicarage Farm Close'),
('Vicarage Farm Court'),
('Vicarage Farm Road'),
('Vicarage Farm Yard'),
('Vicarage Field'),
('Vicarage Fields'),
('Vicarage Flats'),
('Vicarage Fold'),
('Vicarage Gate'),
('Vicarage Gorse'),
('Vicarage Gorse Covert'),
('Vicarage Green'),
('Vicarage Grove'),
('Vicarage Heights'),
('Vicarage Hill'),
('Vicarage Hill Head'),
('Vicarage House'),
('Vicarage Lane'),
('Vicarage Lawn'),
('Vicarage Lawns'),
('Vicarage Meadow'),
('Vicarage Meadows'),
('Vicarage Mews'),
('Vicarage Paddock'),
('Vicarage Park'),
('Vicarage Prospect'),
('Vicarage Rise'),
('Vicarage Row'),
('Vicarage Shaw'),
('Vicarage Spinney'),
('Vicarage Square'),
('Vicarage View'),
('Vicarage Walk'),
('Vicarage Way'),
('Vicarage Wood Way'),
('Vicarland'),
('Vicarman Clough'),
('Vicars Allotment'),
('Vicars Brake'),
('Vicars Bridge Close'),
('Vicars Bridge Road'),
('Vicars Close'),
('Vicars Coppice'),
('Vicars Copse'),
('Vicars Court'),
('Vicars Croft'),
('Vicars Cross Road'),
('Vicars Drive'),
('Vicars Fields'),
('Vicars Garth'),
('Vicars Gate'),
('Vicars Grove'),
('Vicars Hall Gardens'),
('Vicars Hall Lane'),
('Vicars Hill'),
('Vicars Lane'),
('Vicars Mews'),
('Vicars Moor Lane'),
('Vicars Moor Wood'),
('Vicars Oak Road'),
('Vicars Orchard'),
('Vicars Pond'),
('Vicars Rough'),
('Vicars Row'),
('Vicars Walk'),
('Vicarscross'),
('Vicarsholme Close'),
('Vicarwood Avenue'),
('Vicary Close'),
('Vicary Lane'),
('Vicary Way'),
('Vice Lane'),
('Viceroy Close'),
('Viceroy Drive'),
('Vichy Close'),
('Vicker Close'),
('Vicker Grove'),
('Vickermans Lane'),
('Vickers Avenue'),
('Vickers Close'),
('Vickers Drive'),
('Vickers Ground'),
('Vickers Lane'),
('Vickers Point'),
('Vickers Row'),
('Vickers Way'),
('Vickersdale'),
('Vickerstown'),
('Vickery Close'),
('Vickery Court'),
('Vickery Way'),
('Vicks Meadow'),
('Victop Lay Place'),
('Victor Approach'),
('Victor Avenue'),
('Victor Beamish Avenue'),
('Victor Charles Close'),
('Victor Close'),
('Victor Drive'),
('Victor Grove'),
('Victor Jackson Avenue'),
('Victor Lane'),
('Victor Mann Street'),
('Victor Mew Close'),
('Victor Park Terrace'),
('Victor Walk'),
('Victor Way'),
('Victor Wilde Drive'),
('Victoria & Norcross'),
('Victoria Approach'),
('Victoria Avenue'),
('Victoria Avenue East'),
('Victoria Avenue West'),
('Victoria Bay'),
('Victoria Beach'),
('Victoria Belt'),
('Victoria Bridge Road'),
('Victoria Bridge Street'),
('Victoria Buildings'),
('Victoria Care Centre'),
('Victoria Chase'),
('Victoria Circus'),
('Victoria Close'),
('Victoria Clump'),
('Victoria Common'),
('Victoria Copse'),
('Victoria Cottage'),
('Victoria Cottages'),
('Victoria Court'),
('Victoria Crescent Lane'),
('Victoria Crescent Place'),
('Victoria Crescent Road'),
('Victoria Crescent West'),
('Victoria Cross Road'),
('Victoria Deep Water'),
('Victoria Dock'),
('Victoria Dock Road'),
('Victoria Docks'),
('Victoria Drive'),
('Victoria Drive East'),
('Victoria Drive West'),
('Victoria East Road'),
('Victoria Embankment'),
('Victoria Esplanade'),
('Victoria Estate'),
('Victoria Falls'),
('Victoria Falls Road'),
('Victoria Farm Close'),
('Victoria Fields'),
('Victoria Fold'),
('Victoria Garesfield'),
('Victoria Gate'),
('Victoria Gate Gardens'),
('Victoria Glade'),
('Victoria Grange Drive'),
('Victoria Grange Way'),
('Victoria Green'),
('Victoria Grove'),
('Victoria Grove Mews'),
('Victoria Hall Gardens'),
('Victoria Harbour'),
('Victoria Heights'),
('Victoria Hill'),
('Victoria Hill Road'),
('Victoria Hospice'),
('Victoria Hospital Annexe'),
('Victoria House'),
('Victoria Infirmary'),
('Victoria Integrated Care Centre'),
('Victoria Jubilee Covert'),
('Victoria Lake'),
('Victoria Lane'),
('Victoria Lawn'),
('Victoria Lodge'),
('Victoria Manor'),
('Victoria Mead'),
('Victoria Meadow'),
('Victoria Memorial'),
('Victoria Mews'),
('Victoria Mill Drive'),
('Victoria Mill Road'),
('Victoria Mills'),
('Victoria Mount'),
('Victoria Orchard'),
('Victoria Osiers'),
('Victoria Parade'),
('Victoria Park'),
('Victoria Park Avenue'),
('Victoria Park Corner'),
('Victoria Park Drive'),
('Victoria Park Gardens'),
('Victoria Park Grove'),
('Victoria Park Lane North'),
('Victoria Park Mount'),
('Victoria Park Neuk'),
('Victoria Park Road'),
('Victoria Park Road East'),
('Victoria Park Road West'),
('Victoria Park Square'),
('Victoria Park Street'),
('Victoria Park View'),
('Victoria Park Way'),
('Victoria Passage'),
('Victoria Point'),
('Victoria Promenade'),
('Victoria Quadrant'),
('Victoria Quay'),
('Victoria Reservoir'),
('Victoria Retreat'),
('Victoria Rise'),
('Victoria Rooms'),
('Victoria Row'),
('Victoria Spinney'),
('Victoria Springs'),
('Victoria Square'),
('Victoria Stables'),
('Victoria Station Approach'),
('Victoria Station Road'),
('Victoria Track'),
('Victoria Vale'),
('Victoria Viaduct'),
('Victoria Village'),
('Victoria Villas'),
('Victoria Walk'),
('Victoria Way'),
('Victorian Grove'),
('Victoriana Way'),
('Victorias Spinney'),
('Victorias Way'),
('Victors Close'),
('Victors Drive'),
('Victors Way'),
('Victory Avenue'),
('Victory Belt'),
('Victory Boulevard'),
('Victory Close'),
('Victory Clump'),
('Victory Court'),
('Victory Drive'),
('Victory Green'),
('Victory Grove'),
('Victory Lane'),
('Victory Park'),
('Victory Park Road'),
('Victory Park Way'),
('Victory Planting'),
('Victory Rise'),
('Victory Road Mews'),
('Victory Square'),
('Victory Street East'),
('Victory Street West'),
('Victory Way'),
('Victuals Grove'),
('Vicus Way'),
('Vida Field Stour'),
('Vidgeon Avenue'),
('Vidler Square'),
('Vidlin'),
('Vidlin Loch'),
('Vidlin Ness'),
('Vidlin Voe'),
('Vienenburg Avenue'),
('Vienna Close'),
('Vienna Court'),
('Vienna Grove'),
('Vienna Road East'),
('Vienna Way'),
('Vienne Close'),
('Viersen Platz'),
('Vieux Close'),
('View Bank'),
('View Close'),
('View Croft Road'),
('View Drive'),
('View Edge'),
('View Forth'),
('View France Close'),
('View Hall Fields'),
('View Island'),
('View Lane'),
('View Mount'),
('View Park Road'),
('View Point'),
('View Point Road'),
('View Ponds'),
('View Rock'),
('View Spinney'),
('View Strip'),
('View Tops'),
('View Tree Close'),
('Viewbank'),
('Viewbank Avenue'),
('Viewbank Drive'),
('Viewbank View'),
('Viewdales Close'),
('Viewfield'),
('Viewfield Avenue'),
('Viewfield Close'),
('Viewfield Court'),
('Viewfield Drive'),
('Viewfield Lane'),
('Viewfield Park'),
('Viewfield Woods'),
('Viewfields'),
('Viewforth'),
('Viewforth Avenue'),
('Viewforth Drive'),
('Viewforth Square'),
('Viewglen Court'),
('Viewhill'),
('Viewhill Meadows'),
('Viewie Knowe'),
('Viewing Hill'),
('Viewland Close'),
('Viewlands'),
('Viewlands Avenue'),
('Viewlands Close'),
('Viewlands Drive'),
('Viewlands Mount'),
('Viewlands Rise'),
('Viewlands Road West'),
('Viewlaw'),
('Viewlaw Lake'),
('Viewley Centre Road'),
('Viewley Hill Avenue'),
('Viewly Hill'),
('Viewmount Brae'),
('Viewmount Drive'),
('Viewpark'),
('Viewpark Avenue'),
('Viewpark Close'),
('Viewpark Drive'),
('Viewpark Glen'),
('Viewpoint Gate'),
('Viewside Close'),
('Viewy Knowe'),
('Viga Geo'),
('Viga Taing'),
('Vigadale'),
('Vigar Houll'),
('Vigar Stack'),
('Vigar Way'),
('Vigerons Way'),
('Vigers Geo'),
('Viggar Geo'),
('Viggen Way'),
('Viggory Lane'),
('Vigilance Avenue'),
('Vigilant Close'),
('Vigilant Way'),
('Vigo'),
('Vigo Avenue'),
('Vigo Close'),
('Vigo Hill'),
('Vigo Lane'),
('Vigo Sprong'),
('Vigo Village'),
('Vigor Close'),
('Vigornia Avenue'),
('Vigors Croft'),
('Vigrind'),
('Vigus Close'),
('Vihiers Close'),
('Vijay Patel Building'),
('Viking'),
('Viking Avenue'),
('Viking Bay'),
('Viking Close'),
('Viking Court'),
('Viking Drive'),
('Viking Gas Terminal'),
('Viking Grove'),
('Viking Heights'),
('Viking Meadow'),
('Viking Rise'),
('Viking Way'),
('Vikinglea Close'),
('Vikinglea Drive'),
('Vikinglea Glade'),
('Vikings Close'),
('Vikings Court'),
('Vikings Way'),
('Vilberie Close'),
('Vilberie Way'),
('Vile Skerry'),
('Vileneuve St. Georges Way'),
('Viles Park Wood'),
('Vilia Close'),
('Villa Avenue'),
('Villa Bank'),
('Villa Close'),
('Villa Court'),
('Villa Dean'),
('Villa Dean Park'),
('Villa Farm'),
('Villa Farm Close'),
('Villa Fields'),
('Villa Gloria Close'),
('Villa Grove'),
('Villa Hill'),
('Villa Lane'),
('Villa Mount'),
('Villa Park Road'),
('Villa Pond'),
('Villa Real Estate'),
('Villa Real Road'),
('Villa Rise'),
('Villa Scalabrini'),
('Villa View'),
('Villa Walk'),
('Villa Way'),
('Villafield Avenue'),
('Villafield Drive'),
('Villafield Loan'),
('Village Acres'),
('Village Avenue'),
('Village Centre'),
('Village Close'),
('Village Court'),
('Village Courts'),
('Village Croft'),
('Village Cross Road'),
('Village Drive'),
('Village East'),
('Village Farm'),
('Village Farm Close'),
('Village Farm Court'),
('Village Farm Drive'),
('Village Farm Road'),
('Village Fold'),
('Village Garden Mews'),
('Village Garth'),
('Village Gate'),
('Village Green'),
('Village Green Avenue'),
('Village Green Court'),
('Village Green Lane'),
('Village Green Road'),
('Village Green Way'),
('Village Hall Close'),
('Village Hall Yard'),
('Village Heights'),
('Village Jubilee Orchard'),
('Village Lake'),
('Village Lane'),
('Village Manor'),
('Village Meadow'),
('Village Mews'),
('Village Nook'),
('Village Paddock'),
('Village Park'),
('Village Park Close'),
('Village Row'),
('Village Spinney'),
('Village View'),
('Village Walks'),
('Village Way'),
('Village Way East'),
('Villagers Close'),
('Villarome'),
('Villas Court'),
('Villavon Way'),
('Villdale Avenue'),
('Ville De Paris Road'),
('Villebon Way'),
('Villeboys Close'),
('Villers Court'),
('Villers View'),
('Villes Lane'),
('Villette Brook Street'),
('Villette Close'),
('Villette Grove'),
('Villette Path'),
('Villice Bay'),
('Villice Lane'),
('Villier Court'),
('Villier Drive'),
('Villiers Avenue'),
('Villiers Close'),
('Villiers Court'),
('Villiers Drive'),
('Villiers Grove'),
('Villiers Lane'),
('Villiers Mead'),
('Villiers Russell Close'),
('Villiers Square'),
('Villiers Way'),
('Villiers  Sur  Marne Avenue'),
('Villigar'),
('Vilner Lane'),
('Viltham Copse'),
('Vilts Coppice'),
('Vilverie Mead'),
('Vimiera Close'),
('Vimoutiers Court'),
('Vimpany Close'),
('Vimpennys Lane'),
('Vimy Avenue'),
('Vimy Close'),
('Vimy Drive'),
('Vimy Ridge'),
('Vin Field'),
('Vinalls Copse'),
('Vinca Grove'),
('Vincam Close'),
('Vince Close'),
('Vince Dunn Mews'),
('Vince Moor Wood'),
('Vincent'),
('Vincent Avenue'),
('Vincent Carey Road'),
('Vincent Close'),
('Vincent Court'),
('Vincent Drift'),
('Vincent Drive'),
('Vincent Farm Mews'),
('Vincent Grove'),
('Vincent Hills'),
('Vincent Lane'),
('Vincent Mews'),
('Vincent Parade'),
('Vincent Pits'),
('Vincent Rise'),
('Vincent Row'),
('Vincent Square'),
('Vincent View'),
('Vincent Way'),
('Vincents Close'),
('Vincents Grove'),
('Vincents Lake'),
('Vincents Walk'),
('Vincents Way'),
('Vincenzo Close'),
('Vincenzo Lunardi Place'),
('Vinces Court'),
('Vinculum Way'),
('Vindelis Way'),
('Vindex Close'),
('Vindomis Close'),
('Vine Acre'),
('Vine Avenue'),
('Vine Bank'),
('Vine Bank Road'),
('Vine Close'),
('Vine Coppice'),
('Vine Court'),
('Vine Court Road'),
('Vine Drive'),
('Vine End'),
('Vine Farm'),
('Vine Farm Close'),
('Vine Farm Road'),
('Vine Farm Yard'),
('Vine Fold'),
('Vine Garth'),
('Vine Geo'),
('Vine Grove'),
('Vine Grove Court'),
('Vine Grove Gardens'),
('Vine Hill'),
('Vine Hill Close'),
('Vine Hill Drive'),
('Vine House Close'),
('Vine House Gardens'),
('Vine Lands'),
('Vine Lane'),
('Vine Mews'),
('Vine Moor'),
('Vine Orchard'),
('Vine Park Avenue'),
('Vine Park Drive'),
('Vine Passage'),
('Vine Row'),
('Vine Square'),
('Vine Street Bridge'),
('Vine Tree Avenue'),
('Vine Tree Close'),
('Vine Tree Court'),
('Vine Tree Terrace'),
('Vine Walk'),
('Vine Way'),
('Vine Yard'),
('Vineburgh Avenue'),
('Vineburgh Court'),
('Vinefield Court'),
('Vinefields'),
('Vinegar Cove'),
('Vinegar Hill'),
('Vinegar Lane'),
('Vinegar Spring'),
('Vinegar Yard'),
('Vinegars Shaw'),
('Vinegarth'),
('Vinehall Close'),
('Vinehall Forest'),
('Vinehouse Close'),
('Viner Close'),
('Viner Way'),
('Vineries Bank'),
('Vineries Close'),
('Viners Close'),
('Viners Lane'),
('Vinery Avenue'),
('Vinery Close'),
('Vinery Court'),
('Vinery Grove'),
('Vinery Lane'),
('Vinery Meadow'),
('Vinery Mount'),
('Vinery Park'),
('Vinery View'),
('Vinery Way'),
('Vines Avenue'),
('Vines Brake'),
('Vines Court'),
('Vines Cross'),
('Vines Cross Road'),
('Vines Gate Shaw'),
('Vines Lane'),
('Vinescroft'),
('Vinesend Lane'),
('Vineside'),
('Vinetrees'),
('Viney Avenue'),
('Viney Bank'),
('Viney Close'),
('Viney Hill'),
('Viney Lane'),
('Vineyard'),
('Vineyard Avenue'),
('Vineyard Bottom'),
('Vineyard Close'),
('Vineyard Clump'),
('Vineyard Coppice'),
('Vineyard Copse'),
('Vineyard Cottages'),
('Vineyard Court'),
('Vineyard Drive'),
('Vineyard Gate'),
('Vineyard Grove'),
('Vineyard Hill'),
('Vineyard Hill Road'),
('Vineyard Lane'),
('Vineyard Path'),
('Vineyard Row'),
('Vineyard Shaw'),
('Vineyard Spring'),
('Vineyard Vale'),
('Vineyard Walk'),
('Vineyard Way'),
('Vineyards Brake'),
('Vineyards Close'),
('Vineyards Lane'),
('Vineycroft Lane'),
('Vineys Copse'),
('Vineys Yard'),
('Vingoes Lane'),
('Vingsteen'),
('Vinicombe Lane'),
('Vining Common'),
('Vining Copse'),
('Vining Walk'),
('Vinings Hill'),
('Vink'),
('Vinlake Avenue'),
('Vinnall Grove'),
('Vinnells Lane'),
('Vinnetrow Lake'),
('Vinney Copse'),
('Vinney Lane'),
('Vinney Ridge Inclosure'),
('Vinneys Close'),
('Vinnick Rock'),
('Vinnicombes Covert'),
('Vinns Lane'),
('Vinny Avenue'),
('Vinny Combe'),
('Vinny Den'),
('Vinny Green'),
('Vinquin Hill'),
('Vinquoy Hill'),
('Vins Geo'),
('Vins Taing'),
('Vinson Close'),
('Vinstone Way'),
('Vinstra Close'),
('Vinstrick Ness'),
('Vint Rise'),
('Vintage Close'),
('Vintage Mews'),
('Vinten Close'),
('Vinters Avenue'),
('Vinters Park'),
('Vinters Way'),
('Vintery Leys'),
('Vinthill Withy Bed'),
('Vintin Lane'),
('Vintner Close'),
('Vintners Close'),
('Vintners Court'),
('Vintners Mews'),
('Vintners Way'),
('Vintry'),
('Vintry Mews'),
('Vinyard Close'),
('Viol Moor'),
('Viola Avenue'),
('Viola Bank'),
('Viola Close'),
('Viola Croft'),
('Viola Drive'),
('Viola Square'),
('Viola Way'),
('Violet Avenue'),
('Violet Bank'),
('Violet Bank Road'),
('Violet Close'),
('Violet Court'),
('Violet Croft'),
('Violet Drive'),
('Violet Farm Close'),
('Violet Grove'),
('Violet Hill'),
('Violet Hill Clump'),
('Violet Hill Copse'),
('Violet Hill Road'),
('Violet Lane'),
('Violet Row'),
('Violet Spinney'),
('Violet Street North'),
('Violet Strip'),
('Violet Walk'),
('Violet Way'),
('Violets Close'),
('Violets Lane'),
('Violets Spring'),
('Viper Hall Wood'),
('Vipoints Hill'),
('Vir Vaa'),
('Virda'),
('Virda Dale'),
('Virda Field'),
('Virda Geo'),
('Virda Loch'),
('Virda Pund'),
('Virda Vatn'),
('Virda Water'),
('Virdi Field'),
('Virdi Geos'),
('Virdi Point'),
('Virdi Taing'),
('Virdi Water'),
('Virdik'),
('Virdins'),
('Vire Island'),
('Virgate'),
('Virgil Court'),
('Virgil Drive'),
('Virgin Hill'),
('Virgin Hill Wood'),
('Virgin Moss'),
('Virgin Square'),
('Virginia'),
('Virginia Avenue'),
('Virginia Chase'),
('Virginia Close'),
('Virginia Court'),
('Virginia Drive'),
('Virginia Grove'),
('Virginia Orchard'),
('Virginia Park Road'),
('Virginia Water'),
('Virginia Way'),
('Virgins Corner Wood'),
('Virgins Croft'),
('Virgins Lane'),
('Virgins Spring'),
('Virginsalley Lane'),
('Virginstow'),
('Viridian Mews'),
('Viridian Square'),
('Virley'),
('Virley Channel'),
('Virley Close'),
('Virnells Copse'),
('Virtle Rock'),
('Virtue Close'),
('Virtue Well View'),
('Virtuewell Glen'),
('Virva'),
('Virworthy'),
('Visa View'),
('Viscar'),
('Viscount Avenue'),
('Viscount Close'),
('Viscount Court'),
('Viscount Drive'),
('Viscount Evan Drive'),
('Viscount Gate'),
('Viscount Grove'),
('Viscount Mews'),
('Viscount Square'),
('Viscount Walk'),
('Viscount Way'),
('Viscounts Pend'),
('Vishall Hill'),
('Vision Hill Road'),
('Vision West Nottinghamshire Collegre'),
('Visitors Hill'),
('Vislok Close'),
('Vissett Close'),
('Vissitt Lane'),
('Vista Avenue'),
('Vista Close'),
('Vista Court'),
('Vista Drive'),
('Vista Green'),
('Vista Rise'),
('Vista Way'),
('Vista  Del  Mar'),
('Vistavird'),
('Vitali Close'),
('Vitllus Close'),
('Vitriol Square'),
('Vitruvius Court'),
('Vitruvius Way'),
('Vittery Close'),
('Vittle Drive'),
('Vittoria Close'),
('Vittoria Dock'),
('Vittoria Walk'),
('Viva Way'),
('Vivaldi Close'),
('Vivaldi Court'),
('Vivaldi Drive'),
('Vivars Way'),
('Vivary Bridge'),
('Vivary Way'),
('Viveash Close'),
('Viveham'),
('Viver'),
('Viver Green'),
('Viver Lane'),
('Viverdon Down'),
('Vivers Hill'),
('Vivian Avenue'),
('Vivian Close'),
('Vivian Comma Close'),
('Vivian Court'),
('Vivian Drive'),
('Vivian Park'),
('Vivian Park Drive'),
('Vivian Square'),
('Vivian Way'),
('Vivians Covert'),
('Vivid Approach'),
('Vivien Avenue'),
('Vivien Close'),
('Vivienne Close'),
('Vivienne Cohen House'),
('Vivienne Smith Lane'),
('Vivilie Loch'),
('Vivis Lane'),
('Vivod Mountain'),
('Vixen Close'),
('Vixen Court'),
('Vixen Drive'),
('Vixen Grove'),
('Vixen Gully'),
('Vixen Tor'),
('Vixen Tor Close'),
('Vixen Track'),
('Vixen Walk'),
('Vixen Way'),
('Viyella Mews'),
('Vizard Close'),
('Vize Lane'),
('Vlissingen Drive'),
('Voake Close'),
('Voases Close'),
('Voases Lane'),
('Vobster'),
('Vobster Hill'),
('Voces Lane'),
('Vochums Cleuch'),
('Vockins Close'),
('Vocus Copse'),
('Voder'),
('Voder View'),
('Vodmore Copse'),
('Vodo Meadow'),
('Voe'),
('Voe Botn'),
('Voe Drus'),
('Voe of Browland'),
('Voe of Clousta'),
('Voe of Cullingsburgh'),
('Voe of Dale'),
('Voe of Footabrough'),
('Voe of Leiraness'),
('Voe of Littlure'),
('Voe of North House'),
('Voe of Rumble'),
('Voe of Scatsta'),
('Voe of Setter'),
('Voe of Snarraness'),
('Voe of Sound'),
('Voe of the Brig'),
('Voe of the Mels'),
('Voe of Vaila'),
('Voel  y  crio'),
('Voes Bottom'),
('Voewood Close'),
('Vog Minn'),
('Vog Skerry'),
('Vogan Avenue'),
('Vogan Close'),
('Vogans Point'),
('Vogans Voe'),
('Vogue'),
('Vogue Beloth'),
('Vogue Close'),
('Vogue Hill'),
('Vogus Lane'),
('Vogwell Down'),
('Voil Drive'),
('Voils Grove'),
('Voisey Close'),
('Vokes Close'),
('Vokes Way'),
('Volage Court'),
('Volans Drive'),
('Volans Lane'),
('Volante Close'),
('Volante Drive'),
('Volary Grove'),
('Volcanic Dyke'),
('Vole'),
('Vole Close'),
('Vole Court'),
('Voley'),
('Voley Close'),
('Voley Lane'),
('Volis Hill'),
('Vollans Court'),
('Vollards Lane'),
('Voller Drive'),
('Vollgastell'),
('Vollum Rise'),
('Volpe Close'),
('Volri Geo'),
('Volridge Copse'),
('Volt Avenue'),
('Volta Close'),
('Volta Rise'),
('Volta Way'),
('Voltaire Avenue'),
('Voltigeur Drive'),
('Volunteer Avenue'),
('Volunteer Close'),
('Volunteer Fields'),
('Volunteer Way'),
('Volunteers Green'),
('Volwycke Avenue'),
('Vomit Point'),
('Vong Lane'),
('Vongs'),
('Vord Hill'),
('Vorfield Close'),
('Vorlich Avenue'),
('Vorlich Court'),
('Vorlich Drive'),
('Vorlich Way'),
('Vorrap'),
('Vorrap Zawn'),
('Voryn Avenue'),
('Vose Close'),
('Vosper Croft'),
('Vosporth Hill'),
('Voss Court'),
('Voss Park Close'),
('Voss Park Drive'),
('Vosss Lane'),
('Vosss Moor'),
('Vostock Close'),
('Voter Run'),
('Votersay'),
('Voulsdon Copse'),
('Vounder Close'),
('Vounder Glaze'),
('Voundervour Lane'),
('Vounog Hill'),
('Vow Randie'),
('Vowchurch'),
('Vowchurch Close'),
('Vowchurch Common'),
('Vowchurch Way'),
('Vowell Close'),
('Vowels Lane'),
('Vowes Gorse'),
('Vowles Bottom'),
('Vowles Close'),
('Vowley'),
('Vowley View'),
('Vownog'),
('Vownog Newydd'),
('Voxhills Copse'),
('Voxter'),
('Voxter Ness'),
('Voxter Voe'),
('Voxwell Lane'),
('Voxwill Copse'),
('Voy'),
('Voyager Close'),
('Voyager Drive'),
('Voyager Park North'),
('Voyagers Close'),
('Voyce Close'),
('Voyce Way'),
('Voylart Close'),
('Voysey Avenue'),
('Voysey Court'),
('Voysey Hill'),
('Vriskaig Point'),
('Vroe'),
('Vron Close'),
('Vron Gate'),
('Vron Square'),
('Vron Vellin Wood'),
('Vroncysyllte'),
('Vronhill Close'),
('Vroning Coppice'),
('Vryburg Close'),
('Vuefield Hill'),
('Vugga Cove'),
('Vulcan Close'),
('Vulcan Court'),
('Vulcan Croft'),
('Vulcan Drive'),
('Vulcan Gate'),
('Vulcan Mews'),
('Vulcan Park Way'),
('Vulcan View'),
('Vulcan Village'),
('Vulcan Way'),
('Vulcans Lane'),
('Vulscombe Lane'),
('Vyne Close'),
('Vyne Meadow'),
('Vyne Walk'),
('Vyner Close'),
('Vyner Croft'),
('Vyner Grove'),
('Vyner Park'),
('Vyners Close'),
('Vyners Way'),
('Vynes Close'),
('Vynes Way'),
('Vyrnwy Close'),
('Vyrnwy Grove'),
('Vyrnwy'),
('Vyrnwy Way'),
('Vyse Close'),
('Vyse Drive'),
('Vyse Lane'),
('Vyvyan Court'),
('Vyvyan Drive'),
('Vyvyan Spinney'),
('Vacoas  Phoenix'),
('Vadodara'),
('Valdivia'),
('Valencia'),
('Valenzuela'),
('Valera'),
('Valinhos'),
('Valladolid'),
('Valle de Chalco'),
('Valledupar'),
('Vallejo'),
('Valparaíso de Goiás'),
('Valparaíso'),
('Valsad'),
('Van'),
('Vancouver'),
('Vantaa'),
('Vapi'),
('Varamin'),
('Varanasi'),
('Varginha'),
('Varna'),
('Várzea Grande'),
('Várzea Paulista'),
('Vasai  Virar'),
('Västerås'),
('Vaughan'),
('Veliky Novgorod'),
('Vellore'),
('Venlo'),
('Veracruz'),
('Veraval'),
('Vespasiano'),
('Viamão'),
('Vicente López'),
('Vicenza'),
('Victorville'),
('Vidisha'),
('Vienna'),
('Vientiane'),
('Vihiga'),
('Vijayawada'),
('Vila Nova de Gaia'),
('Vila Velha'),
('Villa Alemana'),
('Villa Nueva'),
('Villahermosa'),
('Villanueva'),
('Villavicencio'),
('Villeurbanne'),
('Vilnius'),
('Viña del Mar'),
('Vinh'),
('Vinnytsia'),
('Viranşehir'),
('Virginia Beach'),
('Visakhapatnam'),
('Visalia'),
('Vitebsk'),
('Vitória da Conquista'),
('Vitória de Santo Antão'),
('Vitória'),
('Vitoria  Gasteiz'),
('Vizianagaram'),
('Vladikavkaz'),
('Vladimir'),
('Vladivostok'),
('Vlorë'),
('Volgodonsk'),
('Volgograd'),
('Vologda'),
('Volos'),
('Volta Redonda'),
('Volzhsky'),
('Voronezh'),
('Vosloorus'),
('Votorantim'),
('Vũng Tàu'),
('Vadills'),
('Valder'),
('Vale House'),
('Vale of Grwyney'),
('Vale Uxbridge Road'),
('Vallance'),
('Valleys'),
('Valls'),
('Vatch'),
('Vauld'),
('Vauntie'),
('Vennel'),
('Vennings'),
('Ventry'),
('Vere'),
('Verne'),
('Verneys'),
('Veshels'),
('Vetches'),
('Vian'),
('Viels'),
('Vilage'),
('Villa'),
('Village Barn'),
('Village Belt'),
('Vineries'),
('Vineway'),
('Vintners'),
('Violet'),
('Violets'),
('Vir'),
('Voes'),
('Voute'),
('Vro'),
('Vron'),
('Vyne');
-- Down
DELETE FROM "Placename" WHERE "keyword" LIKE 'v%';