-- Up

INSERT INTO "Placename"
("keyword")
VALUES
('Y Bae'),
('Y Bala'),
('Y Barri'),
('Y Beddau'),
('Y Berllan'),
('Y Blaenau'),
('Y Bonc'),
('Y Bont'),
('Y Bont Faen Primary School'),
('Y Bont Hir'),
('Y Bont-Faen'),
('Y Bont-faen a Llanfleiddan'),
('Y Borth'),
('Y Bracty'),
('Y Brif Heol'),
('Y Bryn'),
('Y Bwlfar'),
('Y Bwthyn'),
('Y Bwthyn The Cottage'),
('Y Castellnewydd'),
('Y Cedrwydd'),
('Y Cedrwydden'),
('Y Ceffyl'),
('Y Ceunant'),
('Y Cilffordd'),
('Y Cilgant'),
('Y Clas-ar-Wy'),
('Y Clawdd'),
('Y Clawstrau'),
('Y Clogwyn'),
('Y Clos'),
('Y Clun a Melin-cwrt'),
('Y Cocyd'),
('Y Coed'),
('Y Coed Duon'),
('Y Coleg Merthyr Tudful'),
('Y Copi'),
('Y Corsydd'),
('Y Creunant'),
('Y Crochan'),
('Y Crofft'),
('Y Crwys'),
('Y Cwcwll'),
('Y Cwm'),
('Y Cymer'),
('Y Cyswllt'),
('Y Darren'),
('Y Das'),
('Y Dderwen'),
('Y Dderwen Deg'),
('Y Ddol'),
('Y Ddol Fach'),
('y Ddraenen'),
('Y Ddraenen Wen'),
('Y Ddwyberth'),
('Y Deri'),
('Y Derwydd'),
('Y Dolau'),
('Y Dolydd'),
('Y Dolydd-The Meadows'),
('Y Domen Fawr'),
('Y Drain'),
('Y Dref'),
('Y Dreflan'),
('Y Drenewydd'),
('Y Drenewydd - Canol'),
('Y Drenewydd - De'),
('Y Drenewydd - Dwyrain'),
('Y Drenewydd a Llanllwchaearn'),
('Y Drenewydd Gogledd Llanllwchaearn'),
('Y Drenewydd Gorllewin Llanllwchaearn'),
('Y Drim'),
('Y Drindod Dewi Saint'),
('Y Drindod Dewi Sant'),
('Y Drum'),
('Y Fach'),
('Y Faenor'),
('Y Fâl'),
('Y Fali'),
('Y Fan'),
('Y Farchnad'),
('Y Fawnen'),
('Y Fedwen'),
('Y Feithrinfa'),
('Y Felin'),
('Y Felin Ffrwd'),
('Y Felin Goed'),
('Y Felin Heli'),
('Y Felin Lon'),
('Y Felinheli'),
('Y Fenni'),
('Y Ferwig'),
('Y Ffald'),
('Y Ffawydden'),
('Y Ffennant'),
('Y Fferi Isaf'),
('Y Fflint'),
('Y Fflint - Castell'),
('Y Fflint - Cwnsyllt'),
('Y Fflint - Oakenholt'),
('Y Fflint - Trelawny'),
('Y Ffòr'),
('Y Ffôr'),
('Y Ffordd Wen'),
('Y Ffowndri'),
('Y Ffridd'),
('Y Ffrith'),
('Y Ffrydd'),
('Y Ffynnon Haearn'),
('Y Foel'),
('Y Foel Goch'),
('Y Foryd'),
('Y Fron'),
('Y Fronllwyd'),
('Y Gadfa'),
('Y Gadlys Aberdare Girls School'),
('Y Gaer'),
('Y Gamallt'),
('Y Gamer'),
('Y Gamlas'),
('Y Gamriw'),
('Y Ganolfan'),
('Y Garn'),
('Y Garnedd'),
('Y Garreg'),
('Y Garth'),
('Y Garw'),
('Y Gefnen'),
('Y Geibren'),
('Y Gelli'),
('Y Gelli Gandryll'),
('Y Gerddi'),
('Y Gesail'),
('Y Gifford'),
('Y Gilan'),
('Y Gilfach'),
('Y Gilfach Isaf'),
('Y Gilfach Uchaf'),
('Y Gilfach-goch'),
('Y Gilwern'),
('Y Globa Fawr'),
('Y Glog'),
('Y Glòg'),
('Y Glonc'),
('Y Glyderau'),
('Y Glyn'),
('Y Glynnor'),
('Y Goedlan'),
('Y Goedwig'),
('Y Gogarth'),
('Y Golfa'),
('Y Golff'),
('Y Gorlan'),
('Y Gors'),
('Y Gorsedd'),
('Y Graig'),
('Y Gribin'),
('Y Groes'),
('Y Groes Fagl'),
('Y Groeslon'),
('Y Groes-Wen'),
('Y Grugan'),
('Y Grysmwnt'),
('Y Gully'),
('Y Gurn'),
('Y Gurnos'),
('Y Gwernydd'),
('Y Gwter'),
('Y Gwyndy Ysgol Gyfun Cwm Rhymni'),
('Y Gyrn'),
('Y Lan'),
('Y Lanfa'),
('Y Lasinwen'),
('Y Lawnt'),
('Y Lawnt Fowlio'),
('Y Lincs'),
('Y Llan'),
('Y Llanerch'),
('Y Llannerch'),
('Y Llech'),
('Y Llest'),
('Y Llethr'),
('Y Lliwedd'),
('Y Llwyn'),
('Y Llwyni'),
('Y Login Fach Bilingual Primary School'),
('Y Lon Gam'),
('Y Lòn Gefn'),
('Y Lon Goed'),
('Y Lon Groes'),
('Y Lon Las'),
('Y Maerdy'),
('Y Maes'),
('Y Mieri'),
('Y Mot'),
('Y Mwmbwls'),
('Y Mynydd Bychan'),
('Y Nant'),
('Y Pant Comprehensive School'),
('Y Parc'),
('Y Parciau'),
('Y Penrhyn'),
('Y Pil'),
('Y Pîl'),
('Y Pinwydd'),
('Y Plantation'),
('Y Popls'),
('Y Poplys'),
('Y Porth'),
('Y Priordy'),
('Y Prom'),
('Y Rhath'),
('Y Rhigos'),
('Y Rhiw'),
('Y Rhodfa'),
('Y Rhos'),
('Y Rhws'),
('Y Rhyl'),
('Y Ro Fawr'),
('Y Ro Wen'),
('Y Sblot'),
('Y Sgwar'),
('Y Sgwâr'),
('Y Stryd Fawr'),
('Y Stryd Newydd'),
('Y Stryd Uchel'),
('Y Stryt Fawr'),
('Y Swnt'),
('Y Talar'),
('Y Teiryd'),
('Y Traeth'),
('Y Trallwng'),
('Y Trallwng - Castell'),
('Y Trallwng Gungrog'),
('Y Trallwng Llanerchyddol'),
('Y Trwyn'),
('Y Tyddyn'),
('Y Tymbl'),
('Y Waen'),
('Y Waun'),
('Y Waun - De'),
('Y Waun - Gogledd'),
('Y Waun Fach'),
('Y Weirglodd'),
('Y Wenallt'),
('Y Wennallt'),
('Y Wern'),
('Y Wern Primary School'),
('Y Wig'),
('Yaa Field'),
('Yabsley Street'),
('Yacht Haven Quay'),
('Yacht Way'),
('Yachtsman Close'),
('Yacley Close'),
('Yad Moss'),
('Yadburgh Hill'),
('Yadd Linn Wood'),
('Yaddlethorpe'),
('Yade Moss'),
('Yadhill Wood'),
('Yadhole Plantation'),
('Yadley Close'),
('Yadley Lane'),
('Yadley Way'),
('Yaffle Crescent'),
('Yaffle Road'),
('Yafford'),
('Yafford Furze Brake'),
('Yafforth'),
('Yafforth Moor'),
('Yafforth Road'),
('Yagden Hill'),
('Yaidon Coppice'),
('Yair Boat Stream'),
('Yair Drive'),
('Yair Hill Forest'),
('Yairs Rise'),
('Yalberton Copse'),
('Yalberton Road'),
('Yalbury Lane'),
('Yalbury Wood Way'),
('Yalden Close'),
('Yalden Gardens'),
('Yalden Lane'),
('Yalden Wood'),
('Yaldham'),
('Yaldhurst Copse'),
('Yaldhurst Court'),
('Yaldhurst Lane'),
('Yalding'),
('Yalding Close'),
('Yalding Drive'),
('Yalding Gardens'),
('Yalding Grove'),
('Yalding Hill'),
('Yalding Road'),
('Yalding St Peter And St Paul Church Of England (Voluntary Controlled) Primary School'),
('Yale Close'),
('Yale Crescent'),
('Yale Drive'),
('Yale Grove'),
('Yale Mews'),
('Yale Park'),
('Yale Road'),
('Yale Street'),
('Yale Way'),
('Yall Flat Lane'),
('Yalland Close'),
('Yalland Warren'),
('Yallands Hill'),
('Yallop Avenue'),
('Yallop Way'),
('Yalta Close'),
('Yalts Brow'),
('Yamburg Road'),
('Yamna Field'),
('Yamson Coppice'),
('Yamson Plantation'),
('Yan Brow'),
('Yanel Lane'),
('Yanhey Copse'),
('Yanhey Hill'),
('Yanhey Moor'),
('Yanleigh Close'),
('Yanley'),
('Yanley Lane'),
('Yannon Drive'),
('Yannon Lane'),
('Yannon Terrace'),
('Yannons Court'),
('Yannons Road'),
('Yans Lane'),
('Yantlet Beach'),
('Yantlet Drive'),
('Yanwath'),
('Yanwath and Eamont Bridge'),
('Yanwath Primary School'),
('Yanwath Street'),
('Yanwath Wood'),
('Yanwath Woodhouse Plantation'),
('Yanworth'),
('Yanworth Common'),
('Yanworth Long Acre'),
('Yanworth Wood'),
('Yapham'),
('Yapham Common'),
('Yapham Road'),
('Yapham Wood'),
('Yapin Hill'),
('Yappers Wood'),
('Yapsel Bank'),
('Yapton'),
('Yapton Church Of England Primary School'),
('Yapton Lane'),
('Yapton Road'),
('Yapton Street'),
('Yar Neap'),
('Yar Tor'),
('Yarberry'),
('Yarborough'),
('Yarborough Close'),
('Yarborough Crescent'),
('Yarborough Croft'),
('Yarborough Drive'),
('Yarborough Primary School'),
('Yarborough Rise'),
('Yarborough Road'),
('Yarborough Terrace'),
('Yarborough Wood'),
('Yarbridge'),
('Yarbridge Close'),
('Yarbrook'),
('Yarburgh'),
('Yarburgh Close'),
('Yarburgh Grove'),
('Yarburgh Plantation'),
('Yarburgh Road'),
('Yarburgh Street'),
('Yarburgh Way'),
('Yarbury Combe'),
('Yarbury Way'),
('Yarcombe'),
('Yarcombe Close'),
('Yarcombe Wood'),
('Yard Close'),
('Yard Coal Rise'),
('Yard Copse'),
('Yard Court'),
('Yard Down'),
('Yard Downs Lane'),
('Yard Drove'),
('Yard Drove Withy Bed'),
('Yard Four'),
('Yard Hill'),
('Yard Lane'),
('Yard Mead'),
('Yard Plantation'),
('Yard Road'),
('Yard Row'),
('Yard Steel'),
('Yard Wood'),
('Yardbury Hill Road'),
('Yarde'),
('Yarde Alders'),
('Yarde Close'),
('Yarde Copse'),
('Yarde Farm'),
('Yarde Hill Orchard'),
('Yarde Lane'),
('Yarde Mead'),
('Yarde Place'),
('Yarde Wood'),
('Yardelands'),
('Yardelands Close'),
('Yardheads'),
('Yardhope Flow'),
('Yardhurst Gardens'),
('Yardie'),
('Yardington'),
('Yardlea Close'),
('Yardlee Walk'),
('Yardley'),
('Yardley Avenue'),
('Yardley Birmingham'),
('Yardley Chase Road'),
('Yardley Close'),
('Yardley Court'),
('Yardley Drive'),
('Yardley East'),
('Yardley Fields'),
('Yardley Fields Road'),
('Yardley Gardens'),
('Yardley Gobion'),
('Yardley Gobion Church Of England Primary School'),
('Yardley Green Road'),
('Yardley Grove'),
('Yardley Hall Lane'),
('Yardley Hastings'),
('Yardley Hastings Primary School'),
('Yardley Hill'),
('Yardley Lane'),
('Yardley Park Road'),
('Yardley Place'),
('Yardley Primary School'),
('Yardley Road'),
('Yardley Square'),
('Yardley Street'),
('Yardley Way'),
('Yardley West & Stechford'),
('Yardley Wood'),
('Yardley Wood Community Primary School'),
('Yardley Wood Road'),
('Yardleys School'),
('Yardro'),
('Yards Brake'),
('Yards Hill'),
('Yards Lane'),
('Yards Lane'),
('Yards Plantation'),
('Yards South Coppice'),
('Yards West Coppice'),
('Yardside Road'),
('Yardstone Knowe'),
('Yardwall Manor Farm Solar Park'),
('Yardwall Road'),
('Yardworthy'),
('Yardy Close'),
('Yard-yr-Odyn Wood'),
('Yare and All Saints'),
('Yare Avenue'),
('Yare Close'),
('Yare Grove'),
('Yare Road'),
('Yare Street'),
('Yare Valley Drive'),
('Yare Valley Rise'),
('Yare View Close'),
('Yare Way'),
('Yarfils Wick'),
('Yarford'),
('Yarhampton'),
('Yarhampton Cross'),
('Yarker Bank Lane'),
('Yarker Lane'),
('Yarkhill'),
('Yarkhill Marsh'),
('Yarl Meadow'),
('Yarl Well'),
('Yarlands'),
('Yarlet'),
('Yarlet Croft'),
('Yarlet Hill'),
('Yarlet Lane'),
('Yarlet Wood'),
('Yarley'),
('Yarley Field Lane'),
('Yarley Hill'),
('Yarlington'),
('Yarlington Close'),
('Yarlington Mill'),
('Yarlington Orchard'),
('Yarls Wood'),
('Yarlsber'),
('Yarlsey Hill'),
('Yarlsey Moss'),
('Yarlside'),
('Yarlside Close'),
('Yarlside Crescent'),
('Yarlside Hill'),
('Yarlside Lane'),
('Yarlside Primary School'),
('Yarlside Road'),
('Yarm'),
('Yarm Back Lane'),
('Yarm Close'),
('Yarm Court Road'),
('Yarm Holt'),
('Yarm Lane'),
('Yarm Place'),
('Yarm Primary School'),
('Yarm Road'),
('Yarm School'),
('Yarm Street'),
('Yarm Way'),
('Yarmer Head'),
('Yarmleigh Copse'),
('Yarmleigh Lane'),
('Yarmley Lane'),
('Yarmouth'),
('Yarmouth Avenue'),
('Yarmouth Church Of England (Aided) Primary School'),
('Yarmouth Close'),
('Yarmouth Crescent'),
('Yarmouth Drive'),
('Yarmouth Ferry Terminal'),
('Yarmouth Gardens'),
('Yarmouth Green'),
('Yarmouth Harbour'),
('Yarmouth Nelson and Southtown'),
('Yarmouth North'),
('Yarmouth North and Central'),
('Yarmouth Place'),
('Yarmouth Road'),
('Yarmouth Roads'),
('Yarmouth Sand'),
('Yarmouth Street'),
('Yarmouth Way'),
('Yarmshaw Plantations'),
('Yarn Avenue'),
('Yarn Barton'),
('Yarn Close'),
('Yarn Cole'),
('Yarn Copse'),
('Yarn Croft'),
('Yarn Hill'),
('Yarn Hill Covert'),
('Yarn Lane'),
('Yarn Mill Close'),
('Yarn Street'),
('Yarn Walk'),
('Yarn Windle Plantation'),
('Yarnacott'),
('Yarnbarton'),
('Yarnborough Hill'),
('Yarnbrook'),
('Yarnbrook Grove'),
('Yarnbrook Road'),
('Yarnbury Castle'),
('Yarnbury Close'),
('Yarncliff Close'),
('Yarncliff Wood'),
('Yarneford Copse'),
('Yarnells Hill'),
('Yarnells Road'),
('Yarner Beacon'),
('Yarner Close'),
('Yarner Wood'),
('Yarnest Wood'),
('Yarnfield'),
('Yarnfield Close'),
('Yarnfield Common Wood'),
('Yarnfield Croft'),
('Yarnfield Lane'),
('Yarnfield Parkway'),
('Yarnfield Primary School'),
('Yarnfield Road'),
('Yarngallows Knowe'),
('Yarngrove Wood'),
('Yarnhams Close'),
('Yarnhams Copse'),
('Yarnicombe Wood'),
('Yarningale Close'),
('Yarningale Common'),
('Yarningale Coppice'),
('Yarningale Lane'),
('Yarningale Road'),
('Yarningdale Avenue'),
('Yarninknowle Wood'),
('Yarnmakers Path'),
('Yarnold Close'),
('Yarnold Lane'),
('Yarnolds'),
('Yarns Hill'),
('Yarnscombe'),
('Yarnsdale'),
('Yarnshaw Hill'),
('Yarnside Close'),
('Yarnspath Law'),
('Yarnsworth Road'),
('Yarnton'),
('Yarnton Close'),
('Yarnton Court'),
('Yarnton Lane'),
('Yarnton Road'),
('Yarnton Way'),
('Yarpole'),
('Yarpole Lane'),
('Yarr Dale'),
('Yarr Mill Close'),
('Yarra Road'),
('Yarrangall Green'),
('Yarranton Close'),
('Yarraville Street'),
('Yarrell Croft'),
('Yarrell Mead'),
('Yarrells Close'),
('Yarrells Drive'),
('Yarrells Lane'),
('Yarrells Preparatory School'),
('Yarrington Way'),
('Yarrow'),
('Yarrow Avenue'),
('Yarrow Close'),
('Yarrow Court'),
('Yarrow Crescent'),
('Yarrow Drive'),
('Yarrow Gardens'),
('Yarrow Gardens Lane'),
('Yarrow Gate'),
('Yarrow Grove'),
('Yarrow Hill'),
('Yarrow Mead'),
('Yarrow Park'),
('Yarrow Place'),
('Yarrow Point'),
('Yarrow Primary School'),
('Yarrow Reservoir'),
('Yarrow Road'),
('Yarrow Slake'),
('Yarrow Street'),
('Yarrow Terrace'),
('Yarrow Valley Way'),
('Yarrow Walk'),
('Yarrow Way'),
('Yarrowbank Plantation'),
('Yarrowford'),
('Yarrows Hill'),
('Yarrowside'),
('Yarsop'),
('Yartleton Lane'),
('Yartor Down'),
('Yarty'),
('Yarty Copse'),
('Yarwell'),
('Yarwell Close'),
('Yarwell Drive'),
('Yarwell Junction'),
('Yarwell Road'),
('Yarwell Square'),
('Yarwells Headland'),
('Yarwells Walk'),
('Yarwood Avenue'),
('Yarwood Close'),
('Yarwood Drive'),
('Yarwood Grove'),
('Yarwood Heath'),
('Yarwood Road'),
('Yarwood Street'),
('Yarwoodheath Covert'),
('Yarwoodheath Lane'),
('Yasmin Gardens'),
('Yate'),
('Yate and Pickup Bank'),
('Yate Central'),
('Yate Grove'),
('Yate Lane'),
('Yate North'),
('Yate Road'),
('Yate Rocks'),
('Yate Sills'),
('Yate Street'),
('Yateholm Drive'),
('Yateholme Reservoir'),
('Yatehouse Green'),
('Yatehouse Lane'),
('Yateley'),
('Yateley Avenue'),
('Yateley Close'),
('Yateley Common'),
('Yateley Crescent'),
('Yateley Drive'),
('Yateley East'),
('Yateley East & Blackwater'),
('Yateley Heath Wood'),
('Yateley Manor School'),
('Yateley Road'),
('Yateley School'),
('Yateley Street'),
('Yateley West'),
('Yately Close'),
('Yates Avenue'),
('Yates Close'),
('Yates Copse'),
('Yates Copse'),
('Yates Court'),
('Yates Court'),
('Yates Croft'),
('Yates Drive'),
('Yates Flat'),
('Yates Fold'),
('Yates Gardens'),
('Yates Grove'),
('Yates Hay Road'),
('Yates Lane'),
('Yates Meadow'),
('Yates Plantation'),
('Yates Road'),
('Yates Street'),
('Yates Way'),
('Yates Wood'),
('Yatesbury'),
('Yatesbury Avenue'),
('Yatesbury Close'),
('Yatesbury Copse'),
('Yatesbury Crescent'),
('Yatesbury Field'),
('Yatesbury Garth'),
('Yatesbury Lane'),
('Yatesbury Road'),
('Yatesbury Withybed'),
('Yatesfield Hill'),
('Yatland Copse'),
('Yatscombe Copse'),
('Yatt Wood'),
('Yattendon'),
('Yattendon Avenue'),
('Yattendon Church Of England Primary School'),
('Yattendon Lane'),
('Yattendon Road'),
('Yattendon School'),
('Yatton'),
('Yatton (Voluntary Controlled) Infant School'),
('Yatton Church Of England Voluntary Controlled Juni'),
('Yatton Church Of England Voluntary Controlled Junior School'),
('Yatton Close'),
('Yatton Hall Nursing Home'),
('Yatton Hill'),
('Yatton Keynell'),
('Yatton Road'),
('Yatton Wood'),
('Yatts'),
('Yatts Road'),
('Yaud Sike lane'),
('Yaugher Lane'),
('Yaugher Shaw'),
('Yaugher Woods'),
('Yaul Sike Slack'),
('Yaverland'),
('Yaverland Close'),
('Yaverland Drive'),
('Yaverland Road'),
('Yavneh College'),
('Yaw Yeat Wood'),
('Yawl'),
('Yawl Bottom'),
('Yawl Hill'),
('Yawl Hill Lane'),
('Yawling Gate Road'),
('Yawlings Wood'),
('Yawthorpe'),
('Yawthorpe Fox Covert'),
('Yaxes Plantation'),
('Yaxham'),
('Yaxham Primary School'),
('Yaxham Road'),
('Yaxham Wood'),
('Yaxley'),
('Yaxley & Farcet'),
('Yaxley Close'),
('Yaxley Court'),
('Yaxley Fen'),
('Yaxley Hall Lane'),
('Yaxley Infant School'),
('Yaxley Loke'),
('Yaxley Meadow'),
('Yaxley Place'),
('Yaxley Road'),
('Yaxley Way'),
('Yaxleys Lane'),
('Yazor'),
('Yazor Road'),
('Yazor Wood'),
('Y-Ddol'),
('Ye Farre Close'),
('Ye Meads'),
('Yea Fold'),
('Yea of Migganess'),
('Yeabridge'),
('Yeabsleys Way'),
('Yeading'),
('Yeading Avenue'),
('Yeading Fork'),
('Yeading Gardens'),
('Yeading Infant And Nursery School'),
('Yeading Junior School'),
('Yeading Lane'),
('Yeadon'),
('Yeadon Close'),
('Yeadon Court'),
('Yeadon Drive'),
('Yeadon Gardens'),
('Yeadon Garth'),
('Yeadon Grove'),
('Yeadon Moor'),
('Yeadon Moor Road'),
('Yeadon Road'),
('Yeadon Tarn'),
('Yeadon Walk'),
('Yeadon Way'),
('Yeadon Westfield Infant School'),
('Yeadon Westfield Junior School'),
('Yeager Court'),
('Yealand Avenue'),
('Yealand Church Of England Primary School'),
('Yealand Close'),
('Yealand Conyers'),
('Yealand Drive'),
('Yealand Grove'),
('Yealand Redmayne'),
('Yealand Road'),
('Yealand Storrs'),
('Yeald Brow'),
('Yeald Wood'),
('Yealm Close'),
('Yealm Grove'),
('Yealm Park'),
('Yealm Pool'),
('Yealm Road'),
('Yealm Steps'),
('Yealm View Road'),
('Yealmbridge'),
('Yealmbury Hill'),
('Yealmpstone Close'),
('Yealmpstone Drive'),
('Yealmpstone Farm Primary School'),
('Yealmpton'),
('Yealmpton Primary School'),
('Yeals Combe'),
('Yeals Combe'),
('Yealscombe Lane'),
('Yealscombe Wood'),
('Yeaman Lane'),
('Yeaman Place'),
('Yeaman Shore'),
('Yeaman Street'),
('Yeamans Alley'),
('Yeamans Lane'),
('Yeames Close'),
('Yeams Plantation'),
('Yeaps Drove'),
('Yearby'),
('Yearby Bank'),
('Yearby Bank Plantation'),
('Yearby Close'),
('Yearby Crescent'),
('Yearby Road'),
('Yearby Wood'),
('Yeardsley Avenue'),
('Yeardsley Close'),
('Yeardsley Green'),
('Yeardsley Lane'),
('Yearl Hill'),
('Yearl Rise'),
('Yearles Wood'),
('Yearling Chase'),
('Yearling Close'),
('Yearlings Bottom'),
('Yearlings Coppice'),
('Yearlings Drove'),
('Yearlstone Square'),
('Yearly Auld Hole'),
('Yearmoor Lane'),
('Yearn Cleuch'),
('Yearn Cleugh'),
('Yearn Hope'),
('Yearngill'),
('Yearngill Head'),
('Yearning Cleuch'),
('Yearning Law'),
('Yearnor'),
('Yearnor Mill Lane'),
('Yearnor Wood'),
('Yearnslow'),
('Yearsett Coppice'),
('Yearsley'),
('Yearsley Crescent'),
('Yearsley Cross'),
('Yearsley Grove'),
('Yearsley Grove Primary School'),
('Yearsley Moor'),
('Yearsley Moor Bank'),
('Yearsley Plantation'),
('Yearsleys Lane'),
('Yeat House'),
('Yeate Street'),
('Yeates Arce'),
('Yeates Close'),
('Yeates Court'),
('Yeates Drive'),
('Yeates Field View'),
('Yeates Road'),
('Yeathouse Road'),
('Yeatlands Coppice'),
('Yeatman Close'),
('Yeatman Hospital'),
('Yeatman Road'),
('Yeatmans Close'),
('Yeatmans Lane'),
('Yeatminster Road'),
('Yeaton'),
('Yeats Close'),
('Yeats Drive'),
('Yeats Road'),
('Yeats Way'),
('Yeatsall Road'),
('Yeatt Copse'),
('Yeaveley'),
('Yeavering'),
('Yeavering Bell'),
('Yeavering Close'),
('Yeckhouse Lane'),
('Yederick Road'),
('Yederick Woods'),
('Yedingham'),
('Yedman Dale'),
('Yedmandale Road'),
('Yedmandale Woods'),
('Yeend Close'),
('Yeftly Drive'),
('Yehudi Menuhin School'),
('Yelcombe Bottom'),
('Yelcombe Drove'),
('Yeld Bank'),
('Yeld Close'),
('Yeld Hall Road'),
('Yeld Lane'),
('Yeld Road'),
('Yeld Wood'),
('Yelden'),
('Yelden Close'),
('Yelden Spinney'),
('Yelden Wold'),
('Yeldersley'),
('Yeldersley Close'),
('Yeldersley Court'),
('Yeldersley Lane'),
('Yeldham'),
('Yeldham Lock'),
('Yeldham Mews'),
('Yeldham Place'),
('Yeldham Road'),
('Yeldon Close'),
('Yeldon Court'),
('Yelds Hill'),
('Yelds Rough'),
('Yelds Wood'),
('Yeldside Gardens'),
('Yelford'),
('Yelfs Road'),
('Yell'),
('Yell Bank'),
('Yell Dingle'),
('Yell Hill'),
('Yell Pool'),
('Yell Rough'),
('Yell Sound'),
('Yell Wood'),
('Yella Moor'),
('Yellaford Way'),
('Yelland'),
('Yelland Common Wood'),
('Yelland Coppice'),
('Yelland Copse'),
('Yelland Cross'),
('Yelland Lane'),
('Yelland Moor'),
('Yelland Plantation'),
('Yelland Road'),
('Yelland Walk'),
('Yelland Wood'),
('Yellands'),
('Yellands Moor'),
('Yellands Park'),
('Yellaton Lane'),
('Yellaton Wood'),
('Yelling'),
('Yellingmill Lane'),
('Yellison Wood'),
('Yellnowte Isle'),
('Yellow Ark'),
('Yellow Batches Drove'),
('Yellow Bog'),
('Yellow Brae'),
('Yellow Brook Close'),
('Yellow Carn'),
('Yellow Carn Porth'),
('Yellow Craig'),
('Yellow Craig Head'),
('Yellow Craig Plantation'),
('Yellow Craigs'),
('Yellow Falls'),
('Yellow Fawns'),
('Yellow Hammer Rock'),
('Yellow Head'),
('Yellow Hill'),
('Yellow Hill Wood'),
('Yellow Horse'),
('Yellow House Lane'),
('Yellow Hundred Close'),
('Yellow Isle'),
('Yellow Lake'),
('Yellow Lane'),
('Yellow Ledge'),
('Yellow Lodge Drive'),
('Yellow Moss'),
('Yellow Muir'),
('Yellow Nose'),
('Yellow Post'),
('Yellow Quarry Wood'),
('Yellow Rabbit Hills'),
('Yellow Rock'),
('Yellow Rocks'),
('Yellow Rocks of Splears'),
('Yellow School Copse'),
('Yellow Stack'),
('Yellow Stone'),
('Yellow Top'),
('Yellow Tor Court'),
('Yellow Tor Lane'),
('Yellow Way Road'),
('Yellow Withy Bed'),
('Yellowberries Copse'),
('Yellowcar'),
('Yellowcar Hole'),
('Yellowcoat Wood'),
('Yellowcombe Lane'),
('Yellowcombe Plantation'),
('Yellowcraig Plantation'),
('Yellowcraig Wood'),
('Yellowcress Drive'),
('Yellowdales Plantation'),
('Yellowfauld Wood'),
('Yellowford'),
('Yellowgate Road'),
('Yellowham Hill'),
('Yellowham Wood'),
('Yellowhammer Close'),
('Yellowhammer Court'),
('Yellowhammer Crescent'),
('Yellowhammer Drive'),
('Yellowhammer Road'),
('Yellowhammers'),
('Yellowhill Road'),
('Yellowley Court'),
('Yellowmead Down'),
('Yellowmead Road'),
('Yellowpine Way'),
('Yellowstone Close'),
('Yellowtor Road'),
('Yellow-Wort'),
('Yells Plantation'),
('Yells Way'),
('Yells Wood'),
('Yelmacott Moor'),
('Yelnow Lane'),
('Yelnow Plantation'),
('Yelsted'),
('Yelsted Lane'),
('Yelsted Road'),
('Yelt Lane'),
('Yelting Geo'),
('Yelvertoft'),
('Yelvertoft Fieldside Covert'),
('Yelvertoft Primary School'),
('Yelvertoft Road'),
('Yelverton'),
('Yelverton Avenue'),
('Yelverton Close'),
('Yelverton Court'),
('Yelverton Crescent'),
('Yelverton Drive'),
('Yelverton Reservoir'),
('Yelverton Road'),
('Yelverton Rural'),
('Yeman Road'),
('Yementry Court'),
('Yemscroft'),
('Yendacott Copse'),
('Yendacott Lane'),
('Yenham Lane'),
('Yennadon Down'),
('Yennadon Plantation'),
('Yennastaba Dale'),
('Yennepark Copse'),
('Yenston'),
('Yenston Close'),
('Yenston Hill'),
('Yenton Close'),
('Yenton Grove'),
('Yenton Primary School'),
('Yenworthy Combe'),
('Yenworthy Common'),
('Yenworthy Wood'),
('Yeo'),
('Yeo Bank Lane'),
('Yeo Brake'),
('Yeo Close'),
('Yeo Coppice'),
('Yeo Copse'),
('Yeo Court'),
('Yeo Drive'),
('Yeo Hill'),
('Yeo Lane'),
('Yeo Mill'),
('Yeo Moor'),
('Yeo Moor Drove'),
('Yeo Moor Primary School'),
('Yeo Park'),
('Yeo Road'),
('Yeo Street'),
('Yeo Vale'),
('Yeo Vale Road'),
('Yeo Valley'),
('Yeo Valley Primary School'),
('Yeo Valley Way'),
('Yeo View'),
('Yeo Way'),
('Yeoford'),
('Yeoford Community Primary School'),
('Yeoford Copse'),
('Yeoford Drive'),
('Yeoford Meadows'),
('Yeoford Way'),
('Yeol Mouth'),
('Yeoland Down'),
('Yeoland Lane'),
('Yeolands Drive'),
('Yeolands Road'),
('Yeolden Copse'),
('Yeolland Lane'),
('Yeolland Park'),
('Yeolmbridge'),
('Yeolmbridge Wood'),
('Yeolmouth Cliff'),
('Yeoman Avenue'),
('Yeoman Bank'),
('Yeoman Close'),
('Yeoman Cottages'),
('Yeoman Court'),
('Yeoman Crescent'),
('Yeoman Drive'),
('Yeoman Fold'),
('Yeoman Gardens'),
('Yeoman Gate'),
('Yeoman Hey Plantation'),
('Yeoman Hey Reservoir'),
('Yeoman Hill'),
('Yeoman Lane'),
('Yeoman Meadow'),
('Yeoman Park'),
('Yeoman Park School'),
('Yeoman Place'),
('Yeoman Road'),
('Yeoman Street'),
('Yeoman Terrace'),
('Yeoman Way'),
('Yeomanry Close'),
('Yeomanry Court'),
('Yeomanry Drive'),
('Yeomanry Place'),
('Yeomanry Road'),
('Yeomanry Walk'),
('Yeomanry Way'),
('Yeomans'),
('Yeomans Acre'),
('Yeomans Avenue'),
('Yeomans Close'),
('Yeomans Close'),
('Yeomans Court'),
('Yeomans Dale'),
('Yeomans Drive'),
('Yeomans Field'),
('Yeomans Gate'),
('Yeomans Lane'),
('Yeomans Lodge'),
('Yeomans Meadows'),
('Yeomans Mount'),
('Yeomans Orchard'),
('Yeomans Place'),
('Yeomans Ride'),
('Yeomans Road'),
('Yeomans Row'),
('Yeomans Square'),
('Yeomans Way'),
('Yeomans Way'),
('Yeomans Yard'),
('Yeomanside Close'),
('Yeomead'),
('Yeomeads'),
('Yeomen Way'),
('Yeorton Brow'),
('Yeory Wood'),
('Yeotown Wood'),
('Yeoveney Close'),
('Yeovil'),
('Yeovil Bus Station'),
('Yeovil Central'),
('Yeovil Chase'),
('Yeovil Close'),
('Yeovil College'),
('Yeovil District Hospital'),
('Yeovil East'),
('Yeovil Junction'),
('Yeovil Marsh'),
('Yeovil Pen Mill'),
('Yeovil Place'),
('Yeovil Primary Campus'),
('Yeovil Road'),
('Yeovil Rock'),
('Yeovil South'),
('Yeovil Street'),
('Yeovil West'),
('Yeovil Westland Airfield'),
('Yeovil Without'),
('Yeovilton'),
('Yeovilton Close'),
('Yeovilton Place'),
('Yeovilton Royal Naval Air Station'),
('Yeoward Road'),
('Yeowood Solar Farm'),
('Yerbeston'),
('Yerburgh Avenue'),
('Yerburgh Road'),
('Yerburgh Street'),
('Yerbury Grove'),
('Yerbury Primary School'),
('Yerbury Road'),
('Yerbury Street'),
('Yerdley Coppice'),
('Yerley Hill'),
('Yerris Road'),
('Yerton Brae'),
('Yerville Gardens'),
('Yes Tor'),
('Yeshivah Ohr Torah School'),
('Yesmere'),
('Yesnaby'),
('Yesnaby Road'),
('Yesodey Hatorah Grammar School'),
('Yesodey Hatorah Senior Girls School'),
('Yesoiday Hatorah School'),
('Yessell Lane'),
('Yessness'),
('Yester'),
('Yester Drive'),
('Yester Park'),
('Yester Place'),
('Yester Primary School'),
('Yester Road'),
('Yet Mead Lane'),
('Yetchleys Coppice'),
('Yetholm'),
('Yetholm Avenue'),
('Yetholm Gardens'),
('Yetholm Law'),
('Yetholm Loch'),
('Yetholm Park'),
('Yetholm Place'),
('Yetholm Primary School'),
('Yetholm Road'),
('Yetholm Street'),
('Yetholm Terrace'),
('Yetholm Way'),
('Yethouse Hill'),
('Yetlands'),
('Yetlington'),
('Yetlington Drive'),
('Yetmans Copse'),
('Yetminster'),
('Yetminster & Cam Vale'),
('Yetminster Road'),
('Yett Hill'),
('Yett Road'),
('Yettan Terrace'),
('Yettington'),
('Yettington Road'),
('Yettna Geo'),
('Yetts Avenue'),
('Yetts Crescent'),
('Yetts Hole Road'),
('Yetts o Muckhart'),
('Yevele Close'),
('Yevele Way'),
('Yew Avenue'),
('Yew Band'),
('Yew Bank'),
('Yew Bank Road'),
('Yew Barrow'),
('Yew Barrow Breast'),
('Yew Barrow Close'),
('Yew Barrow Wood'),
('Yew Cleugh'),
('Yew Cliff Coppice'),
('Yew Close'),
('Yew Clump'),
('Yew Corner'),
('Yew Court'),
('Yew Covert'),
('Yew Crescent'),
('Yew Croft Avenue'),
('Yew Dale Gardens'),
('Yew Down'),
('Yew Down Plantation'),
('Yew Drive'),
('Yew Gardens'),
('Yew Gate'),
('Yew Greave Crescent'),
('Yew Green'),
('Yew Green Avenue'),
('Yew Green Road'),
('Yew Grove'),
('Yew Hill'),
('Yew Lane'),
('Yew Oval'),
('Yew Pike Moss'),
('Yew Place'),
('Yew Plantation'),
('Yew Redding'),
('Yew Ring'),
('Yew Road'),
('Yew Scar Force'),
('Yew Street'),
('Yew Terrace'),
('Yew Tree'),
('Yew Tree Avenue'),
('Yew Tree Bank'),
('Yew Tree Bottom Road'),
('Yew Tree Close'),
('Yew Tree Close Covert'),
('Yew Tree Community Primary School'),
('Yew Tree Community Primary School And Acorn Nurser'),
('Yew Tree Community Primary School And Acorn Nursery'),
('Yew Tree Community School'),
('Yew Tree Copse'),
('Yew Tree Corner'),
('Yew Tree Court'),
('Yew Tree Courtyard'),
('Yew Tree Covert'),
('Yew Tree Crescent'),
('Yew Tree Dingle'),
('Yew Tree Drive'),
('Yew Tree Farm'),
('Yew Tree Gardens'),
('Yew Tree Gorge'),
('Yew Tree Green'),
('Yew Tree Green Road'),
('Yew Tree Grounds'),
('Yew Tree Grove'),
('Yew Tree Hangings'),
('Yew Tree Heath'),
('Yew Tree Hill'),
('Yew Tree Hills'),
('Yew Tree Hollow'),
('Yew Tree Lane'),
('Yew Tree Meadow'),
('Yew Tree Mews'),
('Yew Tree Moor'),
('Yew Tree Nursing Home'),
('Yew Tree Park'),
('Yew Tree Park Road'),
('Yew Tree Place'),
('Yew Tree Plantation'),
('Yew Tree Primary School'),
('Yew Tree Rein'),
('Yew Tree Rise'),
('Yew Tree Road'),
('Yew Tree Shaw'),
('Yew Tree Spinney'),
('Yew Tree Square'),
('Yew Tree Stables'),
('Yew Tree Street'),
('Yew Tree Tarn'),
('Yew Tree Terrace'),
('Yew Tree Walk'),
('Yew Tree Way'),
('Yew Tree Wood'),
('Yew Trees'),
('Yew Trees Avenue'),
('Yew Trees Croft'),
('Yew Trees Wood'),
('Yew Walk'),
('Yew Way'),
('Yew Wood'),
('Yewbank Avenue'),
('Yewbank Close'),
('Yewbank Lane'),
('Yewbank Terrace'),
('Yewbarrow'),
('Yewbarrow Close'),
('Yewbarrow Road'),
('Yewbarrow Wood'),
('Yewberry Close'),
('Yewberry Coppice'),
('Yewberry Lane'),
('Yewberry Way'),
('Yewburn Way'),
('Yewcrag Plantation'),
('Yewcroft'),
('Yewcroft Avenue'),
('Yewcroft Close'),
('Yewdale'),
('Yewdale Avenue'),
('Yewdale Close'),
('Yewdale Crag Moss'),
('Yewdale Crescent'),
('Yewdale Drive'),
('Yewdale Fell Side'),
('Yewdale Fells'),
('Yewdale Gardens'),
('Yewdale Grove'),
('Yewdale Moss'),
('Yewdale Park'),
('Yewdale Primary School'),
('Yewdale Road'),
('Yewdale School'),
('Yewdall Road'),
('Yewdall Way'),
('Yewens'),
('Yewens Hanger'),
('Yewfield Road'),
('Yewhedges'),
('Yewhow Wood'),
('Yewhurst Close'),
('Yewhurst Road'),
('Yewlands'),
('Yewlands Academy'),
('Yewlands Avenue'),
('Yewlands Close'),
('Yewlands Crescent'),
('Yewlands Drive'),
('Yewlands Gardens'),
('Yewleigh Lane'),
('Yews Avenue'),
('Yews Close'),
('Yews Crescent'),
('Yews Drive'),
('Yews Green'),
('Yews Hill'),
('Yews Hill Road'),
('Yews Lane'),
('Yews Mount'),
('Yews Place'),
('Yews Plantation'),
('Yewside'),
('Yewstock'),
('Yewstock College'),
('Yewstock Crescent West'),
('Yewstock Plantation'),
('Yewstock School'),
('Yewthwaite Comb'),
('Yewtree Avenue'),
('Yewtree Bank'),
('Yewtree Batch'),
('Yewtree Bottom'),
('Yewtree Close'),
('Yewtree Coppice'),
('Yewtree Copse'),
('Yewtree Court'),
('Yewtree Crescent'),
('Yewtree Dingle'),
('Yewtree Drive'),
('Yewtree End'),
('Yewtree Gardens'),
('Yewtree Gate'),
('Yewtree Green'),
('Yewtree Grove'),
('Yewtree Hanger'),
('Yewtree Hassock'),
('Yewtree Hill'),
('Yewtree Hill Brake'),
('Yewtree Hill Plantation'),
('Yewtree Holms'),
('Yewtree Lane'),
('Yewtree Mews'),
('Yewtree Nob'),
('Yewtree Pit Covert'),
('Yewtree Plantation'),
('Yewtree Primary School'),
('Yewtree Rise'),
('Yewtree Road'),
('Yewtree Row'),
('Yewtree Shaw'),
('Yewtree Spinney'),
('Yewtree Spring'),
('Yewtree Toll'),
('Yewtree Wood'),
('Yewtreebrake Inclosure'),
('Yewtrees'),
('Yewtrees Lane'),
('Yewvale Road'),
('Y-Fron'),
('Y-Gaer'),
('Ygerddi'),
('Y-Gesail'),
('Y-Glyn'),
('Yield Brae'),
('Yield Hall Lane'),
('Yield Hall Place'),
('Yielding Copse'),
('Yielding Tree'),
('Yieldings Close'),
('Yieldingtree'),
('Yieldshields'),
('Yieldshields Road'),
('Yiewsley'),
('Yiewsley Close'),
('Yiewsley Crescent'),
('Yiewsley Drive'),
('Yinstay'),
('Yinstay Head'),
('Yinstay Road'),
('Yllaethdy'),
('YMCA George Williams College'),
('Ymyl yr Afon'),
('Ymyl-Yr-Afon'),
('Yniscedwyn Road'),
('Ynisderw Road'),
('Ynisydarren Road'),
('Ynys'),
('Ynys Amlwch'),
('Ynys Arw'),
('Ynys Bach'),
('Ynys Bâch'),
('Ynys Badrig'),
('Ynys Benlas'),
('Ynys Berchen'),
('Ynys Bery'),
('Ynys Bery Close'),
('Ynys Byr'),
('Ynys Cadwyn'),
('Ynys Cantwr'),
('Ynys Castell'),
('Ynys Close'),
('Ynys Creua'),
('Ynys Cyngar'),
('Ynys Dawel'),
('Ynys Ddu'),
('Ynys Defaid'),
('Ynys Deullyn'),
('Ynys Dinas'),
('Ynys Dol-lleian'),
('Ynys Dol-rhedyn'),
('Ynys Drai'),
('Ynys Dulas'),
('Ynys Eilun'),
('Ynys Enlli'),
('Ynys Fach'),
('Ynys Fâch'),
('Ynys Fach Avenue'),
('Ynys Faelog'),
('Ynys Fawr'),
('Ynys Fawr Avenue'),
('Ynys Feirig'),
('Ynys Fer-Lâs'),
('Ynys Feurig'),
('Ynys Gaint'),
('Ynys Galch'),
('Ynys Gifftan'),
('Ynys Glyd Street'),
('Ynys Goediog'),
('Ynys Gored Goch'),
('Ynys Groes'),
('Ynys Gron'),
('Ynys Gwair'),
('Ynys Gwelltog'),
('Ynys Gwylan-bâch'),
('Ynys Gwylan-fawr'),
('Ynys Gwyndwn-mawr'),
('Ynys Gybi'),
('Ynys Halen'),
('Ynys Hir'),
('Ynys Hwrddod'),
('Ynys Isaf'),
('Ynys Lane'),
('Ynys Las'),
('Ynys Lawd'),
('Ynys Leurad'),
('Ynys Llanddwyn'),
('Ynys Llanfihangel-y-traethau'),
('Ynys Lochtyn'),
('Ynys Lom'),
('Ynys Meibion'),
('Ynys Meicel'),
('Ynys Melyn'),
('Ynys Moelfre'),
('Ynys Mon'),
('Ynys Môn'),
('Ynys Nedd'),
('Ynys Newydd Road'),
('Ynys Onnen'),
('Ynys Peibio'),
('Ynys Piod'),
('Ynys Seiriol'),
('Ynys Sili'),
('Ynys Street'),
('Ynys Sych'),
('Ynys Terrace'),
('Ynys Thomas-Howel'),
('Ynys Tobig'),
('Ynys Traws'),
('Ynys Tysilio'),
('Ynys Tywyn'),
('Ynys Wall'),
('Ynys Wellt'),
('Ynys Welltog'),
('Ynys y Big'),
('Ynys y Brawd'),
('Ynys y Carcharorion'),
('Ynys y Castell'),
('Ynys y Clochydd'),
('Ynys Y Coed'),
('Ynys Y Cwm Road'),
('Ynys y Ddinas'),
('Ynys y Fydlyn'),
('Ynys Y Gored'),
('Ynys y Mochyn'),
('Ynys Y Nos'),
('Ynys Y Wern'),
('Ynys yr Adar'),
('Ynys yr Wyn'),
('Ynysallan Road'),
('Ynysangharad'),
('Ynysangharad Road'),
('Ynysarwed'),
('Ynysawdre'),
('Ynysboeth'),
('Ynysboeth Community Primary School'),
('Ynysbryn Close'),
('Ynyscedwyn'),
('Ynyscorrwg Road'),
('Ynyscynon Road'),
('Ynyscynon Street'),
('Ynysddu'),
('Ynys-ddu'),
('Ynysddu Hotel Approach'),
('Ynysddu Primary School'),
('Ynysderw Park Road'),
('Ynysfach'),
('Ynys-fach'),
('Ynysfeio Avenue'),
('Ynysforgan'),
('Ynys-Forgan'),
('Ynysfro Reservoirs'),
('Ynysgau Street'),
('Ynysgedwyn'),
('Ynys-Gyfeillon Road'),
('Ynys-hafren'),
('Ynyshir'),
('Ynys-hir'),
('Ynyshir Community Primary School'),
('Ynyshir Road'),
('Ynys-Isaf'),
('Ynyslas'),
('Ynys-las'),
('Ynyslas Crescent'),
('Ynys-Lee'),
('Ynys-Lwyd Road'),
('Ynys-Lwyd Street'),
('Ynyslyn Road'),
('Ynysmaerdy'),
('Ynysmaerdy Primary School'),
('Ynysmaerdy Terrace'),
('Ynysmeudwy'),
('Ynys-Meudwy Road'),
('Ynysmeurig Road'),
('Ynys-Mòn'),
('Ynysoedd Duon'),
('Ynysoedd Gwylanod'),
('Ynysoedd y Ffrydiau'),
('Ynysoedd y Moelrhoniaid'),
('Ynysowen'),
('Ynysowen Community Primary School'),
('Ynysowen Fach'),
('Ynysowen School'),
('Ynyspenllwch'),
('Ynys-Penllwch Road'),
('Ynystawe'),
('Ynys-Tawe'),
('Ynysteg'),
('Ynys-uchaf'),
('Ynyswen'),
('Ynys-wen'),
('Ynyswen Infants School'),
('Ynyswen Road'),
('Ynyswerdd'),
('Ynys-Wil-hernyn Wood'),
('Ynysybwl'),
('Ynys-y-bwl'),
('Ynys-y-bwl a Choed-y-cwm'),
('Ynysybwl and Coed-y-Cwm'),
('Ynysybwl Road'),
('Ynys-Y-Coed'),
('Ynys-y-cranc'),
('Ynysydarren'),
('Ynysygerwn Avenue'),
('Ynysygerwn Crescent'),
('Ynysygored Road'),
('Ynysygwas'),
('Ynysygwas Hill'),
('Ynysymaerdy'),
('Ynysymaerdy Road'),
('Ynys-Y-Mond Road'),
('Ynys-y-mond Uchaf'),
('Ynys-y-pica Wood'),
('Ynys-Yr-Afon'),
('Yoadcastle'),
('Yoadcomb Hill'),
('Yoadwath Bank'),
('Yoags Haven'),
('Yoakes Lane'),
('Yoakley Road'),
('Yoakley Square'),
('Yock Lane'),
('Yockenthwaite'),
('Yockenthwaite Moor'),
('Yockleton'),
('Yockleton Road'),
('Yockletts Banks'),
('Yockley Close'),
('Yockley Wood'),
('Yockney Close'),
('Yoden Court'),
('Yoden Road'),
('Yoden Way'),
('Yoells Copse'),
('Yoells Crescent'),
('Yoells Lane'),
('Yoesden Wood'),
('Yoga Way'),
('Yogli Geo'),
('Yohden Hall Nursing Home'),
('Yohden Primary School'),
('Yoke'),
('Yoke Close'),
('Yoke Hill'),
('Yoke Knowes'),
('Yoke Wood'),
('Yokecliffe Avenue'),
('Yokecliffe Crescent'),
('Yokecliffe Drive'),
('Yokecliffe Hill'),
('Yokecliffe Lane'),
('Yokecliffe Wood'),
('Yokefleet'),
('Yokefleet Clough'),
('Yokehouse Lane'),
('Yokeing Close Wood'),
('Yoker'),
('Yoker Ferry Road'),
('Yoker Mill Gardens'),
('Yoker Mill Road'),
('Yoker Primary School'),
('Yokerburn Place'),
('Yokerburn Terrace'),
('Yokesford Hill'),
('Yokine Gardens'),
('Yokosuka Way'),
('Yolande Gardens'),
('Yolhey Lane'),
('Yolk Meadow'),
('Yollacombe Plantations'),
('Yolland Close'),
('Yolland Hill'),
('Yolland Plantation'),
('Yolsham Green'),
('Yolsham Hill'),
('Yolsum Close'),
('Yolsum Plantation'),
('Yomede Park'),
('Yon Street'),
('Yonder'),
('Yonder Acre Way'),
('Yonder Brake'),
('Yonder Close'),
('Yonder Coppice'),
('Yonder Cross Close Copse'),
('Yonder Drove'),
('Yonder Hare Down'),
('Yonder Horse Park Copse'),
('Yonder Mead'),
('Yonder Meadow'),
('Yonder Moor'),
('Yonder Mount'),
('Yonder Plantation'),
('Yonder Slade'),
('Yonder Street'),
('Yonder Way'),
('Yonder Wyke Moor Copse'),
('Yonderberry Point'),
('Yondercott'),
('Yonderdown Wood'),
('Yonderton Place'),
('Yondertown'),
('Yondover'),
('Yondover Mill'),
('Yonge Close'),
('Yonge Park'),
('Yons Hill'),
('Yons Nab'),
('Yont the Cleugh'),
('Yopps Green'),
('Yorath Road'),
('Yorburgh'),
('Yordas Court'),
('Yordas Wood'),
('Yore Mill'),
('Yoredale Avenue'),
('Yoredale Close'),
('Yoredale Drive'),
('Yoreham Close'),
('Yorfalls Wood'),
('Yorick Avenue'),
('Yorick Road'),
('York'),
('York Alley'),
('York And Albany Close'),
('York Avenue'),
('York Bridge'),
('York Bridge Road'),
('York Buildings'),
('York Central'),
('York Chase'),
('York Close'),
('York College'),
('York College Construction Centre'),
('York Cottages'),
('York Court'),
('York Crescent'),
('York Dale'),
('York Day Hospital'),
('York Drive'),
('York Drove'),
('York Fields'),
('York Gardens'),
('York Garth'),
('York Gate'),
('York Gate Lane'),
('York Gate Plantation'),
('York Grove'),
('York High School'),
('York Hill'),
('York Hill Crescent'),
('York Hill Plantation'),
('York Hill Road'),
('York Hospital Nuffield Health'),
('York House Place'),
('York House Road'),
('York House School'),
('York Lane'),
('York Mead Primary School'),
('York Mews'),
('York Outer'),
('York Paddock'),
('York Parade'),
('York Place'),
('York Place Lane'),
('York Plantation'),
('York Ride'),
('York Rise'),
('York Road'),
('York Road East'),
('York Road Junior Academy and Language Unit'),
('York Road South'),
('York Road West'),
('York Row'),
('York Square'),
('York St John University'),
('York Steiner School'),
('York Street'),
('York Street Building'),
('York Street Campus'),
('York Street Lane'),
('York Teaching Hospital'),
('York Terrace'),
('York Terrace East'),
('York Terrace Lane'),
('York Terrace West'),
('York Town'),
('York View'),
('York Villa Close'),
('York Villas'),
('York Walk'),
('York Way'),
('York Way Court'),
('York Way Field'),
('York Wood'),
('Yorkaster Road'),
('Yorkbrooke Drive'),
('Yorkdale'),
('Yorkdale Close'),
('Yorkdale Court'),
('Yorkdale Drive'),
('Yorkdale Place'),
('Yorkdale Road'),
('Yorke Avenue'),
('Yorke Close'),
('Yorke Drive'),
('Yorke Gardens'),
('Yorke Gate'),
('Yorke Place'),
('Yorke Rise'),
('Yorke Road'),
('Yorke Rock'),
('Yorke Street'),
('Yorke Way'),
('Yorkersgate'),
('Yorkes Dingles'),
('Yorkfield Lane'),
('Yorkhill'),
('Yorkhill Parade'),
('Yorkhill Street'),
('Yorkhurst Hill'),
('Yorkland Avenue'),
('Yorklands'),
('Yorklea Croft'),
('Yorklets'),
('Yorkletts'),
('Yorkley'),
('Yorkley Lane'),
('Yorkley Primary School'),
('Yorkley Road'),
('Yorkley Slade'),
('Yorkley Wood'),
('Yorkley Wood Road'),
('Yorkmead Junior And Infant School'),
('Yorkminster Drive'),
('Yorks Hill'),
('Yorks Lane'),
('Yorks Wood'),
('Yorks Wood Drive'),
('Yorksand Road'),
('Yorksfield Plantation'),
('Yorkshire'),
('Yorkshire and The Humber'),
('Yorkshire Close'),
('Yorkshire Coast College'),
('Yorkshire Coast College Westwood Campus'),
('Yorkshire Dales National Park'),
('Yorkshire Drive'),
('Yorkshire Gardens'),
('Yorkshire Grove'),
('Yorkshire Place'),
('Yorkshire Road'),
('Yorkshire Shaw'),
('Yorkshire Street'),
('Yorkshire Street East'),
('Yorkshire Street West'),
('Yorkshire Way'),
('Yorkshire Wolds'),
('Yorkshireside'),
('Yorkston Moss'),
('Yorkstone'),
('Yorkstone Close'),
('Yorkswood Primary School'),
('Yorkswood Road'),
('Yorkton Street'),
('Yorktown Close'),
('Yorktown Road'),
('Yorkway'),
('Yorkwood'),
('Yorney Wood'),
('Yorstans Geo'),
('Yorston Lodge School'),
('Yorton'),
('Yorton Heath'),
('Yosemite Park'),
('Yosgill Wood'),
('Yottenfews'),
('Youatt Avenue'),
('Youchtrie Heugh'),
('Youd Street'),
('Youell Avenue'),
('Youens Crescent'),
('Youens Drive'),
('Youens Road'),
('Youens Way'),
('Youghal Close'),
('Youings Drive'),
('Youlbury Pool'),
('Youlbury Wood'),
('Youlden Close'),
('Youlden Drive'),
('Youlden Lane'),
('Youlden Plantation'),
('Youlden Plantations'),
('Youlden Wood'),
('Youldholes Lane'),
('Youldon Way'),
('Youldon Wood'),
('Youldons Close'),
('Youlgrave'),
('Youlgrave Avenue'),
('Youlgreave'),
('Youlgreave Avenue'),
('Youlgreave Close'),
('Youlgreave Crescent'),
('Youlgreave Drive'),
('Youlieburn'),
('Youll Close'),
('Youlston Close'),
('Youlston Park'),
('Youlston Wood'),
('Youlstone'),
('Youlthorpe'),
('Youlthorpe Pasture Hill'),
('Youlton'),
('Youlton Moor'),
('Youlton Moor Plantation'),
('Young A Plantation'),
('Young Albemarle Plantation'),
('Young Avenue'),
('Young Bank Lane'),
('Young Beech Plantation'),
('Young Bog Wood'),
('Young Bush Wood'),
('Young Close'),
('Young Contract Wood'),
('Young Coombe'),
('Young Coppice'),
('Young Copse'),
('Young Court'),
('Young Covert'),
('Young Crescent'),
('Young Croft Brake'),
('Young Drive'),
('Young Eaa Plantation'),
('Young Heater Plantation'),
('Young Hill'),
('Young Jeanies Wood'),
('Young Kings Wood'),
('Young Ladys Wood'),
('Young Lane'),
('Young Marys Grove'),
('Young Oaks'),
('Young Oaks Wood'),
('Young Options College'),
('Young Peoples Academy'),
('Young Place'),
('Young Plantation'),
('Young Road'),
('Young Row Plantation'),
('Young Salamanca Covert'),
('Young Spinney'),
('Young Spring Wood'),
('Young Square'),
('Young Street'),
('Young Street North Lane'),
('Young Street South Lane'),
('Young Terrace'),
('Young Trees'),
('Young Wood'),
('Young Wynd'),
('Youngaton Road'),
('Youngcross Grounds'),
('Younger Drive'),
('Younger Gardens'),
('Younger Place'),
('Younger Quadrant'),
('Younger Street'),
('Youngers Lane'),
('Youngers Terrace'),
('Youngfield Road'),
('Younghall Close'),
('Younghayes Road'),
('Younghurst Wood'),
('Younghusband Wood'),
('Youngman Avenue'),
('Youngman Close'),
('Youngman Place'),
('Youngmans Close'),
('Youngmans Lane'),
('Youngmans Lane'),
('Youngmans Road'),
('Youngoak Covert'),
('Youngs Avenue'),
('Youngs Close'),
('Youngs Copse'),
('Youngs Court'),
('Youngs Court'),
('Youngs Crescent'),
('Youngs Drive'),
('Youngs Drive'),
('Youngs End'),
('Youngs Grove'),
('Youngs Hill'),
('Youngs Knowe'),
('Youngs Lane'),
('Youngs Mews'),
('Youngs Orchard'),
('Youngs Paddock'),
('Youngs Park Lane'),
('Youngs Park Road'),
('Youngs Place'),
('Youngs Plantation'),
('Youngs Rise'),
('Youngs Road'),
('Youngs Row'),
('Youngs Way'),
('Youngs Wood'),
('Youngs Yard'),
('Youngsbury'),
('Youngsbury Lane'),
('Youngsclose Plantation'),
('Youngsdale Place'),
('Youngsmere Close'),
('Youngsons Lane'),
('Youngstroat Lane'),
('Youngwood Lane'),
('Youngwoods Copse'),
('Youngwoods Plantation'),
('Youngwoods Way'),
('Youth Close'),
('Youth Wood'),
('Yowlass Wood'),
('Yowley Road'),
('Yoxall'),
('Yoxall Avenue'),
('Yoxall Drive'),
('Yoxall Grove'),
('Yoxall Park'),
('Yoxall Road'),
('Yoxall Way'),
('Yoxford'),
('Yoxford & Peasenhall Primary School'),
('Yoxford County Primary School'),
('Yoxford Little Street'),
('Yoxford Mews'),
('Yoxford Road'),
('Yoxford Wood'),
('Yoxhall Drive'),
('Yoxhall Meadow Woods'),
('Yoxie Geo'),
('Yoxley Approach'),
('Yoxley Drive'),
('Yoxley Plantation'),
('Yoxwood View'),
('Ypres Close'),
('Ypres Court'),
('Ypres Drive'),
('Ypres Place'),
('Ypres Road'),
('Ypres Way'),
('Yr Aber'),
('Yr Aes'),
('Yr Ala'),
('Yr Allt'),
('Yr Allt Boeth'),
('Yr Allt Gethin'),
('Yr Angorfa'),
('Yr Aran'),
('Yr Ardd Fawr'),
('Yr Arddu'),
('Yr Arwydd'),
('Yr As Fach'),
('Yr As Fawr'),
('Yr Ebolion'),
('Yr Efail'),
('Yr Eglwys Newydd'),
('Yr Eglwys Newydd a Thongwynlais'),
('Yr Eifl'),
('Yr Elain'),
('Yr Elen'),
('Yr Encil'),
('Yr Encilfa'),
('Yr Erw'),
('Yr Esgair'),
('Yr Hafan'),
('Yr Hafanau'),
('Yr Hafn'),
('Yr Hafod'),
('Yr Harbwr'),
('Yr Havens'),
('Yr Helfa'),
('Yr Helyg'),
('Yr Hen Berlan'),
('Yr Hen Berllan'),
('Yr Hen Draeth Ymdrochi'),
('Yr Hen Erddi'),
('Yr Hen Erddi (The Old Allotments)'),
('Yr Hen Gorlan'),
('Yr Hen Heol'),
('Yr Hen Laethdy'),
('Yr Hen Ysgol'),
('Yr Hendre'),
('Yr Hendy'),
('Yr Hen-ffordd'),
('Yr Hirgylch'),
('Yr Hob'),
('Yr Hòb'),
('Yr Hôb'),
('Yr Hobin Cast'),
('Yr Hwylfa'),
('Yr Ochr'),
('Yr Oerfa'),
('Yr Ogof'),
('Yr Orsedd'),
('Yr Rhos'),
('Yr Wyddfa'),
('Yr Wyddgrug'),
('Yr Wyddgrug - Broncoed'),
('Yr Wyddgrug - De'),
('Yr Wyddgrug - Dwyrain'),
('Yr Wyddgrug - Gorllewin'),
('Yr Wylorn'),
('Yr Ydlan'),
('Yr Ynys'),
('Yr Ysfa'),
('Yr Ysgol John Frost'),
('Yr Ystog'),
('Yr Ystrad'),
('Yr-allt Wood'),
('Yr-efail Covert'),
('Yr-Hen-Lawnt'),
('Y-Rhos'),
('Ysbryd-Y-Coed'),
('Ysbty Aneurin Bevan'),
('Ysbutyr Santes Tudful'),
('Ysbytr tri Chwm Hospital'),
('Ysbytty Reservoir'),
('Ysbyty Alltwen'),
('Ysbyty Athrofaol Cymru'),
('Ysbyty Athrofaol Llandochau'),
('Ysbyty Brenhinol Gwent'),
('Ysbyty Bryn Beryl'),
('Ysbyty Castell Nedd Port Talbot'),
('Ysbyty Coffa Sir Frycheiniog'),
('Ysbyty Coffa Victoria Y Trallwng'),
('Ysbyty Cwm Cynon'),
('Ysbyty Cyffredinol Llwynhelyg'),
('Ysbyty Cymuned Glannau Dyfrdwy'),
('Ysbyty Cymunedol Y Waun'),
('Ysbyty Cymunedol Yr Wyddgrug'),
('Ysbyty Cynfyn'),
('Ysbyty Dewi Sant'),
('Ysbyty Dolgellau Y Bermo Ar Cylch'),
('Ysbyty Eglwys Newydd'),
('Ysbyty Eryri'),
('Ysbyty Frenhinol Morgannwg'),
('Ysbyty Garngoch'),
('Ysbyty Glan Clwyd'),
('Ysbyty Gwynedd Gwynedd Hospital'),
('Ysbyty Gymuned Bro Ddyfi'),
('Ysbyty Ifan'),
('Ysbyty Llandudno'),
('Ysbyty Llanymddfri'),
('Ysbyty Maelor Wrecsam'),
('Ysbyty Neuadd Nevill'),
('Ysbyty Penrhos Stanley'),
('Ysbyty Sir Drefaldwyn'),
('Ysbyty Treforys'),
('Ysbyty Twysog Siarl'),
('Ysbyty Tywysoges Cymru'),
('Ysbyty Ystrad Fawr'),
('Ysbyty Ystwyth'),
('Ysbyty Ystwyth County Primary School'),
('Ysceifiog'),
('Ysceifiog Lake'),
('Yscir'),
('YsgÃ¯og Wood'),
('Ysgafell Wen'),
('Ysgeifiog'),
('Ysgeifiog Moor'),
('Ysgir'),
('Ysgol'),
('Ysgol a Chanolfan Adnoddau Caeaur Drindod'),
('Ysgol Aberconwy'),
('Ysgol Abererch'),
('Ysgol Abersychan'),
('Ysgol Annibynnol Bangor'),
('Ysgol Arbennig Pen Y Cwm'),
('Ysgol Ardudwy'),
('Ysgol Awel Y Mynydd'),
('Ysgol Babanod A Meithrin New Inn'),
('Ysgol Babanod Cefn Glas'),
('Ysgol Babanod Coed Mawr'),
('Ysgol Babanod Dolgellau'),
('Ysgol Babanod Hendre'),
('Ysgol Babanod Ladywell Green'),
('Ysgol Babanod Llwyncelyn'),
('Ysgol Babanod PenmaenrhÃ´s'),
('Ysgol Babanod Penmaenrhòs'),
('Ysgol Babanod Y Melin'),
('Ysgol Bae Baglan'),
('Ysgol Baladeulyn'),
('Ysgol Baratoadol Gollop'),
('Ysgol Beca'),
('Ysgol Bendigaid William Davies'),
('Ysgol Betws Yn Rhos'),
('Ysgol Bod Alaw'),
('Ysgol Bodafon'),
('Ysgol Bodfari'),
('Ysgol Bodfeurig'),
('Ysgol Bodhyfryd'),
('Ysgol Botwnnog'),
('Ysgol Bro Aled'),
('Ysgol Bro Alun'),
('Ysgol Bro Brynach'),
('Ysgol Bro Carmel'),
('Ysgol Bro Cleddau'),
('Ysgol Bro Cynllaith'),
('Ysgol Bro Ddyfi'),
('Ysgol Bro Dewi Primary School'),
('Ysgol Bro Dinefwr'),
('Ysgol Bro Dyfrdwy'),
('Ysgol Bro Elwern Gwyddelwern County Primary School'),
('Ysgol Bro Famau Llanarmon-Yn-Lal'),
('Ysgol Bro Famau Llanferres'),
('Ysgol Bro Gwaun'),
('Ysgol Bro Gwydir'),
('Ysgol Bro Hedd Wyn'),
('Ysgol Bro Idris'),
('Ysgol Bro Ingli'),
('Ysgol Bro Lleu'),
('Ysgol Bro Llifon'),
('Ysgol Bro Myrddin'),
('Ysgol Bro Pedr'),
('Ysgol Bro Sannan'),
('Ysgol Bro Siòn Cwilt'),
('Ysgol Bro Tawe'),
('Ysgol Bro Tegid'),
('Ysgol Bro Teifi'),
('Ysgol Bro Tryweryn'),
('Ysgol Bryn Alyn High School'),
('Ysgol Bryn Castell'),
('Ysgol Bryn Clwyd'),
('Ysgol Bryn Coch County Primary School'),
('Ysgol Bryn Collen Llangollen'),
('Ysgol Bryn Derw'),
('Ysgol Bryn Deva Community Primary School'),
('Ysgol Bryn Elian'),
('Ysgol Bryn Gwalia Primary School'),
('Ysgol Bryn Hedydd'),
('Ysgol Bryn Hyfryd'),
('Ysgol Bryn Onnen'),
('Ysgol Bryn Tabor'),
('Ysgol Brynaerau'),
('Ysgol Bryngwyn School'),
('Ysgol Brynhyfryd'),
('Ysgol Brynrefail'),
('Ysgol Brynteg County Primary School'),
('Ysgol Bueno Sant'),
('Ysgol Cae Top'),
('Ysgol Caer Drewyn'),
('Ysgol Caer Elen'),
('Ysgol Caer Felin'),
('Ysgol Capelulo'),
('Ysgol Carreg Emlyn'),
('Ysgol Carreg Hir'),
('Ysgol Carreg Hirfaen'),
('Ysgol Carrog School'),
('Ysgol Casmael'),
('Ysgol Cedewain'),
('Ysgol Cefn Coch'),
('Ysgol Cefn Meiriadog'),
('Ysgol Ceiriog School'),
('Ysgol Cil-y-Coed'),
('Ysgol Clawdd Offa'),
('Ysgol Clywedog'),
('Ysgol Coedcae'),
('Ysgol Cradoc CP School'),
('Ysgol Craig Y Deryn'),
('Ysgol Craig Y Don'),
('Ysgol Crownbridge'),
('Ysgol Crud Y Werin'),
('Ysgol Crug Glas'),
('Ysgol Cwmllynfell'),
('Ysgol Cybi'),
('Ysgol Cymerau'),
('Ysgol Cymuned Lon Barcas'),
('Ysgol Cynddelw'),
('Ysgol Cynfran Llysfaen'),
('Ysgol Cynhaliaeth Trwy Grant Caergeliog'),
('Ysgol Cynwyd Sant'),
('Ysgol Cynwyl Elfed'),
('Ysgol Cystennin'),
('Ysgol Dafydd Llwyd'),
('Ysgol Deganwy'),
('Ysgol Derwen School'),
('Ysgol Derwenfa'),
('Ysgol Dewi Sant'),
('Ysgol Dinas Bran'),
('Ysgol Dinmael'),
('Ysgol Dolafon'),
('Ysgol Dolwyddelan'),
('Ysgol Dyffryn Cledlyn'),
('Ysgol Dyffryn Conwy'),
('Ysgol Dyffryn Dulas Corris'),
('Ysgol Dyffryn Ial'),
('Ysgol Dyffryn Iâl'),
('Ysgol Dyffryn Nantlle'),
('Ysgol Dyffryn Taf'),
('Ysgol Dyffryn Teifi'),
('Ysgol Dyffryn Trannon'),
('Ysgol Dyffryn Yr Enfys'),
('Ysgol Edmwnd Prys'),
('Ysgol Eglwsig Llanwenog (Voluntary Aided) School'),
('Ysgol Eglwys Llanllwni'),
('Ysgol Eifion Wyn'),
('Ysgol Eifionydd'),
('Ysgol Ein Harglwyddes'),
('Ysgol Emmanuel'),
('Ysgol Emrys Ap Iwan'),
('Ysgol Esceifiog Gaerwen'),
('Ysgol Esgob Morgan'),
('Ysgol Estyn Community School'),
('Ysgol Ewloe Green County Primary School'),
('Ysgol Eyton'),
('Ysgol Ffordd Dyffryn'),
('Ysgol Ffridd Y Llyn'),
('Ysgol Foel Gron'),
('Ysgol Friars'),
('Ysgol Frongoch'),
('Ysgol G G Nantmel Nantmel Church In Wales School'),
('Ysgol Gatholig Saint Ffrancis'),
('Ysgol Ger Y Llan'),
('Ysgol Glan Aber'),
('Ysgol Glan Cleddau'),
('Ysgol Glan Clwyd'),
('Ysgol Glan Gele Infants School'),
('Ysgol Glan Morfa'),
('Ysgol Glan Y Mòr School'),
('Ysgol Glanadda'),
('Ysgol Glancegin'),
('Ysgol Glannau Gwaun'),
('Ysgol Glanrafon'),
('Ysgol Glantwymyn'),
('Ysgol Glanwydden'),
('Ysgol Glan-Y-Mòr'),
('Ysgol Glyndyfrdwy'),
('Ysgol Gogarth'),
('Ysgol Golftyn Community Primary School'),
('Ysgol Golwg y Cwm'),
('Ysgol Golwg-Y-Mor'),
('Ysgol Goronwy Owen'),
('Ysgol Grynradd Maes-Y-Coed County Primary School'),
('Ysgol Gwaelod-Y-Garth School'),
('Ysgol Gwaun Gynfi'),
('Ysgol Gwynedd Primary School'),
('Ysgol Gyfen Gymraeg Bryn Tawe'),
('Ysgol Gyfun Aberaeron'),
('Ysgol Gyfun Aberpennar'),
('Ysgol Gyfun Blaen-Gwawr'),
('Ysgol Gyfun Bryn Celynnog'),
('Ysgol Gyfun Bryntirion'),
('Ysgol Gyfun Caerllion'),
('Ysgol Gyfun Cefn Saeson'),
('Ysgol Gyfun Coed-Y-Ian'),
('Ysgol Gyfun Cwm Rhymni'),
('Ysgol Gyfun Cwmtawe'),
('Ysgol Gyfun Cymer Rhondda'),
('Ysgol Gyfun Cynffig'),
('Ysgol Gyfun David Hughes'),
('Ysgol Gyfun Dyffryn Aman'),
('Ysgol Gyfun Emlyn'),
('Ysgol Gyfun Garth Olwg'),
('Ysgol Gyfun Gatholig Joseff Sant'),
('Ysgol Gyfun Gatholig Sant Ioan Llwyd'),
('Ysgol Gyfun Gwent Is Coed'),
('Ysgol Gyfun Gwynllyw'),
('Ysgol Gyfun Gwyr'),
('Ysgol Gyfun Gymraeg Bro Edern'),
('Ysgol Gyfun Gymraeg GlantÃ¢f'),
('Ysgol Gyfun Gymraeg Glantâf'),
('Ysgol Gyfun Gymraeg Llangynwyd'),
('Ysgol Gyfun Gymraeg Plasmawr'),
('Ysgol Gyfun Gymunedol Rhisga'),
('Ysgol Gyfun Heol-ddu'),
('Ysgol Gyfun Lewis I Ferched'),
('Ysgol Gyfun Llangefni'),
('Ysgol Gyfun Llanhari'),
('Ysgol Gyfun Llanilltud Fawr'),
('Ysgol Gyfun Pantycellyn'),
('Ysgol Gyfun Penglais'),
('Ysgol Gyfun Penweddig'),
('Ysgol Gyfun Penyrheol'),
('Ysgol Gyfun Porthcawl'),
('Ysgol Gyfun Rhydywaun'),
('Ysgol Gyfun Tonyrefail'),
('Ysgol Gyfun Treforys'),
('Ysgol Gyfun Y Bontfaen'),
('Ysgol Gyfun Y Pant'),
('Ysgol Gyfun Y Strade'),
('Ysgol Gyfun Yr Esgob Gor'),
('Ysgol Gyfun Ystalyfera'),
('Ysgol Gymradd Y Rhos'),
('Ysgol Gymraeg'),
('Ysgol Gymraeg Aberystwyth'),
('Ysgol Gymraeg Blaendulais'),
('Ysgol Gymraeg Bodringallt'),
('Ysgol Gymraeg Bro Allta'),
('Ysgol Gymraeg Bro Dur'),
('Ysgol Gymraeg Bro Eirwg'),
('Ysgol Gymraeg Bro Morgannwg'),
('Ysgol Gymraeg Bro Ogwr'),
('Ysgol Gymraeg Bro Teyrnon'),
('Ysgol Gymraeg Brohelyg'),
('Ysgol Gymraeg Brynsierfel'),
('Ysgol Gymraeg Coed-Y-Gof'),
('Ysgol Gymraeg Croes Atti'),
('Ysgol Gymraeg Cwm Derwen'),
('Ysgol Gymraeg Cwm Gwyddon'),
('Ysgol Gymraeg Cwmbran A Meithrin'),
('Ysgol Gymraeg Dewi Sant'),
('Ysgol Gymraeg Dyffryn Glowyr'),
('Ysgol Gymraeg Ffwrnes'),
('Ysgol Gymraeg Gilfach Fargoed'),
('Ysgol Gymraeg Glan Ceubal'),
('Ysgol Gymraeg Gwaun Cae Gurwen'),
('Ysgol Gymraeg Gwaun Y Nant'),
('Ysgol Gymraeg Gwenllian'),
('Ysgol Gymraeg Ifor Hael'),
('Ysgol Gymraeg Melin Gruffydd'),
('Ysgol Gymraeg Mornant Picton'),
('Ysgol Gymraeg Mynachlog Nedd'),
('Ysgol Gymraeg Nant Caerau'),
('Ysgol Gymraeg Pen-Y-Groes'),
('Ysgol Gymraeg Plas Coch'),
('Ysgol Gymraeg Rhyd y Grug'),
('Ysgol Gymraeg Rhydaman'),
('Ysgol Gymraeg Tan-Y-Lan'),
('Ysgol Gymraeg Trelyn'),
('Ysgol Gymraeg Y Fenni'),
('Ysgol Gymraeg y Gwernant'),
('Ysgol Gymraeg Ystalyfera'),
('Ysgol Gymrarg Casnewydd'),
('Ysgol Gymreig Pwll Coch'),
('Ysgol Gymuned Carreglefn'),
('Ysgol Gymuned Llanerchymedd'),
('Ysgol Gymuned Moelfre'),
('Ysgol Gymuned Penisarwaun'),
('Ysgol Gymuned Y Fali'),
('Ysgol Gymuned Y Gors'),
('Ysgol Gymunedol Abercanaid'),
('Ysgol Gymunedol Aberdar'),
('Ysgol Gymunedol Bodnant'),
('Ysgol Gymunedol Cefn Hengoed'),
('Ysgol Gymunedol Coedybryn'),
('Ysgol Gymunedol Croesgoch'),
('Ysgol Gymunedol Daniel James'),
('Ysgol Gymunedol Dylan Thomas'),
('Ysgol Gymunedol Felindre'),
('Ysgol Gymunedol Llanfihangel-Y-Creuddyn'),
('Ysgol Gymunedol Llangatwg'),
('Ysgol Gymunedol Neyland'),
('Ysgol Gymunedol Plascrug'),
('Ysgol Gymunedol Talybont'),
('Ysgol Gymunedol Yr Eglwys Yng Nghymru Trefonnen Ll'),
('Ysgol Gymunedol Yr Eglwys Yng Nghymru Trefonnen Llandrindod'),
('Ysgol Gynradd'),
('Ysgol Gynradd a Meithrin Dewstow'),
('Ysgol Gynradd a Meithrin Durand'),
('Ysgol Gynradd A Meithrin Gatholig Dewi Sant'),
('Ysgol Gynradd a Meithrin Thornwell'),
('Ysgol Gynradd Aberaeron'),
('Ysgol Gynradd Aberbanc'),
('Ysgol Gynradd Abercaseg'),
('Ysgol Gynradd Aberllechau'),
('Ysgol Gynradd Abernant Primary School'),
('Ysgol Gynradd Aberporth'),
('Ysgol Gynradd Abersoch'),
('Ysgol Gynradd Ac Uned Feithrin Albert'),
('Ysgol Gynradd Ac Uned Feithrin St Illtyd'),
('Ysgol Gynradd Adamsdown'),
('Ysgol Gynradd Alltwalis'),
('Ysgol Gynradd Amlwch'),
('Ysgol Gynradd Arberth'),
('Ysgol Gynradd Beaumaris'),
('Ysgol Gynradd Beddgelert'),
('Ysgol Gynradd Bethel'),
('Ysgol Gynradd Betws-Y-Coed'),
('Ysgol Gynradd Bigyn'),
('Ysgol Gynradd Blaengwawr'),
('Ysgol Gynradd Bodffordd'),
('Ysgol Gynradd Bodorgan'),
('Ysgol Gynradd Bodringallt Primary School'),
('Ysgol Gynradd Bontddu'),
('Ysgol Gynradd Bontnewydd'),
('Ysgol Gynradd Bracla'),
('Ysgol Gynradd Brithdir'),
('Ysgol Gynradd Bron Y Foel'),
('Ysgol Gynradd Brychdyn'),
('Ysgol Gynradd Bryncethin'),
('Ysgol Gynradd Bryngwran'),
('Ysgol Gynradd Brynhyfryd'),
('Ysgol Gynradd Brynmenyn'),
('Ysgol Gynradd Brynnau'),
('Ysgol Gynradd Brynsaron'),
('Ysgol Gynradd Brynsiencyn'),
('Ysgol Gynradd Buttington Trewern'),
('Ysgol Gynradd Bwrlais'),
('Ysgol Gynradd Cae-Draw'),
('Ysgol Gynradd Caer Nant'),
('Ysgol Gynradd Caerau'),
('Ysgol Gynradd Capcoch'),
('Ysgol Gynradd Capel Garmon'),
('Ysgol Gynradd Capel Iwan'),
('Ysgol Gynradd Caradog'),
('Ysgol Gynradd Carmel'),
('Ysgol Gynradd Carno'),
('Ysgol Gynradd Catholig Sant Roberts'),
('Ysgol Gynradd Cefn-Y-Pant'),
('Ysgol Gynradd Cemaes'),
('Ysgol Gynradd Chwilog'),
('Ysgol Gynradd Cilcennin'),
('Ysgol Gynradd Ciliau Parc'),
('Ysgol Gynradd Coed Hirwaun Primary School'),
('Ysgol Gynradd Coedffranc'),
('Ysgol Gynradd Coedpenmaen'),
('Ysgol Gynradd Coed-Yr-Esgob'),
('Ysgol Gynradd Coety'),
('Ysgol Gynradd Corn Hir'),
('Ysgol Gynradd Corneli'),
('Ysgol Gynradd Creigiau'),
('Ysgol Gynradd Crindai'),
('Ysgol Gynradd Cwm Clydach Primary Shool'),
('Ysgol Gynradd Cwmffrwdoer'),
('Ysgol Gynradd Cwmpadarn'),
('Ysgol Gynradd Cymuned y Maerdy'),
('Ysgol Gynradd Ddwyieithog Y Login Fach'),
('Ysgol Gynradd Derwendeg'),
('Ysgol Gynradd Dinas Mawddwy'),
('Ysgol Gynradd Dinbych y Pysgod'),
('Ysgol Gynradd Dolbadarn'),
('Ysgol Gynradd Dolgellau'),
('Ysgol Gynradd Dowlais'),
('Ysgol Gynradd Dwyran'),
('Ysgol Gynradd Dyffryn Banw'),
('Ysgol Gynradd Edern'),
('Ysgol Gynradd Eglwys Crist'),
('Ysgol Gynradd Eglwysbach'),
('Ysgol Gynradd Evenlode'),
('Ysgol Gynradd Felinfach'),
('Ysgol Gynradd Felinwnda'),
('Ysgol Gynradd Ffairfach'),
('Ysgol Gynradd Ffestiniog'),
('Ysgol Gynradd Ffynnon-TÃ¢f'),
('Ysgol Gynradd Ffynnon-Tâf'),
('Ysgol Gynradd Gaer'),
('Ysgol Gynradd Garndolbenmaen'),
('Ysgol Gynradd Gatholic Padarn Sant'),
('Ysgol Gynradd Gatholig Crist Y Brenin'),
('Ysgol Gynradd Gatholig Padarn'),
('Ysgol Gynradd Gatholig Padrig Santl'),
('Ysgol Gynradd Gatholig Y Santes Fair'),
('Ysgol Gynradd Gatholig Y Santes-Fair'),
('Ysgol Gynradd Gelli'),
('Ysgol Gynradd Gladstone'),
('Ysgol Gynradd Glan Conwy'),
('Ysgol Gynradd Glan Wysg'),
('Ysgol Gynradd Glan-Yr-Afon Primary School'),
('Ysgol Gynradd Glyncoed'),
('Ysgol Gynradd Gnoll'),
('Ysgol Gynradd Godrer Graig'),
('Ysgol Gynradd Goetre'),
('Ysgol Gynradd Greenhill'),
('Ysgol Gynradd Gronant'),
('Ysgol Gynradd Gwaelod Y Garth'),
('Ysgol Gynradd Gwalchmai'),
('Ysgol Gynradd Gwenffrwd Primary School'),
('Ysgol Gynradd Gwenlli'),
('Ysgol Gynradd Gwersyllt'),
('Ysgol Gynradd Gwyrosydd'),
('Ysgol Gynradd Gymorthedig yr Eglwys yng Nghymru'),
('Ysgol Gynradd Gymraeg'),
('Ysgol Gynradd Gymraeg Abercynon'),
('Ysgol Gynradd Gymraeg Aberdare'),
('Ysgol Gynradd Gymraeg Bronllwyn'),
('Ysgol Gynradd Gymraeg Bryniago'),
('Ysgol Gynradd Gymraeg Bryn-y-Mòr'),
('Ysgol Gynradd Gymraeg Castellau'),
('Ysgol Gynradd Gymraeg Castell-Nedd'),
('Ysgol Gynradd Gymraeg Cwm Garw'),
('Ysgol Gynradd Gymraeg Evan James'),
('Ysgol Gynradd Gymraeg Felindre'),
('Ysgol Gynradd Gymraeg Garth Olwg'),
('Ysgol Gynradd Gymraeg Gellionnen'),
('Ysgol Gynradd Gymraeg Llantrisant'),
('Ysgol Gynradd Gymraeg Llwyncelyn'),
('Ysgol Gynradd Gymraeg Llwynderw'),
('Ysgol Gynradd Gymraeg Llyn-Y-Forwyn'),
('Ysgol Gynradd Gymraeg Lòn Las'),
('Ysgol Gynradd Gymraeg Pontardawe'),
('Ysgol Gynradd Gymraeg Pont-Sion-Norton'),
('Ysgol Gynradd Gymraeg Pontybrenin'),
('Ysgol Gynradd Gymraeg Rhosafan'),
('Ysgol Gynradd Gymraeg Santes Tudful'),
('Ysgol Gynradd Gymraeg Tirdeunaw'),
('Ysgol Gynradd Gymraeg Trebannws'),
('Ysgol Gynradd Gymraeg Tyler Ynn'),
('Ysgol Gynradd Gymraeg Y Castell'),
('Ysgol Gynradd Gymraeg Ynyswen'),
('Ysgol Gynradd Gymuned Penderyn'),
('Ysgol Gynradd Gymuned Ynyshir'),
('Ysgol Gynradd Gymunedol Abercynon'),
('Ysgol Gynradd Gymunedol Abermule'),
('Ysgol Gynradd Gymunedol Bryn Teg'),
('Ysgol Gynradd Gymunedol Caersws'),
('Ysgol Gynradd Gymunedol Clydau'),
('Ysgol Gynradd Gymunedol Coed y Dderwen'),
('Ysgol Gynradd Gymunedol Craig Yr Wylfa'),
('Ysgol Gynradd Gymunedol Cwmbach'),
('Ysgol Gynradd Gymunedol Eglwyswrw'),
('Ysgol Gynradd Gymunedol Gymraeg Llantrisant'),
('Ysgol Gynradd Gymunedol Halfway'),
('Ysgol Gynradd Gymunedol Llangwyryfon'),
('Ysgol Gynradd Gymunedol Llanon'),
('Ysgol Gynradd Gymunedol Machynlleth'),
('Ysgol Gynradd Gymunedol Peniel'),
('Ysgol Gynradd Gymunedol T. Llew Jones'),
('Ysgol Gynradd Gymunedol y Parc'),
('Ysgol Gynradd Gymunedol Ynysboeth'),
('Ysgol Gynradd Gymunedol Ynysowen'),
('Ysgol Gynradd Gymunedol Yr Ystog'),
('Ysgol Gynradd Hendreforgan'),
('Ysgol Gynradd Heol-Y-Cyw'),
('Ysgol Gynradd Holt Primary School'),
('Ysgol Gynradd Llanafan'),
('Ysgol Gynradd Llanarmon DC'),
('Ysgol Gynradd Llanbedrog'),
('Ysgol Gynradd Llanddona'),
('Ysgol Gynradd Llandegfan'),
('Ysgol Gynradd Llandeilo'),
('Ysgol Gynradd Llandwrog'),
('Ysgol Gynradd Llandybie'),
('Ysgol Gynradd Llandygai'),
('Ysgol Gynradd Llandysul'),
('Ysgol Gynradd Llanelltyd'),
('Ysgol Gynradd Llanerfyl'),
('Ysgol Gynradd Llanfaes Primary School'),
('Ysgol Gynradd Llanfair Llwyth Yfnwg Gladestry Chur'),
('Ysgol Gynradd Llanfair Llwyth Yfnwg Gladestry Church-In-Wales Primary School'),
('Ysgol Gynradd Llanfairpwllgwyngyll'),
('Ysgol Gynradd Llanfair-ym-Muallt'),
('Ysgol Gynradd Llanfarian'),
('Ysgol Gynradd Llanfarthin'),
('Ysgol Gynradd Llanfechell'),
('Ysgol Gynradd Llanfihangel Glyn Myfyr'),
('Ysgol Gynradd Llanfyllin'),
('Ysgol Gynradd Llangaffo'),
('Ysgol Gynradd Llangan'),
('Ysgol Gynradd Llangeitho'),
('Ysgol Gynradd Llangwyryfon'),
('Ysgol Gynradd Llangybi'),
('Ysgol Gynradd Llangyfelach'),
('Ysgol Gynradd Llanidloes'),
('Ysgol Gynradd Llanilar'),
('Ysgol Gynradd Llanilltud Faerdref'),
('Ysgol Gynradd Llanllechid'),
('Ysgol Gynradd Llanllwchaiarn'),
('Ysgol Gynradd Llanllyfni'),
('Ysgol Gynradd Llannon'),
('Ysgol Gynradd Llanpumsaint'),
('Ysgol Gynradd Llanrhaeadr Ym Mochnant'),
('Ysgol Gynradd Llanrug'),
('Ysgol Gynradd Llansawel'),
('Ysgol Gynradd Llwydcoed'),
('Ysgol Gynradd Llwyn-Yr-Eos'),
('Ysgol Gynradd Llynarth'),
('Ysgol Gynradd Llys Malpas'),
('Ysgol Gynradd Machen'),
('Ysgol Gynradd Maendy'),
('Ysgol Gynradd Maes-Glas'),
('Ysgol Gynradd Maesincla'),
('Ysgol Gynradd Maesybryn'),
('Ysgol Gynradd Maes-Y-Deri'),
('Ysgol Gynradd Maindee'),
('Ysgol Gynradd Melin'),
('Ysgol Gynradd Milton'),
('Ysgol Gynradd Monnow'),
('Ysgol Gynradd Mynach'),
('Ysgol Gynradd Nant y feln'),
('Ysgol Gynradd Nant-Y-Moel'),
('Ysgol Gynradd Nebo'),
('Ysgol Gynradd Nefyn'),
('Ysgol Gynradd Newydd Penrhyn Angle'),
('Ysgol Gynradd Niwbwrch'),
('Ysgol Gynradd O M Edwards'),
('Ysgol Gynradd Parc Aberdar'),
('Ysgol Gynradd Parc Acton'),
('Ysgol Gynradd Parc Cornist'),
('Ysgol Gynradd Parc Hendredenni'),
('Ysgol Gynradd Parc Jiwbili'),
('Ysgol Gynradd Parc Malpas'),
('Ysgol Gynradd Parcyrhun'),
('Ysgol Gynradd Pembroke'),
('Ysgol Gynradd Penarlag'),
('Ysgol Gynradd Pencoed'),
('Ysgol Gynradd Pendyrus'),
('Ysgol Gynradd Penllwyn'),
('Ysgol Gynradd Penmachno'),
('Ysgol Gynradd Penrhys'),
('Ysgol Gynradd Pentraeth'),
('Ysgol Gynradd Pentre a Reolir'),
('Ysgol Gynradd Pentrechwyth'),
('Ysgol Gynradd Pentrer Graig'),
('Ysgol Gynradd Pentreuchaf'),
('Ysgol Gynradd Penuwch'),
('Ysgol Gynradd Penybont'),
('Ysgol Gynradd Penygawsi'),
('Ysgol Gynradd Plasmarl'),
('Ysgol Gynradd Plas-Y-Felin'),
('Ysgol Gynradd Pontgarreg'),
('Ysgol Gynradd Pontnewydd-Ar-Wy'),
('Ysgol Gynradd Pontrhydfendigiad'),
('Ysgol Gynradd Pontsenni Sennybridge Primary School'),
('Ysgol Gynradd Pontsian'),
('Ysgol Gynradd Pontyberem'),
('Ysgol Gynradd Pontybrenin'),
('Ysgol Gynradd Pontyclun'),
('Ysgol Gynradd Prendergast Primary School'),
('Ysgol Gynradd Pum Heol'),
('Ysgol Gynradd Rhiwbeina Rhiwbina Prmary School'),
('Ysgol Gynradd Rhiwlas'),
('Ysgol Gynradd Rhoscolyn'),
('Ysgol Gynradd Rhosddu'),
('Ysgol Gynradd Rhosgadfan'),
('Ysgol Gynradd Rhosneigr County Primary School'),
('Ysgol Gynradd Rhostryfan'),
('Ysgol Gynradd Rhostyllen Primary School'),
('Ysgol Gynradd Rhosybol'),
('Ysgol Gynradd Rhosymedre'),
('Ysgol Gynradd Rhydypennau'),
('Ysgol Gynradd Rogiet'),
('Ysgol Gynradd Saint-Y-Brid'),
('Ysgol Gynradd Sandfields'),
('Ysgol Gynradd Sant Alban'),
('Ysgol Gynradd Sant Cuthbert'),
('Ysgol Gynradd Sant Elfod'),
('Ysgol Gynradd Sant Iago'),
('Ysgol Gynradd Sant Joseff'),
('Ysgol Gynradd Saron'),
('Ysgol Gynradd Sealand Primary School'),
('Ysgol Gynradd Sgeti'),
('Ysgol Gynradd Sirol A Chanolfan Gymdeithasol Llanb'),
('Ysgol Gynradd Sirol A Chanolfan Gymdeithasol Llanbrynmair'),
('Ysgol Gynradd Sirol Maenclochog'),
('Ysgol Gynradd St Illtyds'),
('Ysgol Gynradd Stebonheath'),
('Ysgol Gynradd Syr John Rhys'),
('Ysgol Gynradd Talgarth'),
('Ysgol Gynradd Tal-Y-Bont'),
('Ysgol Gynradd Tanygrisiau'),
('Ysgol Gynradd Tondu'),
('Ysgol Gynradd Tonyrefail'),
('Ysgol Gynradd Trallwn'),
('Ysgol Gynradd Trefansel'),
('Ysgol Gynradd Trefilan'),
('Ysgol Gynradd Treforys'),
('Ysgol Gynradd Tref-Y-Rhyg'),
('Ysgol Gynradd Tregarth'),
('Ysgol Gynradd Trelewis'),
('Ysgol Gynradd Trelogan County Primary School'),
('Ysgol Gynradd Trem Y Kymin A Meithrinfa'),
('Ysgol Gynradd Treowen'),
('Ysgol Gynradd Tudweiliog'),
('Ysgol Gynradd Tynyrheol'),
('Ysgol Gynradd Tywyn'),
('Ysgol Gynradd Victoria'),
('Ysgol Gynradd Waunceirch'),
('Ysgol Gynradd Waunfawr'),
('Ysgol Gynradd Westwood'),
('Ysgol Gynradd Williamstown'),
('Ysgol Gynradd Windsor Clive'),
('Ysgol Gynradd Wirfoddol a Reolir yr Eglwys yng Ngh'),
('Ysgol Gynradd Wirfoddol a Reolir yr Eglwys yng Nghymru Rhaglan'),
('Ysgol Gynradd Y Blaenau'),
('Ysgol Gynradd Y Crwys'),
('Ysgol Gynradd Y Ffòr'),
('Ysgol Gynradd Y Garn'),
('Ysgol Gynradd Y Garreg Wen'),
('Ysgol Gynradd Y Mileniwm Roseheyworth'),
('Ysgol Gynradd Y Santes Gwenffrewi'),
('Ysgol Gynradd Y Talwrn'),
('Ysgol Gynradd y Tyllgoed'),
('Ysgol Gynradd Y Tymbl'),
('Ysgol Gynradd Ynys Y Barri'),
('Ysgol Gynradd Ynysmaerdy'),
('Ysgol Gynradd Yr Eglwys Nghymru Rhaeadr Gwy'),
('Ysgol Gynradd yr Eglwys yng Nghymru Cleirwy'),
('Ysgol Gynradd Yr Eglwys Yng Nghymru Llansanwyr A L'),
('Ysgol Gynradd Yr Eglwys Yng Nghymru Llansanwyr A Llanharri'),
('Ysgol Gynradd yr Eglwys yng Nghymru Malpas'),
('Ysgol Gynradd Yr Eglwys Yng Nghymru Tref Aberdar'),
('Ysgol Gynradd Ysbyty Ystwyth'),
('Ysgol Gynrodd Tondu'),
('Ysgol Hafan Y Mor'),
('Ysgol Hafod Lon'),
('Ysgol Henblas'),
('Ysgol Hendre'),
('Ysgol Henllan'),
('Ysgol Heol Goffa'),
('Ysgol Heol-Y-Celyn'),
('Ysgol Hiraddug'),
('Ysgol Hirael'),
('Ysgol I D Hooson'),
('Ysgol Iau'),
('Ysgol Iau Clydach'),
('Ysgol Iau Fairwater'),
('Ysgol Iau Greenlawn'),
('Ysgol Iau Hafren Hafren Junior School'),
('Ysgol Iau Hen Golwyn'),
('Ysgol Iau Llangewydd'),
('Ysgol Iau Porth Tywyn'),
('Ysgol Iau Sant Helen'),
('Ysgol Ieuan Gwynedd'),
('Ysgol Ifor Bach'),
('Ysgol Iolo Morganwg'),
('Ysgol John Bright'),
('Ysgol Kingsland'),
('Ysgol Lacharn'),
('Ysgol Lewis Pengam'),
('Ysgol Llanaelhaearn'),
('Ysgol Llanbedrgoch'),
('Ysgol Llanddulas'),
('Ysgol Llandrillo-yn-Rhos'),
('Ysgol Llandudoch'),
('Ysgol Llanedi School'),
('Ysgol Llanfawr'),
('Ysgol Llangain'),
('Ysgol Llangelynnin'),
('Ysgol Llangoed'),
('Ysgol Llangwm'),
('Ysgol Llangynfelyn'),
('Ysgol Llanystumdwy'),
('Ysgol Llidiardau'),
('Ysgol Llwchradd Islwyn'),
('Ysgol Llys Hywel'),
('Ysgol Llywelyn'),
('Ysgol Machreth'),
('Ysgol Maenofferen'),
('Ysgol Maes Edwin'),
('Ysgol Maes Garmon'),
('Ysgol Maes Hyfryd'),
('Ysgol Maes Y Felin'),
('Ysgol Maes Y Gwendraeth'),
('Ysgol Maes Y Mynydd'),
('Ysgol Maesglas'),
('Ysgol Maesteg'),
('Ysgol Maes-y-Coed'),
('Ysgol Maesydderwen'),
('Ysgol Maesydre'),
('Ysgol Maes-Y-Llan'),
('Ysgol Mair Roman Catholic Junior School'),
('Ysgol Manod'),
('Ysgol Melyd'),
('Ysgol Merllyn Primary School'),
('Ysgol Morfa Nefyn'),
('Ysgol Morfa Rhianedd'),
('Ysgol Morgan Llwyd School'),
('Ysgol Morswyn'),
('Ysgol Mynydd Bychan'),
('Ysgol Mynydd Isa'),
('YSGOL NANT Y GROES'),
('Ysgol Nantgaredig'),
('Ysgol Neuadd Brynllywarch'),
('Ysgol Owen Jones'),
('Ysgol Pant Y Rhedyn'),
('Ysgol Panteg'),
('Ysgol Pant-Pastynog'),
('Ysgol Parc Waundew'),
('Ysgol Parc Y Bont'),
('Ysgol Parc y Llan'),
('Ysgol Parc-y-Tywyn'),
('Ysgol Pen Barras'),
('Ysgol Pen Coch'),
('Ysgol Pen Rhos'),
('Ysgol Pen Y Pil'),
('Ysgol Penalltau'),
('Ysgol Pen-Barras'),
('Ysgol Pencae'),
('Ysgol Pendalar'),
('Ysgol Pendref'),
('Ysgol Penfro'),
('Ysgol Penmaes'),
('Ysgol Penmorfa'),
('Ysgol Pennal'),
('Ysgol Pennant'),
('Ysgol Penrhryn'),
('Ysgol Pentrehafod'),
('Ysgol Penybryn'),
('Ysgol Pen-Y-Bryn'),
('Ysgol Penycae'),
('Ysgol Penygaer'),
('Ysgol Pen-Y-Garth'),
('Ysgol Penysarn'),
('Ysgol Place'),
('Ysgol Plant Bach Clydach'),
('Ysgol Plant Bach Copperworks Infants And Nursery S'),
('Ysgol Plant Bach Copperworks Infants And Nursery School'),
('Ysgol Plant Bach Copperworks Nursery School'),
('Ysgol Plant Bach Ferndale'),
('Ysgol Plant Bach Llanfabon'),
('Ysgol Plant Iau Hendre'),
('Ysgol Plas Brondyffryn'),
('Ysgol Plas Cefndy'),
('Ysgol Pont Y Gòf'),
('Ysgol Ponthenri'),
('Ysgol Pontrobert'),
('Ysgol Portfield'),
('Ysgol Porth Y Felin'),
('Ysgol Powys'),
('Ysgol Reoledig Borthyn'),
('Ysgol Rhiw'),
('Ysgol Rhiwabon High School'),
('Ysgol Rhos Y Wlad'),
('Ysgol Rhosnesni High School'),
('Ysgol Rhyd Y Llan'),
('Ysgol Rhydygors'),
('Ysgol Rhys Prichard'),
('Ysgol San Sior'),
('Ysgol Sant Christopher'),
('Ysgol Sant Cyrig'),
('Ysgol Sant Dunawd Community School'),
('Ysgol Santes Dwynwen'),
('Ysgol Santes Fair'),
('Ysgol Santes Helen'),
('Ysgol Sarn Bach'),
('Ysgol Street'),
('Ysgol Stryd y Rhos'),
('Ysgol Sychdyn'),
('Ysgol Syr Hugh Owen'),
('Ysgol Syr Thomas Jones'),
('Ysgol Syr Thomas Picton'),
('Ysgol T Gwynn Jones'),
('Ysgol TÅ· Ffynnon'),
('Ysgol Tafarnspite'),
('Ysgol Talgarreg'),
('Ysgol Tan Y Castell'),
('Ysgol Tan Y Marian'),
('Ysgol Tasker Milward'),
('Ysgol Teilo Sant'),
('Ysgol Tir Morfa'),
('Ysgol Treborth'),
('Ysgol Treferthyr'),
('Ysgol Treganna'),
('Ysgol Treioan'),
('Ysgol Tryfan'),
('Ysgol Tudno'),
('Ysgol Twm Or Nant'),
('Ysgol Ty Coch'),
('Ysgol Ty Ffynnon'),
('Ysgol Tywyn'),
('Ysgol Uchaf'),
('Ysgol Uchrad Penarlag'),
('Ysgol Uwchradd'),
('Ysgol Uwchradd Aberhonddu'),
('Ysgol Uwchradd Aberteifi'),
('Ysgol Uwchradd Argoed'),
('Ysgol Uwchradd Caereinion Caereinion High School'),
('Ysgol Uwchradd Caergybi'),
('Ysgol Uwchradd Casnewydd'),
('Ysgol Uwchradd Crughywel Crickhowell High School'),
('Ysgol Uwchradd Eirias'),
('Ysgol Uwchradd Elfed High School'),
('Ysgol Uwchradd Gatholig Archesgob McGrath'),
('Ysgol Uwchradd Hawthorn'),
('Ysgol Uwchradd John Summers High School'),
('Ysgol Uwchradd Llandrindod'),
('Ysgol Uwchradd Llanfyllin'),
('Ysgol Uwchradd Llanidloes'),
('Ysgol Uwchradd Llanwern'),
('Ysgol Uwchradd Pencoedtre'),
('Ysgol Uwchradd Pontypridd High School'),
('Ysgol Uwchradd Prestatyn High School'),
('Ysgol Uwchradd Teilo Sant yr Eglwys yng Nghymru'),
('Ysgol Uwchradd Treffynnon'),
('Ysgol Uwchradd Whitmore'),
('Ysgol Uwchradd Woodlands'),
('Ysgol Uwchradd Y Drenewydd'),
('Ysgol Uwchradd Y Dwyrain'),
('Ysgol Uwchradd y Fflint'),
('Ysgol Uwchradd Y Frenhines Elisabeth'),
('Ysgol Uwchradd Y Rhyl'),
('Ysgol Uwchradd Y Trallwng'),
('Ysgol Uwchradd Yr Ysgol Newydd'),
('Ysgol Wirfoddol Reoledig Angle'),
('Ysgol Wirfoddola A Reolir Treftadeath Blaenafon'),
('Ysgol Y Babanod'),
('Ysgol Y Babanod Aberdaugleddau'),
('Ysgol Y Bedol'),
('Ysgol Y Berllan Deg'),
('Ysgol y Berwyn'),
('Ysgol Y Borth'),
('Ysgol Y Bryn Bryn School'),
('Ysgol Y Bynea'),
('Ysgol Y Castell'),
('Ysgol Y Creuddyn'),
('Ysgol y Cribarth'),
('Ysgol Y Dderi'),
('Ysgol y Dderwen'),
('Ysgol Y Ddraig'),
('Ysgol Y Ddwylan'),
('Ysgol Y Deri'),
('Ysgol Y Faenol'),
('Ysgol Y Felin'),
('Ysgol Y Felinheli'),
('Ysgol Y Ferch Or Sger'),
('Ysgol Y Foryd'),
('Ysgol y Frenni'),
('Ysgol Y Friog'),
('Ysgol Y Fro'),
('Ysgol Y Gader'),
('Ysgol Y Gaer'),
('Ysgol Y Garnedd'),
('Ysgol Y Garreg'),
('Ysgol Y Gelli'),
('Ysgol Y Gogarth'),
('Ysgol Y Gorlan'),
('Ysgol Y Graig'),
('Ysgol Y Grango'),
('Ysgol Y Lawnt'),
('Ysgol Y Llan Whitford (Voluntary) Primary School'),
('Ysgol Y Maelor'),
('Ysgol Y Merched Aberdâr'),
('Ysgol Y Moelwyn'),
('Ysgol y Mynydd Du'),
('Ysgol Y Plas Llanelian'),
('Ysgol y Preseli'),
('Ysgol Y Rhewl'),
('Ysgol Y Traeth'),
('Ysgol Y Twyn'),
('Ysgol Y Tywyn'),
('Ysgol Y Wern'),
('Ysgol Yr Eglwys Yng Nghymru Ffynnon Gynydd'),
('Ysgol yr Eglwys yng Nghymru Llangors'),
('Ysgol Yr Eglwys Yng Nghymru Priordy'),
('Ysgol Yr Eglwys Yng Nghymru Tref-Y-Clawdd'),
('Ysgol Yr Eifl'),
('Ysgol Yr Eos'),
('Ysgol Yr Hendre'),
('Ysgol Ysbyty'),
('Ysgoldy Covert'),
('Ysgoldy Hill'),
('Ysgol-Y-Bannau'),
('Ysgol-Y-Berwyn'),
('Ysgol-Y-Drindod Junior School'),
('Ysgol-Y-Fron Junior School'),
('Ysgol-Y-Graig Schools'),
('Ysgol-Y-Llys'),
('Ysgol-Y-Parc'),
('Ysgol-Yr-Esgob'),
('Ysgol-Y-Waen'),
('Ysgool Gynradd Llandochau'),
('Ysgubor'),
('Ysgubor Abad'),
('Ysgubor Fach'),
('Ysgubor Fach Street'),
('Ysgubor Mountain'),
('Ysgubor Newydd'),
('Ysgubor Newydd Lane'),
('Ysgubor-Fawr'),
('Ysguboriaur Bugail'),
('Ysguborwen'),
('Ysguborwen Road'),
('Ysgubor-wen Wood'),
('Ysgubor-y-Coed'),
('Ysguthan Road'),
('Ysgwd Ffordd'),
('Ysgwd-Ffordd'),
('Ysgyryd Fach'),
('Ysgyryd Fawr'),
('Yspitty'),
('Yspitty Road'),
('Yspytty Road'),
('Yspytty-Cynfyn'),
('Yspyty Cwm Rhondda'),
('Ystablaur Ysgol'),
('Ystad Bryn Y Ffermwyr'),
('Ystad Cae Bach'),
('Ystad Celyn'),
('Ystad Coed Madog'),
('Ystad Cwm Taf'),
('Ystad Ddiwydiannol Y Glyn'),
('Ystad Deri'),
('Ystad Fferm Y Berllan'),
('Ystad Glorian'),
('Ystad Gwylfa'),
('Ystad Llwyn Bedw'),
('Ystad Mur Poeth'),
('Ystad Tyn Berllan'),
('Ystâd-Y-Gotrel'),
('Ystafelloedd'),
('Ystalyfera'),
('Ysticlau Road'),
('Ysticl-Garu'),
('Ystrad'),
('Ystrad Aeron'),
('Ystrad Barwig'),
('Ystrad Close'),
('Ystrad Drive'),
('Ystrad Einion'),
('Ystrad Einon'),
('Ystrad Fawr'),
('Ystrad Fawr Hospital'),
('Ystrad Fflur'),
('Ystrad Hir'),
('Ystrad Meurig'),
('Ystrad Mynach'),
('Ystrad Mynach Campus'),
('Ystrad Mynach Primary School'),
('Ystrad Rhondda'),
('Ystrad Road'),
('Ystrad Street'),
('Ystrad Terrace'),
('Ystrad Wood'),
('Ystradbarwig Terrace'),
('Ystrad-Einion'),
('Ystrad-Fawr Villas'),
('Ystradfellte'),
('Ystradfellte Reservoir'),
('Ystrad-gwyn'),
('Ystradgynlais'),
('Ystradgynlais Community Hospital'),
('Ystradmeurig'),
('Ystradowen'),
('Ystrodir Wood'),
('Ystruth Primary School'),
('Ystryd Ddu'),
('Ystryd Faen'),
('Ystryd Fawr'),
('Ystryd Y Ceunant'),
('Ystum Taf'),
('Ystumllwynarth'),
('Ystumtuen'),
('Ystwyth'),
('Ystwyth Place'),
('Ythan Place'),
('Ythan Road'),
('Ythan Terrace'),
('Ythanbank'),
('Ythanwells'),
('Ythsie'),
('Ytymbl'),
('Yuill Avenue'),
('Yukon Gardens'),
('Yukon Road'),
('Yukon Terrace'),
('Yukon Way'),
('Yulan Drive'),
('Yule Close'),
('Yule Hill'),
('Yule Lane'),
('Yule Place'),
('Yule Road'),
('Yule Square'),
('Yule Street'),
('Yule Terrace'),
('Yule Way'),
('Yule Wood'),
('Yumfrau Taing'),
('Yungnapool'),
('Yuntaskeos'),
('Yunus Khan Close'),
('Yves Mews'),
('Yvetot Avenue'),
('Yvetot Court'),
('Yvonne Close'),
('Yvonne Crescent'),
('Yvonne Grove'),
('Yvonne Road'),
('Ywen Wood'),
('Y-Wern');

-- Down

DELETE FROM "Placename" WHERE "keyword" LIKE 'y%';
