-- Up
INSERT INTO "Placename"
("keyword")
VALUES
('Y Bae'),
('Y Bala'),
('Y Barri'),
('Y Beddau'),
('Y Berllan'),
('Y Blaenau'),
('Y Bonc'),
('Y Bont'),
('Y Bont Hir'),
('Y Bont  Faen'),
('Y Bont  faen a Llanfleiddan'),
('Y Borth'),
('Y Bracty'),
('Y Brif Heol'),
('Y Bryn'),
('Y Bwlfar'),
('Y Bwthyn'),
('Y Bwthyn The Cottage'),
('Y Castellnewydd'),
('Y Cedrwydd'),
('Y Cedrwydden'),
('Y Ceffyl'),
('Y Ceunant'),
('Y Cilffordd'),
('Y Cilgant'),
('Y Clas  ar  Wy'),
('Y Clawdd'),
('Y Clawstrau'),
('Y Clogwyn'),
('Y Clos'),
('Y Clun a Melin  cwrt'),
('Y Cocyd'),
('Y Coed'),
('Y Coed Duon'),
('Y Coleg Merthyr Tudful'),
('Y Copi'),
('Y Corsydd'),
('Y Creunant'),
('Y Crochan'),
('Y Crofft'),
('Y Crwys'),
('Y Cwcwll'),
('Y Cwm'),
('Y Cymer'),
('Y Cyswllt'),
('Y Darren'),
('Y Das'),
('Y Dderwen'),
('Y Dderwen Deg'),
('Y Ddol'),
('Y Ddol Fach'),
('y Ddraenen'),
('Y Ddraenen Wen'),
('Y Ddwyberth'),
('Y Deri'),
('Y Derwydd'),
('Y Dolau'),
('Y Dolydd'),
('Y Dolydd  The Meadows'),
('Y Domen Fawr'),
('Y Drain'),
('Y Dref'),
('Y Dreflan'),
('Y Drenewydd'),
('Y Drenewydd a Llanllwchaearn'),
('Y Drenewydd Gogledd Llanllwchaearn'),
('Y Drenewydd Gorllewin Llanllwchaearn'),
('Y Drim'),
('Y Drindod Dewi Saint'),
('Y Drindod Dewi Sant'),
('Y Drum'),
('Y Fach'),
('Y Faenor'),
('Y Fali'),
('Y Fan'),
('Y Farchnad'),
('Y Fawnen'),
('Y Fedwen'),
('Y Feithrinfa'),
('Y Felin'),
('Y Felin Ffrwd'),
('Y Felin Goed'),
('Y Felin Heli'),
('Y Felin Lon'),
('Y Felinheli'),
('Y Fenni'),
('Y Ferwig'),
('Y Ffald'),
('Y Ffawydden'),
('Y Ffennant'),
('Y Fferi Isaf'),
('Y Fflint'),
('Y Ffordd Wen'),
('Y Ffowndri'),
('Y Ffridd'),
('Y Ffrith'),
('Y Ffrydd'),
('Y Ffynnon Haearn'),
('Y Ffòr'),
('Y Ffôr'),
('Y Foel'),
('Y Foel Goch'),
('Y Foryd'),
('Y Fron'),
('Y Fronllwyd'),
('Y Fâl'),
('Y Gadfa'),
('Y Gaer'),
('Y Gamallt'),
('Y Gamer'),
('Y Gamlas'),
('Y Gamriw'),
('Y Ganolfan'),
('Y Garn'),
('Y Garnedd'),
('Y Garreg'),
('Y Garth'),
('Y Garw'),
('Y Gefnen'),
('Y Geibren'),
('Y Gelli'),
('Y Gelli Gandryll'),
('Y Gerddi'),
('Y Gesail'),
('Y Gifford'),
('Y Gilan'),
('Y Gilfach'),
('Y Gilfach Isaf'),
('Y Gilfach Uchaf'),
('Y Gilfach  goch'),
('Y Gilwern'),
('Y Globa Fawr'),
('Y Glog'),
('Y Glonc'),
('Y Glyderau'),
('Y Glyn'),
('Y Glynnor'),
('Y Glòg'),
('Y Goedlan'),
('Y Goedwig'),
('Y Gogarth'),
('Y Golfa'),
('Y Golff'),
('Y Gorlan'),
('Y Gors'),
('Y Gorsedd'),
('Y Graig'),
('Y Gribin'),
('Y Groes'),
('Y Groes Fagl'),
('Y Groes  Wen'),
('Y Groeslon'),
('Y Grugan'),
('Y Grysmwnt'),
('Y Gully'),
('Y Gurn'),
('Y Gurnos'),
('Y Gwernydd'),
('Y Gwter'),
('Y Gwyndy Ysgol Gyfun Cwm Rhymni'),
('Y Gyrn'),
('Y Lan'),
('Y Lanfa'),
('Y Lasinwen'),
('Y Lawnt'),
('Y Lawnt Fowlio'),
('Y Lincs'),
('Y Llan'),
('Y Llanerch'),
('Y Llannerch'),
('Y Llech'),
('Y Llest'),
('Y Llethr'),
('Y Lliwedd'),
('Y Llwyn'),
('Y Llwyni'),
('Y Lon Gam'),
('Y Lon Goed'),
('Y Lon Groes'),
('Y Lon Las'),
('Y Lòn Gefn'),
('Y Maerdy'),
('Y Maes'),
('Y Mieri'),
('Y Mot'),
('Y Mwmbwls'),
('Y Mynydd Bychan'),
('Y Nant'),
('Y Parc'),
('Y Parciau'),
('Y Penrhyn'),
('Y Pil'),
('Y Pinwydd'),
('Y Popls'),
('Y Poplys'),
('Y Porth'),
('Y Priordy'),
('Y Prom'),
('Y Pîl'),
('Y Rhath'),
('Y Rhigos'),
('Y Rhiw'),
('Y Rhodfa'),
('Y Rhos'),
('Y Rhws'),
('Y Rhyl'),
('Y Ro Fawr'),
('Y Ro Wen'),
('Y Sblot'),
('Y Sgwar'),
('Y Sgwâr'),
('Y Stryd Fawr'),
('Y Stryd Newydd'),
('Y Stryd Uchel'),
('Y Stryt Fawr'),
('Y Swnt'),
('Y Talar'),
('Y Teiryd'),
('Y Traeth'),
('Y Trallwng'),
('Y Trallwng Gungrog'),
('Y Trallwng Llanerchyddol'),
('Y Trwyn'),
('Y Tyddyn'),
('Y Tymbl'),
('Y Waen'),
('Y Waun'),
('Y Waun Fach'),
('Y Weirglodd'),
('Y Wenallt'),
('Y Wennallt'),
('Y Wern'),
('Y Wig'),
('Y  Ddol'),
('Y  Fron'),
('Y  Gaer'),
('Y  Gesail'),
('Y  Glyn'),
('Y  Rhos'),
('Y  Wern'),
('Yaa Field'),
('Yabsley Street'),
('Yacht Haven Quay'),
('Yacht Way'),
('Yachtsman Close'),
('Yacley Close'),
('Yad Moss'),
('Yadburgh Hill'),
('Yadd Linn Wood'),
('Yaddlethorpe'),
('Yade Moss'),
('Yadhill Wood'),
('Yadley Close'),
('Yadley Lane'),
('Yadley Way'),
('Yaffle Crescent'),
('Yaffle Road'),
('Yafford'),
('Yafford Furze Brake'),
('Yafforth'),
('Yafforth Moor'),
('Yafforth Road'),
('Yagden Hill'),
('Yaidon Coppice'),
('Yair Boat Stream'),
('Yair Drive'),
('Yair Hill Forest'),
('Yairs Rise'),
('Yalberton Copse'),
('Yalberton Road'),
('Yalbury Lane'),
('Yalbury Wood Way'),
('Yalden Close'),
('Yalden Gardens'),
('Yalden Lane'),
('Yalden Wood'),
('Yaldham'),
('Yaldhurst Copse'),
('Yaldhurst Court'),
('Yaldhurst Lane'),
('Yalding'),
('Yalding Close'),
('Yalding Drive'),
('Yalding Gardens'),
('Yalding Grove'),
('Yalding Hill'),
('Yalding Road'),
('Yale Close'),
('Yale Crescent'),
('Yale Drive'),
('Yale Grove'),
('Yale Mews'),
('Yale Park'),
('Yale Road'),
('Yale Street'),
('Yale Way'),
('Yall Flat Lane'),
('Yalland Close'),
('Yalland Warren'),
('Yallands Hill'),
('Yallop Avenue'),
('Yallop Way'),
('Yalta Close'),
('Yalts Brow'),
('Yamburg Road'),
('Yamna Field'),
('Yamson Coppice'),
('Yan Brow'),
('Yanel Lane'),
('Yanhey Copse'),
('Yanhey Hill'),
('Yanhey Moor'),
('Yanleigh Close'),
('Yanley'),
('Yanley Lane'),
('Yannon Drive'),
('Yannon Lane'),
('Yannon Terrace'),
('Yannons Court'),
('Yannons Road'),
('Yans Lane'),
('Yantlet Beach'),
('Yantlet Drive'),
('Yanwath'),
('Yanwath and Eamont Bridge'),
('Yanwath Street'),
('Yanwath Wood'),
('Yanworth'),
('Yanworth Common'),
('Yanworth Long Acre'),
('Yanworth Wood'),
('Yapham'),
('Yapham Common'),
('Yapham Road'),
('Yapham Wood'),
('Yapin Hill'),
('Yappers Wood'),
('Yapsel Bank'),
('Yapton'),
('Yapton Lane'),
('Yapton Road'),
('Yapton Street'),
('Yar Neap'),
('Yar Tor'),
('Yarberry'),
('Yarborough'),
('Yarborough Close'),
('Yarborough Crescent'),
('Yarborough Croft'),
('Yarborough Drive'),
('Yarborough Rise'),
('Yarborough Road'),
('Yarborough Terrace'),
('Yarborough Wood'),
('Yarbridge'),
('Yarbridge Close'),
('Yarbrook'),
('Yarburgh'),
('Yarburgh Close'),
('Yarburgh Grove'),
('Yarburgh Road'),
('Yarburgh Street'),
('Yarburgh Way'),
('Yarbury Combe'),
('Yarbury Way'),
('Yarcombe'),
('Yarcombe Close'),
('Yarcombe Wood'),
('Yard Close'),
('Yard Coal Rise'),
('Yard Copse'),
('Yard Court'),
('Yard Down'),
('Yard Downs Lane'),
('Yard Drove'),
('Yard Drove Withy Bed'),
('Yard Four'),
('Yard Hill'),
('Yard Lane'),
('Yard Mead'),
('Yard Road'),
('Yard Row'),
('Yard Steel'),
('Yard Wood'),
('Yard  yr  Odyn Wood'),
('Yardbury Hill Road'),
('Yarde'),
('Yarde Alders'),
('Yarde Close'),
('Yarde Copse'),
('Yarde Farm'),
('Yarde Hill Orchard'),
('Yarde Lane'),
('Yarde Mead'),
('Yarde Place'),
('Yarde Wood'),
('Yardelands'),
('Yardelands Close'),
('Yardheads'),
('Yardhope Flow'),
('Yardhurst Gardens'),
('Yardie'),
('Yardington'),
('Yardlea Close'),
('Yardlee Walk'),
('Yardley'),
('Yardley Avenue'),
('Yardley Birmingham'),
('Yardley Chase Road'),
('Yardley Close'),
('Yardley Court'),
('Yardley Drive'),
('Yardley East'),
('Yardley Fields'),
('Yardley Fields Road'),
('Yardley Gardens'),
('Yardley Gobion'),
('Yardley Green Road'),
('Yardley Grove'),
('Yardley Hall Lane'),
('Yardley Hastings'),
('Yardley Hill'),
('Yardley Lane'),
('Yardley Park Road'),
('Yardley Place'),
('Yardley Road'),
('Yardley Square'),
('Yardley Street'),
('Yardley Way'),
('Yardley West & Stechford'),
('Yardley Wood'),
('Yardley Wood Road'),
('Yardro'),
('Yards Brake'),
('Yards Hill'),
('Yards Lane'),
('Yards South Coppice'),
('Yards West Coppice'),
('Yardside Road'),
('Yardstone Knowe'),
('Yardwall Manor Farm'),
('Yardwall Road'),
('Yardworthy'),
('Yardy Close'),
('Yare and All Saints'),
('Yare Avenue'),
('Yare Close'),
('Yare Grove'),
('Yare Road'),
('Yare Street'),
('Yare Valley Drive'),
('Yare Valley Rise'),
('Yare View Close'),
('Yare Way'),
('Yarfils Wick'),
('Yarford'),
('Yarhampton'),
('Yarhampton Cross'),
('Yarker Bank Lane'),
('Yarker Lane'),
('Yarkhill'),
('Yarkhill Marsh'),
('Yarl Meadow'),
('Yarl Well'),
('Yarlands'),
('Yarlet'),
('Yarlet Croft'),
('Yarlet Hill'),
('Yarlet Lane'),
('Yarlet Wood'),
('Yarley'),
('Yarley Field Lane'),
('Yarley Hill'),
('Yarlington'),
('Yarlington Close'),
('Yarlington Mill'),
('Yarlington Orchard'),
('Yarls Wood'),
('Yarlsber'),
('Yarlsey Hill'),
('Yarlsey Moss'),
('Yarlside'),
('Yarlside Close'),
('Yarlside Crescent'),
('Yarlside Hill'),
('Yarlside Lane'),
('Yarlside Road'),
('Yarm'),
('Yarm Back Lane'),
('Yarm Close'),
('Yarm Court Road'),
('Yarm Holt'),
('Yarm Lane'),
('Yarm Place'),
('Yarm Road'),
('Yarm Street'),
('Yarm Way'),
('Yarmer Head'),
('Yarmleigh Copse'),
('Yarmleigh Lane'),
('Yarmley Lane'),
('Yarmouth'),
('Yarmouth Avenue'),
('Yarmouth Close'),
('Yarmouth Crescent'),
('Yarmouth Drive'),
('Yarmouth Ferry'),
('Yarmouth Gardens'),
('Yarmouth Green'),
('Yarmouth Harbour'),
('Yarmouth Nelson and Southtown'),
('Yarmouth North'),
('Yarmouth North and Central'),
('Yarmouth Place'),
('Yarmouth Road'),
('Yarmouth Roads'),
('Yarmouth Sand'),
('Yarmouth Street'),
('Yarmouth Way'),
('Yarmshaw'),
('Yarn Avenue'),
('Yarn Barton'),
('Yarn Close'),
('Yarn Cole'),
('Yarn Copse'),
('Yarn Croft'),
('Yarn Hill'),
('Yarn Hill Covert'),
('Yarn Lane'),
('Yarn Mill Close'),
('Yarn Street'),
('Yarn Walk'),
('Yarnacott'),
('Yarnbarton'),
('Yarnborough Hill'),
('Yarnbrook'),
('Yarnbrook Grove'),
('Yarnbrook Road'),
('Yarnbury Castle'),
('Yarnbury Close'),
('Yarncliff Close'),
('Yarncliff Wood'),
('Yarneford Copse'),
('Yarnells Hill'),
('Yarnells Road'),
('Yarner Beacon'),
('Yarner Close'),
('Yarner Wood'),
('Yarnest Wood'),
('Yarnfield'),
('Yarnfield Close'),
('Yarnfield Common Wood'),
('Yarnfield Croft'),
('Yarnfield Lane'),
('Yarnfield Parkway'),
('Yarnfield Road'),
('Yarngallows Knowe'),
('Yarngrove Wood'),
('Yarnhams Close'),
('Yarnhams Copse'),
('Yarnicombe Wood'),
('Yarningale Close'),
('Yarningale Common'),
('Yarningale Coppice'),
('Yarningale Lane'),
('Yarningale Road'),
('Yarningdale Avenue'),
('Yarninknowle Wood'),
('Yarnmakers Path'),
('Yarnold Close'),
('Yarnold Lane'),
('Yarnolds'),
('Yarns Hill'),
('Yarnscombe'),
('Yarnsdale'),
('Yarnshaw Hill'),
('Yarnside Close'),
('Yarnspath Law'),
('Yarnsworth Road'),
('Yarnton'),
('Yarnton Close'),
('Yarnton Court'),
('Yarnton Lane'),
('Yarnton Road'),
('Yarnton Way'),
('Yarpole'),
('Yarpole Lane'),
('Yarr Dale'),
('Yarr Mill Close'),
('Yarra Road'),
('Yarrangall Green'),
('Yarranton Close'),
('Yarraville Street'),
('Yarrell Croft'),
('Yarrell Mead'),
('Yarrells Close'),
('Yarrells Drive'),
('Yarrells Lane'),
('Yarrington Way'),
('Yarrow'),
('Yarrow Avenue'),
('Yarrow Close'),
('Yarrow Court'),
('Yarrow Crescent'),
('Yarrow Drive'),
('Yarrow Gardens'),
('Yarrow Gardens Lane'),
('Yarrow Gate'),
('Yarrow Grove'),
('Yarrow Hill'),
('Yarrow Mead'),
('Yarrow Park'),
('Yarrow Place'),
('Yarrow Point'),
('Yarrow Reservoir'),
('Yarrow Road'),
('Yarrow Slake'),
('Yarrow Street'),
('Yarrow Terrace'),
('Yarrow Valley Way'),
('Yarrow Walk'),
('Yarrow Way'),
('Yarrowford'),
('Yarrows Hill'),
('Yarrowside'),
('Yarsop'),
('Yartleton Lane'),
('Yartor Down'),
('Yarty'),
('Yarty Copse'),
('Yarwell'),
('Yarwell Close'),
('Yarwell Drive'),
('Yarwell Junction'),
('Yarwell Road'),
('Yarwell Square'),
('Yarwells Headland'),
('Yarwells Walk'),
('Yarwood Avenue'),
('Yarwood Close'),
('Yarwood Drive'),
('Yarwood Grove'),
('Yarwood Heath'),
('Yarwood Road'),
('Yarwood Street'),
('Yarwoodheath Covert'),
('Yarwoodheath Lane'),
('Yasmin Gardens'),
('Yate'),
('Yate and Pickup Bank'),
('Yate Central'),
('Yate Grove'),
('Yate Lane'),
('Yate North'),
('Yate Road'),
('Yate Rocks'),
('Yate Sills'),
('Yate Street'),
('Yateholm Drive'),
('Yateholme Reservoir'),
('Yatehouse Green'),
('Yatehouse Lane'),
('Yateley'),
('Yateley Avenue'),
('Yateley Close'),
('Yateley Common'),
('Yateley Crescent'),
('Yateley Drive'),
('Yateley East'),
('Yateley East & Blackwater'),
('Yateley Heath Wood'),
('Yateley Road'),
('Yateley Street'),
('Yateley West'),
('Yately Close'),
('Yates Avenue'),
('Yates Close'),
('Yates Copse'),
('Yates Court'),
('Yates Croft'),
('Yates Drive'),
('Yates Flat'),
('Yates Fold'),
('Yates Gardens'),
('Yates Grove'),
('Yates Hay Road'),
('Yates Lane'),
('Yates Meadow'),
('Yates Road'),
('Yates Street'),
('Yates Way'),
('Yates Wood'),
('Yatesbury'),
('Yatesbury Avenue'),
('Yatesbury Close'),
('Yatesbury Copse'),
('Yatesbury Crescent'),
('Yatesbury Field'),
('Yatesbury Garth'),
('Yatesbury Lane'),
('Yatesbury Road'),
('Yatesbury Withybed'),
('Yatesfield Hill'),
('Yatland Copse'),
('Yatscombe Copse'),
('Yatt Wood'),
('Yattendon'),
('Yattendon Avenue'),
('Yattendon Lane'),
('Yattendon Road'),
('Yatton'),
('Yatton Close'),
('Yatton Hall'),
('Yatton Hill'),
('Yatton Keynell'),
('Yatton Road'),
('Yatton Wood'),
('Yatts'),
('Yatts Road'),
('Yaud Sike lane'),
('Yaugher Lane'),
('Yaugher Shaw'),
('Yaugher Woods'),
('Yaul Sike Slack'),
('Yaverland'),
('Yaverland Close'),
('Yaverland Drive'),
('Yaverland Road'),
('Yaw Yeat Wood'),
('Yawl'),
('Yawl Bottom'),
('Yawl Hill'),
('Yawl Hill Lane'),
('Yawling Gate Road'),
('Yawlings Wood'),
('Yawthorpe'),
('Yawthorpe Fox Covert'),
('Yaxham'),
('Yaxham Road'),
('Yaxham Wood'),
('Yaxley'),
('Yaxley & Farcet'),
('Yaxley Close'),
('Yaxley Court'),
('Yaxley Fen'),
('Yaxley Hall Lane'),
('Yaxley Loke'),
('Yaxley Meadow'),
('Yaxley Place'),
('Yaxley Road'),
('Yaxley Way'),
('Yaxleys Lane'),
('Yazor'),
('Yazor Road'),
('Yazor Wood'),
('Ye Farre Close'),
('Ye Meads'),
('Yea Fold'),
('Yea of Migganess'),
('Yeabridge'),
('Yeabsleys Way'),
('Yeading'),
('Yeading Avenue'),
('Yeading Fork'),
('Yeading Gardens'),
('Yeading Lane'),
('Yeadon'),
('Yeadon Close'),
('Yeadon Court'),
('Yeadon Drive'),
('Yeadon Gardens'),
('Yeadon Garth'),
('Yeadon Grove'),
('Yeadon Moor'),
('Yeadon Moor Road'),
('Yeadon Road'),
('Yeadon Tarn'),
('Yeadon Walk'),
('Yeadon Way'),
('Yeager Court'),
('Yealand Avenue'),
('Yealand Close'),
('Yealand Conyers'),
('Yealand Drive'),
('Yealand Grove'),
('Yealand Redmayne'),
('Yealand Road'),
('Yealand Storrs'),
('Yeald Brow'),
('Yeald Wood'),
('Yealm Close'),
('Yealm Grove'),
('Yealm Park'),
('Yealm Pool'),
('Yealm Road'),
('Yealm Steps'),
('Yealm View Road'),
('Yealmbridge'),
('Yealmbury Hill'),
('Yealmpstone Close'),
('Yealmpstone Drive'),
('Yealmpton'),
('Yeals Combe'),
('Yealscombe Lane'),
('Yealscombe Wood'),
('Yeaman Lane'),
('Yeaman Place'),
('Yeaman Shore'),
('Yeaman Street'),
('Yeamans Alley'),
('Yeamans Lane'),
('Yeames Close'),
('Yeaps Drove'),
('Yearby'),
('Yearby Bank'),
('Yearby Close'),
('Yearby Crescent'),
('Yearby Road'),
('Yearby Wood'),
('Yeardsley Avenue'),
('Yeardsley Close'),
('Yeardsley Green'),
('Yeardsley Lane'),
('Yearl Hill'),
('Yearl Rise'),
('Yearles Wood'),
('Yearling Chase'),
('Yearling Close'),
('Yearlings Bottom'),
('Yearlings Coppice'),
('Yearlings Drove'),
('Yearlstone Square'),
('Yearly Auld Hole'),
('Yearmoor Lane'),
('Yearn Cleuch'),
('Yearn Cleugh'),
('Yearn Hope'),
('Yearngill'),
('Yearngill Head'),
('Yearning Cleuch'),
('Yearning Law'),
('Yearnor'),
('Yearnor Mill Lane'),
('Yearnor Wood'),
('Yearnslow'),
('Yearsett Coppice'),
('Yearsley'),
('Yearsley Crescent'),
('Yearsley Cross'),
('Yearsley Grove'),
('Yearsley Moor'),
('Yearsley Moor Bank'),
('Yearsleys Lane'),
('Yeat House'),
('Yeate Street'),
('Yeates Arce'),
('Yeates Close'),
('Yeates Court'),
('Yeates Drive'),
('Yeates Field View'),
('Yeates Road'),
('Yeathouse Road'),
('Yeatlands Coppice'),
('Yeatman Close'),
('Yeatman'),
('Yeatman Road'),
('Yeatmans Close'),
('Yeatmans Lane'),
('Yeatminster Road'),
('Yeaton'),
('Yeats Close'),
('Yeats Drive'),
('Yeats Road'),
('Yeats Way'),
('Yeatsall Road'),
('Yeatt Copse'),
('Yeaveley'),
('Yeavering'),
('Yeavering Bell'),
('Yeavering Close'),
('Yeckhouse Lane'),
('Yederick Road'),
('Yederick Woods'),
('Yedingham'),
('Yedman Dale'),
('Yedmandale Road'),
('Yedmandale Woods'),
('Yeend Close'),
('Yeftly Drive'),
('Yelcombe Bottom'),
('Yelcombe Drove'),
('Yeld Bank'),
('Yeld Close'),
('Yeld Hall Road'),
('Yeld Lane'),
('Yeld Road'),
('Yeld Wood'),
('Yelden'),
('Yelden Close'),
('Yelden Spinney'),
('Yelden Wold'),
('Yeldersley'),
('Yeldersley Close'),
('Yeldersley Court'),
('Yeldersley Lane'),
('Yeldham'),
('Yeldham Lock'),
('Yeldham Mews'),
('Yeldham Place'),
('Yeldham Road'),
('Yeldon Close'),
('Yeldon Court'),
('Yelds Hill'),
('Yelds Rough'),
('Yelds Wood'),
('Yeldside Gardens'),
('Yelford'),
('Yelfs Road'),
('Yell Bank'),
('Yell Dingle'),
('Yell Hill'),
('Yell Pool'),
('Yell Rough'),
('Yell Sound'),
('Yell Wood'),
('Yella Moor'),
('Yellaford Way'),
('Yelland'),
('Yelland Common Wood'),
('Yelland Coppice'),
('Yelland Copse'),
('Yelland Cross'),
('Yelland Lane'),
('Yelland Moor'),
('Yelland Road'),
('Yelland Walk'),
('Yelland Wood'),
('Yellands'),
('Yellands Moor'),
('Yellands Park'),
('Yellaton Lane'),
('Yellaton Wood'),
('Yelling'),
('Yellingmill Lane'),
('Yellison Wood'),
('Yellnowte Isle'),
('Yellow Ark'),
('Yellow Batches Drove'),
('Yellow Bog'),
('Yellow Brae'),
('Yellow Brook Close'),
('Yellow Carn'),
('Yellow Carn Porth'),
('Yellow Craig'),
('Yellow Craig Head'),
('Yellow Craigs'),
('Yellow Falls'),
('Yellow Fawns'),
('Yellow Hammer Rock'),
('Yellow Head'),
('Yellow Hill'),
('Yellow Hill Wood'),
('Yellow Horse'),
('Yellow House Lane'),
('Yellow Hundred Close'),
('Yellow Isle'),
('Yellow Lake'),
('Yellow Lane'),
('Yellow Ledge'),
('Yellow Lodge Drive'),
('Yellow Moss'),
('Yellow Muir'),
('Yellow Nose'),
('Yellow Post'),
('Yellow Quarry Wood'),
('Yellow Rabbit Hills'),
('Yellow Rock'),
('Yellow Rocks'),
('Yellow Rocks of Splears'),
('Yellow Stack'),
('Yellow Stone'),
('Yellow Top'),
('Yellow Tor Court'),
('Yellow Tor Lane'),
('Yellow Way Road'),
('Yellow Withy Bed'),
('Yellow  Wort'),
('Yellowberries Copse'),
('Yellowcar'),
('Yellowcar Hole'),
('Yellowcoat Wood'),
('Yellowcombe Lane'),
('Yellowcraig Wood'),
('Yellowcress Drive'),
('Yellowfauld Wood'),
('Yellowford'),
('Yellowgate Road'),
('Yellowham Hill'),
('Yellowham Wood'),
('Yellowhammer Close'),
('Yellowhammer Court'),
('Yellowhammer Crescent'),
('Yellowhammer Drive'),
('Yellowhammer Road'),
('Yellowhammers'),
('Yellowhill Road'),
('Yellowley Court'),
('Yellowmead Down'),
('Yellowmead Road'),
('Yellowpine Way'),
('Yellowstone Close'),
('Yellowtor Road'),
('Yells Way'),
('Yells Wood'),
('Yelmacott Moor'),
('Yelnow Lane'),
('Yelsted'),
('Yelsted Lane'),
('Yelsted Road'),
('Yelt Lane'),
('Yelting Geo'),
('Yelvertoft'),
('Yelvertoft Fieldside Covert'),
('Yelvertoft Road'),
('Yelverton'),
('Yelverton Avenue'),
('Yelverton Close'),
('Yelverton Court'),
('Yelverton Crescent'),
('Yelverton Drive'),
('Yelverton Reservoir'),
('Yelverton Road'),
('Yelverton Rural'),
('Yeman Road'),
('Yementry Court'),
('Yemscroft'),
('Yendacott Copse'),
('Yendacott Lane'),
('Yenham Lane'),
('Yennadon Down'),
('Yennastaba Dale'),
('Yennepark Copse'),
('Yenston'),
('Yenston Close'),
('Yenston Hill'),
('Yenton Close'),
('Yenton Grove'),
('Yenworthy Combe'),
('Yenworthy Common'),
('Yenworthy Wood'),
('Yeo'),
('Yeo Bank Lane'),
('Yeo Brake'),
('Yeo Close'),
('Yeo Coppice'),
('Yeo Copse'),
('Yeo Court'),
('Yeo Drive'),
('Yeo Hill'),
('Yeo Lane'),
('Yeo Mill'),
('Yeo Moor'),
('Yeo Moor Drove'),
('Yeo Park'),
('Yeo Road'),
('Yeo Street'),
('Yeo Vale'),
('Yeo Vale Road'),
('Yeo Valley'),
('Yeo Valley Way'),
('Yeo View'),
('Yeo Way'),
('Yeoford'),
('Yeoford Copse'),
('Yeoford Drive'),
('Yeoford Meadows'),
('Yeoford Way'),
('Yeol Mouth'),
('Yeoland Down'),
('Yeoland Lane'),
('Yeolands Drive'),
('Yeolands Road'),
('Yeolden Copse'),
('Yeolland Lane'),
('Yeolland Park'),
('Yeolmbridge'),
('Yeolmbridge Wood'),
('Yeolmouth Cliff'),
('Yeoman Avenue'),
('Yeoman Bank'),
('Yeoman Close'),
('Yeoman Cottages'),
('Yeoman Court'),
('Yeoman Crescent'),
('Yeoman Drive'),
('Yeoman Fold'),
('Yeoman Gardens'),
('Yeoman Gate'),
('Yeoman Hey Reservoir'),
('Yeoman Hill'),
('Yeoman Lane'),
('Yeoman Meadow'),
('Yeoman Park'),
('Yeoman Place'),
('Yeoman Road'),
('Yeoman Street'),
('Yeoman Terrace'),
('Yeoman Way'),
('Yeomanry Close'),
('Yeomanry Court'),
('Yeomanry Drive'),
('Yeomanry Place'),
('Yeomanry Road'),
('Yeomanry Walk'),
('Yeomanry Way'),
('Yeomans'),
('Yeomans Acre'),
('Yeomans Avenue'),
('Yeomans Close'),
('Yeomans Court'),
('Yeomans Dale'),
('Yeomans Drive'),
('Yeomans Field'),
('Yeomans Gate'),
('Yeomans Lane'),
('Yeomans Lodge'),
('Yeomans Meadows'),
('Yeomans Mount'),
('Yeomans Orchard'),
('Yeomans Place'),
('Yeomans Ride'),
('Yeomans Road'),
('Yeomans Row'),
('Yeomans Square'),
('Yeomans Way'),
('Yeomans Yard'),
('Yeomanside Close'),
('Yeomead'),
('Yeomeads'),
('Yeomen Way'),
('Yeorton Brow'),
('Yeory Wood'),
('Yeotown Wood'),
('Yeoveney Close'),
('Yeovil'),
('Yeovil Central'),
('Yeovil Chase'),
('Yeovil Close'),
('Yeovil District'),
('Yeovil Junction'),
('Yeovil Marsh'),
('Yeovil Pen Mill'),
('Yeovil Place'),
('Yeovil Road'),
('Yeovil Rock'),
('Yeovil Street'),
('Yeovil Westland Airfield'),
('Yeovil Without'),
('Yeovilton'),
('Yeovilton Close'),
('Yeovilton Place'),
('Yeovilton Royal Naval Air'),
('Yeoward Road'),
('Yeowood'),
('Yerbeston'),
('Yerburgh Avenue'),
('Yerburgh Road'),
('Yerburgh Street'),
('Yerbury Grove'),
('Yerbury Road'),
('Yerbury Street'),
('Yerdley Coppice'),
('Yerley Hill'),
('Yerris Road'),
('Yerton Brae'),
('Yerville Gardens'),
('Yes Tor'),
('Yesmere'),
('Yesnaby'),
('Yesnaby Road'),
('Yessell Lane'),
('Yessness'),
('Yester'),
('Yester Drive'),
('Yester Park'),
('Yester Place'),
('Yester Road'),
('Yet Mead Lane'),
('Yetchleys Coppice'),
('Yetholm'),
('Yetholm Avenue'),
('Yetholm Gardens'),
('Yetholm Law'),
('Yetholm Loch'),
('Yetholm Park'),
('Yetholm Place'),
('Yetholm Road'),
('Yetholm Street'),
('Yetholm Terrace'),
('Yetholm Way'),
('Yethouse Hill'),
('Yetlands'),
('Yetlington'),
('Yetlington Drive'),
('Yetmans Copse'),
('Yetminster'),
('Yetminster & Cam Vale'),
('Yetminster Road'),
('Yett Hill'),
('Yett Road'),
('Yettan Terrace'),
('Yettington'),
('Yettington Road'),
('Yettna Geo'),
('Yetts Avenue'),
('Yetts Crescent'),
('Yetts Hole Road'),
('Yetts o Muckhart'),
('Yevele Close'),
('Yevele Way'),
('Yew Avenue'),
('Yew Band'),
('Yew Bank'),
('Yew Bank Road'),
('Yew Barrow'),
('Yew Barrow Breast'),
('Yew Barrow Close'),
('Yew Barrow Wood'),
('Yew Cleugh'),
('Yew Cliff Coppice'),
('Yew Close'),
('Yew Clump'),
('Yew Corner'),
('Yew Court'),
('Yew Covert'),
('Yew Crescent'),
('Yew Croft Avenue'),
('Yew Dale Gardens'),
('Yew Down'),
('Yew Drive'),
('Yew Gardens'),
('Yew Gate'),
('Yew Greave Crescent'),
('Yew Green'),
('Yew Green Avenue'),
('Yew Green Road'),
('Yew Grove'),
('Yew Hill'),
('Yew Lane'),
('Yew Oval'),
('Yew Pike Moss'),
('Yew Place'),
('Yew Redding'),
('Yew Ring'),
('Yew Road'),
('Yew Scar Force'),
('Yew Street'),
('Yew Terrace'),
('Yew Tree'),
('Yew Tree Avenue'),
('Yew Tree Bank'),
('Yew Tree Bottom Road'),
('Yew Tree Close'),
('Yew Tree Close Covert'),
('Yew Tree Copse'),
('Yew Tree Corner'),
('Yew Tree Court'),
('Yew Tree Courtyard'),
('Yew Tree Covert'),
('Yew Tree Crescent'),
('Yew Tree Dingle'),
('Yew Tree Drive'),
('Yew Tree Farm'),
('Yew Tree Gardens'),
('Yew Tree Gorge'),
('Yew Tree Green'),
('Yew Tree Green Road'),
('Yew Tree Grounds'),
('Yew Tree Grove'),
('Yew Tree Hangings'),
('Yew Tree Heath'),
('Yew Tree Hill'),
('Yew Tree Hills'),
('Yew Tree Hollow'),
('Yew Tree Lane'),
('Yew Tree Meadow'),
('Yew Tree Mews'),
('Yew Tree Moor'),
('Yew Tree Park'),
('Yew Tree Park Road'),
('Yew Tree Place'),
('Yew Tree Rein'),
('Yew Tree Rise'),
('Yew Tree Road'),
('Yew Tree Shaw'),
('Yew Tree Spinney'),
('Yew Tree Square'),
('Yew Tree Stables'),
('Yew Tree Street'),
('Yew Tree Tarn'),
('Yew Tree Terrace'),
('Yew Tree Walk'),
('Yew Tree Way'),
('Yew Tree Wood'),
('Yew Trees'),
('Yew Trees Avenue'),
('Yew Trees Croft'),
('Yew Trees Wood'),
('Yew Walk'),
('Yew Way'),
('Yew Wood'),
('Yewbank Avenue'),
('Yewbank Close'),
('Yewbank Lane'),
('Yewbank Terrace'),
('Yewbarrow'),
('Yewbarrow Close'),
('Yewbarrow Road'),
('Yewbarrow Wood'),
('Yewberry Close'),
('Yewberry Coppice'),
('Yewberry Lane'),
('Yewberry Way'),
('Yewburn Way'),
('Yewcroft'),
('Yewcroft Avenue'),
('Yewcroft Close'),
('Yewdale'),
('Yewdale Avenue'),
('Yewdale Close'),
('Yewdale Crag Moss'),
('Yewdale Crescent'),
('Yewdale Drive'),
('Yewdale Fell Side'),
('Yewdale Fells'),
('Yewdale Gardens'),
('Yewdale Grove'),
('Yewdale Moss'),
('Yewdale Park'),
('Yewdale Road'),
('Yewdall Road'),
('Yewdall Way'),
('Yewens'),
('Yewens Hanger'),
('Yewfield Road'),
('Yewhedges'),
('Yewhow Wood'),
('Yewhurst Close'),
('Yewhurst Road'),
('Yewlands'),
('Yewlands Avenue'),
('Yewlands Close'),
('Yewlands Crescent'),
('Yewlands Drive'),
('Yewlands Gardens'),
('Yewleigh Lane'),
('Yews Avenue'),
('Yews Close'),
('Yews Crescent'),
('Yews Drive'),
('Yews Green'),
('Yews Hill'),
('Yews Hill Road'),
('Yews Lane'),
('Yews Mount'),
('Yews Place'),
('Yewside'),
('Yewstock'),
('Yewstock Crescent West'),
('Yewthwaite Comb'),
('Yewtree Avenue'),
('Yewtree Bank'),
('Yewtree Batch'),
('Yewtree Bottom'),
('Yewtree Close'),
('Yewtree Coppice'),
('Yewtree Copse'),
('Yewtree Court'),
('Yewtree Crescent'),
('Yewtree Dingle'),
('Yewtree Drive'),
('Yewtree End'),
('Yewtree Gardens'),
('Yewtree Gate'),
('Yewtree Green'),
('Yewtree Grove'),
('Yewtree Hanger'),
('Yewtree Hassock'),
('Yewtree Hill'),
('Yewtree Hill Brake'),
('Yewtree Holms'),
('Yewtree Lane'),
('Yewtree Mews'),
('Yewtree Nob'),
('Yewtree Pit Covert'),
('Yewtree Rise'),
('Yewtree Road'),
('Yewtree Row'),
('Yewtree Shaw'),
('Yewtree Spinney'),
('Yewtree Spring'),
('Yewtree Toll'),
('Yewtree Wood'),
('Yewtreebrake Inclosure'),
('Yewtrees'),
('Yewtrees Lane'),
('Yewvale Road'),
('Ygerddi'),
('Yield Brae'),
('Yield Hall Lane'),
('Yield Hall Place'),
('Yielding Copse'),
('Yielding Tree'),
('Yieldings Close'),
('Yieldingtree'),
('Yieldshields'),
('Yieldshields Road'),
('Yiewsley'),
('Yiewsley Close'),
('Yiewsley Crescent'),
('Yiewsley Drive'),
('Yinstay'),
('Yinstay Head'),
('Yinstay Road'),
('Yllaethdy'),
('Ymyl yr Afon'),
('Ymyl  Yr  Afon'),
('Yniscedwyn Road'),
('Ynisderw Road'),
('Ynisydarren Road'),
('Ynys'),
('Ynys Amlwch'),
('Ynys Arw'),
('Ynys Bach'),
('Ynys Badrig'),
('Ynys Benlas'),
('Ynys Berchen'),
('Ynys Bery'),
('Ynys Bery Close'),
('Ynys Byr'),
('Ynys Bâch'),
('Ynys Cadwyn'),
('Ynys Cantwr'),
('Ynys Castell'),
('Ynys Close'),
('Ynys Creua'),
('Ynys Cyngar'),
('Ynys Dawel'),
('Ynys Ddu'),
('Ynys Defaid'),
('Ynys Deullyn'),
('Ynys Dinas'),
('Ynys Dol  lleian'),
('Ynys Dol  rhedyn'),
('Ynys Drai'),
('Ynys Dulas'),
('Ynys Eilun'),
('Ynys Enlli'),
('Ynys Fach'),
('Ynys Fach Avenue'),
('Ynys Faelog'),
('Ynys Fawr'),
('Ynys Fawr Avenue'),
('Ynys Feirig'),
('Ynys Fer  Lâs'),
('Ynys Feurig'),
('Ynys Fâch'),
('Ynys Gaint'),
('Ynys Galch'),
('Ynys Gifftan'),
('Ynys Glyd Street'),
('Ynys Goediog'),
('Ynys Gored Goch'),
('Ynys Groes'),
('Ynys Gron'),
('Ynys Gwair'),
('Ynys Gwelltog'),
('Ynys Gwylan  bâch'),
('Ynys Gwylan  fawr'),
('Ynys Gwyndwn  mawr'),
('Ynys Gybi'),
('Ynys Halen'),
('Ynys Hir'),
('Ynys Hwrddod'),
('Ynys Isaf'),
('Ynys Lane'),
('Ynys Las'),
('Ynys Lawd'),
('Ynys Leurad'),
('Ynys Llanddwyn'),
('Ynys Llanfihangel  y  traethau'),
('Ynys Lochtyn'),
('Ynys Lom'),
('Ynys Meibion'),
('Ynys Meicel'),
('Ynys Melyn'),
('Ynys Moelfre'),
('Ynys Mon'),
('Ynys Môn'),
('Ynys Nedd'),
('Ynys Newydd Road'),
('Ynys Onnen'),
('Ynys Peibio'),
('Ynys Piod'),
('Ynys Seiriol'),
('Ynys Sili'),
('Ynys Street'),
('Ynys Sych'),
('Ynys Terrace'),
('Ynys Thomas  Howel'),
('Ynys Tobig'),
('Ynys Traws'),
('Ynys Tysilio'),
('Ynys Tywyn'),
('Ynys Wall'),
('Ynys Wellt'),
('Ynys Welltog'),
('Ynys y Big'),
('Ynys y Brawd'),
('Ynys y Carcharorion'),
('Ynys y Castell'),
('Ynys y Clochydd'),
('Ynys Y Coed'),
('Ynys Y Cwm Road'),
('Ynys y Ddinas'),
('Ynys y Fydlyn'),
('Ynys Y Gored'),
('Ynys y Mochyn'),
('Ynys Y Nos'),
('Ynys Y Wern'),
('Ynys yr Adar'),
('Ynys yr Wyn'),
('Ynys  ddu'),
('Ynys  fach'),
('Ynys  Forgan'),
('Ynys  Gyfeillon Road'),
('Ynys  hafren'),
('Ynys  hir'),
('Ynys  Isaf'),
('Ynys  las'),
('Ynys  Lee'),
('Ynys  Lwyd Road'),
('Ynys  Lwyd Street'),
('Ynys  Meudwy Road'),
('Ynys  Mòn'),
('Ynys  Penllwch Road'),
('Ynys  Tawe'),
('Ynys  uchaf'),
('Ynys  wen'),
('Ynys  Wil  hernyn Wood'),
('Ynys  y  bwl'),
('Ynys  y  bwl a Choed  y  cwm'),
('Ynys  Y  Coed'),
('Ynys  y  cranc'),
('Ynys  Y  Mond Road'),
('Ynys  y  mond Uchaf'),
('Ynys  y  pica Wood'),
('Ynys  Yr  Afon'),
('Ynysallan Road'),
('Ynysangharad'),
('Ynysangharad Road'),
('Ynysarwed'),
('Ynysawdre'),
('Ynysboeth'),
('Ynysbryn Close'),
('Ynyscedwyn'),
('Ynyscorrwg Road'),
('Ynyscynon Road'),
('Ynyscynon Street'),
('Ynysddu'),
('Ynysddu Hotel Approach'),
('Ynysderw Park Road'),
('Ynysfach'),
('Ynysfeio Avenue'),
('Ynysforgan'),
('Ynysfro Reservoirs'),
('Ynysgau Street'),
('Ynysgedwyn'),
('Ynyshir'),
('Ynyshir Road'),
('Ynyslas'),
('Ynyslas Crescent'),
('Ynyslyn Road'),
('Ynysmaerdy'),
('Ynysmaerdy Terrace'),
('Ynysmeudwy'),
('Ynysmeurig Road'),
('Ynysoedd Duon'),
('Ynysoedd Gwylanod'),
('Ynysoedd y Ffrydiau'),
('Ynysoedd y Moelrhoniaid'),
('Ynysowen'),
('Ynysowen Fach'),
('Ynyspenllwch'),
('Ynystawe'),
('Ynysteg'),
('Ynyswen'),
('Ynyswen Road'),
('Ynyswerdd'),
('Ynysybwl'),
('Ynysybwl and Coed  y  Cwm'),
('Ynysybwl Road'),
('Ynysydarren'),
('Ynysygerwn Avenue'),
('Ynysygerwn Crescent'),
('Ynysygored Road'),
('Ynysygwas'),
('Ynysygwas Hill'),
('Ynysymaerdy'),
('Ynysymaerdy Road'),
('Yoadcastle'),
('Yoadcomb Hill'),
('Yoadwath Bank'),
('Yoags Haven'),
('Yoakes Lane'),
('Yoakley Road'),
('Yoakley Square'),
('Yock Lane'),
('Yockenthwaite'),
('Yockenthwaite Moor'),
('Yockleton'),
('Yockleton Road'),
('Yockletts Banks'),
('Yockley Close'),
('Yockley Wood'),
('Yockney Close'),
('Yoden Court'),
('Yoden Road'),
('Yoden Way'),
('Yoells Copse'),
('Yoells Crescent'),
('Yoells Lane'),
('Yoesden Wood'),
('Yoga Way'),
('Yogli Geo'),
('Yohden Hall'),
('Yoke'),
('Yoke Close'),
('Yoke Hill'),
('Yoke Knowes'),
('Yoke Wood'),
('Yokecliffe Avenue'),
('Yokecliffe Crescent'),
('Yokecliffe Drive'),
('Yokecliffe Hill'),
('Yokecliffe Lane'),
('Yokecliffe Wood'),
('Yokefleet'),
('Yokefleet Clough'),
('Yokehouse Lane'),
('Yokeing Close Wood'),
('Yoker'),
('Yoker Ferry Road'),
('Yoker Mill Gardens'),
('Yoker Mill Road'),
('Yokerburn Place'),
('Yokerburn Terrace'),
('Yokesford Hill'),
('Yokine Gardens'),
('Yokosuka Way'),
('Yolande Gardens'),
('Yolhey Lane'),
('Yolk Meadow'),
('Yollacombe'),
('Yolland Close'),
('Yolland Hill'),
('Yolsham Green'),
('Yolsham Hill'),
('Yolsum Close'),
('Yomede Park'),
('Yon Street'),
('Yonder'),
('Yonder Acre Way'),
('Yonder Brake'),
('Yonder Close'),
('Yonder Coppice'),
('Yonder Cross Close Copse'),
('Yonder Drove'),
('Yonder Hare Down'),
('Yonder Horse Park Copse'),
('Yonder Mead'),
('Yonder Meadow'),
('Yonder Moor'),
('Yonder Mount'),
('Yonder Slade'),
('Yonder Street'),
('Yonder Way'),
('Yonder Wyke Moor Copse'),
('Yonderberry Point'),
('Yondercott'),
('Yonderdown Wood'),
('Yonderton Place'),
('Yondertown'),
('Yondover'),
('Yondover Mill'),
('Yonge Close'),
('Yonge Park'),
('Yons Hill'),
('Yons Nab'),
('Yont the Cleugh'),
('Yopps Green'),
('Yorath Road'),
('Yorburgh'),
('Yordas Court'),
('Yordas Wood'),
('Yore Mill'),
('Yoredale Avenue'),
('Yoredale Close'),
('Yoredale Drive'),
('Yoreham Close'),
('Yorfalls Wood'),
('Yorick Avenue'),
('Yorick Road'),
('York'),
('York Alley'),
('York And Albany Close'),
('York Avenue'),
('York Bridge'),
('York Bridge Road'),
('York Buildings'),
('York Central'),
('York Chase'),
('York Close'),
('York Cottages'),
('York Court'),
('York Crescent'),
('York Dale'),
('York Day'),
('York Drive'),
('York Drove'),
('York Fields'),
('York Gardens'),
('York Garth'),
('York Gate'),
('York Gate Lane'),
('York Grove'),
('York Hill'),
('York Hill Crescent'),
('York Hill Road'),
('York Hospital Nuffield Health'),
('York House Place'),
('York House Road'),
('York Lane'),
('York Mews'),
('York Outer'),
('York Paddock'),
('York Parade'),
('York Place'),
('York Place Lane'),
('York Ride'),
('York Rise'),
('York Road'),
('York Row'),
('York Square'),
('York St John'),
('York Street'),
('York Street Building'),
('York Street'),
('York Street Lane'),
('York Teaching'),
('York Terrace'),
('York Terrace East'),
('York Terrace Lane'),
('York Terrace West'),
('York Town'),
('York View'),
('York Villa Close'),
('York Villas'),
('York Walk'),
('York Way'),
('York Way Court'),
('York Way Field'),
('York Wood'),
('Yorkaster Road'),
('Yorkbrooke Drive'),
('Yorkdale'),
('Yorkdale Close'),
('Yorkdale Court'),
('Yorkdale Drive'),
('Yorkdale Place'),
('Yorkdale Road'),
('Yorke Avenue'),
('Yorke Close'),
('Yorke Drive'),
('Yorke Gardens'),
('Yorke Gate'),
('Yorke Place'),
('Yorke Rise'),
('Yorke Road'),
('Yorke Rock'),
('Yorke Street'),
('Yorke Way'),
('Yorkersgate'),
('Yorkes Dingles'),
('Yorkfield Lane'),
('Yorkhill'),
('Yorkhill Parade'),
('Yorkhill Street'),
('Yorkhurst Hill'),
('Yorkland Avenue'),
('Yorklands'),
('Yorklea Croft'),
('Yorklets'),
('Yorkletts'),
('Yorkley'),
('Yorkley Lane'),
('Yorkley Road'),
('Yorkley Slade'),
('Yorkley Wood'),
('Yorkley Wood Road'),
('Yorkminster Drive'),
('Yorks Hill'),
('Yorks Lane'),
('Yorks Wood'),
('Yorks Wood Drive'),
('Yorksand Road'),
('Yorkshire'),
('Yorkshire and The Humber'),
('Yorkshire Close'),
('Yorkshire Dales National Park'),
('Yorkshire Drive'),
('Yorkshire Gardens'),
('Yorkshire Grove'),
('Yorkshire Place'),
('Yorkshire Road'),
('Yorkshire Shaw'),
('Yorkshire Street'),
('Yorkshire Street East'),
('Yorkshire Street West'),
('Yorkshire Way'),
('Yorkshire Wolds'),
('Yorkshireside'),
('Yorkston Moss'),
('Yorkstone'),
('Yorkstone Close'),
('Yorkswood Road'),
('Yorkton Street'),
('Yorktown Close'),
('Yorktown Road'),
('Yorkway'),
('Yorkwood'),
('Yorney Wood'),
('Yorstans Geo'),
('Yorton'),
('Yorton Heath'),
('Yosemite Park'),
('Yosgill Wood'),
('Yottenfews'),
('Youatt Avenue'),
('Youchtrie Heugh'),
('Youd Street'),
('Youell Avenue'),
('Youens Crescent'),
('Youens Drive'),
('Youens Road'),
('Youens Way'),
('Youghal Close'),
('Youings Drive'),
('Youlbury Pool'),
('Youlbury Wood'),
('Youlden Close'),
('Youlden Drive'),
('Youlden Lane'),
('Youlden'),
('Youlden Wood'),
('Youldholes Lane'),
('Youldon Way'),
('Youldon Wood'),
('Youldons Close'),
('Youlgrave'),
('Youlgrave Avenue'),
('Youlgreave'),
('Youlgreave Avenue'),
('Youlgreave Close'),
('Youlgreave Crescent'),
('Youlgreave Drive'),
('Youlieburn'),
('Youll Close'),
('Youlston Close'),
('Youlston Park'),
('Youlston Wood'),
('Youlstone'),
('Youlthorpe'),
('Youlthorpe Pasture Hill'),
('Youlton'),
('Youlton Moor'),
('Young Avenue'),
('Young Bank Lane'),
('Young Bog Wood'),
('Young Bush Wood'),
('Young Close'),
('Young Contract Wood'),
('Young Coombe'),
('Young Coppice'),
('Young Copse'),
('Young Court'),
('Young Covert'),
('Young Crescent'),
('Young Croft Brake'),
('Young Drive'),
('Young Hill'),
('Young Jeanies Wood'),
('Young Kings Wood'),
('Young Ladys Wood'),
('Young Lane'),
('Young Marys Grove'),
('Young Oaks'),
('Young Oaks Wood'),
('Young Place'),
('Young Road'),
('Young Salamanca Covert'),
('Young Spinney'),
('Young Spring Wood'),
('Young Square'),
('Young Street'),
('Young Street North Lane'),
('Young Street South Lane'),
('Young Terrace'),
('Young Trees'),
('Young Wood'),
('Young Wynd'),
('Youngaton Road'),
('Youngcross Grounds'),
('Younger Drive'),
('Younger Gardens'),
('Younger Place'),
('Younger Quadrant'),
('Younger Street'),
('Youngers Lane'),
('Youngers Terrace'),
('Youngfield Road'),
('Younghall Close'),
('Younghayes Road'),
('Younghurst Wood'),
('Younghusband Wood'),
('Youngman Avenue'),
('Youngman Close'),
('Youngman Place'),
('Youngmans Close'),
('Youngmans Lane'),
('Youngmans Road'),
('Youngoak Covert'),
('Youngs Avenue'),
('Youngs Close'),
('Youngs Copse'),
('Youngs Court'),
('Youngs Crescent'),
('Youngs Drive'),
('Youngs End'),
('Youngs Grove'),
('Youngs Hill'),
('Youngs Knowe'),
('Youngs Lane'),
('Youngs Mews'),
('Youngs Orchard'),
('Youngs Paddock'),
('Youngs Park Lane'),
('Youngs Park Road'),
('Youngs Place'),
('Youngs Rise'),
('Youngs Road'),
('Youngs Row'),
('Youngs Way'),
('Youngs Wood'),
('Youngs Yard'),
('Youngsbury'),
('Youngsbury Lane'),
('Youngsdale Place'),
('Youngsmere Close'),
('Youngsons Lane'),
('Youngstroat Lane'),
('Youngwood Lane'),
('Youngwoods Copse'),
('Youngwoods Way'),
('Youth Close'),
('Youth Wood'),
('Yowlass Wood'),
('Yowley Road'),
('Yoxall'),
('Yoxall Avenue'),
('Yoxall Drive'),
('Yoxall Grove'),
('Yoxall Park'),
('Yoxall Road'),
('Yoxall Way'),
('Yoxford'),
('Yoxford Little Street'),
('Yoxford Mews'),
('Yoxford Road'),
('Yoxford Wood'),
('Yoxhall Drive'),
('Yoxhall Meadow Woods'),
('Yoxie Geo'),
('Yoxley Approach'),
('Yoxley Drive'),
('Yoxwood View'),
('Ypres Close'),
('Ypres Court'),
('Ypres Drive'),
('Ypres Place'),
('Ypres Road'),
('Ypres Way'),
('Yr Aber'),
('Yr Aes'),
('Yr Ala'),
('Yr Allt'),
('Yr Allt Boeth'),
('Yr Allt Gethin'),
('Yr Angorfa'),
('Yr Aran'),
('Yr Ardd Fawr'),
('Yr Arddu'),
('Yr Arwydd'),
('Yr As Fach'),
('Yr As Fawr'),
('Yr Ebolion'),
('Yr Efail'),
('Yr Eglwys Newydd'),
('Yr Eglwys Newydd a Thongwynlais'),
('Yr Eifl'),
('Yr Elain'),
('Yr Elen'),
('Yr Encil'),
('Yr Encilfa'),
('Yr Erw'),
('Yr Esgair'),
('Yr Hafan'),
('Yr Hafanau'),
('Yr Hafn'),
('Yr Hafod'),
('Yr Harbwr'),
('Yr Havens'),
('Yr Helfa'),
('Yr Helyg'),
('Yr Hen Berlan'),
('Yr Hen Berllan'),
('Yr Hen Draeth Ymdrochi'),
('Yr Hen Erddi'),
('Yr Hen Gorlan'),
('Yr Hen Heol'),
('Yr Hen Laethdy'),
('Yr Hen Ysgol'),
('Yr Hen  ffordd'),
('Yr Hendre'),
('Yr Hendy'),
('Yr Hirgylch'),
('Yr Hob'),
('Yr Hobin Cast'),
('Yr Hwylfa'),
('Yr Hòb'),
('Yr Hôb'),
('Yr Ochr'),
('Yr Oerfa'),
('Yr Ogof'),
('Yr Orsedd'),
('Yr Rhos'),
('Yr Wyddfa'),
('Yr Wyddgrug'),
('Yr Wylorn'),
('Yr Ydlan'),
('Yr Ynys'),
('Yr Ysfa'),
('Yr Ysgol John Frost'),
('Yr Ystog'),
('Yr Ystrad'),
('Yr  allt Wood'),
('Yr  efail Covert'),
('Yr  Hen  Lawnt'),
('Ysbryd  Y  Coed'),
('Ysbty Aneurin Bevan'),
('Ysbutyr Santes Tudful'),
('Ysbytr tri Chwm'),
('Ysbytty Reservoir'),
('Ysbyty Alltwen'),
('Ysbyty Athrofaol Cymru'),
('Ysbyty Athrofaol Llandochau'),
('Ysbyty Brenhinol Gwent'),
('Ysbyty Bryn Beryl'),
('Ysbyty Castell Nedd Port Talbot'),
('Ysbyty Coffa Sir Frycheiniog'),
('Ysbyty Coffa Victoria Y Trallwng'),
('Ysbyty Cwm Cynon'),
('Ysbyty Cyffredinol Llwynhelyg'),
('Ysbyty Cymuned Glannau Dyfrdwy'),
('Ysbyty Cymunedol Y Waun'),
('Ysbyty Cymunedol Yr Wyddgrug'),
('Ysbyty Cynfyn'),
('Ysbyty Dewi Sant'),
('Ysbyty Dolgellau Y Bermo Ar Cylch'),
('Ysbyty Eglwys Newydd'),
('Ysbyty Eryri'),
('Ysbyty Frenhinol Morgannwg'),
('Ysbyty Garngoch'),
('Ysbyty Glan Clwyd'),
('Ysbyty Gwynedd Gwynedd'),
('Ysbyty Gymuned Bro Ddyfi'),
('Ysbyty Ifan'),
('Ysbyty Llandudno'),
('Ysbyty Llanymddfri'),
('Ysbyty Maelor Wrecsam'),
('Ysbyty Neuadd Nevill'),
('Ysbyty Penrhos Stanley'),
('Ysbyty Sir Drefaldwyn'),
('Ysbyty Treforys'),
('Ysbyty Twysog Siarl'),
('Ysbyty Tywysoges Cymru'),
('Ysbyty Ystrad Fawr'),
('Ysbyty Ystwyth'),
('Ysceifiog'),
('Ysceifiog Lake'),
('Yscir'),
('Ysgafell Wen'),
('Ysgeifiog'),
('Ysgeifiog Moor'),
('Ysgir'),
('Ysgol'),
('Ysgoldy Covert'),
('Ysgoldy Hill'),
('Ysgool Gynradd Llandochau'),
('Ysgubor'),
('Ysgubor Abad'),
('Ysgubor Fach'),
('Ysgubor Fach Street'),
('Ysgubor Mountain'),
('Ysgubor Newydd'),
('Ysgubor Newydd Lane'),
('Ysgubor  Fawr'),
('Ysgubor  wen Wood'),
('Ysgubor  y  Coed'),
('Ysguboriaur Bugail'),
('Ysguborwen'),
('Ysguborwen Road'),
('Ysguthan Road'),
('Ysgwd Ffordd'),
('Ysgwd  Ffordd'),
('Ysgyryd Fach'),
('Ysgyryd Fawr'),
('YsgÃ¯og Wood'),
('Yspitty'),
('Yspitty Road'),
('Yspytty Road'),
('Yspytty  Cynfyn'),
('Yspyty Cwm Rhondda'),
('Ystablaur Ysgol'),
('Ystad Bryn Y Ffermwyr'),
('Ystad Cae Bach'),
('Ystad Celyn'),
('Ystad Coed Madog'),
('Ystad Cwm Taf'),
('Ystad Ddiwydiannol Y Glyn'),
('Ystad Deri'),
('Ystad Fferm Y Berllan'),
('Ystad Glorian'),
('Ystad Gwylfa'),
('Ystad Llwyn Bedw'),
('Ystad Mur Poeth'),
('Ystad Tyn Berllan'),
('Ystafelloedd'),
('Ystalyfera'),
('Ysticl  Garu'),
('Ysticlau Road'),
('Ystrad'),
('Ystrad Aeron'),
('Ystrad Barwig'),
('Ystrad Close'),
('Ystrad Drive'),
('Ystrad Einion'),
('Ystrad Einon'),
('Ystrad Fawr'),
('Ystrad Fflur'),
('Ystrad Hir'),
('Ystrad Meurig'),
('Ystrad Mynach'),
('Ystrad Rhondda'),
('Ystrad Road'),
('Ystrad Street'),
('Ystrad Terrace'),
('Ystrad Wood'),
('Ystrad  Einion'),
('Ystrad  Fawr Villas'),
('Ystrad  gwyn'),
('Ystradbarwig Terrace'),
('Ystradfellte'),
('Ystradfellte Reservoir'),
('Ystradgynlais'),
('Ystradgynlais Community'),
('Ystradmeurig'),
('Ystradowen'),
('Ystrodir Wood'),
('Ystryd Ddu'),
('Ystryd Faen'),
('Ystryd Fawr'),
('Ystryd Y Ceunant'),
('Ystum Taf'),
('Ystumllwynarth'),
('Ystumtuen'),
('Ystwyth'),
('Ystwyth Place'),
('Ystâd  Y  Gotrel'),
('Ythan Place'),
('Ythan Road'),
('Ythan Terrace'),
('Ythanbank'),
('Ythanwells'),
('Ythsie'),
('Ytymbl'),
('Yuill Avenue'),
('Yukon Gardens'),
('Yukon Road'),
('Yukon Terrace'),
('Yukon Way'),
('Yulan Drive'),
('Yule Close'),
('Yule Hill'),
('Yule Lane'),
('Yule Place'),
('Yule Road'),
('Yule Square'),
('Yule Street'),
('Yule Terrace'),
('Yule Way'),
('Yule Wood'),
('Yumfrau Taing'),
('Yungnapool'),
('Yuntaskeos'),
('Yunus Khan Close'),
('Yves Mews'),
('Yvetot Avenue'),
('Yvetot Court'),
('Yvonne Close'),
('Yvonne Crescent'),
('Yvonne Grove'),
('Yvonne Road'),
('Ywen Wood'),
('Yachiyo'),
('Yaizu'),
('Yakeshi'),
('Yakutsk'),
('Yalova'),
('Yamagata'),
('Yamaguchi'),
('Yamato'),
('Yamoussoukro'),
('Yamuna Nagar'),
('Yanan'),
('Yanbu'),
('Yancheng'),
('Yangjiang'),
('Yangon'),
('Yangquan'),
('Yangzhou'),
('Yanji'),
('Yantai'),
('Yao'),
('Yaoundé'),
('Yaroslavl'),
('Yasuj'),
('Yatsushiro'),
('Yavatmal'),
('Yazd'),
('Yekaterinburg'),
('Yelets'),
('Yenakiieve'),
('Yeosu'),
('Yerevan'),
('Yessentuki'),
('Yevpatoria'),
('Yibin'),
('Yichang'),
('Yichun'),
('Yidu'),
('Yima'),
('Yinchuan'),
('Yingcheng'),
('Yingkou'),
('Yingtan'),
('Yining'),
('Yiwu'),
('Yixing'),
('Yiyang'),
('Yizheng'),
('Yogyakarta'),
('Yokkaichi'),
('Yokohama'),
('Yokosuka'),
('Yonago'),
('Yongan'),
('Yongzhou'),
('Yonkers'),
('Yopal'),
('Yoshkar  Ola'),
('Yuanjiang'),
('Yueyang'),
('Yulin'),
('Yumen'),
('Yuncheng'),
('Yusufiyah'),
('Yuxi'),
('Yuyao'),
('Yuzhno  Sakhalinsk'),
('Yuzhou'),
('Yannons'),
('Yarde'),
('Yarlet'),
('Yateley Lakes'),
('Yaud'),
('Yei'),
('Yeld'),
('Yellow Man'),
('Yeolands'),
('Yeomans'),
('Yett'),
('Yetts'),
('Yew Trees'),
('Yew Walk'),
('Yews'),
('Yonne'),
('York District'),
('Young Covert');
-- Down
DELETE FROM "Placename" WHERE "keyword" LIKE 'y%';