-- Up
 INSERT INTO Placename (keyword)
VALUES
('Y Bae'),
('Y Bala'),
('Y Barri'),
('Y Beddau'),
('Y Berllan'),
('Y Blaenau'),
('Y Bonc'),
('Y Bont'),
('Y Bont Hir'),
('Y Bont Faen'),
('Y Bont faen a Llanfleiddan'),
('Y Borth'),
('Y Bracty'),
('Y Brif Heol'),
('Y Bryn'),
('Y Bwlfar'),
('Y Bwthyn'),
('Y Bwthyn The Cottage'),
('Y Castellnewydd'),
('Y Cedrwydd'),
('Y Cedrwydden'),
('Y Ceffyl'),
('Y Ceunant'),
('Y Cilffordd'),
('Y Cilgant'),
('Y Clas ar Wy'),
('Y Clawdd'),
('Y Clawstrau'),
('Y Clogwyn'),
('Y Clos'),
('Y Clun a Melin cwrt'),
('Y Cocyd'),
('Y Coed'),
('Y Coed Duon'),
('Y Coleg Merthyr Tudful'),
('Y Copi'),
('Y Corsydd'),
('Y Creunant'),
('Y Crochan'),
('Y Crofft'),
('Y Crwys'),
('Y Cwcwll'),
('Y Cwm'),
('Y Cymer'),
('Y Cyswllt'),
('Y Darren'),
('Y Das'),
('Y Dderwen'),
('Y Dderwen Deg'),
('Y Ddol'),
('Y Ddol Fach'),
('y Ddraenen'),
('Y Ddraenen Wen'),
('Y Ddwyberth'),
('Y Deri'),
('Y Derwydd'),
('Y Dolau'),
('Y Dolydd'),
('Y Dolydd The Meadows'),
('Y Domen Fawr'),
('Y Drain'),
('Y Dref'),
('Y Dreflan'),
('Y Drenewydd'),
('Y Drenewydd a Llanllwchaearn'),
('Y Drenewydd Gogledd Llanllwchaearn'),
('Y Drenewydd Gorllewin Llanllwchaearn'),
('Y Drim'),
('Y Drindod Dewi Saint'),
('Y Drindod Dewi Sant'),
('Y Drum'),
('Y Fach'),
('Y Faenor'),
('Y Fali'),
('Y Fan'),
('Y Farchnad'),
('Y Fawnen'),
('Y Fedwen'),
('Y Feithrinfa'),
('Y Felin'),
('Y Felin Ffrwd'),
('Y Felin Goed'),
('Y Felin Heli'),
('Y Felin Lon'),
('Y Felinheli'),
('Y Fenni'),
('Y Ferwig'),
('Y Ffald'),
('Y Ffawydden'),
('Y Ffennant'),
('Y Fferi Isaf'),
('Y Fflint'),
('Y Ffordd Wen'),
('Y Ffowndri'),
('Y Ffridd'),
('Y Ffrith'),
('Y Ffrydd'),
('Y Ffynnon Haearn'),
('Y Ffòr'),
('Y Ffôr'),
('Y Foel'),
('Y Foel Goch'),
('Y Foryd'),
('Y Fron'),
('Y Fronllwyd'),
('Y Fâl'),
('Y Gadfa'),
('Y Gaer'),
('Y Gamallt'),
('Y Gamer'),
('Y Gamlas'),
('Y Gamriw'),
('Y Ganolfan'),
('Y Garn'),
('Y Garnedd'),
('Y Garreg'),
('Y Garth'),
('Y Garw'),
('Y Gefnen'),
('Y Geibren'),
('Y Gelli'),
('Y Gelli Gandryll'),
('Y Gerddi'),
('Y Gesail'),
('Y Gifford'),
('Y Gilan'),
('Y Gilfach'),
('Y Gilfach Isaf'),
('Y Gilfach Uchaf'),
('Y Gilfach goch'),
('Y Gilwern'),
('Y Globa Fawr'),
('Y Glog'),
('Y Glonc'),
('Y Glyderau'),
('Y Glyn'),
('Y Glynnor'),
('Y Glòg'),
('Y Goedlan'),
('Y Goedwig'),
('Y Gogarth'),
('Y Golfa'),
('Y Golff'),
('Y Gorlan'),
('Y Gors'),
('Y Gorsedd'),
('Y Graig'),
('Y Gribin'),
('Y Groes'),
('Y Groes Fagl'),
('Y Groes Wen'),
('Y Groeslon'),
('Y Grugan'),
('Y Grysmwnt'),
('Y Gully'),
('Y Gurn'),
('Y Gurnos'),
('Y Gwernydd'),
('Y Gwter'),
('Y Gwyndy Ysgol Gyfun Cwm Rhymni'),
('Y Gyrn'),
('Y Lan'),
('Y Lanfa'),
('Y Lasinwen'),
('Y Lawnt'),
('Y Lawnt Fowlio'),
('Y Lincs'),
('Y Llan'),
('Y Llanerch'),
('Y Llannerch'),
('Y Llech'),
('Y Llest'),
('Y Llethr'),
('Y Lliwedd'),
('Y Llwyn'),
('Y Llwyni'),
('Y Lon Gam'),
('Y Lon Goed'),
('Y Lon Groes'),
('Y Lon Las'),
('Y Lòn Gefn'),
('Y Maerdy'),
('Y Maes'),
('Y Mieri'),
('Y Mot'),
('Y Mwmbwls'),
('Y Mynydd Bychan'),
('Y Nant'),
('Y Parc'),
('Y Parciau'),
('Y Penrhyn'),
('Y Pil'),
('Y Pinwydd'),
('Y Popls'),
('Y Poplys'),
('Y Porth'),
('Y Priordy'),
('Y Prom'),
('Y Pîl'),
('Y Rhath'),
('Y Rhigos'),
('Y Rhiw'),
('Y Rhodfa'),
('Y Rhos'),
('Y Rhws'),
('Y Rhyl'),
('Y Ro Fawr'),
('Y Ro Wen'),
('Y Sblot'),
('Y Sgwar'),
('Y Sgwâr'),
('Y Stryd Fawr'),
('Y Stryd Newydd'),
('Y Stryd Uchel'),
('Y Stryt Fawr'),
('Y Swnt'),
('Y Talar'),
('Y Teiryd'),
('Y Traeth'),
('Y Trallwng'),
('Y Trallwng Gungrog'),
('Y Trallwng Llanerchyddol'),
('Y Trwyn'),
('Y Tyddyn'),
('Y Tymbl'),
('Y Waen'),
('Y Waun'),
('Y Waun Fach'),
('Y Weirglodd'),
('Y Wenallt'),
('Y Wennallt'),
('Y Wern'),
('Y Wig'),
('Yaa Field'),
('Yacht Haven Quay'),
('Yacht Way'),
('Yachtsman Close'),
('Yacley Close'),
('Yad Moss'),
('Yadburgh Hill'),
('Yadd Linn Wood'),
('Yaddlethorpe'),
('Yade Moss'),
('Yadley Close'),
('Yadley Lane'),
('Yadley Way'),
('Yafford'),
('Yafford Furze Brake'),
('Yafforth'),
('Yafforth Moor'),
('Yagden Hill'),
('Yair Boat Stream'),
('Yair Drive'),
('Yair Hill Forest'),
('Yairs Rise'),
('Yalberton Copse'),
('Yalbury Lane'),
('Yalbury Wood Way'),
('Yalden Close'),
('Yalden Lane'),
('Yaldham'),
('Yaldhurst Copse'),
('Yaldhurst Lane'),
('Yalding'),
('Yalding Close'),
('Yalding Drive'),
('Yalding Hill'),
('Yale Close'),
('Yale Drive'),
('Yale Mews'),
('Yale Park'),
('Yale Way'),
('Yall Flat Lane'),
('Yalland Close'),
('Yalland Warren'),
('Yallands Hill'),
('Yallop Way'),
('Yalta Close'),
('Yalts Brow'),
('Yamna Field'),
('Yan Brow'),
('Yanel Lane'),
('Yanhey Copse'),
('Yanhey Hill'),
('Yanhey Moor'),
('Yanleigh Close'),
('Yanley'),
('Yanley Lane'),
('Yannon Drive'),
('Yannon Lane'),
('Yans Lane'),
('Yantlet Beach'),
('Yantlet Drive'),
('Yanwath'),
('Yanwath and Eamont Bridge'),
('Yanworth'),
('Yanworth Common'),
('Yanworth Long Acre'),
('Yapham'),
('Yapham Common'),
('Yapin Hill'),
('Yapsel Bank'),
('Yapton'),
('Yapton Lane'),
('Yar Neap'),
('Yar Tor'),
('Yarberry'),
('Yarborough'),
('Yarborough Close'),
('Yarborough Drive'),
('Yarborough Rise'),
('Yarbridge'),
('Yarbridge Close'),
('Yarbrook'),
('Yarburgh'),
('Yarburgh Close'),
('Yarburgh Way'),
('Yarbury Combe'),
('Yarbury Way'),
('Yarcombe'),
('Yarcombe Close'),
('Yard Close'),
('Yard Coal Rise'),
('Yard Copse'),
('Yard Down'),
('Yard Downs Lane'),
('Yard Drove'),
('Yard Drove Withy Bed'),
('Yard Four'),
('Yard Hill'),
('Yard Lane'),
('Yard Mead'),
('Yard Row'),
('Yard Steel'),
('Yard yr Odyn Wood'),
('Yardbury Hill Road'),
('Yarde'),
('Yarde Alders'),
('Yarde Close'),
('Yarde Copse'),
('Yarde Farm'),
('Yarde Hill Orchard'),
('Yarde Lane'),
('Yarde Mead'),
('Yardelands'),
('Yardelands Close'),
('Yardheads'),
('Yardhope Flow'),
('Yardie'),
('Yardington'),
('Yardlea Close'),
('Yardlee Walk'),
('Yardley'),
('Yardley Birmingham'),
('Yardley Chase Road'),
('Yardley Close'),
('Yardley Drive'),
('Yardley East'),
('Yardley Fields'),
('Yardley Fields Road'),
('Yardley Gobion'),
('Yardley Green Road'),
('Yardley Hall Lane'),
('Yardley Hastings'),
('Yardley Hill'),
('Yardley Lane'),
('Yardley Park Road'),
('Yardley Way'),
('Yardley West & Stechford'),
('Yardley Wood Road'),
('Yardro'),
('Yards Brake'),
('Yards Hill'),
('Yards Lane'),
('Yards South Coppice'),
('Yards West Coppice'),
('Yardstone Knowe'),
('Yardwall Manor Farm'),
('Yardworthy'),
('Yardy Close'),
('Yare and All Saints'),
('Yare Close'),
('Yare Valley Drive'),
('Yare Valley Rise'),
('Yare View Close'),
('Yare Way'),
('Yarfils Wick'),
('Yarford'),
('Yarhampton'),
('Yarhampton Cross'),
('Yarker Bank Lane'),
('Yarker Lane'),
('Yarkhill'),
('Yarkhill Marsh'),
('Yarl Meadow'),
('Yarl Well'),
('Yarlands'),
('Yarlet'),
('Yarlet Hill'),
('Yarlet Lane'),
('Yarley'),
('Yarley Field Lane'),
('Yarley Hill'),
('Yarlington'),
('Yarlington Close'),
('Yarlington Mill'),
('Yarlington Orchard'),
('Yarlsber'),
('Yarlsey Hill'),
('Yarlsey Moss'),
('Yarlside'),
('Yarlside Close'),
('Yarlside Hill'),
('Yarlside Lane'),
('Yarm'),
('Yarm Back Lane'),
('Yarm Close'),
('Yarm Court Road'),
('Yarm Holt'),
('Yarm Lane'),
('Yarm Way'),
('Yarmer Head'),
('Yarmleigh Copse'),
('Yarmleigh Lane'),
('Yarmley Lane'),
('Yarmouth'),
('Yarmouth Close'),
('Yarmouth Drive'),
('Yarmouth Ferry'),
('Yarmouth Green'),
('Yarmouth Harbour'),
('Yarmouth Nelson and Southtown'),
('Yarmouth North'),
('Yarmouth North and Central'),
('Yarmouth Roads'),
('Yarmouth Sand'),
('Yarmouth Way'),
('Yarmshaw'),
('Yarn Barton'),
('Yarn Close'),
('Yarn Cole'),
('Yarn Copse'),
('Yarn Hill'),
('Yarn Hill Covert'),
('Yarn Lane'),
('Yarn Mill Close'),
('Yarn Walk'),
('Yarnacott'),
('Yarnbarton'),
('Yarnborough Hill'),
('Yarnbrook'),
('Yarnbury Castle'),
('Yarnbury Close'),
('Yarncliff Close'),
('Yarneford Copse'),
('Yarnells Hill'),
('Yarner Beacon'),
('Yarner Close'),
('Yarnfield'),
('Yarnfield Close'),
('Yarnfield Common Wood'),
('Yarnfield Lane'),
('Yarnfield Parkway'),
('Yarngallows Knowe'),
('Yarnhams Close'),
('Yarnhams Copse'),
('Yarningale Close'),
('Yarningale Common'),
('Yarningale Lane'),
('Yarnmakers Path'),
('Yarnold Close'),
('Yarnold Lane'),
('Yarnolds'),
('Yarns Hill'),
('Yarnscombe'),
('Yarnsdale'),
('Yarnshaw Hill'),
('Yarnside Close'),
('Yarnspath Law'),
('Yarnton'),
('Yarnton Close'),
('Yarnton Lane'),
('Yarnton Way'),
('Yarpole'),
('Yarpole Lane'),
('Yarr Dale'),
('Yarr Mill Close'),
('Yarrangall Green'),
('Yarranton Close'),
('Yarrell Mead'),
('Yarrells Close'),
('Yarrells Drive'),
('Yarrells Lane'),
('Yarrington Way'),
('Yarrow'),
('Yarrow Close'),
('Yarrow Drive'),
('Yarrow Gardens Lane'),
('Yarrow Gate'),
('Yarrow Hill'),
('Yarrow Mead'),
('Yarrow Park'),
('Yarrow Point'),
('Yarrow Reservoir'),
('Yarrow Slake'),
('Yarrow Valley Way'),
('Yarrow Walk'),
('Yarrow Way'),
('Yarrowford'),
('Yarrows Hill'),
('Yarrowside'),
('Yarsop'),
('Yartleton Lane'),
('Yartor Down'),
('Yarty'),
('Yarty Copse'),
('Yarwell'),
('Yarwell Close'),
('Yarwell Drive'),
('Yarwell Junction'),
('Yarwells Headland'),
('Yarwells Walk'),
('Yarwood Close'),
('Yarwood Drive'),
('Yarwood Heath'),
('Yarwoodheath Covert'),
('Yarwoodheath Lane'),
('Yate'),
('Yate and Pickup Bank'),
('Yate Central'),
('Yate Lane'),
('Yate North'),
('Yate Rocks'),
('Yate Sills'),
('Yateholm Drive'),
('Yateholme Reservoir'),
('Yatehouse Green'),
('Yatehouse Lane'),
('Yateley'),
('Yateley Close'),
('Yateley Common'),
('Yateley Drive'),
('Yateley East'),
('Yateley East & Blackwater'),
('Yateley Heath Wood'),
('Yateley West'),
('Yately Close'),
('Yates Close'),
('Yates Copse'),
('Yates Drive'),
('Yates Flat'),
('Yates Fold'),
('Yates Hay Road'),
('Yates Lane'),
('Yates Meadow'),
('Yates Way'),
('Yatesbury'),
('Yatesbury Close'),
('Yatesbury Copse'),
('Yatesbury Field'),
('Yatesbury Garth'),
('Yatesbury Lane'),
('Yatesbury Withybed'),
('Yatesfield Hill'),
('Yatland Copse'),
('Yatscombe Copse'),
('Yattendon'),
('Yattendon Lane'),
('Yatton'),
('Yatton Close'),
('Yatton Hall'),
('Yatton Hill'),
('Yatton Keynell'),
('Yatts'),
('Yaud Sike lane'),
('Yaugher Lane'),
('Yaugher Shaw'),
('Yaul Sike Slack'),
('Yaverland'),
('Yaverland Close'),
('Yaverland Drive'),
('Yaw Yeat Wood'),
('Yawl'),
('Yawl Bottom'),
('Yawl Hill'),
('Yawl Hill Lane'),
('Yawling Gate Road'),
('Yawthorpe'),
('Yawthorpe Fox Covert'),
('Yaxham'),
('Yaxley'),
('Yaxley & Farcet'),
('Yaxley Close'),
('Yaxley Fen'),
('Yaxley Hall Lane'),
('Yaxley Loke'),
('Yaxley Meadow'),
('Yaxley Way'),
('Yaxleys Lane'),
('Yazor'),
('Ye Farre Close'),
('Ye Meads'),
('Yea Fold'),
('Yea of Migganess'),
('Yeabridge'),
('Yeabsleys Way'),
('Yeading'),
('Yeading Fork'),
('Yeading Lane'),
('Yeadon'),
('Yeadon Close'),
('Yeadon Drive'),
('Yeadon Garth'),
('Yeadon Moor'),
('Yeadon Moor Road'),
('Yeadon Tarn'),
('Yeadon Walk'),
('Yeadon Way'),
('Yealand Close'),
('Yealand Conyers'),
('Yealand Drive'),
('Yealand Redmayne'),
('Yealand Storrs'),
('Yeald Brow'),
('Yealm Close'),
('Yealm Park'),
('Yealm Pool'),
('Yealm Steps'),
('Yealm View Road'),
('Yealmbridge'),
('Yealmbury Hill'),
('Yealmpstone Close'),
('Yealmpstone Drive'),
('Yealmpton'),
('Yeals Combe'),
('Yealscombe Lane'),
('Yeaman Lane'),
('Yeaman Shore'),
('Yeamans Alley'),
('Yeamans Lane'),
('Yeames Close'),
('Yeaps Drove'),
('Yearby'),
('Yearby Bank'),
('Yearby Close'),
('Yeardsley Close'),
('Yeardsley Green'),
('Yeardsley Lane'),
('Yearl Hill'),
('Yearl Rise'),
('Yearling Chase'),
('Yearling Close'),
('Yearlings Bottom'),
('Yearlings Drove'),
('Yearly Auld Hole'),
('Yearmoor Lane'),
('Yearn Cleuch'),
('Yearn Cleugh'),
('Yearn Hope'),
('Yearngill'),
('Yearngill Head'),
('Yearning Cleuch'),
('Yearning Law'),
('Yearnor'),
('Yearnor Mill Lane'),
('Yearnslow'),
('Yearsley'),
('Yearsley Cross'),
('Yearsley Moor'),
('Yearsley Moor Bank'),
('Yearsleys Lane'),
('Yeat House'),
('Yeates Arce'),
('Yeates Close'),
('Yeates Drive'),
('Yeates Field View'),
('Yeatman Close'),
('Yeatman'),
('Yeatmans Close'),
('Yeatmans Lane'),
('Yeaton'),
('Yeats Close'),
('Yeats Drive'),
('Yeats Way'),
('Yeatt Copse'),
('Yeaveley'),
('Yeavering'),
('Yeavering Bell'),
('Yeavering Close'),
('Yeckhouse Lane'),
('Yedingham'),
('Yedman Dale'),
('Yeend Close'),
('Yeftly Drive'),
('Yelcombe Bottom'),
('Yelcombe Drove'),
('Yeld Bank'),
('Yeld Close'),
('Yeld Hall Road'),
('Yeld Lane'),
('Yelden'),
('Yelden Close'),
('Yelden Spinney'),
('Yelden Wold'),
('Yeldersley'),
('Yeldersley Close'),
('Yeldersley Lane'),
('Yeldham'),
('Yeldham Lock'),
('Yeldham Mews'),
('Yeldon Close'),
('Yelds Hill'),
('Yelds Rough'),
('Yelford'),
('Yell Bank'),
('Yell Dingle'),
('Yell Hill'),
('Yell Pool'),
('Yell Rough'),
('Yell Sound'),
('Yella Moor'),
('Yellaford Way'),
('Yelland'),
('Yelland Common Wood'),
('Yelland Copse'),
('Yelland Cross'),
('Yelland Lane'),
('Yelland Moor'),
('Yelland Walk'),
('Yellands'),
('Yellands Moor'),
('Yellands Park'),
('Yellaton Lane'),
('Yelling'),
('Yellingmill Lane'),
('Yellnowte Isle'),
('Yellow Ark'),
('Yellow Batches Drove'),
('Yellow Bog'),
('Yellow Brae'),
('Yellow Brook Close'),
('Yellow Carn'),
('Yellow Carn Porth'),
('Yellow Craig'),
('Yellow Craig Head'),
('Yellow Craigs'),
('Yellow Falls'),
('Yellow Fawns'),
('Yellow Hammer Rock'),
('Yellow Head'),
('Yellow Hill'),
('Yellow Hill Wood'),
('Yellow Horse'),
('Yellow House Lane'),
('Yellow Hundred Close'),
('Yellow Isle'),
('Yellow Lake'),
('Yellow Lane'),
('Yellow Ledge'),
('Yellow Lodge Drive'),
('Yellow Moss'),
('Yellow Muir'),
('Yellow Nose'),
('Yellow Post'),
('Yellow Quarry Wood'),
('Yellow Rabbit Hills'),
('Yellow Rock'),
('Yellow Rocks'),
('Yellow Rocks of Splears'),
('Yellow Stack'),
('Yellow Stone'),
('Yellow Top'),
('Yellow Tor Court'),
('Yellow Tor Lane'),
('Yellow Way Road'),
('Yellow Withy Bed'),
('Yellow Wort'),
('Yellowberries Copse'),
('Yellowcar'),
('Yellowcar Hole'),
('Yellowcombe Lane'),
('Yellowcress Drive'),
('Yellowford'),
('Yellowham Hill'),
('Yellowhammer Close'),
('Yellowhammer Drive'),
('Yellowhammers'),
('Yellowmead Down'),
('Yellowpine Way'),
('Yellowstone Close'),
('Yells Way'),
('Yelmacott Moor'),
('Yelnow Lane'),
('Yelsted'),
('Yelsted Lane'),
('Yelt Lane'),
('Yelting Geo'),
('Yelvertoft'),
('Yelvertoft Fieldside Covert'),
('Yelverton'),
('Yelverton Close'),
('Yelverton Drive'),
('Yelverton Reservoir'),
('Yelverton Rural'),
('Yemscroft'),
('Yendacott Copse'),
('Yendacott Lane'),
('Yenham Lane'),
('Yennadon Down'),
('Yennastaba Dale'),
('Yennepark Copse'),
('Yenston'),
('Yenston Close'),
('Yenston Hill'),
('Yenton Close'),
('Yenworthy Combe'),
('Yenworthy Common'),
('Yeo'),
('Yeo Bank Lane'),
('Yeo Brake'),
('Yeo Close'),
('Yeo Copse'),
('Yeo Drive'),
('Yeo Hill'),
('Yeo Lane'),
('Yeo Mill'),
('Yeo Moor'),
('Yeo Moor Drove'),
('Yeo Park'),
('Yeo Vale'),
('Yeo Vale Road'),
('Yeo Valley'),
('Yeo Valley Way'),
('Yeo Way'),
('Yeoford'),
('Yeoford Copse'),
('Yeoford Drive'),
('Yeoford Meadows'),
('Yeoford Way'),
('Yeol Mouth'),
('Yeoland Down'),
('Yeoland Lane'),
('Yeolands Drive'),
('Yeolden Copse'),
('Yeolland Lane'),
('Yeolland Park'),
('Yeolmbridge'),
('Yeolmouth Cliff'),
('Yeoman Bank'),
('Yeoman Close'),
('Yeoman Cottages'),
('Yeoman Drive'),
('Yeoman Fold'),
('Yeoman Gate'),
('Yeoman Hey Reservoir'),
('Yeoman Hill'),
('Yeoman Lane'),
('Yeoman Meadow'),
('Yeoman Park'),
('Yeoman Way'),
('Yeomanry Close'),
('Yeomanry Drive'),
('Yeomanry Walk'),
('Yeomanry Way'),
('Yeomans'),
('Yeomans Acre'),
('Yeomans Close'),
('Yeomans Dale'),
('Yeomans Drive'),
('Yeomans Field'),
('Yeomans Gate'),
('Yeomans Lane'),
('Yeomans Lodge'),
('Yeomans Meadows'),
('Yeomans Mount'),
('Yeomans Orchard'),
('Yeomans Ride'),
('Yeomans Row'),
('Yeomans Way'),
('Yeomans Yard'),
('Yeomanside Close'),
('Yeomead'),
('Yeomeads'),
('Yeomen Way'),
('Yeorton Brow'),
('Yeoveney Close'),
('Yeovil'),
('Yeovil Central'),
('Yeovil Chase'),
('Yeovil Close'),
('Yeovil District'),
('Yeovil Junction'),
('Yeovil Marsh'),
('Yeovil Pen Mill'),
('Yeovil Rock'),
('Yeovil Westland Airfield'),
('Yeovil Without'),
('Yeovilton'),
('Yeovilton Close'),
('Yeovilton Royal Naval Air'),
('Yeowood'),
('Yerbeston'),
('Yerley Hill'),
('Yerton Brae'),
('Yes Tor'),
('Yesmere'),
('Yesnaby'),
('Yessell Lane'),
('Yessness'),
('Yester'),
('Yester Drive'),
('Yester Park'),
('Yet Mead Lane'),
('Yetholm'),
('Yetholm Law'),
('Yetholm Loch'),
('Yetholm Park'),
('Yetholm Way'),
('Yethouse Hill'),
('Yetlands'),
('Yetlington'),
('Yetlington Drive'),
('Yetmans Copse'),
('Yetminster'),
('Yetminster & Cam Vale'),
('Yett Hill'),
('Yettington'),
('Yettna Geo'),
('Yetts Hole Road'),
('Yetts o Muckhart'),
('Yevele Close'),
('Yevele Way'),
('Yew Band'),
('Yew Bank'),
('Yew Bank Road'),
('Yew Barrow'),
('Yew Barrow Breast'),
('Yew Barrow Close'),
('Yew Barrow Wood'),
('Yew Cleugh'),
('Yew Cliff Coppice'),
('Yew Close'),
('Yew Clump'),
('Yew Corner'),
('Yew Covert'),
('Yew Croft Avenue'),
('Yew Dale Gardens'),
('Yew Down'),
('Yew Drive'),
('Yew Gate'),
('Yew Greave Crescent'),
('Yew Green'),
('Yew Green Avenue'),
('Yew Green Road'),
('Yew Hill'),
('Yew Lane'),
('Yew Oval'),
('Yew Pike Moss'),
('Yew Redding'),
('Yew Ring'),
('Yew Scar Force'),
('Yew Tree'),
('Yew Tree Avenue'),
('Yew Tree Bank'),
('Yew Tree Bottom Road'),
('Yew Tree Close'),
('Yew Tree Close Covert'),
('Yew Tree Copse'),
('Yew Tree Corner'),
('Yew Tree Court'),
('Yew Tree Courtyard'),
('Yew Tree Covert'),
('Yew Tree Crescent'),
('Yew Tree Dingle'),
('Yew Tree Drive'),
('Yew Tree Farm'),
('Yew Tree Gardens'),
('Yew Tree Gorge'),
('Yew Tree Green'),
('Yew Tree Green Road'),
('Yew Tree Grounds'),
('Yew Tree Grove'),
('Yew Tree Hangings'),
('Yew Tree Heath'),
('Yew Tree Hill'),
('Yew Tree Hills'),
('Yew Tree Hollow'),
('Yew Tree Lane'),
('Yew Tree Meadow'),
('Yew Tree Mews'),
('Yew Tree Moor'),
('Yew Tree Park'),
('Yew Tree Park Road'),
('Yew Tree Place'),
('Yew Tree Rein'),
('Yew Tree Rise'),
('Yew Tree Road'),
('Yew Tree Shaw'),
('Yew Tree Spinney'),
('Yew Tree Square'),
('Yew Tree Stables'),
('Yew Tree Street'),
('Yew Tree Tarn'),
('Yew Tree Terrace'),
('Yew Tree Walk'),
('Yew Tree Way'),
('Yew Tree Wood'),
('Yew Trees'),
('Yew Trees Avenue'),
('Yew Trees Croft'),
('Yew Trees Wood'),
('Yew Walk'),
('Yew Way'),
('Yewbank Close'),
('Yewbank Lane'),
('Yewbarrow'),
('Yewbarrow Close'),
('Yewberry Close'),
('Yewberry Lane'),
('Yewberry Way'),
('Yewburn Way'),
('Yewcroft'),
('Yewcroft Close'),
('Yewdale'),
('Yewdale Close'),
('Yewdale Crag Moss'),
('Yewdale Drive'),
('Yewdale Fell Side'),
('Yewdale Fells'),
('Yewdale Moss'),
('Yewdale Park'),
('Yewdall Way'),
('Yewens'),
('Yewens Hanger'),
('Yewhedges'),
('Yewhurst Close'),
('Yewlands'),
('Yewlands Close'),
('Yewlands Drive'),
('Yewleigh Lane'),
('Yews Close'),
('Yews Drive'),
('Yews Green'),
('Yews Hill'),
('Yews Hill Road'),
('Yews Lane'),
('Yews Mount'),
('Yewside'),
('Yewstock'),
('Yewstock Crescent West'),
('Yewthwaite Comb'),
('Yewtree Bank'),
('Yewtree Batch'),
('Yewtree Bottom'),
('Yewtree Close'),
('Yewtree Copse'),
('Yewtree Dingle'),
('Yewtree Drive'),
('Yewtree End'),
('Yewtree Gate'),
('Yewtree Green'),
('Yewtree Hanger'),
('Yewtree Hassock'),
('Yewtree Hill'),
('Yewtree Hill Brake'),
('Yewtree Holms'),
('Yewtree Lane'),
('Yewtree Mews'),
('Yewtree Nob'),
('Yewtree Pit Covert'),
('Yewtree Rise'),
('Yewtree Row'),
('Yewtree Shaw'),
('Yewtree Spinney'),
('Yewtree Spring'),
('Yewtree Toll'),
('Yewtreebrake Inclosure'),
('Yewtrees'),
('Yewtrees Lane'),
('Ygerddi'),
('Yield Brae'),
('Yield Hall Lane'),
('Yield Hall Place'),
('Yielding Copse'),
('Yielding Tree'),
('Yieldings Close'),
('Yieldingtree'),
('Yieldshields'),
('Yiewsley'),
('Yiewsley Close'),
('Yiewsley Drive'),
('Yinstay'),
('Yinstay Head'),
('Yllaethdy'),
('Ymyl yr Afon'),
('Ynys'),
('Ynys Amlwch'),
('Ynys Arw'),
('Ynys Bach'),
('Ynys Badrig'),
('Ynys Benlas'),
('Ynys Berchen'),
('Ynys Bery'),
('Ynys Bery Close'),
('Ynys Byr'),
('Ynys Bâch'),
('Ynys Cadwyn'),
('Ynys Cantwr'),
('Ynys Castell'),
('Ynys Close'),
('Ynys Creua'),
('Ynys Cyngar'),
('Ynys Dawel'),
('Ynys Ddu'),
('Ynys Defaid'),
('Ynys Deullyn'),
('Ynys Dinas'),
('Ynys Dol lleian'),
('Ynys Dol rhedyn'),
('Ynys Drai'),
('Ynys Dulas'),
('Ynys Eilun'),
('Ynys Enlli'),
('Ynys Fach'),
('Ynys Fach Avenue'),
('Ynys Faelog'),
('Ynys Fawr'),
('Ynys Fawr Avenue'),
('Ynys Feirig'),
('Ynys Fer Lâs'),
('Ynys Feurig'),
('Ynys Fâch'),
('Ynys Gaint'),
('Ynys Galch'),
('Ynys Gifftan'),
('Ynys Glyd Street'),
('Ynys Goediog'),
('Ynys Gored Goch'),
('Ynys Groes'),
('Ynys Gron'),
('Ynys Gwair'),
('Ynys Gwelltog'),
('Ynys Gwylan bâch'),
('Ynys Gwylan fawr'),
('Ynys Gwyndwn mawr'),
('Ynys Gybi'),
('Ynys Halen'),
('Ynys Hir'),
('Ynys Hwrddod'),
('Ynys Isaf'),
('Ynys Lane'),
('Ynys Las'),
('Ynys Lawd'),
('Ynys Leurad'),
('Ynys Llanddwyn'),
('Ynys Llanfihangel y traethau'),
('Ynys Lochtyn'),
('Ynys Lom'),
('Ynys Meibion'),
('Ynys Meicel'),
('Ynys Melyn'),
('Ynys Moelfre'),
('Ynys Mon'),
('Ynys Môn'),
('Ynys Nedd'),
('Ynys Newydd Road'),
('Ynys Onnen'),
('Ynys Peibio'),
('Ynys Piod'),
('Ynys Seiriol'),
('Ynys Sili'),
('Ynys Sych'),
('Ynys Thomas Howel'),
('Ynys Tobig'),
('Ynys Traws'),
('Ynys Tysilio'),
('Ynys Tywyn'),
('Ynys Wall'),
('Ynys Wellt'),
('Ynys Welltog'),
('Ynys y Big'),
('Ynys y Brawd'),
('Ynys y Carcharorion'),
('Ynys y Castell'),
('Ynys y Clochydd'),
('Ynys Y Coed'),
('Ynys Y Cwm Road'),
('Ynys y Ddinas'),
('Ynys y Fydlyn'),
('Ynys Y Gored'),
('Ynys y Mochyn'),
('Ynys Y Nos'),
('Ynys Y Wern'),
('Ynys yr Adar'),
('Ynys yr Wyn'),
('Ynys Forgan'),
('Ynys Gyfeillon Road'),
('Ynys hafren'),
('Ynys Lee'),
('Ynys Lwyd Road'),
('Ynys Lwyd Street'),
('Ynys Meudwy Road'),
('Ynys Mòn'),
('Ynys Penllwch Road'),
('Ynys Tawe'),
('Ynys uchaf'),
('Ynys wen'),
('Ynys Wil hernyn Wood'),
('Ynys y bwl'),
('Ynys y bwl a Choed y cwm'),
('Ynys y cranc'),
('Ynys Y Mond Road'),
('Ynys y mond Uchaf'),
('Ynys y pica Wood'),
('Ynys Yr Afon'),
('Ynysangharad'),
('Ynysarwed'),
('Ynysawdre'),
('Ynysboeth'),
('Ynysbryn Close'),
('Ynyscedwyn'),
('Ynysddu'),
('Ynysddu Hotel Approach'),
('Ynysderw Park Road'),
('Ynysfach'),
('Ynysforgan'),
('Ynysfro Reservoirs'),
('Ynysgedwyn'),
('Ynyshir'),
('Ynyslas'),
('Ynysmaerdy'),
('Ynysmeudwy'),
('Ynysoedd Duon'),
('Ynysoedd Gwylanod'),
('Ynysoedd y Ffrydiau'),
('Ynysoedd y Moelrhoniaid'),
('Ynysowen'),
('Ynysowen Fach'),
('Ynyspenllwch'),
('Ynystawe'),
('Ynysteg'),
('Ynyswen'),
('Ynyswerdd'),
('Ynysybwl'),
('Ynysybwl and Coed y Cwm'),
('Ynysydarren'),
('Ynysygwas'),
('Ynysygwas Hill'),
('Ynysymaerdy'),
('Yoadcastle'),
('Yoadcomb Hill'),
('Yoadwath Bank'),
('Yoags Haven'),
('Yoakes Lane'),
('Yock Lane'),
('Yockenthwaite'),
('Yockenthwaite Moor'),
('Yockleton'),
('Yockletts Banks'),
('Yockley Close'),
('Yockney Close'),
('Yoden Way'),
('Yoells Copse'),
('Yoells Lane'),
('Yoga Way'),
('Yogli Geo'),
('Yohden Hall'),
('Yoke'),
('Yoke Close'),
('Yoke Hill'),
('Yoke Knowes'),
('Yokecliffe Drive'),
('Yokecliffe Hill'),
('Yokecliffe Lane'),
('Yokefleet'),
('Yokefleet Clough'),
('Yokehouse Lane'),
('Yokeing Close Wood'),
('Yoker'),
('Yoker Ferry Road'),
('Yoker Mill Gardens'),
('Yoker Mill Road'),
('Yokesford Hill'),
('Yokosuka Way'),
('Yolhey Lane'),
('Yolk Meadow'),
('Yollacombe'),
('Yolland Close'),
('Yolland Hill'),
('Yolsham Green'),
('Yolsham Hill'),
('Yolsum Close'),
('Yomede Park'),
('Yonder'),
('Yonder Acre Way'),
('Yonder Brake'),
('Yonder Close'),
('Yonder Cross Close Copse'),
('Yonder Drove'),
('Yonder Hare Down'),
('Yonder Horse Park Copse'),
('Yonder Mead'),
('Yonder Meadow'),
('Yonder Moor'),
('Yonder Mount'),
('Yonder Slade'),
('Yonder Way'),
('Yonder Wyke Moor Copse'),
('Yonderberry Point'),
('Yondercott'),
('Yondertown'),
('Yondover'),
('Yondover Mill'),
('Yonge Close'),
('Yonge Park'),
('Yons Hill'),
('Yons Nab'),
('Yont the Cleugh'),
('Yopps Green'),
('Yorburgh'),
('Yore Mill'),
('Yoredale Close'),
('Yoredale Drive'),
('Yoreham Close'),
('York'),
('York Alley'),
('York And Albany Close'),
('York Bridge'),
('York Bridge Road'),
('York Buildings'),
('York Central'),
('York Chase'),
('York Close'),
('York Cottages'),
('York Dale'),
('York Day'),
('York Drive'),
('York Drove'),
('York Fields'),
('York Garth'),
('York Gate'),
('York Gate Lane'),
('York Hill'),
('York Hill Crescent'),
('York Hill Road'),
('York Hospital Nuffield Health'),
('York House Place'),
('York House Road'),
('York Lane'),
('York Mews'),
('York Outer'),
('York Paddock'),
('York Place Lane'),
('York Ride'),
('York Rise'),
('York Row'),
('York St John'),
('York Street Building'),
('York Street Lane'),
('York Teaching'),
('York Terrace East'),
('York Terrace Lane'),
('York Terrace West'),
('York Town'),
('York Villa Close'),
('York Villas'),
('York Walk'),
('York Way'),
('York Way Court'),
('York Way Field'),
('Yorkbrooke Drive'),
('Yorkdale'),
('Yorkdale Close'),
('Yorkdale Drive'),
('Yorke Close'),
('Yorke Drive'),
('Yorke Gate'),
('Yorke Rise'),
('Yorke Rock'),
('Yorke Way'),
('Yorkersgate'),
('Yorkes Dingles'),
('Yorkfield Lane'),
('Yorkhill'),
('Yorkhurst Hill'),
('Yorklands'),
('Yorklets'),
('Yorkletts'),
('Yorkley'),
('Yorkley Lane'),
('Yorkley Slade'),
('Yorkley Wood Road'),
('Yorkminster Drive'),
('Yorks Hill'),
('Yorks Lane'),
('Yorks Wood Drive'),
('Yorkshire'),
('Yorkshire and The Humber'),
('Yorkshire Close'),
('Yorkshire Dales National Park'),
('Yorkshire Drive'),
('Yorkshire Shaw'),
('Yorkshire Street East'),
('Yorkshire Street West'),
('Yorkshire Way'),
('Yorkshire Wolds'),
('Yorkshireside'),
('Yorkston Moss'),
('Yorkstone'),
('Yorkstone Close'),
('Yorktown Close'),
('Yorkway'),
('Yorkwood'),
('Yorstans Geo'),
('Yorton'),
('Yorton Heath'),
('Yosemite Park'),
('Yottenfews'),
('Youchtrie Heugh'),
('Youens Drive'),
('Youens Way'),
('Youghal Close'),
('Youings Drive'),
('Youlbury Pool'),
('Youlden Close'),
('Youlden Drive'),
('Youlden Lane'),
('Youlden'),
('Youldholes Lane'),
('Youldon Way'),
('Youldons Close'),
('Youlgrave'),
('Youlgreave'),
('Youlgreave Close'),
('Youlgreave Drive'),
('Youlieburn'),
('Youll Close'),
('Youlston Close'),
('Youlston Park'),
('Youlstone'),
('Youlthorpe'),
('Youlthorpe Pasture Hill'),
('Youlton'),
('Youlton Moor'),
('Young Bank Lane'),
('Young Bog Wood'),
('Young Bush Wood'),
('Young Close'),
('Young Contract Wood'),
('Young Coombe'),
('Young Copse'),
('Young Covert'),
('Young Croft Brake'),
('Young Drive'),
('Young Hill'),
('Young Jeanies Wood'),
('Young Kings Wood'),
('Young Ladys Wood'),
('Young Lane'),
('Young Marys Grove'),
('Young Oaks'),
('Young Oaks Wood'),
('Young Salamanca Covert'),
('Young Spinney'),
('Young Spring Wood'),
('Young Street North Lane'),
('Young Street South Lane'),
('Young Trees'),
('Young Wynd'),
('Youngcross Grounds'),
('Younger Drive'),
('Younger Quadrant'),
('Youngers Lane'),
('Younghall Close'),
('Youngman Close'),
('Youngmans Close'),
('Youngmans Lane'),
('Youngoak Covert'),
('Youngs Close'),
('Youngs Copse'),
('Youngs Drive'),
('Youngs End'),
('Youngs Hill'),
('Youngs Knowe'),
('Youngs Lane'),
('Youngs Mews'),
('Youngs Orchard'),
('Youngs Paddock'),
('Youngs Park Lane'),
('Youngs Park Road'),
('Youngs Rise'),
('Youngs Row'),
('Youngs Way'),
('Youngs Yard'),
('Youngsbury'),
('Youngsbury Lane'),
('Youngsmere Close'),
('Youngsons Lane'),
('Youngstroat Lane'),
('Youngwood Lane'),
('Youngwoods Copse'),
('Youngwoods Way'),
('Youth Close'),
('Yoxall'),
('Yoxall Drive'),
('Yoxall Park'),
('Yoxall Way'),
('Yoxford'),
('Yoxford Little Street'),
('Yoxford Mews'),
('Yoxhall Drive'),
('Yoxhall Meadow Woods'),
('Yoxie Geo'),
('Yoxley Approach'),
('Yoxley Drive'),
('Ypres Close'),
('Ypres Drive'),
('Ypres Way'),
('Yr Aber'),
('Yr Aes'),
('Yr Ala'),
('Yr Allt'),
('Yr Allt Boeth'),
('Yr Allt Gethin'),
('Yr Angorfa'),
('Yr Aran'),
('Yr Ardd Fawr'),
('Yr Arddu'),
('Yr Arwydd'),
('Yr As Fach'),
('Yr As Fawr'),
('Yr Ebolion'),
('Yr Efail'),
('Yr Eglwys Newydd'),
('Yr Eglwys Newydd a Thongwynlais'),
('Yr Eifl'),
('Yr Elain'),
('Yr Elen'),
('Yr Encil'),
('Yr Encilfa'),
('Yr Erw'),
('Yr Esgair'),
('Yr Hafan'),
('Yr Hafanau'),
('Yr Hafn'),
('Yr Hafod'),
('Yr Harbwr'),
('Yr Havens'),
('Yr Helfa'),
('Yr Helyg'),
('Yr Hen Berlan'),
('Yr Hen Berllan'),
('Yr Hen Draeth Ymdrochi'),
('Yr Hen Erddi'),
('Yr Hen Gorlan'),
('Yr Hen Heol'),
('Yr Hen Laethdy'),
('Yr Hen Ysgol'),
('Yr Hen ffordd'),
('Yr Hendre'),
('Yr Hendy'),
('Yr Hirgylch'),
('Yr Hob'),
('Yr Hobin Cast'),
('Yr Hwylfa'),
('Yr Hòb'),
('Yr Hôb'),
('Yr Ochr'),
('Yr Oerfa'),
('Yr Ogof'),
('Yr Orsedd'),
('Yr Rhos'),
('Yr Wyddfa'),
('Yr Wyddgrug'),
('Yr Wylorn'),
('Yr Ydlan'),
('Yr Ynys'),
('Yr Ysfa'),
('Yr Ysgol John Frost'),
('Yr Ystog'),
('Yr Ystrad'),
('Yr allt Wood'),
('Yr efail Covert'),
('Yr Hen Lawnt'),
('Ysbryd Y Coed'),
('Ysbty Aneurin Bevan'),
('Ysbutyr Santes Tudful'),
('Ysbytr tri Chwm'),
('Ysbytty Reservoir'),
('Ysbyty Alltwen'),
('Ysbyty Athrofaol Cymru'),
('Ysbyty Athrofaol Llandochau'),
('Ysbyty Brenhinol Gwent'),
('Ysbyty Bryn Beryl'),
('Ysbyty Castell Nedd Port Talbot'),
('Ysbyty Coffa Sir Frycheiniog'),
('Ysbyty Coffa Victoria Y Trallwng'),
('Ysbyty Cwm Cynon'),
('Ysbyty Cyffredinol Llwynhelyg'),
('Ysbyty Cymuned Glannau Dyfrdwy'),
('Ysbyty Cymunedol Y Waun'),
('Ysbyty Cymunedol Yr Wyddgrug'),
('Ysbyty Cynfyn'),
('Ysbyty Dewi Sant'),
('Ysbyty Dolgellau Y Bermo Ar Cylch'),
('Ysbyty Eglwys Newydd'),
('Ysbyty Eryri'),
('Ysbyty Frenhinol Morgannwg'),
('Ysbyty Garngoch'),
('Ysbyty Glan Clwyd'),
('Ysbyty Gwynedd Gwynedd'),
('Ysbyty Gymuned Bro Ddyfi'),
('Ysbyty Ifan'),
('Ysbyty Llandudno'),
('Ysbyty Llanymddfri'),
('Ysbyty Maelor Wrecsam'),
('Ysbyty Neuadd Nevill'),
('Ysbyty Penrhos Stanley'),
('Ysbyty Sir Drefaldwyn'),
('Ysbyty Treforys'),
('Ysbyty Twysog Siarl'),
('Ysbyty Tywysoges Cymru'),
('Ysbyty Ystrad Fawr'),
('Ysbyty Ystwyth'),
('Ysceifiog'),
('Ysceifiog Lake'),
('Yscir'),
('Ysgafell Wen'),
('Ysgeifiog'),
('Ysgeifiog Moor'),
('Ysgir'),
('Ysgol'),
('Ysgoldy Covert'),
('Ysgoldy Hill'),
('Ysgool Gynradd Llandochau'),
('Ysgubor'),
('Ysgubor Abad'),
('Ysgubor Fach'),
('Ysgubor Fach Street'),
('Ysgubor Mountain'),
('Ysgubor Newydd'),
('Ysgubor Newydd Lane'),
('Ysgubor Fawr'),
('Ysgubor wen Wood'),
('Ysgubor y Coed'),
('Ysguboriaur Bugail'),
('Ysguborwen'),
('Ysgwd Ffordd'),
('Ysgyryd Fach'),
('Ysgyryd Fawr'),
('YsgÃ¯og Wood'),
('Yspitty'),
('Yspytty Cynfyn'),
('Yspyty Cwm Rhondda'),
('Ystablaur Ysgol'),
('Ystad Bryn Y Ffermwyr'),
('Ystad Cae Bach'),
('Ystad Celyn'),
('Ystad Coed Madog'),
('Ystad Cwm Taf'),
('Ystad Ddiwydiannol Y Glyn'),
('Ystad Deri'),
('Ystad Fferm Y Berllan'),
('Ystad Glorian'),
('Ystad Gwylfa'),
('Ystad Llwyn Bedw'),
('Ystad Mur Poeth'),
('Ystad Tyn Berllan'),
('Ystafelloedd'),
('Ystalyfera'),
('Ysticl Garu'),
('Ystrad'),
('Ystrad Aeron'),
('Ystrad Barwig'),
('Ystrad Close'),
('Ystrad Drive'),
('Ystrad Einion'),
('Ystrad Einon'),
('Ystrad Fawr'),
('Ystrad Fflur'),
('Ystrad Hir'),
('Ystrad Meurig'),
('Ystrad Mynach'),
('Ystrad Rhondda'),
('Ystrad Fawr Villas'),
('Ystrad gwyn'),
('Ystradfellte'),
('Ystradfellte Reservoir'),
('Ystradgynlais'),
('Ystradgynlais Community'),
('Ystradmeurig'),
('Ystradowen'),
('Ystryd Ddu'),
('Ystryd Faen'),
('Ystryd Fawr'),
('Ystryd Y Ceunant'),
('Ystum Taf'),
('Ystumllwynarth'),
('Ystumtuen'),
('Ystwyth'),
('Ystâd Y Gotrel'),
('Ythanbank'),
('Ythanwells'),
('Ythsie'),
('Ytymbl'),
('Yukon Way'),
('Yulan Drive'),
('Yule Close'),
('Yule Hill'),
('Yule Lane'),
('Yule Way'),
('Yumfrau Taing'),
('Yungnapool'),
('Yuntaskeos'),
('Yunus Khan Close'),
('Yves Mews'),
('Yvonne Close'),
('Yachiyo'),
('Yaizu'),
('Yakeshi'),
('Yakutsk'),
('Yalova'),
('Yamagata'),
('Yamaguchi'),
('Yamato'),
('Yamoussoukro'),
('Yamuna Nagar'),
('Yanan'),
('Yanbu'),
('Yancheng'),
('Yangjiang'),
('Yangon'),
('Yangquan'),
('Yangzhou'),
('Yanji'),
('Yantai'),
('Yao'),
('Yaoundé'),
('Yaroslavl'),
('Yasuj'),
('Yatsushiro'),
('Yavatmal'),
('Yazd'),
('Yekaterinburg'),
('Yelets'),
('Yenakiieve'),
('Yeosu'),
('Yerevan'),
('Yessentuki'),
('Yevpatoria'),
('Yibin'),
('Yichang'),
('Yichun'),
('Yidu'),
('Yima'),
('Yinchuan'),
('Yingcheng'),
('Yingkou'),
('Yingtan'),
('Yining'),
('Yiwu'),
('Yixing'),
('Yiyang'),
('Yizheng'),
('Yogyakarta'),
('Yokkaichi'),
('Yokohama'),
('Yokosuka'),
('Yonago'),
('Yongan'),
('Yongzhou'),
('Yonkers'),
('Yopal'),
('Yoshkar Ola'),
('Yuanjiang'),
('Yueyang'),
('Yulin'),
('Yumen'),
('Yuncheng'),
('Yusufiyah'),
('Yuxi'),
('Yuyao'),
('Yuzhno Sakhalinsk'),
('Yuzhou'),
('Yannons'),
('Yateley Lakes'),
('Yaud'),
('Yei'),
('Yeld'),
('Yellow Man'),
('Yeolands'),
('Yett'),
('Yetts'),
('Yews'),
('Yonne'),
('York District');
-- Down
DELETE FROM "Placename" WHERE "keyword" LIKE 'y%';