-- Up
INSERT INTO Placename (keyword)
VALUES
('Zachary Close'),
('Zachary Merton Community'),
('Zacharys Copse'),
('Zacrys Islands'),
('Zaggy Lane'),
('Zambesi Drive'),
('Zambezie Drive'),
('Zambra Way'),
('Zamek Close'),
('Zamenhof Grove'),
('Zan Drive'),
('Zander Court'),
('Zander Grove'),
('Zannies Coppice'),
('Zante Close'),
('Zantmans Rock'),
('Zara Close'),
('Zara Court'),
('Zara Way'),
('Zareba Clump'),
('Zaria Court'),
('Zarya Court'),
('Zawn a Bal'),
('Zawn Alley'),
('Zawn Alley Isle'),
('Zawn Brinny'),
('Zawn Bros'),
('Zawn Buzz and Gen'),
('Zawn Carve'),
('Zawn Core'),
('Zawn Daniel'),
('Zawn Duel'),
('Zawn Gamper'),
('Zawn Harry'),
('Zawn Kellys'),
('Zawn Lookout'),
('Zawn Organ'),
('Zawn Pedn Kei'),
('Zawn Peggy'),
('Zawn Pyg'),
('Zawn Quoits'),
('Zawn Reeth'),
('Zawn Rinny'),
('Zawn Rundle'),
('Zawn Shaggy'),
('Zawn Susan'),
('Zawn Tor'),
('Zawn Trevilley'),
('Zawn Turbis'),
('Zawn Vinoc'),
('Zawn Wells'),
('Zeal Ball Copse'),
('Zeal Brake'),
('Zeal Gully'),
('Zeal Head'),
('Zeal Hill'),
('Zeal House Copse'),
('Zeal Monachorum'),
('Zeal Plains'),
('Zealand Avenue'),
('Zealand Close'),
('Zealand Drive'),
('Zealand Park'),
('Zeals'),
('Zeals Garth'),
('Zeals Green Drive'),
('Zeals Knoll'),
('Zeals Rise'),
('Zeals Row'),
('Zebedee Close'),
('Zebon Copse'),
('Zebra Hill'),
('Zeigfeld Court'),
('Zelah'),
('Zelah Hill'),
('Zelham Drive'),
('Zell House Copse'),
('Zembard Lane'),
('Zenith'),
('Zenith Avenue'),
('Zenith Close'),
('Zenith Walk'),
('Zennor'),
('Zennor Cliff'),
('Zennor Grove'),
('Zennor Head'),
('Zennor Hill'),
('Zephaniah Way'),
('Zephon Common'),
('Zephyr Close'),
('Zermatt Close'),
('Zermatt Grove'),
('Zermatt Mount'),
('Zeta Close'),
('Zeth Hill Lane'),
('Zetland'),
('Zetland Avenue'),
('Zetland Avenue North'),
('Zetland Close'),
('Zetland Drive'),
('Zetland Hunt'),
('Zetland Row'),
('Zetland Square'),
('Zeus Lane'),
('Zider Pass'),
('Zig Zag'),
('Zig Zag Road'),
('Zig  Zag Hill'),
('Zig  Zag Lane'),
('Zigzag Covert'),
('Zinnia Close'),
('Zinnia Drive'),
('Zinnia Row'),
('Zion Close'),
('Zion Drive'),
('Zion Hill'),
('Zion Lane'),
('Zion Passage'),
('Zion Row'),
('Zions Close'),
('Zions Clump'),
('Zions Loan'),
('Zionshill Copse'),
('Zircon Close'),
('Zoar'),
('Zoar Avenue'),
('Zoar Close'),
('Zoar Lane'),
('Zobel Close'),
('Zodiac Close'),
('Zodiac Drive'),
('Zoes Place Baby Hospice'),
('Zone Point'),
('Zorbit Mews'),
('Zorrina Close'),
('Zortech Avenue'),
('Zouch'),
('Zouch Avenue'),
('Zouch Close'),
('Zouch Farm Road'),
('Zouche Close'),
('Zouche Way'),
('Zuider Zee'),
('Zulu Bank'),
('Zura Avenue'),
('Zura Drive'),
('Zurich'),
('Zurich Avenue'),
('Zurich Close'),
('Zaanstad'),
('Zabol'),
('Zabrze'),
('Zacatecas'),
('Zagazig'),
('Zagreb'),
('Zahedan'),
('Zama'),
('Zamboanga City'),
('Zanjan'),
('Zanzibar City'),
('Zaoyang'),
('Zaozhuang'),
('Zapopan'),
('Zaporizhia'),
('Zaragoza'),
('Zaria'),
('Zarqa'),
('Zelenograd'),
('Zenica'),
('Zhalantun'),
('Zhangjiagang'),
('Zhangjiajie'),
('Zhangjiakou'),
('Zhangshu'),
('Zhangye'),
('Zhangzhou'),
('Zhanjiang'),
('Zhaodong'),
('Zhaoqing'),
('Zhaotong'),
('Zheleznodorozhny'),
('Zhengzhou'),
('Zhenjiang'),
('Zhongshan'),
('Zhoukou'),
('Zhoushan'),
('Zhucheng'),
('Zhuhai'),
('Zhuji'),
('Zhukovsky'),
('Zhumadian'),
('Zhuozhou'),
('Zhuzhou'),
('Zhytomyr'),
('Zibo'),
('Zielona Góra'),
('Zigong'),
('Ziguinchor'),
('Zihuatanejo'),
('Zinder'),
('Zipaquirá'),
('Zixing'),
('Zlatoust'),
('Zoetermeer'),
('Zonguldak'),
('Zrenjanin'),
('Zunyi'),
('Zürich'),
('Zuwarah'),
('Zwolle'),
('Zawn');
-- Down
DELETE FROM "Placename" WHERE "keyword" LIKE 'z%';