-- Up
INSERT INTO Placename (keyword)
VALUES
('Zaanstad'),
('Zabol'),
('Zabrze'),
('Zacatecas'),
('Zachary'),
('Zachary Merton Community'),
('Zacharys'),
('Zacrys Islands'),
('Zagazig'),
('Zaggy'),
('Zagreb'),
('Zahedan'),
('Zakopane'),
('Zama'),
('Zambesi'),
('Zambezie'),
('Zamboanga City'),
('Zambra'),
('Zamek'),
('Zamenhof'),
('Zammit'),
('Zamor'),
('Zampa'),
('Zan'),
('Zander'),
('Zandi'),
('Zangwill'),
('Zanjan'),
('Zannies'),
('Zante'),
('Zantmans Rock'),
('Zanzibar'),
('Zanzibar City'),
('Zaoyang'),
('Zaozhuang'),
('Zapopan'),
('Zaporizhia'),
('Zara'),
('Zaragoza'),
('Zareba Clump'),
('Zaria'),
('Zarqa'),
('Zarya'),
('Zawn'),
('Zawn a Bal'),
('Zawn Alley'),
('Zawn Alley Isle'),
('Zawn Brinny'),
('Zawn Bros'),
('Zawn Buzz'),
('Gen'),
('Zawn Carve'),
('Zawn Core'),
('Zawn Daniel'),
('Zawn Duel'),
('Zawn Gamper'),
('Zawn Harry'),
('Zawn Kellys'),
('Zawn Lookout'),
('Zawn Organ'),
('Zawn Pedn Kei'),
('Zawn Peggy'),
('Zawn Pyg'),
('Zawn Quoits'),
('Zawn Reeth'),
('Zawn Rinny'),
('Zawn Rundle'),
('Zawn Shaggy'),
('Zawn Susan'),
('Zawn Tor'),
('Zawn Trevilley'),
('Zawn Turbis'),
('Zawn Vinoc'),
('Zawn Wells'),
('Zeal'),
('Zeal Ball'),
('Zeal Brake'),
('Zeal Gully'),
('Zeal Head'),
('Zeal House'),
('Zeal Monachorum'),
('Zeal Plains'),
('Zealand'),
('Zealandia'),
('Zeals'),
('Zeals Garth'),
('Zeals Knoll'),
('Zebedee'),
('Zebon'),
('Zebra'),
('Zebu'),
('Zebudah'),
('Zechariah'),
('Zeigfeld'),
('Zelah'),
('Zelenograd'),
('Zelham'),
('Zell House'),
('Zembard'),
('Zena'),
('Zenica'),
('Zenith'),
('Zennor'),
('Zennor Cliff'),
('Zennor Head'),
('Zenoria'),
('Zephaniah'),
('Zephon'),
('Zephyr'),
('Zermatt'),
('Zeta'),
('Zeth'),
('Zetland'),
('Zetland Hunt'),
('Zeus'),
('Zhalantun'),
('Zhangjiagang'),
('Zhangjiajie'),
('Zhangjiakou'),
('Zhangshu'),
('Zhangye'),
('Zhangzhou'),
('Zhanjiang'),
('Zhaodong'),
('Zhaoqing'),
('Zhaotong'),
('Zheleznodorozhny'),
('Zhengzhou'),
('Zhenjiang'),
('Zhongshan'),
('Zhoukou'),
('Zhoushan'),
('Zhucheng'),
('Zhuhai'),
('Zhuji'),
('Zhukovsky'),
('Zhumadian'),
('Zhuozhou'),
('Zhuzhou'),
('Zhytomyr'),
('Zibo'),
('Zider Pass'),
('Zielona Góra'),
('Zig Zag'),
('Ziggarson'),
('Zigong'),
('Ziguinchor'),
('Zigzag'),
('Zigzag Covert'),
('Zihuatanejo'),
('Zillah'),
('Zinc'),
('Zinder'),
('Zinnia'),
('Zinzan'),
('Zion'),
('Zion Passage'),
('Zions'),
('Zions Clump'),
('Zions Loan'),
('Zionshill'),
('Zipaquirá'),
('Zircon'),
('Zixing'),
('Zlatoust'),
('Zoar'),
('Zobel'),
('Zodiac'),
('Zoe'),
('Zoes'),
('Zoes Place Baby Hospice'),
('Zoetermeer'),
('Zoffany'),
('Zone'),
('Zonguldak'),
('Zoons'),
('Zorbit'),
('Zorrina'),
('Zortech'),
('Zouch'),
('Zouche'),
('Zrenjanin'),
('Zuider Zee'),
('Zulla'),
('Zulu'),
('Zunyi'),
('Zura'),
('Zurich'),
('Zuwarah'),
('Zwolle'),
('Zürich');
-- Down
DELETE FROM Placename WHERE keyword LIKE 'z%';