-- Up
INSERT INTO "Placename"
("keyword")
VALUES
('Zachary Close'),
('Zachary Merton Community Hospital'),
('Zacharys Copse'),
('Zacrys Islands'),
('Zaggy Lane'),
('Zakopane Road'),
('Zama Street'),
('Zambesi Drive'),
('Zambesi Road'),
('Zambezie Drive'),
('Zambra Way'),
('Zamek Close'),
('Zamenhof Grove'),
('Zammit Crescent'),
('Zamor Crescent'),
('Zampa Road'),
('Zan Drive'),
('Zander Court'),
('Zander Grove'),
('Zander Road'),
('Zandi Road'),
('Zangwill Road'),
('Zannies Coppice'),
('Zante Close'),
('Zantmans Rock'),
('Zanzibar Wood'),
('Zara Close'),
('Zara Court'),
('Zara Way'),
('Zareba Clump'),
('Zaria Court'),
('Zarya Court'),
('Zawn a Bal'),
('Zawn Alley'),
('Zawn Alley Isle'),
('Zawn Brinny'),
('Zawn Bros'),
('Zawn Buzz and Gen'),
('Zawn Carve'),
('Zawn Core'),
('Zawn Daniel'),
('Zawn Duel'),
('Zawn Gamper'),
('Zawn Harry'),
('Zawn Kellys'),
('Zawn Lookout'),
('Zawn Organ'),
('Zawn Pedn Kei'),
('Zawn Peggy'),
('Zawn Pyg'),
('Zawn Quoits'),
('Zawn Reeth'),
('Zawn Rinny'),
('Zawn Rundle'),
('Zawn Shaggy'),
('Zawn Susan'),
('Zawn Tor'),
('Zawn Trevilley'),
('Zawn Turbis'),
('Zawn Vinoc'),
('Zawn Wells'),
('Zeal Ball Copse'),
('Zeal Brake'),
('Zeal Gully'),
('Zeal Head'),
('Zeal Hill'),
('Zeal House Copse'),
('Zeal Monachorum'),
('Zeal Plains'),
('Zeal Road'),
('Zeal Wood'),
('Zealand Avenue'),
('Zealand Close'),
('Zealand Drive'),
('Zealand Park'),
('Zealand Road'),
('Zealand Street'),
('Zealandia Road'),
('Zeals'),
('Zeals Garth'),
('Zeals Green Drive'),
('Zeals Knoll'),
('Zeals Rise'),
('Zeals Row'),
('Zebedee Close'),
('Zebon Copse'),
('Zebra Hill'),
('Zebu Crescent'),
('Zebudah Street'),
('Zechariah Wood'),
('Zeigfeld Court'),
('Zelah'),
('Zelah Hill'),
('Zelah Road'),
('Zelham Drive'),
('Zell House Copse'),
('Zembard Lane'),
('Zena Crescent'),
('Zena Place'),
('Zena Street'),
('Zenith'),
('Zenith Avenue'),
('Zenith Close'),
('Zenith Walk'),
('Zennor'),
('Zennor Cliff'),
('Zennor Grove'),
('Zennor Head'),
('Zennor Hill'),
('Zennor Road'),
('Zenoria Street'),
('Zephaniah Way'),
('Zephon Common'),
('Zephyr Close'),
('Zephyr Crescent'),
('Zermatt Close'),
('Zermatt Grove'),
('Zermatt Mount'),
('Zermatt Road'),
('Zermatt Street'),
('Zermatt Terrace'),
('Zeta Close'),
('Zeta Street'),
('Zeth Hill Lane'),
('Zetland'),
('Zetland Avenue'),
('Zetland Avenue North'),
('Zetland Close'),
('Zetland Crescent'),
('Zetland Drive'),
('Zetland Hunt'),
('Zetland Place'),
('Zetland Road'),
('Zetland Row'),
('Zetland Square'),
('Zetland Street'),
('Zetland Terrace'),
('Zeus Lane'),
('Zeus Road'),
('Zider Pass'),
('Zig Zag'),
('Zig Zag Road'),
('Zig-Zag Hill'),
('Zig-Zag Lane'),
('Ziggarson Wood'),
('Zigzag Covert'),
('Zigzag Wood'),
('Zillah Gardens'),
('Zinc Road'),
('Zinc Street'),
('Zinnia Close'),
('Zinnia Drive'),
('Zinnia Row'),
('Zinzan Street'),
('Zion Close'),
('Zion Drive'),
('Zion Hill'),
('Zion Lane'),
('Zion Passage'),
('Zion Place'),
('Zion Road'),
('Zion Row'),
('Zion Street'),
('Zion Terrace'),
('Zions Close'),
('Zions Clump'),
('Zions Loan'),
('Zionshill Copse'),
('Zircon Close'),
('Zoar'),
('Zoar Avenue'),
('Zoar Close'),
('Zoar Lane'),
('Zoar Place'),
('Zoar Road'),
('Zoar Street'),
('Zobel Close'),
('Zodiac Close'),
('Zodiac Drive'),
('Zoe Street'),
('Zoes Place Baby Hospice'),
('Zoes Wood'),
('Zoffany Street'),
('Zone Point'),
('Zoons Road'),
('Zorbit Mews'),
('Zorrina Close'),
('Zortech Avenue'),
('Zouch'),
('Zouch Avenue'),
('Zouch Close'),
('Zouch Farm Road'),
('Zouch Road'),
('Zouch Street'),
('Zouche Close'),
('Zouche Way'),
('Zuider Zee'),
('Zulla Road'),
('Zulu Bank'),
('Zulu Road'),
('Zulu Street'),
('Zura Avenue'),
('Zura Drive'),
('Zurich'),
('Zurich Avenue'),
('Zurich Close'),
('Zurich Gardens'),
('Zaanstad'),
('Zabol'),
('Zabrze'),
('Zacatecas'),
('Zagazig'),
('Zagreb'),
('Zahedan'),
('Zama'),
('Zamboanga City'),
('Zanjan'),
('Zanzibar City'),
('Zaoyang'),
('Zaozhuang'),
('Zapopan'),
('Zaporizhia'),
('Zaragoza'),
('Zaria'),
('Zarqa'),
('Zelenograd'),
('Zenica'),
('Zhalantun'),
('Zhangjiagang'),
('Zhangjiajie'),
('Zhangjiakou'),
('Zhangshu'),
('Zhangye'),
('Zhangzhou'),
('Zhanjiang'),
('Zhaodong'),
('Zhaoqing'),
('Zhaotong'),
('Zheleznodorozhny'),
('Zhengzhou'),
('Zhenjiang'),
('Zhongshan'),
('Zhoukou'),
('Zhoushan'),
('Zhucheng'),
('Zhuhai'),
('Zhuji'),
('Zhukovsky'),
('Zhumadian'),
('Zhuozhou'),
('Zhuzhou'),
('Zhytomyr'),
('Zibo'),
('Zielona Góra'),
('Zigong'),
('Ziguinchor'),
('Zihuatanejo'),
('Zinder'),
('Zipaquirá'),
('Zixing'),
('Zlatoust'),
('Zoetermeer'),
('Zonguldak'),
('Zrenjanin'),
('Zunyi'),
('Zürich'),
('Zuwarah'),
('Zwolle'),
('Zawn'),
('Zig Zag');

-- Down
DELETE FROM "Placename" WHERE "keyword" LIKE 'z%';
