-- Up
INSERT INTO Nationality (keyword)
VALUES
('Afghan'),
('Afghans'),
('African'),
('Africans'),
('Albanian'),
('Albanians'),
('Algerian'),
('Algerians'),
('American'),
('Americans'),
('Andorran'), 
('Andorrans'), 
('Angolan'),
('Angolans'),
('Anguillan'),
('Anguillans'),
('Antiguan'),
('Antiguans'),
('Argentine'),
('Argentines'),
('Armenian'),
('Armenians'),
('Australian'),
('Australians'),
('Austrian'), 
('Austrians'), 
('Azerbaijani'), 
('Azerbaijanis'), 
('Bahamian'),
('Bahamians'),
('Bahraini'),
('Bahrainis'),
('Bangladeshi'),
('Bangladeshis'),
('Barbadian'), 
('Barbadians'), 
('Barbudan'), 
('Barbudans'), 
('Belarusian'),
('Belarusians'),
('Belgian'),
('Belgians'),
('Belizean'),
('Belizeans'),
('Beninese'), 
('Bermudian'),
('Bermudians'),
('Bhutanese'),
('Bolivian'), 
('Bolivians'), 
('Bosnian'),
('Bosnians'),
('Botswanan'),
('Botswanans'),
('Brazilian'), 
('Brazilians'), 
('British'),
('Bruneian'),
('Bruneians'),
('Bulgarian'), 
('Bulgarians'), 
('Burkinan'),
('Burkinans'),
('Burmese'),
('Burundian'), 
('Burundians'), 
('Cambodian'),
('Cambodians'),
('Cameroonian'),
('Cameroonians'),
('Canadian'),
('Canadians'),
('Cape Verdean'), 
('Cape Verdeans'), 
('Cayman Islander'),
('Cayman Islanders'),
('Central African'),
('Central Africans'),
('Chadian'),
('Chadians'),
('Chilean'), 
('Chileans'), 
('Chinese'),
('Colombian'),
('Colombians'),
('Comoran'),
('Comorans'),
('Congolese'),
('Cook Islander'),
('Cook Islanders'),
('Cornish'),
('Corsican'),
('Costa Rican'),
('Costa Ricans'),
('Croatian'),
('Croatians'),
('Cuban'),
('Cubans'),
('Cymraes'),
('Cymro'),
('Cypriot'),
('Cypriots'),
('Czech'), 
('Danish'),
('Djiboutian'),
('Djiboutians'),
('Dominican'),
('Dominicans'),
('Dutch'), 
('Ecuadorean'),
('Ecuadoreans'),
('Egyptian'),
('Egyptians'),
('Emirati'), 
('Emiratis'), 
('English'),
('Equatorial Guinean'),
('Equatorial Guineans'),
('Eritrean'),
('Eritreans'),
('Estonian'), 
('Estonians'), 
('Ethiopian'), 
('Ethiopians'),
('Faroese'),
('Fijian'),
('Fijians'),
('Filipino'),
('Filipinos'),
('Finnish'),
('Finns'),
('French'), 
('Gabonese'),
('Gambian'),
('Gambians'),
('Georgian'),
('Georgians'),
('German'),
('Germans'),
('Ghanaian'), 
('Ghanaians'), 
('Gibraltarian'),
('Gibraltarians'),
('Greek'),
('Greeks'),
('Greenlandic'),
('Greenlander'),
('Greenlanders'),
('Grenadian'), 
('Grenadians'), 
('Guamanian'),
('Guamanians'),
('Guatemalan'),
('Guatemalans'),
('Guinea Bissaun'), 
('Guinean'),
('Guyanese'), 
('Haitian'),
('Hawaiian'),
('Herzegovinan'),
('Himalayan'),
('Honduran'),
('Hungarian'), 
('Hungarians'), 
('Icelandic'),
('Icelander'),
('Icelanders'),
('Indian'),
('Indians'),
('Indonesian'),
('Indonesians'),
('Iranian'),
('Iranians'),
('Iraqi'), 
('Iraqis'), 
('Irish'),
('Israeli'),
('Israelis'),
('Italian'),
('Italians'),
('Ivorian'), 
('Ivorians'), 
('Jamaican'),
('Jamaicans'),
('Japanese'),
('Jewish'),
('Jordanian'), 
('Jordanians'), 
('Kazakh'),
('Kenyan'),
('Kenyans'),
('Kittitian'),
('Kiribatian'),
('Korean'),
('Koreans'),
('Kosovan'),
('Kosovans'),
('Kuwaiti'),
('Kuwaitis'),
('Kyrgyz'), 
('Lao'),
('Latvian'),
('Latvians'),
('Lebanese'),
('Liberian'),
('Liberians'),
('Libyan'), 
('Libyans'), 
('Liechtensteiner'),
('Lithuanian'),
('Luxembourger'), 
('Macanese'),
('Macedonian'),
('Macedonians'),
('Malagasy'),
('Malawian'), 
('Malawians'),
('Malaysian'),
('Malaysians'),
('Maldivian'),
('Maldivians'),
('Malian'),
('Maltese'), 
('Marshallese'),
('Martiniquais'),
('Mauritanian'),
('Mauritanians'),
('Mauritian'), 
('Mauritians'), 
('Mexican'),
('Mexicans'),
('Micronesian'),
('Micronesians'),
('Moldovan'),
('Moldovans'),
('Monegasque'), 
('Mongolian'),
('Mongolians'),
('Montenegrin'),
('Montenegrins'),
('Montserratian'),
('Moroccan'), 
('Moroccans'), 
('Mosotho'),
('Mozambican'), 
('Mozambicans'), 
('Namibian'),
('Namibians'),
('Nauruan'),
('Nauruans'),
('Nepalese'),
('New Zealander'), 
('New Zealanders'), 
('Nicaraguan'),
('Nicaraguans'),
('Nigerian'),
('Nigerians'),
('Nigerien'),
('Niuean'), 
('Norwegian'), 
('Norwegians'), 
('Omani'), 
('Omanis'), 
('Pakistani'),
('Pakistanis'),
('Palauan'),
('Palauans'),
('Palestinian'),
('Palestinians'),
('Panamanian'), 
('Panamanians'), 
('Papua New Guinean'),
('Papua New Guineans'),
('Paraguayan'),
('Paraguayans'),
('Persian'),
('Persians'),
('Peruvian'), 
('Peruvians'), 
('Pitcairn Islander'),
('Pitcairn Islanders'),
('Polish'),
('Portuguese'),
('Prydeinig'), 
('Puerto Rican'), 
('Puerto Ricans'), 
('Qatari'),
('Qataris'),
('Romanian'),
('Romanians'),
('Russian'),
('Russians'),
('Rwandan'), 
('Rwandans'), 
('Salvadorean'),
('Salvadoreans'),
('Sammarinese'),
('Samoan'),
('Samoans'),
('Sao Tomean'), 
('Sao Tomeans'), 
('Saudi Arabian'),
('Saudi Arabians'),
('Scandanavian'),
('Scottish'),
('Scots'),
('Senegalese'),
('Serbian'), 
('Serbians'), 
('Sierra Leonean'),
('Sierra Leoneans'),
('Singaporean'), 
('Singaporeans'), 
('Slovak'),
('Slovaks'),
('Slovenian'),
('Slovenians'),
('Solomon Islander'),
('Solomon Islanders'),
('Somali'), 
('Somalis'), 
('Spanish'),
('Spaniard'),
('Spaniards'),
('Sri Lankan'),
('Sri Lankans'),
('St Helenian'),
('St Lucian'), 
('Sudanese'),
('Surinamese'),
('Swazi'),
('Swazis'),
('Swedish'), 
('Swedes'), 
('Swiss'),
('Syrian'), 
('Syrians'), 
('Taiwanese'),
('Tajik'),
('Tajiks'),
('Tanzanian'),
('Tanzanians'),
('Thai'),
('Tibetan'),
('Tibetans'),
('Timorese'),
('Togolese'), 
('Tongan'),
('Tongans'),
('Trinidadian'),
('Tristanian'),
('Tunisian'), 
('Tunisians'), 
('Turkish'),
('Turks'),
('Turkmen'),
('Turks and Caicos Islander'), 
('Tuvaluan'), 
('Tuvaluans'), 
('Ugandan'),
('Ukrainian'),
('Ukrainians'),
('Uruguayan'),
('Uruguayans'),
('Uzbek'), 
('Uzbeks'), 
('Vatican citizen'),
('Vatican citizens'),
('Vanuatuan'),
('Vanuatuans'),
('Venezuelan'), 
('Venezuelans'), 
('Vietnamese'),
('Vincentian'), 
('Vincentians'), 
('Wallisian'),
('Wallisians'),
('Welsh'), 
('Yemeni'), 
('Yemenis'), 
('Zambian'),
('Zambians'),
('Zimbabwean'),
('Zimbabweans'),
('Zulu'),
('Zulus');
-- Down
DELETE FROM "Nationality";