-- Up
INSERT INTO Skip (keyword)
VALUES
('A batch'),
('A bath'),
('A battle'),
('A bill'),
('A black belt'),
('A black hole'),
('A boulder'),
('A bow'),
('A buddy'),
('A cash'),
('A chance'),
('A childs'),
('A christian'),
('A christmas'),
('A clause'),
('A deal'),
('A deep pit'),
('A dot'),
('A fairer'),
('A flurry'),
('A gang'),
('A glass'),
('A gorge'),
('A greater'),
('A green'),
('A guy'),
('A heap'),
('A jan'),
('A june'),
('A king'),
('A knock'),
('A lamb'),
('A little less'),
('A little long'),
('A little rough'),
('A loner'),
('A long road'),
('A long walk'),
('A long way'),
('A lower exchange'),
('A mark'),
('A page'),
('A pat'),
('A peculiar'),
('A penny'),
('A plant'),
('A postal'),
('A pound'),
('A may'),
('A mini'),
('A new house'),
('A ridge'),
('A rod'),
('A savanna'),
('A scolding'),
('A shepherd'),
('A smaller'),
('A spike'),
('A stellar'),
('A steep'),
('A story'),
('A tee'),
('A tennis court'),
('A thorn'),
('A walker'),
('A way'),
('A windy'),
('A wise'),
('Accompany the exchange'),
('Achilles heel'),
('Ad hoc'),
('Addr'),
('Affiliated boards'),
('After the court'),
('Against the wall'),
('Akin to'),
('Albeit smaller'),
('All roses'),
('All stripes'),
('All the pieces'),
('All the points'),
('All the wood'),
('All tier'),
('All westward'),
('Alls well'),
('Alpha male'),
('Along the path'),
('Also'),
('Also rose'),
('Also wear'),
('Always wear'),
('Am holding'),
('Am leary'),
('Amber warning'),
('Amber warnings'),
('Among young'),
('An april'),
('An over'),
('Analyze'),
('And bonds'),
('And dizzy'),
('And green'),
('And hedging'),
('And holding'),
('And snow'),
('And trucks'),
('And mingle'),
('Any deal'),
('Any page'),
('Any pressing'),
('Any reading'),
('Any winnings'),
('Another chance'),
('Appeal court'),
('Approx'),
('Ardent in'),
('Are angels'),
('Are down'),
('Are greater'),
('Are holding'),
('Are loving'),
('Are low'),
('Are reading'),
('Are the key'),
('Are two ways'),
('Are under way'),
('Armor piercing'),
('Armour piercing'),
('Arts majors'),
('As a little'),
('As low as'),
('As well'),
('Asap'),
('Ascii'),
('Asthma'),
('At a march'),
('At the ball'),
('At the borders'),
('At the course'),
('At the court'),
('At the heart'),
('At the helm'),
('At the front'),
('At the mercy'),
('At the spa'),
('Audio channels'),
('Autumn camp'),
('Autumn season'),
('Back corner'),
('Back down'),
('Back in'),
('Back to back'),
('Bad aims'),
('Bad bill'),
('Bad buy'),
('Bad captain'),
('Bad chancellor'),
('Bad charity'),
('Bad christmas'),
('Bad church'),
('Bad clues'),
('Bad college'),
('Bad cook'),
('Bad cooks'),
('Bad day'),
('Bad faith'),
('Bad farewell'),
('Bad grace'),
('Bad guest'),
('Bad guy'),
('Bad heart'),
('Bad june'),
('Bad lady'),
('Bad lord'),
('Bad love'),
('Bad minister'),
('Bad piece'),
('Bad president'),
('Bad price'),
('Bad prince'),
('Bad professor'),
('Bad school'),
('Bad story'),
('Bad summer'),
('Bad summers'),
('Bad university'),
('Bad will'),
('Bad winter'),
('Balk at'),
('Ballsy'),
('Bank of england'),
('Bankruptcy'),
('Banner reading'),
('Bark some'),
('Bashed pots'),
('Battle re-enactments'),
('Be fearing'),
('Be finely'),
('Be holding'),
('Be the key'),
('Bearer of'),
('Beautiful flowers'),
('Been barefoot'),
('Been down'),
('Been loosely'),
('Before christmas'),
('Before holding'),
('Began tembling'),
('Beta test'),
('Beta testing'),
('Big deal'),
('Big guy'),
('Big kitty'),
('Bigger gap'),
('Bird seed'),
('Black beans'),
('Black box'),
('Black eye'),
('Black high'),
('Black labrador'),
('Black market'),
('Black monday'),
('Black olives'),
('Blah'),
('Blob'),
('Blowjob'),
('Blue eyes'),
('Blunt instrument'),
('Blunt refusal'),
('Blur'),
('Bodily harm'),
('Boils down'),
('Bollox'),
('Bona fide'),
('Bond villain'),
('Bonus miles'),
('Boob'),
('Book villain'),
('Booth at'),
('Borders on'),
('Bottles of'),
('Bottom line'),
('Bows out'),
('Box office'),
('Braai'),
('Brace for'),
('Breadth'),
('Break down'),
('Breaks down'),
('Bridal showers'),
('Bride and groom'),
('Brings a'),
('Brings an'),
('Britain tidy'),
('British airways'),
('British ambassador'),
('British towns'),
('Broad gun'),
('Broad range'),
('Brotherhood of'),
('Brown bag'),
('Buffet'),
('Bundle of'),
('Burn bridges'),
('Bus fare'),
('But will'),
('Buy back'),
('By chance'),
('By compass'),
('By courier'),
('By smaller'),
('Cake tin'),
('Calc'),
('Caller id'),
('Camp at'),
('Camp by'),
('Camp will'),
('Camps are'),
('Card holder'),
('Cartel heartland'),
('Cash back'),
('Cash trading'),
('Cavalier attitude'),
('Cctv'),
('Celeb'),
('Centers to'),
('Central bank'),
('Central banks'),
('Challenge harder'),
('Challenging pace'),
('Chamber of'),
('Chambers of commerce'),
('Change the connection'),
('Change the statutes'),
('Chance of'),
('Chinese wall'),
('Christian Democratic'),
('City centre'),
('City of'),
('Climate change'),
('Close down'),
('Clothes hanger'),
('Co ed'),
('Cold winters'),
('Coming autumn'),
('Coming spring'),
('Coming weeks'),
('Common crimes'),
('Common practice'),
('Confer with'),
('Contrasted sharply'),
('Corf'),
('Corporate bonds'),
('Cost center'),
('Cost centre'),
('Couldnt'),
('County level'),
('Court appearance'),
('Court case'),
('Court for'),
('Court heard'),
('Court judge'),
('Cover story'),
('Cranberry sauce'),
('Crimes against'),
('Crystal clear'),
('Christmas day'),
('Cross median'),
('Cross roads'),
('Crown jewel'),
('Crown jewels'),
('Cssu'),
('Current median'),
('Cutoff'),
('Cutting a'),
('Cutting an'),
('Cutting back'),
('Cutting edge'),
('Cutting the'),
('Cyborg'),
('Dairy farmer'),
('Dairy seller'),
('Data grabber'),
('Datix'),
('Dawn of time'),
('Day fall'),
('De facto'),
('Deal by'),
('Deal is'),
('Deal making'),
('Deal negotiation'),
('Deal now'),
('Deal or'),
('Deal should'),
('Deal that'),
('Deal to'),
('Deal transfer'),
('Deal with'),
('Deal would'),
('Dean of'),
('Debts'),
('Deems appropriate'),
('Deep snow'),
('Defra'),
('Demand peaks'),
('Diaphragm'),
('Different story'),
('Dildo'),
('Dining hall'),
('District judge'),
('Dont'),
('Dont wanna'),
('Do the rest'),
('Docking station'),
('Does'),
('Doesn'),
('Dolby digital'),
('Domino effect'),
('Doorbell rang'),
('Double chevron'),
('Doubts'),
('Down before'),
('Down here'),
('Down memory lane'),
('Down the drain'),
('Down the street'),
('Down the valley'),
('Downtrod'),
('Draws for'),
('Draws of'),
('Drew large'),
('Drill down'),
('Drive down'),
('Drive east'),
('Drive north'),
('Drive south'),
('Drive west'),
('Drones'),
('E mails'),
('Each camp'),
('Each day'),
('Each lay'),
('Each purchase'),
('Each side'),
('Each view'),
('Each way'),
('Each westward'),
('Early april'),
('Early june'),
('Early may'),
('Earner for'),
('Ebay'),
('Edge over'),
('Electricity deal'),
('Emblazon'),
('Emmy nomination'),
('End of April'),
('End of Jan'),
('End of June'),
('End of May'),
('End of the month'),
('End of the quarter'),
('End of the year'),
('Ended april'),
('Ended jan'),
('Ended june'),
('Ended may'),
('Enough booze'),
('Escape hatch'),
('Et al'),
('Eve of'),
('Even greater'),
('Even harder'),
('Evenly among'),
('Every angle'),
('Every autumn'),
('Every kitchen'),
('Ex parte'),
('Exec'),
('Exhibit hall'),
('Experience gross'),
('Fair deal'),
('Fairy tale'),
('Faith in'),
('Fall back'),
('Fall from grace'),
('Fall into line'),
('Fall over'),
('Fall well'),
('Fallen angels'),
('Family reading'),
('Faqs'),
('Fast pace'),
('Fell back'),
('Fell ill'),
('Fell over'),
('Fell to its'),
('Ferry terminal'),
('Few weeks'),
('Field day'),
('Fields from'),
('Fields in'),
('Field specialist'),
('Fighting chance'),
('Final weeks'),
('Fine art'),
('Fine day'),
('Finished april'),
('Finished jan'),
('Finished june'),
('Finished may'),
('First blush'),
('First brushes'),
('First dibs'),
('Fixed deal'),
('Flak'),
('Flat colander'),
('Flat pack'),
('Fleet manager'),
('Fleet of'),
('Flurry of'),
('Flying back'),
('Folio'),
('Follow the steps'),
('For biz'),
('For christmas'),
('For greater'),
('For the front'),
('For the joint'),
('For the ride'),
('Foray into'),
('Frank take'),
('French doors'),
('French windows'),
('From'),
('Front page'),
('FTSE 100'),
('Full and frank'),
('Full page'),
('Full story'),
('Fun deal'),
('Future deal'),
('Fuzzy'),
('Gaol'),
('Garden box'),
('Garners respect'),
('Gargantuan'),
('Gas deal'),
('Gas fields'),
('Gave way'),
('GDPR'),
('Gene edited'),
('Gene therapy'),
('General ledger'),
('Generating plant'),
('German shepherd'),
('Get under way'),
('Getting flack'),
('Giddy hope'),
('Given greater'),
('Goes back'),
('Goes sour'),
('Goes through'),
('Goes to the'),
('Goes way'),
('Goes well'),
('Goings on'),
('Good guy'),
('Good lord'),
('Got underway'),
('Govt'),
('Grace period'),
('Grant agreement'),
('Grant agreements'),
('Grant request'),
('Grant requests'),
('Grant similar'),
('Graphic novel'),
('Graphic novels'),
('Great deal'),
('Great guy'),
('Great healer'),
('Greater detail'),
('Greater good'),
('Greater than'),
('Greater value'),
('Green earth'),
('Green energy'),
('Green light'),
('Green power'),
('Grew up reading'),
('Gross profit'),
('Gross profits'),
('Hadnt'),
('Halfway point'),
('Halfway through'),
('Hanky panky'),
('Have heard'),
('Have snow'),
('Have the plain'),
('Have won'),
('He may'),
('He sang'),
('He will'),
('He won'),
('Head end'),
('Head lice'),
('Head of rugby'),
('Head office'),
('Heard back'),
('Heard how'),
('Heart goes'),
('Heavyweight boxer'),
('Hee hee'),
('Helio'),
('High building'),
('High court'),
('High level'),
('High plateau'),
('High price'),
('High school'),
('High speed'),
('High standards'),
('Highest faith'),
('His view'),
('Hit the fan'),
('Ho ho ho'),
('Holding a'),
('Holding back'),
('Holding company'),
('Holding companies'),
('Holding fund'),
('Holding funds'),
('Holding of'),
('Holding off'),
('Holding period'),
('Holding the'),
('Holding up'),
('Holding us'),
('Holdings completely'),
('Hollering like'),
('Home page'),
('Home town'),
('Homing in'),
('Honest and frank'),
('Hope all'),
('Hope everything'),
('Hope everythings'),
('Hope for'),
('Hope of'),
('Hope that'),
('Hope to'),
('Hope we'),
('Hope you'),
('Hope your'),
('Hopping around'),
('Hot cross buns'),
('Hot ember'),
('Hover around'),
('Hover at'),
('How bad'),
('How close'),
('How could'),
('How far'),
('How long'),
('How peculiar'),
('How will'),
('Huddle with'),
('Hung out'),
('Hunt down'),
('Hunts in the'),
('Huge deal'),
('Hypertext'),
('I hope'),
('I lay'),
('I may'),
('I miss'),
('I wear'),
('I will'),
('Ideas forth'),
('In april'),
('In bars'),
('In bonds'),
('In building'),
('In earnest'),
('In flux'),
('In jan'),
('In june'),
('In may'),
('In ruins'),
('In summer'),
('In the autumn'),
('In the bush'),
('In the corner'),
('In the end'),
('In the forehead'),
('In the forest'),
('In the front'),
('In the greater'),
('In the heart'),
('In the joint'),
('In the light'),
('In the loop'),
('In the park'),
('In the run'),
('In the rush'),
('In the rut'),
('In the spa'),
('In the spot'),
('In the spring'),
('In the still'),
('In the walk'),
('In the wood'),
('In the works'),
('Info'),
('Information booths'),
('International women'),
('Into'),
('Is geared to'),
('Is idle'),
('Is loving'),
('Is lower'),
('Is reading'),
('Is under way'),
('Issue bonds'),
('It may'),
('It will'),
('Its bonds'),
('Jabs at'),
('Joins with'),
('Joint boards'),
('Jot those'),
('Junk bonds'),
('Keen to'),
('Keep faith'),
('Key day'),
('Kickoff meeting'),
('King and queen'),
('Kitchen counter'),
('Lane judges'),
('Last april'),
('Last beam'),
('Last jan'),
('Last june'),
('Last may'),
('Last autumn'),
('Last chance'),
('Last christmas'),
('Last easter'),
('Late april'),
('Late jan'),
('Late june'),
('Late may'),
('Law professor'),
('Lay eggs'),
('Lay off'),
('Lay out'),
('Leaks row'),
('Leap of'),
('Left the trees'),
('Left wing'),
('Left winger'),
('Less common'),
('Less rich'),
('Level playing field'),
('Lgbt'),
('Light trucks'),
('Like to pass'),
('Local deal'),
('Locked down'),
('Lockjaw'),
('Locks are'),
('Locks have'),
('Long beard'),
('Long haul'),
('Long range'),
('Longer term'),
('Losing faith'),
('Lovers on'),
('Loves reading'),
('Low cost'),
('Low daily'),
('Low ebb'),
('Low income'),
('Low of'),
('Low price'),
('Low rank'),
('Low ranking'),
('Lowest rung'),
('Lows expected'),
('Lows in'),
('Lows of'),
('Lower christmas'),
('Lower house'),
('Lower level'),
('Made camp'),
('Mailto'),
('Main office'),
('Main page'),
('Major banks'),
('March or april'),
('March through'),
('Marches mark'),
('Marches to'),
('Marches took'),
('Mark discrepancy'),
('Mark it'),
('Mark ups'),
('Mark your'),
('Market approach'),
('Market hedges'),
('Market price'),
('Market rate'),
('Market side'),
('Marks for'),
('Marks of'),
('Marks & spencer'),
('Marks and spencer'),
('Max number'),
('Max numbers'),
('Max rate'),
('Max rates'),
('Maxi'),
('May i'),
('May in'),
('May add'),
('May already'),
('May also'),
('May apply'),
('May be'),
('May come'),
('May concern'),
('May contain'),
('May have'),
('May just'),
('May not'),
('May now'),
('May only'),
('May or may not'),
('May park at'),
('May park in'),
('May park on'),
('May potentially'),
('May show'),
('May soon'),
('May sue'),
('May the'),
('May together'),
('May unduly'),
('May vary'),
('May well'),
('May without'),
('Mayor of London'),
('Mcpj'),
('Meager credit'),
('Meat packer'),
('Median age'),
('Merger deal'),
('Messing things'),
('Messing up'),
('Metre high'),
('Metre higher'),
('Metre lower'),
('Mid jan'),
('Mid june'),
('Mid march'),
('Mid may'),
('Middle school'),
('Midi'),
('Mini'),
('Monte carlo simulation'),
('Month of april'),
('Month of may'),
('Month of jan'),
('Month of june'),
('More miles'),
('More pressing'),
('More weeks'),
('Mountain man'),
('Much smaller'),
('Much snow'),
('Muddle through'),
('Murky brown'),
('Muscle strands'),
('My calendar'),
('My heart'),
('My lips'),
('Nailing down'),
('Narco'),
('Nazi'),
('Nearby camp'),
('Next'),
('Next april'),
('Next autumn'),
('Next jan'),
('Next june'),
('Next may'),
('New bill'),
('New bonds'),
('new deal'),
('New lows'),
('New snow'),
('New way to'),
('News story'),
('Nicer guy'),
('Ninja'),
('Ninjas'),
('No biggie'),
('Noncombat'),
('Normal pace'),
('Northern city'),
('Northern town'),
('Northern village'),
('Not grant'),
('Notch above'),
('Notch below'),
('Of bonds'),
('Of cheddar'),
('Of court'),
('Of fries'),
('Of greater'),
('Of hope'),
('Of jan'),
('Of june'),
('Of march'),
('Of may'),
('Of miles'),
('Of plant'),
('Of summers'),
('Of the ashes'),
('Of the ball'),
('Of the end'),
('Of the joint'),
('Of the osprey'),
('Of the rise'),
('Of weeks'),
('Off the front'),
('Off the hook'),
('Oh my'),
('Oh well'),
('Oil fields'),
('Okay'),
('Old gal'),
('Old guy'),
('Old couple'),
('On black'),
('On boards'),
('On deal'),
('On page'),
('On the corner'),
('On the downside'),
('On the hill'),
('On the hook'),
('On the island'),
('On the lookout'),
('On the moon'),
('On the rise'),
('On the sly'),
('On the stack'),
('Once mighty'),
('One chance'),
('One page'),
('One way'),
('Onto the island'),
('Only chance'),
('Onto'),
('Opening paragraph'),
('Option grant'),
('Orca'),
('Original deal'),
('Oscar nominated'),
('Oscar winning'),
('Other postal'),
('Ouija board'),
('Ouija boards'),
('Our chances'),
('Outgo'),
('Outswam'),
('Oval office'),
('Over a'),
('Over riding'),
('Over steep'),
('Over stepping'),
('Over the border'),
('Over the counter'),
('Over the course of'),
('Over the last'),
('Over weeks'),
('Overawe'),
('Overmix'),
('Overnight lows'),
('Pace through'),
('Package deal'),
('Page at'),
('Page on'),
('Page to'),
('Page using'),
('Page version'),
('Pan racial faith'),
('Parks at'),
('Parks by'),
('Parks near'),
('Parks on'),
('Passersby'),
('Past weeks'),
('Pasta alfredo'),
('Pastures for'),
('Patches of'),
('Pay down the'),
('Payee'),
('Payoff'),
('Pea shoots'),
('Peak weeks'),
('Pearl Harbor'),
('Pelvic'),
('Pesky'),
('Per page'),
('Per pound'),
('Percent bonds'),
('Permanently ground'),
('Personal story'),
('Perv'),
('Phone bill'),
('Pinch on'),
('Pinch the'),
('Pinching yourself'),
('Piles of'),
('Place down here'),
('Place down there'),
('Plain vanilla'),
('Plaintext'),
('Plant pots'),
('Plant will'),
('Plant volume'),
('Planting'),
('Plateau that'),
('Play rugby'),
('Playing rugby'),
('Plays rugby'),
('Polling booth'),
('Polyp'),
('Port of call'),
('Portion of chips'),
('Ports docks'),
('Positive story'),
('Pound sterling'),
('Powder snow'),
('Power plant'),
('Powers to'),
('Prefab'),
('Prelim'),
('Premix'),
('President level'),
('Pretext'),
('Price fell'),
('Price in'),
('Price may'),
('Price ramping'),
('Price swap'),
('Prima facie'),
('Prior deal'),
('Pro rata'),
('Pronoun'),
('Psych'),
('Psyche'),
('Psycho'),
('Public Health England'),
('Pull the ball'),
('Quick halt'),
('Quick pace'),
('Quota'),
('Ramrod'),
('Rapid halt'),
('Rapid pace'),
('Rash of'),
('Reached the dock'),
('Read the joint'),
('Reading about'),
('Reading books'),
('Reading excerpts'),
('Reading from'),
('Reading her'),
('Reading his'),
('Reading my'),
('Reading the'),
('Reading their'),
('Reading this'),
('Reading your'),
('Rebel song'),
('Recent weeks'),
('Redux'),
('Reform bill'),
('Related fields'),
('Remix'),
('Repo'),
('Resculpt'),
('Resolve disputes'),
('Resow'),
('Revenue bonds'),
('Revenue rose'),
('Rich fields'),
('Rich premium'),
('Rich premiums'),
('Rips up'),
('Risky'),
('Road closure'),
('Road closures'),
('Road down to'),
('Rock stars'),
('Rod for'),
('Rod to'),
('Rode that'),
('Rodeo'),
('Roller coaster'),
('Rollmop'),
('Roman catholic'),
('Romp through'),
('Rose almost'),
('Rose by'),
('Rose marginally'),
('Rose slightly'),
('Rose to'),
('Rota'),
('Round trip'),
('Round trips'),
('Row over'),
('Royal Bank of Scotland'),
('Rrom'),
('Rsvp'),
('Rugby club'),
('Rugby clubs'),
('Rugby football'),
('Rugby league'),
('Rugby player'),
('Rugby players'),
('Rugby sevens'),
('Rugby union'),
('Run down'),
('Rushed to'),
('Rushing into'),
('Rushing to'),
('Rushing water'),
('Russian roulette'),
('Sail from'),
('Sail out'),
('Sail to'),
('Sales price'),
('Salt cavern'),
('Same page'),
('Sang about'),
('Santa claus'),
('Satisfy'),
('Satnav'),
('Sea wall'),
('Second reading'),
('Secondary school'),
('Security holdings'),
('Sellers of'),
('Sellers to'),
('Sellers who'),
('Selling bonds'),
('Semi'),
('Send prices down'),
('Sensei'),
('Serve burgers'),
('Set forth'),
('Set to batter'),
('Settle there'),
('Settle these'),
('Several weeks'),
('Sharp decline'),
('Sharp discount'),
('Sharp drop'),
('Sharp fall'),
('Sharp falls'),
('Sharp guy'),
('Sharp turn'),
('Sharpness of'),
('Shares rose'),
('Sharper than'),
('She may'),
('She sang'),
('She will'),
('She won'),
('Shoo in'),
('Shoring up'),
('Short circuit'),
('Short term'),
('School day'),
('Sift through'),
('Silver stars'),
('Similar to how'),
('Since April'),
('Sit idle'),
('Slight chance'),
('Slimming pills'),
('Slow pace'),
('Sluggish pace'),
('Small cliff'),
('Smaller than'),
('Snow machine'),
('Snow mobile'),
('Subtext'),
('Spanning the'),
('Sparerib'),
('Speed bumps'),
('Spelling mistake'),
('Spelling mistakes'),
('Spilling it'),
('Spinoff'),
('Splash page'),
('Spurs opposition'),
('Some beers'),
('Some milder'),
('Southern city'),
('Southern town'),
('Southern village'),
('Summary page'),
('Summed up'),
('Summer day'),
('Summer deal'),
('Summer styles'),
('Sunrise from'),
('Suspension bridges'),
('Stack of'),
('Stacks of'),
('Stakes in'),
('Standby'),
('Standoff'),
('Star quest'),
('Stars are'),
('Start of April'),
('Start of Jan'),
('Start of June'),
('Start of May'),
('Steel foundry'),
('Steep costs'),
('Stepping back'),
('Still under way'),
('Stock holdings'),
('Stocking stuffers'),
('Stocks close higher'),
('Stocks close lower'),
('Stocks fell'),
('Stocks rose'),
('Stone cold'),
('Story about'),
('Stripe down'),
('Street marches'),
('Stylish way'),
('Sue you'),
('Symbol'),
('Taken the liberty'),
('Takeoff'),
('Talc'),
('Taming the'),
('Tarmac'),
('Tax havens'),
('Team won'),
('Techno'),
('Teletext'),
('Television channels'),
('Telly gold'),
('Term deal'),
('Tesco'),
('Text'),
('Texts'),
('Than'),
('That clause'),
('That creates'),
('That deal'),
('That guy'),
('That joins'),
('That nodal'),
('That page'),
('That sees'),
('That song'),
('That the spot'),
('That the walk'),
('That van'),
('That were pressing'),
('The alter'),
('The april'),
('The autumn'),
('The ball is'),
('The bank of'),
('The bank to'),
('The battle'),
('The beam'),
('The bees'),
('The bill'),
('The blithe'),
('The bloc'),
('The bonds'),
('The boulder'),
('The bow'),
('The buffalo'),
('The calendar'),
('The calls to'),
('The camp'),
('The cash'),
('The cashier'),
('The chance'),
('The childs'),
('The clouds'),
('The connection is'),
('The copier'),
('The course of'),
('The course that'),
('The couch'),
('The court of'),
('The court to'),
('The court will'),
('The christmas'),
('The crew'),
('The deal'),
('The dial in'),
('The easter'),
('The edge of'),
('The eggs'),
('The elbow'),
('The fleet'),
('The ferry'),
('The folders specified'),
('The front of'),
('The front office'),
('The front page'),
('The front room'),
('The gang'),
('The golf'),
('The gorge'),
('The grant'),
('The grass'),
('The greater'),
('The guy'),
('The hall to'),
('The heavenly'),
('The heck'),
('The hem'),
('The high crest'),
('The high end'),
('The high street'),
('The higher end'),
('The hope'),
('The hood'),
('The land is'),
('The light at'),
('The light load'),
('The loop on'),
('The low end'),
('The lower end'),
('The jan'),
('The jedi'),
('The june'),
('The key element'),
('The key ingredient'),
('The key is'),
('The key issue'),
('The key to'),
('The king'),
('The kitchen'),
('The main front'),
('The march'),
('The mark'),
('The may'),
('The max'),
('The miles'),
('The moon'),
('The new house'),
('The new site'),
('The pace'),
('The page'),
('The peak hours'),
('The peculiar'),
('The piece between'),
('The plain truth'),
('The plant'),
('The plant would'),
('The point is'),
('The point that'),
('The points which'),
('The pool'),
('The puncher'),
('The prospect of'),
('The prospect that'),
('The rally seemed'),
('The range of'),
('The reins'),
('The rest of'),
('The retreat was'),
('The rise in'),
('The roads'),
('The royal bank'),
('The run of'),
('The seashore'),
('The sellers'),
('The short time'),
('The snow'),
('The swallow'),
('The song'),
('The sound of'),
('The south side'),
('The spring'),
('The spur of'),
('The stakes are'),
('The stock down'),
('The story'),
('The summers'),
('The sun'),
('The tally'),
('The tenor'),
('The tanking'),
('The ticker'),
('The upper hand'),
('The usher'),
('The van'),
('The verge of'),
('The waiter'),
('The walk goes'),
('The walk to'),
('The way'),
('The weeks'),
('The west side'),
('The whack'),
('The winter'),
('The winters'),
('The works of'),
('Their borders'),
('Then the forest'),
('There will'),
('They'),
('They may'),
('They sang'),
('They will'),
('This april'),
('This deal'),
('This grant'),
('This guy'),
('This page'),
('This jan'),
('This june'),
('This may'),
('This autumn'),
('This christmas'),
('This childs'),
('This easter'),
('This rod'),
('This story'),
('This sun'),
('This traverse'),
('This will'),
('This won'),
('Thou'),
('Through the model'),
('Thud'),
('Ticket booth'),
('Tier that'),
('Tightwad'),
('TikTok'),
('Tipper lorry'),
('Tiptoes'),
('To block the'),
('To camp'),
('To chance'),
('To clink'),
('To grant'),
('To hoard'),
('To lavish'),
('To lodge'),
('To quell'),
('To march'),
('To mark the'),
('To pay down'),
('To plant'),
('To plow'),
('To prosper'),
('To rebut'),
('To rout'),
('To stoke'),
('To tailor'),
('To the bar'),
('To the edge'),
('To the forest'),
('To the heart'),
('To the new common'),
('To the joint'),
('To the peak'),
('To the plant'),
('To the point in'),
('To the point when'),
('To the point where'),
('To the rest'),
('To the round'),
('To tilt'),
('To tote'),
('To uphold'),
('To vent'),
('To wear'),
('To withold'),
('Told callers'),
('Tonic for'),
('Too bad'),
('Too low'),
('Top level'),
('Top line'),
('Top notch'),
('Top story'),
('Top will'),
('Tore her'),
('Tore his'),
('Tore my'),
('Tore out'),
('Towns battle'),
('Trade credit'),
('Trade credits'),
('Trade deal'),
('Tradeoff'),
('Trading deal'),
('Trading side'),
('Tree saplings'),
('Trial court'),
('Trickle out'),
('Trickle to'),
('Truly frank'),
('Trustworthy basis'),
('Tumble dryer'),
('Turned the corner'),
('Tut over'),
('Twat'),
('Two way'),
('Uncommon gene'),
('Under house'),
('Under way on'),
('Under way to'),
('Under way with'),
('Unesco'),
('Unjam'),
('Until autumn'),
('Until spring'),
('Untrod'),
('Unzip'),
('Upper chamber'),
('Vantage point'),
('Vehicle fleet'),
('Vessels'),
('Via courier'),
('Vice versa'),
('Video'),
('Virgin atlantic'),
('Voting booth'),
('Walk back'),
('Walk down'),
('walk way'),
('Walked back'),
('Walked down'),
('Walls above'),
('Warns of'),
('Was down'),
('Was idle'),
('Was stolen'),
('Was very low'),
('Wash in'),
('Watch in dismay'),
('Water bottles'),
('Way round'),
('We drew'),
('We hope'),
('We hung'),
('We may'),
('We miss'),
('We will'),
('Wear help them'),
('Wear what'),
('Wear white'),
('Web page'),
('Well and'),
('Well over'),
('Well underway'),
('Week low'),
('Weeks ago'),
('Weeks of'),
('Weeks to'),
('Were down'),
('Were low'),
('Were under way'),
('Wetter than'),
('WhatsApp'),
('When will'),
('Where grass'),
('Which'),
('Which borders'),
('Which wood'),
('While sellers'),
('Who love'),
('Who styles'),
('Who will'),
('Who won'),
('Wholesale sellers'),
('Wild card'),
('Wild goose'),
('Will also'),
('Will in effect'),
('Will likely'),
('Will necessarily'),
('Will never'),
('Will not'),
('Will now'),
('Will probably'),
('Will then'),
('Will wear'),
('Will you'),
('Wind down'),
('Winding down'),
('Wings are'),
('Wings have'),
('Wins a'),
('Winter day'),
('Winter deal'),
('With rich'),
('With smaller'),
('With the court'),
('With the high'),
('Within the bounds'),
('Without reading'),
('Wireless LAN'),
('Women march'),
('Won her'),
('Won his'),
('Won the'),
('Wont'),
('Wood chips'),
('Work crew'),
('Work will'),
('World fleet'),
('Worthy cause'),
('Worthy causes'),
('Worthy of'),
('Would hurt'),
('Would settle'),
('Would sue'),
('Would wear'),
('Writeoff'),
('Year lows'),
('Year old'),
('Years eve'),
('You may'),
('You will'),
('Yougov'),
('Your earthly'),
('Your grant'),
('Your heart'),
('Your knuckles'),
('Your sins');
-- Down
DELETE FROM Skip;