-- Up
INSERT INTO Skip (keyword)
VALUES
('A batch'),
('A bill'),
('A black belt'),
('A black hole'),
('A boulder'),
('A buddy'),
('A cash'),
('A chance'),
('A childs'),
('A christian'),
('A christmas'),
('A clear view'),
('A day'),
('A deal'),
('A deep pit'),
('A dot'),
('A fairer'),
('A flurry'),
('A glass'),
('A gorge'),
('A greater'),
('A guest'),
('A guy'),
('A heap'),
('A jan'),
('A june'),
('A king'),
('A knock'),
('A lamb'),
('A larger'),
('A little rough'),
('A long walk'),
('A love'),
('A page'),
('A peculiar'),
('A plant'),
('A postal'),
('A pound'),
('A price'),
('A may'),
('A mini'),
('A north'),
('A ridge'),
('A savanna'),
('A shepherd'),
('A smaller'),
('A south'),
('A stellar'),
('A steep'),
('A story'),
('A thorn'),
('A walker'),
('A way'),
('A west'),
('A wholly'),
('A windy'),
('A wise'),
('A young'),
('A younger'),
('About the way'),
('Accompany the exchange'),
('Adequate cash'),
('Affidavit'),
('Affiliated boards'),
('Against the wall'),
('Akin to'),
('Albeit smaller'),
('Alfresco'),
('Alien'),
('All day'),
('All roses'),
('All stripes'),
('All the pieces'),
('All the points'),
('All the way'),
('All the wood'),
('All tier'),
('All westward'),
('Alleged price'),
('Along the way'),
('Already heard'),
('Also rose'),
('Am holding'),
('Am leary'),
('Amazon'),
('An april'),
('An east'),
('And banks'),
('And bonds'),
('And day'),
('And hedging'),
('And holding'),
('And price'),
('And snow'),
('And the approach'),
('And the campus'),
('And the place'),
('And the way'),
('And trucks'),
('And mingle'),
('Annul'),
('Any page'),
('Any price'),
('Any reading'),
('Another chance'),
('Another day'),
('Antenna'),
('Anti'),
('Approved the deals'),
('Arbor day'),
('Are angels'),
('Are down'),
('Are greater'),
('Are holding'),
('Are loving'),
('Are low'),
('Are the key'),
('Arts majors'),
('As low as'),
('As the line'),
('As well as cash'),
('Ascii'),
('Assembly bill'),
('At the back'),
('At the ball'),
('At the bank'),
('At the course'),
('At the cross roads'),
('At the heart'),
('At the helm'),
('At the front'),
('At the mercy'),
('At the spa'),
('Audio channels'),
('Autobahn'),
('Autumn camp'),
('Autumn season'),
('Average price'),
('Awesome day'),
('Awesome place'),
('Awesome view'),
('Babe'),
('Baby'),
('Back to back'),
('Bad guy'),
('Bad winter'),
('Balk at'),
('Baklawa'),
('Bankruptcy'),
('Bank of'),
('Banks about'),
('Banks are'),
('Banks by'),
('Banks for'),
('Banks have'),
('Banks in'),
('Banks may'),
('Banks normally'),
('Banks offer'),
('Banks that'),
('Banks to'),
('Bark some'),
('Barracuda'),
('Bars and'),
('Bazaar'),
('Be fearing'),
('Be finely'),
('Be heard'),
('Be holding'),
('Be the key'),
('Beautiful flowers'),
('Been barefoot'),
('Been down'),
('Been loosely'),
('Before christmas'),
('Began tembling'),
('Beta testing'),
('Better day'),
('Big guy'),
('Bigger fish to fry'),
('Bigger story'),
('Bill of'),
('Bivouac'),
('Black beans'),
('Black box'),
('Black eye'),
('Black man'),
('Black market'),
('Black men'),
('Black olives'),
('Black woman'),
('Black women'),
('Blunt instrument'),
('Blunt refusal'),
('Blur'),
('Bodily harm'),
('Bonds are'),
('Bonds at'),
('Bonds because'),
('Bonds could'),
('Bonds due'),
('Bonds fell'),
('Bonds have'),
('Bonds in'),
('Bonds now'),
('Bonds that'),
('Bonds traded'),
('Bonds which'),
('Bonus miles'),
('Booth at'),
('Borders on'),
('Both knuckles'),
('Bottles of'),
('Bows out'),
('Boxing day'),
('Braai'),
('Brace for'),
('Break down'),
('Breaks down'),
('Bride and groom'),
('Brings a'),
('Brings an'),
('British ambassador'),
('Broadaxe'),
('Brotherhood of'),
('Brown bag'),
('Buffet'),
('Burka'),
('Burn bridges'),
('Business day'),
('Buying stocks'),
('By cash'),
('By chance'),
('By compass'),
('By larger'),
('By price'),
('By the courts'),
('By the way'),
('Cadre'),
('Caller id'),
('Camp at'),
('Camp by'),
('Camp will'),
('Camps are'),
('Can rebut'),
('Card holder'),
('Cash and futures'),
('Cash back'),
('Cash flow'),
('Cash flows'),
('Cash income'),
('Cash payment'),
('Cash payments'),
('Cash prize'),
('Cash prizes'),
('Cash proceeds'),
('Cash reward'),
('Cash settlement'),
('Cash traders'),
('Cavalier attitude'),
('Center south'),
('Centers to'),
('Challenge harder'),
('Challenging pace'),
('Chamber of'),
('Champion against'),
('Change the connection'),
('Change the statutes'),
('Chance of'),
('Channels have'),
('Chilli'),
('Chinese wall'),
('Chinwag'),
('Circa'),
('Cisco'),
('Civic'),
('Clear the way'),
('Clearing price'),
('Click on the link'),
('Click the link'),
('Clothes hanger'),
('Co ed'),
('Cold winters'),
('Coming weeks'),
('Cook in'),
('Cook off'),
('Corf'),
('Corporate bonds'),
('Court appearance'),
('Court case'),
('Cover story'),
('Checking the list'),
('Cranberry sauce'),
('Crib'),
('Crimes against'),
('Christmas concert'),
('Christmas day'),
('Christmas dreams'),
('Christmas party'),
('Christmas with'),
('Cross any'),
('Cross border'),
('Cross section'),
('Crown jewel'),
('Crown jewels'),
('Current median'),
('Cutting a'),
('Cutting an'),
('Cutting back'),
('Cutting edge'),
('Cutting the'),
('Daily price'),
('Dairy farmer'),
('Dairy seller'),
('Data grabber'),
('Dawn of time'),
('Day to day'),
('Day ahead'),
('Day before'),
('Day camp'),
('Day care'),
('Day centre'),
('Day down'),
('Day holiday'),
('Day min'),
('Day rally'),
('Day to'),
('Day trades'),
('De facto'),
('Deal now'),
('Deal that'),
('Dean of'),
('Deep snow'),
('Delta'),
('Demand peaks'),
('Diaphragm'),
('Dining hall'),
('Disannul'),
('Disco'),
('Disputes over'),
('Ditch someone'),
('Do the rest'),
('Docking station'),
('Dogma'),
('Dolby digital'),
('Domino effect'),
('Double chevron'),
('Down memory lane'),
('Down the drain'),
('Down the valley'),
('Draws for'),
('Draws of'),
('Dreams of'),
('Drive east'),
('Drive north'),
('Drive south'),
('Drive west'),
('Dusky'),
('East coast'),
('East of'),
('East of the'),
('East from'),
('Each camp'),
('Each day'),
('Each love'),
('Each westward'),
('Early april'),
('Early june'),
('Early may'),
('Earner for'),
('Echo'),
('Emblazon'),
('Ended april'),
('Ended jan'),
('Ended june'),
('Ended may'),
('Energy price'),
('Enigma'),
('Enough booze'),
('Enrich'),
('Entire day'),
('Epiphragm'),
('Escape hatch'),
('Et al'),
('Even bigger'),
('Even greater'),
('Even harder'),
('Evenly among'),
('Eventual price'),
('Everlasting love'),
('Every angle'),
('Every autumn'),
('Every day'),
('Every kitchen'),
('Every summer'),
('Every winter'),
('Exhibit hall'),
('Exit day'),
('Experience gross'),
('Faint of heart'),
('Fair deal'),
('Fairy tale'),
('Faith in'),
('Fall from grace'),
('Fallen angels'),
('Fajita'),
('Far larger'),
('Fast pace'),
('Ferry terminal'),
('Few weeks'),
('Fiasco'),
('Field specialist'),
('Fighting chance'),
('Fill the gap'),
('Final price'),
('Finished april'),
('Finished jan'),
('Finished june'),
('Finished may'),
('First blush'),
('First brushes'),
('First dibs'),
('Fixed price'),
('Flak'),
('Follow the steps'),
('For biz'),
('For day'),
('For down'),
('For downs'),
('For field'),
('For greater'),
('For love'),
('For place'),
('For the campus'),
('For the deals'),
('For the front'),
('For the joint'),
('For the ride'),
('For the stocks'),
('For west'),
('Foray into'),
('Free will'),
('Fresco'),
('Frisky'),
('From'),
('From day'),
('From the mill'),
('From the spot'),
('Front page'),
('Full page'),
('Full story'),
('Fusilli'),
('Gaol'),
('Garners respect'),
('Gargantuan'),
('Gas fields'),
('Gas price'),
('Gauze'),
('Gave way'),
('General ledger'),
('Given greater'),
('Goings on'),
('Gold coin'),
('Gold coins'),
('Gold star'),
('Gold stars'),
('Good cook'),
('Good day'),
('Good faith'),
('Good guy'),
('Good lord'),
('Good will'),
('Got underway'),
('Grace period'),
('Graffiti'),
('Grant agreement'),
('Grant similar'),
('Graphic novel'),
('Graphic novels'),
('Great day'),
('Great guy'),
('Great healer'),
('Greater detail'),
('Greater good'),
('Greater than'),
('Greater value'),
('Green earth'),
('Green light'),
('Green power'),
('Gross profit'),
('Gross profits'),
('Hairs on'),
('Half price'),
('Halfway through'),
('Hanky panky'),
('Have heard'),
('Have price'),
('Have snow'),
('Have the plain'),
('Have won'),
('Havoc'),
('He heard'),
('He may'),
('He sang'),
('He will'),
('He won'),
('Head east'),
('Head north'),
('Head south'),
('Head west'),
('Heard about'),
('Heard by'),
('Heard from'),
('Heard the'),
('Heart attack'),
('Heart attacks'),
('Heart disease'),
('Heart failure'),
('Heart failures'),
('Heavyweight boxer'),
('Hedges against'),
('Hedging a'),
('Hedging bets'),
('Hedging deals'),
('Hedging transactions'),
('Hee hee'),
('Her place'),
('Her scarlet'),
('Her view'),
('High plateau'),
('Highest faith'),
('His hope'),
('His love'),
('His place'),
('His price'),
('His view'),
('His will'),
('Hit the fan'),
('Ho ho ho'),
('Holding a'),
('Holding company'),
('Holding of'),
('Holding off'),
('Holding period'),
('Holding the'),
('Holding up'),
('Holdings completely'),
('Hollering like'),
('Home page'),
('Homing in'),
('Hope all'),
('Hope among'),
('Hope everyone'),
('Hope everything'),
('Hope for'),
('Hope that'),
('Hope the'),
('Hope things'),
('Hope to'),
('Hope you'),
('Horizon'),
('Hour price'),
('Hot ember'),
('Hot summer'),
('Hover around'),
('Hover at'),
('How peculiar'),
('Huddle with'),
('Hung out'),
('Hurt her'),
('Hurt him'),
('Hurt the'),
('Hurt them'),
('Husky'),
('Hydro'),
('I heard'),
('I hope'),
('I love'),
('I may'),
('I will'),
('I won'),
('Idea'),
('It may'),
('It will'),
('Its bonds'),
('Its price'),
('Its stocks'),
('In bars'),
('In bonds'),
('In cash'),
('In april'),
('In east'),
('In flux'),
('In jan'),
('In june'),
('In may'),
('In north'),
('In place'),
('In ruins'),
('In south'),
('In west'),
('In the autumn'),
('In the back'),
('In the bank'),
('In the bush'),
('In the college'),
('In the corner'),
('In the end'),
('In the forehead'),
('In the forest'),
('In the front'),
('In the greater'),
('In the heart'),
('In the hopes'),
('In the light'),
('In the list'),
('In the loop'),
('In the long run'),
('In the low'),
('In the joint'),
('In the park'),
('In the run'),
('In the rut'),
('In the short'),
('In the spa'),
('In the spot'),
('In the spring'),
('In the still'),
('In the summer'),
('In the walk'),
('In the winter'),
('In the wood'),
('In the works'),
('Index price'),
('Inn'),
('Into cash'),
('Into the spring'),
('Investment banks'),
('Is geared to'),
('Is idle'),
('Is lower'),
('Is no place'),
('Is reading'),
('Issue bonds'),
('Jabs at'),
('Joint boards'),
('Jot those'),
('Junk bonds'),
('Just love'),
('Kebab'),
('Keen to'),
('Key steps'),
('Kulak'),
('King and queen'),
('Lambrusco'),
('Lane judges'),
('Lasagna'),
('Last april'),
('Last beam'),
('Last day'),
('Last jan'),
('Last june'),
('Last may'),
('Last autumn'),
('Last chance'),
('Last christmas'),
('Last easter'),
('Last summer'),
('Last winter'),
('Late april'),
('Late jan'),
('Late june'),
('Late may'),
('Later day'),
('Launch day'),
('Lay off'),
('Lay out'),
('Lead banks'),
('Lead the way'),
('Leading the way'),
('Leap of'),
('Left the trees'),
('Liability clause'),
('Lich'),
('Light trucks'),
('Like price'),
('Local deal'),
('Locks are'),
('Locks have'),
('Long day'),
('Longer term'),
('Lose faith'),
('Loses faith'),
('Lost faith'),
('Love and support'),
('Love by'),
('Love if'),
('Love it'),
('Love letter'),
('Love song'),
('Love to'),
('Love with'),
('Love you'),
('Lovers on'),
('Low cost'),
('Low daily'),
('Low income'),
('Low of'),
('Low price'),
('Low rank'),
('Low ranking'),
('Lower price'),
('Lowest price'),
('Lowest rung'),
('Lows expected'),
('Lows in'),
('Lows of'),
('Made camp'),
('Maelstrom'),
('Magma'),
('Majordomo'),
('Making love'),
('March or april'),
('Mark discrepancy'),
('Mark your'),
('Market hedges'),
('Market price'),
('Market rate'),
('Marks for'),
('Marks of'),
('Max number'),
('Max rate'),
('Maxi'),
('May i'),
('May in'),
('May add'),
('May already'),
('May also'),
('May apply'),
('May be'),
('May come'),
('May concern'),
('May contain'),
('May have'),
('May love'),
('May not'),
('May now'),
('May only'),
('May or may not'),
('May park at'),
('May park in'),
('May park on'),
('May potentially'),
('May show'),
('May soon'),
('May the'),
('May together'),
('May unduly'),
('May vary'),
('May well'),
('Meager credit'),
('Meat packer'),
('Median age'),
('Memorial day'),
('Merger deal'),
('Monte carlo simulation'),
('Month of april'),
('Month of may'),
('Month of jan'),
('Month of june'),
('More cash'),
('More miles'),
('More pressing'),
('More weeks'),
('Mothers day'),
('Much smaller'),
('Much snow'),
('Much the way'),
('Muddle through'),
('Murky brown'),
('Muscle strands'),
('Musky'),
('My calendar'),
('My heart'),
('My hope'),
('My lips'),
('My love'),
('My place'),
('My price'),
('My will'),
('Nailing down'),
('Nazi'),
('Near the close'),
('Nearby camp'),
('Next april'),
('Next autumn'),
('Next day'),
('Next jan'),
('Next june'),
('Next may'),
('Next summer'),
('Next winter'),
('New bonds'),
('New cash'),
('New lows'),
('New place of'),
('New price'),
('New snow'),
('News story'),
('Ninja'),
('No biggie'),
('Noel'),
('Normal pace'),
('Normal summer'),
('North of'),
('North of the'),
('North from'),
('Notch above'),
('Notch below'),
('Noun'),
('Nova'),
('Of banks'),
('Of bonds'),
('Of court'),
('Of day'),
('Of fries'),
('Of greater'),
('Of house'),
('Of lake'),
('Of love'),
('Of joy'),
('Of miles'),
('Of plant'),
('Of price'),
('Of summers'),
('Of the ashes'),
('Of the ball'),
('Of the bank'),
('Of the banks'),
('Of the common'),
('Of the deals'),
('Of the end'),
('Of the forest'),
('Of the island'),
('Of the loan'),
('Of the line'),
('Of the links'),
('Of the joint'),
('Of the osprey'),
('Of the rise'),
('Of the settlement'),
('Of the short'),
('Of the tunnel'),
('Of the way'),
('Of weeks'),
('Off the loan'),
('Off the hook'),
('Offal'),
('Offer price'),
('Oil fields'),
('Once mighty'),
('Onto the island'),
('Old gal'),
('Old guy'),
('Old couple'),
('On black'),
('On boards'),
('On day'),
('On love'),
('On page'),
('On the back'),
('On the beach'),
('On the corner'),
('On the hook'),
('On the island'),
('On the line'),
('On the list'),
('On the lookout'),
('On the moon'),
('On the rise'),
('On the shore'),
('On the sly'),
('On the stack'),
('On the way'),
('On white'),
('Only chance'),
('Only will it'),
('One day'),
('Open day'),
('Opening day'),
('Option grant'),
('Orca'),
('Orphan'),
('Other day'),
('Other postal'),
('Our chances'),
('Our east'),
('Our hope'),
('Our love'),
('Our north'),
('Our price'),
('Our south'),
('Our west'),
('Our winter'),
('Out east'),
('Out north'),
('Out south'),
('Out west'),
('Outswam'),
('Oval office'),
('Over weeks'),
('Over steep'),
('Over the course of'),
('Overawe'),
('Overnight lows'),
('Pace through'),
('Page at'),
('Page to'),
('Page using'),
('Page version'),
('Package deal'),
('Paprika'),
('Parka'),
('Parks at'),
('Parks by'),
('Parks near'),
('Parks on'),
('Pastures for'),
('Patches of'),
('Pay cash'),
('Pay down the'),
('Peak day'),
('Pearl Harbor'),
('Penne'),
('Pelvic'),
('Pesky'),
('Per day'),
('Per page'),
('Percent bonds'),
('Personal story'),
('Piazza'),
('Pickaxe'),
('Pinch on'),
('Pinch the'),
('Pinching yourself'),
('Pita'),
('Piles of'),
('Pizza'),
('Plain vanilla'),
('Plant pots'),
('Plant will'),
('Plant volume'),
('Plateau that'),
('Playoff'),
('Pogrom'),
('Poleaxe'),
('Polo'),
('Positive story'),
('Powder snow'),
('Power bill'),
('Power plant'),
('Powers to'),
('Pressing for'),
('Pressing this'),
('Previous day'),
('Price cap'),
('Price caps'),
('Price component'),
('Price control'),
('Price correction'),
('Price curve'),
('Price curves'),
('Price deals'),
('Price difference'),
('Price discrepancy'),
('Price discrepancies'),
('Price forecasts'),
('Price fluctuations'),
('Price for'),
('Price increase'),
('Price increases'),
('Price index'),
('Price manipulation'),
('Price may'),
('Price paid'),
('Price per'),
('Price of'),
('Price on'),
('Price range'),
('Price risk'),
('Price that'),
('Price this'),
('Price to'),
('Price transparency'),
('Price volatility'),
('Price within'),
('Prices sank'),
('Pride day'),
('Prima facie'),
('Prior day'),
('Pro rata'),
('Prom'),
('Promo'),
('Pronoun'),
('Psych'),
('Psycho'),
('Pull the ball'),
('Purchase price'),
('Put the list'),
('Quad'),
('Quay'),
('Quick halt'),
('Quick pace'),
('Range view'),
('Rapid halt'),
('Rapid pace'),
('Rash of'),
('Ray of hope'),
('Razor'),
('Reached the dock'),
('Read the joint'),
('Reading about'),
('Reading books'),
('Reading excerpts'),
('Reading from'),
('Reading her'),
('Reading his'),
('Reading my'),
('Reading their'),
('Reading this'),
('Reading your'),
('Readings by'),
('Readings of'),
('Recent weeks'),
('Red glow'),
('Registrar'),
('Related fields'),  
('Repay the loan'),
('Resolve disputes'),
('Revenue rose'),
('Rib'),
('Rich fields'),
('Rich premium'), 
('Rich premiums'),  
('Risky'),
('Rock stars'),
('Rod for'),
('Rod to'),
('Roller coaster'),
('Rom'),
('Roman catholic'),
('Romp through'),
('Rose by'),
('Rose marginally'),
('Rose slightly'),
('Rub'),
('Run down'),
('Run the way'),
('Rushed to'),
('Rushing into'),
('Rushing to'),
('Rushing water'),
('Rye'),
('Saga'),
('Sail from'),
('Sail out'),
('Sail to'),
('Sales price'),
('Salt cavern'),
('Same day'),
('Same price'),
('Sandwich'),
('Sang about'),
('Snow machine'),
('Snow mobile'),
('Squad'),
('Squab'),
('Such joy'),
('Summer and winter'),
('Summer sale'),
('Summer sales'),
('Security holdings'),
('Selling bonds'),
('Serve burgers'),
('Set forth'),
('Settlement price'),
('Several weeks'),
('Shape the way'),
('Shaped the way'),
('Shaping the way'),
('Sharp decline'),
('Sharp discount'),
('Sharp drop'),
('Sharp fall'),
('Sharp turn'),
('Share price'),
('Shares rose'),
('Sharper than'),
('She heard'),
('She may'),
('She sang'),
('She will'),
('She won'),
('Shoring up'),
('Short term'),
('Shriek'),
('Shrub'),
('Scrub'),
('Sigma'),
('Silver coin'),
('Silver coins'),
('Silver star'),
('Silver stars'),
('Sincerely hope'),
('Sit idle'),
('Slow pace'),
('Sluggish pace'),
('Slur'),
('Small cliff'),
('Spaghetti'),
('Spanning the'),
('Sparerib'),
('Spinoff'),
('Splash page'),
('Spurs opposition'),
('So overly'),
('Solo'),
('Some banks'),
('Some beers'),
('Some milder'),
('Somewhat common'),
('Summary page'),
('Summed up'),
('Summer of'),
('Summer months'),
('Summer track'),
('Sunny day'),
('Sunrise from'),
('Supernova'),
('Sushi'),
('Suspension bridges'),
('South of'),
('South of the'),
('South from'),
('Stack of'),
('Stacks of'),
('Stakes in'),
('Standoff'),
('Staring at'),
('Stars are'),
('Steel foundry'),
('Steep costs'),
('Stigma'),
('Still under way'),
('Stimulus bill'),
('Stock holdings'),
('Stock price'),
('Stocking stuffers'),
('Stocks and bonds'),
('Stocks at'),
('Stocks close higher'),
('Stocks close lower'),
('Stocks fell'),
('Stocks of'),
('Stocks on'),
('Stocks rose'),
('Stocks were'),
('Story about'),
('Strike price'),
('Stucco'),
('Swab'),
('Swag'),
('Swam'),
('Swan'),
('Swap'),
('Swat'),
('Sue you'),
('Summer camp'),
('Summer season'),
('Symbol'),
('Tabacco'),
('Take heart'),
('Take place'),
('Taken the liberty'),
('Talc'),
('Taming the'),
('Target price'),
('Tax havens'),
('Taxi'),
('Team won'),
('Tee box'),
('Terrible day'),
('Tee off'),
('Television channels'),
('Than'),
('That banks'),
('That creates'),
('That day'),
('That guy'),
('That love'),
('That nodal'),
('That page'),
('That price'),
('That sees'),
('That song'),
('That the spot'),
('That the walk'),
('That van'),
('The alter'),
('The april'),
('The autumn'),
('The ball is'),
('The bank of'),
('The bank to'),
('The banks'),
('The beam'),
('The bees'),
('The bill'),
('The bonds'),
('The boulder'),
('The calendar'),
('The calls to'),
('The camp'),
('The cash'),
('The cashier'),
('The chance'),
('The childs'),
('The clouds'),
('The connection is'),
('The copier'),
('The course of'),
('The course that'),
('The couch'),
('The court'),
('The courts are'),
('The courts will'),
('The christmas'),
('The crew'),
('The cross country'),
('The curve been'),
('The curve on'),
('The day'),
('The deal'),
('The deals all'),
('The deals are'),
('The deals were'),
('The east'),
('The easter'),
('The edge of'),
('The elbow'),
('The end of'),
('The ferry'),
('The folders specified'),
('The front of'),
('The front office'),
('The front page'),
('The front room'),
('The gap was'),
('The gap went'),
('The gold'),
('The gorge'),
('The grant'),
('The grass'),
('The guest'),
('The guy'),
('The hall to'),
('The heads up'),
('The heavenly'),
('The heck'),
('The hem'),
('The high crest'),
('The hope'),
('The hood'),
('The house'),
('The land is'),
('The larger'),
('The level of'),
('The light at'),
('The light load'),
('The line at'),
('The line with'),
('The link into'),
('The link to'),
('The links on'),
('The list above'),
('The list includes'),
('The list of'),
('The loan relates'),
('The loop on'),
('The love'),
('The low end'),
('The low values'),
('The low point'),
('The lower end'),
('The jan'),
('The jedi'),
('The june'),
('The key element'),
('The key ingredient'),
('The key is'),
('The key to'),
('The king'),
('The kitchen'),
('The main front'),
('The mark'),
('The may'),
('The max'),
('The miles'),
('The moon'),
('The new'),
('The new site'),
('The north'),
('The outlook becomes'),
('The outlook for'),
('The outlook is'),
('The outlook gets'),
('The outlook on'),
('The pace'),
('The page'),
('The peak hours'),
('The peculiar'),
('The piece between'),
('The place for'),
('The place i'),
('The place he'),
('The place she'),
('The place to'),
('The place we'),
('The place you'),
('The plain truth'),
('The plant'),
('The plant would'),
('The plateau that'),
('The point is'),
('The point of'),
('The point that'),
('The points which'),
('The pool'),
('The puncher'),
('The price'),
('The prince'),
('The prospect of'),
('The prospect that'),
('The rally seemed'),
('The range of'),
('The reins'),
('The rest of'),
('The resolution of'),
('The retreat was'),
('The rise in'),
('The roads'),
('The royal bank'),
('The run of'),
('The seashore'),
('The settlement also'),
('The settlement is'),
('The settlement of'),
('The short time'),
('The square root'),
('The slides that'),
('The snow'),
('The swallow'),
('The east side'),
('The north side'),
('The song'),
('The sound of'),
('The south side'),
('The way i'),
('The way it'),
('The way she'),
('The way they'),
('The way we'),
('The whack'),
('The west side'),
('The works of'),
('The south'),
('The spring festival'),
('The spur of'),
('The stakes are'),
('The stock down'),
('The stone'),
('The story'),
('The summer'),
('The sun'),
('The tally'),
('The tenor'),
('The tanking'),
('The ticker'),
('The usher'),
('The van'),
('The waiter'),
('The walk goes'),
('The walk to'),
('The way around'),
('The way back'),
('The way from'),
('The way of'),
('The way to'),
('The west'),
('The weeks'),
('The winter'),
('The younger'),
('Their place'),
('Their price'),
('Their view'),
('Their walls'),
('Then the forest'),
('They heard'),
('They hope'),
('They love'),
('They may'),
('They sang'),
('They view'),
('They will'),
('Things down'),
('Things will'),
('This april'),
('This day'),
('This love'),
('This grant'),
('This guy'),
('This page'),
('This place'),
('This price'),
('This jan'),
('This june'),
('This may'),
('This autumn'),
('This christmas'),
('This childs'),
('This easter'),
('This story'),
('This summer'),
('This sun'),
('This traverse'),
('This will'),
('This winter'),
('This won'),
('Thou'),
('Through the gap'),
('Ticket booth'),
('Tier that'),
('Tightwad'),
('To be cash'),
('To block the'),
('To camp'),
('To cash'),
('To chance'),
('To clink'),
('To cross'),
('To day'),
('To hurt'),
('To larger'),
('To lavish'),
('To quell'),
('To mark the'),
('To pay down'),
('To place'),
('To plow'),
('To price'),
('To prosper'),
('To rebut'),
('To rout'),
('To stoke'),
('To tailor'),
('To the back'),
('To the bar'),
('To the edge'),
('To the forest'),
('To the heart'),
('To the list'),
('To the new common'),
('To the joint'),
('To the peak'),
('To the plant'),
('To the point in'),
('To the point of'),
('To the point when'),
('To the point where'),
('To the rest'),
('To the round'),
('To the short'),
('To the valley'),
('To the village'),
('To tote'),
('To uphold'),
('To vent'),
('To younger'),
('Told callers'),
('Tomato'),
('Tonic for'),
('Tonne'),
('Too low'),
('Top story'),
('Tore out'),
('Trade credit'),
('Trade credits'),
('Tradeoff'),
('Tradition christmas'),
('Trek'),
('Tree saplings'),
('Trial court'),
('Trickle out'),
('Trickle to'),
('Troop of'),
('True love'),
('Trustworthy basis'),
('Turned the corner'),
('Twat'),
('Typical bill'),
('Under way on'),
('Until autumn'),
('Until spring'),
('Until summer'),
('Until winter'),
('Update day'),
('Urethra'),
('Various banks'),
('Very common'),
('Very down'),
('Very place'),
('Vermicelli'),
('Vehicle fleet'),
('Voting booth'),
('Wad'),
('Wag'),
('Waif'),
('Wap'),
('Walls above'),
('Wanna go'),
('Was day'),
('Was down'),
('Was idle'),
('Was stolen'),
('Water bottles'),
('Waterski'),
('We drew'),
('We hope'),
('We hung'),
('We love'),
('We may'),
('We will'),
('Web page'),
('Well underway'),
('Week low'),
('Weeks ago'),
('Weeks of'),
('Weeks to'),
('Were down'),
('Were low'),
('West coast'),
('West of'),
('West of the'),
('West from'),
('West wing'),
('Wetter than'),
('When will'),
('Where grass'),
('Which'),
('Which will'),
('Which wood'),
('While sellers'),
('Whisky'),
('White man'),
('White men'),
('White shirt'),
('White woman'),
('White women'),
('Who will'),
('Whole day'),
('Whom will'),
('Wigwam'),
('Wild goose'),
('Will a lack'),
('Will absolutely'),
('Will actually'),
('Will adequately'),
('Will add'),
('Will almost'),
('Will also'),
('Will always'),
('Will back'),
('Will be'),
('Will certainly'),
('Will definitely'),
('Will do'),
('Will ever'),
('Will have'),
('Will fiddle'),
('Will finally'),
('Will forever'),
('Will forward'),
('Will he'),
('Will help'),
('Will her'),
('Will i'),
('Will in'),
('Will instead'),
('Will just'),
('Will likely'),
('Will make'),
('Will meet'),
('Will most'),
('Will need'),
('Will never'),
('Will no'),
('Will not'),
('Will now'),
('Will open'),
('Will once'),
('Will only'),
('Will pro'),
('Will probably'),
('Will regularly'),
('Will resend'),
('Will ruefully'),
('Will significantly'),
('Will she'),
('Will still'),
('Will surely'),
('Will the'),
('Will their'),
('Will they'),
('Will then'),
('Will this'),
('Will transition'),
('Will ultimately'),
('Will waive'),
('Will you'),
('Will your'),
('Wind down'),
('Winding down'),
('Wings are'),
('Wings have'),
('Wins a'),
('Winter camp'),
('Winter festival'),
('Winter months'),
('Winter period'),
('Winter sale'),
('Winter sales'),
('Winter season'),
('With banks'),
('With hope'),
('With rich'),
('With smaller'),
('With the belt'),
('Within the bounds'),
('Without reading'),
('Wireless LAN'),
('Wood chips'),
('Work crew'),
('Work day'),
('World fleet'),
('Worthy cause'),
('Worthy causes'),
('Worthy of'),
('Would sue'),
('Writeoff'),
('Year lows'),
('Years eve'),
('Yerba'),
('You cook'),
('You love'),
('You may'),
('You will'),
('Young adult'),
('Young adults'),
('Young baby'),
('Young boy'),
('Young couple'),
('Young gal'),
('Young girl'),
('Young guy'),
('Young males'),
('Young man'),
('Young men'),
('Young people'),
('Young person'),
('Young professionals'),
('Young volunteers'),
('Young woman'),
('Young women'),
('Your day'),
('Your earthly'),
('Your grant'),
('Your heart'),
('Your hope'),
('Your knuckles'),
('Your love'),
('Your price'),
('Your sins');
-- Down
DELETE FROM Skip;