-- Up
INSERT INTO Skip (keyword)
VALUES
('A batch'),
('A bath'),
('A battle'),
('A bill'),
('A black belt'),
('A black hole'),
('A boulder'),
('A bow'),
('A buddy'),
('A cash'),
('A chance'),
('A childs'),
('A christian'),
('A christmas'),
('A clause'),
('A deal'),
('A deep pit'),
('A dot'),
('A fairer'),
('A flurry'),
('A gang'),
('A glass'),
('A gorge'),
('A greater'),
('A green'),
('A guy'),
('A heap'),
('A jan'),
('A june'),
('A king'),
('A knock'),
('A lamb'),
('A little less'),
('A little long'),
('A little rough'),
('A loner'),
('A long road'),
('A long walk'),
('A lower exchange'),
('A mark'),
('A page'),
('A pat'),
('A peculiar'),
('A penny'),
('A plant'),
('A postal'),
('A pound'),
('A may'),
('A mini'),
('A ridge'),
('A rod'),
('A savanna'),
('A scolding'),
('A shepherd'),
('A smaller'),
('A spike'),
('A stellar'),
('A steep'),
('A story'),
('A thorn'),
('A walker'),
('A way'),
('A windy'),
('A wise'),
('Accompany the exchange'),
('Achilles heel'),
('Acrobat'),
('Ad hoc'),
('Addr'),
('Adds'),
('Adopt'),
('Affidavit'),
('Affiliated boards'),
('After the court'),
('Against the wall'),
('Akin to'),
('Albeit smaller'),
('Album'),
('Aldi'),
('Alfalfa'),
('Alfresco'),
('Alien'),
('All roses'),
('All stripes'),
('All the pieces'),
('All the points'),
('All the wood'),
('All tier'),
('All westward'),
('Alls well'),
('Alpha male'),
('Along the path'),
('Also'),
('Also rose'),
('Also wear'),
('Always wear'),
('Am holding'),
('Am leary'),
('Amazon'),
('Amber warning'),
('Amber warnings'),
('Among young'),
('An april'),
('And bonds'),
('And dizzy'),
('And green'),
('And hedging'),
('And holding'),
('And snow'),
('And trucks'),
('And mingle'),
('Annul'),
('Any deal'),
('Any page'),
('Any pressing'),
('Any reading'),
('Any winnings'),
('Anorak'),
('Another chance'),
('Ante'),
('Antenna'),
('Anti'),
('Appeal court'),
('Approx'),
('Aorta'),
('Ardent in'),
('Are angels'),
('Are down'),
('Are greater'),
('Are holding'),
('Are loving'),
('Are low'),
('Are reading'),
('Are the key'),
('Are two ways'),
('Are under way'),
('Armor piercing'),
('Armour piercing'),
('Arts majors'),
('As low as'),
('As well'),
('Asap'),
('Ascii'),
('Asda'),
('Asthma'),
('At the ball'),
('At the borders'),
('At the course'),
('At the court'),
('At the heart'),
('At the helm'),
('At the front'),
('At the mercy'),
('At the spa'),
('Audio channels'),
('Auto'),
('Autobahn'),
('Autumn camp'),
('Autumn season'),
('Babe'),
('Baby'),
('Back down'),
('Back in'),
('Back to back'),
('Bad aims'),
('Bad bill'),
('Bad buy'),
('Bad captain'),
('Bad chancellor'),
('Bad charity'),
('Bad christmas'),
('Bad church'),
('Bad clues'),
('Bad college'),
('Bad cook'),
('Bad cooks'),
('Bad day'),
('Bad faith'),
('Bad farewell'),
('Bad grace'),
('Bad guest'),
('Bad guy'),
('Bad heart'),
('Bad june'),
('Bad lady'),
('Bad lord'),
('Bad love'),
('Bad minister'),
('Bad piece'),
('Bad president'),
('Bad price'),
('Bad prince'),
('Bad professor'),
('Bad school'),
('Bad story'),
('Bad summer'),
('Bad summers'),
('Bad university'),
('Bad will'),
('Bad winter'),
('Balk at'),
('Baklawa'),
('Ballsy'),
('Bank of england'),
('Bankruptcy'),
('Banner reading'),
('Bark some'),
('Barracuda'),
('Battle re-enactments'),
('Bazaar'),
('Be fearing'),
('Be finely'),
('Be holding'),
('Be the key'),
('Bearer of'),
('Bearhug'),
('Beautiful flowers'),
('Been barefoot'),
('Been down'),
('Been loosely'),
('Before christmas'),
('Before holding'),
('Began tembling'),
('Beta test'),
('Beta testing'),
('Bidet'),
('Big deal'),
('Big guy'),
('Big kitty'),
('Bigger gap'),
('Bikini'),
('Bivouac'),
('Black beans'),
('Black box'),
('Black eye'),
('Black high'),
('Black market'),
('Black olives'),
('Blah'),
('Blob'),
('Blowjob'),
('Blunt instrument'),
('Blunt refusal'),
('Blur'),
('Bodily harm'),
('Bollox'),
('Bona fide'),
('Bond holder'),
('Bonds are'),
('Bonds at'),
('Bonds because'),
('Bonds could'),
('Bonds due'),
('Bonds fell'),
('Bonds have'),
('Bonds in'),
('Bonds now'),
('Bonds that'),
('Bonds traded'),
('Bonds which'),
('Bonsai'),
('Bonus miles'),
('Boob'),
('Booth at'),
('Borders on'),
('Bottles of'),
('Bows out'),
('Braai'),
('Brace for'),
('Breadth'),
('Break down'),
('Breaks down'),
('Bridal showers'),
('Bride and groom'),
('Brings a'),
('Brings an'),
('Britain tidy'),
('British airways'),
('British ambassador'),
('Broad gun'),
('Broad range'),
('Broadaxe'),
('Brotherhood of'),
('Brown bag'),
('Buffet'),
('Bundle of'),
('Bureau'),
('Burka'),
('Burn bridges'),
('But will'),
('By chance'),
('By compass'),
('By courier'),
('By smaller'),
('Cacao'),
('Cadet'),
('Cadre'),
('Cajun'),
('Calc'),
('Caller id'),
('Camp at'),
('Camp by'),
('Camp will'),
('Camps are'),
('Canoes'),
('Capita'),
('Card holder'),
('Cartel heartland'),
('Cash back'),
('Cavalier attitude'),
('cctv'),
('Celeb'),
('Centers to'),
('Central bank'),
('Central banks'),
('Challenge harder'),
('Challenging pace'),
('Chamber of'),
('Chambers of commerce'),
('Change the connection'),
('Change the statutes'),
('Chance of'),
('Chase up'),
('Cheetah'),
('Chef'),
('Chilli'),
('Chimpanzee'),
('Chinese wall'),
('Chinwag'),
('Christian Democratic'),
('Ciphertext'),
('Circa'),
('Cisco'),
('City centre'),
('Civic'),
('Climate change'),
('Close down'),
('Clothes hanger'),
('Clumsy'),
('Co ed'),
('Coax'),
('Codec'),
('Cold winters'),
('Combat'),
('Combo'),
('Comfy'),
('Coming autumn'),
('Coming spring'),
('Coming weeks'),
('Common crimes'),
('Common practice'),
('Commonality'),
('Confab'),
('Confer with'),
('Confidante'),
('Context'),
('Contexts'),
('Contrasted sharply'),
('Corf'),
('Corp'),
('Corporate bonds'),
('Cost center'),
('Cost centre'),
('Couldnt'),
('County level'),
('Court appearance'),
('Court case'),
('Court for'),
('Court judge'),
('Cover story'),
('Cranberry sauce'),
('Crib'),
('Crimes against'),
('Crystal clear'),
('Christmas day'),
('Cross median'),
('Cross roads'),
('Crowd'),
('Crown jewel'),
('Crown jewels'),
('Cssu'),
('Current median'),
('Cutoff'),
('Cutting a'),
('Cutting an'),
('Cutting back'),
('Cutting edge'),
('Cutting the'),
('Cyborg'),
('Czar'),
('Dairy farmer'),
('Dairy seller'),
('Data grabber'),
('Datix'),
('Dawn of time'),
('De facto'),
('Deal by'),
('Deal is'),
('Deal making'),
('Deal negotiation'),
('Deal now'),
('Deal or'),
('Deal should'),
('Deal that'),
('Deal transfer'),
('Deal with'),
('Deal would'),
('Dean of'),
('Debts'),
('Debutante'),
('Deems appropriate'),
('Deep snow'),
('Delta'),
('Demand peaks'),
('Demob'),
('Diaphragm'),
('Different story'),
('Dildo'),
('Dilettante'),
('Dining hall'),
('Disannul'),
('Disco'),
('Dismay'),
('Dissatisfy'),
('Dont'),
('Dont wanna'),
('Do the rest'),
('Docking station'),
('Does'),
('Doesn'),
('Dogma'),
('Dojo'),
('Dolby digital'),
('Domino effect'),
('Doorbell rang'),
('Double chevron'),
('Doubts'),
('Down before'),
('Down here'),
('Down memory lane'),
('Down the drain'),
('Down the street'),
('Down the valley'),
('Downtrod'),
('Draws for'),
('Draws of'),
('Drive down'),
('Drive east'),
('Drive north'),
('Drive south'),
('Drive west'),
('Drones'),
('Dusky'),
('E mails'),
('Each camp'),
('Each lay'),
('Each westward'),
('Early april'),
('Early june'),
('Early may'),
('Earner for'),
('Echo'),
('Electricity deal'),
('Emblazon'),
('Employee'),
('End of April'),
('End of Jan'),
('End of June'),
('End of May'),
('End of the month'),
('End of the quarter'),
('End of the year'),
('Ended april'),
('Ended jan'),
('Ended june'),
('Ended may'),
('Enigma'),
('Enjoy'),
('Enough booze'),
('Enrich'),
('Enviro'),
('Epiphragm'),
('Escape hatch'),
('Et al'),
('Eve of'),
('Even greater'),
('Even harder'),
('Evenly among'),
('Every angle'),
('Every autumn'),
('Every kitchen'),
('Ex parte'),
('Exam'),
('Exec'),
('Exhibit hall'),
('Experience gross'),
('Fair deal'),
('Fairy tale'),
('Faith in'),
('Fall back'),
('Fall from grace'),
('Fall well'),
('Fallen angels'),
('Fajita'),
('Family reading'),
('Faqs'),
('Fast pace'),
('Fell back'),
('Fell to its'),
('Ferry terminal'),
('Few weeks'),
('Fiasco'),
('Field day'),
('Fields from'),
('Fields in'),
('Field specialist'),
('Fighting chance'),
('Final weeks'),
('Fine art'),
('Fine day'),
('Finished april'),
('Finished jan'),
('Finished june'),
('Finished may'),
('First blush'),
('First brushes'),
('First dibs'),
('Fixed deal'),
('Flak'),
('Flat pack'),
('Fleet manager'),
('Fleet of'),
('Flurry of'),
('Flying back'),
('Folio'),
('Follow the steps'),
('For biz'),
('For christmas'),
('For greater'),
('For the front'),
('For the joint'),
('For the ride'),
('Foray into'),
('French doors'),
('French windows'),
('Frenzy'),
('Fresco'),
('Frisky'),
('From'),
('Front page'),
('FTSE 100'),
('Full and frank'),
('Full page'),
('Full story'),
('Fun deal'),
('Fusilli'),
('Future deal'),
('Fuzzy'),
('Gaol'),
('Garners respect'),
('Gargantuan'),
('Gas deal'),
('Gas fields'),
('Gateau'),
('Gauze'),
('Gave way'),
('GDPR'),
('General ledger'),
('Generating plant'),
('German shepherd'),
('Get under way'),
('Getting flack'),
('Giddy hope'),
('Given greater'),
('Glim'),
('Glob'),
('Glut'),
('Goes back'),
('Goes sour'),
('Goes through'),
('Goes way'),
('Goes well'),
('Goings on'),
('Gonna'),
('Good guy'),
('Good lord'),
('Goodbye'),
('Gossip'),
('Got underway'),
('Govt'),
('Grace period'),
('Graffiti'),
('Grandma'),
('Grandpa'),
('Grant agreement'),
('Grant agreements'),
('Grant request'),
('Grant requests'),
('Grant similar'),
('Graphic novel'),
('Graphic novels'),
('Great deal'),
('Great guy'),
('Great healer'),
('Greater detail'),
('Greater good'),
('Greater than'),
('Greater value'),
('Green earth'),
('Green energy'),
('Green light'),
('Green power'),
('Gross profit'),
('Gross profits'),
('Hadnt'),
('Halfway point'),
('Halfway through'),
('Handoff'),
('Hanky panky'),
('Have heard'),
('Have snow'),
('Have the plain'),
('Have won'),
('Havoc'),
('He may'),
('He sang'),
('He will'),
('He won'),
('Head lice'),
('Head of rugby'),
('Heard back'),
('Heard how'),
('Heart goes'),
('Heavyweight boxer'),
('Hee hee'),
('Helio'),
('Helix'),
('Helluva'),
('Heroes'),
('High building'),
('High level'),
('High plateau'),
('High price'),
('High school'),
('High speed'),
('High standards'),
('Highest faith'),
('Hijab'),
('His view'),
('Hit the fan'),
('Ho ho ho'),
('Hoax'),
('Holding a'),
('Holding back'),
('Holding company'),
('Holding companies'),
('Holding fund'),
('Holding funds'),
('Holding of'),
('Holding off'),
('Holding period'),
('Holding the'),
('Holding up'),
('Holding us'),
('Holdings completely'),
('Hollering like'),
('Home page'),
('Home town'),
('Homing in'),
('Hope all'),
('Hope everything'),
('Hope everythings'),
('Hope for'),
('Hope that'),
('Hope to'),
('Hope we'),
('Hope you'),
('Hope your'),
('Horizon'),
('Hot ember'),
('Hover around'),
('Hover at'),
('How bad'),
('How close'),
('How could'),
('How far'),
('How long'),
('How peculiar'),
('Huddle with'),
('Hung out'),
('Hunt down'),
('Hunts in the'),
('Huge deal'),
('Husky'),
('Hydro'),
('Hypertext'),
('I hope'),
('I lay'),
('I may'),
('I wear'),
('I won'),
('Idea'),
('Idiocy'),
('Igloo'),
('Iota'),
('It may'),
('Its bonds'),
('In bars'),
('In bonds'),
('In building'),
('In april'),
('In flux'),
('In jan'),
('In june'),
('In may'),
('In ruins'),
('In summer'),
('In the autumn'),
('In the bush'),
('In the corner'),
('In the end'),
('In the forehead'),
('In the forest'),
('In the front'),
('In the greater'),
('In the heart'),
('In the joint'),
('In the light'),
('In the loop'),
('In the park'),
('In the run'),
('In the rush'),
('In the rut'),
('In the spa'),
('In the spot'),
('In the spring'),
('In the still'),
('In the walk'),
('In the wood'),
('In the works'),
('Infarct'),
('Info'),
('Information booths'),
('Inn'),
('Intermix'),
('Into'),
('Is geared to'),
('Is idle'),
('Is loving'),
('Is lower'),
('Is reading'),
('Is under way'),
('Issue bonds'),
('Jabs at'),
('Jihad'),
('Joins with'),
('Joint boards'),
('Jalapeno'),
('Jot those'),
('Junk bonds'),
('Kebab'),
('Keen to'),
('Keep faith'),
('Key day'),
('Kulak'),
('Kickoff'),
('Kilns'),
('King and queen'),
('Kiosk'),
('Kitchen counter'),
('Lambrusco'),
('Lane judges'),
('Lasagna'),
('Last april'),
('Last beam'),
('Last jan'),
('Last june'),
('Last may'),
('Last autumn'),
('Last chance'),
('Last christmas'),
('Last easter'),
('Late april'),
('Late jan'),
('Late june'),
('Late may'),
('Lay eggs'),
('Lay off'),
('Lay out'),
('Leaks row'),
('Leap of'),
('Left the trees'),
('Left wing'),
('Left winger'),
('Less common'),
('Level playing field'),
('Lich'),
('Lidl'),
('Light trucks'),
('Like to pass'),
('Limbo'),
('Local deal'),
('Locked down'),
('Lockjaw'),
('Locks are'),
('Locks have'),
('Logjam'),
('Logo'),
('Long beard'),
('Long range'),
('Longer term'),
('Losing faith'),
('Loofa'),
('Lovers on'),
('Loves reading'),
('Low cost'),
('Low daily'),
('Low ebb'),
('Low income'),
('Low of'),
('Low price'),
('Low rank'),
('Low ranking'),
('Lowest rung'),
('Lows expected'),
('Lows in'),
('Lows of'),
('Lower christmas'),
('Lower house'),
('Lower level'),
('Made camp'),
('Maelstrom'),
('Mailto'),
('Main page'),
('Maglev'),
('Magma'),
('Major'),
('Majordomo'),
('March or april'),
('March through'),
('Mark discrepancy'),
('Mark it'),
('Mark your'),
('Market approach'),
('Market hedges'),
('Market price'),
('Market rate'),
('Market side'),
('Marks for'),
('Marks of'),
('Marks & spencer'),
('Marks and spencer'),
('Mascara'),
('Max number'),
('Max numbers'),
('Max rate'),
('Max rates'),
('Maxi'),
('May i'),
('May in'),
('May add'),
('May already'),
('May also'),
('May apply'),
('May be'),
('May come'),
('May concern'),
('May contain'),
('May have'),
('May just'),
('May not'),
('May now'),
('May only'),
('May or may not'),
('May park at'),
('May park in'),
('May park on'),
('May potentially'),
('May show'),
('May soon'),
('May sue'),
('May the'),
('May together'),
('May unduly'),
('May vary'),
('May well'),
('May without'),
('Mayor of London'),
('Mcpj'),
('Meager credit'),
('Meat packer'),
('Median age'),
('Meow'),
('Merger deal'),
('Messing things'),
('Messing up'),
('Metre high'),
('Metre higher'),
('Metre lower'),
('Mid jan'),
('Mid june'),
('Mid march'),
('Mid may'),
('Middle school'),
('Midi'),
('Militia'),
('Mini'),
('Monte carlo simulation'),
('Month of april'),
('Month of may'),
('Month of jan'),
('Month of june'),
('More miles'),
('More pressing'),
('More weeks'),
('Much smaller'),
('Much snow'),
('Muddle through'),
('Muddy'),
('Muesli'),
('Multi'),
('Murky brown'),
('Muscle strands'),
('Musky'),
('My calendar'),
('My heart'),
('My lips'),
('Nailing down'),
('Narco'),
('Nazi'),
('Nearby camp'),
('Neon'),
('Next'),
('Next april'),
('Next autumn'),
('Next jan'),
('Next june'),
('Next may'),
('New bonds'),
('new deal'),
('New lows'),
('New snow'),
('New way to'),
('News story'),
('Nicer guy'),
('Ninja'),
('Ninjas'),
('No biggie'),
('Noel'),
('Noncombat'),
('Normal pace'),
('Northern city'),
('Northern town'),
('Northern village'),
('Not grant'),
('Notch above'),
('Notch below'),
('Noun'),
('Nova'),
('Nutmeg'),
('Of bonds'),
('Of court'),
('Of fries'),
('Of greater'),
('Of hope'),
('Of jan'),
('Of june'),
('Of march'),
('Of may'),
('Of miles'),
('Of plant'),
('Of summers'),
('Of the ashes'),
('Of the ball'),
('Of the end'),
('Of the joint'),
('Of the osprey'),
('Of the rise'),
('Of weeks'),
('Off the front'),
('Off the hook'),
('Offal'),
('Oh my'),
('Oh well'),
('Oil fields'),
('Okay'),
('Old gal'),
('Old guy'),
('Old couple'),
('On black'),
('On boards'),
('On deal'),
('On page'),
('On the corner'),
('On the downside'),
('On the hill'),
('On the hook'),
('On the island'),
('On the lookout'),
('On the moon'),
('On the rise'),
('On the sly'),
('On the stack'),
('Once mighty'),
('One chance'),
('One page'),
('One way'),
('Onto the island'),
('Only chance'),
('Onto'),
('Opening paragraph'),
('Option grant'),
('Orca'),
('Original deal'),
('Orphan'),
('Oscar winning'),
('Other postal'),
('Ouija board'),
('Ouija boards'),
('Our chances'),
('Outgo'),
('Outswam'),
('Oval office'),
('Over riding'),
('Over steep'),
('Over stepping'),
('Over the counter'),
('Over the course of'),
('Over weeks'),
('Overawe'),
('Overmix'),
('Overnight lows'),
('Pace through'),
('Page at'),
('Page on'),
('Page to'),
('Page using'),
('Page version'),
('Palsy'),
('Package deal'),
('Paprika'),
('Paracetamol'),
('Parka'),
('Parks at'),
('Parks by'),
('Parks near'),
('Parks on'),
('Passersby'),
('Past weeks'),
('Pasta alfredo'),
('Pastures for'),
('Patches of'),
('Pay down the'),
('Payee'),
('Payoff'),
('Peak weeks'),
('Pearl Harbor'),
('Penne'),
('Pelvic'),
('Pesky'),
('Per page'),
('Per pound'),
('Percent bonds'),
('Permanently ground'),
('Personal story'),
('Perv'),
('Phone bill'),
('Physio'),
('Piazza'),
('Pickaxe'),
('Pinch on'),
('Pinch the'),
('Pinching yourself'),
('Pita'),
('Piles of'),
('Pizza'),
('Pizzaz'),
('Place down here'),
('Place down there'),
('Plain vanilla'),
('Plaintext'),
('Plant pots'),
('Plant will'),
('Plant volume'),
('Plateau that'),
('Play rugby'),
('Playing rugby'),
('Plays rugby'),
('Playoff'),
('Pleb'),
('Plod'),
('Poem'),
('Poet'),
('Pogrom'),
('Poleaxe'),
('Polio'),
('Polling booth'),
('Polo'),
('Polyp'),
('Port of call'),
('Portfolio'),
('Ports docks'),
('Positive story'),
('Pound sterling'),
('Powder snow'),
('Power plant'),
('Powers to'),
('Prefab'),
('Prelim'),
('Premix'),
('President level'),
('Pretext'),
('Price in'),
('Price may'),
('Prima facie'),
('Prior deal'),
('Pro rata'),
('Prod'),
('Prom'),
('Promo'),
('Pronoun'),
('Psych'),
('Psyche'),
('Psycho'),
('Public Health England'),
('Pull the ball'),
('Pullup'),
('Pushtrod'),
('Quad'),
('Queue'),
('Quick halt'),
('Quick pace'),
('Quota'),
('Ramrod'),
('Rapid halt'),
('Rapid pace'),
('Rash of'),
('Razor'),
('Reached the dock'),
('Read the joint'),
('Reading about'),
('Reading books'),
('Reading excerpts'),
('Reading from'),
('Reading her'),
('Reading his'),
('Reading my'),
('Reading the'),
('Reading their'),
('Reading this'),
('Reading your'),
('Readings by'),
('Readings of'),
('Rebel song'),
('Recent weeks'),
('Redux'),
('Reform bill'),
('Registrar'),
('Related fields'),
('Remix'),
('Repo'),
('Resculpt'),
('Resolve disputes'),
('Resow'),
('Revenue bonds'),
('Revenue rose'),
('Rib'),
('Rich fields'),
('Rich premium'), 
('Rich premiums'),
('Riding on'),
('Rips up'),
('Risky'),
('Road closure'),
('Road closures'),
('Road down to'),
('Rock stars'),
('Rod for'),
('Rod to'),
('Rodeo'),
('Roller coaster'),
('Rollmop'),
('Roman catholic'),
('Romp through'),
('Rose almost'),
('Rose by'),
('Rose marginally'),
('Rose slightly'),
('Rose to'),
('Rota'),
('Round trip'),
('Round trips'),
('Row over'),
('Rrom'),
('Rub'),
('Ruckus'),
('Rugby club'),
('Rugby clubs'),
('Rugby football'),
('Rugby league'),
('Rugby player'),
('Rugby players'),
('Rugby sevens'),
('Rugby union'),
('Run down'),
('Rushed to'),
('Rushing into'),
('Rushing to'),
('Rushing water'),
('Rye'),
('Saga'),
('Sail from'),
('Sail out'),
('Sail to'),
('Salt cavern'),
('Same page'),
('Sandwich'),
('Sang about'),
('Santa claus'),
('Satisfy'),
('Satnav'),
('Sea wall'),
('Second reading'),
('Secondary school'),
('Security holdings'),
('Sellers of'),
('Sellers to'),
('Sellers who'),
('Selling bonds'),
('Semi'),
('Sensei'),
('Serve burgers'),
('Set forth'),
('Set to batter'),
('Several weeks'),
('Shag'),
('Sharp decline'),
('Sharp discount'),
('Sharp drop'),
('Sharp fall'),
('Sharp turn'),
('Sharpness of'),
('Shares rose'),
('Sharper than'),
('She may'),
('She sang'),
('She will'),
('She won'),
('Shoes'),
('Shoo in'),
('Shoring up'),
('Short circuit'),
('Short term'),
('Shriek'),
('Shrub'),
('Schnitzel'),
('School day'),
('Scrub'),
('Scuba'),
('Sculpt'),
('Sift through'),
('Sigma'),
('Silver stars'),
('Similar to how'),
('Since April'),
('Sit idle'),
('Slight chance'),
('Slim'),
('Slow pace'),
('Sluggish pace'),
('Slur'),
('Slut'),
('Small cliff'),
('Smaller than'),
('Smog'),
('Smug'),
('Snafu'),
('snag'),
('Snow machine'),
('Snow mobile'),
('Snub'),
('Snug'),
('Subtext'),
('Spaghetti'),
('Spanning the'),
('Sparerib'),
('Speed bumps'),
('Spelling mistake'),
('Spelling mistakes'),
('Spilling it'),
('Spinoff'),
('Splash page'),
('Squad'),
('Squab'),
('Spur'),
('Spurs opposition'),
('Sudoku'),
('Sofa'),
('Solo'),
('Some beers'),
('Some milder'),
('Southern city'),
('Southern town'),
('Southern village'),
('Summary page'),
('Summed up'),
('Summer day'),
('Summer deal'),
('Summer styles'),
('Sunrise from'),
('Superhelix'),
('Supernova'),
('Sushi'),
('Suspension bridges'),
('Stack of'),
('Stacks of'),
('Stakes in'),
('Standby'),
('Standoff'),
('Star quest'),
('Stars are'),
('Start of April'),
('Start of Jan'),
('Start of June'),
('Start of May'),
('Steel foundry'),
('Steep costs'),
('Stepping back'),
('Stew'),
('Stigma'),
('Still under way'),
('Stock holdings'),
('Stocking stuffers'),
('Stocks close higher'),
('Stocks close lower'),
('Stocks fell'),
('Stocks rose'),
('Stone cold'),
('Stooge'),
('Story about'),
('Stripe down'),
('Strut'),
('Stucco'),
('Stun'),
('Stylish way'),
('Swab'),
('Swag'),
('Swam'),
('Swan'),
('Swap'),
('Swat'),
('Sue you'),
('Symbol'),
('Tabacco'),
('Taken the liberty'),
('Takeoff'),
('Talc'),
('Taming the'),
('Tarmac'),
('Tax havens'),
('Taxi'),
('Team won'),
('Techno'),
('Tee box'),
('Tee off'),
('Teletext'),
('Television channels'),
('Term deal'),
('Text'),
('Texts'),
('Than'),
('That clause'),
('That creates'),
('That deal'),
('That guy'),
('That joins'),
('That nodal'),
('That page'),
('That sees'),
('That song'),
('That the spot'),
('That the walk'),
('That van'),
('The alter'),
('The april'),
('The autumn'),
('The ball is'),
('The bank of'),
('The bank to'),
('The battle'),
('The beam'),
('The bees'),
('The bill'),
('The blithe'),
('The bloc'),
('The bonds'),
('The boulder'),
('The bow'),
('The buffalo'),
('The calendar'),
('The calls to'),
('The camp'),
('The cash'),
('The cashier'),
('The chance'),
('The childs'),
('The clouds'),
('The connection is'),
('The copier'),
('The course of'),
('The course that'),
('The couch'),
('The court of'),
('The court to'),
('The court will'),
('The christmas'),
('The crew'),
('The deal'),
('The dial in'),
('The easter'),
('The edge of'),
('The eggs'),
('The elbow'),
('The fleet'),
('The ferry'),
('The folders specified'),
('The front of'),
('The front office'),
('The front page'),
('The front room'),
('The gang'),
('The gorge'),
('The grant'),
('The grass'),
('The greater'),
('The guy'),
('The hall to'),
('The heavenly'),
('The heck'),
('The hem'),
('The high crest'),
('The high end'),
('The higher end'),
('The hope'),
('The hood'),
('The land is'),
('The light at'),
('The light load'),
('The loop on'),
('The low end'),
('The lower end'),
('The jan'),
('The jedi'),
('The june'),
('The key element'),
('The key ingredient'),
('The key is'),
('The key issue'),
('The key to'),
('The king'),
('The kitchen'),
('The main front'),
('The march'),
('The mark'),
('The may'),
('The max'),
('The middle of'),
('The miles'),
('The moon'),
('The new'),
('The new site'),
('The pace'),
('The page'),
('The peak hours'),
('The peculiar'),
('The piece between'),
('The plain truth'),
('The plant'),
('The plant would'),
('The point is'),
('The point that'),
('The points which'),
('The pool'),
('The puncher'),
('The prospect of'),
('The prospect that'),
('The rally seemed'),
('The range of'),
('The reins'),
('The rest of'),
('The retreat was'),
('The rise in'),
('The roads'),
('The royal bank'),
('The run of'),
('The seashore'),
('The sellers'),
('The short time'),
('The snow'),
('The swallow'),
('The song'),
('The sound of'),
('The south side'),
('The spring'),
('The spur of'),
('The stakes are'),
('The stock down'),
('The story'),
('The summers'),
('The sun'),
('The tally'),
('The tenor'),
('The tanking'),
('The ticker'),
('The upper hand'),
('The usher'),
('The van'),
('The verge of'),
('The waiter'),
('The walk goes'),
('The walk to'),
('The way'),
('The weeks'),
('The west side'),
('The whack'),
('The winters'),
('The works of'),
('Their borders'),
('Then the forest'),
('There will'),
('They'),
('They may'),
('They sang'),
('They will'),
('This april'),
('This deal'),
('This grant'),
('This guy'),
('This page'),
('This jan'),
('This june'),
('This may'),
('This autumn'),
('This christmas'),
('This childs'),
('This easter'),
('This rod'),
('This story'),
('This sun'),
('This traverse'),
('This will'),
('This won'),
('Thou'),
('Through the model'),
('Thud'),
('Ticket booth'),
('Tier that'),
('Tightwad'),
('Tipper lorry'),
('Tiptoes'),
('To block the'),
('To camp'),
('To chance'),
('To clink'),
('To grant'),
('To hoard'),
('To lavish'),
('To lodge'),
('To quell'),
('To march'),
('To mark the'),
('To pay down'),
('To plant'),
('To plow'),
('To prosper'),
('To rebut'),
('To rout'),
('To stoke'),
('To tailor'),
('To the bar'),
('To the edge'),
('To the forest'),
('To the heart'),
('To the new common'),
('To the joint'),
('To the peak'),
('To the plant'),
('To the point in'),
('To the point when'),
('To the point where'),
('To the rest'),
('To the round'),
('To tilt'),
('To tote'),
('To uphold'),
('To vent'),
('To wear'),
('Tobacco'),
('Toes'),
('Toga'),
('Told callers'),
('Tomato'),
('Tonic for'),
('Tonne'),
('Too bad'),
('Too low'),
('Top level'),
('Top notch'),
('Top story'),
('Top will'),
('Tore her'),
('Tore his'),
('Tore my'),
('Tore out'),
('Towns battle'),
('Trade credit'),
('Trade credits'),
('Trade deal'),
('Tradeoff'),
('Trading deal'),
('Trek'),
('Tree saplings'),
('Trial court'),
('Trickle out'),
('Trickle to'),
('Trustworthy basis'),
('Tsetse'),
('Turned the corner'),
('Twat'),
('Under way on'),
('Unesco'),
('Unjam'),
('Until autumn'),
('Until spring'),
('Untrod'),
('Unzip'),
('Upper chamber'),
('Urethra'),
('Vantage point'),
('Vermicelli'),
('Vehicle fleet'),
('Vessels'),
('Via courier'),
('Vice versa'),
('Video'),
('Vigilante'),
('Vindaloo'),
('Vodka'),
('Voting booth'),
('Vulva'),
('Wad'),
('Wag'),
('Waif'),
('Wap'),
('Walk back'),
('walk way'),
('Walls above'),
('Wanna'),
('Warmth'),
('Warmup'),
('Warns of'),
('Was down'),
('Was idle'),
('Was stolen'),
('Wash in'),
('Water bottles'),
('Waterski'),
('Way round'),
('We drew'),
('We hope'),
('We hung'),
('We may'),
('Wear what'),
('Wear white'),
('Web page'),
('Well and were'),
('Well underway'),
('Week low'),
('Weeks ago'),
('Weeks of'),
('Weeks to'),
('Were down'),
('Were low'),
('Were under way'),
('Wetter than'),
('WhatsApp'),
('Whelk'),
('When will'),
('Where grass'),
('Which'),
('Which borders'),
('Which wood'),
('While sellers'),
('Whisky'),
('Who love'),
('Who styles'),
('Who will'),
('Wholesale sellers'),
('Wigwam'),
('Wild card'),
('Wild goose'),
('Will also'),
('Will likely'),
('Will necessarily'),
('Will not'),
('Will now'),
('Will then'),
('Will wear'),
('Will you'),
('Wind down'),
('Winding down'),
('Wings are'),
('Wings have'),
('Wins a'),
('Winter day'),
('Winter deal'),
('With rich'),
('With smaller'),
('With the court'),
('With the high'),
('Within the bounds'),
('Without reading'),
('Wireless LAN'),
('Wombat'),
('Won her'),
('Won his'),
('Won the'),
('Wood chips'),
('Work crew'),
('Work will'),
('World fleet'),
('Worthy cause'),
('Worthy causes'),
('Worthy of'),
('Would hurt'),
('Would settle'),
('Would sue'),
('Would wear'),
('Writeoff'),
('Year lows'),
('Year old'),
('Years eve'),
('Yerba'),
('Yoga'),
('You may'),
('You will'),
('Yougov'),
('Your earthly'),
('Your grant'),
('Your heart'),
('Your knuckles'),
('Your sins');
-- Down
DELETE FROM Skip;