-- Up
INSERT INTO Part (keyword)
VALUES
('A batch'),
('A black belt'),
('A black hole'),
('A boulder'),
('A buddy'),
('A chance'),
('A Christmas'),
('A clear view'),
('A day'),
('A deep pit'),
('A dot'),
('A fairer'),
('A flurry'),
('A glass'),
('A gorge'),
('A greater'),
('A guest'),
('A guy'),
('A heap'),
('A king'),
('A knock'),
('A long walk'),
('A love'),
('A page'),
('A peculiar'),
('A postal'),
('A pound'),
('A price'),
('A mini'),
('A north'),
('A ridge'),
('A savanna'),
('A south'),
('A stellar'),
('A steep'),
('A story'),
('A thorn'),
('A west'),
('A wholly'),
('A windy'),
('A young'),
('Accompany the exchange'),
('Against the wall'),
('Akin to'),
('All day'),
('All roses'),
('All stripes'),
('All the points'),
('All the way'),
('All the wood'),
('All tier'),
('All westward'),
('Alleged price'),
('Along the way'),
('Am holding'),
('An east'),
('And banks'),
('And bonds'),
('And day'),
('And holding'),
('And price'),
('And snow'),
('And the campus'),
('And the place'),
('And the way'),
('And trucks'),
('And mingle'),
('Snow machine'),
('Snow mobile'),
('Summer and winter'),
('Another chance'),
('Another day'),
('Approved the deals'),
('Are angels'),
('Are low'),
('Arts majors'),
('As the line'),
('As well as cash'),
('Assembly bill'),
('At the back'),
('At the ball'),
('At the bank'),
('At the course'),
('At the cross roads'),
('At the helm'),
('At the front'),
('At the mercy'),
('At the spa'),
('Audio channels'),
('Autumn camp'),
('Autumn season'),
('Average price'),
('Awesome day'),
('Back to back'),
('Bad winter'),
('Banks about'),
('Banks are'),
('Banks by'),
('Banks for'),
('Banks have'),
('Banks may'),
('Banks normally'),
('Banks offer'),
('Banks to'),
('Bark some'),
('Bars and restaurants'),
('Be fearing'),
('Be holding'),
('Beautiful flowers'),
('Been barefoot'),
('Before Christmas'),
('Began tembling'),
('Beta testing'),
('Better day'),
('Big guy'),
('Bigger fish to fry'),
('Bill of'),
('Black beans'),
('Black box'),
('Black eye'),
('Black man'),
('Black market'),
('Black men'),
('Black olives'),
('Black woman'),
('Black women'),
('Blunt instrument'),
('Blunt refusal'),
('Bonds are'),
('Bonds at'),
('Bonds because'),
('Bonds could'),
('Bonds due'),
('Bonds fell'),
('Bonds have'),
('Bonds in'),
('Bonds now'),
('Bonds that'),
('Bonds traded'),
('Bonds which'),
('Booth at'),
('Both knuckles'),
('Bottles of'),
('Bows out'),
('Boxing day'),
('Brace for'),
('Brings a'),
('Brings an'),
('British ambassador'),
('Brotherhood of'),
('Brown bag'),
('By cash'),
('By chance'),
('By compass'),
('By larger'),
('By price'),
('By the way'),
('Caller id'),
('Camp at'),
('Camp by'),
('Camp will'),
('Can rebut'),
('Cash and futures'),
('Cash flow'),
('Cash income'),
('Cash payment'),
('Cash payments'),
('Cash traders'),
('Cavalier attitude'),
('Center south'),
('Centers to'),
('Challenging pace'),
('Chamber of'),
('Change the connection'),
('Change the statutes'),
('Chance of'),
('Channels have'),
('Click on the link'),
('Chili'),
('Cold winters'),
('Corf'),
('Corporate bonds'),
('Cover story'),
('Couple of weeks'),
('Checking the list'),
('Cranberry sauce'),
('Crimes against'),
('Christmas concert'),
('Christmas day'),
('Christmas party'),
('Christmas with'),
('Cross any'),
('Crown jewel'),
('Crown jewels'),
('Current median'),
('Cutting a'),
('Cutting an'),
('Cutting back'),
('Cutting the'),
('Daily price'),
('Data grabber'),
('Dawn of time'),
('Day-to-day'),
('Day to day'),
('Day-ahead'),
('Day ahead'),
('Day before'),
('Day camp'),
('Day care'),
('Day centre'),
('Day holiday'),
('Day min'),
('Day rally'),
('Day to'),
('Day trades'),
('Dean of'),
('Deep snow'),
('Demand peaks'),
('Dense woods'),
('Dining hall'),
('Disputes over'),
('Ditch someone'),
('Docking station'),
('Dolby digital'),
('Double chevron'),
('Down the drain'),
('Down the valley'),
('Draws for'),
('Draws of'),
('Dreams of'),
('Drive east'),
('Drive north'),
('Drive south'),
('Drive west'),
('East and west'),
('East coast'),
('East of'),
('East of the'),
('East from'),
('Each camp'),
('Each day'),
('Each love'),
('Each westward'),
('Early April'),
('Early June'),
('Early May'),
('Earner for'),
('Echo'),
('Ended April'),
('Ended June'),
('Ended May'),
('Enough booze'),
('Entire day'),
('Escape hatch'),
('Et al'),
('Even bigger'),
('Evenly among'),
('Eventual price'),
('Every angle'),
('Every autumn'),
('Every day'),
('Every kitchen'),
('Every summer'),
('Every winter'),
('Exhibit hall'),
('Exit day'),
('Experience gross'),
('Faint of heart'),
('Fairy tale'),
('Faith in'),
('Fall from grace'),
('Fallen angels'),
('Fajita'),
('Far larger'),
('Fast pace'),
('Ferry terminal'),
('Few weeks'),
('Fighting chance'),
('Fill the gap'),
('Finished April'),
('Finished June'),
('Finished May'),
('First brushes'),
('First dibs'),
('Fixed price'),
('Follow the steps'),
('For day'),
('For greater'),
('For love'),
('For the campus'),
('For the front'),
('For the deals'),
('For the stocks'),
('For west'),
('Foray into'),
('Free will'),
('From day'),
('From the mill'),
('Front page'),
('Full story'),
('Garners respect'),
('Gas fields'),
('Gave way'),
('Given greater'),
('Goings on'),
('Gold coin'),
('Gold coins'),
('Gold star'),
('Gold stars'),
('Good cook'),
('Good day'),
('Good faith'),
('Good lord'),
('Good will'),
('Grace period'),
('Graffiti'),
('Grant agreement'),
('Grant similar'),
('Graphic novel'),
('Graphic novels'),
('Great day'),
('Great guy'),
('Green earth'),
('Green light'),
('Green power'),
('Gross profit'),
('Gross profits'),
('Half price'),
('Hanky panky'),
('Have price'),
('Have snow'),
('Have the plain'),
('Have won'),
('He heard'),
('He may'),
('He sang'),
('He will'),
('Head east'),
('Head north'),
('Head south'),
('Head west'),
('Heart attack'),
('Heart attacks'),
('Heart disease'),
('Heart failure'),
('Heart failures'),
('Hedges against'),
('Hedging a'),
('Hedging bets'),
('Hedging deals'),
('Hedging transactions'),
('Hee hee'),
('Her scarlet'),
('High plateau'),
('His hope'),
('His love'),
('His price'),
('His will'),
('Hit the fan'),
('Holding a'),
('Holding company'),
('Holding of'),
('Holding period'),
('Holding the'),
('Holding up'),
('Holdings completely'),
('Hollering like'),
('Hope all'),
('Hope among'),
('Hope everyone'),
('Hope everything'),
('Hope for'),
('Hope that'),
('Hope the'),
('Hope things'),
('Hope to'),
('Hope you'),
('Hour price'),
('Hot ember'),
('Hot summer'),
('Hover around'),
('Hover at'),
('How peculiar'),
('Huddle with'),
('Hung out'),
('Hurt her'),
('Hurt him'),
('Hurt the'),
('Hurt them'),
('I heard'),
('I hope'),
('I love'),
('I may'),
('I will'),
('It may'),
('It will'),
('Its bonds'),
('Its price'),
('Its stocks'),
('In bonds'),
('In cash'),
('In Jan'),
('In April'),
('In flux'),
('In June'),
('In May'),
('In ruins'),
('In the autumn'),
('In the back'),
('In the bank'),
('In the college'),
('In the coming weeks'),
('In the corner'),
('In the end'),
('In the forehead'),
('In the forest'),
('In the front'),
('In the heart'),
('In the hopes'),
('In the list'),
('In the long run'),
('In the low'),
('In the joint'),
('In the park'),
('In the run'),
('In the spot'),
('In the spring'),
('In the still'),
('In the summer'),
('In the walk'),
('In the winter'),
('In the wood'),
('In the works'),
('Index price'),
('Investment banks'),
('Is idle'),
('Is reading'),
('Issue bonds'),
('Jot those'),
('Junk bonds'),
('Just love'),
('Keen To'),
('King and queen'),
('Lane judges'),
('Last day'),
('Last Jan'),
('Last June'),
('Last May'),
('Last Autumn'),
('Last Christmas'),
('Last Easter'),
('Last road'),
('Last Summer'),
('Last Winter'),
('Later day'),
('Launch day'),
('Lay off'),
('Lead banks'),
('Leap of'),
('Left the trees'),
('Liability clause'),
('Light trucks'),
('Like price'),
('Locks are'),
('Locks have'),
('Long day'),
('Lose faith'),
('Loses faith'),
('Lost faith'),
('Love and support'),
('Love by'),
('Love if'),
('Love it'),
('Love song'),
('Love with'),
('Love you'),
('Low cost'),
('Low daily'),
('Low price'),
('Low rank'),
('Low ranking'),
('Lower price'),
('Lowest price'),
('Lowest rung'),
('Lows expected'),
('Lows in'),
('Lows of'),
('Made camp'),
('March or April'),
('Mark discrepancy'),
('Marks for'),
('Matter of weeks'),
('Max number'),
('Max rate'),
('May I'),
('May add'),
('May already'),
('May also'),
('May apply'),
('May be'),
('May come'),
('May concern'),
('May contain'),
('May have'),
('May love'),
('May not'),
('May now'),
('May only'),
('May or may not'),
('May park at'),
('May park in'),
('May park on'),
('May potentially'),
('May show'),
('May soon'),
('May together'),
('May unduly'),
('May vary'),
('May well'),
('Meager credit'),
('Median age'),
('Monte-Carlo simulation'),
('Monte Carlo simulation'),
('Month of April'),
('Month of May'),
('Month of Jan'),
('Month of June'),
('More cash'),
('More miles'),
('More weeks'),
('Much smaller'),
('Much snow'),
('Muddle through'),
('Murky brown'),
('Muscle strands'),
('My calendar'),
('My heart'),
('My hope'),
('My lips'),
('My love'),
('My price'),
('My will'),
('Nailing down'),
('Nazi'),
('Near the close'),
('Nearby camp'),
('Next autumn'),
('Next day'),
('Next road'),
('Next summer'),
('Next winter'),
('New bonds'),
('New lows'),
('New snow'),
('News story'),
('No biggie'),
('Normal pace'),
('Normal summer'),
('North and south'),
('North of'),
('North of the'),
('North from'),
('Notch above'),
('Notch below'),
('Of banks'),
('Of bonds'),
('Of day'),
('Of fries'),
('Of love'),
('Of joy'),
('Of miles'),
('Of price'),
('Of summers'),
('Of the ashes'),
('Of the ball'),
('Of the bank'),
('Of the banks'),
('Of the common'),
('Of the deals'),
('Of the end'),
('Of the island'),
('Of the loan'),
('Of the line'),
('Of the links'),
('Of the joint'),
('Of the osprey'),
('Of the rise'),
('Of the settlement'),
('Of the short'),
('Of the tunnel'),
('Of the way'),
('Off the loan'),
('Off the hook'),
('Offer price'),
('Once mighty'),
('Onto the island'),
('Old gal'),
('Old guy'),
('On black'),
('On day'),
('On love'),
('On page'),
('On the back'),
('On the beach'),
('On the corner'),
('On the hook'),
('On the island'),
('On the line'),
('On the list'),
('On the lookout'),
('On the moon'),
('On the rise'),
('On the shore'),
('On the way'),
('On white'),
('Only chance'),
('Only will it'),
('One day'),
('Option grant'),
('Other postal'),
('Our chances'),
('Our east'),
('Our hope'),
('Our love'),
('Our north'),
('Our price'),
('Our south'),
('Our west'),
('Our winter'),
('Out east'),
('Out north'),
('Out south'),
('Out west'),
('Oval office'),
('Over steep'),
('Over the course of'),
('Overnight lows'),
('Pace through'),
('Page at the'),
('Page to'),
('Page using'),
('Parks at'),
('Parks by'),
('Parks near'),
('Parks on'),
('Pastures for'),
('Patches of'),
('Pay cash'),
('Pay down the'),
('Peak day'),
('Per day'),
('Percent bonds'),
('Pinch on'),
('Pinch the'),
('Pinching yourself'),
('Pita'),
('Piles of'),
('Plain vanilla'),
('Plant pots'),
('Plant volume'),
('Plateau that'),
('Positive story'),
('Powder snow'),
('Power plant'),
('Powers to'),
('Pressing this point'),
('Previous day'),
('Price cap'),
('Price caps'),
('Price curve'),
('Price curves'),
('Price deals'),
('Price discrepancy'),
('Price discrepancies'),
('Price forecasts'),
('Price fluctuations'),
('Price for'),
('Price increase'),
('Price increases'),
('Price index'),
('Price may'),
('Price per'),
('Price of'),
('Price range'),
('Price risk'),
('Price this'),
('Price to'),
('Price volatility'),
('Price within'),
('Prices sank'),
('Prima facie'),
('Prior day'),
('Pro rata'),
('Psycho'),
('Pull the ball'),
('Purchase price'),
('Quick halt'),
('Quick pace'),
('Rapid halt'),
('Rapid pace'),
('Rash of'),
('Ray of hope'),
('Reached the dock'),
('Reading about'),
('Reading excerpts'),
('Reading from'),
('Reading her'),
('Reading his'),
('Reading my'),
('Reading their'),
('Reading your'),
('Readings by'),
('Readings of'),
('Recent weeks'),
('Red glow'),
('Related fields'),
('Repay the loan'),
('Revenue rose'),
('Rich fields'),
('Rock stars'),
('Rod for'),
('Rod to'),
('Roman catholic'),
('Romp through'),
('Rose by'),
('Rose marginally'),
('Rose slightly'),
('Run the way'),
('Rushed to'),
('Rushing into'),
('Rushing to'),
('Rushing water'),
('Sail from'),
('Sail out'),
('Sail to'),
('Sales price'),
('Salt cavern'),
('Same day'),
('Sang about'),
('Security holdings'),
('Selling bonds'),
('Serve burgers'),
('Several weeks'),
('Sharp decline'),
('Sharp discount'),
('Sharp drop'),
('Sharp fall'),
('Sharp turn'),
('Share price'),
('She heard'),
('She may'),
('She sang'),
('She will'),
('Shoring up'),
('Silver coin'),
('Silver coins'),
('Silver star'),
('Silver stars'),
('Sincerely hope'),
('Sit idle'),
('Slow pace'),
('Small cliff'),
('Splash page'),
('Spanning the'),
('So overly'),
('Some banks'),
('Some beers'),
('Some milder'),
('Summary page'),
('Summed up'),
('Summer of'),
('Summer months'),
('Summer track'),
('Sunny day'),
('Sunrise from'),
('Supernova'),
('Suspension bridges'),
('South of'),
('South of the'),
('South from'),
('Stack of'),
('Stacks of'),
('Stakes in'),
('Staring at'),
('Steep costs'),
('Still under way'),
('Stock price'),
('Stocks and bonds'),
('Stocks at'),
('Stocks close higher'),
('Stocks close lower'),
('Stocks fell'),
('Stocks of'),
('Stocks on'),
('Stocks rose'),
('Stocks were'),
('Story about'),
('Sue you'),
('Summer camp'),
('Summer season'),
('Take heart'),
('Taming the'),
('Target price'),
('Tee box'),
('Terrible day'),
('Tee off'),
('Television channels'),
('That banks'),
('That creates'),
('That day'),
('That guy'),
('That love'),
('That price'),
('That sees'),
('That song'),
('That the spot'),
('That van'),
('The alter'),
('The april'),
('The autumn'),
('The bank to'),
('The bees'),
('The bill'),
('The bonds'),
('The boulder'),
('The calls to'),
('The camp'),
('The cashier'),
('The chance'),
('The clouds'),
('The connection is'),
('The course of'),
('The course that'),
('The couch'),
('The courts are'),
('The courts will'),
('The Christmas'),
('The crew'),
('The cross country'),
('The curve been'),
('The curve on'),
('The day'),
('The deals all'),
('The deals are'),
('The deals were'),
('The East'),
('The Easter'),
('The edge of'),
('The elbow'),
('The end of'),
('The ferry'),
('The folders specified'),
('The front of'),
('The front office'),
('The front page'),
('The front room'),
('The gap was'),
('The gap went'),
('The gold'),
('The gorge'),
('The grant'),
('The grass'),
('The guest'),
('The guy'),
('The hall to'),
('The heavenly'),
('The heck'),
('The hem'),
('The high crest'),
('The hope'),
('The land is'),
('The larger'),
('The light at'),
('The light load'),
('The line at'),
('The line with'),
('The list above'),
('The list of'),
('The loan relates'),
('The loop on'),
('The love'),
('The low end'),
('The low values'),
('The low point'),
('The lower end'),
('The jan'),
('The june'),
('The key is'),
('The key to'),
('The king'),
('The mark'),
('The may'),
('The max'),
('The miles'),
('The moon'),
('The new'),
('The new site'),
('The North'),
('The outlook for'),
('The outlook on'),
('The pace'),
('The peak hours'),
('The peculiar'),
('The place I'),
('The place he'),
('The place she'),
('The place to'),
('The place we'),
('The place you'),
('The plain truth'),
('The plant is'),
('The plant would'),
('The plateau that'),
('The point is'),
('The point of'),
('The point that'),
('The points which'),
('The puncher'),
('The price'),
('The prince'),
('The prospect of'),
('The prospect that'),
('The rally seemed'),
('The rest of'),
('The resolution of'),
('The road'),
('The roads'),
('The royal bank'),
('The run of'),
('The settlement also'),
('The settlement is'),
('The square root'),
('The slides that'),
('The snow'),
('The east side'),
('The north side'),
('The song'),
('The sound of'),
('The south side'),
('The way I'),
('The way it'),
('The way she'),
('The way they'),
('The way we'),
('The whack'),
('The west side'),
('The works of'),
('The South'),
('The Spring Festival'),
('The spur of'),
('The stock down'),
('The stone'),
('The story'),
('The Summer'),
('The sun'),
('The tally'),
('The tenor'),
('The tanking'),
('The ticker'),
('The usher'),
('The van'),
('The waiter'),
('The walk goes'),
('The walk to'),
('The way around'),
('The way back'),
('The way from'),
('The way of'),
('The way to'),
('The West'),
('The weeks'),
('The Winter'),
('Then the forest'),
('They heard'),
('They hope'),
('They love'),
('They may'),
('They sang'),
('They will'),
('This April'),
('This day'),
('This love'),
('This grant'),
('This guy'),
('This page'),
('This price'),
('This Jan'),
('This June'),
('This May'),
('This Autumn'),
('This Christmas'),
('This Easter'),
('This road'),
('This story'),
('This summer'),
('This sun'),
('This traverse'),
('This will'),
('This Winter'),
('This won'),
('Thou'),
('Through the gap'),
('Ticket booth'),
('Tier that'),
('To be cash'),
('To camp'),
('To clink'),
('To cross'),
('To day'),
('To hurt'),
('To quell'),
('To mark the'),
('To pay down'),
('To price'),
('To prosper'),
('To rebut'),
('To rout'),
('To tailor'),
('To the back'),
('To the bar'),
('To the edge'),
('To the forest'),
('To the heart'),
('To the new common'),
('To the joint'),
('To the peak'),
('To the plant'),
('To the point in'),
('To the point of'),
('To the point when'),
('To the point where'),
('To the rest'),
('To the round'),
('To the valley'),
('To the village'),
('To tote'),
('To uphold'),
('To vent'),
('Tonic for'),
('Too low'),
('Top story'),
('Tore out'),
('Trade credit'),
('Trade credits'),
('Tradition christmas'),
('Tree saplings'),
('Trickle out'),
('Trickle to'),
('Troop of'),
('Trustworthy basis'),
('Turned the corner'),
('Under way on'),
('Until autumn'),
('Until spring'),
('Until summer'),
('Until winter'),
('Various banks'),
('Vehicle fleet'),
('Walls above'),
('Wanna go'),
('Was day'),
('Was idle'),
('Was stolen'),
('Water bottles'),
('We drew'),
('We hope'),
('We hung'),
('We love'),
('We may'),
('We will'),
('Web page'),
('Well underway'),
('Week low'),
('Weeks ago'),
('Weeks of'),
('Weeks to'),
('West coast'),
('West of'),
('West of the'),
('West from'),
('West wing'),
('Wetter than'),
('What road'),
('When will'),
('Where grass'),
('Which road'),
('Which will'),
('White man'),
('White men'),
('White shirt'),
('White woman'),
('White women'),
('Who will'),
('Whom will'),
('Wild goose'),
('Will a lack'),
('Will actually'),
('will adequately'),
('Will add'),
('Will almost'),
('Will also'),
('Will always'),
('Will back'),
('Will be'),
('Will certainly'),
('Will definitely'),
('Will do'),
('Will have'),
('Will finally'),
('Will forever'),
('Will forward'),
('Will he'),
('Will help'),
('Will her'),
('Will I'),
('Will instead'),
('Will just'),
('Will likely'),
('Will make'),
('Will meet'),
('Will most'),
('Will need'),
('Will never'),
('Will no'),
('Will not'),
('Will now'),
('Will open'),
('Will once'),
('Will only'),
('Will pro'),
('Will probably'),
('Will regularly'),
('Will resend'),
('Will ruefully'),
('Will significantly'),
('Will she'),
('Will still'),
('Will the'),
('Will their'),
('Will they'),
('Will then'),
('Will this'),
('Will transition'),
('Will waive'),
('Will you'),
('Will your'),
('Wings are'),
('Wings have'),
('Winter camp'),
('Winter months'),
('Winter period'),
('Winter season'),
('With banks'),
('With rich'),
('With smaller'),
('Wireless LAN'),
('Wood chips'),
('Work day'),
('Worthy of'),
('Would sue'),
('Year lows'),
('Years eve'),
('You cook'),
('You love'),
('You may'),
('You will'),
('Young adult'),
('Young adults'),
('Young baby'),
('Young boy'),
('Young gal'),
('Young girl'),
('Young guy'),
('Young males'),
('Young man'),
('Young men'),
('Young people'),
('Young person'),
('Young professionals'),
('Young volunteers'),
('Young woman'),
('Young women'),
('Your day'),
('Your heart'),
('Your grant'),
('Your knuckles'),
('Your price'),
('Your hope');
-- Down
DELETE FROM Part;