-- Up
INSERT INTO Part (keyword)
VALUES
('A buddy'),
('A Christmas'),
('A day'),
('A guy'),
('A heap'),
('A love'),
('A price'),
('A north'),
('A south'),
('A west'),
('Across the street'),
('All day'),
('All roses'),
('Alleged price'),
('Along the way'),
('Am holding'),
('An east'),
('And the place'),
('At the back'),
('At the bank'),
('At the front'),
('At the spa'),
('Audio channels'),
('Autumn season'),
('Average price'),
('Awesome day'),
('Banks are'),
('Bark some'),
('Be holding'),
('Beautiful flowers'),
('Before Christmas'),
('Best price'),
('Bill of'),
('Black olives'),
('Blunt refusal'),
('Bows out'),
('Boxing day'),
('Brings a'),
('Brings an'),
('British ambassador'),
('Brown bag'),
('By chance'),
('By price'),
('By the way'),
('Camp at'),
('Camp by'),
('Centers to'),
('Chamber of'),
('Click on the link'),
('Corf'),
('Couple of weeks'),
('Couple of weeks'),
('Checking the list'),
('Cranberry sauce'),
('Christmas day'),
('Christmas with'),
('Crown jewel'),
('Crown jewels'),
('Cutting a'),
('Cutting an'),
('Daily price'),
('Day before'),
('Day care'),
('Day centre'),
('Day holiday'),
('Day rally'),
('Down the drain'),
('Draws for'),
('Draws of'),
('Dreams of'),
('East of'),
('Each day'),
('Each love'),
('Enough booze'),
('Entire day'),
('Et al'),
('Every angle'),
('Every day'),
('Faith in'),
('Fall from grace'),
('Fajita'),
('Few weeks'),
('Fixed price'),
('For day'),
('For love'),
('For the front'),
('For west'),
('Goings on'),
('Good cook'),
('Good faith'),
('Good lord'),
('Grace period'),
('Grant agreement'),
('Great day'),
('Great guy'),
('Green light'),
('Hail a'),
('Have snow'),
('Have won'),
('He may'),
('He will'),
('Heart attack'),
('Heart attacks'),
('Heart failure'),
('Heart failures'),
('His hope'),
('His love'),
('His price'),
('His will'),
('Hollering like'),
('Hope all'),
('Hope among'),
('Hope everyone'),
('Hope everything'),
('Hope for'),
('Hope that'),
('Hope the'),
('Hope things'),
('Hope to'),
('Hope you'),
('Hot ember'),
('Hover around'),
('Hover at'),
('Huddle with'),
('I hope'),
('I love'),
('I may'),
('I will'),
('It may'),
('It will'),
('In Jan'),
('In April'),
('In June'),
('In May'),
('In the coming weeks'),
('In the back'),
('In the end'),
('In the front'),
('In the joint'),
('In the works'),
('Issue bonds'),
('Just love'),
('Keen To'),
('Last day'),
('Last Jan'),
('Last June'),
('Last May'),
('Last Autumn'),
('Last Christmas'),
('Last Easter'),
('Last Summer'),
('Last Winter'),
('Leap of'),
('Long day'),
('Lose faith'),
('Lost faith'),
('Love if'),
('Low price'),
('Lows expected'),
('Lows in'),
('Lows of'),
('Mark discrepancy'),
('Marks for'),
('May I'),
('May add'),
('May also'),
('May apply'),
('May be'),
('May come'),
('May concern'),
('May contain'),
('May have'),
('May love'),
('May not'),
('May now'),
('May park at'),
('May park in'),
('May park on'),
('May show'),
('May vary'),
('Median age'),
('Month of April'),
('Month of May'),
('Month of Jan'),
('Month of June'),
('My heart'),
('My hope'),
('My love'),
('My price'),
('My will'),
('Nailing down'),
('Next day'),
('New lows'),
('North of'),
('Of fries'),
('Of love'),
('Of joy'),
('Of the ashes'),
('Of the end'),
('Of the line'),
('Of the joint'),
('Of the tunnel'),
('Old gal'),
('Old guy'),
('On love'),
('On the back'),
('On the beach'),
('On the corner'),
('On the list'),
('On the moon'),
('On the rise'),
('On the shore'),
('On the street'),
('On the way'),
('Only will it'),
('One day'),
('Our hope'),
('Our love'),
('Our price'),
('Our west'),
('Over the course of'),
('Parks at'),
('Parks by'),
('Parks near'),
('Parks on'),
('Peak day'),
('Per day'),
('Pita'),
('Piles of'),
('Plain vanilla'),
('Positive story'),
('Powers to'),
('Previous day'),
('Price cap'),
('Price curve'),
('Price curves'),
('Price discrepancy'),
('Price discrepancies'),
('Price per'),
('Price of'),
('Price range'),
('Price to'),
('Price within'),
('Prior day'),
('Pro rata'),
('Purchase price'),
('Rash of'),
('Related fields'),
('Rock stars'),
('Rod for'),
('Rod to'),
('Sail from'),
('Sail out'),
('Sail to'),
('Sales price'),
('Same day'),
('Sang about'),
('Security holdings'),
('She may'),
('She will'),
('Sincerely hope'),
('Supernova'),
('Suspension bridges'),
('South of'),
('Stacks of'),
('Stock price'),
('Stocks at'),
('Stocks of'),
('Stocks were'),
('Story about'),
('Sue you'),
('Summer season'),
('Tee off'),
('Television channels'),
('That day'),
('That love'),
('That price'),
('That van'),
('The alter'),
('The autumn'),
('The bill'),
('The chance'),
('The course of'),
('The course that'),
('The couch'),
('The Christmas'),
('The day'),
('The East'),
('The Easter'),
('The edge of'),
('The end of'),
('The front of'),
('The grant'),
('The hall to'),
('The heck'),
('The light at'),
('The light load'),
('The list of'),
('The loop on'),
('The love'),
('The low point'),
('The Jan'),
('The June'),
('The king'),
('The mark'),
('The May'),
('The max'),
('The moon'),
('The North'),
('The peak hours'),
('The place I'),
('The place he'),
('The place she'),
('The place we'),
('The place you'),
('The point is'),
('The point of'),
('The point that'),
('The points which'),
('The price'),
('The prince'),
('The prospect of'),
('The rest of'),
('The resolution of'),
('The slides that'),
('The snow'),
('The South'),
('The spur of'),
('The street below'),
('The story'),
('The Summer'),
('The sun'),
('The tally'),
('The usher'),
('The van'),
('The waiter'),
('The walk to'),
('The way around'),
('The way back'),
('The way from'),
('The way to'),
('The West'),
('The weeks'),
('The Winter'),
('They hope'),
('They love'),
('They may'),
('They will'),
('This April'),
('This day'),
('This love'),
('This grant'),
('This guy'),
('This price'),
('This Jan'),
('This June'),
('This May'),
('This Autumn'),
('This Christmas'),
('This Easter'),
('This Summer'),
('This Winter'),
('This won'),
('Thou'),
('To the back'),
('To the edge'),
('To the street'),
('To the village'),
('Was idle'),
('We hope'),
('We love'),
('We may'),
('We will'),
('Well underway'),
('Weeks of'),
('West of'),
('When will'),
('Which will'),
('White shirt'),
('Who will'),
('Whom will'),
('Will actually'),
('Will add'),
('Will also'),
('Will back'),
('Will be'),
('Will do'),
('Will have'),
('Will forever'),
('Will forward'),
('Will he'),
('Will help'),
('Will her'),
('Will I'),
('Will instead'),
('Will just'),
('Will likely'),
('Will make'),
('Will meet'),
('Will need'),
('Will never'),
('Will no'),
('Will not'),
('Will open'),
('Will once'),
('Will only'),
('Will probably'),
('will ruefully'),
('Will she'),
('Will the'),
('Will their'),
('Will they'),
('Will then'),
('Will you'),
('Will your'),
('Winter period'),
('Winter season'),
('With rich'),
('Wireless LAN'),
('Worthy of'),
('Would sue'),
('Years eve'),
('You cook'),
('You may'),
('You will'),
('Young baby'),
('Young boy'),
('Young gal'),
('Young girl'),
('Young guy'),
('Young males'),
('Young man'),
('Young men'),
('Young people'),
('Young person'),
('Young woman'),
('Young women'),
('Your day'),
('Your heart'),
('Your grant'),
('Your price'),
('Your hope');

-- Down
DELETE FROM Part;