-- Up
INSERT INTO Part (keyword)
VALUES
('A batch'),
('A black hole'),
('A buddy'),
('A chance'),
('A Christmas'),
('A day'),
('A dot'),
('A fairer'),
('A greater'),
('A guy'),
('A heap'),
('A love'),
('A page'),
('A postal'),
('A price'),
('A mini'),
('A north'),
('A south'),
('A stellar'),
('A west'),
('Against the wall'),
('All day'),
('All roses'),
('All stripes'),
('Alleged price'),
('Along the way'),
('Am holding'),
('An east'),
('And bonds'),
('And price'),
('And the campus'),
('And the place'),
('And the way'),
('And mingle'),
('Another chance'),
('Approved the deals'),
('Arts majors'),
('At the back'),
('At the bank'),
('At the course'),
('At the helm'),
('At the front'),
('At the spa'),
('Audio channels'),
('Autumn camp'),
('Autumn season'),
('Average price'),
('Awesome day'),
('Back-to-back'),
('Banks about'),
('Banks are'),
('Banks by'),
('Banks for'),
('Banks have'),
('Banks may'),
('Banks normally'),
('Banks offer'),
('Banks to'),
('Bark some'),
('Bars and restaurants'),
('Be fearing'),
('Be holding'),
('Beautiful flowers'),
('Before Christmas'),
('Began tembling'),
('Beta testing'),
('Better day'),
('Bill of'),
('Black beans'),
('Black box'),
('Black eye'),
('Black olives'),
('Blunt instrument'),
('Blunt refusal'),
('Bonds are'),
('Bonds at'),
('Bonds because'),
('Bonds could'),
('Bonds due'),
('Bonds fell'),
('Bonds have'),
('Bonds in'),
('Bonds now'),
('Bonds that'),
('Bonds traded'),
('Bonds which'),
('Booth at'),
('Bows out'),
('Boxing day'),
('Brace for'),
('Brings a'),
('Brings an'),
('British ambassador'),
('Brown bag'),
('By chance'),
('By price'),
('By the way'),
('Camp at'),
('Camp by'),
('Camp will'),
('Centers to'),
('Chamber of'),
('Change the connection'),
('Click on the link'),
('Cold winters'),
('Corf'),
('Corporate bonds'),
('Couple of weeks'),
('Chance of'),
('Checking the list'),
('Cranberry sauce'),
('Channels have'),
('Christmas concert'),
('Christmas day'),
('Christmas party'),
('Christmas with'),
('Crown jewel'),
('Crown jewels'),
('Current median'),
('Cutting a'),
('Cutting an'),
('Cutting back'),
('Cutting the'),
('Daily price'),
('Data grabber'),
('Dawn of time'),
('Day-to-day'),
('Day ahead'),
('Day before'),
('Day camp'),
('Day care'),
('Day centre'),
('Day holiday'),
('Day rally'),
('Day to'),
('Day trades'),
('Dining hall'),
('Docking station'),
('Dolby digital'),
('Down the drain'),
('Draws for'),
('Draws of'),
('Dreams of'),
('Drive east'),
('Drive north'),
('Drive south'),
('Drive west'),
('East coast'),
('East of'),
('East from'),
('Each camp'),
('Each day'),
('Each love'),
('Early April'),
('Early June'),
('Early May'),
('Earner for'),
('Echo'),
('Ended April'),
('Ended June'),
('Ended May'),
('Enough booze'),
('Entire day'),
('Et al'),
('Even bigger'),
('Evenly among'),
('Every angle'),
('Every autumn'),
('Every day'),
('Every summer'),
('Every winter'),
('Exhibit hall'),
('Experience gross'),
('Faint of heart'),
('Fairy tale'),
('Faith in'),
('Fall from grace'),
('Fallen angels'),
('Fajita'),
('Far larger'),
('Ferry terminal'),
('Few weeks'),
('Fighting chance'),
('Fill the gap'),
('Finished April'),
('Finished June'),
('Finished May'),
('First dibs'),
('Fixed price'),
('For day'),
('For love'),
('For the front'),
('For the deals'),
('For the stocks'),
('For west'),
('Front page'),
('Full story'),
('Garners respect'),
('Gas fields'),
('Gave way'),
('Goings on'),
('Good cook'),
('Good day'),
('Good faith'),
('Good lord'),
('Good will'),
('Grace period'),
('Grant agreement'),
('Grant similar'),
('Great day'),
('Great guy'),
('Green light'),
('Gross profit'),
('Gross profits'),
('Half price'),
('Have price'),
('Have snow'),
('Have won'),
('He may'),
('He will'),
('Head east'),
('Head north'),
('Head south'),
('Head west'),
('Heart attack'),
('Heart attacks'),
('Heart failure'),
('Heart failures'),
('Hedges against'),
('Hedging a'),
('Hedging bets'),
('Hedging deals'),
('Hedging transactions'),
('Hee hee'),
('His hope'),
('His love'),
('His price'),
('His will'),
('Hit the fan'),
('Holding a'),
('Holding company'),
('Holding of'),
('Holding period'),
('Holding the'),
('Holdings completely'),
('Hollering like'),
('Hope all'),
('Hope among'),
('Hope everyone'),
('Hope everything'),
('Hope for'),
('Hope that'),
('Hope the'),
('Hope things'),
('Hope to'),
('Hope you'),
('Hour price'),
('Hot ember'),
('Hot summer'),
('Hover around'),
('Hover at'),
('Huddle with'),
('I hope'),
('I love'),
('I may'),
('I will'),
('It may'),
('It will'),
('Its bonds'),
('Its price'),
('Its stocks'),
('In Jan'),
('In April'),
('In flux'),
('In June'),
('In May'),
('In the autumn'),
('In the college'),
('In the coming weeks'),
('In the back'),
('In the bank'),
('In the end'),
('In the front'),
('In the heart'),
('In the hopes'),
('In the long run'),
('In the low'),
('In the joint'),
('In ruins'),
('In the run'),
('In the spot'),
('In the spring'),
('In the still'),
('In the summer'),
('In the walk'),
('In the winter'),
('In the works'),
('Investment banks'),
('Issue bonds'),
('Junk bonds'),
('Just love'),
('Keen To'),
('King and queen'),
('Lane judges'),
('Last day'),
('Last Jan'),
('Last June'),
('Last May'),
('Last Autumn'),
('Last Christmas'),
('Last Easter'),
('Last Summer'),
('Last Winter'),
('Launch day'),
('Lay off'),
('Lead banks'),
('Leap of'),
('Like price'),
('Long day'),
('Lose faith'),
('Lost faith'),
('Love and support'),
('Love if'),
('Love with'),
('Low price'),
('Lower price'),
('Lowest price'),
('Lowest rung'),
('Lows expected'),
('Lows in'),
('Lows of'),
('March or April'),
('Mark discrepancy'),
('Marks for'),
('Matter of weeks'),
('May I'),
('May add'),
('May already'),
('May also'),
('May apply'),
('May be'),
('May come'),
('May concern'),
('May contain'),
('May have'),
('May love'),
('May not'),
('May now'),
('May or may not'),
('May park at'),
('May park in'),
('May park on'),
('May potentially'),
('May show'),
('May soon'),
('May together'),
('May vary'),
('May well'),
('Meager credit'),
('Median age'),
('Month of April'),
('Month of May'),
('Month of Jan'),
('Month of June'),
('Much smaller'),
('Muddle through'),
('My heart'),
('My hope'),
('My lips'),
('My love'),
('My price'),
('My will'),
('Nailing down'),
('Nazi'),
('Nearby camp'),
('Next autumn'),
('Next day'),
('Next summer'),
('Next winter'),
('New lows'),
('News story'),
('No biggie'),
('Normal summer'),
('North of'),
('North from'),
('Notch above'),
('Notch below'),
('Of banks'),
('Of bonds'),
('Of fries'),
('Of love'),
('Of joy'),
('Of summers'),
('Of the ashes'),
('Of the bank'),
('Of the banks'),
('Of the common'),
('Of the deals'),
('Of the end'),
('Of the loan'),
('Of the line'),
('Of the links'),
('Of the joint'),
('Of the rise'),
('Of the short'),
('Of the tunnel'),
('Off the loan'),
('Off the hook'),
('Offer price'),
('On the hook'),
('Once mighty'),
('Old gal'),
('Old guy'),
('On love'),
('On the back'),
('On the beach'),
('On the corner'),
('On the list'),
('On the lookout'),
('On the moon'),
('On the rise'),
('On the shore'),
('On the way'),
('Only chance'),
('Only will it'),
('One day'),
('Option grant'),
('Other postal'),
('Our hope'),
('Our love'),
('Our price'),
('Our west'),
('Over the course of'),
('Overnight lows'),
('Parks at'),
('Parks by'),
('Parks near'),
('Parks on'),
('Pay down the'),
('Peak day'),
('Per day'),
('Percent bonds'),
('Pita'),
('Piles of'),
('Plain vanilla'),
('Plant pots'),
('Positive story'),
('Power plant'),
('Powers to'),
('Pressing this point'),
('Previous day'),
('Price cap'),
('Price curve'),
('Price curves'),
('Price discrepancy'),
('Price discrepancies'),
('Price for'),
('Price may'),
('Price per'),
('Price of'),
('Price range'),
('Price to'),
('Price within'),
('Prices sank'),
('Prior day'),
('Pro rata'),
('Psycho'),
('Purchase price'),
('Rapid pace'),
('Rash of'),
('Ray of hope'),
('Reached the dock'),
('Reading about'),
('Recent weeks'),
('Related fields'),
('Repay the loan'),
('Rich fields'),
('Rock stars'),
('Rod for'),
('Rod to'),
('Roman catholic'),
('Romp through'),
('Rose marginally'),
('Rose slightly'),
('Rushed to'),
('Rushing to'),
('Rushing water'),
('Sail from'),
('Sail out'),
('Sail to'),
('Sales price'),
('Same day'),
('Sang about'),
('Security holdings'),
('Serve burgers'),
('Several weeks'),
('Sharp discount'),
('Sharp fall'),
('Sharp turn'),
('Share price'),
('She may'),
('She will'),
('Shoring up'),
('Sincerely hope'),
('Sit idle'),
('Splash page'),
('Some banks'),
('Some beers'),
('Some milder'),
('Summary page'),
('Summed up'),
('Summer of'),
('Summer track'),
('Sunrise from'),
('Supernova'),
('Suspension bridges'),
('South of'),
('South from'),
('Stacks of'),
('Stakes in'),
('Still under way'),
('Stock price'),
('Stocks and bonds'),
('Stocks at'),
('Stocks close higher'),
('Stocks close lower'),
('Stocks fell'),
('Stocks of'),
('Stocks on'),
('Stocks rose'),
('Stocks were'),
('Story about'),
('Sue you'),
('Summer camp'),
('Summer season'),
('Take heart'),
('Target price'),
('Tee box'),
('Terrible day'),
('Tee off'),
('Television channels'),
('That banks'),
('That day'),
('That love'),
('That price'),
('That sees'),
('That van'),
('The alter'),
('The autumn'),
('The bank to'),
('The bill'),
('The bonds'),
('The calls to'),
('The camp'),
('The chance'),
('The course of'),
('The course that'),
('The couch'),
('The courts are'),
('The courts will'),
('The Christmas'),
('The cross country'),
('The curve been'),
('The curve on'),
('The day'),
('The deals are'),
('The deals were'),
('The East'),
('The Easter'),
('The edge of'),
('The end of'),
('The ferry'),
('The front of'),
('The front office'),
('The front page'),
('The front room'),
('The gap was'),
('The grant'),
('The guy'),
('The hall to'),
('The heck'),
('The hope'),
('The larger'),
('The light at'),
('The light load'),
('The list of'),
('The loan relates'),
('The loop on'),
('The love'),
('The low end'),
('The low values'),
('The low point'),
('The Jan'),
('The June'),
('The key is'),
('The key to'),
('The king'),
('The mark'),
('The May'),
('The max'),
('The moon'),
('The new'),
('The new site'),
('The North'),
('The outlook for'),
('The outlook on'),
('The peak hours'),
('The place I'),
('The place he'),
('The place she'),
('The place to'),
('The place we'),
('The place you'),
('The point is'),
('The point of'),
('The point that'),
('The points which'),
('The puncher'),
('The price'),
('The prince'),
('The prospect of'),
('The prospect that'),
('The rally seemed'),
('The rest of'),
('The resolution of'),
('The royal bank'),
('The run of'),
('The square root'),
('The slides that'),
('The snow'),
('The east side'),
('The north side'),
('The south side'),
('The way I'),
('The way it'),
('The way she'),
('The way they'),
('The way we'),
('The whack'),
('The west side'),
('The works of'),
('The South'),
('The Spring Festival'),
('The spur of'),
('The stock down'),
('The story'),
('The Summer'),
('The sun'),
('The tally'),
('The tanking'),
('The ticker'),
('The usher'),
('The van'),
('The waiter'),
('The walk goes'),
('The walk to'),
('The way around'),
('The way back'),
('The way from'),
('The way of'),
('The way to'),
('The West'),
('The weeks'),
('The Winter'),
('They hope'),
('They love'),
('They may'),
('They will'),
('This April'),
('This day'),
('This love'),
('This grant'),
('This guy'),
('This page'),
('This price'),
('This Jan'),
('This June'),
('This May'),
('This Autumn'),
('This Christmas'),
('This Easter'),
('This story'),
('This Summer'),
('This Winter'),
('This won'),
('Thou'),
('Ticket booth'),
('To quell'),
('To price'),
('To prosper'),
('To rout'),
('To the back'),
('To the edge'),
('To the heart'),
('To the new common'),
('To the joint'),
('To the peak'),
('To the point in'),
('To the point of'),
('To the point when'),
('To the point where'),
('To the village'),
('Tonic for'),
('Top story'),
('Trade credit'),
('Trade credits'),
('Tradition christmas'),
('Tree saplings'),
('Trickle out'),
('Trustworthy basis'),
('Under way on'),
('Various banks'),
('Wanna go'),
('Was idle'),
('Was stolen'),
('We hope'),
('We love'),
('We may'),
('We will'),
('Web page'),
('Well underway'),
('Weeks ago'),
('Weeks of'),
('West coast'),
('West of'),
('West from'),
('Wetter than'),
('When will'),
('Which will'),
('White shirt'),
('Who will'),
('Whom will'),
('Will a lack'),
('Will actually'),
('will adequately'),
('Will add'),
('Will almost'),
('Will also'),
('Will always'),
('Will back'),
('Will be'),
('Will certainly'),
('Will definitely'),
('Will do'),
('Will have'),
('Will forever'),
('Will forward'),
('Will he'),
('Will help'),
('Will her'),
('Will I'),
('Will instead'),
('Will just'),
('Will likely'),
('Will make'),
('Will meet'),
('Will most'),
('Will need'),
('Will never'),
('Will no'),
('Will not'),
('Will now'),
('Will open'),
('Will once'),
('Will only'),
('Will probably'),
('Will regularly'),
('Will resend'),
('Will ruefully'),
('Will significantly'),
('Will she'),
('Will still'),
('Will the'),
('Will their'),
('Will they'),
('Will then'),
('Will waive'),
('Will you'),
('Will your'),
('Winter camp'),
('Winter period'),
('Winter season'),
('With banks'),
('With rich'),
('With smaller'),
('Wireless LAN'),
('Work day'),
('Worthy of'),
('Would sue'),
('Year lows'),
('Years eve'),
('You cook'),
('You may'),
('You will'),
('Young adult'),
('Young adults'),
('Young baby'),
('Young boy'),
('Young gal'),
('Young girl'),
('Young guy'),
('Young males'),
('Young man'),
('Young men'),
('Young people'),
('Young person'),
('Young professionals'),
('Young volunteers'),
('Young woman'),
('Young women'),
('Your day'),
('Your heart'),
('Your grant'),
('Your price'),
('Your hope');

-- Down
DELETE FROM Part;