INSERT INTO TempPlacename
(keyword)
VALUES
('Maanshan'),
('Maastricht'),
('Mabalacat'),
('Macaé'),
('Macapá'),
('Macau'),
('Maceió'),
('Machakos'),
('Machala'),
('Macheng'),
('Machida'),
('Machilipatnam'),
('Madanapalle'),
('Madhavaram'),
('Madhyamgram'),
('Madina'),
('Madison'),
('Madiun'),
('Madrid'),
('Madurai'),
('Maebashi'),
('Magalang'),
('Magangué'),
('Magdeburg'),
('Magé'),
('Magelang'),
('Magnitogorsk'),
('Magway'),
('Mahabad'),
('Mahajanga'),
('Mahbubnagar'),
('Maheshtala'),
('Mahmoudiyah'),
('Maicao'),
('Maidstone'),
('Maiduguri'),
('Mainpuri'),
('Mainz'),
('Makassar'),
('Makati'),
('Makeni'),
('Makhachkala'),
('Makiivka'),
('Malabo'),
('Malabon'),
('Málaga'),
('Malakal'),
('Malang'),
('Malappuram'),
('Malard'),
('Malasiqui'),
('Malatya'),
('Malaybalay'),
('Malayer'),
('Malé'),
('Malegaon'),
('Malerkotla'),
('Malindi'),
('Malita'),
('Malmö'),
('Malolos'),
('Malungon'),
('Mamuju'),
('Man'),
('Manado'),
('Managua'),
('Manama'),
('Manaus'),
('Manavgat'),
('Manchester'),
('Mandalay'),
('Mandaluyong'),
('Mandaue'),
('Mandoli'),
('Mandsaur'),
('Mandya'),
('Mangaldan'),
('Mangalore'),
('Mangaung'),
('Mango'),
('Manila'),
('Manisa'),
('Manizales'),
('Mannheim'),
('Manolo Fortich'),
('Mansoura'),
('Manta'),
('Manzanillo'),
('Manzhouli'),
('Maoming'),
('Maputo'),
('Mar del Plata'),
('Maraba'),
('Maracaibo'),
('Maracanau'),
('Maracay'),
('Maradi'),
('Maramag'),
('Marand'),
('Maranguape'),
('Maraqeh'),
('Marawi'),
('Marbella'),
('Mardan'),
('Margilan'),
('Maricá'),
('Marikina'),
('Marilao'),
('Marília'),
('Maringá'),
('Marituba'),
('Mariupol'),
('Marivan'),
('Mariveles'),
('Markham'),
('Marrakech'),
('Marseille'),
('Marugame'),
('Marvdasht'),
('Mary'),
('Masaka'),
('Masaya'),
('Mascara'),
('Maseru'),
('Mashhad'),
('Masjed Soleyman'),
('Matadi'),
('Matamoros'),
('Matanzas'),
('Mataram'),
('Mataró'),
('Mathura'),
('Mati'),
('Matola'),
('Matsubara'),
('Matsudo'),
('Matsue'),
('Matsumoto'),
('Matsusaka'),
('Matsuyama'),
('Maturín'),
('Mau'),
('Mauá'),
('Mawlamyine'),
('Maxixe'),
('Maykop'),
('Mazari Sharif'),
('Mazatlán'),
('Mazyr'),
('Mbandaka'),
('Mbarara'),
('Mbeya'),
('Mbour'),
('Mbuji-Mayi'),
('McAllen'),
('McKinney'),
('Mecca'),
('Medan'),
('Medea'),
('Medellín'),
('Medina'),
('Medinipur'),
('Meerut'),
('Mehsana'),
('Meihekou'),
('Meizhou'),
('Mejicanos'),
('Mekele'),
('Meknes'),
('Melbourne'),
('Melitopol'),
('Memphis'),
('Mendoza'),
('Mérida'),
('Mérida'),
('Mersin'),
('Mesa'),
('Mesquita'),
('Mesquite'),
('Messad'),
('Messina'),
('Metepec'),
('Metz'),
('Mexicali'),
('Mexico City'),
('Mexico'),
('Meycauayan'),
('Mezhdurechensk'),
('Miami Gardens'),
('Miami'),
('Miandoab'),
('Mianyang'),
('Miass'),
('Middlesbrough'),
('Midland'),
('Midsayap'),
('Milagro'),
('Milan'),
('Milton Keynes'),
('Miluo'),
('Milwaukee'),
('Minatitlán'),
('Minglanilla'),
('Mangora'),
('Minneapolis'),
('Minoh'),
('Minsk'),
('Minya'),
('Miqdadiyah'),
('Mira-Bhayandar'),
('Miramar'),
('Miri'),
('Mirpur Khas'),
('Miryalaguda'),
('Mirzapur-cum-Vindhyachal'),
('Misato'),
('Mishan'),
('Mishima'),
('Miskolc'),
('Misrata'),
('Mississauga'),
('Mitaka'),
('Mito'),
('Mixco'),
('Miyakonojo'),
('Miyazaki'),
('Mobile'),
('Moca'),
('Modena'),
('Modesto'),
('Modinagar'),
('Moers'),
('Moga'),
('Mogadishu'),
('Mogi das Cruzes'),
('Mogi Guaçu'),
('Mogilev'),
('Mogpo'),
('Mohammadshahr'),
('Mohammedia'),
('Mojokerto'),
('Mombasa'),
('Mönchengladbach'),
('Monclova'),
('Moncton'),
('Monrovia'),
('Montego Bay'),
('Montería'),
('Monterrey'),
('Montes Claros'),
('Montevideo'),
('Montgomery'),
('Montpellier'),
('Montreal'),
('Montreuil'),
('Monywa'),
('Monza'),
('Mopti'),
('Moradabad'),
('Moratuwa'),
('Morelia'),
('Morena'),
('Moreno Valley'),
('Moriguchi'),
('Morioka'),
('Morogoro'),
('Morvi'),
('Moscow'),
('Mossoró'),
('Mostaganem'),
('Mostar'),
('Móstoles'),
('Mosul'),
('Motihari'),
('MSila'),
('Mudanjiang'),
('Mueang Samut Prakan'),
('Mufulira'),
('Mughalsarai'),
('Mukdahan'),
('Mukono Town'),
('Mülheim an der Ruhr'),
('Mulhouse'),
('Multan'),
('Mumbai'),
('Munger'),
('Munich'),
('Münster'),
('Muntinlupa'),
('Murcia'),
('Murfreesboro'),
('Muriaé'),
('Muridke'),
('Murmansk'),
('Murom'),
('Murrieta'),
('Murwara'),
('Musashino'),
('Muscat'),
('Mushin'),
('Mustafabad'),
('Mutare'),
('Muttrah'),
('Muzaffargharh'),
('Muzaffarnagar'),
('Muzaffarpur'),
('Mwanza'),
('Myitkyina'),
('Mykolaiv'),
('Mymensingh'),
('Mysore'),
('Mytho'),
('Mytishchi'),
('Mzuzu'),
('Nabadwip'),
('Naberezhnye Chelny'),
('Nablus'),
('Nacala'),
('Nadiad'),
('Nador'),
('Naga'),
('Nagahama'),
('Nagano'),
('Nagaoka'),
('Nagaon'),
('Nagapattinam'),
('Nagareyama'),
('Nagasaki'),
('Nagaur'),
('Nagda'),
('Nagercoil'),
('Nagoya'),
('Nagpur'),
('Naguanagua'),
('Naha'),
('Naic'),
('Naihati'),
('Nairobi'),
('Naivasha'),
('Najaf'),
('Najafabad'),
('Najran'),
('Nakhodka'),
('Nakhon Pathom'),
('Nakhon Ratchasima'),
('Nakhon Sawan'),
('Nakhon Si Thammarat'),
('Nakuru'),
('Nalchik'),
('Nalgonda'),
('Nam Định'),
('Namangan'),
('Nampo'),
('Nampula'),
('Namur'),
('Nanchang'),
('Nanchong'),
('Nancy'),
('Nanded'),
('Nanded-Waghala'),
('Nandurbar'),
('Nandyal'),
('Nangloi Jat'),
('Nanjing'),
('Nanning'),
('Nanping'),
('Nansana'),
('Nantes'),
('Nantong'),
('Nanyang'),
('Naperville'),
('Napier-Hastings'),
('Naples'),
('Nara'),
('Narasaraopet'),
('Narashino'),
('Narayanganj'),
('Narita'),
('Nashik'),
('Nashville'),
('Nasimshahr'),
('Nasiriyah'),
('Nassau'),
('Nasugbu'),
('Nasushiobara'),
('Natal'),
('Naucalpan'),
('Naujan'),
('Navapolatsk'),
('Navi Mumbai'),
('Navoiy'),
('Navojoa'),
('Navotas'),
('Navsari'),
('Nawabganj'),
('Nawabshah'),
('Naypyidaw'),
('Nazarabad'),
('Nazilli'),
('NDjamena'),
('Ndola'),
('Neemuch'),
('Neftekamsk'),
('Nefteyugansk'),
('Negombo'),
('Neijiang'),
('Neiva'),
('Nellore'),
('Netanya'),
('Neuquén'),
('Neuss'),
('Nevinnomyssk'),
('New Delhi'),
('New Haven'),
('New Orleans'),
('New York'),
('Newark'),
('Newcastle upon Tyne'),
('Newcastle'),
('Newport News'),
('Newport'),
('Neyagawa'),
('Neyveli'),
('Ngong'),
('Nha Trang'),
('Niamey'),
('Nice'),
('Nicolás Romero'),
('Nicosia'),
('Niğde'),
('Niigata'),
('Niihama'),
('Niiza'),
('Nijmegen'),
('Nikopol'),
('Nilópolis'),
('Nîmes'),
('Ningbo'),
('Ningde'),
('Niš'),
('Nishapur'),
('Nishinomiya'),
('Nishio'),
('Nishitōkyō'),
('Niterói'),
('Nizamabad'),
('Nizhnekamsk'),
('Nizhnevartovsk'),
('Nizhny Novgorod'),
('Nizhny Tagil'),
('Nizwa'),
('Nobeoka'),
('Noda'),
('Nogales'),
('Noginsk'),
('Noida'),
('Nonthaburi'),
('Norilsk'),
('Norman'),
('Norrköping'),
('North Barrackpur'),
('North Dumdum'),
('North Las Vegas'),
('Northampton'),
('Norwalk'),
('Norwich'),
('Norzagaray'),
('Nossa Senhora do Socorro'),
('Nottingham'),
('Nouakchott'),
('Nova Friburgo'),
('Nova Iguaçu'),
('Novara'),
('Novi Sad'),
('Novo Gama'),
('Novo Hamburgo'),
('Novocheboksarsk'),
('Novocherkassk'),
('Novokuybyshevsk'),
('Novokuznetsk'),
('Novomoskovsk'),
('Novorossiysk'),
('Novoshakhtinsk'),
('Novosibirsk'),
('Novy Urengoy'),
('Noyabrsk'),
('Nuevo Laredo'),
('Nukus'),
('Numazu'),
('Nuremberg'),
('Nur-Sultan'),
('Nyala'),
('Nyeri'),
('Nyíregyháza'),
('Nzérékoré'),
('Oakland'),
('Oakville'),
('Oaxaca de Juárez'),
('Oberhausen'),
('Obihiro'),
('Obninsk'),
('Obuasi'),
('Oceanside'),
('Ocumare del Tuy'),
('Odawara'),
('Odense'),
('Odesa'),
('Odintsovo'),
('Offenbach am Main'),
('Ōgaki'),
('Ogbomosho'),
('Ōita'),
('Okara'),
('Okayama'),
('Okazaki'),
('Okene'),
('Okinawa'),
('Oklahoma City'),
('Oktyabrsky'),
('Olanchito'),
('Olathe'),
('Oldenburg'),
('Olinda'),
('Olmaliq'),
('Olomouc'),
('Olongapo'),
('Olsztyn'),
('Omaha'),
('Omdurman'),
('Ōme'),
('Omsk'),
('Ōmuta'),
('Ongole'),
('Onitsha'),
('Onomichi'),
('Ontario'),
('Opole'),
('Oradea'),
('Orai'),
('Oral'),
('Oran'),
('Orange'),
('Ordos City'),
('Ordu'),
('Örebro'),
('Orekhovo-Zuyevo'),
('Orenburg'),
('Orizaba'),
('Orlando'),
('Orléans'),
('Ormoc'),
('Orsha'),
('Orsk'),
('Oruro'),
('Oryol'),
('Osaka'),
('Ōsaki'),
('Osasco'),
('Osh'),
('Oshawa'),
('Oshogbo'),
('Ōshū'),
('Osijek'),
('Oskemen'),
('Oslo'),
('Osmanabad'),
('Osmaniye'),
('Osnabrück'),
('Osorno'),
('Ostrava'),
('Ōta'),
('Otaru'),
('Ōtsu'),
('Ottawa'),
('Ouagadougou'),
('Ouargla'),
('Oujda'),
('Oulu'),
('Ourense'),
('Ourinhos'),
('Overland Park'),
('Oviedo'),
('Oxford'),
('Oxnard'),
('Oyama'),
('Oyo'),
('Ozamiz'),
('Ozhukarai'),
('Paarl'),
('Pabna'),
('Pachuca'),
('Padang'),
('Paderborn'),
('Padua'),
('Pagadian'),
('Paita'),
('Pakalongan'),
('Pakan Baru'),
('Pakdasht'),
('Pakpattan'),
('Palakkad'),
('Palangkaraya'),
('Palanpur'),
('Palembang'),
('Palermo'),
('Palhoça'),
('Pali'),
('Pallavaram'),
('Palm Bay'),
('Palma de Mallorca'),
('Palmas'),
('Palmdale'),
('Palmira'),
('Palopo'),
('Palu'),
('Palwal'),
('Pamplona'),
('Panabo'),
('Panama City'),
('Panchkula'),
('Pangkal Pinang'),
('Panihati'),
('Panipat'),
('Panjin'),
('Panvel'),
('Panzhihua'),
('Paradise'),
('Parakou'),
('Paramaribo'),
('Paraná'),
('Paranaguá'),
('Parañaque'),
('Parauapebas'),
('Parbhani'),
('Parepare'),
('Parintins'),
('Paris'),
('Parla'),
('Parma'),
('Parnaíba'),
('Parnamirim'),
('Parral'),
('Pasadena'),
('Pasay'),
('Pasig'),
('Passo Fundo'),
('Passos'),
('Pasto'),
('Pasuruan'),
('Patan'),
('Paterson'),
('Pathankot'),
('Pathein'),
('Patiala'),
('Patna'),
('Patos de Minas'),
('Patos'),
('Patras'),
('Paulínia'),
('Paulista'),
('Paulo Afonso'),
('Pavlodar'),
('Pavlohrad'),
('Pécs'),
('Pelotas'),
('Pematang Siantar'),
('Pemba'),
('Pembroke Pines'),
('Penza'),
('Peoria'),
('Pereira'),
('Perez Zeledon'),
('Peristeri'),
('Perm'),
('Perpignan'),
('Perth'),
('Perugia'),
('Pervouralsk'),
('Pescara'),
('Peshawar'),
('Petah Tikva'),
('Petaling Jaya'),
('Petare'),
('Peterborough'),
('Petrolina'),
('Petropavl'),
('Petropavlovsk-Kamchatsky'),
('Petrópolis'),
('Petrozavodsk'),
('Pforzheim'),
('Pennsylvania'),
('Phnom Penh'),
('Phoenix'),
('Phyongsong'),
('Piacenza'),
('Piedecuesta'),
('Piedras Negras'),
('Pietermaritzburg'),
('Pikine'),
('Pikit'),
('Pilibhit'),
('Pimpri-Chinchwad'),
('Pinar del Río'),
('Pindamonhangaba'),
('Pingdingshan'),
('Pingdu'),
('Pingliang'),
('Pingxiang'),
('Pinhais'),
('Pinsk'),
('Pir Mahal'),
('Piracicaba'),
('Piraeus'),
('Pisco'),
('Pitalito'),
('Piteşti'),
('Pithampur'),
('Pittsburgh'),
('Piura'),
('Plano'),
('Plaridel'),
('Playa del Carmen'),
('Pleven'),
('Płock'),
('Ploieşti'),
('Plovdiv'),
('Plymouth'),
('Plzeň'),
('Poá'),
('Pococí'),
('Poços de Caldas'),
('Podgorica'),
('Podolsk'),
('Pohang'),
('Pointe-Noire'),
('Pokhara'),
('Polomolok'),
('Poltava'),
('Pomona'),
('Ponce'),
('Pondicherry'),
('Ponta Grossa'),
('Pontianak'),
('Poole'),
('Popayán'),
('Porac'),
('Porbandar'),
('Port Blair'),
('Port Elizabeth'),
('Port Harcourt'),
('Port Louis'),
('Port Moresby'),
('Port Said'),
('Port St. Lucie'),
('Port Sudan'),
('Port-au-Prince'),
('Port-Gentil'),
('Portland'),
('Portmore'),
('Porto Alegre'),
('Porto Novo'),
('Porto Seguro'),
('Porto Velho'),
('Porto'),
('Portoviejo'),
('Portsmouth'),
('Posadas'),
('Potosí'),
('Potsdam'),
('Pouso Alegre'),
('Poza Rica de Hidalgo'),
('Poznań'),
('Pozuelos'),
('Prague'),
('Praia Grande'),
('Praia'),
('Prato'),
('Presidente Prudente'),
('Preston'),
('Pretoria'),
('Pristina'),
('Probolinggo'),
('Proddatur'),
('Prokopyevsk'),
('Providence'),
('Provo'),
('Pskov'),
('Pucallpa'),
('Puducherry'),
('Pudukkottai'),
('Puebla de Zaragoza'),
('Pueblo'),
('Puente Alto'),
('Puerto Cabello'),
('Puerto Cortés'),
('Puerto Montt'),
('Puerto Plata'),
('Puerto Princesa'),
('Puerto Vallarta'),
('Pune'),
('Puno'),
('Punta Arenas'),
('Punto Fijo'),
('Puri'),
('Purnia'),
('Purulia'),
('Pushkino'),
('Putian'),
('Puyang'),
('Pyatigorsk'),
('Pyongyang'),
('Qā’em Shahr'),
('Qalat Sukkar'),
('Qalyub'),
('Qamishli'),
('Qarchak'),
('Qarshi'),
('Qatif'),
('Qazvin'),
('Qena'),
('Qianjiang'),
('Qidong'),
('Qingdao'),
('Qingtongxia'),
('Qingyang'),
('Qingyuan'),
('Qingzhou'),
('Qinhuangdao'),
('Qinyang'),
('Qinzhou'),
('Qiqihar'),
('Qitaihe'),
('Qods'),
('Qom'),
('Quanzhou'),
('Quchan'),
('Quebec City'),
('Queimados'),
('Quelimane'),
('Querétaro'),
('Quetta'),
('Quetzaltenango'),
('Quevedo'),
('Quezon'),
('Quezon City'),
('Qufu'),
('Qui Nhơn'),
('Quibdó'),
('Quilmes'),
('Quilpué'),
('Quito'),
('Qujing'),
('Qurayyat'),
('Quzhou'),
('Rabat'),
('Rạch Giá'),
('Radom'),
('Raebareli'),
('Rafah'),
('Rafsanjan'),
('Rahim Yar Khan'),
('Raichur'),
('Raigad'),
('Raiganj'),
('Raigarh'),
('Raipur'),
('Rajahmundry'),
('Rajapalayam'),
('Rajarhat'),
('Rajkot'),
('Rajnandgaon'),
('Rajpur Sonarpur'),
('Rajshahi'),
('Raleigh'),
('Ramadi'),
('Ramagundam'),
('Ramat Gan'),
('Rampur'),
('Ranaghat'),
('Rancagua'),
('Ranchi'),
('Rancho Cucamonga'),
('Ranebennuru'),
('Rangpur'),
('Raniganj'),
('Raqqa'),
('Ras al-Khaimah'),
('Rasht'),
('Rason'),
('Ratlam'),
('Ravenna'),
('Rawalpindi'),
('Rawson'),
('Reading'),
('Recife'),
('Recklinghausen'),
('Regensburg'),
('Reggio Calabria'),
('Reggio Emilia'),
('Regina'),
('Rehovot'),
('Reims'),
('Relizane'),
('Remscheid'),
('Rennes'),
('Reno'),
('Renqiu'),
('Resende'),
('Resistencia'),
('Reus'),
('Reutlingen'),
('Rewa'),
('Rewari'),
('Reykjavík'),
('Reynosa'),
('Ribeirão das Neves'),
('Ribeirão Pires'),
('Ribeirão Preto'),
('Richmond Hill'),
('Richmond'),
('Riga'),
('Rijeka'),
('Rimini'),
('Rio Branco'),
('Rio Claro'),
('Rio Cuarto'),
('Rio das Ostras'),
('Rio de Janeiro'),
('Rio Grande'),
('Rio Verde'),
('Riobamba'),
('Riohacha'),
('Rishon LeZion'),
('Rishra'),
('Riverside'),
('Rivne'),
('Riyadh'),
('Rize'),
('Rizhao'),
('Robertsonpet'),
('Rochdale'),
('Rochester'),
('Rockford'),
('Rodriguez'),
('Rohtak'),
('Rome'),
('Rondonópolis'),
('Rongcheng'),
('Roodepoort'),
('Roorkee'),
('Rosario'),
('Rosario'),
('Roseville'),
('Rostock'),
('Rostov-on-Don'),
('Rotherham'),
('Rotterdam'),
('Rouen'),
('Round Rock'),
('Rourkela'),
('Roxas'),
('Rubtsovsk'),
('Ruda Śląska'),
('Rudny'),
('Rudrapur'),
('Rufisque'),
('Ruian'),
('Ruichang'),
('Ruiru'),
('Ruse'),
('Russeifa'),
('Rustaq'),
('Rustavi'),
('Ruzhou'),
('Ryazan'),
('Rybinsk'),
('Rybnik'),
('Rzeszów'),
('S.A.S. Nagar'),
('Saanich'),
('Saarbrücken'),
('Sabadell'),
('Sabára'),
('Sabzewar'),
('Sacaba'),
('Sacramento'),
('Sadiqabad'),
('Sadr City'),
('Safi'),
('Saga'),
('Sagamihara'),
('Sagar'),
('Sagay'),
('Saguenay'),
('Saham'),
('Saharanpur'),
('Saharsa'),
('Sahiwal'),
('Saida'),
('Saidpur'),
('Saijō'),
('Saint Petersburg'),
('Saint-Denis'),
('Saint-Étienne'),
('Saint-Louis'),
('Saint-Paul'),
('Saitama'),
('Sakado'),
('Sakai'),
('Sakakah'),
('Sakata'),
('Sakura'),
('Salalah'),
('Salamanca'),
('Salamanca'),
('Salatiga'),
('Salavat'),
('Salé'),
('Salem'),
('Salerno'),
('Salihorsk'),
('Salinas'),
('Salmiya'),
('Salt Lake City'),
('Salta'),
('Saltillo'),
('Salto'),
('Salvador'),
('Salzburg'),
('Salzgitter'),
('Samal'),
('Samara'),
('Samarinda'),
('Samarkand'),
('Samarra'),
('Samawah'),
('Sambalpur'),
('Sambhal'),
('Samsun'),
('San Antonio'),
('San Bernardino'),
('San Bernardo'),
('San Buenaventura'),
('San Carlos'),
('San Cristóbal de La Laguna'),
('San Cristóbal de Las Casas'),
('San Cristóbal'),
('San Diego'),
('San Fernando'),
('San Fernando de Apure'),
('San Fernando de Valle de Catamarca'),
('San Francisco'),
('San Francisco de Macorís'),
('San Francisco del Rincón'),
('San Idelfonso'),
('San José'),
('San Jose'),
('San Juan'),
('San Juan Bautista Tuxtepec'),
('San Juan de Girón'),
('San Juan de la Maguana'),
('San Juan del Río'),
('San Lorenzo'),
('San Luis'),
('San Luis Potosí'),
('San Luis Río Colorado'),
('San Martin'),
('San Mateo'),
('San Miguel'),
('San Miguel'),
('San Miguel de Tucumán'),
('San Miguelito'),
('San Nicolás'),
('San Nicolás de los Garza'),
('San Pablo'),
('San Pedro'),
('San Pedro de la Paz'),
('San Pedro de Macoris'),
('San Pedro Sula'),
('San Rafael'),
('San Salvador'),
('San Salvador de Jujuy'),
('San Sebastián'),
('Sanaa'),
('Sanandaj'),
('Sancti Spíritus'),
('Sanda'),
('Sandakan'),
('Sangli'),
('Şanlıurfa'),
('Sanmenxia'),
('Sanming'),
('Sano'),
('San-Pédro'),
('Santa Ana de Coro'),
('Santa Ana'),
('Santa Bárbara dOeste'),
('Santa Clara'),
('Santa Clarita'),
('Santa Coloma de Gramanet'),
('Santa Cruz'),
('Santa Cruz de la Sierra'),
('Santa Cruz de Tenerife'),
('Santa Cruz do Capibaribe'),
('Santa Cruz do Sul'),
('Santa Fe de Bogotá'),
('Santa Fe'),
('Santa Lucía'),
('Santa Luzia'),
('Santa Maria'),
('Santa Maria'),
('Santa Marta'),
('Santa Rita'),
('Santa Rosa'),
('Santa Tecla'),
('Santana de Parnaíba'),
('Santana'),
('Santander'),
('Santarém'),
('Santiago'),
('Santiago'),
('Santiago de Cuba'),
('Santiago de los Caballeros'),
('Santiago del Estero'),
('Santipur'),
('Santo André'),
('Santo Antônio de Jesus'),
('Santo Domingo'),
('Santo Domingo de los Colorados'),
('Santo Domingo Este'),
('Santo Domingo Norte'),
('Santo Domingo Oeste'),
('Santo Tomas'),
('Santos'),
('Sanya'),
('São Bernardo do Campo'),
('São Caetano do Sul'),
('São Carlos'),
('São Gonçalo'),
('São João de Meriti'),
('São José de Ribamar'),
('São José do Rio Preto'),
('São José dos Campos'),
('São José dos Pinhais'),
('São José'),
('São Leopoldo'),
('São Lourenço da Mata'),
('São Luís'),
('São Mateus'),
('São Paulo'),
('São Vicente'),
('Sapporo'),
('Sapucaia do Sul'),
('Saqez'),
('Sarajevo'),
('Saransk'),
('Sarapul'),
('Saratov'),
('Sargodha'),
('Sari'),
('Sariaya'),
('Sariwon'),
('Sasaram'),
('Sasebo'),
('Saskatoon'),
('Sassari'),
('Satara'),
('Satna'),
('Satu Mare'),
('Savannah'),
('Saveh'),
('Sawai Madhopur'),
('Sayama'),
('Schaerbeek'),
('Scottsdale'),
('Seam Reab'),
('Seattle'),
('Secunderabad'),
('Seeb'),
('Ségou'),
('Sehore'),
('Sejong City'),
('Sekondi-Takoradi'),
('Seleyang Baru'),
('Semarang'),
('Semey'),
('Semnan'),
('Sendai'),
('Seongnam'),
('Seoni'),
('Seoul'),
('Serampore'),
('Seremban'),
('Sergiyev Posad'),
('Serpukhov'),
('Serra'),
('Sertaozinho'),
('Sete Lagoas'),
('Setif'),
('Seto'),
('Settat'),
('Sevastopol'),
('Severodvinsk'),
('Seversk'),
('Seville'),
('Sfax'),
('Shah Alam'),
('Shahe'),
('Shahin Shahr'),
('Shahjahanpur'),
('Shahrekord'),
('Shahreza'),
('Shahriar'),
('Shahrisabz'),
('Shahrud'),
('Shakhty'),
('Shamli'),
('Shanghai'),
('Shangluo'),
('Shangqiu'),
('Shangrao'),
('Shangzhi'),
('Shantou'),
('Shanwei'),
('Shaoguan'),
('Shaowu'),
('Shaoxing'),
('Shaoyang'),
('Sharjah'),
('Shchyolkovo'),
('Sheberghan'),
('Sheffield'),
('Sheikhu Pura'),
('Shenyang'),
('Shenzhen'),
('Sheopur'),
('Sherbrooke'),
('Hertogenbosch'),
('Shibin el-Kom'),
('Shihezi'),
('Shihung'),
('Shijiazhuang'),
('Shikarpur'),
('Shikohabad'),
('Shillong'),
('Shimizu'),
('Shimla'),
('Shimoga'),
('Shimonoseki'),
('Shinyanga'),
('Shiraz'),
('Shishi City'),
('Shishou'),
('Shivpuri'),
('Shiyan'),
('Shizuishan'),
('Shizuoka'),
('Shkodër'),
('Shreveport'),
('Shuangcheng'),
('Shuangyashan'),
('Shubra al Khaymah'),
('Shūnan'),
('Shuozhou'),
('Shymkent'),
('Sialkote'),
('Šiauliai'),
('Sibiu'),
('Sibu'),
('Sidi-bel-Abbès'),
('Siegen'),
('Sieverodonetsk'),
('Siirt'),
('Sikar'),
('Sikasso'),
('Silang'),
('Silay'),
('Silchar'),
('Siliguri'),
('Simferopol'),
('Simi Valley'),
('Simões Filho'),
('Sincelejo'),
('Singapore'),
('Singkawang'),
('Singrauli'),
('Sinop'),
('Sinpo'),
('Sinuiji'),
('Sioux Falls'),
('Siping'),
('Sirjan'),
('Sirsa'),
('Sitapur'),
('Sittwe'),
('Sivas'),
('Siverek'),
('Siwan'),
('Skikda'),
('Skopje'),
('Slough'),
('Sloviansk'),
('Słupsk'),
('Smederevo'),
('Smolensk'),
('Soacha'),
('Sobral'),
('Sochi'),
('Sofia'),
('Sogamoso'),
('Sohag'),
('Sohar'),
('Soka'),
('Sokodé'),
('Solapur'),
('Soledad'),
('Solihull'),
('Solingen'),
('Songyuan'),
('Sonipat'),
('Sorocaba'),
('Sorsogon City'),
('Sosnowiec'),
('Soubré'),
('Souk Ahras'),
('South Bend'),
('South Dum Dum'),
('South Tangerang'),
('Southampton'),
('Southend on Sea'),
('Soweto'),
('Soyapango'),
('Spanish Town'),
('Split'),
('Spokane'),
('Springfield'),
('Springs'),
('Sri Jayawardenepura Kotte'),
('Sri Muktsar Sahib'),
('Srikakulam'),
('Srinagar'),
('Ssabagabo'),
('St. Catharines'),
('St. Helens'),
('St. Johns'),
('St. Louis'),
('St. Paul'),
('St. Petersburg'),
('Stakhanov'),
('Stamford'),
('Stara Zagora'),
('Stary Oskol'),
('Stavanger'),
('Stavropol'),
('Sterling Heights'),
('Sterlitamak'),
('Stockholm'),
('Stockport'),
('Stockton'),
('Stoke-on-Trent'),
('Strasbourg'),
('Stuttgart'),
('Subang Jaya'),
('Subic'),
('Subotica'),
('Suceava'),
('Sucre'),
('Suez'),
('Suhaj'),
('Suihua'),
('Suining'),
('Suita'),
('Suizhou'),
('Sujangarh'),
('Sukabumi'),
('Sukkur'),
('Sulamaniya'),
('Sullana'),
('Sultan Pur Majra'),
('Sultanbeyli'),
('Sultanpur'),
('Sumaré'),
('Sumgait'),
('Sumy'),
('Suncheon'),
('Sunchon'),
('Sunderland'),
('Sungai Petani'),
('Sunnyvale'),
('Sunshine Coast'),
('Sunyani'),
('Suqian'),
('Sur'),
('Surabaya'),
('Surakarta'),
('Surat Thani'),
('Surat'),
('Surendranagar Dudhrej'),
('Surgut'),
('Surigao City'),
('Surprise'),
('Surrey'),
('Suryapet'),
('Suwayq'),
('Suwon'),
('Suzano'),
('Suzhou'),
('Suzuka'),
('Swansea'),
('Swindon'),
('Sydney'),
('Syktyvkar'),
('Syracuse'),
('Syzran'),
('Szczecin'),
('Szeged'),
('Taif'),
('Tabaco'),
('Taboão da Serra'),
('Tabriz'),
('Tabuk'),
('Tabuk'),
('Tacheng'),
('Tachikawa'),
('Tacloban'),
('Tacna'),
('Tacoma'),
('Tadepalligudem'),
('Tadipatri'),
('Taganrog'),
('Tagbilaran'),
('Taguig'),
('Tagum'),
('Tahoua'),
('Taian'),
('Taichung'),
('Tainan City'),
('Taipei'),
('Taiping'),
('Taiyuan'),
('Taiz'),
('Taizhou'),
('Taji'),
('Tajimi'),
('Takamatsu'),
('Takaoka'),
('Takarazuka'),
('Takasaki'),
('Takatsuki'),
('Tal Afar'),
('Talavera'),
('Talca'),
('Talcahuano'),
('Taldıqorğan'),
('Talisay'),
('Tallahassee'),
('Tallinn'),
('Taloqan'),
('Tama'),
('Tamale'),
('Tambaram'),
('Tambov'),
('Tampa'),
('Tampere'),
('Tampico'),
('Tanauan'),
('Tanay'),
('Tanchon'),
('Tandil'),
('Tandoadam'),
('Tanga'),
('Tangail'),
('Tangerang'),
('Tangier'),
('Tangshan'),
('Tanjung Pinang'),
('Tanjungbalai'),
('Tanta'),
('Tanza'),
('Taonan'),
('Taourirt'),
('Tapachula'),
('Taranto'),
('Tarapoto'),
('Taraz'),
('Târgu-Mureş'),
('Táriba'),
('Tarija'),
('Tarlac City'),
('Tarnów'),
('Tarragona'),
('Tarsus'),
('Tartus'),
('Tashkent'),
('Tatuí'),
('Taubaté'),
('Taunggyi'),
('Tauranga'),
('Tawau'),
('Taytay'),
('Taza'),
('Tbilisi'),
('Tebessa'),
('Tebing Tinggi'),
('Tecomán'),
('Tegal'),
('Tegucigalpa'),
('Tehran'),
('Tehuacán'),
('Teixeira de Freitas'),
('Tekirdağ'),
('Tel Aviv'),
('Telde'),
('Telford'),
('Tema'),
('Temara'),
('Tembisa'),
('Temecula'),
('Temirtau'),
('Tempe'),
('Temuco'),
('Tenali'),
('Tengzhou'),
('Teófilo Otoni'),
('Tepatitlán'),
('Tepic'),
('Teresina'),
('Teresópolis'),
('Termez'),
('Terni'),
('Ternopil'),
('Terrassa'),
('Tete'),
('Tétouan'),
('Thai Nguyen'),
('Thane'),
('Thanesar'),
('Thanjavur'),
('Thessaloniki'),
('Thiès'),
('Thika'),
('Thimphu'),
('Thiruvananthapuram'),
('Thoothukudi'),
('Thornton'),
('Thousand Oaks'),
('Thrissur'),
('Thunder Bay'),
('Tianjin'),
('Tianmen'),
('Tianshui'),
('Tiaret'),
('Tieli'),
('Tieling'),
('Tijuana'),
('Tikrit'),
('Tilburg'),
('Timişoara'),
('Timon'),
('Tipitapa'),
('Tirana'),
('Tiruchchirappalli'),
('Tiruchirappalli'),
('Tirunelveli'),
('Tirupati'),
('Tiruppur'),
('Tiruvannamalai'),
('Tiruvottiyur'),
('Titagarh'),
('Tizi Ouzou'),
('Tlalnepantla'),
('Tlalpan'),
('Tlaquepaque'),
('Tlaxcala'),
('Tlemoen'),
('Toamasina'),
('Tochigi'),
('Tocuyito'),
('Toda'),
('Tōkai'),
('Tokat'),
('Tokchon'),
('Tokorozawa'),
('Tokushima'),
('Tokuyama'),
('Tokyo'),
('Toledo'),
('Toliara'),
('Toluca'),
('Tolyatti'),
('Tomakomai'),
('Tomsk'),
('Tondabayashi'),
('Tongchuan'),
('Tonghua'),
('Tongi'),
('Tongjiang'),
('Tongliao'),
('Tongling'),
('Tongren'),
('Tonk'),
('Toowoomba'),
('Topeka'),
('Torbat-e Heydarieh'),
('Toride'),
('Toronto'),
('Torrance'),
('Torrejón de Ardoz'),
('Torreón'),
('Toruń'),
('Tottori'),
('Touggourt'),
('Toulon'),
('Toulouse'),
('Tours'),
('Townsville'),
('Toyama'),
('Toyohashi'),
('Toyokawa'),
('Toyonaka'),
('Toyota'),
('Trabzon'),
('Trece Martires'),
('Trento'),
('Três Lagoas'),
('Trier'),
('Trieste'),
('Trindade'),
('Tripoli'),
('Tripoli'),
('Trois-Rivières'),
('Trondheim'),
('Trujillo'),
('Tsu'),
('Tsuchiura'),
('Tsukuba'),
('Tsuruoka'),
('Tsuyama'),
('Tubarão'),
('Tucson'),
('Tucuruí'),
('Tuguegarao'),
('Tula de Allende'),
('Tula'),
('Tulancingo'),
('Tulsa'),
('Tulua'),
('Tulufan'),
('Tumaco'),
('Tumbes'),
('Tumen'),
('Tumkur'),
('Tunis'),
('Tunja'),
('Turbo'),
('Turgutlu'),
('Turhal'),
('Turin'),
('Turkistan'),
('Turkmenabat'),
('Turku'),
('Tuticorin'),
('Tuxpan'),
('Tuxtla Gutiérrez'),
('Tuz Khurmatu'),
('Tuzla'),
('Tver'),
('Tychy'),
('Tyumen'),
('Ubá'),
('Ube'),
('Uberaba'),
('Uberlândia'),
('Ubon Ratchathani'),
('Udaipur'),
('Udgir'),
('Udine'),
('Udon Thani'),
('Udupi'),
('Ueda'),
('Ufa'),
('Uji'),
('Ujjain'),
('Ulaanbaatar'),
('Ulan Hot'),
('Ulanqab'),
('Ulan-Ude'),
('Ulhasnagar'),
('Ulm'),
('Ulsan'),
('Uluberia'),
('Ulyanovsk'),
('Umlazi'),
('Umuarama'),
('Unaizah'),
('Unnao'),
('Uppsala'),
('Urasoe'),
('Urawa'),
('Urayasu'),
('Urdaneta'),
('Urgench'),
('Uribia'),
('Urmia'),
('Uruapan'),
('Uruguaiana'),
('Uruma'),
('Ürümqi'),
('Uşak'),
('Ussuriysk'),
('Utrecht'),
('Utsunomiya'),
('Uttarpara'),
('Uzhhorod'),
('Vacoas-Phoenix'),
('Vadodara'),
('Valdivia'),
('Valencia'),
('Valencia'),
('Valencia'),
('Valenzuela'),
('Valera'),
('Valinhos'),
('Valladolid'),
('Valle de Chalco'),
('Valledupar'),
('Vallejo'),
('Valparaíso de Goiás'),
('Valparaíso'),
('Valsad'),
('Van'),
('Vancouver'),
('Vantaa'),
('Vapi'),
('Varamin'),
('Varanasi'),
('Varginha'),
('Varna'),
('Várzea Grande'),
('Várzea Paulista'),
('Vasai-Virar'),
('Västerås'),
('Vaughan'),
('Veliky Novgorod'),
('Vellore'),
('Venice'),
('Venlo'),
('Veracruz'),
('Veraval'),
('Verona'),
('Vespasiano'),
('Viamão'),
('Vicente López'),
('Vicenza'),
('Victoria'),
('Victorville'),
('Vidisha'),
('Vienna'),
('Vientiane'),
('Vigo'),
('Vihiga'),
('Vijayawada'),
('Vila Nova de Gaia'),
('Vila Velha'),
('Villa Alemana'),
('Villa Nueva'),
('Villahermosa'),
('Villanueva'),
('Villavicencio'),
('Villeurbanne'),
('Vilnius'),
('Viña del Mar'),
('Vinh'),
('Vinnytsia'),
('Viranşehir'),
('Virginia Beach'),
('Visakhapatnam'),
('Visalia'),
('Vitebsk'),
('Vitória da Conquista'),
('Vitória de Santo Antão'),
('Vitória'),
('Vitoria-Gasteiz'),
('Vizianagaram'),
('Vladikavkaz'),
('Vladimir'),
('Vladivostok'),
('Vlorë'),
('Volgodonsk'),
('Volgograd'),
('Vologda'),
('Volos'),
('Volta Redonda'),
('Volzhsky'),
('Voronezh'),
('Vosloorus'),
('Votorantim'),
('Vũng Tàu'),
('Xai-Xai'),
('Xalapa'),
('Xiamen'),
('Xian'),
('Xiangtan'),
('Xiangyang'),
('Xianning'),
('Xiantao'),
('Xianyang'),
('Xiaogan'),
('Xiaoshan'),
('Xichang'),
('Xilinhot'),
('Xingcheng'),
('Xinghua'),
('Xingtai'),
('Xingyi'),
('Xining'),
('Xinji'),
('Xintai'),
('Xinxiang'),
('Xinyang'),
('Xinyi'),
('Xinyu'),
('Xinzhou'),
('Xo‘jayli'),
('Xochimilco'),
('Xuancheng'),
('Xuchang'),
('Yachiyo'),
('Yaizu'),
('Yakeshi'),
('Yakutsk'),
('Yalova'),
('Yamagata'),
('Yamaguchi'),
('Yamato'),
('Yamoussoukro'),
('Yamuna Nagar'),
('Yanan'),
('Yanbu'),
('Yancheng'),
('Yangjiang'),
('Yangon'),
('Yangquan'),
('Yangzhou'),
('Yanji'),
('Yantai'),
('Yao'),
('Yaoundé'),
('Yaroslavl'),
('Yasuj'),
('Yatsushiro'),
('Yavatmal'),
('Yazd'),
('Yekaterinburg'),
('Yelets'),
('Yenakiieve'),
('Yeosu'),
('Yerevan'),
('Yessentuki'),
('Yevpatoria'),
('Yibin'),
('Yichang'),
('Yichun'),
('Yidu'),
('Yima'),
('Yinchuan'),
('Yingcheng'),
('Yingkou'),
('Yingtan'),
('Yining'),
('Yiwu'),
('Yixing'),
('Yiyang'),
('Yizheng'),
('Yogyakarta'),
('Yokkaichi'),
('Yokohama'),
('Yokosuka'),
('Yonago'),
('Yongan'),
('Yongzhou'),
('Yonkers'),
('Yopal'),
('York'),
('Yoshkar-Ola'),
('Yuanjiang'),
('Yueyang'),
('Yulin'),
('Yumen'),
('Yuncheng'),
('Yusufiyah'),
('Yuxi'),
('Yuyao'),
('Yuzhno-Sakhalinsk'),
('Yuzhou'),
('Zaanstad'),
('Zabol'),
('Zabrze'),
('Zacatecas'),
('Zagazig'),
('Zagreb'),
('Zahedan'),
('Zama'),
('Zamboanga City'),
('Zanjan'),
('Zanzibar City'),
('Zaoyang'),
('Zaozhuang'),
('Zapopan'),
('Zaporizhia'),
('Zaragoza'),
('Zaria'),
('Zarqa'),
('Zelenograd'),
('Zenica'),
('Zhalantun'),
('Zhangjiagang'),
('Zhangjiajie'),
('Zhangjiakou'),
('Zhangshu'),
('Zhangye'),
('Zhangzhou'),
('Zhanjiang'),
('Zhaodong'),
('Zhaoqing'),
('Zhaotong'),
('Zheleznodorozhny'),
('Zhengzhou'),
('Zhenjiang'),
('Zhongshan'),
('Zhoukou'),
('Zhoushan'),
('Zhucheng'),
('Zhuhai'),
('Zhuji'),
('Zhukovsky'),
('Zhumadian'),
('Zhuozhou'),
('Zhuzhou'),
('Zhytomyr'),
('Zibo'),
('Zielona Góra'),
('Zigong'),
('Ziguinchor'),
('Zihuatanejo'),
('Zinder'),
('Zipaquirá'),
('Zixing'),
('Zlatoust'),
('Zoetermeer'),
('Zonguldak'),
('Zrenjanin'),
('Zunyi'),
('Zürich'),
('Zuwarah'),
('Zwolle'),
('Waco'),
('Wad Madani'),
('Wafangdian'),
('Wah Cantonment'),
('Wakayama'),
('Wałbrzych'),
('Wanica'),
('Wanzhou District'),
('Warangal'),
('Wardha'),
('Warren'),
('Warrington'),
('Warsaw'),
('Washington'),
('Waterbury'),
('Wau'),
('Weifang'),
('Weihai'),
('Weihui'),
('Weinan'),
('Wellington'),
('Wendeng'),
('Wenzhou'),
('West Bromwich'),
('West Covina'),
('West Jordan'),
('West Valley City'),
('Westland'),
('Westminster'),
('Whitby'),
('Wichita Falls'),
('Wichita'),
('Wiesbaden'),
('Willemstad'),
('Wilmington'),
('Windhoek'),
('Windsor'),
('Winnipeg'),
('Winston-Salem'),
('Winterthur'),
('Włocławek'),
('Wolfsburg'),
('Wollongong'),
('Wolverhampton'),
('Wonju'),
('Wonsan'),
('Worcester'),
('Wrocław'),
('Wuan'),
('Wuhai'),
('Wuhan'),
('Wuhu'),
('Wuppertal'),
('Würzburg'),
('Wuwei'),
('Wuxi'),
('Wuxue'),
('Wuyishan'),
('Wuzhong'),
('Wuzhou');